### ISSUE TITLE
option to disable unreachable code hints

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pylance-release#1775] opened 2021-09-03 23:59 UTC
there are many problems with pyright's unreachable code detection. see https://github.com/microsoft/pyright/issues/1951, https://github.com/microsoft/pyright/issues/2231, https://github.com/microsoft/pyright/issues/1531, https://github.com/microsoft/pyright/issues/2258

it would be nice to have an option to disable unreachable code warnings. especially since my project already uses mypy to detect unreachable code anyway.

**Comment by erictraut** [comment] 2021-09-07 17:31
Pyright never issues warnings or errors for unreachable code, so there's really nothing to disable here.

The LSP standard supports a special type of optional "hint" that can be used to indicate that a text range should be displayed in a "grayed out" manner. Pyright does use this hint if the client claims to support it. The problem is that some clients interpret this hint incorrectly and display these hints as a regular diagnostic. If these clients don't properly support these hints, they should either ignore them or not request them in the first place.

**Comment by jakebailey** [comment] 2021-09-07 17:32
Judging by the issue history here, I believe they are using VS Code, though potentially not Pylance.

**Comment by erictraut** [comment] 2021-09-07 17:34
@DetachHead, perhaps I misinterpreted your request then. Could you provide an example of where you are seeing a warning or error diagnostic for unreachable code?

**Comment by DetachHead** [comment] 2021-09-08 02:00
@erictraut the error level (info, warning, error, etc.) isn't really relevant to the problem here imo. the issue is that the "hint" or whatever it's called is incorrect in many cases.

it'd be like saying a hint like this from the editor isn't a problem simply because it's not a warning:
![image](https://user-images.githubusercontent.com/57028336/132424295-fb503744-1210-4081-a167-7c957b3ba0d4.png)
(note: this is a fake screenshot)

like, not only is that not correct but it's also probably the lsp causing it and not the editor.

so in this case, this check implies that it's possible for both branches of the statement to run. why would i write a check like this otherwise? if there's no way to tell the editor that there's more than one supported python version such that neither of these branches are reported as unreachable, i would like an option to disable these hints entirely.
```py
if sys.version_info < (3, 8):
    print("🧓")
elif sys.version_info == (3,10):
    print("✔")
```

and in this case, the hint is obviously 100% incorrect. even though it's obviously doing this because of the type checker, it should have logic to not report this hint on the `TYPE_CHECKING` variable. if that's not possible/feasible, i would like an option to disable these hints entirely.
![image](https://user-images.githubusercontent.com/57028336/132433189-c92e0cc6-14ab-4cb6-bdd0-00e85b47860d.png)

**Comment by erictraut** [comment] 2021-09-08 02:31
OK, thanks for the explanation.

From the perspective of the code analyzer, this code _is unreachable_, and it does not impact the code analysis. So in that sense, it is not incorrect to indicate that the code is unreachable. The question is whether it's useful to report this to the programmer. I'd argue that it is, but others may see it differently.

Consider the following code:
```python
if sys.version_info < (3, 10):
    foo = None
else:
    foo = "hi"

print(foo.capitalize())
```

If you run this code in Python 3.9, it will crash, but in Python 3.10, it will run without error. Pylance will correctly report the bug if you have a Python 3.9 interpreter selected but will not show any errors if you have a Python 3.10 interpreter selected. That's because the statement `foo = None` is unreachable if you are running in Python 3.10. I find it's important to understand what code is considered reachable in different modes.

When you hover over the grayed-out text, you currently see the text "Code is unreachable". Perhaps you would find the grayed-out text less objectionable and less confusing if we changed that text to say something like "Code is unreachable when run in the selected Python interpreter"? Or is it the presence of the grayed-out text that bothers you?

**Comment by DetachHead** [comment] 2021-09-08 03:00
i see your point now. i would suggest changing the text to something like "Code is not type-checked" however, since that will also make sense for the `if not TYPE_CHECKING` scenario as well

**Comment by MetRonnie** [comment] 2022-03-22 11:40
I had a function with a annotated return type of `typing.NoReturn` (it calls `sys.exit()`). In a unit test, `sys.exit()` was mocked/patched, but Pylance still claimed everything after the function call was unreachable, leading to it being greyed out in VSCode, annoyingly. One solution I found was to defer the import to the test function, with a type annotation beforehand to override the real one. I.e.
```python
# foo/bar.py
def myfunc() -> NoReturn:
    ...
    sys.exit()
```
```python
# tests/test_bar.py
def test_myfunc():
    myfunc: Callable
    from foo.bar import myfunc
    ...
```

**Comment by judej** [comment] 2022-04-20 17:51
Moving this issue to discussion as an enhancement request for comments and upvotes.

**Closed as completed** 2022-04-20 17:52 UTC
Labels: enhancement
