### ISSUE TITLE
Getting a valid, but false Error, Import "Example.R1" could not be resolved error

### ISSUE THREAD

**Issue by sean-galloway** [microsoft/pylance-release#1842] opened 2021-09-20 14:47 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.9.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

No Error

<h3> Actual behaviour </h3>

Reporting: Import "Example.R1" could not be resolved

Note: The import is needed for some environments, but not others. So, I've wrapped it in a try block.

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

try:
    import Example.R1
except ImportError:
    print("Example.R1 is not needed")

```python
XXX
```

**Comment by jakebailey** [comment] 2021-09-20 17:11
Duplicate of #32.

**Closed by jakebailey** 2021-09-20 17:11 UTC
Labels: triage

**Comment by sean-galloway** [comment] 2021-09-20 17:28
I'm so sorry about the duplicate. Thank you so much for the quick pointer to a workable solution.
