### ISSUE TITLE
Enable the pylint expansion, the intelligent prompt is invalidated

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/pylance-release#5109] opened 2023-11-10 08:31 UTC
As shown in the title, when I enabled Pylint, the window prompt error will appear, and the intelligent prompt will fail. After restarting VSCODE, everything returned to normal.

![image](https://github.com/microsoft/vscode-python/assets/108051416/be5629a5-2dff-49f0-9f89-1fbba393c2e8)

**Go to output:**

```
2023-11-10 16:16:08.244 [info] [Error - 4:16:08 PM] Server process exited with code 1.
2023-11-10 16:16:08.244 [info] [Error - 4:16:08 PM] Connection to server got closed. Server will not be restarted.
2023-11-10 16:16:08.245 [info] [Error - 4:16:08 PM] Handling connection close failed
2023-11-10 16:16:08.245 [info] TypeError: e.clear is not a function
    at _.cleanUp (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2412859)
    at _.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2417283)
    at _.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2578252)
    at c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2416709
    at o.invoke (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
    at s.fire (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
    at te (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2349784)
    at o.invoke (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
    at s.fire (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
    at d.fireClose (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2372012)
    at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2384364)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

A simple example:

![222](https://github.com/microsoft/vscode-python/assets/108051416/de3db8e6-30ad-4d45-9dfc-c9d4ef041b34)

```
Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by rchiodo** [comment] 2023-11-13 17:55
This is a dupe of https://github.com/microsoft/pylance-release/issues/5086 which is fixed in our latest prerelease version.

**Comment by rchiodo** [comment] 2023-11-13 17:56
It should only happen when restarting the Pylance language server. Restarting VS code would make the problem go away.

**Closed by rchiodo** 2023-11-13 17:55 UTC
Labels: needs repro

**Comment by sanglist** [comment] 2024-12-05 14:13
Having the same issue:
Tried all combinations, pylance (disable, restart) * pylint (disable, restart)  * vscode (open, close)
Usually a restart of vscode helps
