### ISSUE TITLE
Pressing X on pylance has crashed notification should be treated as a `No`

### ISSUE THREAD

**Issue by lramos15** [microsoft/pylance-release#6156] opened 2024-07-17 19:55 UTC
1. Crash your pylance 🎉 
2. See the notification that asks you if you want to spawn it as a node process instead
3. Click X
4. 🐛 Notification reappears.

This is a bit of UX smell in my opinion as I clicked X to get it out of the way so I could focus on my work and it kept popping back up. This is a different behavior than most notifications in VS Code.

**Comment by rchiodo** [comment] 2024-07-17 21:29
Thanks for the issue.

That's a bug in this logic here:
https://github.com/microsoft/pyrx/blob/6cbd08616443676ee9b0496952ab445e287ce4c6/packages/vscode-pylance/src/extension.ts#L132

The loop there was intended to keep the dialog up if the user clicked the help button, but not if they clicked the X.

**Comment by heejaechang** [comment] 2024-07-24 20:48
This issue has been fixed in prerelease version 2024.7.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20247102-24-July-2024-PreRelease)

**Closed by heejaechang** 2024-07-24 20:48 UTC
Labels: bug, fixed in next version (release)
