### ISSUE TITLE
Missing import:  redistimeseries

### ISSUE THREAD

**Issue by owentechnologist** [microsoft/pylance-release#1452] opened 2021-06-15 18:51 UTC
When adding redistimeseries: 

https://github.com/RedisTimeSeries/redistimeseries-py

to my macosx environment using:

bash-3.2$ python3 -m pip install redistimeseries

Requirement already satisfied: redistimeseries in /usr/local/lib/python3.9/site-packages (1.4.3)
Requirement already satisfied: rmtest>=0.2 in /usr/local/lib/python3.9/site-packages (from redistimeseries) (0.7.0)
Requirement already satisfied: hiredis>=0.2.0 in /usr/local/lib/python3.9/site-packages (from redistimeseries) (0.3.1)
Requirement already satisfied: redis>=2.10 in /usr/local/lib/python3.9/site-packages (from redistimeseries) (3.0.1)

**Pylance reports:**

"redistimeseries" is not accessedPylance"
Import "redistimeseries" could not be resolved Pylancereport MissingImports

**Comment by jakebailey** [comment] 2021-06-15 18:52
Does it work if you restart the language server (there's a command for it) or reload the editor? If so, this is a duplicate of #923, as you are installing the package outside of the workspace.

**Comment by owentechnologist** [comment] 2021-06-17 16:04
Thanks for the response Jake.  Unfortunately, restarting the editor does not alter the failed state.  I also tried:  Python: Restart Language Server from the Command Palette.

Neither effort resolves this issue.

Any further ideas?

Thanks,

Owen

**Comment by jakebailey** [comment] 2021-06-17 16:59
Can you please provide some trace logs? I'd like to see what your search paths are.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by owentechnologist** [comment] 2021-06-17 17:42
Fixed:
 
* created a new project in VS code
* copied the source files into it using the file system
* specified the latest release of python available on my system (Python 3.9.5)
View|Command Palette|Python Select Interpreter

and the import works.

**Comment by jakebailey** [comment] 2021-06-17 19:56
Alright, with that I do think that there may have been something wrong with the original setup, and the wrong interpreter was being used. If you still get this issue and can provide logs we can look at them, but it does seem like you've fixed the problem.

**Closed by jakebailey** 2021-06-17 19:56 UTC
Labels: waiting for user response
