### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KikeVen** [microsoft/pylance-release#1051] opened 2021-03-13 22:41 UTC
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.2.633441544`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 4030,
		"activateCallTime": 216,
		"activateResolvedTime": 4055,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-python.vscode-pylance",
				"_lower": "ms-python.vscode-pylance"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Webview is disposed"
		}
	]
}
```

**Comment by judej** [comment] 2021-03-15 18:04
Thanks for the report. This is a dupe of #963

**Closed by judej** 2021-03-15 18:04 UTC
Labels: duplicate, triage
