### ISSUE TITLE
Internal error while type checking

### ISSUE THREAD

**Issue by goruck** [microsoft/pylance-release#1219] opened 2021-05-02 02:25 UTC
## Environment data

-   Language Server version: v2021.4.3
-   OS and version: Ubuntu 20.04.2 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

No internal error while type checking. 

## Actual behaviour

An internal error occurred while type checking file "/home/lindo/Develop/radar-ml/sgan.py": Error: Debug Failure. False expression.
    at a.lock (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeVarMap.ts:238:9)
    at validateFunctionArgumentTypes (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8080:24)
    at callback (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:6349:28)
    at useSpeculativeMode (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17893:20)
    at validateOverloadsWithExpandedTypes (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:6347:17)
    at validateOverloadedFunctionArguments (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:6421:32)
    at callback (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7042:48)
    at expandSubtype (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3310:41)
    at mapSubtypesExpandTypeVars (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3326:13)
    at ft (/home/lindo/.vscode-server/extensions/ms-python.vscode-pylance-2021.4.3/dist/pyright-internal/src/analyzer/typeEvaluator.ts:6960:28)

## Logs

```
See problem message above from Visual Studio Code. 
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment] 2021-05-02 02:55
Thanks for the bug report. This appears to be a duplicate of https://github.com/microsoft/pylance-release/issues/1218, which I've already fixed.

**Comment by jakebailey** [comment] 2021-05-05 23:04
This issue has been fixed in version 2021.5.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202150-5-may-2021

**Closed by jakebailey** 2021-05-05 23:04 UTC
Labels: bug, fixed in next version
