### ISSUE TITLE
Cannot read property 'onDidOpenNotebookDocument' of undefined

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/pylance-release#1387] opened 2021-06-03 08:45 UTC
# Environment data

-   Language Server version: 2021.6.0
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

# Expected behaviour

no errors, the language server works

# Actual behaviour

it doesn't work

# Logs

```
Error 2021-06-03 10:45:07: Failed to restart language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/home/adrian/.vscode-server-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:78:180756)
	at new a (/home/adrian/.vscode-server-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (/home/adrian/.vscode-server-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:178815)
	at new y (/home/adrian/.vscode-server-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:446239)
	at r.startLanguageServer (/home/adrian/.vscode-server-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:240168)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
```

**Comment by judej** [comment] 2021-06-03 17:51
This a dupe of https://github.com/microsoft/vscode-jupyter/issues/6108. See comment https://github.com/microsoft/vscode-jupyter/issues/6101#issuecomment-854043224

**Closed by judej** 2021-06-03 17:51 UTC
Labels: triage

**Comment by joyceerhl** [comment] 2021-06-04 03:53
This has been resolved. https://github.com/microsoft/vscode-python/suites/2904962837/artifacts/65133411 should contain the fix if you'd like to try it out now (you should get the same build if you're opted into daily insiders builds for the Python extension).
