### ISSUE TITLE
UndefinedVariable in interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/pylance-release#3661] opened 2022-11-22 01:36 UTC
## Environment data

-   Language Server version: v2022.11.30
-   OS and version: macos 13
-   Python version (& distribution if applicable, e.g. Anaconda): conda python 3.9.12

Pylance keep showing me UndefinedVariable error in the interactive window no matter what I do

![CS-uREImsfs](https://user-images.githubusercontent.com/33796896/203194864-2f17af6e-9967-40f0-882b-aff3e55a4433.png)
![CS-CFWlmlxf](https://user-images.githubusercontent.com/33796896/203195247-424689b9-44d6-42bc-89f3-ab763163d494.png)

**Comment by debonte** [comment] 2022-11-22 20:54
@StevenLi-DS, can you please provide the content of your "Python Language Server" log from VS Code's output pane?

**Comment by StevenLi-DS** [comment] 2022-11-22 21:05
@debonte hope this gotta be helpful
[pylance-log.log](https://github.com/microsoft/pylance-release/files/10071061/pylance-log.log)

**Comment by debonte** [comment] 2022-11-22 21:32
Are you sure the diagnostic is `reportUndefinedVariable`? What I'm seeing is `reportUnusedExpression`.

If that's what you're seeing also, this is a duplicate of #3282 which was fixed in our most recent prerelease build, 2022.11.31.

**Comment by StevenLi-DS** [comment] 2022-11-22 22:52
This is what it's telling me as shown in the screenshot above as well.

![CS-AECGHYhQ](https://user-images.githubusercontent.com/33796896/203437401-19c0e561-b0c9-48d6-915a-2174b62b7b10.png)

**Comment by debonte** [comment] 2022-11-23 00:37
I was able to repro this by downgrading my Jupyter extension to their current Release version. Can you try upgrading to the latest Pre-Release build of Jupyter? They had a regression earlier this month that caused them to start a second instance of Pylance, and I think the error you are seeing may be coming from that second instance.

That would also explain the multiple lines of type info for `df` seen in your first screenshot.

If you see a log like the following in the Output window in addition to the "Python Language Server" log, that would also indicate that you're hitting this.

![image](https://user-images.githubusercontent.com/12820898/203448277-96e9f4a2-8d6b-4a03-8076-e8eb35e735a8.png)

**Comment by StevenLi-DS** [comment] 2022-11-23 01:18
@debonte Thanks man. Indeed, after I switch to pre-release `v2022.11.1003281132` Jupyter extension, the problem is gone. Maybe Jupyter extension version should also be included in the bug report template. lol..

**Comment by debonte** [comment] 2022-11-23 01:25
Duplicate of https://github.com/microsoft/pylance-release/issues/3530

**Closed by debonte** 2022-11-23 01:25 UTC
Labels: external bug

**Comment by StevenLi-DS** [comment] 2023-02-08 01:07
@debonte The issue seems back in v2023.2.10
<img width="390" alt="CS-hJWqB1zb@2x" src="https://user-images.githubusercontent.com/33796896/217402503-bb4203a5-ff0e-4ab3-8fb4-81014e4edcaf.png">

**Comment by debonte** [comment] 2023-02-10 20:09
@StevenLi-DS, thanks for reporting this. I haven't been able to repro the issue yet though. Can you open a new issue with steps to reproduce the problem? Might as well include your Jupyter extension version too. :)
