### ISSUE TITLE
Issue resolving parameters for pywin32 function even with type shed

### ISSUE THREAD

**Issue by MorselHoarder** [microsoft/pylance-release#6383] opened 2024-09-12 15:20 UTC
<h3> Environment data </h3>

-   Language Server version: 2024.9.1
-   OS and version: win32 x64
-   Python version: 3.11.9
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

Pylance cannot resolve any parameters to `win32gui.GetSaveFileNameW` while type checking is on. Here's an example error:
>No parameter named "InitialDir" Pylance(reportCallIssue)

The following snippet is taken from the pywin32 demo file [GetSaveFileName.py](https://github.com/mhammond/pywin32/blob/main/win32/Demos/GetSaveFileName.py)
```python
import os

import win32con
import win32gui

filter = "Python Scripts\0*.py;*.pyw;*.pys\0Text files\0*.txt\0"
customfilter = "Other file types\0*.*\0"

fname, customfilter, flags = win32gui.GetSaveFileNameW(  # All parameters to this function will be marked with a reportCallIssue error
    InitialDir=os.environ["temp"],
    Flags=win32con.OFN_ALLOWMULTISELECT | win32con.OFN_EXPLORER,
    File="somefilename",
    DefExt="py",
    Title="GetSaveFileNameW",
    Filter=filter,
    CustomFilter=customfilter,
    FilterIndex=1,
)
```

<h3> Repro Steps </h3>

1. Create a new empty profile in VSCode.
2. Install the Python extension.
3. Create a new project folder (i.e. C:\Users\MyUser\Test-Pylance).
4. Create a new virtual environment in project folder: `python -m venv venv`
5. Activate the virtual environment and install pywin32: `pip install pywin32`
6. In the project root, create `main.py` and paste the code from [this demo file](https://github.com/mhammond/pywin32/blob/main/win32/Demos/GetSaveFileName.py).
7. In User settings, set `python.analysis.typeCheckingMode` to `basic`. 

<h3> Expected behavior </h3>

There shouldn't be any parameter warnings.

<h3> Actual behavior </h3>

All parameters are marked as not found. If you go to the definition of `GetSaveFileNameW`, the type shed fallback contains a stub for this function. The other function in the demo doesn't have this issue for some reason.

I've tried:
- Adding the stub files manually to `python.analysis.typeshedPaths`.
- Using the global interpreter instead of venv.
- Pip installing `types-pywin32`.

<h3> Logs </h3>

```
2024-09-12 11:03:01.063 [info] (332) [BG(1)] SemanticTokens full at file:///c%3A/Users/schult/Test-Pylance/main.py (1ms)
2024-09-12 11:03:01.280 [info] (332) [BG(1)] indexing: file:///c%3A/Users/schult/Test-Pylance/main.py [found 4] (0ms)
2024-09-12 11:03:01.280 [info] (332) Indexing Done: file:///c%3A/Users/schult/Test-Pylance/main.py
2024-09-12 11:03:01.280 [info] [Info  - 11:03:01 AM] (332) Heap stats: total_memory_size=32466MB, total_free_size=15978MB, total_heap_size=63MB, used_heap_size=59MB, cross_worker_used_heap_size=59MB, total_physical_size=63MB, total_available_size=4035MB, heap_size_limit=4096MB
2024-09-12 11:03:22.308 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (10ms)
2024-09-12 11:03:22.312 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/typing.pyi (4ms)
2024-09-12 11:03:22.322 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 1ms] (7ms)
2024-09-12 11:03:22.324 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/types.pyi (2ms)
2024-09-12 11:03:22.330 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (4ms)
2024-09-12 11:03:22.330 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2024-09-12 11:03:22.333 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (2ms)
2024-09-12 11:03:22.334 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
2024-09-12 11:03:22.335 [info] (332) [FG] parsing: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32gui-stubs/__init__.pyi [fs read 0ms] (1ms)
2024-09-12 11:03:22.342 [info] (332) [FG] binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32gui-stubs/__init__.pyi ...
2024-09-12 11:03:22.343 [info] (332) [FG]   parsing: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32-stubs/win32gui.pyi [fs read 0ms] (6ms)
2024-09-12 11:03:22.345 [info] (332) [FG]   binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32-stubs/win32gui.pyi (3ms)
2024-09-12 11:03:22.345 [info] (332) [FG] binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32gui-stubs/__init__.pyi (9ms)
2024-09-12 11:03:22.349 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (3ms)
2024-09-12 11:03:22.350 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (1ms)
2024-09-12 11:03:22.374 [info] (332) [FG] parsing: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/_win32typing-stubs/__init__.pyi [fs read 1ms] (24ms)
2024-09-12 11:03:22.411 [info] (332) [FG] binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/_win32typing-stubs/__init__.pyi (36ms)
2024-09-12 11:03:22.418 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/os/__init__.pyi [fs read 0ms] (6ms)
2024-09-12 11:03:22.423 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/os/__init__.pyi (5ms)
2024-09-12 11:03:22.424 [info] (332) [FG] parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/collections/abc.pyi [fs read 0ms] (0ms)
2024-09-12 11:03:22.424 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/collections/abc.pyi ...
2024-09-12 11:03:22.425 [info] (332) [FG]   parsing: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi [fs read 0ms] (1ms)
2024-09-12 11:03:22.425 [info] (332) [FG]   binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi (0ms)
2024-09-12 11:03:22.425 [info] (332) [FG] binding: file:///c%3A/Users/schult/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/typeshed-fallback/stdlib/collections/abc.pyi (1ms)
2024-09-12 11:03:22.426 [info] (332) [FG] parsing: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32con-stubs/__init__.pyi [fs read 0ms] (1ms)
2024-09-12 11:03:22.438 [info] (332) [FG] binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32con-stubs/__init__.pyi ...
2024-09-12 11:03:22.438 [info] (332) [FG]   parsing: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32-stubs/lib/win32con.pyi [fs read 0ms] (11ms)
2024-09-12 11:03:22.453 [info] (332) [FG]   binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32-stubs/lib/win32con.pyi (16ms)
2024-09-12 11:03:22.455 [info] (332) [FG] binding: file:///c%3A/Users/schult/Test-Pylance/venv/Lib/site-packages/win32con-stubs/__init__.pyi (28ms)
```

**Comment by rchiodo** [comment] 2024-09-12 16:23
Thanks for the issue, I can reproduce it. Not sure why the parameters are marked that way because the stub has those parameters in it.

![Image](https://github.com/user-attachments/assets/896c802b-1737-4655-9156-cb9ee97adfab)

**Comment by rchiodo** [comment] 2024-09-12 17:17
Ah I figured out why the problem is happening. That function is marked as positional only parameters, not keyword parameters. Might be a bug in the typeshed. Here's the definition:

```python
def GetSaveFileNameW(
    hwndOwner: int | None = ...,
    hInstance: int | None = ...,
    Filter: Incomplete | None = ...,
    CustomFilter: Incomplete | None = ...,
    FilterIndex: int = ...,
    File: Incomplete | None = ...,
    MaxFile: int = ...,
    InitialDir: Incomplete | None = ...,
    Title: Incomplete | None = ...,
    Flags: int = ...,
    DefExt: Incomplete | None = ...,
    TemplateName: _win32typing.PyResourceId | None = ...,
    /, <-- This value here marks all the previous params as position only. Removing this gets rid of the errors.
) -> tuple[Incomplete, Incomplete, Incomplete]: ...
```

You could submit an issue to typeshed for them to resolve.

The original commit looks like it might have been too aggressive (or put the / in the wrong spot).
https://github.com/python/typeshed/commit/0b8841edd8009b7a19ad1038c17e5dbb649ac60f

**Closed by rchiodo** 2024-09-12 17:17 UTC
Labels: bug

**Comment by MorselHoarder** [comment] 2024-09-12 17:47
Oh wow, good find. I'll open an issue with the typeshed.

Thank you for your help and for being so responsive! 🙂
