### ISSUE TITLE
No semantic highlighting for magic variables

### ISSUE THREAD

**Issue by Antyos** [microsoft/pylance-release#1771] opened 2021-09-06 17:11 UTC
## Environment data

-   Language Server version: 2021.9.0
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Expected behaviour

I am currently working on a color theme with semantic highlighting. Magic variables, such as `__name__` should be cyan.

![image](https://user-images.githubusercontent.com/17516195/132247647-9ac9b43d-19cc-4d0a-96d9-1288604360f0.png)

## Actual behaviour

Magic variables, such as `__name__`, are highlighted red. Because semantic highlighting takes precedence over TextMate scopes, there does not seem to be any way to force magic variables to be a different color. 

![image](https://user-images.githubusercontent.com/17516195/132247718-dc10e6c5-8f13-4589-a8ce-7b4778d1a0e1.png)

It does not appear that magic variables have a semantic highlighting scope. Perhaps a new scope, `magicVariable`, could be added to go with the `magicFunction` scope.

## Logs

```
XXX
```

**Comment by jakebailey** [comment] 2021-09-06 17:16
Duplicate of #964.

**Closed by jakebailey** 2021-09-06 17:16 UTC
Labels: triage
