### ISSUE TITLE
Pylance fails in v2023.18.0

### ISSUE THREAD

**Issue by sniafas** [microsoft/pylance-release#4943] opened 2023-10-10 10:45 UTC
## Environment data

-   Language Server version: v2023.18.0
-   OS and version: PopOS 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8 via poetry

## Description

Latest version of pylance fails to show the `Go to` command  `definition|type definition|References` when right-click on a Python variable in VSCodium 1.82.2

Falling back to v2023.16.0 works fine.

**Comment by debonte** [comment] 2023-10-10 13:38
Dupe of https://github.com/microsoft/pylance-release/issues/4747

Pylance only works in official builds of VS Code.

If using an official build isn't an option, you could try using Pyright instead. It doesn't have as many features as Pylance, but it works in any editor that supports LSP.

**Closed by debonte** 2023-10-10 13:38 UTC
Labels: needs repro
