### ISSUE TITLE
Autocomplete should be less aggressive about suggesting function definitions

### ISSUE THREAD

**Issue by tuchandra** [microsoft/pylance-release#629] opened 2020-11-19 19:19 UTC
## Environment data
-   Language Server version: 2020.11.2
-   OS and version: MacOS 10.15.3 Catalina
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.6, miniconda

## Expected behaviour
Code completion should be less aggressive about suggesting function definitions.

Some examples:
 - typing `from torch.utils.data import Data` should suggest at the top the two items that begin with `Data`, `DataLoader` and `DataSet`
 - typing `from torch.utils.data import DataLoad` should suggest at the top the one item that begins with that, `DataLoader`
 - typing `from datetime import d` should suggest closer to the top the items that begin with `d`, `date` and `datetime`
 - typing `from datetime import date` should suggest at the top the items that begin with `date`, `date` and `datetime` 

## Actual behaviour
The suggestions from Pylance autocomplete place what I think is way too high of a priority on fuzzy matches. The first few options are usually some combination of `def`, `def(class method)`, `def(abstract class method)` and `def(static class method)`.

![image](https://user-images.githubusercontent.com/11623486/99711228-2672fc00-2a67-11eb-8faa-971e195d6c1c.png)

![image](https://user-images.githubusercontent.com/11623486/99711458-6934d400-2a67-11eb-9352-d3dc5e2c364c.png)

![image](https://user-images.githubusercontent.com/11623486/99712405-9e8df180-2a68-11eb-8bab-3813f6bb1a96.png)

![image](https://user-images.githubusercontent.com/11623486/99712615-ee6cb880-2a68-11eb-8e17-b56907b7e0ee.png)

These suggestions in particular don't really make any sense in the context of imports—they'd all be syntax errors—but I am not sure if this problem is limited to imports.

## Logs
There don't appear to be any here.

## Code Snippet / Additional information
Code snippets are above. I don't know if this is a design decision or an actual bug, but it *feels* apparent to me that the exact matches should be listed at the top. I don't believe this has been filed before; I searched for 'autocomplete', 'completion', and 'suggestions' but didn't see a relevant issue. I apologize if it has.

Thank you for your great work on Pylance. It's incredible how well it works day-to-day. I really appreciate it.

**Comment by jakebailey** [comment] 2020-11-19 19:29
This behavior changed once we stopped offering completions in these contexts (as we can't know what you want to name a new import alias). VS Code has taken over and started offering snippets and word suggestions.

These snippets come from the Python extension. They rely on regex matching to guess as to what context they should be offered in, and IMO don't work so well. Personally I recommend disabling them altogether:

```json
"[python]": {
    "editor.snippetSuggestions": "none"
}
```

Or just for every language (what I do):

```json
"editor.snippetSuggestions": "none"
```

Once these are disabled, you may get word suggestions too, and there's info in #604 for that.

I'm going to close this as a dupe of #604 as I believe the fix for that will also fix this issue (offering up a single completion that's what you typed so VS Code stops trying to be clever).

**Closed by jakebailey** 2020-11-19 19:29 UTC
Labels: triage

**Comment by jakebailey** [comment] 2020-11-19 19:53
Filed microsoft/vscode-python#14781.

**Comment by tuchandra** [comment] 2020-11-19 20:07
Thanks for the quick response. That all makes sense; I didn't realize it was upstream now. I appreciate the help.
