### ISSUE TITLE
Reopen: Backslash escape for underscores in Markdown docstrings

### ISSUE THREAD

**Issue by brian316** [microsoft/pylance-release#886] opened 2021-01-27 01:12 UTC
This is a duplicate issue and I want to reopen it because the issue is not fixed even though it was closed.
view the original [issue](https://github.com/Microsoft/vscode-python/issues/911)

## Environment 
- vscode version: 1.51.1
- python ext version: v2021.1.502429796

## Actual behavior
```python
- get\_tag - (str) default=None.
```

## Expected Behavior
```python
- get_tag - (str) default=None.
```

## Steps to reproduce
```python
def myfunc(element: tuple):
    """
    myfunc definition
         - by - (By) html type for value e.g class, id, xpath...
         - value - (str) unique identifier for element
         - get_tag - (str) default=None. 
         - timeout - (int) default=5. 
    """
    pass
```

**Comment by jakebailey** [comment] 2021-01-27 19:20
Duplicate of #805

**Closed by jakebailey** 2021-01-27 19:20 UTC
Labels: triage
