### ISSUE TITLE
rename symbol not working

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/pylance-release#3998] opened 2023-02-23 07:23 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

in a code cell with valid code contents, right click to select `rename symbol`. It should work (as expected and as before), but now it says `The element can't be renamed.`. Copying the same code to a new (unsaved) file, the renaming works as expected.

(p.s. what's not working is not limited to `rename symbol`, e.g. `editor.action.smartSelected.grow`. It feels a subset of features is not working.)

### VS Code Version

1.75.1

### Jupyter Extension Version

2023.1.2010391206

### Jupyter logs

```shell
(nothing happens there)
```

### Coding Language and Runtime Version

python 3.9.12

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2023-02-23 19:41
Do you have a gif of it not working? It might be the language of the cell is wrong.

This works fine for me:
![rename](https://user-images.githubusercontent.com/19672699/221012898-3871595e-73e8-458c-9a3e-3eb0aa5b0e31.gif)

**Comment by rchiodo** [comment] 2023-02-23 19:42
Language of cell is set here:
![image](https://user-images.githubusercontent.com/19672699/221013120-93109a28-0fc9-4edc-a2b2-6b39a142005e.png)

**Comment by debonte** [comment] 2023-02-23 19:44
I'm curious to know if the behavior is different in new (i.e. unsaved) notebooks vs. notebooks that have been saved.

**Comment by yuuuxt** [comment] 2023-02-24 01:55
> Do you have a gif of it not working? It might be the language of the cell is wrong.

I find something useful: it works on a notebook saved on local drive, but doesn't work on a notebook saved on remote (notice the file path on the left side; remote notebook hasn't been connected to any kernel yet, though that doesn't make a difference ):
![temp2](https://user-images.githubusercontent.com/3153534/221072484-a369f185-e1ba-4ecc-a22a-a0b105d804a7.gif)


> I'm curious to know if the behavior is different in new (i.e. unsaved) notebooks vs. notebooks that have been saved.

I haven't checked that - I don't know how to turn a "new file" into an unsaved notebook.

**Comment by debonte** [comment] 2023-02-24 18:34
> I haven't checked that - I don't know how to turn a "new file" into an unsaved notebook.

When you execute the `Create: New Jupyter Notebook` command you'll get a file named something like `Untitled-1.ipynb`. This is not saved on disk. Pylance treats unsaved files differently from saved files, or at least differently from files saved within your workspace directory.

This is probably a dupe of https://github.com/microsoft/pylance-release/issues/3279.

@rchiodo, I'm able to repro this with both unsaved notebooks and locally saved notebooks.

**Comment by rchiodo** [comment] 2023-02-24 18:38
Do you mean with remote?

**Comment by debonte** [comment] 2023-02-24 18:45
> This is probably a dupe of #3279.

I'm embarrassed that I've been sitting on this for so long. I'll look at this as next.

**Comment by heejaechang** [comment] 2023-02-24 21:47
I think for the case it wasn't allowed to be renamed, I think we think those virtual cell files are not user files.

(this)[https://github.com/microsoft/pyrx/blob/main/packages/pylance-internal/src/server.ts#L450] might not working as expected for remote file.

**Comment by debonte** [comment] 2023-03-16 21:35
@yuuuxt, I was able to reproduce this issue a few days ago, but I'm not able to reproduce it with our latest prerelease build ([2023.3.22](https://github.com/microsoft/pylance-release/releases/tag/2023.3.22)).

Can you try upgrading to that build and see if it fixes the issue for you?

**Comment by yuuuxt** [comment] 2023-03-17 02:08
I checked 2 projects, one is working now, the other is not. 

![image](https://user-images.githubusercontent.com/3153534/225793492-0bb9a836-ae15-4494-a150-1c73e2f8ff0f.png)

The file is "also_remote.ipynb", which appeared in my previous reply.

I'm not going to show the working one, but what's strange is that the working one is also in a remote drive.

**Comment by debonte** [comment] 2023-03-24 22:10
> I assume such a behavior (kernel running as a prerequisite) is not expected...

No, it's not expected. I'm unable to repro this remaining issue. I've tried without a kernel selected, with an unstarted kernel, after starting the kernel. It all works for me.

I'm going to close this issue for now. If you have any additional thoughts on how to repro this, please let us know.

**Closed by debonte** 2023-03-24 22:10 UTC
Labels: waiting for user response

**Comment by yuuuxt** [comment] 2023-03-29 09:21
Though there is already some improvements on this issue (as above), I can still find some cases where it's not working:

The vscode version is 1.76.2, and the pylance version is prerelease 2023.3.31; the kernel is remote and the notebook file is on remote as well.

![image](https://user-images.githubusercontent.com/3153534/228487987-6436f16f-a6ac-42be-abf9-8e2132a750da.png)
