### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for Python.

### ISSUE THREAD

**Issue by Cteljr** [microsoft/pylance-release#232] opened 2020-08-12 13:28 UTC
Issue Type: <b>Bug</b>

Open a python file in VSCode.

## versions
VSCode 1.47.3
Python extension version 2020.7.96456

### IntelliCode log:
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at u._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:717
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error while activating Python: {}

### Python Log:
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - experiment'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/workspace/api-proxy-generator/venv/bin/python3 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Python interpreter path: /usr/local/opt/python/bin/python3.7
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/opt/python/bin/python3.7 ~/.vscode/extensions/ms-python.python-2020.7.96456/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
Error 2020-08-12 09:06:30: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/Users/clester/workspace/api-proxy-generator/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Users/clester/workspace/api-proxy-generator/.vscode/settings.json')
	at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:657:25)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:1:571666)
	at async p.doesFileNeedToBeFixed (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:932592)
	at async /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931719
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931665)
	at async p.updateTestSettings (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:48:931292)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Pylance language server.
Error 2020-08-12 09:06:31: Listing Nuget Packages, Class name = d, completed in 45ms, has a falsy return value, Arg 1: "https://pvsc.blob.core.windows.net", Arg 2: "-stable", Arg 3: "", Arg 4: "https://pvsc.azureedge.net", Arg 5: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:184964)
	at v.t.containerNameIsValid (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:185226)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410229
	at Object.t.validateArgs (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:189471)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410156)
	at z.listBlobsSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:368123)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314745
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314723)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async listPackages (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314429)]
Error 2020-08-12 09:06:31: Get latest language server nuget package version, Class name = d, completed in 51ms, has a falsy return value, Arg 1: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Arg 2: "0.0.0", Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:184964)
	at v.t.containerNameIsValid (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:185226)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410229
	at Object.t.validateArgs (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:189471)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410156)
	at z.listBlobsSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:368123)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314745
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314723)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async listPackages (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314429)]
Error 2020-08-12 09:06:31: Get latest version of Language Server, Class name = f, completed in 51ms, has a falsy return value, Arg 1: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Return Value: undefined [SyntaxError: Container name format is incorrect.
	at f (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:184964)
	at v.t.containerNameIsValid (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:185226)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410229
	at Object.t.validateArgs (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:189471)
	at z._listBlobsOrDircotriesSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:410156)
	at z.listBlobsSegmentedWithPrefix (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/node_modules/azure-storage.js:211:368123)
	at /Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314745
	at new Promise (<anonymous>)
	at listBlobStoreCatalog (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314723)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async listPackages (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:39:314429)]
Error 2020-08-12 09:06:31: Get language server folder name, Class name = f, completed in 78ms, has a falsy return value, Arg 1: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at m.getLanguageServerFolderName (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:24:46002)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)]
Error 2020-08-12 09:06:31: Failed to ensure language server is available, Class name = f, completed in 79ms, has a falsy return value, Arg 1: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at m.getLanguageServerFolderName (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:24:46002)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)]
Starting Pylance language server.
Error 2020-08-12 09:06:31: Failed to activate language server, Class name = l, completed in 79ms, has a falsy return value, Arg 1: <Uri:/Users/clester/workspace/api-proxy-generator/app/__init__.py>, Arg 2: {"architecture":3,"path":"/Users/clester/workspace/api-proxy-generator/venv/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.7.7-final","major":3,"minor":7,"patch":7,"prerelease":["final"],"build":[],"version":"3.7.7-final"},"sysPrefix":"/Users/clester/workspace/api-proxy-generator/venv","fileHash":"29237e2bdb62ca10d667d8ba604ab3973c60b53e81788acea72c9a12e9cf3dbf3d1ef7f8211a9125b7a92d50ea7ee7b851a6b50950a8cb48e297d3076ac746e6","type":"Unknown","displayName":"Python 3.7.7 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at m.getLanguageServerFolderName (/Users/clester/.vscode/extensions/ms-python.python-2020.7.96456/out/client/extension.js:24:46002)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)]
> conda --version

Extension version: 2020.7.96456
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 8|
|Memory (System)|16.00GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jakebailey** [comment] 2020-08-12 17:20
Duplicate of #50.

**Closed by jakebailey** 2020-08-12 17:20 UTC
Labels: triage
