### ISSUE TITLE
Sometimes function list does not work for Python

### ISSUE THREAD

**Issue by chascruzrm** [microsoft/pylance-release#839] opened 2021-01-12 21:22 UTC
Issue Type: <b>Bug</b>

Hi, when I start VSC, last Typescript project folder is opened, then:
I go to File -> Close Folder
Then, I choose a Python project at the Recent section on Welcome tab.
After that, the Python project fully loads, but the Outline window doesn't show function list in any python file saying "No symbols found in document '<filename.py>'", it does not matter how much I wait, method list is not shown.

Extension version: 2020.12.424452561
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.80GB free)|
|Process Argv|--crash-reporter-id bc78da00-d373-4252-83bf-6b2b6b546847|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by jakebailey** [comment] 2021-01-15 23:29
If you type something into the editor, does the outline appear?

**Comment by chascruzrm** [comment] 2021-01-15 23:46
Interesting, I typed a space (character) and outline windows loaded file's
members

**Comment by jakebailey** [comment] 2021-01-15 23:52
Thanks. That implies VS Code either failed to call Pylance, or timed out during startup and chose not to query again. Editing the file means VS Code will re-ask for the outline, and will get a response.

I'm not entirely certain we can do something here, but perhaps it'll improve with some client cleanups we're working on. Maybe there's a timeout to tweak, but we'd have to reproduce this first to know which problem it is.

**Comment by chascruzrm** [comment] 2021-01-15 23:54
Thanks for your time and for the "press a key" tip, Jake.

**Comment by erictraut** [comment] 2021-01-16 00:06
I'm able to repro the problem with Pylance. I think it's a timeout issue because the core Python extension is taking too long to load.

**Comment by jakebailey** [comment] 2021-01-27 23:15
This is a dupe of #534, actually.

**Closed by jakebailey** 2021-01-27 23:15 UTC
Labels: needs investigation
