### ISSUE TITLE
`python.analysis.extraPaths` seems to work even when `pyrightconfig.json` is present

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#6610] opened 2024-10-28 23:26 UTC
## Environment data

-   Pylance version: 2024.10.103
-   OS and version: Windows 11
-   Python version: 3.12.6

## Repro Steps

1. Open `testing\single` in pylance-release
2. Open `.vscode/settings.json` and note that `python.analysis.extraPaths` is flagged with a warning because there is a `pyrightconfig.json` file present.
3. Open `codeaction.py`
4. Find the `import outerModule` line and trigger the `Add "./outsideLib" to extraPaths` code action.

## Expected behavior

One or more of the following:
1. The code action should set `extraPaths` in `pyrightconfig.json` since the presence of the config file (according to the warning) causes `python.analysis.extraPaths` to be ignored.
2. If the warning in `.vscode/settings.json` is wrong, don't show it.
3. If the warning is correct, changes to `python.analysis.extraPaths` should be ignored.

## Actual behavior

`"./outsideLib"` is added to the `python.analysis.extraPaths` array in `.vscode/settings.json` and it appears to work because the "Import 'outerModule' could not be resolved" diagnostic in `codeaction.py` disappears.

**Comment by rchiodo** [comment] 2024-10-28 23:32
I believe this is a dupe of https://github.com/microsoft/pylance-release/issues/5195

**Comment by debonte** [comment] 2024-10-29 03:29
> I believe this is a dupe of [#5195](https://github.com/microsoft/pylance-release/issues/5195)

Maybe I'm misreading #5195, but the actual behavior there seems to be the opposite of this issue?

**Comment by rchiodo** [comment] 2024-10-29 16:00
No, #5195 was adding it to the settings.json too. Which it shouldn't do because pyrightconfig.json is the only place extraPaths applies. Seems weird that the import error would go away though. Maybe extraPaths isn't behaving the way I thought and it's allowing overrides.

**Closed** 2024-10-29 16:13 UTC
Labels: needs repro
