### ISSUE TITLE
Pylance won't use lxml-stubs

### ISSUE THREAD

**Issue by Timmmm** [microsoft/pylance-release#1358] opened 2021-05-27 14:35 UTC
## Environment data

-   Language Server version: v2021.5.4
-   OS and version: MacOS 11.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.7

## Expected behaviour

I installed `lxml-stubs` using `pip install lxml-stubs`. I expect when I use `lxml.etree.parse("foo.xml")` it should use the definition from `lxml-stubs` which has a return type of `_ElementTree`.

## Actual behaviour

It actually still uses the bundled `lxml` type stubs which return `Any`.

## Logs

The logs don't say anything at all while resolving this type.

**Comment by jakebailey** [comment] 2021-05-27 16:41
Hmm, the bundled lxml stubs aren't traditional stubs and won't be loaded unless we need to analyze the real code (which is compiled, so we fail). The stubs should be taking precedence over the real code if we can find them.

What does your code look like? Is it like:

```python
import lxml.etree

lxml.etree.parse("foo.xml")
```

Or is it like:

```python
import lxml

lxml.etree.parse("foo.xml")
```

I ask because the `lxml-stubs`' `__init__.py` file does not indicate that the modules are reexported.

**Comment by Timmmm** [comment] 2021-05-28 07:24
It's like your first example - `import lxml.etree`.  I'll try changing it to be like the second one.

**Comment by jakebailey** [comment] 2021-05-28 07:40
Okay, thanks. The second one is the one that I don't think should work, so I wanted to verify that you weren't doing it.

**Comment by Timmmm** [comment] 2021-05-28 08:06
Hmm this is the first one:

![image](https://user-images.githubusercontent.com/376842/119951310-b56f4c80-bf93-11eb-9398-5c3d06433250.png)

The second one fails in a different way:

![image](https://user-images.githubusercontent.com/376842/119951264-a7b9c700-bf93-11eb-88bf-25f6d4008b81.png)

But I think that's correct (sorry I am still learning how Python's crazy import system works):

```
>>> import lxml
>>> lxml.etree.parse("foo.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lxml' has no attribute 'etree'
>>> import lxml.etree
>>> lxml.etree.parse("foo.xml")
...
OSError: Error reading file 'foo.xml': failed to load external entity "foo.xml"
```

So I have to use `import lxml.etree`.

**Comment by jakebailey** [comment] 2021-05-28 08:17
Yes, this fits with us not finding the stub package for some reason. Don't worry about the import form, since you're using the module the right way.

**Comment by Timmmm** [comment] 2021-06-01 14:10
Presumably this is a problem in Pylance rather than Pyright, so I can't do anything to debug/fix it?

**Comment by erictraut** [comment] 2021-06-01 14:36
I'm not able to repro the problem.

Which version of lxml and lxml-stubs are you using? Have you tried upgrading them to the latest?

If you right-click on `parse` and choose "Go to Declaration", where does it take you? You should go to the stub file called `etree.pyi`.

**Comment by Timmmm** [comment] 2021-06-03 12:22
Ok I finally figured out how to reproduce it! Not sure if this is minimal but it seems to work. This is on a Mac.

1. `mkdir ~/local_python`
2. `pip3 install --target=$HOME/local_python lxml-stubs`
3. `mkdir ~/d1` (demo directory)

In `~/d1/main.py` put

```python
import lxml.etree

lxml.etree.parse("foo.xml")
```

In `~/d1/.env` put

```
PYTHONPATH=${env:PYTHONPATH}:/usr/local/lib/python3.9/site-packages:/Users/you/local_python
```

(Replace `you` with your username and the python path from `python3 -m site` as appropriate.)

If I do all that then it uses the bundled stubs. If I change `.env` to

```
PYTHONPATH=${env:PYTHONPATH}:/Users/you/local_python
```

then it uses the `lxml-stubs`.

So I'm guessing in the first case it searches `PYTHONPATH` for `lxml`, finds it, and looks in the same directory for  stubs (instead of the whole `PYTHONPATH`), whereas in the second case if finds `lxml` without looking in `PYTHONPATH` and then searches all of `PYTHONPATH` for the stubs. Or something.

**Comment by jakebailey** [comment] 2021-06-03 15:00
Can you provide trace logs for each of these cases? I'm especially interested in the paths section, to see how they differ.

**Comment by Timmmm** [comment] 2021-06-03 15:17
Ok, not sure I've got exactly what you want...

# Failing Case

## `Python` Output

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: /usr/local/opt/python@3.9/bin/python3.9
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-06-03 16:12:18: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/Users/timh/d1/.vscode/settings.json' (Error: Unable to resolve non-existing file '/Users/timh/d1/.vscode/settings.json')
	at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:581560)
	at async /Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version
Python interpreter path: /usr/local/bin/python3
```

## `Python Language Server` Output

```
[Info  - 4:12:19 PM] Pylance language server 2021.6.0 (pyright 209c8040) starting
[Info  - 4:12:19 PM] Server root directory: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 4:12:19 PM] No configuration file found.
[Info  - 4:12:19 PM] No pyproject.toml file found.
[Info  - 4:12:19 PM] Setting pythonPath for service "d1": "/usr/local/bin/python3"
[Warn  - 4:12:19 PM] stubPath /Users/timh/d1/typings is not a valid directory.
[Info  - 4:12:19 PM] Assuming Python version 3.9
[Info  - 4:12:19 PM] Assuming Python platform Darwin
Search paths for /Users/timh/d1
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib
  /Users/timh/d1
  /Users/timh/d1/${env
  /Users/timh/d1/PYTHONPATH}
  /usr/local/lib/python3.9/site-packages
  /Users/timh/local_python
  /Users/timh/d1/typings
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stubs/...
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/bundled/stubs
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python39.zip
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python3.9
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python3.9/lib-dynload
  /users/timh/library/python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages
  /usr/local/cellar/protobuf/3.15.6/libexec/lib/python3.9/site-packages
  /usr/local/cellar/pybind11/2.6.2/libexec/lib/python3.9/site-packages
[Info  - 4:12:19 PM] Searching for source files
[Info  - 4:12:19 PM] Found 1 source file
[FG] parsing: /Users/timh/d1/main.py (19ms)
[FG] parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (96ms)
[FG] binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi (37ms)
[FG] binding: /Users/timh/d1/main.py (0ms)
[Info  - 4:12:19 PM] Background analysis(1) root directory: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 4:12:19 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: analyze
[BG(1)] analyzing: /Users/timh/d1/main.py ...
[BG(1)]   parsing: /Users/timh/d1/main.py (20ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (93ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi (45ms)
[BG(1)]   binding: /Users/timh/d1/main.py (0ms)
[BG(1)]   checking: /Users/timh/d1/main.py ...
[BG(1)]     parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing.pyi [fs read 2ms] (34ms)
[BG(1)]     binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing.pyi (11ms)
[BG(1)]     parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (9ms)
[BG(1)]     binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
[BG(1)]     parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (3ms)
[BG(1)]     binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing_extensions.pyi (1ms)
[BG(1)]     parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/bundled/native-stubs/lxml/etree.pyi [fs read 2ms] (105ms)
[BG(1)]     binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/bundled/native-stubs/lxml/etree.pyi (39ms)
[BG(1)]   checking: /Users/timh/d1/main.py (232ms)
[BG(1)] analyzing: /Users/timh/d1/main.py (393ms)
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /Users/timh/d1/main.py (2ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 3:0 at /Users/timh/d1/main.py (1ms)
Background analysis message: resumeAnalysis
```

# Working Case

## `Python` Output

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: /usr/local/opt/python@3.9/bin/python3.9
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-06-03 16:14:00: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/Users/timh/d1/.vscode/settings.json' (Error: Unable to resolve non-existing file '/Users/timh/d1/.vscode/settings.json')
	at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:581560)
	at async /Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/Users/timh/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version
Python interpreter path: /usr/local/bin/python3
```

## `Python Language Server` Output

```
[Info  - 4:14:00 PM] Pylance language server 2021.6.0 (pyright 209c8040) starting
[Info  - 4:14:00 PM] Server root directory: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 4:14:00 PM] No configuration file found.
[Info  - 4:14:00 PM] No pyproject.toml file found.
[Info  - 4:14:00 PM] Setting pythonPath for service "d1": "/usr/local/bin/python3"
[Warn  - 4:14:00 PM] stubPath /Users/timh/d1/typings is not a valid directory.
[Info  - 4:14:00 PM] Assuming Python version 3.9
[Info  - 4:14:00 PM] Assuming Python platform Darwin
Search paths for /Users/timh/d1
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib
  /Users/timh/d1
  /Users/timh/d1/${env
  /Users/timh/d1/PYTHONPATH}
  /Users/timh/local_python
  /Users/timh/d1/typings
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stubs/...
  /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/bundled/stubs
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python39.zip
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python3.9
  /usr/local/cellar/python@3.9/3.9.5/frameworks/python.framework/versions/3.9/lib/python3.9/lib-dynload
  /users/timh/library/python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages
  /usr/local/cellar/protobuf/3.15.6/libexec/lib/python3.9/site-packages
  /usr/local/cellar/pybind11/2.6.2/libexec/lib/python3.9/site-packages
[Info  - 4:14:01 PM] Searching for source files
[Info  - 4:14:01 PM] Found 1 source file
[Info  - 4:14:01 PM] Background analysis(1) root directory: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 4:14:01 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /Users/timh/d1/main.py ...
[BG(1)]   parsing: /Users/timh/d1/main.py (22ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (91ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/builtins.pyi (35ms)
[BG(1)]   binding: /Users/timh/d1/main.py (1ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing.pyi [fs read 2ms] (32ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing.pyi (10ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (7ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (2ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/typing_extensions.pyi (1ms)
[BG(1)]   parsing: /Users/timh/local_python/lxml-stubs/etree.pyi [fs read 1ms] (13ms)
[BG(1)]   binding: /Users/timh/local_python/lxml-stubs/etree.pyi (5ms)
[BG(1)]   parsing: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
[BG(1)]   binding: /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
[BG(1)] getSemanticTokens full at /Users/timh/d1/main.py (257ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 3:0 at /Users/timh/d1/main.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/timh/d1/main.py ...
[BG(1)]   checking: /Users/timh/d1/main.py (1ms)
[BG(1)] analyzing: /Users/timh/d1/main.py (2ms)
Background analysis message: resumeAnalysis
```

This looks very wrong!

```
  /Users/timh/d1/${env
  /Users/timh/d1/PYTHONPATH}
```

But it happens in the passing case too so maybe it's just printing things badly.

**Comment by jakebailey** [comment] 2021-06-03 18:13
Yes, that variable thing is wrong; we should be getting the replaced version but apparently this API in the core Python extension isn't doing that.

Past that, I think you're seeing this work because you're forcing the interpeter to appear before our bundled stubs; I think there's something to be done here to ensure that if stubs are installed they are chosen first (as that is the intent). Right now we have the problem of both wanting to ensure stubs are read before regular python code (so, search stub locations first), but somehow also pick up stubs provided in paths first. It's a complicated search procedure to get right when there are more than one providers of a module.

**Comment by Timmmm** [comment] 2021-06-04 07:03
> I think you're seeing this work because you're forcing the interpeter to appear before our bundled stubs; 

Hmm I don't think that can be quite right, because it works when I *don't* force the default site-packages dir to appear before the bundled stubs.

But yeah there must be something funky going on with the search order. Is that bit closed source?

**Comment by jakebailey** [comment] 2021-06-04 17:15
The vast majority of Pylance is OSS here: https://github.com/microsoft/pyright

**Comment by jakebailey** [comment] 2021-07-07 18:11
Marking as needs investigation; I think we need to fix up our import resolver in Pylance to not offer our bundled stubs ahead of explicitly installed stubs or py.typed libraries.

**Comment by jakebailey** [comment] 2021-09-07 22:53
As far as I can tell, this doesn't reproduce anymore:

![image](https://user-images.githubusercontent.com/5341706/132420498-17987117-4259-4ab8-bb95-b507a9bf860c.png)

**Closed by jakebailey** 2021-09-07 22:53 UTC
Labels: in backlog, needs investigation, in iteration

**Comment by imba-tjd** [comment] 2021-10-04 04:54
@jakebailey I tested that stubs for `lxml.etree` are OK. But `lxml.html` won't work.

![图片](https://user-images.githubusercontent.com/24759802/135796299-4c66aeff-909b-48fd-9411-ede371d8c5db.png)

![图片](https://user-images.githubusercontent.com/24759802/135796315-a07fb8ae-a21d-4d1e-94e0-086252aa004e.png)
