### ISSUE TITLE
"Code is Unreachable" when using numpy.cross() in a function

### ISSUE THREAD

**Issue by DavideRuzza** [microsoft/pylance-release#3288] opened 2022-09-06 12:31 UTC
-   Language Server version: 2022.8.51
-   OS and version: Windows 11
-   Python version: 3.10.6
-   numpy version: 1.23.2

I have found a bug, when i use the  numpy `cross()` function inside a function, then all the code that follow get the message * code is unreachable * and the code color fade.This only happens in a function. An example which give me this error is this:

```python
import numpy as np

def fun(a, b):
    c = np.cross(a, b)
    return c
```

then the line `return c` is not rachable

**Comment by erictraut** [comment] 2022-09-06 13:03
This is a bug in numpy. See https://github.com/microsoft/pylance-release/issues/3277#issuecomment-1237782014.

**Comment by judej** [comment] 2022-09-06 17:45
duplicate of #3277

**Closed by judej** 2022-09-06 17:45 UTC
Labels: external bug
