### ISSUE TITLE
Saving .py files delayed by Getting code actions from ''Python'

### ISSUE THREAD

**Issue by armenzg** [microsoft/pylance-release#4263] opened 2023-04-19 12:55 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I expect to save a Python file and not have to wait over 15+ seconds to save.
Instead I get `Getting code actions from ''Python'"`.  Before, it used to be Jupyter getting on the way but after I uninstalled it, the problem came directly from the "Python" extension.

This is similar to https://github.com/microsoft/vscode-python/issues/19808, however, I can't make any comments.

I think I've noticed this issue in the last month or two.

It does not happen all the time but when it does, it happens often.

Here's a screenshot:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/44410/233082940-6a5474f3-8978-4f36-a9e9-b8f7629dd92f.png">

## Steps to reproduce:

1. Edit Python file
2. Hit Command + S to save the file

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
LINTING: Skipping linting from Python extension, since Flake8 extension is installed and enabled.
> ./.venv/bin/black --diff --quiet ./src/sentry/issues/escalating.py.d3fb48e40859389f827f7b92bdb1d899.tmp
cwd: .
LINTING: Skipping linting from Python extension, since Flake8 extension is installed and enabled.
> ./.venv/bin/python ~/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear tests
cwd: .
[ERROR 2023-3-19 9:2:20.223]: Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform darwin -- Python 3.8.13, pytest-7.2.1, pluggy-0.13.1
rootdir: /Users/armenzg/code/sentry, configfile: pyproject.toml
plugins: forked-1.4.0, fail-slow-0.3.0, rerunfailures-11.0, sentry-0.1.11, xdist-3.0.2, typeguard-2.13.3, cov-4.0.0, django-4.4.0

###################
#
# Frontend assets last built 3562 seconds ago, skipping rebuilds for another 38 seconds.
# Delete the file: `.webpack.meta` to rebuild.
#
###################

collected 17246 items / 4 errors

##### SKIPPING A MILLION LINES HERE

=========================== short test summary info ============================
ERROR tests/sentry/celery/test_app.py - NameError: name 'logging' is not defined
ERROR tests/sentry/issues/test_escalating.py - NameError: name 'logging' is n...
ERROR tests/sentry/issues/test_escalating_issues_alg.py - NameError: name 'lo...
ERROR tests/sentry/tasks/test_weekly_escalating_forecast.py - NameError: name...
!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
================== 17246 tests collected, 4 errors in 18.80s ===================

Traceback (most recent call last):
  File "/Users/armenzg/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/Users/armenzg/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/testing_tools/adapter/__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
  File "/Users/armenzg/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/Users/armenzg/.vscode/extensions/ms-python.python-2023.6.1/out/client/extension.js:2:238829)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)]
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Enabled: true
• flake8Path: "<placeholder>"
• pycodestylePath: "<placeholder>"

formatting
• provider: "black"
• blackPath: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• pytestPath: "<placeholder>"

```

</p>
</details>

Extension version: 2023.6.1
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 8fcb9b29-2bdc-4a61-9b8c-1be28aead4fa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
azdwalk:30687957
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by rchiodo** [comment] 2023-04-20 16:58
Thanks for the issue.

The root cause of the problem is that it takes 30 seconds to analyze your file. That's a bit out of the ordinary. If we could get access to your source, we might be able to fix that problem.

Secondly, I'm not sure why VS code is asking for code actions on file save. We might be able to shortcut this problem. I'll look into if that's possible or not.

**Comment by rchiodo** [comment] 2023-04-20 17:57
It seems there is a setting to control if code actions run on save or not. You must have this setting set:

```
  "editor.codeActionsOnSave": {
    "source.fixAll": true, <-- This one causes Pylance to have to analyze the file again before the save is finished.
    "source.organizeImports": true
  }
```

**Comment by armenzg** [comment] 2023-04-20 18:48
Okay. Let me add it to the user settings and report back.

**Comment by rchiodo** [comment] 2023-04-20 20:19
I am reproing the issue using the source code provided. It's not quite as slow, but I can get the dialog to show up. 

This setting has to be set for me to repro the problem though:

```
  "python.analysis.fixAll": [
    "source.unusedImports",
  ],
```

**Comment by rchiodo** [comment] 2023-04-20 20:25
I believe we might be able to fix this problem by **not** cloning the service during a save. That seems to be what takes so long. It has to reparse everything every time you hit save.

At least that's what the log looks like when I repro (log output from just saving)
[savelog.txt](https://github.com/microsoft/pylance-release/files/11290219/savelog.txt)

**Comment by heejaechang** [comment] 2023-04-20 20:28
that is only when you have 1 fix all in the setting. when there are multiple ones, you can't avoid cloning. we could optimize a case where there is only one fix all in the setting if we think that's worth it.

**Comment by armenzg** [comment] 2023-04-21 13:07
Hi @ heejaechang 
That's for your help. Find below my reply to your comment. 

> ![image](https://user-images.githubusercontent.com/1333179/233462082-225c2706-c39f-4e51-adf7-e13941be683a.png)
> 
> if you click `cancel`, does it actually cancel `codeActionsOnSave` (https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save)? I am wondering whether cancellation is working as expected.
> 
I believe hitting the cancel button works. I will pay closer attention.

This is what I would notice:
* I hit save
* I switch to my terminal to run the tests
* The tests unexpectedly fail since I just fixed them on VS Code
* I switch back to VS Code and I notice that the prompt is there, thus, the code fixes have not been saved
* I hit the cancel button and I go back to running the tests

I believe it's worked as mentioned above but I will check again.

> by the way, by default, we don't do anything on `codeActionsOnSave`, you must have set up something to run on save using `python.analysis.fixAll`
> 
I see [this](https://github.com/getsentry/sentry/blob/6f5ab5919970a060d4665f81a39b551bb13006d4/.vscode/settings.json#L24-L26) and [this](https://github.com/getsentry/sentry/blob/6f5ab5919970a060d4665f81a39b551bb13006d4/.vscode/settings.json#L59-L64) in our repo's workspace settings. Would that do it?

```
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  ...
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },
```

> you can disable us participating in `codeActionsOnSave` using 2 ways. one is disabling `codeActionsOnSave` all together using `editor.codeActionsOnSave`. That will disable not just us but all extensions. the other one is disabling just us using `python.analysis.fixAll` (https://github.com/microsoft/pylance-release/blob/main/README.md#settings-and-customization)

Like this? `"python.analysis.fixAll": [],` (No list of actions to be taken)

**Comment by armenzg** [comment] 2023-04-21 13:26
For anyone following along.

Before this comment:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/44410/233646599-9b5f9103-661c-447e-970f-d0976119ab16.png">

I had this setting from the workspace's setting:
```
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  ...
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },
```

Yesterday I added the following as suggested and the issue still happened this morning:
```
  "editor.codeActionsOnSave": {
    "source.fixAll": true, <-- This one causes Pylance to have to analyze the file again before the save is finished.
    "source.organizeImports": true
  }
```

I now have:
* Removed the `"editor.codeActionsOnSave"` section mentioned by @rchiodo 
* Kept the workspace settings
* Added the following `"python.analysis.fixAll": [],`

**Comment by armenzg** [comment] 2023-04-21 13:46
Is this useful output?

```
2023-04-21 09:43:47.145 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-04-21 09:43:53.265 [warning] UNRESPONSIVE extension host: 'ms-python.python' took 64.93929990255603% of 3248.832ms, saved PROFILE here: 'file:///var/folders/4p/5s4qn7950nx1j4_j5f748n5w0000gn/T/exthost-835837.cpuprofile'
2023-04-21 09:44:28.203 [error] Error: Aborted onWillSaveTextDocument-event after 1750ms
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1906:13638
2023-04-21 09:44:30.839 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-04-21 09:44:34.059 [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
2023-04-21 09:44:34.976 [warning] UNRESPONSIVE extension host: 'ms-python.python' took 70.24299447387308% of 2282.4ms, saved PROFILE here: 'file:///var/folders/4p/5s4qn7950nx1j4_j5f748n5w0000gn/T/exthost-3692a7.cpuprofile'
2023-04-21 09:45:06.633 [error] Error: Aborted onWillSaveTextDocument-event after 1750ms
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1906:13638
2023-04-21 09:45:08.759 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-04-21 09:45:14.647 [warning] UNRESPONSIVE extension host: 'ms-python.python' took 69.13412892594997% of 3461.373ms, saved PROFILE here: 'file:///var/folders/4p/5s4qn7950nx1j4_j5f748n5w0000gn/T/exthost-b85259.cpuprofile'
2023-04-21 09:45:51.115 [info] UNRESPONSIVE extension host: starting to profile NOW
2023-04-21 09:45:55.910 [info] UNRESPONSIVE extension host: received responsive event and cancelling profiling session
2023-04-21 09:45:56.789 [warning] UNRESPONSIVE extension host: 'ms-python.python' took 69.23570817182755% of 3321.266ms, saved PROFILE here: 'file:///var/folders/4p/5s4qn7950nx1j4_j5f748n5w0000gn/T/exthost-8abcc6.cpuprofile'
```

**Comment by armenzg** [comment] 2023-04-21 14:01
I have verified that adding `"python.analysis.fixAll": [],` removes the problem.

Here's my config.

```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index 4e6108da16..c7f254b2d3 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -59,9 +59,11 @@
   "[python]": {
     "editor.formatOnSave": true,
     "editor.codeActionsOnSave": {
-      "source.organizeImports": true
+      "source.organizeImports": true,
+      "source.fixAll": true
     }
   },
+  // "python.analysis.fixAll": [],

   "[html]": {
     "editor.formatOnSave": false```
```

**Comment by armenzg** [comment] 2023-04-21 14:07
I'm also upgrading to the M1 build rather than the Universal just in case there are some perf improvements.

```
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

```
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

**Comment by bschnurr** [comment] 2023-04-21 14:50
Its the source of the problem 4542 source files and index hitting the limit of 2000?
from the logs
```
[Warn  - 8:56:36 AM] (44971) Workspace indexing has hit its upper limit: 2000 files
[Info  - 8:56:36 AM] (44971) [IDX(2)] Long operation: index execution environment /Users/armenzg/code/sentry (3219ms)
[Info  - 8:56:36 AM] (44971) [IDX(2)] Long operation: index packages /Users/armenzg/code/sentry (3231ms)
[Info  - 8:56:36 AM] (44971) indexed(2) 169 files over 1 exec env
[Info  - 8:56:36 AM] (44971) Indexing finished(2).
[Info  - 9:15:34 AM] (44971) Found 4542 source files
```

**Comment by armenzg** [comment] 2023-04-21 16:21
Yeah. I'm still hitting the issue.

Any other setting I should try?

**Comment by armenzg** [comment] 2023-04-21 19:09
I thought so too.

Am I setting it correctly as this? `"python.analysis.fixAll": []`

It stills happens sporadically with this configuration:
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index 4e6108da16..d82e921adb 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -59,9 +59,11 @@
   "[python]": {
     "editor.formatOnSave": true,
     "editor.codeActionsOnSave": {
-      "source.organizeImports": true
+      "source.organizeImports": false,
+      "source.fixAll": false
     }
   },
+  "python.analysis.fixAll": [],
```

**Comment by heejaechang** [comment] 2023-04-21 19:35
then, it might not even us. it could be some other extension running. turn off everything that is supposed to do anything while save such as `formatOnSave`

**Comment by heejaechang** [comment] 2023-04-21 19:59
hmm... we have this code 

```ts
const workspace = (await this._ls.getWorkspaceForFile(filePath)) as PylanceWorkspace;
        if (!workspace || !workspace.fixAll || workspace.fixAll.length === 0) {
            // No fix all is configured.
            return;
        }
```

`fixAll` has value of `python.analysis.fixAll`, so unless there is a bug (I just checked and I couldn't see any issue), if there is no `python.analysis.fixAll` set, then it should be same as having `python.analysis.fixAll: []` so not sure why having that setting affect anything.

> The real problem here is we reindex after every save because of the cloning of the service to handle the fix all command.

> Warn  - 8:56:36 AM] (44971) Workspace indexing has hit its upper limit: 2000 files

if we are hitting this from `cloned` service (hopefully, once we change how we use `program`, we just clone `program` rather than clone entire `service` to get cloned `program`), that sounds like a bug. the `cloned` service is supposed to be `disabled all ide` features including `background thread`.

**Comment by heejaechang** [comment] 2023-04-21 20:40
So, I just debugged our code and found that our cloneService doesn't create a bg, which means the indexer can't run for the cloned service since it only runs when there's a bg. Additionally, the cloned service is marked as not scan folder, so it can't be discovering files and taking a long time to do so.

That being said, I did find a bug. When we reach the 2000 file limit for the workspace, it appears that the limit only applies to how many files we process in one chunk. This means that if there are 4000 files, we will hit the 2000 file limit twice and end up processing all 4000 files. It seems like this occurs whenever a file is saved/edited because that's when the next 2000 chunk is processed.

In this particular case where there are 4xxx files, the process will run 3 times: 2 times for the 2000 files and once for the remaining files. After that, it will stop processing indices for workspace files.

I will fix this bug. However, it's worth noting that it shouldn't affect the fix all issue, as it should be unrelated. It's just that the repo is large enough to reveal another bug we weren't previously aware of.

**Comment by lobsterkatie** [comment] 2023-04-25 23:16
Hey, all, @armenzg's teammate here. 

I'm running into the same thing (not surprising, since we're working on the same codebase), and thought I'd add two points:

1) This slow saving has been happening for a while but I think it might (?) have gotten worse when I switched to using the official `black` formatter (which I actually did in hopes of making this slow-save problem _better_):
    ```
    "[python]": {
            "editor.defaultFormatter": "ms-python.black-formatter"
        },
    ```
    Since it's slow both ways, it's hard to tell what's better. In theory, should this `black` be faster than a venv `black`?

2) It's worth noting that I run into this more frequently than I otherwise would because of https://github.com/microsoft/vscode-python/issues/408. If I don't save, it's very hard to tell if I've fixed whatever the linter is mad about, so I hit save lot of times when I otherwise wouldn't. Also, I wouldn't need it to lint on save at all if lint-on-type worked in Python the way it does in TS.

Thanks for looking into this!

**Comment by heejaechang** [comment] 2023-04-26 00:16
@lobsterkatie those 2 are handled by `https://github.com/microsoft/vscode-python`. we only handle ones in `python.analysis.fixall` so you probably want to open an issue there for those 2 features.

**Comment by karthiknadig** [comment] 2023-04-26 00:51
@lobsterkatie You can look at the logs for Output > Black, it should give some clue on how long black actually took to format. The Black formatter extension does only one thing different from running black in terminal; it has the modules pre-loaded for formatting and does not have to spawn a new process to actually do formatting. The speed up comes from not having python run a separate process on each save.

That being said, black formatter extension does not contribute Code Actions, so if you are seeing a notification for this then please file a bug https://github.com/microsoft/vscode-black-formatter

**Comment by lobsterkatie** [comment] 2023-04-26 01:20
> @lobsterkatie those 2 are handled by [microsoft/vscode-python](https://github.com/microsoft/vscode-python) . we only handle ones in `python.analysis.fixall` so you probably want to open an issue there for those 2 features.

Ah, right - I saw that the very similar issue Armen linked in the original issue description above was from the `vscode-python` repo, and failed to notice that this one was not! Apologies!

> @lobsterkatie You can look at the logs for Output > Black, it should give some clue on how long black actually took to format. The Black formatter extension does only one thing different from running black in terminal; it has the modules pre-loaded for formatting and does not have to spawn a new process to actually do formatting. The speed up comes from not having python run a separate process on each save.
> 
> That being said, black formatter extension does not contribute Code Actions, so if you are seeing a notification for this then please file a bug [microsoft/vscode-black-formatter](https://github.com/microsoft/vscode-black-formatter)

Thanks, that's helpful to know. And yeah, I do think that the popup I see mentioning the `black` formatter running is separate from the popup Armen mentioned about gathering code actions, but they come immediately in sequence when I save, and both contribute to the slowness. In any case, I can take that up in the `vscode-python` repo (now that I know that that's not here!).

Cheers!

**Comment by rchiodo** [comment] 2023-04-26 20:14
@heejaechang and @erictraut I tried this with a deep copy of the program and the problem goes away in my repro. The save is almost instant then. 

I'm going to look into have one source of truth for document parse trees.

**Comment by heejaechang** [comment] 2023-04-26 20:19
since plan is only sharing text and tree, but not binding info and type cache, once you did deep copy, you could remove all binding info using cleantree call and create new type eval and run `fix all` on it.

**Comment by rchiodo** [comment] 2023-04-26 20:23
You mean don't create a 'DocumentManager' but instead keep it the same (with a deep copy) and then prune the deep copy?

**Comment by heejaechang** [comment] 2023-04-26 20:56
I meant just for prototyping.

**Comment by erictraut** [comment] 2023-04-26 20:59
@rchiodo, I propose we do this in stages. We can start with having one source of truth for the document text. That will address [this bug](https://github.com/microsoft/pyright/issues/4994). Then we can separate the bind information from the parse tree, which will allow us to treat the parse tree as immutable. Then we can share the parse trees without the need to do any deep cloning. Does that sound like a reasonable plan?

**Comment by rchiodo** [comment] 2023-04-26 21:09
> @rchiodo, I propose we do this in stages. We can start with having one source of truth for the document text. That will address [this bug](https://github.com/microsoft/pyright/issues/4994). Then we can separate the bind information from the parse tree, which will allow us to treat the parse tree as immutable. Then we can share the parse trees without the need to do any deep cloning. Does that sound like a reasonable plan?

Sounds good to me. I'm still verifying using Heejae's idea at the moment, but after that I'll create some sort of 'DocumentManager' that is the place to get SourceFiles? or maybe just parse results.

**Comment by rchiodo** [comment] 2023-04-27 18:16
Cloning and rebinding is about the same time as the old algorithm (so parsing is not the slow part here).

Old code:
- 2200 ms or so (average)

Clone with clear all bindings
- 2100 ms. 

Clone service, but keep same parse tree with same bindings (don't rebind or copy anything)
- 800 ms.

Copying the different parse trees and rebinding takes just as long as creating them from scratch. So this will only really get us a gain if we bind less.

Not sure it would be worth it to just share the parse information then. 

What about a copy on write scheme were we only rebind when the edit is applied (just like when typing), but instead of rebinding the current source file, we copy it to another source file and bind that one?

**Comment by rchiodo** [comment] 2023-04-27 19:08
Oh I guess the clone could be taking a portion of the time too. I didn't factor that time out.

**Comment by erictraut** [comment] 2023-04-27 19:18
Are you doing a shallow or deep clone of the parse tree? A shallow clone should be almost free. A deep clone won't be free, but my guess is that it's negligible.

I typically find that the time it takes to parse and bind files is similar. That is, if parsing all of the files in your project takes 1000ms, the total bind time will be roughly the same. The file load time varies greatly depending on whether it's in the OS's file system cache (and if not, how fast the storage device is). 

Here's a typical breakdown.

![image](https://user-images.githubusercontent.com/7040122/234968843-ef873ed3-27e5-48a0-9a1c-0975b7ef6478.png)

If I understand your results correctly, you're saying that eliminating the file reads (which you get for free with the change I made yesterday) and eliminating parsing (which you get by cloning and cleaning the parse tree) drops the time by only 100ms (from 2200 to 2100ms), but eliminating the binding drops it by 1300ms (2100 to 800ms). That's not what I'd expect to see, so I'm somewhat suspicious of these results.

What about import resolution? Are you cloning that information as well, or are you recalculating that? Import resolution can be quite costly for some projects. I'm guessing that you're cloning it because the "clean parse tree" call doesn't clear it.

**Comment by rchiodo** [comment] 2023-04-27 19:25
Yeah computing the deep clone only takes 10ms on average. It's negligible. (Just tracked it now).

Where is the import resolution data stored? I'm creating a new backgroundAnalysisProgram, a new program, sourceFileInfos are shallow copies, sourceFiles are deep copies with the parse tree recreated by deep coping it. 

If it's on the sourceFileInfo, then it should save the import resolution information.

**Comment by rchiodo** [comment] 2023-04-27 19:27
Perhaps it's the checker? There's no background thread for this clone of the service, so the checker might be taking CPU cycles?

**Comment by rchiodo** [comment] 2023-04-27 22:37
I think I need to do more analysis to determine which part is taking so long. It's too broad at the moment.

**Comment by heejaechang** [comment] 2023-04-28 07:20
we have a way to see how much time we spent on parsing, and binding accumulated. you can use that to see how much time is spent.

**Comment by heejaechang** [comment] 2023-04-28 08:51
sent PR that can track perf - https://github.com/microsoft/pyrx/pull/3443

**Comment by rchiodo** [comment] 2023-05-10 22:33
This issue has been fixed in prerelease version 2023.5.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023521-10-May-2023-PreRelease)

**Closed by rchiodo** 2023-05-10 22:33 UTC
Labels: bug, fixed in next version, P2

**Comment by armenzg** [comment] 2023-05-12 12:42
Thank you so much @rchiodo! I will update to the prerelease!

**Comment by flying-sheep** [comment] 2023-07-06 11:29
Still unbearably slow in my code base: https://github.com/scverse/scanpy

Saving files takes multiple seconds. VS Code waits and eventually shows a popup “Getting code actions from ''Python"”.

When setting `"python.languageServer": "Default",` saving works as expected.

Why will VS Code wait for Pylance to save things? I explicitly deactivated `source.fixAll.python`.

```json
{
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.codeActionsOnSave": {
            "source.fixAll.ruff": true,
            "source.fixAll.python": false,
        },
    },
    "python.testing.pytestArgs": ["scanpy/tests"],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.languageServer": "Pylance",
}
```

**Comment by rchiodo** [comment] 2023-07-06 16:04
@flying-sheep, I'm opening a new issue for your problem. It might be the black formatter that is also taking a long time as you're formatting on every save.

**Comment by flying-sheep** [comment] 2023-07-06 19:31
it’s not black:

> When setting "python.languageServer": "None", saving works as expected.

**Comment by flying-sheep** [comment] 2023-08-08 09:45
Actually it’s not relevant how slow or fast Pyright is.

Pylance should not delay saving a document for a single nanosecond if I don’t have VS Code configured to run “on save” actions from Pylance. Any kind of parsing and analysis should happen asynchronously without blocking saving.

Could you please reopen this until Pylance doesn’t delay saving anymore?

**Comment by flying-sheep** [comment] 2023-08-10 08:15
OK, thank you for clarifying! So you *did* stop running analysis synchronously before returning the save actions, that’s great!
