### ISSUE TITLE
function is not a known member of module in numpy. reportGeneralTypeIssues

### ISSUE THREAD

**Issue by lepecoder** [microsoft/pylance-release#106] opened 2020-07-14 09:44 UTC
When I use numpy or torch etc, the Pylance alert that some function is not a known member of module.

![批注 2020-07-14 171840](https://user-images.githubusercontent.com/34852544/87410533-08007e00-c5f9-11ea-9aa0-aab1bed8b446.jpg)
![批注 2020-07-14 172240](https://user-images.githubusercontent.com/34852544/87410568-12bb1300-c5f9-11ea-971c-fab051da543c.jpg)

My python environment is anaconda.

**Comment by johnybx** [comment] 2020-07-14 10:33
Same goes for sqlalchemy objects where for example session methods like commit or add are unrecognized (probably dynamic methods based on database type). Maybe this could be at least split to independent diagnostics which can be turned off or severity level could be overridden independently.

**Comment by jakebailey** [comment] 2020-07-14 17:11
You have a type checking mode enabled, which means you're going to get more errors for untyped code or potentially missing types. See #93 for numpy; most of numpy is compiled and we don't have the information from compiled modules.

PyTorch ships with annotations and stubs, if you believe the signature for FloatTensor's constructor to be wrong you may want to file a bug on their tracker.

@johnybx This diagnostic is disabled by default (type checking mode "off"). I assume you mean when the mode is not just "off"?

**Comment by jakebailey** [comment] 2020-07-14 17:56
Also, note that you can do `# type: ignore` on a specific line if you want to suppress that line's type errors.

**Comment by johnybx** [comment] 2020-07-14 18:18
@jakebailey I mean that I would like to have checking mode basic but I would like to have diagnostic `"x" is not a known member of module` set as information not error as most of these messages are displayed for modules which which I do not develop so it would be nice if it wasn't `reportGeneralTypeIssues` but some independent class of issue. I think it would be much better user experience if we could distinguish these errors based on severity level set.

**Comment by jakebailey** [comment] 2020-08-14 22:01
Closing in favor of #150, which is covering general numpy support.

**Closed by jakebailey** 2020-08-14 22:01 UTC
Labels: enhancement

**Comment by alexeyr** [comment] 2020-09-02 15:36
> PyTorch ships with annotations and stubs, if you believe the signature for FloatTensor's constructor to be wrong you may want to file a bug on their tracker.

My question would be where to find these stubs (at least for `torch` module itself).

**Comment by jakebailey** [comment] 2020-09-02 17:33
They are in their repo, a mix of stubs and inline annotations: https://github.com/pytorch/pytorch

**Comment by AgentIvan** [comment] 2020-09-09 07:26
![image](https://user-images.githubusercontent.com/16723960/92567510-15935680-f27e-11ea-88e9-5b99fe062e4c.png)
The same. It is still not solved.

**Comment by jakebailey** [comment] 2020-09-14 20:56
@AgentIvan This issue is a dupe of #150 (which is not closed); you can follow there.
