### ISSUE TITLE
python.analysis.extraPaths does not import correctly

### ISSUE THREAD

**Issue by anupamdialpad** [microsoft/pylance-release#5747] opened 2024-04-10 06:10 UTC
## Environment data

-   Language Server version: v2024.4.1
-   OS and version: macOS 14.4.1 
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.17

## Code Snippet

<img width="1094" alt="Screenshot 2024-04-10 at 11 23 30 AM" src="https://github.com/microsoft/pylance-release/assets/54094065/acc487b7-459d-4249-a46e-31832fa48eba">

settings.json
```json
{
    "python.terminal.activateEnvironment": true,
    "python.defaultInterpreterPath": "/Users/anupamghosh/workspace/venv/fst2/bin/python",
    "python.analysis.extraPaths": ["/Users/anupamghosh/workspace/venv/fst2/"]
}
```

vscode workspace file
```json
{
    "folders": [
        {   
            "path": "servers"
        },  
        {   
            "path": "firespotter/fstelephony"
        },  
        {   
            "path": "firespotter/fst2"
        }   
    ],  
    "settings": {
        "debug.node.autoAttach": "off"
    }   
}
```

## Logs

Unable to add logLevel Trace
<img width="1061" alt="Screenshot 2024-04-10 at 11 35 46 AM" src="https://github.com/microsoft/pylance-release/assets/54094065/a530b529-20ee-45a2-a4ff-a4d9ee4f60aa">

When I directly open the directory with `code fst2` the imports work correctly. When I open the directory via vscode workspace configuration it doesn't open

**Comment by debonte** [comment] 2024-04-10 15:44
This is a duplicate of #5740.

**Comment by anupamdialpad** [comment] 2024-05-09 06:41
Hi @debonte, The issue has not yet fixed for me. I am using pylance version `v2024.5.1`. 
When I open the directory directly the `extraPaths` works but when I open the same directory from a workspace it doesn't work

**Comment by heejaechang** [comment] 2024-05-09 06:55
for `python.analysis.logLevel`, you need to put it in `settings` section in `code-workspace` file.

```
"settings": {
		"python.analysis.logLevel": "Trace"
	}
```

**Comment by heejaechang** [comment] 2024-05-09 06:58
by the way, folder info you shared

```
{
    "folders": [
        {   
            "path": "servers"
        },  
        {   
            "path": "firespotter/fstelephony"
        },  
        {   
            "path": "firespotter/fst2"
        }   
    ],  
    "settings": {
        "debug.node.autoAttach": "off"
    }   
}
```

and settings you shared

```
{
    "python.terminal.activateEnvironment": true,
    "python.defaultInterpreterPath": "/Users/anupamghosh/workspace/venv/fst2/bin/python",
    "python.analysis.extraPaths": ["/Users/anupamghosh/workspace/venv/fst2/"]
}
```

path for `fst2` seems not matching.

also, location of `fst2/.vscode/settings.json` seems strange as well, it should be at the top of multi workspace root, not sub folder.

probably best way is you sharing [log](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs) so we can take a look at all settings and configurations?

**Comment by heejaechang** [comment] 2024-05-09 07:29
I tried to repro it with `windows` and `linux` with `full path` in `extraPaths` in `.vscode/settings` for `multi root workspace` and all works as expected.

**Comment by anupamdialpad** [comment] 2024-05-09 07:34
Hi @heejaechang, I found the issue. In the settings of `code-workspace` file the location of extraPath of was missing.

The extraPath issue has been solved. Thanks for your help!

Currently the issue is packages installed in the virtualenv are not picking up automatically I have to add them to extraPath to get picked up. Here is the log file 
[vscode-trace.log](https://github.com/microsoft/pylance-release/files/15259111/vscode-trace.log)

**Comment by heejaechang** [comment] 2024-05-09 08:06
> Currently the issue is packages installed in the virtualenv are not picking up automatically I have to add them to extraPath to get picked up. 

can you open a new issue for this? we should run python interpreter at `pythonpath` (python interpreter you selected in vscode) and get `sys.path` that should contain `site-packages` folder of your `virtual env`

[log](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs) should contain those info.

that said, the log you shared `vscode-trace.log` is not full log but some parts of it and it doesn't contain any info we need.

please make sure your log contains these info.

```
Search paths for file:///c%3A/repo/test
  c:\repo\test
  c:\repo\test\src
  c:\repo\test\.venv
  c:\repo\test\.venv\Lib\site-packages
  
Adding fs watcher for library directories:
  file:///c%3A/repo/test/.venv
  file:///c%3A/repo/test/.venv/Lib/site-packages
  
Adding fs watcher for directories:
  file:///c%3A/repo/test
```

**Comment by heejaechang** [comment] 2024-05-09 08:09
you can also use `Pylance: Start Logging` and `Pylance: Stop Logging` command to save those logs to a file and share that with us.

**Closed** 2024-05-09 08:10 UTC
Labels: duplicate
