### ISSUE TITLE
Add import quick action doesn't list the expected value

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5196] opened 2023-12-02 00:22 UTC
I had some code like so:

```python
from typing_extensions import Union

class Options:
   mode: Union[str, None] = None
   address: Union[Tuple[str, int], None] = None <-- Quick action here for `Tuple`
```

The quick action list showed this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/72651355-f648-4510-9bca-32010e6e6985)

Notice how it doesn't include an action to add to my already existing typing_extensions.

**Comment by StellaHuang95** [comment] 2024-02-22 21:41
There are two issues with the fix in my pull request:

1. The `typing_extensions` is not an actual [python standard library](https://docs.python.org/3/library/index.html); it's a third-party library that requires user installation. Pyright treats it as part of the stdlib because it's included in the [typeshed's stdlib folder](https://github.com/python/typeshed/tree/main/stdlib). As a result, pyright won't report a `reportMissingModuleSource` error if a user imports `typing_extensions` but have no corresponding source file. Adding this option to the quick fix or auto imports might potentially cause runtime errors in users' code.
2. As Erik mentioned, we wouldn't want to display both suggestions.  @bschnurr  is currently working on implementing a `pylance create all std indices` command that users can run to match their python version. This solution seems more appropriate for the long term, so just closed my PR.

Relevant issues that Bill's working on:

- https://github.com/microsoft/pylance-release/issues/4993
- https://github.com/microsoft/pylance-release/issues/3785

**Comment by StellaHuang95** [comment] 2024-02-22 21:43
This issue is actually a dupe of https://github.com/microsoft/pylance-release/issues/3785, so maybe I should close this one.

**Closed** 2024-02-22 22:16 UTC
Labels: bug, duplicate
