### ISSUE TITLE
Third party libraries Symbol in Workspaces

### ISSUE THREAD

**Issue by tamutamu** [microsoft/pylance-release#1894] opened 2021-10-01 05:48 UTC
## Environment
  - Language Server version: 2021.9.4
## Expected
  - `Go to Symbol in workspace`(Ctrl + T) command suggest a symbol containing a third party libraries(ex: site-packages).
## Actual
  - `Go to Symbol in workspace`(Ctrl + T) command suggest a symbol without a third party libraries.

Is there way to suggest a symbol that contains a third party libraries.

**Comment by jakebailey** [comment] 2021-10-01 07:04
Duplicate of #35.

**Closed by jakebailey** 2021-10-01 07:04 UTC
Labels: triage
