### ISSUE TITLE
Switching interpreter to Python 3.8.x crashes the server

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#2796] opened 2022-05-10 21:14 UTC
## Environment data
Windows10 LTSC 2021
VSCode 1.67.1
Pylance language server 2022.4.3 (pyright 88f2a424)
Python v2022.6.0

## Expected behavior
Interpreter changed with no isses

## Actual behavior
Server crashes

## Logs

```
[Info  - 12:04:17 AM] (7656) Setting pythonPath for service "PythonTest": "C:\Programs\Python310\python.exe"
[Warn  - 12:04:17 AM] (7656) stubPath d:\Unlinked\GIT\PythonTest\typings is not a valid directory.
[Info  - 12:04:17 AM] (7656) Assuming Python version 3.10
[Info  - 12:04:17 AM] (7656) Assuming Python platform Windows
[Info  - 12:04:17 AM] (7656) Searching for source files
[Info  - 12:04:17 AM] (7656) Found 3 source files
[Error - 12:04:17 AM] Request textDocument/semanticTokens/full/delta failed.
Error: Connection got disposed.
	at Object.dispose (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2114794)
	at Object.dispose (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2165082)
	at c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2161350
[Info  - 12:04:18 AM] (2556) Pylance language server 2022.4.3 (pyright 88f2a424) starting
[Info  - 12:04:18 AM] (2556) Server root directory: C:\Programs\VSCode\data\extensions\ms-python.vscode-pylance-2022.4.3\dist
[Info  - 12:04:18 AM] (2556) No configuration file found.
[Info  - 12:04:18 AM] (2556) No pyproject.toml file found.
[Info  - 12:04:18 AM] (2556) Setting pythonPath for service "PythonTest": "C:\Programs\Python310\python.exe"
[Warn  - 12:04:18 AM] (2556) stubPath d:\Unlinked\GIT\PythonTest\typings is not a valid directory.
[Info  - 12:04:18 AM] (2556) Assuming Python version 3.10
[Info  - 12:04:18 AM] (2556) Assuming Python platform Windows
[Info  - 12:04:18 AM] (2556) Searching for source files
[Info  - 12:04:18 AM] (2556) Found 3 source files
[Info  - 12:04:18 AM] (2556) Background analysis(1) root directory: C:\Programs\VSCode\data\extensions\ms-python.vscode-pylance-2022.4.3\dist
[Info  - 12:04:18 AM] (2556) Background analysis(1) started
[Info  - 12:04:29 AM] (4780) Pylance language server 2022.4.3 (pyright 88f2a424) starting
[Info  - 12:04:29 AM] (4780) Server root directory: C:\Programs\VSCode\data\extensions\ms-python.vscode-pylance-2022.4.3\dist
[Info  - 12:04:29 AM] (4780) No configuration file found.
[Info  - 12:04:29 AM] (4780) No pyproject.toml file found.
[Info  - 12:04:29 AM] (4780) Setting pythonPath for service "PythonTest": "C:\Programs\Python385\python.exe"
[Warn  - 12:04:29 AM] (4780) stubPath d:\Unlinked\GIT\PythonTest\typings is not a valid directory.
[Info  - 12:04:29 AM] (4780) Assuming Python version 3.8
[Info  - 12:04:29 AM] (4780) Assuming Python platform Windows
[Info  - 12:04:30 AM] (4780) Searching for source files
[Info  - 12:04:30 AM] (4780) Found 3 source files
[Info  - 12:04:30 AM] (4780) Background analysis(1) root directory: C:\Programs\VSCode\data\extensions\ms-python.vscode-pylance-2022.4.3\dist
[Info  - 12:04:30 AM] (4780) Background analysis(1) started
[Info  - 12:04:30 AM] (5152) Pylance language server 2022.4.3 (pyright 88f2a424) starting
[Info  - 12:04:30 AM] (5152) Server root directory: C:\Programs\VSCode\data\extensions\ms-python.vscode-pylance-2022.4.3\dist
[Error - 12:04:30 AM] Server initialization failed.
Error: command 'pyright.createtypestub' already exists
	at o.registerCommand (c:\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:29716)
	at Object.registerCommand (c:\Programs\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:30972)
	at t.ExecuteCommandFeature.register (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2220052)
	at t.ExecuteCommandFeature.initialize (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2219631)
	at S.initializeFeatures (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2172196)
	at S.doInitialize (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2160120)
	at async S.start (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2157135)
	at async S.$start (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2163935)
	at async t.Delayer.<anonymous> (c:\Programs\VSCode\data\extensions\ms-python.python-2022.6.0\out\client\extension.js:2:2162206)
[Error - 12:04:30 AM] Pylance client: couldn't create connection to server.
```

**Comment by debonte** [comment] 2022-05-10 21:16
Dupe of #2765

**Closed by debonte** 2022-05-10 21:16 UTC
Labels: duplicate, triage
