### ISSUE TITLE
Pylance stuck analyzing Jupyter notebook with every input, leaving vscode lagging with no prompts

### ISSUE THREAD

**Issue by saipavanc** [microsoft/pylance-release#5539] opened 2024-02-28 19:57 UTC
## Environment data

-   Language Server version: 2024.2.2
-   OS and version: Arch linux 6.7.4-arch1-1
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda, python 3.11.7

With the above configuration, I run into the issue where pylance is stuck analyzing files for so long that I do not get any prompts for the arguments or object methods for several seconds. Here is the output from pylance:

```
2024-02-28 13:42:08.420 [info] (Client) Pylance async client (2024.2.2) started with python extension (2024.0.1)
2024-02-28 13:42:09.001 [info] [Info  - 1:42:09 PM] (53874) Pylance language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c) starting
2024-02-28 13:42:09.002 [info] [Info  - 1:42:09 PM] (53874) Server root directory: file:///home/saipavanchitta/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-28 13:42:09.006 [info] [Info  - 1:42:09 PM] (53874) Starting service instance "codes"
2024-02-28 13:42:09.047 [info] [Info  - 1:42:09 PM] (53874) Setting pythonPath for service "codes": "/bin/python"
2024-02-28 13:42:09.047 [info] [Info  - 1:42:09 PM] (53874) Setting environmentName for service "codes": "3.11.7 (global)"
2024-02-28 13:42:09.073 [info] [Info  - 1:42:09 PM] (53874) Assuming Python version 3.11
2024-02-28 13:42:09.136 [info] [Info  - 1:42:09 PM] (53874) Found 4 source files
2024-02-28 13:42:09.170 [info] [Info  - 1:42:09 PM] (53874) Starting service instance "codes"
2024-02-28 13:42:09.193 [info] [Info  - 1:42:09 PM] (53874) Setting pythonPath for service "codes": "/home/saipavanchitta/miniconda3/envs/scqubits-spc/bin/python"
2024-02-28 13:42:09.193 [info] [Info  - 1:42:09 PM] (53874) Setting environmentName for service "codes": "3.11.7 (global)"
2024-02-28 13:42:09.228 [info] [Info  - 1:42:09 PM] (53874) Assuming Python version 3.11
2024-02-28 13:42:09.300 [info] [Info  - 1:42:09 PM] (53874) Found 4 source files
2024-02-28 13:42:09.699 [info] [Info  - 1:42:09 PM] (53874) Background analysis(1) root directory: file:///home/saipavanchitta/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-28 13:42:09.699 [info] [Info  - 1:42:09 PM] (53874) Background analysis(1) started
2024-02-28 13:42:09.747 [info] [Info  - 1:42:09 PM] (53874) Background analysis(2) root directory: file:///home/saipavanchitta/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-28 13:42:09.750 [info] [Info  - 1:42:09 PM] (53874) Background analysis(2) started
2024-02-28 13:42:09.907 [info] [Info  - 1:42:09 PM] (53874) Indexer background runner(3) root directory: file:///home/saipavanchitta/.vscode/extensions/ms-python.vscode-pylance-2024.2.2/dist (index)
2024-02-28 13:42:09.908 [info] [Info  - 1:42:09 PM] (53874) Indexing(3) started
2024-02-28 13:42:10.452 [info] [Info  - 1:42:10 PM] (53874) scanned(3) 240 files over 1 exec env
2024-02-28 13:42:11.198 [info] [Info  - 1:42:11 PM] (53874) indexed(3) 157 files over 1 exec env
2024-02-28 13:42:11.381 [info] [Info  - 1:42:11 PM] (53874) Indexing finished(3).
2024-02-28 13:42:20.448 [info] [Info  - 1:42:20 PM] (53874) [BG(2)] Long operation: getSemanticTokens range 0:0 - 0:14 at file:///Lecture_5_Sympy.ipynb.py#X34sZmlsZQ%3D%3D (10134ms)
2024-02-28 13:42:24.532 [info] [Info  - 1:42:24 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (3804ms)
2024-02-28 13:42:41.440 [info] [Info  - 1:42:41 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3436ms)
2024-02-28 13:42:41.440 [info] [Info  - 1:42:41 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3436ms)
2024-02-28 13:42:41.441 [info] [Info  - 1:42:41 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (3471ms)
2024-02-28 13:42:50.620 [info] [Info  - 1:42:50 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (9169ms)
2024-02-28 13:42:50.620 [info] [Info  - 1:42:50 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (9169ms)
2024-02-28 13:42:50.620 [info] [Info  - 1:42:50 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (9183ms)
2024-02-28 13:42:54.128 [info] [Info  - 1:42:54 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3213ms)
2024-02-28 13:42:54.128 [info] [Info  - 1:42:54 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3213ms)
2024-02-28 13:42:54.129 [info] [Info  - 1:42:54 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (3261ms)
2024-02-28 13:42:58.513 [info] [Info  - 1:42:58 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3053ms)
2024-02-28 13:42:58.513 [info] [Info  - 1:42:58 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3053ms)
2024-02-28 13:42:58.513 [info] [Info  - 1:42:58 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (3067ms)
2024-02-28 13:43:07.305 [info] [Info  - 1:43:07 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3092ms)
2024-02-28 13:43:07.306 [info] [Info  - 1:43:07 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (3092ms)
2024-02-28 13:43:07.306 [info] [Info  - 1:43:07 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (3137ms)
2024-02-28 13:43:16.543 [info] [Info  - 1:43:16 PM] (53874) [BG(2)] Long operation: checking: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (9206ms)
2024-02-28 13:43:16.543 [info] [Info  - 1:43:16 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#Y303sZmlsZQ%3D%3D (9206ms)
2024-02-28 13:43:18.007 [info] [Info  - 1:43:18 PM] (53874) [BG(2)] Long operation: analyzing: file:///Lecture_5_Sympy.ipynb.py#pylancePrefixCell (10678ms)
```
I have also uploaded my environment configuration, and the Jupyter notebook where I observed this issue in this [repo](https://github.com/saipavanc/shared). Please let me know if I can provide any more info

**Comment by rchiodo** [comment] 2024-02-28 19:59
Thanks for uploading. Without even looking at it, my guess it's because of sympy. Sympy is notoriously slow.

See this issue:
https://github.com/microsoft/pyright/issues/7159

**Comment by rchiodo** [comment] 2024-02-28 20:04
Yeah I can repro with the sympy code in the notebook:

```python
import sympy

x = sympy.Symbol('x', real=True)
x.
```

Any typing in that file causes a bunch of analysis that takes too long.

I'm marking this as a dupe of that Pyright bug.

**Closed by rchiodo** 2024-02-28 20:04 UTC
Labels: needs repro
