### ISSUE TITLE
Some characters are mistaken for invalid identifiers

### ISSUE THREAD

**Issue by wcshds** [microsoft/pylance-release#5656] opened 2024-03-18 19:39 UTC
version: v2024.3.1

## Example
```Python
𣎴="hello world"
print(𣎴)
```

![image](https://github.com/microsoft/pylance-release/assets/8537285/b08b100c-6fb9-4314-b64b-41067ed157f1)

**Comment by debonte** [comment] 2024-03-18 23:59
@erictraut, the `𣎴` character is supported as an indentifier by Python (running this code prints out "hello world"). The problem is that [the surrogate character 55372](https://unicodeplus.com/U+D84C) is missing from `pyright-internal\src\parser\unicode.ts`. I added the following to `unicodeLuSurrogate` and it fixed this issue, but a) I'm not sure that's the correct surrogate table for it to be in and b) I'm assuming there are more characters that are missing.

```python
    55372: [57268],
```

`unicode.ts` says it was built from the [npm `unicode` package](https://github.com/tdanecker/node-unicodetable), which says that it provides data from https://unicode.org/Public/UNIDATA/UnicodeData.txt. That file doesn't contain this surrogate.

Seems like we need to update our tables using a new source of Unicode surrogate info?

**Comment by erictraut** [comment] 2024-03-19 08:41
I'm not sure what to say here. [PEP 3131](https://peps.python.org/pep-3131/#id12) is pretty clear about which character ranges are allowed for identifier starts and continuations. In particular, it says:

> ID_Start is defined as all characters having one of the general categories uppercase letters (Lu), lowercase letters (Ll), titlecase letters (Lt), modifier letters (Lm), other letters (Lo), letter numbers (Nl), the underscore, and characters carrying the Other_ID_Start property. XID_Start then closes this set under normalization, by removing all characters whose NFKC normalization is not of the form ID_Start ID_Continue* anymore.

The character 0xD84C is not in any of these general categories. It's part of the "Cs" category, which doesn't appear in the list above.

This is reinforced by the information in [this document](https://www.unicode.org/Public/4.1.0/ucd/DerivedCoreProperties.txt). Search for "Characters that can start an identifier". Note that this document comes directly from the unicode organization.

I'm guessing that this is explained by one of three things:
1. This is a bug in the CPython implementation where it's not following the spec.
2. The spec has changed since PEP 3131 was written, and the CPython implementation has been amended accordingly.
3. I'm missing something.

More investigation is likely needed to determine which of the above is the explanation.

If we want to use the CPython code as a reference, [here](https://github.com/python/cpython/blob/main/Objects/unicodetype_db.h) is where you can look.

**Comment by wcshds** [comment] 2024-03-19 08:52
@erictraut @debonte I think 0xD84C is used in UTF16. I'm guessing Pylance's Javascript code didn't handle the surrogate pair well and treated 𣎴 (0x233B4) as if it is seperate characters

**Comment by debonte** [comment] 2024-03-20 06:04
I'm working on a fix for this. CPython's character info is currently based on [Unicode 15.1](https://github.com/python/cpython/pull/109560). I'm not sure what version ours is based on, but we're out of date.

**Comment by StellaHuang95** [comment] 2024-03-27 20:21
This issue has been fixed in prerelease version 2024.3.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20243102-27-March-2024-PreRelease)

**Closed by StellaHuang95** 2024-03-27 20:21 UTC
Labels: bug, fixed in next version
