### ISSUE TITLE
type alias highlighting issue

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#1224] opened 2021-05-03 09:21 UTC
## Environment data
-   Language Server version: 2021.4.3 (pyright 320a0a2f)
(activated as the default language server in Python extension settings)
-   OS and version: Windows 10 Pro, Version	10.0.19041 Build 19041
-   Python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

## Expected behaviour
- By default, type aliases (such as `MyClass = _MyClass`) should be highlighted the same as actual types.
- We should have a a way to identify such tokens in semantic/syntactic highlighting options.

## Actual behaviour
- Type aliases are identified as variables, even though the tooltip does show them as "type alias"!
- They are highlighted with the same color as variables (blue), whereas classes appear green.

## Code Snippet / Additional information
Consider the following code:
```python
import os
os._PathLike
os.PathLike
```
_PathLike is the actual class definition. PathLike is an alias, but is the one we're supposed to actually use (for type hints etc).
![image](https://user-images.githubusercontent.com/574187/116860293-a1893280-ac01-11eb-8232-001ed4e7a47d.png)

Tooltip for _PathLike: ![image](https://user-images.githubusercontent.com/574187/116860210-83233700-ac01-11eb-8f69-ad15dfbff837.png)
Tooltip for PathLike: ![image](https://user-images.githubusercontent.com/574187/116860260-96ce9d80-ac01-11eb-9d77-fb0aa47c1103.png)

**Comment by jakebailey** [comment] 2021-05-03 17:31
Dupe of #857.

**Closed by jakebailey** 2021-05-03 17:31 UTC
Labels: triage
