### ISSUE TITLE
Unreachable mark but it is reachable

### ISSUE THREAD

**Issue by simm4256** [microsoft/pylance-release#2093] opened 2021-11-20 14:46 UTC
![image](https://user-images.githubusercontent.com/25508348/142730346-6da74b95-c039-4e58-bd10-c01593b476a2.png)

pylance v2021.11.2
python v3.9,6
os windows10 20H2 19042.1348

**Comment by erictraut** [comment] 2021-11-20 20:11
Thanks for the bug report. This will be fixed in the next release. In the meantime, you can work around the problem by providing a return type annotation for your function:

```python
def tree(len) -> None:
    ...
```

**Comment by bschnurr** [comment] 2021-12-02 21:22
This issue has been fixed in version 2021.12.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021120-2-december-2021)

**Closed by bschnurr** 2021-12-02 21:22 UTC
Labels: bug, fixed in next version

**Comment by zigomir** [comment] 2022-01-07 09:05
Getting same problem on VSC: Version: 1.63.2, Pylance v2022.1.0 and macOS.

Happens after instantiating `DjangoModelFactory` object 🤷‍♂️

**Comment by adrianosmarinho** [comment] 2022-01-10 00:46
> Getting same problem on VSC: Version: 1.63.2, Pylance v2022.1.0 and macOS.
> 
> Happens after instantiating `factory.base.Factory` object from [factoryboy](https://factoryboy.readthedocs.io/en/stable/reference.html#the-factory-class) 🤷‍♂️
> 
> [edit] I guess it's because this method in `BaseFactory` class
> 
> ```python
> def __new__(cls, *args, **kwargs):
>     """Would be called if trying to instantiate the class."""
>     raise errors.FactoryError('You cannot instantiate BaseFactory')
> ```
> 
> If I comment it out, all code becomes reachable again.

Hey @zigomir 
Same setup here, same problem. Pylance marks my code as unreachable after instantiating a factoryboy object 🤷 
It is important to note that the same code was working fine two weeks ago, before I left the office on annual leave.

```python

from api.models import Token
from datetime import datetime
from django.contrib.auth.models import User
from factory.django import DjangoModelFactory


class UserFactory(DjangoModelFactory):
    """
    User Factory to be used on tests.
    """

    password = ""
    is_superuser = False
    username = "test_user"
    first_name = "Test"
    last_name = "User"
    email = "test_user@test.com"
    is_staff = True
    is_active = True
    date_joined = datetime.utcnow()

    class Meta:
        model = User
        django_get_or_create = ("username", "email", "is_active")


class TokenFactory(DjangoModelFactory):
    """
    Token Factory to be used on our tests
    """

    user = UserFactory()
    name = "test_user_token"
    identifier = "2e42a19593f047e080285e49864b0fb6"
    secret = "6ff2dc141c0841e2a43c25be9ae9b097"

    class Meta:
        model = Token
        django_get_or_create = ("user", "name", "identifier")
        
```

**Comment by erictraut** [comment] 2022-01-10 00:51
@adrianosmarinho, the problem you're seeing is [this issue](https://github.com/microsoft/pylance-release/issues/2224), which will be fixed in the next release.

**Comment by adchang21** [comment] 2022-07-26 00:03
I am also encountering this issue, here is a sample of my code. 
<h3> Environment data </h3>

-   Language Server version: 2022.7.40
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```
os.chdir(r'C:\Users\example')
path = r'C:\
![snip](https://user-images.githubusercontent.com/78053758/180894864-fe103358-28bf-477f-919d-b19946a7e869.png)
Users\example'
today = str(date.today())
filename = os.path.join(path, 'example_'+ today + '.txt')

ob=Screenshot_Clipping.Screenshot()
chrome_options = Options()
chrome_options.add_argument("--start-maximized")
driver = webdriver.Chrome(options=chrome_options)

driver.get('https://www.google.com/search?q=aardvark')
WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.XPATH, '//*[@id="fsl"]/a[1]')))
html = driver.page_source
img_url=ob.full_Screenshot(driver, save_path=r'C:\Users\example', image_name='screenshot.png')
print(img_url)

time.sleep(random.randint(2,5))
driver.quit()

with open(filename, 'w', encoding="utf-8") as f:
    f.write(html)
```

The code after driver.quit() is marked as unreachable, even though it very much is.

**Comment by erictraut** [comment] 2022-07-26 00:33
@adchang21, could you provide a self-contained minimal code sample? The sample above references symbols that are presumably imported from somewhere. Am I correct in assuming that you are using the selenium library? If so, are you using the latest version? There is a known bug in earlier versions of selenium that results in this behavior. Try `pip install selenium --upgrade` and see if that fixes your issue.

**Comment by adchang21** [comment] 2022-07-26 00:47
Upgrading selenium fixed it, thank you!

**Comment by rwayan** [comment] 2022-07-26 07:40
> @adchang21, could you provide a self-contained minimal code sample? The sample above references symbols that are presumably imported from somewhere. Am I correct in assuming that you are using the selenium library? If so, are you using the latest version? There is a known bug in earlier versions of selenium that results in this behavior. Try `pip install selenium --upgrade` and see if that fixes your issue.

upgraded to version 4.3.0 but it said code unreachable 

import rqdatac
rqdatac.init()

## code below will treated as unreacable
print("a")

**Comment by erictraut** [comment] 2022-07-26 14:04
@adchang21, it looks like the issue you're hitting is not related to selenium. Your code snippet above references a module called `rqdatac`. Am I correct in assuming that's a reference to the [rqdatac](https://pypi.org/project/rqdatac/) package? If so, which version are you using? The latest version is 2.9.55. When I install that version, I'm not able to repro unreachable code. I'm guessing that you have an older version installed. Please try updating with `pip install rqdatac --upgrade`.

**Comment by erictraut** [comment] 2022-07-26 14:07
This issue is closed. If you got here because you are seeing code that is marked as unreachable by pylance, it is most likely an issue in a library or type stub, not a bug in pylance. If you want help diagnosing the problem, please use the discussion tab.

If you think that it is potentially a bug in pylance, please open a new bug report. Do not use this closed issue. And as with all bug reports, please include a self-contained minimal code example and specify which versions of third-party libraries the code sample imports.
