### ISSUE TITLE
It cannnot autocomplete the OpenCV

### ISSUE THREAD

**Issue by sunshineharry** [microsoft/pylance-release#195] opened 2020-08-01 01:02 UTC
## Environment data

-   Language Server version: 2020.7.4
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda with python 3.7
-   OpenCV version: 3.4.2 ( and I use the OpenCV and OpenCV_contribe in same version)

## Expected behaviour

When I use origian python Language Serve provided by Microsoft, It works. When I coding ```cv2.``` ,it autocompletes ```imread``` etc. It's expected behaviour

## Actual behaviour

It cannnot autocomplete the OpenCV!!!

Well, when conding like that,
```python
import cv2
cv2.
```
It doesn't work.

## Logs

Maybe I don't have it, sorry.

**Comment by sunshineharry** [comment] 2020-08-01 01:11
I don't know how to upload the screenshot, maybe I can email to you

**Comment by sunshineharry** [comment] 2020-08-01 01:17
Well, I know it.
## In ```Expected behaviour```, the following screenshot should be appendixed.
![image](https://user-images.githubusercontent.com/52942042/89090710-4a86d080-d3d7-11ea-92f1-eba9a1272f6a.png)
## In ```Actual behaviour```, the following screenshot should be appendixed.
![image](https://user-images.githubusercontent.com/52942042/89090772-ad786780-d3d7-11ea-8c93-bf4c237a1c55.png)

**Comment by jakebailey** [comment] 2020-08-01 01:19
Duplicate of #138.

**Closed by jakebailey** 2020-08-01 01:19 UTC
Labels: triage

**Comment by ZhouyangFANG** [comment] 2020-11-03 07:55
This problem seems related with Pylance server. Uninstalling Pylance plugin and switching back to default Jedi server can solve it.
