### ISSUE TITLE
Semantic Highlighting producing errors after specifying type of value returned in python function

### ISSUE THREAD

**Issue by akionsight** [microsoft/pylance-release#732] opened 2020-12-11 05:05 UTC
I searched, this is not a duplicate question
## Environment data

-   VS Code version: October 2020
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS and version: macOS Catalina
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Not used
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: python (extension from Microsoft)
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

The Syntax highlighting should continue as normal

## Actual behaviour

The syntax highlighting does not continue as normal

## Steps to reproduce:
<img width="1440" alt="Screen Shot 2020-12-11 at 10 31 30 AM" src="https://user-images.githubusercontent.com/62844691/101865368-1220ab80-3b9c-11eb-9fd8-dcbc3972552b.png">
see the code given above, as seen the print statement does not highlight correctly. this only occurs when the returning datatype is specified.

## Logs
There was noting useful in the logs, only that the language server is up and running
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

## it works but the highlighting is wrong

</p>
</details>

**Comment by judej** [comment] 2020-12-14 18:39
Could you please send the output log from Pylance? Need to know the Pylance version.

**Comment by akionsight** [comment] 2020-12-15 03:13
```logs
[Info  - 8:37:38 AM] Pylance language server 2020.12.2 (pyright 6feebac9) starting
[Info  - 8:37:38 AM] Server root directory: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist
```
These were the logs for PyLance (the version is a little off because I updated it later)

```logs
Info 2020-12-15 08:37:35: Searching for workspace virtual envs in: /Users/nivarsh/Desktop/Harsh/programming/code/webRTC
Info 2020-12-15 08:37:35: Searching for workspace virtual envs in: /Users/nivarsh/Desktop/Harsh/programming/code/webRTC/.direnv
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/Envs
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/.direnv
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/.venvs
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/.virtualenvs
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/.local/share/virtualenvs
Info 2020-12-15 08:37:35: Searching for global virtual envs in: /Users/nivarsh/envs
Info 2020-12-15 08:37:35: Found: /usr/bin/python --> /usr/bin/python
Info 2020-12-15 08:37:35: Found: /usr/bin/python2.7 --> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Info 2020-12-15 08:37:35: Found: /usr/include/python2.7 --> ../../System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
Error 2020-12-15 08:37:35: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.9'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.9'
}
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
Error 2020-12-15 08:37:35: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.9'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.9'
}
Error 2020-12-15 08:37:35: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2020-12-15 08:37:35: Failed to parse version from path: /usr/bin/python Error: invalid version python
    at l (/Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:9:88680)
    at Object.a [as parseVersion] (/Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:9:87989)
    at h.buildEnvInfo (/Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:78:27346)
    at e (/Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:78:26791)
    at Array.map (<anonymous>)
    at /Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:78:27207
    at o (/Users/nivarsh/.vscode/extensions/ms-python.python-2020.12.422005962/out/client/extension.js:1:48521)
> conda --version
> ~/opt/anaconda3/bin/conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/local/bin/python3 ~/.vscode/extensions/ms-python.python-2020.12.422005962/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/opt/anaconda3/bin/conda env list
Python interpreter path: /usr/local/bin/python3
Starting Pylance language server.

```

This is the python extension test log

the log for `python test log` was empty

**Comment by akionsight** [comment] 2020-12-15 03:15
![image](https://user-images.githubusercontent.com/62844691/102166301-c9296980-3eb1-11eb-848f-950c37bf3e6a.png)

**Comment by akionsight** [comment] 2020-12-21 02:39
even though I upgraded the pylance release. The same error still occours

**Comment by bschnurr** [comment] 2020-12-21 16:27
can you send the Pylance logs with trace enabled in your settings.json? `"python.analysis.logLevel": "Trace",`

**Comment by akionsight** [comment] 2020-12-25 06:38
I enabled trace in the `settings.json` and these are the logs now

```logs
[Info  - 12:05:30 PM] Pylance language server 2020.12.2 (pyright 6feebac9) starting
[Info  - 12:05:30 PM] Server root directory: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist
[Info  - 12:05:31 PM] No configuration file found.
[Info  - 12:05:31 PM] Setting pythonPath for service "lol": "/usr/local/bin/python3"
Search paths found for configured python interpreter:
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/nivarsh/Library/Python/3.9/lib/python/site-packages
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
[Error - 12:05:31 PM] stubPath /Users/nivarsh/Desktop/Harsh/programming/lol/typings is not a valid directory.
[Info  - 12:05:31 PM] Assuming Python version 3.9
[Info  - 12:05:31 PM] Assuming Python platform Darwin
[Info  - 12:05:31 PM] Searching for source files
[Info  - 12:05:31 PM] No source files found.
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (17ms)
[FG] parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/builtins.pyi [fs read 3ms] (470ms)
[FG] binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/builtins.pyi (208ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[Info  - 12:05:31 PM] Background analysis(1) root directory: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist
[Info  - 12:05:31 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY:0:4 ...
[FG]   parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (2ms)
[FG]   binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] completion at /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY:0:4 [found 7 items] (13ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY ...
[BG(1)]   parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (41ms)
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (5ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[FG] parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [fs read 3ms] (139ms)
[FG] binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi (4ms)
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[FG] parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi [fs read 2ms] (30ms)
[FG] binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi (4ms)
[FG] parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/typing.pyi [fs read 2ms] (339ms)
[FG] binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/typing.pyi (94ms)
[FG] completion at /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY:0:8 ...
[FG]   parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (2ms)
[FG]   binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[FG] completion at /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY:0:8 (3ms)
[BG(1)]   parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/builtins.pyi [fs read 9ms] (865ms)
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[BG(1)]   binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/builtins.pyi (329ms)
[BG(1)]   binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[BG(1)]   checking: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (2ms)
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1244ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY ...
[BG(1)]   parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (2ms)
[BG(1)]   binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[BG(1)]   checking: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY ...
[BG(1)]     parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [fs read 1ms] (49ms)
[BG(1)]     binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi (5ms)
[BG(1)]   checking: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (58ms)
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (61ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
[FG] binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: analyze
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY ...
[BG(1)]   parsing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[BG(1)]   binding: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (1ms)
[BG(1)]   checking: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY ...
[BG(1)]     parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi [fs read 2ms] (13ms)
[BG(1)]     binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi (3ms)
[BG(1)]     parsing: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/typing.pyi [fs read 2ms] (83ms)
[BG(1)]     binding: /Users/nivarsh/.vscode/extensions/ms-python.vscode-pylance-2020.12.2/dist/typeshed-fallback/stdlib/3/typing.pyi (30ms)
[BG(1)]   checking: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (231ms)
[BG(1)] analyzing: /Users/nivarsh/Desktop/Harsh/programming/lol/mL.PY (234ms)
Background analysis message: resumeAnalysis
```

**Comment by MalcolmMielle** [comment] 2021-04-06 08:58
I was able to fix this by desactivating the " Python for VSCode extension" extension by Thomas Haakon Townsend (htanks to this comment https://github.com/microsoft/pylance-release/issues/862#issuecomment-783313780). It seems to be a problem of conflicting extensions.

**Comment by akionsight** [comment] 2021-04-06 14:35
> Python for VSCode extension

Yes, seems to work for me too

**Comment by AlexanderDudnyk** [comment] 2021-04-06 14:48
> I was able to fix this by desactivating the " Python for VSCode extension"
I can confirm. This solved the problem for me. Thanks!

**Comment by jakebailey** [comment] 2021-04-06 17:28
I see. That seems to account for everyone who was commenting on this thread, so if the fix is just to remove that extension (https://marketplace.visualstudio.com/items?itemName=tht13.python), then we can close this and if this repeats again see if people have that mistakenly installed.

That extension hasn't been updated in 5 years, so who knows what's lurking there.

**Closed by jakebailey** 2021-04-06 17:28 UTC
Labels: in backlog, needs investigation

**Comment by h12sw06** [comment] 2022-09-03 05:08
I'm using a temporary solution.
It's a way to create a meaningless def _(): pass.
```
def function() -> str:
  def _():
    pass

  return 'Hello World!'

```
