### ISSUE TITLE
Support lazy loading individual virtualenvs in a multi-root workspace

### ISSUE THREAD

**Issue by pcasdf** [microsoft/pylance-release#6009] opened 2024-06-13 04:35 UTC
My company uses a monorepo and multi-root VS Code workspace with over 40 Python projects. On initial startup of VS Code, the Python extension takes a ton of CPU and memory because it starts indexing every virtualenv. I really wish there were a config that allows us to choose to only begin indexing a virtualenv when a file within that project / sub-root is opened.

**Comment by heejaechang** [comment] 2024-06-13 17:25
good idea. something I will do soon.

**Comment by rchiodo** [comment] 2024-06-25 21:50
This issue has been fixed in prerelease version 2024.6.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246102-25-June-2024-PreRelease)

**Closed by rchiodo** 2024-06-25 21:50 UTC
Labels: enhancement, fixed in next version (main), needs repro

**Comment by pcasdf** [comment] 2024-06-25 21:54
🙏 Y'all rock! Thank you so much!

**Comment by rchiodo** [comment] 2024-06-25 21:59
I should explain how to use it. Well actually @heejaechang would be better at doing that. He implemented it :)

**Comment by pcasdf** [comment] 2024-06-25 21:59
Was just about to ask, since it doesn't seem to be the default -- I don't see the setting under `python.*` either.

**Comment by heejaechang** [comment] 2024-06-25 22:04
Hi pcasdf. there is no setting. it is a new default behavior. we were postponing indexing third party libraries until there is a file opened from a workspace, but we didn't do that for user files. now we will postpone any file (third party or user file) until a file is opened for the workspace.

**Comment by pcasdf** [comment] 2024-06-25 22:05
@heejaechang is it intended that given this structure:
```
root
- project a
- - main.py
- project b
- project c
```
if I open `main.py` in project a, I should see indexing begin for project b and c as well? That was the behavior that I described originally, which seems to still occur.

**Comment by pcasdf** [comment] 2024-06-25 22:10
> @heejaechang is it intended that given this structure:
> 
> ```
> root
> - project a
> - - main.py
> - project b
> - project c
> ```
> 
> if I open `main.py` in project a, I should see indexing begin for project b and c as well? That was the behavior that I described originally, which seems to still occur.

To clarify, my hope is that I can open a file in project a, and project b and c should not try to index.
Either way, the change that you made is still a huge improvement for us, because not all of our devs even touch Python files, but we share a single workspace among everyone.

**Comment by heejaechang** [comment] 2024-06-25 22:41
are you using multi root workspace as in vscode's multi root workspace support? or are you using it as different meaning?

if you have multi root workspace where root is
```
project a
    main.py
project b
project c
````
opening `main.py` won't cause `project b or c` to start indexing.

if you have 1 workspace as `root` and just have multiple folders under it as `project a/b/c` and then call it multi-root workspace, current change won't do anything.

**Comment by pcasdf** [comment] 2024-06-25 22:52
We do use multi-root project with structure similar to:
```
root
project a
project b
project c
```
But I also removed root, leaving it as:
```
project a
project b
project c
```
And I see output similar to:
```
2024-06-25 22:48:39.277 [info] [Info  - 10:48:39 PM] (202134) Starting service instance "a"
2024-06-25 22:48:39.277 [info] [Info  - 10:48:39 PM] (202134) Starting service instance "b"
2024-06-25 22:48:39.286 [info] [Info  - 10:48:39 PM] (202134) Starting service instance "c"
2024-06-25 22:48:40.554 [info] [Info  - 10:48:40 PM] (202134) Background analysis(24) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:40.555 [info] [Info  - 10:48:40 PM] (202134) Background analysis(24) started
2024-06-25 22:48:40.567 [info] [Info  - 10:48:40 PM] (202134) Background analysis(1) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:40.571 [info] [Info  - 10:48:40 PM] (202134) Background analysis(1) started
2024-06-25 22:48:40.575 [info] [Info  - 10:48:40 PM] (202134) Background analysis(3) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:40.575 [info] [Info  - 10:48:40 PM] (202134) Background analysis(23) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:40.577 [info] [Info  - 10:48:40 PM] (202134) Background analysis(23) started
2024-06-25 22:48:40.577 [info] [Info  - 10:48:40 PM] (202134) Background analysis(3) started
2024-06-25 22:48:40.579 [info] [Info  - 10:48:40 PM] (202134) Background analysis(16) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:40.580 [info] [Info  - 10:48:40 PM] (202134) Background analysis(20) root directory: file:///home/discord/.vscode-server/extensions/ms-python.vscode-pylance-2024.6.102%2Bdiscord.3/dist
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Setting pythonPath for service "a": "/home/discord/.virtualenvs/a/bin/python"
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Setting environmentName for service "a": "3.7.17 (a venv)"
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) No include entries specified; assuming /home/discord/discord/a
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Auto-excluding **/node_modules
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Auto-excluding **/__pycache__
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Auto-excluding **/.*
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Assuming Python version 3.7.17.final.0
2024-06-25 22:48:42.932 [info] [Info  - 10:48:42 PM] (202134) Found 441 source files
2024-06-25 22:48:44.091 [info] [Info  - 10:48:44 PM] (202134) Setting pythonPath for service "b": "/home/discord/.virtualenvs/b/bin/python"
2024-06-25 22:48:44.093 [info] [Info  - 10:48:44 PM] (202134) Setting environmentName for service "b": "3.11.9 (b venv)"
2024-06-25 22:48:44.093 [info] [Info  - 10:48:44 PM] (202134) No include entries specified; assuming /home/discord/discord/b
2024-06-25 22:48:44.094 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/node_modules
2024-06-25 22:48:44.094 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/__pycache__
2024-06-25 22:48:44.094 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/.*
2024-06-25 22:48:44.094 [info] [Warn  - 10:48:44 PM] (202134) stubPath file:///home/discord/discord/b/stubs is not a valid directory.
2024-06-25 22:48:44.094 [info] [Info  - 10:48:44 PM] (202134) Assuming Python version 3.11.9.final.0
2024-06-25 22:48:44.094 [info] [Info  - 10:48:44 PM] (202134) Found 6443 source files
2024-06-25 22:48:44.620 [info] [Info  - 10:48:44 PM] (202134) Setting pythonPath for service "c": "/home/discord/.virtualenvs/c/bin/python"
2024-06-25 22:48:44.620 [info] [Info  - 10:48:44 PM] (202134) Setting environmentName for service "c": "3.11.9 (c-env venv)"
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) No include entries specified; assuming /home/discord/discord/discord_clyde
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/node_modules
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/__pycache__
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) Auto-excluding **/.*
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) Assuming Python version 3.11.9.final.0
2024-06-25 22:48:44.621 [info] [Info  - 10:48:44 PM] (202134) Found 876 source files
```

Maybe I misunderstand how the indexing works, but this step usually seems to take a lot of CPU.

I do see now a separate step when I open a file under a separate project:
```
2024-06-25 22:51:15.762 [info] [Info  - 10:51:15 PM] (202134) [IDX(53)] Long operation: index execution environment file:///home/discord/repo/a (3975ms)
2024-06-25 22:51:15.798 [info] [Info  - 10:51:15 PM] (202134) [IDX(53)] Long operation: index packages file:///home/discord/repo/a (4058ms)
2024-06-25 22:51:15.798 [info] [Info  - 10:51:15 PM] (202134) indexed(53) 258 files over 1 exec env
2024-06-25 22:51:15.887 [info] [Info  - 10:51:15 PM] (202134) Indexing finished(53).
2024-06-25 22:51:17.082 [info] [Info  - 10:51:17 PM] (202134) [BG(5)] Long operation: checking: file:///home/discord/repo/a/a/a/user.py (6362ms)
2024-06-25 22:51:17.083 [info] [Info  - 10:51:17 PM] (202134) [BG(5)] Long operation: analyzing: file:///home/discord/repo/a/a/a/user.py (6881ms)
```

So is this where the actual indexing occurs?

**Comment by pcasdf** [comment] 2024-06-25 22:56
I think I understand now that that's where the indexing occurs. Sorry for my confusion!

**Comment by heejaechang** [comment] 2024-06-25 22:56
ya, the second one is when indexing started. so if you are saying the first one takes a lot of cpus, it could be something else taking time. also, you can do `python.analysis.indexing: false` to see whether CPU issue still persist.

**Comment by heejaechang** [comment] 2024-06-25 23:05
> I think I understand now that that's where the indexing occurs. Sorry for my confusion!

don't worry about it, anyway, if there is other perf (CPU) issue outside of indexing, can you provide us some logs so we can take a look what is going on?

https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-cpuprofiles

basically steps you need to do is

1. start vscode and open multi root workspace as you used to do
2. wait until `vscode` goes `idle` (make sure pylance is loaded. you can create `untitled` python file to make that happen)
3. open `workspace settings json` file
4. invoke `pylance start profiling` command
5. change someting in the `setting` file such as adding `python.analysis.indexing: false` and save
6. wait until `vscode` goes `idle`
7. invoke `pyalnce stop profiling` command
8. provide us *.cpuprofile files created by pylance (message box should tell you where those files are)

it would help us a lot to find out where CPUs are used for the part you mentioned.

**Comment by pcasdf** [comment] 2024-06-26 03:32
I see now that indexing appears to complete fairly quickly, even in a large 7k Python file sub-project. But when opening a file after the Python extension just began to load, it appears that the background analysis tasks may be blocking before allowing indexing to begin. This is only a problem for us since we have so many projects, or "service instances" as they're named in the output.

Here are two profiles. The first one was after disabling indexing, and the second is after enabling indexing. 
[pyright-cpuprofile.tar.gz](https://github.com/user-attachments/files/15981923/pyright-cpuprofile.tar.gz)
[pyright-cpuprofile-2.tar.gz](https://github.com/user-attachments/files/15981924/pyright-cpuprofile-2.tar.gz)

**Comment by heejaechang** [comment] 2024-06-26 16:47
no worry. thank you for providing the data!

**Comment by heejaechang** [comment] 2024-06-27 00:15
found the issue. dupe of https://github.com/microsoft/pylance-release/issues/6046
