### ISSUE TITLE
constant definition in __init__

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#2775] opened 2022-05-05 04:39 UTC
Pylance thinks a class member declaration is a definition, and thus doesn't allow the definition of the constant.

```python3
class C:
    BANANAS: int

    def __init__(self, b: int) -> None:
        self.BANANAS = b
```

## Expected behavior

no error
There is no redefinition. There is only one definition.

## Actual behavior

`"BANANAS" is constant (because it is uppercase) and cannot be redefined Pylance[reportConstantRedefinition]`

## Environment data

-   Language Server version: v2022.4.3
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
-   Python › Analysis: Type Checking Mode: strict

**Comment by erictraut** [comment] 2022-05-05 04:43
This is intended behavior. All-caps identifiers are meant to be used for constants, not for variables. If you don't want this flagged as an error, you can leave the `reportConstantRedefinition` option disabled. This is a strict-mode check, and it's intentionally fairly opinionated.

**Comment by erictraut** [comment] 2022-05-05 04:45
If your intent is to create a read-only instance variable (as opposed to a constant declaration), the way to do that is with a `Final` annotation, like this:

```python
from typing import Final

class C:
    bananas: Final[int]

    def __init__(self, b: int) -> None:
        self.bananas = b
```

**Comment by beauxq** [comment] 2022-05-05 04:46
What would a constant instance member look like?

**Comment by beauxq** [comment] 2022-05-05 05:02
Whether we call it a constant is irrelevant.

There is no "redefining" of anything in this example.
Pylance says that there is "redefining", so Pylance is wrong.

**Comment by erictraut** [comment] 2022-05-05 05:24
A constant instance variable would look like this:

```python
class C:
    def __init__(self) -> None:
        self.BANANAS = 2
```

I don't know why you'd want a constant instance variable though. If it's a constant, just define it within the class or global scope.

Constants must be assigned a value at the time they are declared.

Like I said, if you don't like the way this rule works, you can leave it disabled. It is not enabled by default.

**Comment by beauxq** [comment] 2022-05-05 05:26
> Constants must be assigned a value at the time they are declared.

So why doesn't it report any problem with this?

```python3
class C:
    BANANAS: int
```

**Comment by erictraut** [comment] 2022-05-05 05:34
The rule detects and reports cases where a constant (i.e. a symbol that is named with all-caps) is assigned a value in a location other than when it is initially declared.

**Comment by beauxq** [comment] 2022-05-05 05:36
That's not what it's saying that it is detecting.

**Comment by beauxq** [comment] 2022-05-05 05:54
You could change what it's reporting to match what it's detecting, or you could change what it's detecting to match what it's reporting.

Either way would be ok.

But right now, what it's reporting does not match what it's detecting.

**Comment by erictraut** [comment] 2022-05-05 06:04
The rule is working as designed, and we aren't going to change the name of the rule. If you find the documentation or the wording of the diagnostic message confusing, we could consider changing that.

**Comment by beauxq** [comment] 2022-05-05 06:14
I don't find it confusing. I find it to be reporting something that is objectively false.

**Comment by erictraut** [comment] 2022-05-05 06:48
You have declared a variable within the class scope and given it a name that implies it's a constant. You've chosen not to initialize it with a constant value. Then you've attempted to overwrite the class-scoped constant with an instance variable of the same name and assign it a value.

There's an argument to be made that we should add a separate diagnostic check for the condition where a constant is declared but not assigned a value, but that probably wouldn't fall under `reportConstantRedefinition`.

In any case, now that you understand how the `reportConstantRedefinition` check works, you can either adapt your code accordingly or choose to leave the check disabled.

**Comment by beauxq** [comment] 2022-05-05 10:33
> You have declared a variable within the class scope

This is false.

[PEP 526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) says that it is in the instance scope and that it "**should be initialized in `__init__` or `__new__`**".

**Comment by debonte** [comment] 2022-05-11 00:38
> [PEP 526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) says that it is in the instance scope and that it "**should be initialized in `__init__` or `__new__`**".

@beauxq, that section of PEP 526 is written in a confusing way. If you read down a bit further to the paragraph that begins with "`stats` is intended to be a class variable," you'll see that when the authors used the terms "instance variable" and "class variable" in the comments in the `BasicStarship` class, they are referring to how those variables are intended to be **used**, rather than to their **scope**. Specifically, they are saying that `captain` and `damage` are class variables (i.e. variables defined at class scope) that are intended to be set on instances in `__init__`.

Eric recently [added some Pyright documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#class-and-instance-variables) that covers the behavior of class and instance variables. Take a look. Hopefully it will clarify things for you.

In any case, `reportConstantRedefinition` is behaving correctly here.

**Closed by debonte** 2022-05-11 00:38 UTC
Labels: triage

**Comment by beauxq** [comment] 2022-05-11 05:39
> If you read down a bit further to the paragraph that begins with "`stats` is intended to be a class variable," you'll see that when the authors used the terms "instance variable" and "class variable" in the comments in the `BasicStarship` class, they are referring to how those variables are intended to be **used**, rather than to their **scope**. Specifically, they are saying that `captain` and `damage` are class variables (i.e. variables defined at class scope) that are intended to be set on instances in `__init__`.

That is talking about variables that are initialized in the class. That doesn't apply to anything we've been talking about here.
