### ISSUE TITLE
Rename symbol: No result

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#441] opened 2020-10-01 04:47 UTC
## Environment data

-   Language Server version: Pylance language server 2020.9.6 (pyright c52b78aa)
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9

## Expected behaviour

Renaming a function argument renames its usage within the function 

## Actual behaviour

`No result`

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
def go(foo: str) -> str:
    return foo
```
![recording](https://user-images.githubusercontent.com/125105/94769238-eabb9e80-03f4-11eb-90ec-2870978b0635.gif)

**Comment by tekumara** [comment] 2020-10-01 05:05
Have upgraded and am still experiencing this with Pylance language server 2020.9.7 (pyright a0620921)

**Comment by erictraut** [comment] 2020-10-01 15:24
Thanks for the bug report.

I'm not able to repro this in either Pylance or Pyright. Do you have any non-default settings enabled that might affect this?

**Comment by VladimortZA** [comment] 2020-10-02 06:51
I'm also experiencing this exact same issue. Going to try this on another os with a fresh install and report back.

**Comment by VladimortZA** [comment] 2020-10-02 08:51
Ok so I've discovered something, but I'm not yet sure if this is related to pylance itself.

I'm able to perform a rename in a workspace without a venv. As soon as I create a new venv then I'm unable to rename.
@tekumara Can you confirm this behavior on your side?

**Comment by tekumara** [comment] 2020-10-03 05:01
Ah, so in my case it's because I haven't opened a folder yet. This is how I repo:

Open a new VSCode window, and open a single file. Rename symbol will fail in that file. In the same window now open the file's folder. Rename symbol will succeed.

@VladimortZA are you using a _pyrightconfig.json_? If you are, check the `include` or `exclude` options are correct if they exist. NB: `include: "."` is assumed if not present.

**Comment by erictraut** [comment] 2020-10-03 05:29
Good clue!

Interesting, it looks like this might be a bug in VS Code. The language server isn't receiving an `onRenameRequest` callback if I open a file and attempt to rename a symbol. If I open a folder and then open a file within it, the rename request is received as expected.

@jakebailey, any thoughts about this?

**Comment by jakebailey** [comment] 2020-10-03 06:00
Single file mode has always been a bit shoddy, but it might be an artifact of how the core extension manages the LS connection. A test would be to repeat the same thing with the pyright extension (which doesn't do anything but start the client for all Python requests).

**Comment by erictraut** [comment] 2020-10-03 06:01
I already confirmed that the same thing occurs with the Pyright extension, so that would seem to indicate it's a problem with VS Code, not the core Python extension.

**Comment by jakebailey** [comment] 2020-10-03 06:24
Very strange. I haven't seen this before (and quick searching the VS Code issues doesn't net anything, but there are literally a hundred thousand issues).

**Comment by MiMiMeowMeow** [comment] 2020-12-10 18:24
I have same problem.  Must be pretty hard to track down the cause beacuse everybody has different setup...

Python 3.7.7 64-bit.  Pylance 2020.12.1, Python 2020.11.371526539

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by MiMiMeowMeow** [comment] 2020-12-13 20:42
Looks like is unrelated to size of the file but the extension of the file.  It looks like if the extension is not ".py" you will get this problem.  Seen it happen on ".pyw" files and it works fine when renamed to ".py".  Should work on all files extentions associated with python.  Here are a few:

    "files.associations": {
        "*.py*":       "python",
        "*.spec":      "python",
        "SConstruct":  "python",
        "SConscript":  "python"
    }

**Comment by paulcsimon** [comment] 2020-12-13 20:55
For me this happens when the file is in a project subfolder. In a flat project structure (all files beside each other in the opened folder) the command works as expected. Since all of my projects contain a more or less complex folder structure the bug is quite annoying.

**Comment by jakebailey** [comment] 2020-12-14 18:58
We only support python in py and pyi files; any other format isn't supported (and overriding it probably confuses Pylance). I think pyw is the same syntax, so potentially that could be supported, but this is the first time I've seen it in practice.

**Comment by MiMiMeowMeow** [comment] 2020-12-14 19:13
pyw extention are for windowed python programs created from wxpython, pyqt, tkinter. 
spec files are pyinstaller files that are writen in Python. Scons files are also writen in Python.

**Comment by jakebailey** [comment] 2020-12-15 20:47
Just to cross-link it, for extensions that aren't py or pyi, see #739.

**Comment by jakebailey** [comment] 2021-01-04 20:48
@MiMiMeowMeow #739 should be fixed in the next release; I don't know if I can close this issue though as the original issue was not file extension related.

**Comment by paulcsimon** [comment] 2021-01-04 20:54
No, under no circumstances can this be closed. The original issue hasn't been fixed! #739 is completely unrelated to #441.

**Comment by steevelaquitaine** [comment] 2021-02-05 14:32
What solved it for me was to:
1. Open Folder - Select my project folder ...
2. Make sure every subfolders had an __init__.py
3. Make sure Pylance does not complain about anything under VSCODE "PROBLEMS" tab (Ctrl + J for access)
4. Then selecting the variable - right click - rename symbol - I rename it - Enter.
... and it worked.

**Comment by majidhas** [comment] 2021-03-05 11:58
For me, the problem was Pylance itself....for temporary solving, you can change the "python.languageServer" in setting json file from "Pylance" to "Microsoft" and then it works with Microsoft.

**Comment by H4ndsomeJohn** [comment] 2021-03-18 13:33
I meet this issue, too. But when I try to rename this symbol again, it worked. I don't know why.

**Comment by edmond-irani** [comment] 2021-03-18 18:29
> I meet this issue, too. But when I try to rename this symbol again, it worked. I don't know why.

I am experiencing the same thing. Sometimes does not work on the first shot, but worked in the second time.

**Comment by jakebailey** [comment] 2021-03-18 18:31
The fact that it fails the first time but succeeds the second time is interesting. I see this with other calls as well, like when I reproduced #227 (which is go-to-def, not rename). I'm wondering if this is all some common issue.

**Comment by K4ndo** [comment] 2021-03-18 19:05
I experience the very same issue. Whenever im trying to rename or go-to-def for the first time in a file it does not work. Repeating either command is working just fine though

**Comment by AG-LC** [comment] 2021-03-22 13:38
> The fact that it fails the first time but succeeds the second time is interesting. I see this with other calls as well, like when I reproduced #227 (which is go-to-def, not rename). I'm wondering if this is all some common issue.

I have both issues: go-to-def and rename work on the second try only (the first yields "no results"). After doing that in one file, it seems to keep working in this file, but the other open ones still have the issue.

This is VSCode 1.54.3 (system setup) on Windows 10, in a venv.

**Comment by erictraut** [comment] 2021-03-22 16:11
This is related to issue https://github.com/microsoft/pylance-release/issues/1069. As I mentioned in that thread, my investigation leads me to think this is a bug in the core Python extension.

**Comment by jakebailey** [comment] 2021-03-22 17:59
See https://github.com/microsoft/vscode-python/issues/15727; this is a bug in the core extension and we'll fix it there.

**Comment by jakebailey** [comment] 2021-03-22 22:04
Just to show the original issue working:

![pylance441](https://user-images.githubusercontent.com/5341706/112064167-c7f68100-8b1f-11eb-9c22-8ae70552357d.gif)

I'll close this (and the numerous other issues the bug caused) when the core extension's point release is done.

**Comment by jakebailey** [comment] 2021-03-24 18:14
This is now fixed in the core extension (v2021.3.680753044).

**Closed by jakebailey** 2021-03-24 18:14 UTC
Labels: waiting for upstream

**Comment by Hubro** [comment] 2021-04-27 08:12
Should this be fixed in the current stable release? I'm still getting "No result." when trying to rename a simple variable in Python. Should I open a new bug report?

![image](https://user-images.githubusercontent.com/597206/116208180-ec5a0480-a740-11eb-80ba-d3cf91f09370.png)

![image](https://user-images.githubusercontent.com/597206/116208265-0693e280-a741-11eb-81d0-4d9a6dfca40c.png)

**Comment by K4ndo** [comment] 2021-04-27 11:02
The error does not occure in the current stable release. Everthing works perfectly fine for me using 1.55.2

**Comment by jakebailey** [comment] 2021-04-27 22:43
Yes, please file a new issue. This issue was caused by a client bug that's since been fixed.

**Comment by ivan0kurnia** [comment] 2021-08-03 15:19
Hi! In my case this seems to happen when opening a simple file in an untrusted [yet] workspace. It doesn't happen when I open a project (not a single file) in a trusted workspace.

**Comment by jakebailey** [comment] 2021-08-04 19:54
The Python extension and Pylance don't (yet) support untrusted workspaces, so no features are going to work as the Python extension doesn't start Pylance.

**Comment by DervishD** [comment] 2021-09-15 07:34
I'm sorry to say that this still happens for `.pyw` files under VSCode 1.60.1 and Pylance v2021.9.1.

As soon as I rename the offending file to `.py`, the rename symbol function works.

This is happening in a trusted folder.

Is there anything I can do in order to provide more useful information?
Thanks in advance.

**Comment by jakebailey** [comment] 2021-09-15 07:38
That would be #1636.

**Comment by DervishD** [comment] 2021-09-15 08:14
I checked that, @jakebailey , but apparently Pylance now supports `.pyw` files, too, per #739, so renaming symbols should work. This is a pure Python file, not some syntax derived from Python, like SageMath.

Also, the file mode is properly set as `Python`, so I don't get why this should be happening.

Anything wrong on my side that I can check? Thanks a lot for the reply, @jakebailey .

**Comment by jakebailey** [comment] 2021-09-15 16:33
I'm not sure what you mean. The linked issue may talk about .sage, but the issue is more generic around anything that's not just a .py or .pyi. The language you have set the file to doesn't change that we are excluding other extensions from our list of source field where refactoring is valid.

**Comment by DervishD** [comment] 2021-09-15 16:55
Oh, sorry, my bad then. I assumed that since Pylance supported `.pyw` files, that included refactoring.

Any possibility of including `.pyw` as a supported extension for refactoring? I know that extension is *very* platform specific, as it's only for Windows, and I suppose those files could be renamed and then using some fix they will still work with the proper (non-console) Python for Windows interpreter, but I'm just curious if adding that extension is an easy fix or if it has some deeper implications.

And again, @jakebailey thanks **A LOT** for your help. I was seeing the whole picture 😃

**Comment by jakebailey** [comment] 2021-09-15 17:21
That is precisely what #1636 covers.
