### ISSUE TITLE
Inaccesible code

### ISSUE THREAD

**Issue by LuisMorenoSerrano** [microsoft/pylance-release#6130] opened 2024-07-13 15:05 UTC
<h3> Environment data </h3>

-   Language Server version: 2024.7.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12.3
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
def scalar_product(vector1: tuple, vector2: tuple) -> int:
    # Error control: "raise" shows as inaccesible code
    if not isinstance(vector1, tuple) or not isinstance(vector2, tuple):
        raise TypeError("Ambos argumentos deben ser tuplas.")

    # Error control: Using variable "raise" shows ok
    type_err = not isinstance(vector1, tuple) or not isinstance(vector2, tuple)

    if type_err:
        raise TypeError("Ambos argumentos deben ser tuplas.")

    # Another error control
    if len(vector1) != len(vector2):
        raise ValueError("Las tuplas deben tener la misma longitud.")

    # Compute scalar product
    return sum(a * b for a, b in zip(vector1, vector2))
```
<h3> Expected behavior </h3>

Code line
```python
raise TypeError("Ambos argumentos deben ser tuplas.")
```
should be accesible

<h3> Actual behavior </h3>

Code line
```python
raise TypeError("Ambos argumentos deben ser tuplas.")
```
is not accesible due to Pylance message

<h3> Logs </h3>

```
2024-07-13 16:59:15.089 [info] (Client) Pylance async client (2024.7.1) started with python extension (2024.10.0)
2024-07-13 16:59:15.509 [info] [Info  - 16:59:15] (46715) Pylance language server 2024.7.1 (pyright version 1.1.369, commit 1168be71) starting
2024-07-13 16:59:15.509 [info] [Info  - 16:59:15] (46715) Server root directory: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist
2024-07-13 16:59:15.528 [info] [Info  - 16:59:15] (46715) Starting service instance "<default>"
2024-07-13 16:59:15.558 [info] (46715) No pyproject.toml file found.
2024-07-13 16:59:15.558 [info] [Info  - 16:59:15] (46715) Setting pythonPath for service "<default>": "/bin/python3"
2024-07-13 16:59:15.558 [info] [Info  - 16:59:15] (46715) Setting environmentName for service "<default>": "3.12.3 (global)"
2024-07-13 16:59:15.558 [info] [Info  - 16:59:15] (46715) No include entries specified; assuming /<default workspace root>
2024-07-13 16:59:15.558 [info] [Info  - 16:59:15] (46715) Auto-excluding **/node_modules
2024-07-13 16:59:15.559 [info] [Info  - 16:59:15] (46715) Auto-excluding **/__pycache__
2024-07-13 16:59:15.559 [info] [Info  - 16:59:15] (46715) Auto-excluding **/.*
2024-07-13 16:59:15.574 [info] [Info  - 16:59:15] (46715) Assuming Python version 3.12.3.final.0
2024-07-13 16:59:15.575 [info] (46715) Assuming Python platform Linux
2024-07-13 16:59:15.774 [info] [Info  - 16:59:15] (46715) Search paths for file:///%3Cdefault%20workspace%20root%3E
2024-07-13 16:59:15.774 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib
2024-07-13 16:59:15.774 [info] [Info  - 16:59:15] (46715)   /<default workspace root>
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /<default workspace root>/typings
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stubs/...
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/bundled/stubs
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3.12
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3.12/lib-dynload
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /usr/local/lib/python3.12/dist-packages
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3/dist-packages
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715) Adding fs watcher for library directories:
 file:///usr/lib/python3.12
file:///usr/lib/python3.12/lib-dynload
file:///usr/local/lib/python3.12/dist-packages
file:///usr/lib/python3/dist-packages
2024-07-13 16:59:15.775 [info] [Info  - 16:59:15] (46715) Adding fs watcher for directories:
 file:///%3Cdefault%20workspace%20root%3E
2024-07-13 16:59:15.775 [info] (46715) Searching for source files
2024-07-13 16:59:15.775 [info] [Error - 16:59:15] (46715) File or directory "/<default workspace root>" does not exist.
2024-07-13 16:59:15.776 [info] [Info  - 16:59:15] (46715) No source files found.
2024-07-13 16:59:15.784 [info] (46715) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:15.785 [info] (46715) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:15.796 [info] (46715) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) ...
2024-07-13 16:59:15.796 [info] (46715) [IDX(FG)]   read stdlib indices (10ms)
2024-07-13 16:59:15.797 [info] (46715) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) [succeed] (11ms)
2024-07-13 16:59:15.801 [info] (46715) Server settings returned for workspace: undefined: {
  "autoSearchPaths": true,
  "disableLanguageServices": false,
  "openFilesOnly": true,
  "useLibraryCodeForTypes": true,
  "watchForSourceChanges": true,
  "watchForLibraryChanges": true,
  "watchForConfigChanges": true,
  "typeCheckingMode": "off",
  "diagnosticSeverityOverrides": {
    "reportShadowedImports": "warning"
  },
  "logLevel": "log",
  "autoImportCompletions": false,
  "indexing": false,
  "completeFunctionParens": false,
  "enableExtractCodeAction": true,
  "indexOptions": {
    "packageDepths": [
      [
        "sklearn",
        2,
        false
      ],
      [
        "matplotlib",
        2,
        false
      ],
      [
        "scipy",
        2,
        false
      ],
      [
        "django",
        2,
        false
      ],
      [
        "flask",
        2,
        false
      ],
      [
        "fastapi",
        2,
        false
      ]
    ],
    "userFileIndexingLimit": 2000
  },
  "variableInlayTypeHints": false,
  "callArgumentNameInlayHints": "off",
  "functionReturnInlayTypeHints": false,
  "pytestParametersInlayTypeHints": false,
  "importFormat": "absolute",
  "includeFileSpecs": [],
  "excludeFileSpecs": [],
  "ignoreFileSpecs": [],
  "formatOnType": true,
  "taskListTokens": [],
  "enablePytestSupport": true,
  "gotoDefinitionInStringLiteral": true,
  "remapDiagnostics": false,
  "intelliCodeEnabled": true,
  "pythonPath": {
    "_key": "/bin/python3",
    "_filePath": "/bin/python3",
    "_query": "",
    "_fragment": "",
    "_originalString": "file:///bin/python3",
    "_isCaseSensitive": true
  },
  "pythonEnvironmentName": "3.12.3 (global)",
  "fixAll": [],
  "extraCommitChars": false,
  "autoFormatStrings": false,
  "autoIndent": true,
  "supportRestructuredText": true,
  "collectModuleInfo": false,
  "nodeExecutable": "",
  "editorIndentConfig": {
    "defaultTabSequence": "    ",
    "tabSize": 4
  }
}
2024-07-13 16:59:15.807 [info] (46715) No pyproject.toml file found.
2024-07-13 16:59:15.807 [info] [Info  - 16:59:15] (46715) Setting pythonPath for service "<default>": "/bin/python3"
2024-07-13 16:59:15.807 [info] [Info  - 16:59:15] (46715) Setting environmentName for service "<default>": "3.12.3 (global)"
2024-07-13 16:59:15.808 [info] [Info  - 16:59:15] (46715) No include entries specified; assuming /<default workspace root>
2024-07-13 16:59:15.808 [info] [Info  - 16:59:15] (46715) Auto-excluding **/node_modules
2024-07-13 16:59:15.808 [info] [Info  - 16:59:15] (46715) Auto-excluding **/__pycache__
2024-07-13 16:59:15.808 [info] [Info  - 16:59:15] (46715) Auto-excluding **/.*
2024-07-13 16:59:15.830 [info] [Info  - 16:59:15] (46715) Assuming Python version 3.12.3.final.0
2024-07-13 16:59:15.830 [info] (46715) Assuming Python platform Linux
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715) Search paths for file:///%3Cdefault%20workspace%20root%3E
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /<default workspace root>
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /<default workspace root>/typings
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stubs/...
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/bundled/stubs
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3.12
2024-07-13 16:59:15.955 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3.12/lib-dynload
2024-07-13 16:59:15.956 [info] [Info  - 16:59:15] (46715)   /usr/local/lib/python3.12/dist-packages
2024-07-13 16:59:15.956 [info] [Info  - 16:59:15] (46715)   /usr/lib/python3/dist-packages
2024-07-13 16:59:15.956 [info] [Info  - 16:59:15] (46715) Adding fs watcher for library directories:
 file:///usr/lib/python3.12
file:///usr/lib/python3.12/lib-dynload
file:///usr/local/lib/python3.12/dist-packages
file:///usr/lib/python3/dist-packages
2024-07-13 16:59:15.956 [info] [Info  - 16:59:15] (46715) Adding fs watcher for directories:
 file:///%3Cdefault%20workspace%20root%3E
2024-07-13 16:59:15.956 [info] (46715) Searching for source files
2024-07-13 16:59:15.956 [info] [Error - 16:59:15] (46715) File or directory "/<default workspace root>" does not exist.
2024-07-13 16:59:15.956 [info] [Info  - 16:59:15] (46715) No source files found.
2024-07-13 16:59:15.956 [info] (46715) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) ...
2024-07-13 16:59:15.956 [info] (46715) [IDX(FG)]   read stdlib indices (0ms)
2024-07-13 16:59:15.957 [info] (46715) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) [succeed] (1ms)
2024-07-13 16:59:16.062 [info] (46715) Attempting to resolve using local imports: __builtins__
2024-07-13 16:59:16.062 [info] (46715) Attempting to resolve using root path 'file:///home/lmoreno/Proyectos/Retos_Programacion/2022'
2024-07-13 16:59:16.063 [info] (46715) [FG] parsing: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (104ms)
2024-07-13 16:59:16.134 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (70ms)
2024-07-13 16:59:16.163 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/builtins.pyi (26ms)
2024-07-13 16:59:16.168 [info] (46715) [FG] binding: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (5ms)
2024-07-13 16:59:16.170 [info] (46715) pytest configurations: {"message":"spawn /bin/python3 ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:16.175 [info] [Info  - 16:59:16] (46715) Background analysis(1) root directory: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist
2024-07-13 16:59:16.176 [info] [Info  - 16:59:16] (46715) Background analysis(1) started
2024-07-13 16:59:16.177 [info] (46715) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:16.177 [info] (46715) pytest configurations: {"message":"spawn /bin/python3 ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:16.247 [info] (46715) pytest configurations: {"message":"spawn /bin/python3 ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-07-13 16:59:16.350 [info] (46715) Attempting to resolve using local imports: __builtins__
2024-07-13 16:59:16.384 [info] (46715) Attempting to resolve using root path 'file:///home/lmoreno/Proyectos/Retos_Programacion/2022'
2024-07-13 16:59:16.384 [info] (46715) [BG(1)] analyzing: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py ...
2024-07-13 16:59:16.384 [info] (46715) [BG(1)]   parsing: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (102ms)
2024-07-13 16:59:16.402 [info] (46715) [BG(1)]   parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (51ms)
2024-07-13 16:59:16.430 [info] (46715) [BG(1)]   binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/builtins.pyi (26ms)
2024-07-13 16:59:16.431 [info] (46715) [BG(1)]   binding: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (1ms)
2024-07-13 16:59:16.456 [info] (46715) [BG(1)]   checking: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py ...
2024-07-13 16:59:16.456 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 0ms] (15ms)
2024-07-13 16:59:16.462 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing.pyi (6ms)
2024-07-13 16:59:16.476 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (4ms)
2024-07-13 16:59:16.478 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/types.pyi (3ms)
2024-07-13 16:59:16.485 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (2ms)
2024-07-13 16:59:16.486 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2024-07-13 16:59:16.490 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (0ms)
2024-07-13 16:59:16.491 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
2024-07-13 16:59:16.503 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (7ms)
2024-07-13 16:59:16.504 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (2ms)
2024-07-13 16:59:16.519 [info] (46715) [BG(1)]     parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi [fs read 0ms] (0ms)
2024-07-13 16:59:16.519 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi ...
2024-07-13 16:59:16.520 [info] (46715) [BG(1)]       parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi [fs read 0ms] (0ms)
2024-07-13 16:59:16.520 [info] (46715) [BG(1)]       binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi (1ms)
2024-07-13 16:59:16.520 [info] (46715) [BG(1)]     binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi (2ms)
2024-07-13 16:59:16.555 [info] (46715) [BG(1)]   checking: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (124ms)
2024-07-13 16:59:16.555 [info] (46715) [BG(1)] analyzing: file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (307ms)
2024-07-13 16:59:16.558 [info] (46715) [BG(1)] SemanticTokens full at file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (2ms)
2024-07-13 16:59:16.561 [info] (46715) [BG(1)] SemanticTokens range 0:0 - 55:0 at file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (1ms)
2024-07-13 16:59:17.322 [info] (46715) [BG(1)] SemanticTokens delta previousResultId:1720882756556 at file:///home/lmoreno/Proyectos/Retos_Programacion/2022/reto_028.py (1ms)
2024-07-13 16:59:44.980 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (20ms)
2024-07-13 16:59:45.004 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing.pyi (23ms)
2024-07-13 16:59:45.025 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (12ms)
2024-07-13 16:59:45.030 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/types.pyi (5ms)
2024-07-13 16:59:45.041 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (6ms)
2024-07-13 16:59:45.042 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2024-07-13 16:59:45.048 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (0ms)
2024-07-13 16:59:45.048 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
2024-07-13 16:59:45.265 [info] (46715) Attempting to resolve using local imports: __builtins__
2024-07-13 16:59:45.265 [info] (46715) Attempting to resolve using root path 'file:///tmp/pyright-46715-1Qq4Pmp6wOeV'
2024-07-13 16:59:45.266 [info] (46715) [FG] parsing: file:///tmp/pyright-46715-1Qq4Pmp6wOeV/builtins-46715-lgcS6VV0ZCPf-.py [fs read 2ms] (45ms)
2024-07-13 16:59:45.288 [info] (46715) [FG] binding: file:///tmp/pyright-46715-1Qq4Pmp6wOeV/builtins-46715-lgcS6VV0ZCPf-.py (23ms)
2024-07-13 16:59:45.289 [info] (46715) Restructured text parsing enabled
2024-07-13 16:59:45.289 [info] (46715) Converting docstring to markdown
2024-07-13 16:59:45.289 [info] (46715) Common base class for all exceptions
2024-07-13 16:59:45.295 [info] (46715) Fixed docstring:
2024-07-13 16:59:45.295 [info] (46715) Common base class for all exceptions
2024-07-13 16:59:45.296 [info] (46715) Conversion complete in 7ms
2024-07-13 16:59:45.296 [info] (46715) Common base class for all exceptions
2024-07-13 17:02:35.773 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi [fs read 1ms] (1ms)
2024-07-13 17:02:35.777 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi ...
2024-07-13 17:02:35.777 [info] (46715) [FG]   parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi [fs read 0ms] (4ms)
2024-07-13 17:02:35.778 [info] (46715) [FG]   binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/_collections_abc.pyi (1ms)
2024-07-13 17:02:35.779 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/collections/abc.pyi (7ms)
2024-07-13 17:02:35.799 [info] (46715) [FG] parsing: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (17ms)
2024-07-13 17:02:35.803 [info] (46715) [FG] binding: file:///home/lmoreno/.vscode/extensions/ms-python.vscode-pylance-2024.7.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (4ms)
2024-07-13 17:04:30.491 [info] (46715) Restructured text parsing enabled
2024-07-13 17:04:30.491 [info] (46715) Converting docstring to markdown
2024-07-13 17:04:30.491 [info] (46715) Common base class for all exceptions
2024-07-13 17:04:30.492 [info] (46715) Conversion complete in 0ms
2024-07-13 17:04:30.492 [info] (46715) Common base class for all exceptions
```

**Comment by erictraut** [comment] 2024-07-13 15:23
This is a duplicate of https://github.com/microsoft/pylance-release/issues/6106.

**Closed** 2024-07-13 15:26 UTC
Labels: duplicate
