### ISSUE TITLE
Add a "copy as 

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#1456] opened 2021-06-16 21:32 UTC
PyCharm has something like this, and it's incredibly useful when you want to import a function from your codebase e.g. in a Python REPL.

Let's say you have a file `mypackage/foo/bar.py` containing a `test` function. Then this action would copy `from mypackage.foo.bar import test`.

PyCharm copies `mypackage.foo.bar.test` but I think an actual import statement is more useful.

_Originally posted by @ThiefMaster in https://github.com/microsoft/vscode-python/discussions/16412_

**Comment by jakebailey** [comment] 2021-06-16 21:34
Dupe of #1457.

**Closed by jakebailey** 2021-06-16 21:34 UTC
Labels: triage
