### ISSUE TITLE
Pylance can't recognize available parameters for a decorator 

### ISSUE THREAD

**Issue by defracted** [microsoft/pylance-release#324] opened 2020-09-04 17:50 UTC
## Environment data 

-   Language Server version: Pylance language server 2020.9.0
-   OS and version: Windows 10 2004 (Build 19041.450)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 and Pipenv 2020.8.13

## Expected behaviour

Pylance should recognize decorator's parameters 

## Actual behaviour

Pylance sees decorator parameter as a variable and says it's not defined

## Logs

Output was really long, so I created a secret [gist](https://gist.github.com/defracted/b1b925535946722f2f8483f11f5e9a5a).

## Code Snippet / Additional information

```python
import time


def benchmark(foo):
    def actual_decorator(func):
        def wrapper(*args, **kwargs):
            bar = None if not foo else 1
            del bar

            start = time.time()
            return_value = func(*args, **kwargs)
            end = time.time()
            print("[*] Executed in: {} seconds.".format(end - start))
            return return_value

        return wrapper
    return actual_decorator


@benchmark(foo="test")
def big_iteration():
    c = 0
    for x in range(5000000):  # be careful here, you might need to change it!
        c += 1
    print("`c` value is {}".format(c))


big_iteration()

```

![Code_gePddELoyb](https://user-images.githubusercontent.com/51153795/92271042-2c415280-eef8-11ea-9a41-62fa51685e89.png)

#### Note

I am actually using aiogram to build a Telegram bot and I noticed that issue. I tried to make a decorator that measures execution time of a function and the issue was still there.

**Comment by judej** [comment] 2020-09-04 17:56
Duplicate of #322

**Closed by judej** 2020-09-04 17:56 UTC
Labels: duplicate, triage
