### ISSUE TITLE
Confusing behavior of docstring vs type hints when pyi files are present

### ISSUE THREAD

**Issue by gonzalocasas** [microsoft/pylance-release#1040] opened 2021-03-12 21:23 UTC
I am developing a small library and I noticed a weird/confusing behavior on Pylance depending on whether I generate stub files (`*.pyi`) for it or not.

In summary, my library is heavily documented with docstrings, which work like a charm with Pylance ONLY IF I don't generate stub files with `mypy`. As soon as I generate `pyi` files (using the super standard `stubgen -p compas_rrc -o src` to place stubfiles next to source files), the **apparent behavior** is that docstrings are gone and only type hints remain. I highlight "apparent" because I noticed that if I hover over the keyword I'm typing, then the docstrings show up, but that's not useful at all, I don't want to use my mouse to get docstrings popping up.

I realize there have been [multiple similar issues reported](https://github.com/microsoft/pylance-release/issues?q=is%3Aissue+is%3Aopen+stub+docstring), but I did not find this exact one, at least not narrowed down to this scenario, so hope it's worth reporting.

## Behavior without pyi files

Here Pylance shows the full docstring information as soon as I open the parentheses (in this case, of the constructor of my class):

![image](https://user-images.githubusercontent.com/933277/110997831-3f891b00-837e-11eb-82ce-5f649ac124dd.png)

## Behavior with pyi files

After running `stubgen` (and without any manual changes to anything else), Pylance stops showing docstrings and decides to only show type hint info:
![image](https://user-images.githubusercontent.com/933277/110998072-8f67e200-837e-11eb-912a-f2832b2d33e4.png)

However, if I hover over the word with the mouse, I see the docstrings are still there:
![image](https://user-images.githubusercontent.com/933277/110998093-9858b380-837e-11eb-9ab4-99dc91fdd433.png)

## Environment data

-   Language Server version: 2021.3.1 (pyright 5d6db8d1)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): `Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:20:24) [MSC v.1916 64 bit (AMD64)] on win32`
-   Conda environment: can be recreated with `conda create -n test-env-pylance compas_fab python=3.8`

## Expected behaviour

The expected behavior is that the typing info hints and the docstrings are shown together, just like they seem to be if there are no `pyi` files present.

## Actual behaviour

Currently the docstring is only shown on hover if `pyi` files are present.

**Comment by jakebailey** [comment] 2021-03-12 21:27
Thanks for the report; this is actually a dupe of #784. The source mapper isn't piped through the signature help call (but is for hover and completion, as you're seeing).

**Closed by jakebailey** 2021-03-12 21:27 UTC
Labels: triage
