### ISSUE TITLE
Ability to force pylance to treat wrapped functions as functions as opposed to variables

### ISSUE THREAD

**Issue by jabbera** [microsoft/pylance-release#5856] opened 2024-05-07 14:14 UTC
With the following code pylance recognizes wrapped_function_definition as a variable/constant. I'd love a way to force pylance to treat this as a function. (Unless there is another way I should be using to provide both a wrapped and unwrapped implementation of the same function without having to keep the parameter list/typehints up to date?) See the screenshot, wrapped_function_definition is blue and listed as a constant as opposed to yellow and listed as a function.

<img width="320" alt="image" src="https://github.com/microsoft/pylance-release/assets/301208/792f4f72-ce8d-4ec4-91f2-c0278fc03335">

```
from collections.abc import Callable
from typing import Final, ParamSpec, TypeVar

T = TypeVar("T")
P = ParamSpec("P")


def wrap_function(func: Callable[P, T]) -> Callable[P, T]:
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
        return func(*args, **kwargs)

    return wrapper


def function_to_wrap(i: int) -> int:
    return i


wrapped_function_definition: Final = wrap_function(function_to_wrap)
```

**Comment by debonte** [comment] 2024-05-07 16:33
This is a duplicate of https://github.com/microsoft/pylance-release/issues/5785. You may want to up-vote the issue that spun out of that one -- https://github.com/microsoft/pylance-release/issues/5841.

**Closed by debonte** 2024-05-07 16:33 UTC
Labels: needs repro

**Comment by jabbera** [comment] 2024-05-07 17:00
Thanks! I tried to search it before but was unable to locate those issues.
