### ISSUE TITLE
Feature: jump to type definition

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#2360] opened 2022-02-09 05:56 UTC
In python, when I hover over the `i` variable the type (eg: `InstanceTypeDef`) is displayed.

I'd like to be able to jump to the type definition, eg: via a keyboard shortcut or Ctrl+click on `InstanceTypeDef`
 
<img width="758" alt="Screen Shot 2022-02-09 at 4 54 22 pm" src="https://user-images.githubusercontent.com/125105/153130429-65f094f9-dc67-422f-ae80-8ded797f41e3.png">

**Comment by debonte** [comment] 2022-02-10 01:12
Dupe of https://github.com/microsoft/pylance-release/issues/2309?

**Closed** 2022-02-10 18:47 UTC
Labels: duplicate, classify, feature-request
