### ISSUE TITLE
When would I include a module in __all__?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#2574] opened 2022-04-17 05:09 UTC
I'm trying to improve the intellisense experience of using the Panel package by adding `__all__`.

I'm in doubt whether `modules` should be included in `__all__` and why? I've tried to google an answer without luck.

## Example Pydantic

Pydantic does it :-) 

![image](https://user-images.githubusercontent.com/42288570/163701286-eca078e7-6eb4-4911-a1c0-6018a70ad58e.png)

https://github.com/samuelcolvin/pydantic/blob/master/pydantic/__init__.py

## Should Panel do it?

![image](https://user-images.githubusercontent.com/42288570/163701311-fc71435a-890e-42b2-938e-66e87c170749.png)

## Bonus question

Is there a "best practice" package that I could look at if I am not able to understand or find what I need in the documentation?

**Comment by erictraut** [comment] 2022-04-17 05:14
The purpose of `__all__` is simply to define which symbols should be imported as part of a wildcard import that targets that module. If a symbol is importable through a wildcard import, it makes sense that it should be considered public.

As I mentioned in [this response](https://github.com/microsoft/pylance-release/issues/2572#issuecomment-1100723655), I wouldn't recommend adding `__all__` to your library if it doesn't already support it because wildcard imports should really never be used to import from a library. I would recommend instead that you use redundant import forms if the intent is to re-export an imported symbol from the module.

```python
from . import label as label
from . import links as links
...
```

**Comment by erictraut** [comment] 2022-04-17 05:20
I realize this probably seems convoluted and overly complicated. The problem is that Python, unlike most modern languages, doesn't have keywords to designate access control. Most languages have keywords like `public`, `private` and `export` so you can be explicit about access control. Python started as a scripting language, and access control is less important in that context. So now we're stuck with these convoluted conventions so library authors can specify which symbols are intended to be public versus private. :(

**Comment by MarcSkovMadsen** [comment] 2022-04-17 05:22
Using *redundant form* is a hard sell :-)

![image](https://user-images.githubusercontent.com/42288570/163701620-067526b5-0d8d-4b60-95b2-927b8eb1e4f9.png)

**Comment by MarcSkovMadsen** [comment] 2022-04-17 05:23
Isn't `public`, `private` and `export` a PEP away? :-)

**Comment by MarcSkovMadsen** [comment] 2022-04-17 05:30
To add a little bit more context. A part of the value proposition of Panel is that it should work

- for beginning pythonistas and data exploration people in Jupyter Notebooks - They might be using `from panel.widgets import *`. For data exploration or an analysis situation on a trading floor this provides a short time to market.
- for experienced software developers working in VS Code and using all kinds of tools and best practices to provide solid code.

Personally I'm trying my best to be the second persona. But my job is to support the first type of persona.

We are at version `0.13.0` :-). So early stage. But have +500.000 downloads per month.

**Comment by MarcSkovMadsen** [comment] 2022-04-17 05:40
Ahh. *redundant form* and `__all__` are not just two ways of achieving the same thing. They have two different intents. The intent of `__all__` is to enable using `from XYZ import *`. But pyright, pylance etc also uses them to determine which symbols should be considered public.

The intent of the redundant form is to help pyright, pylance etc to determine which symbols should be considered public.

??

**Comment by erictraut** [comment] 2022-04-17 05:44
Yes, that's correct. And to be clear, the "redundant form of import" wasn't our idea. It comes from [PEP 484](https://peps.python.org/pep-0484/#stub-files) and is the standard way to indicate in type stubs that an imported symbol should be re-exported. We're just reusing a convention that already exists rather than inventing a new one.

**Comment by erictraut** [comment] 2022-04-17 05:50
> my job is to support the first type of persona.

To be clear, we're interested in both personas too! Pylance powers the programming experience in VS Code for both Python source (".py") files and Jupyter notebooks, and it caters to beginners who simply want completion suggestions all the way to power users who want refactoring tools and static type checking. So we understand where you're coming from!

**Comment by erictraut** [comment] 2022-04-17 05:54
> Isn't `public`, `private` and `export` "just" a PEP away? :-)

This is highly unlikely. The Python steering council has not been receptive to adding features like this to the language.

**Comment by debonte** [comment] 2022-05-21 00:22
@MarcSkovMadsen, I'm closing this issue as it seems that your questions have been answered. If you disagree, please let us know.

**Closed by debonte** 2022-05-21 00:22 UTC
Labels: waiting for user response, reference
