### ISSUE TITLE
High reindexing CPU cost while editing `-e` installed libraries in multi-root workspace 

### ISSUE THREAD

**Issue by justinttl** [microsoft/pylance-release#2318] opened 2022-02-01 15:30 UTC
I am working in a multi-root workspace project with 10+ workspaces, each with its own venv and instance of pylance. Most workspaces are web applications, and consumes a common library via `-e` install (a poetry [dependency](https://python-poetry.org/docs/dependency-specification/#path-dependencies) with `develop = true`),  which itself is a workspace. 

When editing and saving files within the common library, I have noticed that it causes all the consuming application's workspace pylance to `invalidateAndForceReanalysis`, even if I have none of the application's source files open. The subsequent reindexing of all the workspaces spikes CPU and freezes up my computer for up to a minute or two. 

## Environment data

-   Language Server version: 2022.1.5
-   OS and version: MacOS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9, using poetry

## Expected behaviour

Ideally, the indexer wouldn't run for applications where I haven't open the files for. A simple change save causing a full reindexing also seems unnecessary. 

## Actual behaviour

Full re-indexing from every workspace's instance of pyright (10+).

## Logs

```
[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'add' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'add' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'add' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'add' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
# .... one for each consuming app, tmp files created when saving within vscode.

[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'change' for path '<...>.py'}'
# .... one for each consuming app, probably from the actual change of the library file

[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'change' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
# ... one for each consuming app, probably from the deletion of the .tmp files

(35572) Background analysis message: markFilesDirty
(35572) Background analysis message: analyze
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: analyze
(35572) Background analysis message: analyze
(35572) Background analysis message: analyze
(35572) Background analysis message: analyze
(35572) Background analysis message: analyze
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: analyze
(35572) Background analysis message: invalidateAndForceReanalysis
(35572) Background analysis message: analyze
(35572) Background analysis message: invalidateAndForceReanalysis
... long indexing trace logs
```

## Code Snippet / Additional information
I have tried adding `**/*.tmp` to `files.watcherExclude` but that doesn't seem to help. The created `.tmp` file still triggers the `fs event`

**Comment by heejaechang** [comment] 2022-02-02 01:29
@justinttl unfortunately, currently there is no easy way to support this since each pylance servers are independent each other (one per root) and can't share indices for the changed libraries.

for now, only option you have is turning off indexing. "python.analysis.indexing": false in your setting.json file (or workspace setting file)

**Comment by justinttl** [comment] 2022-02-02 15:13
Hey @heejaechang, thanks for the quick response! I have taken a look at #2270 and will experiment with removing the root workspace. (for context, it was useful to have that around since we run a monorepo and a lot of the configuration and monorepo tooling is on the root workspace) 

I have a question though: 
Is it expected behavior that file change in a library will cause a full reindex? I have known that new file tends to cause pylance to reindex, but I am surprised to see that a save causes the same reindexing behavior. 

Perhaps it is from the `.tmp` or `.swp` files created when an editor (vscode, vim) saves?

**Comment by justinttl** [comment] 2022-02-02 15:23
INFO level language server logs when I save a change in a common library workspace 

```
[Info  - 10:18:42 AM] (68738) Indexer background runner(88) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(88) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(81) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(81) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(82) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(82) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(85) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(85) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(83) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(83) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(84) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(84) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(89) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(89) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(90) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(90) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(86) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(86) started
[Info  - 10:18:42 AM] (68738) Indexer background runner(87) root directory: /Users/justinlee/.vscode/extensions/ms-python.vscode-pylance-2022.1.5/dist (refresh)
[Info  - 10:18:42 AM] (68738) Indexing(87) started
[Info  - 10:18:45 AM] (68738) [IDX(90)] Long operation: scan packages (2231ms)
[Info  - 10:18:45 AM] (68738) [IDX(81)] Long operation: scan packages (2816ms)
[Info  - 10:18:45 AM] (68738) [IDX(88)] Long operation: scan packages (2424ms)
[Info  - 10:18:45 AM] (68738) [IDX(85)] Long operation: scan packages (2327ms)
[Info  - 10:18:46 AM] (68738) [IDX(87)] Long operation: scan packages (2596ms)
[Info  - 10:18:46 AM] (68738) [IDX(84)] Long operation: scan packages (2633ms)
[Info  - 10:18:46 AM] (68738) [IDX(89)] Long operation: scan packages (2853ms)
[Info  - 10:18:46 AM] (68738) [IDX(83)] Long operation: scan packages (2825ms)
[Info  - 10:18:46 AM] (68738) [IDX(86)] Long operation: scan packages (3070ms)
[Info  - 10:18:46 AM] (68738) [IDX(82)] Long operation: scan packages (3122ms)
[Info  - 10:18:55 AM] (68738) [IDX(85)] Long operation: index execution environment /Users/justinlee/Development/<...> (10158ms)
[Info  - 10:18:55 AM] (68738) [IDX(85)] Long operation: index libraries /Users/justinlee/Development/<....> (13271ms)
[Info  - 10:18:55 AM] (68738) Indexer done(85). indexed 473 files
[Info  - 10:18:56 AM] (68738) [IDX(90)] Long operation: index execution environment /Users/justinlee/Development/<.....> (10453ms)
[Info  - 10:18:56 AM] (68738) [IDX(90)] Long operation: index libraries /Users/justinlee/Development/<.....> (13402ms)
[Info  - 10:18:56 AM] (68738) Indexer done(90). indexed 473 files
[Info  - 10:18:58 AM] (68738) [IDX(88)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (12319ms)
[Info  - 10:18:58 AM] (68738) [IDX(88)] Long operation: index libraries /Users/justinlee/Development/<.....> (15499ms)
[Info  - 10:18:58 AM] (68738) Indexer done(88). indexed 503 files
[Info  - 10:18:59 AM] (68738) [IDX(81)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (13333ms)
[Info  - 10:18:59 AM] (68738) [IDX(81)] Long operation: index libraries /Users/justinlee/Development/<.....> (16428ms)
[Info  - 10:18:59 AM] (68738) Indexer done(81). indexed 506 files
[Info  - 10:18:59 AM] (68738) [IDX(83)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (13342ms)
[Info  - 10:18:59 AM] (68738) [IDX(83)] Long operation: index libraries /Users/justinlee/Development/<.....> (16992ms)
[Info  - 10:18:59 AM] (68738) Indexer done(83). indexed 516 files
[Info  - 10:18:59 AM] (68738) [IDX(82)] Long operation: index execution environment /Users/justinlee/Development/<.....> 
 (13192ms)
[Info  - 10:18:59 AM] (68738) [IDX(82)] Long operation: index libraries /Users/justinlee/Development/<.....> (17080ms)
[Info  - 10:18:59 AM] (68738) Indexer done(82). indexed 517 files
[Info  - 10:18:59 AM] (68738) [IDX(84)] Long operation: index execution environment /Users/justinlee/Development/<.....> (13579ms)
[Info  - 10:18:59 AM] (68738) [IDX(84)] Long operation: index libraries /Users/justinlee/Development/<.....>  (16988ms)
[Info  - 10:18:59 AM] (68738) Indexer done(84). indexed 516 files
[Info  - 10:18:59 AM] (68738) [IDX(87)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (13906ms)
[Info  - 10:18:59 AM] (68738) [IDX(87)] Long operation: index libraries /Users/justinlee/Development/<.....> (16998ms)
[Info  - 10:18:59 AM] (68738) Indexer done(87). indexed 512 files
[Info  - 10:19:00 AM] (68738) [IDX(86)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (13675ms)
[Info  - 10:19:00 AM] (68738) [IDX(86)] Long operation: index libraries /Users/justinlee/Development/<.....> (17347ms)
[Info  - 10:19:00 AM] (68738) Indexer done(86). indexed 516 files
[Info  - 10:19:00 AM] (68738) [IDX(89)] Long operation: index execution environment /Users/justinlee/Development/<.....>  (13865ms)
[Info  - 10:19:00 AM] (68738) [IDX(89)] Long operation: index libraries /Users/justinlee/Development/<.....>  (17244ms)
[Info  - 10:19:00 AM] (68738) Indexer done(89). indexed 518 files
```

**Comment by heejaechang** [comment] 2022-02-03 20:59
@justinttl problem is you have multiple roots (multiple pylance servers) and each root is editable install to other roots, in other word, a library to other roots. so, when you change a file (save) in other root, other roots think there is a change in library installed, and each roots re-index libraries.

right now, we assume library changes rarely, so when a library change, each root re-index all libraries. and I believe that is what is happening here.

this won't happen if there is only 1 root (one workspace) since all packages (install -e packages) are under 1 server. but in multi root workspace case, each root has its own isolated pylance server. so it has no idea on other roots (basically other pylance servers). so when file is changed on one of root, other roots (server) will wake up and say "library change detected!" and re-index their libraries.

..

and yes, fs event below probably is the cause of making us to re-index.

```
[Info  - 10:09:43 AM] (35572) LibraryFile: Received fs event 'add' for path '<....>.py.5577df4034c34679659b7356775fc122.tmp'}'
```

..

if you change your multiroot workpace to single root workspace, these issue will probably go away.

**Comment by justinttl** [comment] 2022-02-03 23:05
> right now, we assume library changes rarely, so when a library change, each root re-index all libraries. and I believe that is what is happening here. 

I was afraid that is the case... **Is there room for optimization there?** Multi-root workspace lends very nicely to working on application and libraries concurrently...

> if you change your multiroot workpace to single root workspace, these issue will probably go away.
We lose out a lot by not being in a multi-root workspace. The monorepo we have defines 10 microservices and shared libraries. The multi-root setup have been amazing for us in getting 100% intellisense coverage across all app's diverging dependencies in separate virtualenvs. It also makes tools like isort and pylint work well in the IDE since they are dependent on being within the venv the code is running on. 

Anyhow, thank you for clarifying the behavior. 

Few more question: 
- If I turn off indexing, do I loose intenseness and type hints? 
- Is there a way to configure not running pylance on certain workspaces while under a multi-root setup? (like adding `.vscode/settings` under a particular workspace and setting the language server to `None`?)

**Comment by heejaechang** [comment] 2022-02-04 03:28
@justinttl 

> If I turn off indexing, do I loose intenseness and type hints?
turning off indexing won't affect intelliSense and type hints. they will still work. main thing you will lose is auto-import for third party libraries (ones you never used before) but you will still get auto-import for stdlib.

> Is there a way to configure not running pylance on certain workspaces while under a multi-root setup? (like adding .vscode/settings under a particular workspace and setting the language server to None?)
you can, but turning off indexing should be sufficient for your issue.

that being said, I think we have some idea on improving this case. I will let you know once we have something working.

**Comment by justinttl** [comment] 2022-02-09 16:16
@heejaechang

Turning off indexing worked wonders! Thank you for the suggestion.
Feel free to close the issue, I will keep any eye out for any updates on the improvements you mentioned.

**Comment by heejaechang** [comment] 2022-02-09 19:30
closing it as dup of https://github.com/microsoft/pylance-release/issues/2270 since new change addresses both issue.

**Closed by heejaechang** 2022-02-09 19:30 UTC
Labels: enhancement, fixed in next version
