### ISSUE TITLE
VSCode crash on Ubuntu 22.04 caused by Pylance set to use a non-existing venv

### ISSUE THREAD

**Issue by m-tartari** [microsoft/pylance-release#4989] opened 2023-10-20 07:10 UTC
Type: <b>Bug</b>

When VSCode starts it crashes. below you can see a screenshot:
![image](https://github.com/microsoft/pylance-release/assets/37861893/6bd3e696-aca8-4952-bf1a-ab68e8313736)

I've identified this extension to be the issue using the [extension bisect utility](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect).

Extension version: 2023.10.30
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 6.2.0-34-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 3114)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|13.52GB (6.84GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b40c81a4-f1b4-4e12-b1f0-ea0880ccb63e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by m-tartari** [comment] 2023-10-20 08:37
Doing some more testing, it seems to be caused by using a venv that does not exist.

### How to reproduce:

file structure and content:
```bash
~/path_to/debug_pylance/
├── python_project
│   └── main.py
└── .vscode
    └── debug-pylance.code-workspace
```


`main.py` is empty.

`debug-pylance.code-workspace` contains the following:
```jsonc
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "../python_project"
    }
  ],
  "settings": {
    "editor.tabSize": 2,
    "python.envFile": "../foo/venv", // does not exist
    "python.defaultInterpreterPath": "../foo/venv/bin/python", // does not exist
    "python.linting.pylintArgs": [
      "--disable=C0103" // disable Pyling(invalid-name) message
    ],
  }
}
```

Only Python and Pylance extensions are enabled:
![image](https://github.com/microsoft/pylance-release/assets/37861893/451a47e5-cdd8-4fb1-b392-69bf6a127302)

Now open the workspace and open main.py and the editor will return the screenshot in the issue description.

**Comment by m-tartari** [comment] 2023-10-20 09:00
even removing the problematic venv from the workspace config does not fix the issue.

here are my global Python settings:
```jsonc
  // Python
  "python.showStartPage": false,
  "python.languageServer": "Pylance",
  "python.pythonPath": "/usr/bin/python3",
  "python.defaultInterpreterPath": "/usr/bin/python3",
  "python.formatting.provider": "yapf",
  "python.formatting.yapfArgs": [
    "--style={based_on_style: pep8, indent_width: 4,colum_limit: 999, dedent_closing_brackets: true}"
  ],
  "python.linting.pylintEnabled": true,
  "python.linting.pylintCategorySeverity.refactor": "Hint",
  "python.jediEnabled": false,
  "[python]": {
    "editor.defaultFormatter": "ms-python.python"
  },
  "[jupyter]": {
    "editor.defaultFormatter": "ms-python.python"
  },
  "jupyter.askForKernelRestart": false,
  "jupyter.widgetScriptSources": [
    "jsdelivr.com",
    "unpkg.com"
  ],
```

here the updated`debug-pylance.code-workspace`:
```jsonc
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "../python_project"
    }
  ],
  "settings": {
    "editor.tabSize": 2,
  }
}
```

I've noticed a warning for before the crash:
![image](https://github.com/microsoft/pylance-release/assets/37861893/e56a964f-f9bf-4f6c-9fa5-54d0ddaa35b8)
I managed to catch the output (it stays too little copy and paste it:
```log
  path: '/home/user/foo/venv/bin/python'
}
2023-10-20 10:56:28.179 [warning] Identifier for virt-virtualenv failed to identify /home/user/foo/venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/user/foo/venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/user/foo/venv/bin'
}
2023-10-20 10:56:28.179 [warning] Identifier for virt-virtualenv failed to identify /home/user/foo/venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/user/foo/venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/user/foo/venv/bin'
}
2023-10-20 10:56:28.180 [warning] Identifier for virt-virtualenv failed to identify /home/user/foo/venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/user/foo/venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/user/foo/venv/bin'
}
```

**Comment by m-tartari** [comment] 2023-10-20 09:17
Creating a new a new code-workspace with the same configs as the previous one (no venv) stops the crashes, but sill report errors:
```
2023-10-20 11:07:14.459 [info] Experiment 'pythonaacf' is active
2023-10-20 11:07:14.459 [info] Experiment 'pythonTensorboardExperiment' is active
2023-10-20 11:07:14.459 [info] Experiment 'PythonPyTorchProfiler' is active
2023-10-20 11:07:14.459 [info] Experiment 'pythonDeprecatePythonPath' is active
2023-10-20 11:07:14.459 [info] Experiment 'pythonInterpreterInfoPinned' is active
2023-10-20 11:07:14.459 [info] Test server listening.
2023-10-20 11:07:14.459 [info] Python interpreter path: /usr/bin/python3
2023-10-20 11:07:14.487 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-20 11:07:14.487 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-20 11:07:14.487 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-20 11:07:14.487 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-20 11:07:15.738 [info] Extension search path: /home/mtartari/.vscode/extensions
2023-10-20 11:07:15.772 [info] > /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/linter.py -m pylint ~/Downloads/debug_pylance/python_project/main.py
2023-10-20 11:07:15.772 [info] cwd: ~/Downloads/debug_pylance/python_project
2023-10-20 11:07:15.901 [info] > /usr/bin/python3 -c "import pylint"
2023-10-20 11:07:16.026 [error] There was an error in running the linter pylint [n [Error]: Module 'pylint' not installed.
	at s.execForLinter (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:234513)
	at async c.run (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:541293)
	at async c.runLinter (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:562501)]
2023-10-20 11:07:16.026 [error] Support for "pylint" is moved to ms-python.pylint extension.
2023-10-20 11:07:16.026 [error] Please install the extension from: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint
2023-10-20 11:07:16.026 [error] If the error is due to missing pylint, please install pylint using pip manually.
2023-10-20 11:07:16.026 [error] Learn more here: https://aka.ms/AAlgvkb
2023-10-20 11:07:16.026 [info] Linting with pylint failed.
2023-10-20 11:07:16.026 [info] Error: Module 'pylint' not installed.
2023-10-20 11:07:16.445 [info] Starting Pylance language server.
```

enabling the `Pylint` extension further removes errors:
```
2023-10-20 11:12:24.510 [info] Experiment 'pythonaacf' is active
2023-10-20 11:12:24.510 [info] Experiment 'pythonTensorboardExperiment' is active
2023-10-20 11:12:24.510 [info] Experiment 'PythonPyTorchProfiler' is active
2023-10-20 11:12:24.510 [info] Experiment 'pythonDeprecatePythonPath' is active
2023-10-20 11:12:24.510 [info] Experiment 'pythonInterpreterInfoPinned' is active
2023-10-20 11:12:24.573 [info] Test server listening.
2023-10-20 11:12:24.580 [info] Python interpreter path: /usr/bin/python3
2023-10-20 11:12:26.165 [info] Extension search path: /home/mtartari/.vscode/extensions
2023-10-20 11:12:26.306 [info] > /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/linter.py -m pylint ~/Downloads/debug_pylance/python_project/main.py
2023-10-20 11:12:26.306 [info] cwd: ~/Downloads/debug_pylance/python_project
2023-10-20 11:12:26.395 [info] > /usr/bin/python3 -c "import pylint"
2023-10-20 11:12:26.542 [error] There was an error in running the linter pylint [n [Error]: Module 'pylint' not installed.
	at s.execForLinter (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:234513)
	at async c.run (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:541293)
	at async c.runLinter (/home/mtartari/.vscode/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:562501)]
2023-10-20 11:12:26.542 [error] Support for "pylint" is moved to ms-python.pylint extension.
2023-10-20 11:12:26.542 [error] Please install the extension from: https://marketplace.visualstudio.com/items?itemName=ms-python.pylint
2023-10-20 11:12:26.542 [error] If the error is due to missing pylint, please install pylint using pip manually.
2023-10-20 11:12:26.542 [error] Learn more here: https://aka.ms/AAlgvkb
2023-10-20 11:12:26.542 [info] Linting with pylint failed.
2023-10-20 11:12:26.542 [info] Error: Module 'pylint' not installed.
2023-10-20 11:12:27.356 [info] Starting Pylance language server.
```

**Comment by debonte** [comment] 2023-10-20 15:18
Closing for now under the assumption that this is a duplicate of #4983. Follow that issue for updates.

**Closed by debonte** 2023-10-20 15:18 UTC
Labels: needs repro
