### ISSUE TITLE
Pylance crashes when starting

### ISSUE THREAD

**Issue by mrichtarsky** [microsoft/pylance-release#5024] opened 2023-10-27 16:07 UTC
## Environment data

-   Language Server version: 2023.10.52 (pyright d7012d0d)
-   OS and version: Windows 10 22H2 19045.3570 (client), Ubuntu 22.04.3 LTS (remote machine, where the language server runs)
-   Python version (& distribution if applicable, e.g. Anaconda):  3.10.12 (remote machine)

## Code Snippet

- An empty python file suffices

## Repro Steps

- Navigate to python file

## Expected behavior

- Language server works

## Actual behavior

- Language server crashes

## Logs

```
2023-10-27 17:42:17.239 [info] [Info  - 5:42:17 PM] (3949915) Pylance language server 2023.10.52 (pyright d7012d0d) starting
2023-10-27 17:42:17.240 [info] [Info  - 5:42:17 PM] (3949915) Server root directory: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist
2023-10-27 17:42:17.257 [info] [Info  - 5:42:17 PM] (3949915) Starting service instance "tmp"
2023-10-27 17:42:17.268 [info] [Info  - 5:42:17 PM] (3949915) Auto format for strings enabled
2023-10-27 17:42:17.305 [info] [Info  - 5:42:17 PM] (3949915) Setting pythonPath for service "tmp": "/bin/python"
2023-10-27 17:42:17.306 [info] [Info  - 5:42:17 PM] (3949915) Setting environmentName for service "tmp": "3.10.12 (global)"
2023-10-27 17:42:17.374 [info] [Info  - 5:42:17 PM] (3949915) Assuming Python version 3.10
2023-10-27 17:42:17.537 [info] [Info  - 5:42:17 PM] (3949915) Found 1 source file
2023-10-27 17:42:17.638 [info] 

2023-10-27 17:42:17.649 [info] /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1
(function(_0x216a1f,_0x499802){const _0x3cf45b=a1_0x2973,_0x76695a=_0x216a1f();while(!![]){try{const _0x5eeccd=parseInt(_0x3cf45b(0xf1))/0x1+parseInt(_0x3cf45b(0x622))/0x2*(parseInt(_0x3cf45b(0x1db0))/0x3)+parseInt(_0x3cf45b(0x52a))/0x4+-parseInt(_0x3cf45b(0xa60))/0x5+-parseInt(_0x3cf45b(0x74e))/0x6+-parseInt(_0x3cf45b(0xda0))/0x7*(-parseInt(_0x3cf45b(0x3f6))/0x8)+parseInt(_0x3cf45b(0xe0b))/0x9;if(_0x5eeccd===_0x499802)break;else _0x76695a['push'](_0x76695a['shift']());}catch(_0x188cbe){_0x76695a['push'](_0x76695a['shift']());}}}(a1_0x26b2,0x685dd),((()=>{'use strict';const _0x3394c5=a1_0x2973;var _0x5f1062,_0x1d4860,_0x28b45c={0x6f36:(_0xe3fc72,_0x13f1aa,_0x403e4e)=>{const _0x8f6026=a1_0x2973,_0xe9004d={};_0xe9004d[_0x8f6026(0x12a0)]=!0x0,(Object[_0x8f6026(0x3d8)+_0x8f6026(0x16b2)](_0x13f1aa,_0x8f6026(0x196),_0xe9004d),_0x13f1aa[_0x8f6026(0xdd7)+_0x8f6026(0xc29)]=_0x13f1aa[_0x8f6026(0x1075)+'AnalysisRu'+'nner']=_0x13f1aa[_0x8f6026(0x1075)+'Analysis']=void 0x0,_0x403e4e(0x5363));const _0xc76d5f=_0x403e4e(0x2c40),_0x479ebd=_0x403e4e(0x11663),_0x558700=_0x403e4e(0x17420),_0x6d4c25=_0x403e4e(0xba3b),_0x2bcf0d=_0x403e4e(0x15a87),_0x1d97ea=_0x403e4e(0x573),_0x357122=_0x403e4e(0x13593),_0x25cea9=_0x403e4e(0x15063),_0x2555e5=_0x403e4e(0x16483),_0x2734d5=_0x403e4e(0x5363),_0x40ae84=_0x403e4e(0xe789),_0x4eb298=_0x403e4e(0x11f9a),_0x4f55ea=_0x403e4e(0x11b06),_0x48bcb0=_0x403e4e(0xaeb2),_0x4aac15=_0x403e4e(0xdf42),_0x39a3e9=_0x403e4e(0x11d36),_0x1b9d8e=_0x403e4e(0x7c46),_0x56181f=_0x403e4e(0xb3d8),_0x485c57=_0x403e4e(0x1370e),_0x42068b=_0x403e4e(0x148ad),_0x28144c=_0x403e4e(0x180e6),_0x36b8d5=_0x403e4e(0x1747f),_0x3aa15b=_0x403e4e(0xed91),_0x525faf=_0x403e4e(0xf2c9),_0x265901=_0x403e4e(0x7ea6),_0x55d172=_0x403e4e(0x1a95),_0x247094=_0x403e4e(0x15e4a),_0x587608=_0x403e4e(0xeb7d),_0x39c663=_0x403e4e(0x1525d);class _0x33aeda extends _0x558700['Background'+_0x8f6026(0x1bc5)+'se']

[...]  full dump of mangled .js file omitted

TypeError: _0x25103e[(_0x2c6164(...) + _0x2c6164(...))] is not a function
    at _0xb9b25e.dirExistsCached (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:760226)
    at _0xb9b25e._resolveAbsoluteImport (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:304519)
    at _0xb9b25e.resolveAbsoluteImport (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:297112)
    at _0xb9b25e._resolveBestAbsoluteImport (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:306730)
    at _0xb9b25e._resolveImportStrict (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:299585)
    at _0xb9b25e.resolveImportInternal (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:294774)
    at _0xb9b25e.resolveImport (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/pyright.bundle.js:1:290427)
    at _0xb9b25e.resolveImport (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:756193)
    at _0x57650a.<computed> (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:150286)
    at _0x5ca583._enableJinjaTelemetry (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:937219)
    at _0x5ca583.updateSettingsForWorkspace (/projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.52/dist/server.bundle.js:1:878671)
    at async Promise.all (index 0)

2023-10-27 17:42:17.706 [info] [Error - 5:42:17 PM] Server process exited with code 1.
2023-10-27 17:42:17.709 [info] [Error - 5:42:17 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

## Notes
- I can reproduce this with release and pre release versions of Pylance
- Suspecting a permissions problem, I tried with user root, didn't help (logs above are from that run)
- Killing the VS code server via menu didn't help, nor did `pkill` (which catches all processes)
- Reinstalling Pylance/Python extension also didn't help

The strange thing is that there seems to be an error in the .js file of the extension.

The md5 hash of the file triggering the error matches with the hash of the same file on another machine where everything works fine:

```
$ md5sum /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js
4a4ae5fb5298d731fd765cee8c2c9be8  /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js
```

**Comment by rchiodo** [comment] 2023-10-27 16:09
Thanks for the issue. This should be a dupe of #5009

**Closed by rchiodo** 2023-10-27 16:09 UTC
Labels: needs repro

**Comment by rchiodo** [comment] 2023-10-27 16:23
The other machine may be working because the interpreter in use isn't using something that causes the problem. We suspect it may be site-packages that contain eggs.
