### ISSUE TITLE
"from x import y as z" results in y being reported as undefinedVariable

### ISSUE THREAD

**Issue by yury-tokpanov** [microsoft/pylance-release#388] opened 2020-09-17 22:42 UTC
Sometime ago after Pylance update I started to notice consistently, if I do "from x import y as z", then y would be reported as not defined. If I do "from x import y", everything is fine.

Is it a bug or a supposed behavior? If supposed behavior, then why?

I have the most recent Pylance version.

**Comment by jakebailey** [comment] 2020-09-17 22:44
I believe this is a dupe of #307.

If you set the following to disable semantic highlighting and reload, does the diagnostic go away?

```json
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```

**Comment by yury-tokpanov** [comment] 2020-09-18 02:18
@jakebailey yes, it does go away. But it removes everything, including useful things.

**Comment by jakebailey** [comment] 2020-09-18 18:12
I'm assuming you mean that it hides the semantic highlighting, yes? That setting only toggles the VS Code feature.

I'll close this as a dupe of #376, as I believe them to be the same.

**Closed by jakebailey** 2020-09-18 18:12 UTC
Labels: waiting for info
