### ISSUE TITLE
code after in-line Jupyter magic (%time) not recognised

### ISSUE THREAD

**Issue by martinfleis** [microsoft/pylance-release#2176] opened 2021-12-15 15:34 UTC
## Environment data

-   Language Server version: v2021.12.2
-   OS and version: macOS 12.0.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7 via conda from conda-forge channel

## Expected behaviour

When using in-line cell magic (like `%time`) in Jupyter notebook, Pylance should understand that code after it may define a variable.

## Actual behaviour

It seems that everything after `%time` on the same line is ignored by Pylance.

## Logs

```
[Info  - 3:30:42 PM] Searching for source files
[Info  - 3:30:42 PM] Found 7 source files
[Info  - 3:30:42 PM] Searching for source files
[Info  - 3:30:42 PM] Found 7 source files
[Info  - 3:31:10 PM] No configuration file found.
[Info  - 3:31:10 PM] No pyproject.toml file found.
[Info  - 3:31:10 PM] Setting pythonPath for service "spatial_signatures_concept": "/Users/martin/mambaforge/envs/geo_dev/bin/python"
[Warn  - 3:31:10 PM] stubPath /Users/martin/Git/spatial_signatures_concept/typings is not a valid directory.
[Info  - 3:31:10 PM] Assuming Python version 3.9
[Info  - 3:31:10 PM] Assuming Python platform Darwin
Search paths for /Users/martin/Git/spatial_signatures_concept
  /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib
  /Users/martin/Git/spatial_signatures_concept
  /Users/martin/Git/spatial_signatures_concept/typings
  /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stubs/...
  /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/bundled/stubs
  /Users/martin/mambaforge/envs/geo_dev/lib/python3.9
  /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/lib-dynload
  /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages
  /Users/martin/Git/momepy
  /Users/martin/Git/pyogrio
  /Users/martin/Git/geopandas
  /Users/martin/Git/mapclassify
[Info  - 3:31:10 PM] Searching for source files
[Info  - 3:31:10 PM] Found 7 source files
Background analysis message: setConfigOptions
Background analysis message: setImportResolver
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 2:0 - 3:4 at /_NotebookConcat_2eac645a500e.py ...
[BG(1)]   parsing: /_NotebookConcat_2eac645a500e.py (28ms)
[BG(1)]   parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 1ms] (10ms)
[BG(1)]   binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/builtins.pyi (5ms)
[BG(1)]   binding: /_NotebookConcat_2eac645a500e.py (0ms)
[BG(1)]   parsing: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/__init__.py [fs read 0ms] (3ms)
[BG(1)]   binding: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/__init__.py (0ms)
[BG(1)] getSemanticTokens range 2:0 - 3:4 at /_NotebookConcat_2eac645a500e.py (48ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 4:0 - 5:4 at /_NotebookConcat_2eac645a500e.py ...
[BG(1)]   parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (4ms)
[BG(1)]   binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/typing.pyi (2ms)
[BG(1)]   parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (2ms)
[BG(1)]   binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (0ms)
[BG(1)]   parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (1ms)
[BG(1)]   binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/typing_extensions.pyi (0ms)
[BG(1)]   parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (0ms)
[BG(1)]   binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
[BG(1)] getSemanticTokens range 4:0 - 5:4 at /_NotebookConcat_2eac645a500e.py (13ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 6:0 - 6:1 at /_NotebookConcat_2eac645a500e.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: /_NotebookConcat_2eac645a500e.py ...
[BG(1)]   checking: /_NotebookConcat_2eac645a500e.py ...
[BG(1)]     parsing: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/core/getipython.py [fs read 0ms] (1ms)
[BG(1)]     binding: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/core/getipython.py (0ms)
[BG(1)]     parsing: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py [fs read 1ms] (39ms)
[BG(1)]     binding: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py (3ms)
[BG(1)]     parsing: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/traitlets/config/configurable.py [fs read 0ms] (3ms)
[BG(1)]     binding: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/traitlets/config/configurable.py (1ms)
[BG(1)]     parsing: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/traitlets/traitlets.py [fs read 0ms] (10ms)
[BG(1)]     binding: /Users/martin/mambaforge/envs/geo_dev/lib/python3.9/site-packages/traitlets/traitlets.py (3ms)
[BG(1)]     parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/re.pyi [fs read 0ms] (1ms)
[BG(1)]     binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/re.pyi (0ms)
[BG(1)]     parsing: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/enum.pyi [fs read 0ms] (0ms)
[BG(1)]     binding: /Users/martin/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist/typeshed-fallback/stdlib/enum.pyi (1ms)
[BG(1)]   checking: /_NotebookConcat_2eac645a500e.py (67ms)
[BG(1)] analyzing: /_NotebookConcat_2eac645a500e.py (67ms)
Background analysis message: resumeAnalysis
```

## Code Snippet / Additional information

```python
# this is fine
foo = 1
foo

# this says that `bar` is not defined
%time bar = foo
bar
```

https://user-images.githubusercontent.com/36797143/146200799-adc44abb-9cc9-4c59-b043-24d7d5e9161e.mov

**Comment by judej** [comment] 2022-01-03 19:08
Thanks for the report. We will look at this issue.

**Comment by judej** [comment] 2022-06-13 17:58
Dupe of https://github.com/microsoft/pylance-release/discussions/2582

**Closed by judej** 2022-06-13 17:58 UTC
Labels: bug, enhancement, notebooks
