### ISSUE TITLE
Strange Error Message when deleteing a cell in jupyter notebook 

### ISSUE THREAD

**Issue by tjdcs** [microsoft/pylance-release#5084] opened 2023-11-05 04:29 UTC
Hi all, 

First off... this issue is probably misplaced. Please help me find the right place to document and provide more information for support. 

I'm running python notebooks in a poetry managed python kernel and getting a strange issue with pylance when I delete a cell. Pylance crashes and I get a licensing error message. Please review and let me know where this is better suited and what better information I can provide. Thank you! 

<h3> Environment data </h3>

-   Language Server version: 2023.11.11
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

Open a python notebook and make a few cells with a poetry managed python kernel

<h3> Repro Steps </h3>

1. Delete a cell

<h3> Expected behavior </h3>

The language server does not crash

<h3> Actual behavior </h3>

The language server crashes and does not restart correctly 

<h3> Error message </h3>

2023-11-05 00:22:24.702 [info] [Error - 12:22:24 AM] Restarting server failed
2023-11-05 00:22:24.702 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [644d0d32deb291c91360a263db12200aa7308e7339ae4c21482bab00cfac9dcc]

  Code: -32603

**Comment by debonte** [comment] 2023-11-05 05:06
Can you please provide your full "Python Language Server" log?

**Comment by tjdcs** [comment] 2023-11-05 07:44
Here is the full log file of crashing when deleting notebook cells. It looks totally mangled to me, but maybe it's still useful. 

I didn't get the licensing warning but this is still a bad issue by itself and is probably leading to the licensing message. 

[Python Language Server.log](https://github.com/microsoft/pylance-release/files/13258902/Python.Language.Server.log)

**Comment by rchiodo** [comment] 2023-11-06 17:11
Thanks for the issue. This indicates:

```
2023-11-05 00:41:14.149 [info] Error: Debug Failure. Cell path not found for cell vscode-notebook-cell:/Users/tucker/Dev/colour-workbench/notebooks/WGM.ipynb#W2sZmlsZQ%3D%3D
    at _0x5e8922.getNotebookCellPath (/Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:261668)
    at _0x8f195a.decodeTextDocumentUri (/Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:230980)
    at _0x45a7e7.onDidCloseTextDocument (/Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:901599)
    at /Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/pyright.bundle.js:1:1144202
    at /Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234062
    at oe (/Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234284)
    at /Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230224
    at Immediate.<anonymous> (/Users/tucker/.vscode/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230244)
    at processImmediate (node:internal/timers:476:21)
```

That this is a dupe of https://github.com/microsoft/pylance-release/issues/5071

**Closed by rchiodo** 2023-11-06 17:11 UTC
Labels: needs repro

**Comment by tjdcs** [comment] 2023-11-06 18:02
Thanks @rchiodo! I also realized I was running -insiders and switched back to release for now.
