### ISSUE TITLE
Hooks to extend autocompletion suggestions

### ISSUE THREAD

**Issue by kartikgupta-db** [microsoft/pylance-release#4448] opened 2023-06-01 17:41 UTC
We have been working on an extension for vscode, where we want to extend the autocompletion functionality of Python, with some information specific to our use case. We can't use "onHover" suggestion hook provided by [vscode extension API](https://code.visualstudio.com/api/references/vscode-api#languages), because we need the parsed AST. 

It would be amazing if we can have some hooks to extend the autocomplete suggestions.

**Comment by erictraut** [comment] 2023-06-01 17:52
Exposing an API for extending pylance's completion suggestions (along with the internal parse tree representation used within pylance) would be fraught with problems — compatibility, robustness, etc., so it's not something we'd be likely to do unless the need was extremely compelling. Even then, we'd look for alternative solutions before exposing an extensibility mechanism.

Let's see if there are ways to address your needs that don't involve exposing an extension mechanism. Could you provide more details about your use case?

**Comment by kartikgupta-db** [comment] 2023-06-01 18:07
Hi @erictraut. We want to provide specific autocompletions for strings in certain functions, based on the function name. Eg
`pd.readTable("<>")` we would want to provide user with names of the specific tables they have in their catalog, for <>. 
Similarly, we have a bunch more libraries we are integrating with, where such non standard autocompletions are required. We can provided limited functionality with the existing `registerhoverProvider` but we would rather not parse AST on our own.

**Comment by erictraut** [comment] 2023-06-01 18:15
Extensibility mechanisms are notoriously difficult to get correct. You need to protect against things like crashes in the extension, memory exhaustion, performance issues (e.g. if the extension takes a long time to respond), and forward/backward compatibility issues. VS Code implements a robust extensibility mechanism already. Implementing a parallel extensibility mechanism in pylance would require us to replicate all of that infrastructure and functionality. 

Here are some alternative approaches you might want to consider:
1. If your extension is written in Python, you can use the Python interpreter to generate the AST. Then you can simply walk the AST to extract the information you want.
2. If your extension is written in TypeScript or Javascript, you could reuse the open-source parser from pyright, which is the type checker upon which pylance is built. This parser builds an AST that you could use in the same manner as suggestion 1.
3. If the "certain functions" in your use case are isolated to specific modules, you could auto-generate type stubs for those modules. When you import from these modules, pylance will use the type information in the stubs to inform its completion suggestions.

**Comment by kartikgupta-db** [comment] 2023-06-01 18:19
I like the second suggestion, as long as we can be sure that the pyright parser will respect all the same settings as pylance. Eg extraPaths, stubPath etc. 

We are making a vscode extension, so it is entirely in Typescript.

**Comment by erictraut** [comment] 2023-06-01 18:22
> as long as we can be sure that the pyright parser will respect all the same settings as pylance

The parser is just a parser. It produces an AST (abstract syntax tree) data structure. It doesn't provide any semantic analysis of the parse tree or resolve imports, so pylance settings like `extraPaths` and `stubPath` are not applicable here.

**Comment by kartikgupta-db** [comment] 2023-06-01 18:29
Pardon my limited knowledge here, but a static analyser needs to resolve imports at some point to figure out types of imported objects? So that would mean there should be a way to wire together the parser and "import resolver" to build a more comprehensive structure?

**Comment by debonte** [comment] 2024-01-30 05:30
Closing as a duplicate of https://github.com/microsoft/pylance-release/discussions/2718

**Closed by debonte** 2024-01-30 05:30 UTC
