### ISSUE TITLE
Python Language Server crashing on dirExistsCached

### ISSUE THREAD

**Issue by brenfwd** [microsoft/pylance-release#5029] opened 2023-10-27 15:34 UTC
Type: <b>Bug</b>

I created a new python file and tried to edit it. I have python 3.10.12 64-bit.

```
2023-10-27 11:32:41.755 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:898287)
    at _0x170d92.<computed> (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (/home/bforward/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:1019982)
    at async Promise.all (index 0)
```

Extension version: 2023.18.0
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 5.15.0-87-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HX with Radeon Graphics (16 x 3300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|30.58GB (25.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 7fcb7a6b-88bf-47de-bd1a-87c1563b874b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30866519
2e7ec940:30870395
pythontbext0:30864172

```

</details>

**Comment by debonte** [comment] 2023-10-27 20:23
Duplicate of #5009. We just shipped the fix for this in prerelease build 2023.10.53.

**Closed by debonte** 2023-10-27 20:23 UTC
Labels: triage-needed, needs repro
