### ISSUE TITLE
Add all missing imports for file

### ISSUE THREAD

**Issue by ShravanSunder** [microsoft/pylance-release#5929] opened 2024-05-28 13:35 UTC
Currently pylance has a context window option of adding missing imports in a file
![2024-05-28 0532 Brave Browser Microsoft](https://github.com/microsoft/pylance-release/assets/5294949/2d4e3dd1-c58d-4879-8394-97f5c6ab8aca)

It would be amazing if (like typescript in vscode) it allows adding all missing imports in file.  

![2024-05-28 0535 Brave Browser New Issue · microsoftpylance-release](https://github.com/microsoft/pylance-release/assets/5294949/a03a70c8-e97c-4d91-8298-a2e5d6dbf057)

**Comment by rchiodo** [comment] 2024-05-28 16:19
Thanks for the issue. This should be a dupe of this request here:
https://github.com/microsoft/pylance-release/discussions/5653

**Closed by rchiodo** 2024-05-28 16:19 UTC
Labels: needs repro
