### ISSUE TITLE
Pylance server crash 5 times 

### ISSUE THREAD

**Issue by MSJavaScript** [microsoft/pylance-release#5069] opened 2023-11-02 07:42 UTC
Type: <b>Bug</b>

From the previous update, the extension of Python and Pylance does not work at all. In the latest update, the Pylance extension complains that "Pylance server crash 5 times  in 3 minutes", and  the extension still does not work.

Here are some outputs.
TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (/home/USERNAME/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (/home/USERNAME/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (/home/USERNAME/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (/home/USERNAME/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:305905)

Extension version: 2023.10.50
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (10.21GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/luandong --remote=wsl+Ubuntu-20.04 --crash-reporter-id 8866418a-ec0d-47dd-985a-cac7d7f48d8f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|Memory (System)|15.79GB (10.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by HenraL** [comment] 2023-11-02 11:17
I have the same issue:
* Python version: 3.11.4
* OS and version: Windows_NT x64 10.0
* Vscode version: 
```
Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```
* Latest version of pylance: v2023.10.50
* Error:
```
2023-11-02 12:04:19.744 [info] [Error - 12:04:19 PM] Server process exited with code 1.
2023-11-02 12:04:19.744 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:898287)
    at _0x170d92.<computed> (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (c:\Users\<username>\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1019982)
    at async Promise.all (index 0)

2023-11-02 12:04:19.748 [info] [Error - 12:04:19 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by michael-2956** [comment] 2023-11-02 11:28
Switching to pre-release Pylance extension (2023.10.53) helped solve the issue for me

**Comment by debonte** [comment] 2023-11-02 13:26
@MSJavaScript, this is a duplicate of #5009 which is fixed in our latest prerelease build (2023.10.53).

**Closed by debonte** 2023-11-02 13:26 UTC
Labels: needs repro
