### ISSUE TITLE
Intellisence show methods as properties

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/pylance-release#6642] opened 2024-11-06 01:50 UTC
## Environment data

-   Pylance version: `v2024.11.1`
-   OS and version: `Win11 24H2`
-   Python version (& distribution if applicable, e.g. Anaconda): `Conda Python: 3.10.12`

## Code Snippet

```python
XXX
```

## Repro Steps

![Image](https://github.com/user-attachments/assets/b8ef94b4-d1b3-46dd-a1bf-1279f76dd00e)

## Expected behavior
When typing `np.arr`, only show methods. In fact, `.array` is not a property.

## Actual behavior
When typing `np.arr`, it show all matching methods and treat them as properties.

## Logs

```
XXX
```

**Comment by rchiodo** [comment] 2024-11-06 17:31
Thanks for the issue. I'm going to guess you're running the notebook first. At least one cell.  I believe this is a dupe of this issue here:
https://github.com/microsoft/vscode-jupyter/issues/16173

**Closed by rchiodo** 2024-11-06 17:31 UTC
Labels: needs repro
