### ISSUE TITLE
Rename symbol (F2) failed in files with pyw extension

### ISSUE THREAD

**Issue by yansnow78** [microsoft/pylance-release#2359] opened 2022-02-09 13:37 UTC
-   Language Server version: Pylance language server 2022.2.0
-   OS and version: Windows 10
-   Python version : Any version

## Expected behaviour

Rename symbol (F2) should also work when you rename symbol in file with pyw extension

## Actual behaviour

i get "no result" whenever i try to rename a symbol (f2) in file with pyw extension

## Logs

no extra log lines when rename doesn't work

**Comment by debonte** [comment] 2022-02-09 19:51
Dupe of #2332. We currently do not support .pyw files. The other issue is tracking adding that support.

**Closed by debonte** 2022-02-09 19:51 UTC
Labels: duplicate, triage
