### ISSUE TITLE
@property and property(lambda) members are not treated the same

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#1230] opened 2021-05-05 08:04 UTC
## Environment data
-   Language Server version: 2021.4.3 (pyright 320a0a2f)
(activated as the default language server in Python extension settings)
-   OS and version: Windows 10 Pro, Version	10.0.19041 Build 19041
-   Python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

## Expected behaviour

- `@property` and `property(lambda)` members should be treated the same (same member type/icon)

## Actual behaviour

- `@property` members are identified as "properties"
- `property(lambda)` members are identified as "variables"

## Code Snippet / Additional information

Consider the following code:
```python
class Test(object):
	@property
	def my_property_from_decorator(self):
		return self.foo

	my_property_from_field = property(lambda self: self.bar)


test = Test()
test.my_property_from_decorator
test.my_property_from_field
```

- `my_property_from_decorator` is listed as a "property" in the tooltip:
![image](https://user-images.githubusercontent.com/574187/117111812-72e99400-ad88-11eb-99ad-346b95a0dcb9.png)
- `my_property_from_field` is listed as a "variable" in the tooltip:
![image](https://user-images.githubusercontent.com/574187/117111878-872d9100-ad88-11eb-8a86-283f5f6b47f3.png)
- same issue in autocomplete menu, and the icons are different:
![image](https://user-images.githubusercontent.com/574187/117111974-a88e7d00-ad88-11eb-8819-10e0e1b4c984.png)

---
Side-note: weirdly enough the scopes inspector returns the same for both:
```
language	python
standard token type	Other
foreground	#9CDCFE
background	#1E1E1E
contrast ratio	11.18
semantic token type	property
foreground	variable.other.property
variable
meta.definition.variable.name
support.variable
entity.name.variable
{ "foreground": "#9CDCFE" }
textmate scopes	meta.attribute.python
meta.member.access.python
source.python
```

**Comment by erictraut** [comment] 2021-05-05 14:59
Pyright (the type checker at the heart of pylance) contains a bunch of special-case code to handle the property decorator, but it doesn't include such special cases for arbitrary calls to `property`. We're unlikely to add these special cases to accommodate this very unusual use of `property`. The problem is that the `property` class contains a bunch of special-case behaviors that are not (and cannot be) described in the standard type definition for the class.

Is there any reason why you are using `property` in such an atypical manner? Could you convert it to a decorator?

Incidentally, mypy (another popular Python type checker) treats `property` similarly. Like pyright, it includes special-case handling when it's used as a decorator (the typical use case) and otherwise treats it as a normal class instantiation with no special semantics.

**Comment by benblo** [comment] 2021-05-05 16:51
I wasn't aware this was "very unusual", I'm relatively new to Python and I think I saw this in some tutorial so I used it.
I like this syntax for one-liner accessors (similar to C#'s properties), but sure I can use decorators (or just live with the discrepancy).
I figured if this was easy to fix, then why not :) !

**Comment by judej** [comment] 2021-05-05 17:50
Assuming the decorator works for you, I'm closing this. If there is more feedback or others have a similar issue, please reopen.
thanks

**Closed by judej** 2021-05-05 17:50 UTC
Labels: triage
