### ISSUE TITLE
.env file with PYTHONPATH=... is not supported

### ISSUE THREAD

**Issue by qqgg231** [microsoft/pylance-release#275] opened 2020-08-24 06:42 UTC
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 (not conda)

## Expected behaviour

No error and should allow to "peek definition" without adding "source." to "from .....   import ....... " line

This works as expected if I disable pylance and use only Python vscode extension

More about expected behaviour:
 https://stackoverflow.com/questions/50089498/how-to-set-the-root-directory-for-visual-studio-code-python-extension

## Actual behaviour

![2020-08-24 08_26_44-app_debug py - create-import-order - Visual Studio Code](https://user-images.githubusercontent.com/11590960/91011522-bf1eea80-e5e4-11ea-98ca-29f0d0b00637.png)

## Code Snippet / Additional information

workspace structure:

![2020-08-24 08_33_49-app_debug py - create-import-order - Visual Studio Code](https://user-images.githubusercontent.com/11590960/91011737-250b7200-e5e5-11ea-9fdb-6ee27a65c881.png)

.env (which is at root of workspace)
```python
PYTHONPATH=source
```

**Comment by aykutkilic** [comment] 2020-09-01 06:03
We're also facing this issue. Latest versions VSCode became unusable for us.

**Comment by jakebailey** [comment] 2020-09-01 08:06
I am working on restoring this in the core extension (been busy with a giant refactoring), but as a workaround you can mirror the paths to `extraPaths`.

**Comment by cuchoi** [comment] 2020-09-17 05:50
I add my path to `extraPaths` and the package is still not recognized. Any ideas of how to debug this?

**Comment by jakebailey** [comment] 2020-09-17 19:42
If you can provide you set `extraPaths` to, we can look, but I don't think extraPaths not working is related to this issue (PYTHONPATH not being read), so I would prefer if you made a new issue with your info.

**Comment by johneast** [comment] 2020-09-17 20:28
We've just hit this problem.

We have automated set up tools that create the development workspace and we use the `.env` file for setting the PYTHONPATH so we can be reasonably IDE agnostic. Without this feature we can't use Pylance.

**Comment by jakebailey** [comment] 2020-09-21 21:37
Unfortunately, this isn't as simple as I had thought. With MPLS we started one server per workspace, so the environment variables made sense within each. But now with full multi-root workspace support, we can't just apply the environment variables as we did before as there's only one process. We'll need to come up with some solution to pass the environment down per-workspace, which likely means a similar solution to our pythonPath resolution (passing the info in the configuration).

**Comment by haimat** [comment] 2020-09-22 14:58
I can confirm this issue. Have an additional directory in my workspace and made that available via `PYTHONPATH` in the `.env` file, located in the workspace root. That always worked fine, however, after activating **Pylance** as Python language server the VS Code editor complains about unresolvable imports (i.e. those from the `PYTHONPATH` variable in the `.env` file). Switching back to the default Python language server does solve this issue for me.

**Comment by haimat** [comment] 2020-10-09 09:19
Hey guys, any news on this?
I would **really** like to use Pylance, but w/o `PYTHONPATH` support it is not usable for us :-(

**Comment by jakebailey** [comment] 2020-10-09 17:25
We'll update this thread when something changes. We're having a discussion about the future of path setting (as the current way isn't well designed to cover all of the different tooling between Pylance, the debugger, external linters, pytest, etc), but it might be possible to do what I said in my last message and hack the client to pass the environment variable down in the config or tack it on to extraPaths.

**Comment by egabrum** [comment] 2020-10-19 16:33
I have the same issue, but I have noticed that PYTHONPATH is properly read from .env if I run from the debugger.
Also, I have the same issue regardless whether I use jedi or pylance.

For what it's worth, I think this setting should be less obscure. By default, these thing don't work in VSCode because you need to know about PYTHONPATH and its effect, and that there is no setting for that, but you have to create a .env file... and so on.
On the other side, this just works in pyCharm, because there is a setting ("Add source roots to PYTHONPATH") that is enabled by default. Just a constructive critique.

**Comment by wshayes** [comment] 2020-11-16 15:28
Thanks - the extrapaths (python.autoComplete.extraPaths: ["./src", "./tests"]) suggestion worked great.

Pylance is a great enhancement - thank you!

**Comment by raulbocanegra** [comment] 2020-12-04 23:02
In my case worked with:
```json
"python.analysis.extraPaths": [
    "./src",
    "./another_src"
]
```

**Comment by versatran01** [comment] 2020-12-09 22:25
the `extraPaths` worked for me but afther Dec 9th update it stopped working.

**Comment by LuisPeregrinaIBM2** [comment] 2020-12-29 18:40
Please also be aware that the variable [may contain multiple paths](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH). The MS Python Language Server does not handle that, the bug template redirects to this Pylance, which at least works with "python.analysis.extraPaths" but that's manual.

**Comment by jakebailey** [comment] 2021-01-04 21:55
Yes, certainly; I don't know why MPLS didn't handle that... My WIP definitely splits on the system PATH separator.

**Comment by jakebailey** [comment] 2021-01-13 19:56
This'll be fixed in the next version of Pylance so long as you have an insiders build of the Python extension (or their stable release next week).

**Comment by jakebailey** [comment] 2021-01-13 23:49
This issue has been fixed in version 2021.1.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202111-13-january-2021

**Closed by jakebailey** 2021-01-13 23:49 UTC
Labels: enhancement, fixed in next version

**Comment by jakebailey** [comment] 2021-05-10 19:35
Please file a new issue; that should be supported, though I don't think that you can put those `${}` in .env files...

If you enable trace logging, we'll print the paths we are using and you'll be able to see what's being used.

**Comment by jakebailey** [comment] 2021-05-26 04:48
Revising this (was in my inbox sitting, sorry) @Timmmm if you're still having trouble with the `${workspaceFolder}`, that'd be worth a new issue as well. According to https://code.visualstudio.com/docs/python/environments#_variable-substitution, it should have worked, which would imply some bug in the way that Pylance is getting the environment variable from the Python extension.

**Comment by Timmmm** [comment] 2021-05-26 13:26
Are you sure it should have worked? I can't see anything on that page that says anything other than `${env:...}` would work. I just assumed it would because that would be sensible.

**Comment by jakebailey** [comment] 2021-05-26 17:06
They do only talk about `${env:...}`, but I assumed that was just an example and the rest would work (seems incongruent otherwise). Maybe @karthiknadig remembers the extent of the syntax supported.
