### ISSUE TITLE
Enum issue

### ISSUE THREAD

**Issue by Fapso** [microsoft/pylance-release#6381] opened 2024-09-11 21:30 UTC
![image](https://github.com/user-attachments/assets/2e557c7b-bf81-412d-8cb8-3f053f044c7f)
## Environment data

-   Pylance version: v2024.9.1
-   OS and version: Windows 10
-   Python version: 3.9.4

## Code Snippet
```
from enum import IntFlag

class Test(IntFlag):
    """"""
    Onet = 1
    Two = 2
    Three = 3
    Four = 4


for k in Test:
    print(k.name.lower())
```

```python
3.9.4
```

## Expected behavior

I excepected ```.name``` to always return a string, especially since all Enum's class members are hard-coded.

## Actual behavior

As you can see, it claims, whatever is returned cannot get the ```.lower()``` treatment, because it *might* be a None.

**Comment by Fapso** [comment] 2024-09-11 21:33
![image](https://github.com/user-attachments/assets/ae504a65-8b75-41e2-af85-bc35f9cf6bb7)

Pylance v2024.8.1 did not have such an issue.

**Comment by erictraut** [comment] 2024-09-11 21:34
This behavior is intended. Instances of of `Flag` (which is the parent class for `IntFlag`) can be combined to produce new (nameless) enum values. For this reason, the type definition for [Flag.name](https://github.com/python/typeshed/blob/c7c430857eec9835cdf1b688ba4fd493ab449a81/stdlib/enum.pyi#L244` in the typeshed stubs indicates that `name` can be `None`.

I'm guessing that this was recently changed in the typeshed stubs, which would explain why you didn't see this error in older versions of pylance.

**Comment by erictraut** [comment] 2024-09-11 21:38
Actually, it looks like a name is synthesized at runtime for combinations.

```python
x: Test = Test.Two | Test.Four
print(x.name.lower()) # prints "two|four"
```

So this might be a bug in the typeshed stubs. If you'd like to pursue that, you can file a bug report or PR in the [typeshed proejct](https://github.com/python/typeshed). All of the major type checkers (including pyright, which pylance is built upon) make use of these stubs.

**Comment by luanft** [comment] 2024-09-12 02:51
The same issue on Id attribute of Django models. Also on ManyToMany, ForeignKey fields

**Comment by Fapso** [comment] 2024-09-12 07:06
Trusting: https://github.com/python/cpython/blob/cbfeb6a7fe89101e24ba7f61b5d42e12b79f1c9d/Lib/enum.py#L1492, it is possible for a FlagInt to have name `None` under this condition:
```
            if not combined_value:
                pseudo_member._name_ = None
```
Seems that Pylance is doing this thing correctly, or I'm being mistaken here.

Changed `FlagInt` to `IntEnum` and the problem disappeared.

Thank you, Erictraut, for pushing me in the right direction.


> The same issue on Id attribute of Django models. Also on ManyToMany, ForeignKey fields

Luanft, indeed I have the same issue happening, but shouldn't it be a different 'bug'?

![image](https://github.com/user-attachments/assets/9a1e182a-d840-4b96-85a8-d8e99469cf75)

**Comment by heejaechang** [comment] 2024-09-19 17:55
going to close it as by design. for the other issue, please open new issue

**Closed by heejaechang** 2024-09-19 17:55 UTC
Labels: needs repro
