### ISSUE TITLE
Numpy members marked as nonexistent

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/pylance-release#460] opened 2020-10-05 19:29 UTC
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: Windows 10 v2004 build 19041.264
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.6 x64

## Expected behaviour

Correctly access members

## Actual behaviour

![image](https://user-images.githubusercontent.com/165937/95123138-58720e00-0706-11eb-8687-12b6cb971d90.png)

## Code Snippet / Additional information

As screenshot:

```python
inputColumns = ["foo", "bar", "baz"] # real one is ~200 items
dnnDepth = np.random.randint((len(inputColumns) // 25), (len(inputColumns) // 10) + 2) + 1
```

**Comment by jakebailey** [comment] 2020-10-05 19:31
Duplicate of #150.

Numpy has no stubs, it's not a good idea to run the type checker in higher than the "off" mode. Likely fixed in the next numpy release.

**Closed by jakebailey** 2020-10-05 19:31 UTC
Labels: triage
