### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Suyashbajpai27** [microsoft/pylance-release#1889] opened 2021-09-29 19:10 UTC
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.9.1246542782`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by judej** [comment] 2021-09-30 17:43
dupe of #1773

**Closed by judej** 2021-09-30 17:43 UTC
Labels: triage
