### ISSUE TITLE
`continue` is suggested inside function call

### ISSUE THREAD

**Issue by lainisourgod** [microsoft/pylance-release#4387] opened 2023-05-18 13:12 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.5.20
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
def read_data(config: dict) -> dict:
    return {}

config = {}
data = read_data(config=con|<trigger suggestion>)
```
<img width="1282" alt="CleanShot 2023-05-18 at 17 06 48@2x" src="https://github.com/microsoft/pylance-release/assets/24773652/8f39be34-9512-487d-b571-e4b33beba332">

<h3> Expected behavior </h3>

Don't suggest `continue` at all, or at least not as the first option.

<h3> Actual behavior </h3>

`continue` is a first suggestion, the obvious `config` here is only second. `continue` doesn't make sense here as I try to autocomplete a function argument.

<h3> Logs </h3>
nothing happens in logs when I trigger autosuggestion, so not providing

**Comment by debonte** [comment] 2023-05-18 19:51
This is a duplicate of https://github.com/microsoft/pylance-release/discussions/2599. Please upvote that enhancement discussion.

**Closed by debonte** 2023-05-18 19:51 UTC
