### ISSUE TITLE
Wrong None detection.

### ISSUE THREAD

**Issue by Hudrolax** [microsoft/pylance-release#4743] opened 2023-08-21 22:37 UTC
```
from asyncpg import Connection, Record

async def get_user_settings(conn: Connection, user_id: int) -> Record | None:
    """The function gets user settings."""
    result = await conn.fetchrow("""
        SELECT * FROM user_settings WHERE user_id = $1
    """, user_id)
    return result
```

After update, pylance says "None" is not awaitable. But I clearly defined the type. With the old version, I have no problem with this piece of code.

**Comment by erictraut** [comment] 2023-08-21 22:42
Thanks for the bug report. I think this is already fixed in last week's pre-release version of pylance, and the fix will be in this week's production version. You can temporarily switch to the pre-release version of pylance, and the error should go away.

**Comment by Hudrolax** [comment] 2023-08-21 22:50
Thank you! I confirm, the bug was fixed in the last pre-release version.

**Comment by Elchinchel** [comment] 2023-08-22 11:34
I dont know if this related to this issue, but seems similar.

In release (2023.8.30) version i have bug with this code:
```python
class Param:
    bar: int

async def foo(param):
    return param.bar

async def bar():
    reveal_type(foo)  # Type of "foo" is "(param: Unknown) -> Coroutine[Any, Any, Unknown]"
    reveal_type(foo(int()))  # Type of "foo(int())" is "Unknown"  # Just as example of param without 'bar' attribute
    reveal_type(foo(Param()))  # Type of "foo(Param())" is "int"

    await foo(Param())  # "int" is not awaitable
```

Switching to pre-release version fix issue, but there is another one:
```python
async def foo():
    reveal_type(foo)  # Type of "foo" is "() -> Coroutine[Any, Any, None]"
    reveal_type(foo())  # Type of "foo()" is "None"

    await foo()  # "None" is not awaitable
```


Hope this helps.

**Comment by erictraut** [comment] 2023-08-22 14:50
@Elchinchel, the last code sample that you posted above is a duplicate of https://github.com/microsoft/pyright/issues/5745, which will be fixed in this week's pylance pre-release build. It's specific to recursive coroutine calls. You can work around it in the meantime by adding an explicit `-> None` return type annotation to the function.

**Closed** 2023-08-23 18:13 UTC
Labels: needs repro
