### ISSUE TITLE
Pylance does not resolve imports automatically after installation

### ISSUE THREAD

**Issue by satheeshkatipomu** [microsoft/pylance-release#1166] opened 2021-04-16 14:50 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.4.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

`pylance` automatically resolves a package imports when it is installed.

<h3> Actual behaviour </h3>

After installing a package, `pylance` is unable to resolve the import unless reopening the window. Instead it is returning an error `reportMissingImports`

<img width="1135" alt="Screenshot 2021-04-16 at 7 05 42 PM" src="https://user-images.githubusercontent.com/44122848/115042494-2af5f080-9ef1-11eb-8de7-4162225aa1d0.png">

**Comment by navneethc** [comment] 2021-04-16 15:19
OS: WSL 2 Ubuntu 20.04
VSCode 1.55.2 + Remote - WSL 0.39.6
Python extension: 2021.3.1
Pylance: 2021.4.1
Python 3.8.2

Can confirm something similar, if not the same issue.

![image](https://user-images.githubusercontent.com/4192839/115045859-8a093480-9ef4-11eb-8383-4a3dac6f4b18.png)

**Comment by jakebailey** [comment] 2021-04-16 17:37
This is largely a dupe of #68 or #253.

Our canonical solution to this is to set extraPaths, see the troubleshooting doc: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings

But, if you could try out this WIP option, it may help your case:

```
"python.analysis.useImportHeuristic": true
```

**Comment by satheeshkatipomu** [comment] 2021-04-16 17:44
Hey @jakebailey 

I did try explicitly mentioning `site-packages` path in extra paths, but no luck there. btw I am facing this issue in both my local and remove dev container environments. 

Let me try the WIP option.

**Comment by jakebailey** [comment] 2021-04-16 17:45
Agh, I'm sorry; I was referring to @navneethc and missed your actual issue. Don't set that to fix your issue with installing packages. That's a known issue for interpreters that live outside the workspace, and I'll find the issue we have for that already.

**Comment by jakebailey** [comment] 2021-04-16 17:46
The issue about needing a reload on package install is #923; I tried to fix it once but it caused some problems so was reverted. You can follow that issue instead.

**Closed by jakebailey** 2021-04-16 17:46 UTC
Labels: triage
