### ISSUE TITLE
Pylance crashed on load with error `TypeError: e.clear is not a function`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#5000] opened 2023-10-24 16:18 UTC
```
2023-10-24 09:09:42.028 [info] [Error - 9:09:42 AM] Server process exited with code 1.
2023-10-24 09:09:42.028 [info] Error: Unhandled method python/isTrustedWorkspace
    at c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.40\dist\vendor.bundle.js:2:1472879
    at oe (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.40\dist\vendor.bundle.js:2:1473173)
    at c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.40\dist\vendor.bundle.js:2:1467932
    at Immediate.<anonymous> (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.10.40\dist\vendor.bundle.js:2:1467952)
    at processImmediate (node:internal/timers:476:21)

2023-10-24 09:09:42.038 [info] [Error - 9:09:42 AM] Connection to server got closed. Server will not be restarted.
2023-10-24 09:09:42.039 [info] [Error - 9:09:42 AM] Handling connection close failed
2023-10-24 09:09:42.039 [info] TypeError: e.clear is not a function
    at _.cleanUp (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2410357)
    at _.handleConnectionClosed (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2414781)
    at _.handleConnectionClosed (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2575750)
    at c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2414207
    at o.invoke (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2360885)
    at s.fire (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2361650)
    at te (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2347282)
    at o.invoke (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2360885)
    at s.fire (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2361650)
    at d.fireClose (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2369510)
    at ChildProcess.<anonymous> (c:\Users\kanadig\.vscode-insiders\extensions\ms-python.python-2023.19.12971007\out\client\extension.js:2:2381862)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
```

Full log here:
[pylance_crash.log](https://github.com/microsoft/pylance-release/files/13120968/pylance_crash.log)

**Comment by rchiodo** [comment] 2023-10-24 16:23
This should be a dupe of this issue: https://github.com/microsoft/pyrx/issues/4186

It should only happen if you have this setting enabled:

```jsonc
"python.analysis.enableSyncServer": true
```

And it should be fixed in our latest bits.

**Comment by rchiodo** [comment] 2023-10-24 16:24
It was caused by the LSP upgrade. The feature list that the connection creates assumes every feature implements the newer interface. Pylance didn't upgrade to 9.0 yet so it hadn't implemented the 'clear' function.

**Closed by rchiodo** 2023-10-24 16:23 UTC
Labels: needs repro

**Comment by rchiodo** [comment] 2023-10-24 16:41
Hmm, your log says you don't have 'enableSyncServer' set though. Oh no it looks like we create the feature regardless of whether or not sync server is enabled. So this would crash in async too.

@karthiknadig what version of the Python extension were you using? I assume this error was happening on a 'Restart Language Server'?

**Comment by rchiodo** [comment] 2023-10-24 16:44
Yeah it repros if I have Python prerelease and Pylance stable and then do a 'Restart Language Server'.

**Comment by rchiodo** [comment] 2023-10-24 16:45
So the fix here is to install the prerelease version of the Pylance extension.
