### ISSUE TITLE
internal error related to ms-python.vscode

### ISSUE THREAD

**Issue by aphearin** [microsoft/pylance-release#5028] opened 2023-10-27 14:34 UTC
Type: <b>Bug</b>

Out of the blue I see the following error message in my console for any python module I open with vs code. I see the same (or very similar) message regardless of the python code:

An internal error occurred while parsing file "/Users/aphearin/work/repositories/python/dsps/dsps/utils.py": TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:898287)
    at i (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:510945)
    at _0x4c3a07._resolveImports (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:511197)
    at /Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:499381
    at a.timeOperation (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1129990)
    at /Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:499348
    at t.LogTracker.log (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1092230)
    at _0x4c3a07.parse (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:498098)
    at N._parseFile (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:434006)
    at N._bindFile (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:434964)
    at /Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:436150
    at t.LogTracker.log (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1092230)
    at N._checkTypes (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:435861)
    at /Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:420596
    at runWithCancellationToken (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:843404)
    at a.timeOperation (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1130032)
    at N._runEvaluatorWithCancellationToken (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:426484)
    at N.analyze (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:420355)
    at t.analyzeProgram (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:923)
    at _0x79f29.handleResumeAnalysis (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1021122)
    at _0x79f29.handleAnalyze (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1021046)
    at _0x79f29.handleAnalyze (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:139271)
    at _0x79f29.onMessage (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1018726)
    at _0x79f29.onMessage (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:138679)
    at _0x79f29._onMessageWrapper (/Users/aphearin/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1023516)

Extension version: 2023.18.0
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (26.96GB free)|
|Process Argv|utils.py --crash-reporter-id ce60b1b9-5d58-404f-9753-8bc020d6d08a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by debonte** [comment] 2023-10-27 20:21
Duplicate of #5009. We just shipped the fix for this in 2023.10.53.

**Closed by debonte** 2023-10-27 20:21 UTC
Labels: triage-needed, needs repro

**Comment by aphearin** [comment] 2023-10-27 20:44
OK great, thanks for the quick fix and also the quick reply @debonte!

**Comment by jacopos86** [comment] 2023-10-27 22:03
can I do something about it for now ?

**Comment by debonte** [comment] 2023-10-27 22:06
Install the latest prerelease build of the Pylance extension (2023.10.53).

**Comment by jacopos86** [comment] 2023-10-27 22:12
I can see only 2023.10.50

**Comment by debonte** [comment] 2023-10-27 22:17
Find Pylance in the Extensions pane and press the "Switch to Pre-Release" button:

![image](https://github.com/microsoft/pylance-release/assets/12820898/ddfc48a9-87da-48e3-8853-5bb9ce132d5f)

**Comment by jacopos86** [comment] 2023-10-27 22:29
yes, I needed to restart the computer

**Comment by 0x4D2D** [comment] 2023-10-29 02:44
fix doesn't work, i still get the EXACT same crash, i'm on the pre-release 2023.19.13001012 but its STILL crashing???!

**Comment by debonte** [comment] 2023-10-29 02:56
@0x4D2D you need the latest prerelease of Pylance, not of the Python extension.

**Comment by aphearin** [comment] 2023-10-31 19:11
Just confirming that prerelease 2023.10.53 does indeed resolve this problem.

**Comment by dootss** [comment] 2023-11-01 06:39
works for me too, and thank you so much :)

**Comment by Richard-CokeCola** [comment] 2023-11-01 07:55
> Install the latest prerelease build of the Pylance extension (2023.10.53).

works for me too, thanks!
