### ISSUE TITLE
python and pylance keep throwing errors: unexpected indentation 

### ISSUE THREAD

**Issue by RBnzr** [microsoft/pylance-release#6374] opened 2024-09-11 00:42 UTC
Type: <b>Bug</b>

all my code base is returning with this error even tho nothing changed except vs code update even dongraded to older version and still the same issue

Extension version: 2024.14.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.77GB (43.85GB free)|
|Process Argv|--crash-reporter-id 44261052-917d-401d-b885-b5cacbea1c48|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by debonte** [comment] 2024-09-11 15:36
@RBnzr, can you please provide some more details?
- Screenshot of what you're seeing.
- Full text of the diagnostics you're seeing.
- Version numbers of the extensions where you saw the issue vs. where it did not occur?

**Comment by debonte** [comment] 2024-09-11 23:30
@RBnzr, looks like this is a duplicate of https://github.com/microsoft/pylance-release/issues/6373?

**Closed** 2024-09-12 15:18 UTC
Labels: waiting for user response, needs repro
