### ISSUE TITLE
Create Type Stub fails silently

### ISSUE THREAD

**Issue by MrTheSaw** [microsoft/pylance-release#5271] opened 2023-12-17 19:43 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.12.100
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

- Running remote: VSCode on macOS, vscode-server on Ubuntu 20.04

<h3> Code Snippet </h3>

```python
from icecream import ic
```

<h3> Repro Steps </h3>

1. hover on "icecream"
2. choose Quick Fix
3. click on "Create Type Stub"

<h3> Expected behavior </h3>

Type stubs created or system tells me why it can't, with enough detail to allow me to correct the problem.

<h3> Actual behavior </h3>

Nothing. No dialog, no log, nothing new in the "Output"
BTW: My current log level is "Trace"
I did **Trace** logging, everything got very verbose, but **nothing** new appeared when I tried the Quick Fix. 

Note that when I run my code, it runs as expected, calls to the icecream library are used throughout.
<h3> Logs </h3>

Nothing new in **any** log when I run the Quick Fix.

**Comment by debonte** [comment] 2023-12-18 17:52
Duplicate of https://github.com/microsoft/pylance-release/issues/5188

**Closed by debonte** 2023-12-18 17:52 UTC
Labels: needs repro
