### ISSUE TITLE
Invalid type deduction using match-by-position syntax with 3rd party library

### ISSUE THREAD

**Issue by ihor-rud** [microsoft/pylance-release#2327] opened 2022-02-03 11:05 UTC
## Environment data
-   Language Server version: v2022.1.6-pre.1
-   OS and version: Windows 10 Pro 21H1 19043.1503 wsl2 Ubuntu-20.04
-   Python version: Python 3.10.2

## Expected behaviour

type of variable data is str
like here:
![image](https://user-images.githubusercontent.com/31574816/152330404-27df2483-519f-45ed-b98d-3db5499fbc02.png)

## Actual behaviour

type of variable data is unknown
![image](https://user-images.githubusercontent.com/31574816/152328077-d4918b3f-ffa0-43ef-9648-baae4f9660bf.png)

mypy from master branch does not detect any issue in code above.
using match-by-name (see `Expected behaviour`) syntax works as expected.
copy-pasting Ok class definition into foo.py insted of importing it from result library fixes error.

## Logs
```
Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
> conda info --json
> ~/.local/share/virtualenvs/foo-axPv8F9-/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
Python interpreter path: ~/.local/share/virtualenvs/foo-axPv8F9-/bin/python
> ~/.local/share/virtualenvs/backend-3s6fGLx4/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> ~/.local/share/virtualenvs/backend-NpB-Rz6Z/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> ~/.local/share/virtualenvs/schema-loader-7edZk0mg/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /bin/python3.10 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /bin/python3.9 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3.10 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3.9 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
Starting Pylance language server.
> conda --version
```
```
[Info  - 11:21:36 AM] (23788) Pylance language server 2022.1.6-pre.1 (pyright 8d096292) starting
[Info  - 11:21:36 AM] (23788) Server root directory: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist
[Info  - 11:21:36 AM] (23788) No configuration file found.
[Info  - 11:21:36 AM] (23788) No pyproject.toml file found.
[Info  - 11:21:36 AM] (23788) Setting pythonPath for service "foo": "/home/ihor/.local/share/virtualenvs/foo-axPv8F9-/bin/python"
[Warn  - 11:21:36 AM] (23788) stubPath /home/ihor/Documents/foo/typings is not a valid directory.
[Info  - 11:21:36 AM] (23788) Assuming Python version 3.10
[Info  - 11:21:36 AM] (23788) Assuming Python platform Linux
[Info  - 11:21:36 AM] (23788) Search paths for /home/ihor/Documents/foo
[Info  - 11:21:36 AM] (23788)   /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib
[Info  - 11:21:36 AM] (23788)   /home/ihor/Documents/foo
[Info  - 11:21:36 AM] (23788)   /home/ihor/Documents/foo/typings
[Info  - 11:21:36 AM] (23788)   /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/...
[Info  - 11:21:36 AM] (23788)   /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/bundled/stubs
[Info  - 11:21:36 AM] (23788)   /usr/lib/python3.10
[Info  - 11:21:36 AM] (23788)   /usr/lib/python3.10/lib-dynload
[Info  - 11:21:36 AM] (23788)   /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages
[Info  - 11:21:36 AM] (23788) Adding fs watcher for library directories:
 /usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages
[Warn  - 11:21:37 AM] (23788) Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:21:37 AM] (23788) Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:21:37 AM] (23788) Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 11:21:37 AM] (23788) Adding fs watcher for directories:
 /home/ihor/Documents/foo
[Info  - 11:21:37 AM] (23788) Searching for source files
[Info  - 11:21:37 AM] (23788) Found 1 source file
[Info  - 11:21:37 AM] (23788) Background analysis(1) root directory: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist
[Info  - 11:21:37 AM] (23788) Background analysis(1) started
(23788) Background analysis message: setConfigOptions
(23788) Background analysis message: setImportResolver
(23788) Background analysis message: ensurePartialStubPackages
(23788) Background analysis message: setTrackedFiles
(23788) Background analysis message: markAllFilesDirty
(23788) Background analysis message: setFileOpened
(23788) Background analysis message: analyze
(23788) [BG(1)] analyzing: /home/ihor/Documents/foo/foo.py ...
(23788) [BG(1)]   parsing: /home/ihor/Documents/foo/foo.py (13ms)
(23788) [BG(1)]   parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (85ms)
(23788) [BG(1)]   binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/builtins.pyi (36ms)
(23788) [BG(1)]   binding: /home/ihor/Documents/foo/foo.py (1ms)
(23788) [BG(1)]   checking: /home/ihor/Documents/foo/foo.py ...
(23788) [BG(1)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (9ms)
(23788) [BG(1)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (1ms)
(23788) [BG(1)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 0ms] (20ms)
(23788) [BG(1)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing.pyi (9ms)
(23788) [BG(1)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (8ms)
(23788) [BG(1)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[Info  - 11:21:37 AM] (23788) Indexer background runner(2) root directory: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist (index)
[Info  - 11:21:37 AM] (23788) Indexing(2) started
(23788) [BG(1)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (14ms)
(23788) [BG(1)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/types.pyi (4ms)
(23788) [BG(1)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
(23788) [BG(1)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
(23788) [BG(1)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py [fs read 0ms] (1ms)
(23788) [BG(1)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py (0ms)
(23788) [BG(1)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/result.py [fs read 0ms] (7ms)
(23788) [BG(1)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/result.py (2ms)
(23788) [BG(1)]   checking: /home/ihor/Documents/foo/foo.py (122ms)
(23788) [BG(1)] analyzing: /home/ihor/Documents/foo/foo.py (258ms)
(23788) Background analysis message: resumeAnalysis
(23788) [BG(1)] indexing: /home/ihor/Documents/foo/foo.py [found 2] (1ms)
(23788) Indexing Done: /home/ihor/Documents/foo/foo.py
(23788) [IDX(2)] index libraries /home/ihor/Documents/foo ...
(23788) [IDX(2)]   read stdlib indices (66ms)
(23788) [IDX(2)]   scan packages [found 14 modules over 1 exec env] (64ms)
(23788) [IDX(2)]   index execution environment /home/ihor/Documents/foo ...
(23788) [IDX(2)]     parsing: /usr/lib/python3.10/xml/__init__.py [fs read 0ms] (11ms)
(23788) [IDX(2)]     parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (54ms)
(23788) [IDX(2)]     binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/builtins.pyi (14ms)
(23788) [IDX(2)]     binding: /usr/lib/python3.10/xml/__init__.py (0ms)
(23788) [IDX(2)]     indexing: /usr/lib/python3.10/xml/__init__.py [found 0] (0ms)
(23788) [IDX(2)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pip/__init__.py [fs read 1ms] (3ms)
(23788) [IDX(2)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pip/__init__.py (0ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pip/__init__.py ...
(23788) [IDX(2)]       parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 0ms] (18ms)
(23788) [IDX(2)]       binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/typing.pyi (3ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pip/__init__.py [found 3] (22ms)
(23788) [IDX(2)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pkg_resources/__init__.py [fs read 0ms] (37ms)
(23788) [IDX(2)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pkg_resources/__init__.py (3ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pkg_resources/__init__.py ...
(23788) [IDX(2)]       parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/pkgutil.pyi [fs read 0ms] (6ms)
(23788) [IDX(2)]       binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stdlib/pkgutil.pyi (0ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/pkg_resources/__init__.py [found 71] (7ms)
(23788) [IDX(2)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py [fs read 0ms] (0ms)
(23788) [IDX(2)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py (1ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py ...
(23788) [IDX(2)]       parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/result.py [fs read 0ms] (1ms)
(23788) [IDX(2)]       binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/result.py (0ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/result/__init__.py [found 7] (1ms)
(23788) [IDX(2)]     parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/__init__.py [fs read 0ms] (10ms)
(23788) [IDX(2)]     binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/__init__.py (1ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/__init__.py ...
(23788) [IDX(2)]       parsing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/_deprecation_warning.py [fs read 0ms] (0ms)
(23788) [IDX(2)]       binding: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/_deprecation_warning.py (0ms)
(23788) [IDX(2)]       parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/extension.pyi [fs read 0ms] (0ms)
(23788) [IDX(2)]       binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/extension.pyi (1ms)
(23788) [IDX(2)]       parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/dist.pyi [fs read 0ms] (1ms)
(23788) [IDX(2)]       binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/dist.pyi (0ms)
(23788) [IDX(2)]       parsing: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/depends.pyi [fs read 0ms] (0ms)
(23788) [IDX(2)]       binding: /home/ihor/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.6-pre.1/dist/typeshed-fallback/stubs/setuptools/setuptools/depends.pyi (0ms)
(23788) [IDX(2)]     indexing: /home/ihor/.local/share/virtualenvs/foo-axPv8F9-/lib/python3.10/site-packages/setuptools/__init__.py [found 8] (3ms)
(23788) [IDX(2)]   index execution environment /home/ihor/Documents/foo [found 8805 in 425 files] (170ms)
(23788) [IDX(2)] index libraries /home/ihor/Documents/foo [found 8805 in 1 exec envs] (301ms)
[Info  - 11:21:37 AM] (23788) Indexer done(2). indexed 425 files
```
## Code Snippet / Additional information
result library repo https://github.com/rustedpy/result
```python
from result import Ok

val = Ok("foo")

match val:
    case Ok(data): print(data) # Type of "data" is unknown
    case _: print('no match')
```

**Comment by erictraut** [comment] 2022-02-03 22:40
Thanks for reporting. The problem is that this is a "py.typed" library, and the `__match_args__` symbol in the `Ok` class is not annotated. Pyright (the type checker upon which Pylance is built) generally does not infer types of symbols in "py.typed" libraries, so it is evaluating the type of `__match_args__` as `Unknown`. It should make an exception for `__match_args__` and allow its type to be inferred from the tuple expression that is assigned to it. I'll work on a fix.

**Comment by erictraut** [comment] 2022-02-03 22:54
This will be fixed in the next release.

**Comment by debonte** [comment] 2022-02-10 04:19
This issue has been fixed in version 2022.2.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202221-9-February-2022)

**Closed by debonte** 2022-02-10 04:19 UTC
Labels: bug, fixed in next version

**Comment by cartercanedy** [comment] 2023-12-19 21:05
I'm actually implementing something similar here:
```python
from typing import (
  Type,
  Self,
  assert_type,
)

from dataclasses import dataclass

class Option[ TSome ]:
  @dataclass
  class Some:
    some : TSome
  
  Value : Some | None

  @classmethod
  def FromSome( cls : Type[ Self ] , value : TSome ) -> Self:
    opt = cls()
    opt.Value = Option.Some( value )
    return opt
  
  @classmethod
  def FromNone( cls : Type[ Self ] ) -> Self:
    opt = cls()
    opt.Value = None
    return opt
```
But I am getting this error ![pylance option type deduction error in pattern match](https://github.com/microsoft/pylance-release/assets/99052281/f56c75b3-ca1d-4fa4-b0ff-aadd5678a0de)

**Comment by cartercanedy** [comment] 2023-12-19 21:07
I want to say that this probably has something to do with the new 3.12 generic type syntax, but that's just conjecture on my part
