### ISSUE TITLE
Ctrl + Click (or F12) does not take me to the Definition or Reference in my python code.

### ISSUE THREAD

**Issue by JulianInskip** [microsoft/pylance-release#5059] opened 2023-10-31 17:50 UTC
## Environment data

-   Language Server version: English
-   OS and version: Windows 10 and Windows Server 2022 Datacenter
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16 64-bit

## Code Snippet

```python
XXX
```

## Repro Steps

1. Using pylance 2023.10.50 - Ctrl + Click (or F12) does not take me to the Definition or Reference in my python code.
2. Revert back to pylance 2023.10.40 - Ctrl + Click (or F12) does take me to the Definition or Reference in my python code.

## Expected behavior

Ctrl + Click (or F12) should take me to the Definition or Reference in my python code.

## Actual behavior

Ctrl + Click (or F12) does not take me to the Definition or Reference in my python code.

## Logs

```
XXX
```

**Comment by bdpedigo** [comment] 2023-11-01 23:25
I'm having the same issue but on Mac 12.6.3, Python 3.11

I usually don't have this issue when I've first started VS Code, but eventually an error message pops up and it looks like Pylance can't restart. Below is the log output 

```
2023-11-01 16:20:29.080 [info] Error: Debug Failure. Unable to find notebook URI for vscode-notebook-cell:/Interactive-1.interactive#W2sdW50aXRsZWQ%3D
    at _0x4f6f08._getNotebookUri (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:377799)
    at _0x4f6f08.getNotebookPathFromCell (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:375944)
    at _0x4f6f08.getNotebookCellPath (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:375163)
    at _0x29682b.decodeTextDocumentUri (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:347323)
    at _0x5e13d0.onDidCloseTextDocument (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js:1:1035718)
    at /Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/pyright.bundle.js:1:1143599
    at /Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/vendor.bundle.js:2:1471770
    at oe (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/vendor.bundle.js:2:1471992)
    at /Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/vendor.bundle.js:2:1467932
    at Immediate.<anonymous> (/Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist/vendor.bundle.js:2:1467952)
    at processImmediate (node:internal/timers:476:21)

2023-11-01 16:20:29.158 [info] [Error - 4:20:29 PM] Server process exited with code 1.
2023-11-01 16:20:29.162 [info] [Info  - 4:20:29 PM] Connection to server got closed. Server will restart.
2023-11-01 16:20:29.162 [info] true
2023-11-01 16:20:29.820 [info] [Info  - 4:20:29 PM] (65723) Pylance language server 2023.10.50 (pyright cfe56bfb) starting
2023-11-01 16:20:29.820 [info] [Info  - 4:20:29 PM] (65723) Server root directory: /Users/bpedigo/.vscode/extensions/ms-python.vscode-pylance-2023.10.50/dist
2023-11-01 16:20:29.826 [info] [Error - 4:20:29 PM] Server initialization failed.
2023-11-01 16:20:29.826 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603 
2023-11-01 16:20:29.826 [info] [Error - 4:20:29 PM] Pylance client: couldn't create connection to server.
2023-11-01 16:20:29.826 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603 
2023-11-01 16:20:29.826 [info] [Error - 4:20:29 PM] Restarting server failed
2023-11-01 16:20:29.826 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603 

```

It seems like this might also be related to the jupyter interactive window; I usually notice this error popping up when I have to restart the jupyter notebook kernel. 

Please let me know if I can provide any further information.

**Comment by rchiodo** [comment] 2023-11-01 23:46
Thanks @bdpedigo. Your issue looks like a dupe of https://github.com/microsoft/pylance-release/issues/5037. At least the first error message. The second problem with restarting the language server seems like a separate issue.

**Comment by KacieKK** [comment] 2023-12-05 01:12
Hey @JulianInskip , 
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Closed** 2024-01-05 00:23 UTC
Labels: waiting for user response, needs repro
