### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by au1bhi** [microsoft/pylance-release#6537] opened 2024-10-08 15:27 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2024.9.2`
- OS Version: `Windows_NT x64 10.0.22631`
- VS Code version: `1.94.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/au1bhi/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by debonte** [comment] 2024-10-08 16:38
@au1bhi, can you provide more details? Does this only occur with certain projects? When using certain packages? Can you provide access to a project that reproduces this behavior?

**Comment by blacelle** [comment] 2024-10-22 20:09
I had a similar issue having opened a large (5MB csv) file next to some `.py` file. Closing it lead to Pylance being more CPU-friendly.

**Comment by debonte** [comment] 2024-10-22 21:26
@blacelle, please file a separate issue. There are many things that could cause the symptom of high CPU usage. We can resolve the two issues as dupes if we find they have the same underlying cause, but at the moment we have no reason to believe that your issue and the OP's issue are the same.

**Comment by blacelle** [comment] 2024-10-23 06:12
I open https://github.com/microsoft/pylance-release/issues/6591

**Closed** 2024-12-31 11:22 UTC
Labels: waiting for user response, needs repro
