### ISSUE TITLE
PyLance using "object()" docs, instead of user-defined

### ISSUE THREAD

**Issue by JulianOrteil** [microsoft/pylance-release#1205] opened 2021-04-29 13:42 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.4.2
-   OS and version: win32 x64 | Windows 10
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.8; using Anaconda
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Use the user-defined docs instead of `object()`'s.

**Example**
![image](https://user-images.githubusercontent.com/23083317/116557874-7ed6e100-a8c4-11eb-90f3-98099df934d9.png)

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/23083317/116557735-5949d780-a8c4-11eb-9b5b-72205b785af6.png)

Also very intermittent. Works sometimes, but not always.

<h3> Logs </h3>

Python Language Server Log

[pylancelog.txt](https://github.com/microsoft/pylance-release/files/6398997/pylancelog.txt)

<h3> Code Snippet / Additional information </h3>

```python
```

**Comment by JulianOrteil** [comment] 2021-06-05 00:27
Checking up on this. Haven't heard back as to whether this is being investigated?

**Comment by jakebailey** [comment] 2021-06-05 00:35
This has to do with the way that we look up docs for init functions. Right now, it appears as though we are looking up the class hierarchy for a doc for `__init__`, then looking up the class hierarchy for a class doc. With this method, we hit object's `__init__` function first.

Changing this so that we walk up the hierarchy once (init then class, repeatedly) would fix this, but cause other issues where the parent class's method doc is what is intended (plus is a little hard to do).

I think that we can probably just omit object's init function doc from our builtin scraped output for now as a workaround, but this does need more testing and speccing (and we have been working on other things, hence the lack of updates; but we do know the root cause).

**Comment by JulianOrteil** [comment] 2021-06-05 21:41
@jakebailey Excellent, thank you for the update.

It's not a major problem, just an annoying persistent one. Let me know if you need anything further from me :)

**Comment by RileyMShea** [comment] 2021-08-12 03:04
@jakebailey I'm currently seeing this on a large subset of classes.  I agree I'd much rather be shown no docstring than see the base `object` string.  

One such example is the `Timeout` class from httpx https://github.com/encode/httpx/blob/b43af721cd7804214396b5511e4f68d144a9b6a6/httpx/_config.py#L190

**Comment by jakebailey** [comment] 2021-09-02 19:29
This is technically a duplicate of #1047, but my plan for this specific issue in the short term is to disable docstring inheritance from the builtins (so no classes get `object`'s docs), as they generally don't appear to be useful (not even the dunder method docs).

**Comment by jakebailey** [comment] 2021-09-07 20:48
The next release will include the above change.

**Comment by JulianOrteil** [comment] 2021-09-08 13:48
> The next release will include the above change.

Thank you for your work with this, Jake. I appreciate it :)

**Comment by jakebailey** [comment] 2021-09-08 21:21
This issue has been fixed in version 2021.9.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202191-8-september-2021

**Closed by jakebailey** 2021-09-08 21:21 UTC
Labels: bug, fixed in next version, in backlog, docstrings, in iteration
