### ISSUE TITLE
Missing ellipsis in displayed type of tuples created using `tuple(iterable)`

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#881] opened 2021-01-26 08:00 UTC
## Environment data

-   Language Server version: Pylance 2021.1.2
-   OS and version: Irrelevant
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 (Anaconda)

## Example code

```python
a = (int(0),)
b = tuple(a)

# We can find that Pylance treats `a` and `b` differently, as their types are indeed different.
(_, _) = a  # Error reported: "Tuple size mismatch: expected 2 but received 1".
(_, _) = b  # No error reported. Runtime error will be expected.
```

## Actual behavior

Types of `a` and `b` are both displayed as `tuple[int]`.

## Expected behavior

Type of `b` is displayed as `tuple[int, ...]` while type of `a` is still displayed as `tuple[int]`.

**Comment by Azureblade3808** [comment] 2021-01-26 08:02
I have modified the bundled "dist/typeshed-fallback/stdlib/3/builtins.pyi", from

```python
# from line 668 through 669
class tuple(Sequence[_T_co], Generic[_T_co]):
    def __new__(cls: Type[_T], iterable: Iterable[_T_co] = ...) -> _T: ...
```

to

```python
class tuple(Sequence[_T_co], Generic[_T_co]):
    @overload
    def __new__(cls: Type[tuple], iterable: Iterable[_T_co] = ...) -> Tuple[_T_co, ...]: ...
    @overload
    def __new__(cls: Type[_T], iterable: Iterable[_T_co] = ...) -> _T: ...
```

with the 3 lines in the middle inserted.

It has worked so far, but I'm unsure if it was a good fix.

**Comment by erictraut** [comment] 2021-01-26 16:39
Pyright is doing the correct thing given the type information in builtins.pyi.

The solution you've suggested has some problems. The biggest issue is that it breaks the ability to subclass the tuple class.

I don't see a good way to fix this prior to the introduction of [PEP 646](https://www.python.org/dev/peps/pep-0646/), which is still in the draft phase. Once there is support for variadic type variables, we'll be able to provide a proper type signature in this case. That could take as much as a year for this PEP to be finalized and all of the type checkers to introduce support. Only then can the builtins.pyi be updated.

In the meantime, you might want to post a tracking bug in the typeshed repo.

I'm going to close this work item because it's not a bug in pyright.

**Closed** 2021-01-26 18:45 UTC
Labels: triage, waiting for upstream
