### ISSUE TITLE
Pylance does not work properly with networkx

### ISSUE THREAD

**Issue by ldorigo** [microsoft/pylance-release#682] opened 2020-12-03 16:42 UTC
Issue Type: <b>Bug</b>

Networkx is a popular library for doing network analysis.

At the moment, pylance does not show contextual info (documentation, type hints)  when using networkx. For instance:

```python
import networkx as nx

nx.readwrite.gpickle.<tab>
```

Does not show anything, instead of showing the proper module members.

I am not sure if this is an issue with the upstream package, but I thought you might want to know.

Extension version: 2020.12.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.79-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2216)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (4.69GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 66ea3ec9-05eb-4edd-8d35-34bbe6c1aba1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/local/share/xsessions/plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by judej** [comment] 2020-12-03 21:37
@ldorigo, thanks for the report. The reason the completions are not showing is because networkx does not explicitly export the `readwrite` module or the `gpickle` module. if you look at the top level `__init.py__` you will notice that `readwrite` is not exported like they have done with `from networkx.testing.test import run as test` 

Therefore, you will need to explicitly import the gpickle module like `import networkx.readwrite.gpickle as gp` and then `gp.` should give you completions.

Please let me know if you have further questions.
Thanks

**Comment by judej** [comment] 2020-12-29 21:52
Closing issue. Please reopen if necessary.

**Closed by judej** 2020-12-29 21:52 UTC
Labels: waiting for info

**Comment by goyalyashpal** [comment] 2023-04-18 11:44
Reproduction successful, under "discussion" upstream at: https://github.com/networkx/networkx/discussions/6638

### Steps to Reproduce

1. Open VSCodium with `ms-python.python` extension enabled
2. Save this following code to a file with python valid file name & extension and 
open it with vscodium > ensure language mode is set to Python
3. This requires turning on the "Python Type Checking Mode" from status bar (default 
is off). This will show as Set to "basic".
    1. Open the Problems Panel `ctrl + shift + m` or
    2. Hover over or click on `draw` (line 9) and then do `ctrl + shift + p` Command 
    Palette > type `hover` > select "Show definition preview hover"
4. Click on `draw` (line 9) > press `f12` "Go to definition"
 

```python
import networkx
import matplotlib.pyplot as plt

edges = [(1,2),(2,3),(2,4)]

nxgraph = networkx.DiGraph()
nxgraph.add_edges_from(edges)

# networkx.draw_networkx(nxgraph)
networkx.draw(nxgraph)
plt.show()

```

### Current Behavior (for corresponding step )

3. "draw_networkx" is not a known member of module "networkx" Pylance [reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues) [Ln 9, Col 10]
(function) draw_networkx: Unknown
4. No definition found for `draw_networkx`

### Environment

Python: 3.11.2 (via `python --version`)
NetworkX: 3.1 (via `pip list | grep networkx`)
OS: Windows 10 22H2 x64

VSCodium: 1.77.0
Pylance extension `ms-python.vscode-pylance` : v2023.3.41
Python extension `ms-python.python` : v2023.6.0

**Comment by debonte** [comment] 2023-04-18 16:08
@goyalyashpal, this is a problem with our bundled `networkx` stubs. Please open a new issue.
