### ISSUE TITLE
Pylance can't format code when pressing enter

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#574] opened 2020-11-06 09:17 UTC
## Environment data

-   Language Server version: **v2020.11.0**
-   OS and version: **Windows_NT x64 10.0.19042**
-   Python version (& distribution if applicable, e.g. Anaconda): **v2020.10.332292344**

## Expected behaviour

When I select the Microsoft language server, the code is automatically formatted by pressing enter.
![format](https://user-images.githubusercontent.com/65096819/98348531-d7cf6600-2053-11eb-9cb2-12d6644c4ab9.gif)

## Actual behaviour

When I switch to the Pylance language server, the code is not automatically formatted by pressing enter.
![cant_format](https://user-images.githubusercontent.com/65096819/98348575-e3bb2800-2053-11eb-99a0-ea2a576328fc.gif)

**Comment by huguesv** [comment] 2020-11-06 18:35
Duplicate of https://github.com/microsoft/pylance-release/issues/283

**Closed by huguesv** 2020-11-06 18:35 UTC
Labels: triage
