### ISSUE TITLE
Proper syntax highlight for type hints

### ISSUE THREAD

**Issue by lowercase00** [microsoft/pylance-release#796] opened 2021-01-03 06:20 UTC
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: MacOS High Sierra
-   Python version (Pyenv): 3.7.6

## Expected behaviour
Proper syntax highlight for anotation-based type hints after customization of `editor.semanticTokenColorCustomizations`.
```javascript
"editor.semanticTokenColorCustomizations": {
    "[dark-plus-syntax]": {
        "enabled": true,
        "rules": {
            "typeHint": "#45C9B0" // tried `*.typeHint`, same behaviour
        }
    },
},
```

## Actual behaviour
Without any customization:
![Screen Shot 2021-01-03 at 03 17 40](https://user-images.githubusercontent.com/21188280/103472972-4853e400-4d72-11eb-8b87-b2348f396833.png)

After the customization (notice the change in foreground). Only seems to have any effect with the "enabled" key.
![Screen Shot 2021-01-03 at 03 17 17](https://user-images.githubusercontent.com/21188280/103472971-45f18a00-4d72-11eb-9f26-bc466ea1646b.png)

It seems that started to consider it as a `variable` and use that blueish variable color.

**Comment by judej** [comment] 2021-01-05 18:27
@lowercase00, thanks for the report. `abc` above IS a variable - as the hover indicates. So, I am unsure what the issue is. Could you please clarify?
thanks!

**Comment by lowercase00** [comment] 2021-01-05 18:31
hi @judej  what happens is that every single "variable:  turns blue when I add the logic to add color do the type hint.
Even though it IS a variable indeed, it wasn't considered as such before (more in the line of a simple "declaration" or something), to `abc` was white before (which is the expected behavior, and after I added the rule to add color to the typeHint, it completely changed the behavior of the variables.

**Comment by jakebailey** [comment] 2021-01-05 18:52
Unless I'm mistaken, the change you're seeing is enabling and disabling semantic tokenization as a whole, not that the typehint change is doing anything, no?

The white variables are the old-style TextMate profile highlights, which have no context as to what any given thing are (mostly). White means "I don't know", and the profile included with VS Code does not apply any color to variables. You can change the color of the variable token (not the type hint token) if you want variables to be white again. Changing the type hint only changes things after the `:` (the part that is the annotation).

**Comment by lowercase00** [comment] 2021-01-05 18:57
@jakebailey  hmm.. I don't know, it is indeed changing the semantic tokenization as a whole, but the green I've chosen for the type hint is also being applied to the function (after the `=`), so there might be two things happening:

1. Semantic Tokenizatoin is being applied and basically changing the whole theme
2. There's a bug with the type hint rule, that makes it colorize things even after the `=`

Does that make sense, maybe?

**Comment by jakebailey** [comment] 2021-01-05 19:03
Green is the default color for classes, and `datetime` is a class, so you're seeing it as green. If you use the token menu to look at the two `datetime` tokens, you should see that they are both marked as classes, just that the one after the `:` before the `=` is marked as a type hint (as it's the annotation itself, and some people want to override those colors specifically).

If you want to do a comparison, I would turn semantic highlighting on and off without any overrides to see the difference. I don't really see anything in these screenshots as unexpected; the old TextMate colorization had no info about varibles and marked many things as white (unknown), so it would appear like things were being changed a bunch.

**Comment by lowercase00** [comment] 2021-01-05 19:12
Got it. If that's the case, the `typeHint` modifier is not overwriting anything (I tested using a random color different from the class one). Maybe this is just the way it was design (the `semantic token type` > `modifier`)... Anyways, thanks for the attention, I guess I'll just stick with the old version of things and give up typehint customization..

**Comment by jakebailey** [comment] 2021-01-05 19:14
I think if you describe what you're looking to change, we should be able to point you in the right direction of what you can configure to get it to work. Things should be customizable enough to change the colors of variables back to white if that is your preference.

**Comment by lowercase00** [comment] 2021-01-05 19:17
I was trying to have my exact same setup, only with a standard color for type hints: at the moment type hints are only being colored if there are native (str, int, list, dict, etc) and don't work for other types (`datetime` for example).

So in this picture:
![Screen Shot 2021-01-05 at 16 15 38](https://user-images.githubusercontent.com/21188280/103689010-79e6ce00-4f71-11eb-91c8-ebac8a02b3ee.png)


The only difference would be the last line would have the `datetime` type hint colored green, just like `int` and `str`

**Comment by jakebailey** [comment] 2021-01-05 19:23
That's the coloring of the old TextMate profile, which hardcoded the builtin types as being classes (green), and then treated anything that looked like a call as a function (yellow). The rest are unknown, so become white (default text color in VS Code).

I'd think what you're looking for is:

```jsonc
"editor.semanticTokenColorCustomizations": {
    "[dark-plus-syntax]": {
        "rules": {
            "variable": "#000000"
        }
    },
},
```

Similar to what's written in: https://github.com/microsoft/pylance-release/issues/323#issuecomment-698023291

Then you'd still have `datetime` as green (as it is a type), but variables return to being white. If that's not enough, you may be able to extend this to more token types, like:

```jsonc
"editor.semanticTokenColorCustomizations": {
    "[dark-plus-syntax]": {
        "rules": {
            "variable": "#000000",
            "property": "#000000"
        }
    },
},
```

And so on.

**Comment by lowercase00** [comment] 2021-01-05 19:35
Makes sense, thanks a lot.
I'm not really used to having parameters definitions (within a method) being the same color as the parameters being utilized (within the method itself), also not very used to having the class instancing (calling a class) as being treated the same way as the class definition, but I can definitely see how this would be useful, so I might try to give it a go.

Also, a bit out of scope, but when I did `abc = string_var + integer_var` (summing an `int` and `str`) didn't say anything, I thought Pylance understood the typing (a bit like `mypy`) enough to warn me that this operation would lead to an `Exception`.

**Comment by jakebailey** [comment] 2021-01-05 19:41
It's important to note that semantic highlighting highlights each token with its meaning; a class is a class regardless of how it's referred to; being called doesn't change that the token `datetime` is still the class ("bound" to a specific type, in our analysis' terms). I can just as easily write `SomeClass()()()()` and it would still be green or just do `isinstance(x, SomeClass)` and it be green. Before, the only way that the editor know that a given token was a class was in the class definition (where the only context that's needed was the keyword `class`) or via special casing the builtins and hoping it was right (as you're seeing when you do say `int("1234")`; that's green before as well). Try doing `int = "broke it"`, and you'll see that we understand that uses of `int` after the assignment are no longer a class.

RE: your extra question, Pylance has type checking disabled by default (as most people are uninterested in the messages at the moment, comparing with jedi or MPLS), but you can change the type checking mode to "basic" or higher to get those sorts of messages.

**Comment by jakebailey** [comment] 2021-01-25 21:56
Unless I'm mistaken, I don't think there's anything to check here; things appear to be working as designed within the way VS Code and the LSP handle semantic highlighting.

**Closed by jakebailey** 2021-01-25 21:56 UTC
Labels: waiting for info
