### ISSUE TITLE
Support import convention: Use import statements for packages and modules only, not for individual classes or functions.

### ISSUE THREAD

**Issue by BaconPancakes** [microsoft/pylance-release#4866] opened 2023-09-21 21:01 UTC
There's a style guideline in [Google ](https://google.github.io/styleguide/pyguide.html#22-imports) recommending against direct imports of symbols from a module that would be nice to support in terms of autocompletion capability.

What this would mean is that autocompletion for imports would prefer to import by module as opposed to the class directly, and autocompletions for subclasses, etc. would also use the module.

For example,  typing `@dataclass` would offer an import suggestion that would autocomplete
```python
import dataclasses

@dataclasses.dataclass
```

instead of current behavior
```python
from dataclasses import dataclass

@dataclass
```

For autcompletion in subclasses:

```python

import numbers


class BaseClass(Protocol):
    def my_method(self, number: numbers.Number):
        pass
        
 class SubClass(BaseClass): 
    def my_method
```
where `my_method` should autocomplete to `my_method(self, number: numbers.Number)` instead of currently `my_method(self, number: Number)`

**Comment by StellaHuang95** [comment] 2023-09-28 17:10
Hi @BaconPancakes, thanks for the issue. We have moved this issue to discussion as an enhancement request for comments and upvotes. Please upvote [the idea](https://github.com/microsoft/pylance-release/discussions/4897) if you'd like to see it being supported. 

The second example you listed seems like a bug. Pylance is supposed to add import statement when auto-completing `my_method`. I will look into it.

**Comment by StellaHuang95** [comment] 2023-10-11 18:13
Closing this one as duplicate of https://github.com/microsoft/pylance-release/issues/4948

**Closed by StellaHuang95** 2023-10-11 18:13 UTC
Labels: bug, duplicate
