### ISSUE TITLE
Warnings are issued erroneously

### ISSUE THREAD

**Issue by aprknight** [microsoft/pylance-release#4184] opened 2023-04-02 08:05 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.3.40
-   OS and version: macOS Ventura 13.3
-   Python version 3.11.2
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class TrieNode:
    def __init__(self):
        self._children = [None] * 128
        self._endofword = False
  
class Trie:
    def __init__(self):
        self.root = TrieNode()
  
    def insert(self, key):
        root = self.root
        for index in map(ord, key):
            if not root._children[index]: # warning indicated here
                root._children[index] = TrieNode() # warning indicated here
            root = root._children[index] # warning indicated here
        root._endofword = True # warning indicated here
  
    def search(self, key):
        root = self.root
        for index in map(ord, key):
            if not root._children[index]:
                return False
            root = root._children[index] # warning indicated here
        return root._endofword # warning indicated here
```

<h3> Repro Steps </h3>

1. Open file in VSCode and observe warnings on the lines indicated. 

<h3> Expected behavior </h3>

These warnings are erroneous and should not be highlighted

<h3> Actual behavior </h3>

The warning are of the for 'XXXX is not a known member of "None"'

<img width="379" alt="Screenshot 2023-04-02 at 09 04 40" src="https://user-images.githubusercontent.com/29652671/229340430-9b7c0711-b028-4f38-91c7-73fef0ea7234.png">

**Comment by erictraut** [comment] 2023-04-02 14:48
The current behavior is as designed. Pyright, the type checker upon which pylance is built, is performing type analysis of your code and determining that there are potential type violations (and therefore potential bugs).

If you find that these type checking errors are not useful, you can disable type checking by setting `python.analysis.typeCheckingMode` to "off" in your settings.

If you want this code to type check without errors, you would need to make some small modifications:

```python
class TrieNode:
    def __init__(self):
        self._children: "list[TrieNode | None]" = [None] * 128
        self._endofword = False

class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, key) -> None:
        root = self.root
        for index in map(ord, key):
            if not (x := root._children[index]):
                x = root._children[index] = x
            root = x
        root._endofword = True

    def search(self, key) -> bool:
        root = self.root
        for index in map(ord, key):
            if not (x := root._children[index]):
                return False
            root = x
        return root._endofword
```

If you're interested in the technical reason for why these changes are required, it has to do with the fact that type checkers cannot generally "narrow" the type of an index expression when the subscript is a varaible. In your code, the expression `root._children[index]` is such an expression. Its type is evaluated to be `TrieNode | None`, but it cannot be safely narrowed to just `TrieNode` after the `if not root._children[index]` check because `index` is a variable, and the value referred to by `root._children[index]` is not provably the same as the value being checked. By assigning this expression to a local variable (`x`), the type checker can now narrow the type to `TrieNode`.

Note that other Python type checkers like mypy also have similar limitations and generate similar errors in this case.

**Comment by aprknight** [comment] 2023-04-02 17:43
Thank you very much for the prompt and detailed explanation

**Closed** 2023-04-03 14:50 UTC
Labels: triage-needed, by design
