### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by heydeepakch** [microsoft/pylance-release#1898] opened 2021-10-04 13:50 UTC
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.9.1246542782`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.60.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 197,
		"activateCallTime": 7,
		"activateResolvedTime": 248,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-python.vscode-pylance",
				"_lower": "ms-python.vscode-pylance"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by jakebailey** [comment] 2021-10-04 17:50
Duplicate of #1773.

**Closed by jakebailey** 2021-10-04 17:50 UTC
Labels: triage
