### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ali-harini101** [microsoft/pylance-release#2015] opened 2021-10-30 09:32 UTC
why is it not importing and i am getting

Import "speechRecognition" could not be resolvedPylance

![image](https://user-images.githubusercontent.com/82109937/139527720-99f1606c-a09b-4f8e-a27d-e321992a101a.png)

**Comment by jakebailey** [comment] 2021-11-01 17:47
You haven't provided much information or logs; are these local modules? Are they installed libraries?

If they are installed libraries, can you verify that the interpreter at the bottom left is the one you've installed the libraries into?

**Comment by wovano** [comment] 2021-11-04 08:22
This seems a duplicate of #1971 (even mostly the same Python packages being used and not imported correctly).

**Comment by CodeCrazy-ywt** [comment] 2021-11-04 11:55
Is it after you pip-install the package that you import this package and get this error? Sometimes when I pip-install a package and import it in a `.py` file, I get an error message that says `xxx could not be resolved`. And when I restart VSCode, the error dissappears.

**Comment by jakebailey** [comment] 2021-11-04 17:57
@CodeCrazy-ywt That one's #923; we don't currently watch files outside of the workspace, so if the interpreter isn't within the workspace we don't notice that something changed.

**Closed** 2021-12-02 17:47 UTC
Labels: waiting for user response
