### ISSUE TITLE
GoTo Definition goes into .pyi files and not the .py ones

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#529] opened 2020-10-27 14:45 UTC
## Environment data
Version: 1.51.0-insider (user setup)
Commit: e5c0007ce0e9a3816679cba674d03376c03726e3
Date: 2020-10-27T05:37:14.199Z (8 hrs ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Python extension: v2020.9.114305
Pylance: v2020.10.2

## Expected behaviour

• I can <kbd>Ctrl</kbd>+<kbd>Click</kbd> on a function like `os.chmod` 
• I jump to the function definition in the python environment that I'm currently using and can read the according logic.

## Actual behaviour

• I end up in `C:\Users\eric\.vscode-insiders\extensions\ms-python.vscode-pylance-2020.10.2\dist\typeshed-fallback\stdlib\3\os\__init__.pyi` and read a whole lot of mumbo jumbo of what types go in and out withou a single comment or doc string. (I suppose the stubs are generated, right?)

## Steps to reproduce:

1. have code like
```python
import os, stat
os.chmod(path, stat.S_IREAD)
```
2. <kbd>Ctrl</kbd>+<kbd>Click</kbd> on `chmod`

## more

Hello! I see the stubs are awesome and nice. But on a day to day basis, I'd not look into them at all! Am I missing something? I didn't see an issue like that yet and I have the same behavior on a non-Insider VS Code on another machine.
Can I configure this somehow?
Why is this standard?
Is this WIP? Probably huh? Is there more info?
Where? 

Cheers! Keep doing great things! <3

**Comment by jakebailey** [comment] 2020-10-27 17:35
Duplicate of #65.

Note that we do provide VS Code with both locations if possible (and then it chooses which one to show first).

**Closed by jakebailey** 2020-10-27 17:35 UTC
Labels: triage

**Comment by ewerybody** [comment] 2020-10-27 17:55
Well alright. Thanks @jakebailey . But what about WIP? How is this supposed to work in the future? Is there a plan?
For me this is simply broken atm and it was fine in the past.

**Comment by jakebailey** [comment] 2020-10-27 18:02
You can vote on #65 and follow the issue for updates. This is currently the expected behavior as type stubs are a critical part (sometimes the only part) of defining many library's APIs, but if the behavior of jumping to them isn't desired then that could be changed (which is #65).
