### ISSUE TITLE
Pylance interprets Literal type into str

### ISSUE THREAD

**Issue by jackjyq** [microsoft/pylance-release#6238] opened 2024-08-07 07:36 UTC
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
from typing import Literal

ContactType = Literal["phone_number", "email"]


class Contact:
    def __init__(self, contact_type: ContactType) -> None:
        self.contact_type = contact_type

    def get_contact_type(self) -> ContactType:
        return self.contact_type
```

## Repro Steps

1. 
![image](https://github.com/user-attachments/assets/07507c92-f7f3-4c00-be4e-fb722e39e7f5)

## Expected behavior

No error. 

I expect Pylance to know that self.contact_type is "ContactType" rather than "str"

## Actual behavior

Expression of type "str" is incompatible with return type "ContactType"

## Logs

```
```

**Comment by erictraut** [comment] 2024-08-07 13:58
This is intended behavior, not a bug. You have not specified a type declaration for the instance variable `contact_type`, so it is inferred from values that are assigned to it. In your example, you are assigning a value in the statement `self.contact_type = contact_type`. The right-hand side of this assignment has a literal type, but the default inference rule widens literals to non-literal types. For example, if this statement was `self.contact_type = "x"`, you wouldn't expect the type of `contact_type` to be inferred as `Literal["x"]`; you'd expect it to be `str`. Likewise, when you assign a value of type `Literal["phone_number", "email"]`, it is inferred to be `str`.

If you want the instance variable `contact_type` to be constrained to literal values, you need to provide an explicit type declaration for it:

```python
class Contact:
    def __init__(self, contact_type: ContactType) -> None:
        self.contact_type: ContactType = contact_type
```

**Closed** 2024-08-07 15:31 UTC
Labels: by design
