### ISSUE TITLE
Inherited class variable modification

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#2558] opened 2022-04-11 05:48 UTC
In fact：
![image](https://user-images.githubusercontent.com/100815370/162672709-acd53934-87a8-499f-9431-0ae12e11c8f5.png)

Expect：
![image](https://user-images.githubusercontent.com/100815370/162672746-8418f225-6114-4596-bb48-17f20158468e.png)

**Comment by heejaechang** [comment] 2022-04-22 01:32
we currently only show methods so it can be overriden, but not fields.

**Comment by judej** [comment] 2022-04-26 23:25
Dupe of #2059

**Closed by judej** 2022-04-26 23:25 UTC
Labels: enhancement
