### ISSUE TITLE
Docstring not working in Python

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#4376] opened 2023-05-17 01:10 UTC
Type: Bug

codes:

def function(a: str, b: bool, c: int):
    ''' the function doc string. 
    Here is a bit more.

    args:
        a:  a random string goes here
        b:  lets describe something binary
        c:  we have a whole number

    return:
        gives something back

    '''
![image](https://user-images.githubusercontent.com/100815370/236362014-345a940a-d28f-4d73-845c-4138699fd8cd.png)

When hovering over the function definition in VS Code, the description is formatted correctly.

If the type is wrapped in parentheses after the parameter, the description will appear on the one line

def function(a: str, b: bool, c: int):
    ''' the function doc string. 
    Here is a bit more.

    args:
        a(str):  a random string goes here
        b(bool):  lets describe something binary
        c(int):  we have a whole number

    return:
        gives something back

    '''
![image](https://user-images.githubusercontent.com/100815370/236361958-51bd1870-9214-40b2-a5ae-29450ee7a473.png)

The same issue has been closed in Microsoft/vscode, they believe it is an issue with vscode-Python.

VS Code version: Code 1.78 (https://github.com/microsoft/vscode/commit/5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by rchiodo** [comment] 2023-05-17 16:20
Thanks for the issue.

This should be a dupe of #4317 which was fixed last in last week's prerelease. The fix for that should ship in this week's stable version.

**Closed by rchiodo** 2023-05-17 16:20 UTC
Labels: triage-needed
