### ISSUE TITLE
No overloads for "__getitem__" match the provided arguments

### ISSUE THREAD

**Issue by gandroz** [microsoft/pylance-release#1851] opened 2021-09-21 18:31 UTC
## Environment data

-   Language Server version: python extension v2021.9.1246542782
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8.5, conda 4.10.1

## Expected behaviour

`__getitem__` supports slices with variable names

## Actual behaviour

Pylance reports a problem  when the `__getitem__` method is provided a slice with variables and not integers

## Logs

```
No overloads for "__getitem__" match the provided arguments
  Argument types: (slice)
```

## Code Snippet / Additional information

```python
self.df.iloc[self.current_step - self.history_length:self.current_step]
```

**Comment by erictraut** [comment] 2021-09-21 18:41
We can't diagnose this without additional information. Could you please provide a self-contained minimal sample that exhibits the problem?

**Comment by gandroz** [comment] 2021-09-21 18:44
```python
history_length = 10
step = 100
df = pd.read_csv('./data.csv')
df.iloc[step - history_length:step].values.mean() <---- issue
```

**Comment by jakebailey** [comment] 2021-09-21 20:41
This is technically a dupe of #1607, but I'll leave this one open as that issue is two issues in once (and it's better to track two issues in two issues).

**Comment by rchiodo** [comment] 2022-10-14 17:17
Other issue was closed as fixed.

**Closed by rchiodo** 2022-10-14 17:17 UTC
Labels: bug, typestub
