### ISSUE TITLE
Pylance not recognizing properties and methods from injected dependencies after v2023.12.1 update

### ISSUE THREAD

**Issue by l1h2** [microsoft/pylance-release#5262] opened 2023-12-14 12:52 UTC
## Environment data

-   Language Server version: v2023.12.1 
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6

## Code Snippet

```python
class NewClass:
    def __init__(self, injected_dependency: InjectedClass) -> None:
        self.new_prop = injected_dependency
        self.new_prop.old_prop_or_method # Intellisense not working after v2023.12.1 update
```

## Expected behavior

I expected intelisense to show me the properties and methods available to the original class, as well as carry the correct types, same as it was working up to v2023.11.10.

## Actual behavior

It doesn't recognize any properties and methods for injected dependencies anymore.

**Comment by a690089735** [comment] 2023-12-14 15:06
![image](https://github.com/microsoft/pylance-release/assets/34900141/310676f4-12cb-4927-af67-652070dbee46)
I also have a similar problem, after updating can not find the subclass
Back to 2023.11.10 will be fine.

**Comment by rchiodo** [comment] 2023-12-14 17:14
Thanks for the issue. @l1h2 I'm not sure what you mean by an injected dependency. This works for me:

![image](https://github.com/microsoft/pylance-release/assets/19672699/b9b98e73-ebb9-4dc5-a744-f9afd567edf1)

Can you provide a more complete example?

@a690089735 it looks to me like we're not finding the PySide2 modules. That doesn't seem related to me. That's an import resolution problem. That works fine for me:

![image](https://github.com/microsoft/pylance-release/assets/19672699/ea33edce-0724-4b9a-9708-16744d13bf20)

You might just need to restart VS code.

**Comment by l1h2** [comment] 2023-12-14 17:21
I tried restarting VS code and even my machine a few times, but the only thing that solved the problem was going back to v2023.11.10. Then everything works perfectly.

Here is the actual code I was looking at:

```python
class BuildOrderManager:
    def __init__(self, bot: "Sc2City"):
        self.bot = bot
        self.scv_manager = SCVManager(bot)
        self.structure_manager = StructureManager(bot)
        self.__order_managers = {
            OrderType.STRUCTURE: self.scv_manager.scv_build,
            OrderType.PRODUCTION: self.structure_manager.produce,
            OrderType.ACTION: self.structure_manager.execute_action,
            OrderType.SCV_ACTION: self.scv_manager.execute_action,
        }

    def production_complete(self, unit: Unit) -> None:
        order_id = (
            AbilityId.CALLDOWNMULE_CALLDOWNMULE
            if unit.type_id == UnitTypeId.MULE
            else unit.type_id
        )
        order = next(
            (
                order
                for order in self.bot.queue # This is the line that lost intellisense
                if order.id == order_id and order.status == Status.STARTED
            ),
            None,
        )
        # More code...
```

**Comment by rchiodo** [comment] 2023-12-14 17:22
Do you have a repo I can look at? That has a bunch of dependencies that I can stub out, but I imagine that wouldn't reproduce the problem for me.

**Comment by l1h2** [comment] 2023-12-14 17:22
Forgot to send the original class, but this is the relevant part:

```python
class Sc2City(BotAI):
    def __init__(self, settings: Settings) -> None:
        self.queue: list[Order] = []
```

**Comment by rchiodo** [comment] 2023-12-14 17:23
Okay but I'd still need your `Settings` and `BotAI` class to reproduce.

**Comment by l1h2** [comment] 2023-12-14 17:27
> Do you have a repo I can look at? That has a bunch of dependencies that I can stub out, but I imagine that wouldn't reproduce the problem for me.

https://github.com/savelas81/Sc2City/blob/new-architecture/sc2city/managers/build_order_manager/main.py

**Comment by rchiodo** [comment] 2023-12-14 17:54
Which part of that code isn't working? It seems to work for me:

![image](https://github.com/microsoft/pylance-release/assets/19672699/03d2c86b-029b-4c71-be0c-e14ff8df100e)

In the Sc2City module:
![image](https://github.com/microsoft/pylance-release/assets/19672699/1100e358-757c-4770-9e9f-319245b11d55)


Although maybe this is a linux only problem. I'm trying this on Windows at the moment.

**Comment by rchiodo** [comment] 2023-12-14 18:02
Hmm, I get different results on Linux for the type of `bot`:

Windows:
![image](https://github.com/microsoft/pylance-release/assets/19672699/a625cd66-8949-4d3b-8321-36376e24bf8e)

Linux:
![image](https://github.com/microsoft/pylance-release/assets/19672699/2cacd111-94d1-4dcd-bc05-fd1f5bbcb151)

Windows with 2023.11.10:
![image](https://github.com/microsoft/pylance-release/assets/19672699/8c3bf73b-6d48-4953-8c07-5b4f6955f29c)

So there is some difference. We not resolving the same type for some reason as we used to.

**Comment by l1h2** [comment] 2023-12-14 18:03
Here are some more examples from places I'm seeing this problem

On v2023.12.1:

![image](https://github.com/microsoft/pylance-release/assets/32434817/dbbfe8f2-c482-498a-b9a6-2fd1d9e08723)

![image](https://github.com/microsoft/pylance-release/assets/32434817/b3bc4baf-2e57-4b5e-a44a-26ebbcaf8353)

![image](https://github.com/microsoft/pylance-release/assets/32434817/c15993e0-57f4-435f-82fb-3b64f7b56fa4)

On older versions:

![image](https://github.com/microsoft/pylance-release/assets/32434817/ce82d27a-9603-4e3f-bee0-211d55f49f4f)

![image](https://github.com/microsoft/pylance-release/assets/32434817/c002ceb8-16ab-4cee-a168-a4040c5c4c5d)

![image](https://github.com/microsoft/pylance-release/assets/32434817/75e2210d-e9b1-4b7b-97eb-4565b8601e7e)

**Comment by rchiodo** [comment] 2023-12-14 18:06
Repro steps:
1. git clone https://github.com/savelas81/Sc2City.git
2. git checkout `new-architecture` at this commit id: 0fd2e3aa93a5e6eaa4e693bed6f7c707428e08cf
3. create venv
4. install requirements.txt (I had to remove the git requirement and set platformdirs to not set a version for it to work)
5. Open sc2city\managers\build_order_manager\main.py
6. Hover over the `bot` object passed in. The type is wrong. It should be just `Sc2City` and it's `Module Sc2City.Sc2City`

Doesn't seem to repro on WSL for me.

**Comment by rchiodo** [comment] 2023-12-14 20:34
I believe the root cause of the problem is case sensitivity. On linux, Sc2City is unambiguously resolved to the Sc2City.py:

![image](https://github.com/microsoft/pylance-release/assets/19672699/d84f5d4d-b181-4490-87d3-4c9778fa9382)

On windows, `sc2city` and `Sc2City` are resolving the same way. I'm guessing we removed a realcase check somewhere that's causing the issue.

**Comment by rchiodo** [comment] 2023-12-14 20:44
I can reproduce with this much simpler setup:

- root
   - module
      - __init__.py
      - Module.py
      - test.py

Where `Module.py` has:

```python
class Module():
    def return_int(self):
        return 42
```

And test.py has:
```python
from Module import Module

x = Module()
y = x.return_int()
reveal_type(y)  
```

On Windows, the type of `y` is Any
On Linux, the type of `y` is Literal[42]

**Comment by rchiodo** [comment] 2023-12-14 20:46
Yeah with that simpler test case, with 2023.11.10, Windows produces the correct results.

**Comment by debonte** [comment] 2023-12-15 01:05
This issue has been fixed in prerelease version 2023.12.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312100-14-December-2023-PreRelease)

**Closed by debonte** 2023-12-15 01:05 UTC
Labels: bug, fixed in next version, user responded, regression
