### ISSUE TITLE
"Tuple size mismatch" error does not respect length verification

### ISSUE THREAD

**Issue by TotallyNotChase** [microsoft/pylance-release#695] opened 2020-12-07 15:33 UTC
For a function taking a union of tuples (of different sizes), the destructuring doesn't respect length verification.

## Environment data

-   Language Server version: 2020.12.0
-   OS and version: Windows 10 Version 2004 (Build 19041.630)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

## Expected behaviour

No errors should be raised, after the length verification.

## Actual behaviour

Errors are raised on both branches of the length verification.

```python
def foo(x: Union[Tuple[str, int], Tuple[int, float, str]]):
    if len(x) == 3:
        a, b, s = x
    else:
        s, a = x
```
The above raises "Tuple size mismatch" on both of the destructure lines, albeit - the first claims to have received 2 elements (and expected 3) and the second claims to have received 3 elements (and expected 2). The wording made me think as if the order is switched, but changing `len(x) == 3` to `len(x) == 2` makes no difference.

**Comment by erictraut** [comment] 2020-12-07 15:40
Pylance doesn't contain special-case type narrowing logic for expressions of the form "len(x) == y". This would apply only to unions of tuples whose lengths are known — the very specific case that you used in your example. Other type checkers like mypy do not support this form of narrowing either. This is not a common pattern, so we're unlikely to add the special-case logic specifically for this unless we hear from enough other users.

If you are interested in the forms of conditional type narrowing (also referred to as "type guards") that Pylance supports, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards).

**Comment by TotallyNotChase** [comment] 2020-12-07 16:05
@erictraut hmm, I see. I'd assume using a `type(x) is T` type guard would be ideal for determining the correct tuple type from a union?

Also, when I do-
```py
def foo(x: Union[Tuple[str, int], Tuple[int, float, str]]):
    if type(x) is Tuple[int, float, str]:
        a, b, s = x
    else:
        s, a = x
```
The `else` block still has the same error. I assume I've to use the type guard in an `elif` branch. But would deducing the remaining type through elimination from the `Union` be unfeasible?

**Comment by erictraut** [comment] 2020-12-07 16:16
The `type(x) is T` expression wouldn't work because `type(x)` evaluates to `tuple` for both subtypes in your union. There's no way to differentiate between the two at runtime using `type(x)`.

A special-purpose type guard would properly narrow the type for both the `if` and the `else` clause. But without this logic, the type of x is not narrowed in either the `if` or the `else` clause.

There are many candidates for type guards that could be added. Each of them needs to look for specific expression forms and apply certain logic. As you can see, pylance already supports several dozen expression forms — to my knowledge, more than any other Python type checker. I'm sure we will add more over time, but only for patterns that are sufficiently common. We can leave this issue open and see if it gets more upvotes.

**Comment by bfs15** [comment] 2020-12-18 18:42
Is this related?
I have the following error, which just by reading it shouldn't be an error/mismatch at all since it says it's the same size.
"Tuple size mismatch; expected 2 but received 2"
Minimal code to reproduce, you can try casting it, but it doesn't make a difference.

```python
from typing import List, Tuple, Union, cast
def getTuple(li: Union[Tuple[int, int], Tuple[int, int, int]]):
    tu: Tuple[int, int]
    if len(li) == 3:
        # li = cast(Tuple[int, int, int], li)
        tu = li[:2]
        return tu
    return None
```

![pylance-tuple_size_mismatch](https://user-images.githubusercontent.com/21046091/102649140-6f41d180-4147-11eb-94c2-8f18b6f0fdf1.png)

**Comment by erictraut** [comment] 2020-12-18 18:48
The error message is definitely confusing in this case. I can improve that. But it is correct for a type checker to emit an error here. That's because the expression `li[:2]` returns the type `Tuple[int, ...]` of unknown length, and you're assigning it to a tuple with a specific known length.

**Comment by erictraut** [comment] 2020-12-18 18:54
I've updated the text in the error message so it's accurate and less confusing.

![Screen Shot 2020-12-18 at 10 54 07 AM](https://user-images.githubusercontent.com/7040122/102650197-5ae9de80-411f-11eb-8eda-e62da3e89cba.png)

**Comment by bfs15** [comment] 2020-12-18 19:01
I see, thanks!
Though if you know type of of `li` has length 3, a slice of [:2] has a known length doesn't it? In the code I found this I even had a length check beforehand like this:
```python
def getTuple(li: Tuple[int, int, int]):
    tu: Tuple[int, int] = (0,0)
    if len(li) == 3:
        tu = li[:2]
    return tu
# Using cast
def getTupleCast(li: Tuple[int, int, int]):
    tu: Tuple[int, int]
    tu =  cast(Tuple[int, int], li[:2])
    return tu
```
So the way of doing this without errors is with cast() like in the second function?

**Comment by erictraut** [comment] 2020-12-18 20:17
A type checker doesn't have intrinsic knowledge about how these classes work. It needs to apply a set of rules based on the information it's provided. In the case of a tuple, the type of the expression `li[:2]` is dictated by the following method declaration in the `builtins.pyi` type stub:

```python
    def __getitem__(self, x: slice) -> Tuple[_T_co, ...]: ...
```

Yeah, there's not an elegant way to handle this case other than to avoid writing methods that accept tuples of different sizes, which is arguably not a good practice to begin with. For example, would it make sense to switch `Union[Tuple[int, int], Tuple[int, int, int]]` to `Tuple[int, int, Optional[int]]`?

**Comment by bfs15** [comment] 2020-12-18 20:58
Ah, I see.
Yes makes sense! Thanks again

**Comment by bschnurr** [comment] 2021-09-23 19:08
Closing for now

**Closed by bschnurr** 2021-09-23 19:08 UTC
Labels: enhancement
