### ISSUE TITLE
Some information is missing while typing.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/pylance-release#1741] opened 2021-08-30 06:33 UTC
## Environment data

Version: 1.60.0-insider (user setup)
Commit: 8dbad73de575e47e127c8b1a4324f2b61257fbdc
Date: 2021-08-27T21:25:29.781Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17134

Build of python-insider: 2021.9.1176299738-dev 
Build of jupyter-insider: 2021.8.2031173646 
Build of Pylance: 2021.8.3

## Expected behaviour

It has auto pop-up docstring while typing.

![image](https://user-images.githubusercontent.com/82852072/131293482-0354c092-8ab8-4962-9a69-8a13f1125590.png)

![image](https://user-images.githubusercontent.com/82852072/131293493-c3a9dc51-9ee3-43c1-9a55-0fdb43e5f9d8.png)

## Actual behaviour

The information is missing.

![image](https://user-images.githubusercontent.com/82852072/131293560-f6decef6-5d1a-4261-8c98-a143473dea6c.png)

![image](https://user-images.githubusercontent.com/82852072/131293635-ba30d477-cf94-4505-ae53-4abdb48cbc34.png)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Python interpreter path: C:\ProgramData\Anaconda3\python.exe
Starting Pylance language server.
Error 2021-08-30 06:16:17: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\vting\Downloads\Test6\.vscode\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\vting\Downloads\Test6\.vscode\settings.json')
	at _handleError (c:\Users\vting\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:160087)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2021.9.1176299738-dev\out\client\extension.js:9:315784)
	at async p.doesFileNeedToBeFixed (c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2021.9.1176299738-dev\out\client\extension.js:59:823850)
	at async c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2021.9.1176299738-dev\out\client\extension.js:59:822977
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2021.9.1176299738-dev\out\client\extension.js:59:822923)
	at async p.updateTestSettings (c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2021.9.1176299738-dev\out\client\extension.js:59:822550)] {
  code: 'FileNotFound'
}
Python interpreter path: C:\Python39-64\python.exe

```

</p>
</details>

**Comment by jakebailey** [comment] 2021-08-30 16:45
Duplicate of #1350.

**Closed by jakebailey** 2021-08-30 16:45 UTC
Labels: triage
