### ISSUE TITLE
Pylance "argument" is not accessed

### ISSUE THREAD

**Issue by PASUNX** [microsoft/pylance-release#1120] opened 2021-04-04 07:25 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.3.4
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet / Additional information </h3>

```python
class GreeterBase:

    @staticmethod
    def greeting(name: str) -> str: ...
                # "name" is not accessed

class HelloGreeter(GreeterBase):

    @staticmethod
    def greeting(name: str) -> str:
        return "Hello, %s!" % name
```

**Comment by erictraut** [comment] 2021-04-04 15:22
What behavior do you expect to see here? What you're describing is intended behavior.

The symbol `name` in this example is not accessed. Pylance displays unaccessed symbols as "grayed out" as a subtle visual hint to the programmer. This isn't necessarily the sign of a bug, but it can sometimes indicate unintended behaviors in the code.

**Comment by PASUNX** [comment] 2021-04-04 15:29
I think it shouldn't show "name" is not accessed because that is only interface (with only "..." in function)

**Comment by erictraut** [comment] 2021-04-04 15:45
The behavior is consistent with other language servers. Pylance never emits an error (even in strict mode) for this condition. It simply provides a subtle visual clue.

**Comment by PASUNX** [comment] 2021-04-04 15:52
I mean it shouldn't grayed out
![image](https://user-images.githubusercontent.com/76944694/113514381-5a733780-9598-11eb-949a-2cb1f9abb988.png)
so I must define interface in .pyi only ?
![image](https://user-images.githubusercontent.com/76944694/113514387-64953600-9598-11eb-893e-06a9ba4c5047.png)

**Comment by erictraut** [comment] 2021-04-04 16:00
OK, thanks for the clarification.

As I said, the current behavior is intended and is consistent with other language servers, but that doesn't necessarily mean it's preferred by everyone. We can leave this issue open and see what feedback we get from others.

There is already an issue open on a similar topic: https://github.com/microsoft/pylance-release/issues/194

**Comment by PASUNX** [comment] 2021-04-04 16:04
in this case is only interface no reason to grayed out unused variable

**Comment by erictraut** [comment] 2021-04-04 16:13
One could make the same argument for parameters within abstract methods, "self" parameters, parameters within some dunder methods, etc. The current rule is straightforward and consistent and always provides the visual clue when a symbol is not accessed in a code file. Programmers can use this visual clue to determine whether it's something they want to be concerned about or not. If we were to apply some complicated set of heuristics for when to apply the "unaccessed symbol" visual clue, it would require a much more complicated mental model to understand why it's present in some cases and not in others. At least that's the thinking — and how I make use of the "grayed out" visual clue in my day-to-day programming.

**Comment by jakebailey** [comment] 2021-04-05 17:58
This is a duplicate of #194; please vote/comment on this issue if you think this behavior should change.

Personally, I'm still in favor of making this more complicated. Other languages have things like an implicit "this" they don't have to specify in the parameter list, so no graying t here. TS's semantic tokenization does not gray out parameters in bodyless abstract methods.

**Closed by jakebailey** 2021-04-05 17:58 UTC
Labels: triage
