### ISSUE TITLE
Keywords not rendering properly

### ISSUE THREAD

**Issue by MystWraith** [microsoft/pylance-release#5033] opened 2023-10-27 20:36 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

`in` and `not` are always rendered as keywords.

They are not rendered as keywords consistently. Also, the hover hint also lables it as a function.

## Steps to reproduce:

I personally use dark-modern theme.

In a standard python file, type the following and observe what happens:

1. `for key, item in dictionary.items():`
   `in` is colored like a function
2. `if item not in dictionary.keys():`
   `not` is colored as a function
3. `if item not in list`
   this renders properly.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): MicrosoftStore
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.19.13001012
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7940HS w/ Radeon 780M Graphics      (16 x 3993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.22GB (44.74GB free)|
|Process Argv|--crash-reporter-id ad1c9e51-33c8-4d07-953c-7ba4a7371075|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
pythonmpsinfo:30842941
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859726
pythoncet00cf:30874137
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by rchiodo** [comment] 2023-10-27 22:24
Thanks for the issue. This is a dupe of https://github.com/microsoft/pylance-release/issues/4909

The color changes are actually on purpose. They indicate you have an overload for one of the functions. That's why hovering over them show a function.

**Closed by rchiodo** 2023-10-27 22:24 UTC
Labels: triage-needed, needs repro
