### ISSUE TITLE
Import "X" could not be resolvedPylancereportMissingImports

### ISSUE THREAD

**Issue by joshua40302-intel** [microsoft/pylance-release#4369] opened 2023-05-15 19:16 UTC
Type: <b>Bug</b>

After updating to the latest VS code and pylance, my import doesn't work for the local module under the same project folder. It used to work well, but now it cannot detect the module.

Extension version: 2023.5.20
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by joshua40302-intel** [comment] 2023-05-15 19:20
I've tried re-install Pylance, VS code, or added extra path for root directory, but all seems not work. Anything I missed here?

**Comment by rchiodo** [comment] 2023-05-15 21:29
This could be a dupe of #4357. Are your net drives UNC paths or did you mount them?

**Comment by joshua40302-intel** [comment] 2023-05-15 21:32
Yeah I am using a UNC path

**Closed** 2023-05-15 21:42 UTC
Labels: user responded
