### ISSUE TITLE
Installed packaged not being 'resolved' - Brownie and PyTest

### ISSUE THREAD

**Issue by liam-ot** [microsoft/pylance-release#1020] opened 2021-03-07 14:46 UTC
```
import brownie
from brownie import accounts, Farm
import pytest
```

pylance doesn't recognize these libraries though the warning is ignored and compiles correctly as these are all up to date on my machine, i understand i can change the config to not show me the warning, that is not the point, just wanted to point out that pylance seems to be having some issues with the `brownie` and `pytest` packages

**Comment by erictraut** [comment] 2021-03-07 16:20
Please fill out the full template for pylance issue reporting. It will tell you what logs we need to help you diagnose your configuration issue.

**Comment by liam-ot** [comment] 2021-03-07 16:33
if you could kindly point me in that direction i will do so

**Comment by judej** [comment] 2021-03-08 18:38
Here is the instructions for filing the issue:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

thanks

**Comment by jakebailey** [comment] 2021-04-09 19:45
Without the requested info, we can't really help here without being able to reproduce this. It's been a month since we asked, so I'm going to close this, but if you can provide the requested info we can reopen. Thanks.

**Closed by jakebailey** 2021-04-09 19:45 UTC
Labels: waiting for info

**Comment by blockdjango** [comment] 2021-09-24 15:34
Terrible support. You can tell they're more concerned about closing the issue than helping with the issue. This is a common problem which most people experiencing it won't be able to provide that lowlevel information you're requesting. We are just using python and one library is not being recognized and ruining the entire auto complete experience. Just tell me how to fix this and why tf Pylance can't see a library I installed. You're the expert on this, not us asking the question.

**Comment by blockdjango** [comment] 2021-09-24 15:46
I installed brownie with pipx if that helps. I don't know what is going on. Help me understand what needs to be done. everything compiles fine, but it's irritating asl having to having no autocomplete for the entire brownie library. wtf help.

**Comment by jakebailey** [comment] 2021-09-24 17:45
This issue was closed because we waited for a month to get logs back to offer suggestions, but none were provided.

Would you mind opening a new issue with your setup and logs?

As far as I'm aware, `pipx` is a tool designed to manage executable Python packages, not to install libraries to import, so I'm not sure how one would import from it in a Python script. Almost all of the cases that look like this issue (imports not being resolved) are due to the wrong interpreter being selected at the bottom left.

**Comment by GZRdev** [comment] 2021-11-18 08:07
Having similar issues as CarsonLMH. I have a red squiggly line under brownie as well- no fix has worked yet for me.

os: linux mint
brownie version:  1.17.1
Python version : 3.8.10
ganache-cli version: 6.12.2
using visual studio code with python, pylance, and solidity extensions.

"Import "brownie" could not be resolved"

I'm pulling my hair out. No joke been stuck on this for probably around 10 hours. Hoping it's something simple and I'm just being dumb.

Here is the tutorial video I've been following that I'm getting stuck on around 43:50.
https://youtu.be/eYKSUCKif-g?t=2600

**Comment by anwar11235** [comment] 2021-11-30 01:13
> I'm fairly certain that `pipx` is only for managing global installs of executable modules; roughly, `pipx` is to `pip` what `npx` is to `npm`. https://pypa.github.io/pipx/#how-is-it-different-from-pip
> 
> > pip is a general-purpose package installer for both libraries and apps with no environment isolation. pipx is made specifically for application installation, as it adds isolation yet still makes the apps available in your shell: pipx creates an isolated environment for each application and its associated packages.
> 
> If you're working with `brownie` as a library, you'd want to install it into a virtual environment so you can import it, which will also get you the `brownie` into `$PATH` (runnable at a terminal) when the environment is activated like other executables installed with `pip`.

I was running in to the same issue on VS Code (I had installed brownie using pipx as well). I fixed the issue by doing `pip install eth-brownie`. Code is formatted fine and all "problems" are resolved now.

**Comment by chang432** [comment] 2021-12-05 22:54
This worked for me:
https://ethereum.stackexchange.com/questions/114841/failed-brownie-import-when-running-scripts/114857

**Comment by navigatrum** [comment] 2021-12-09 10:23
> This fixed the import error for me: https://ethereum.stackexchange.com/questions/114841/failed-brownie-import-when-running-scripts/114857

I installed `brownie` via `pipx` (on Ubuntu18), and solved the issue by adding `~/.local/pipx/venvs/eth-brownie/bin/python` to the interpreter path.

**Comment by mludvig** [comment] 2021-12-10 11:18
I had the same problem, having `brownie` installed in a _virtualenv_. The issue was that _Code_ didn't use the virtualenv's Python interpreter and instead used the system one.

Fixed by selecting the right python interpreter from the virtual environment: `Ctrl+Shift+P` (or `Ctrl+Cmd+P` on Mac) -> **Python: select Interpreter** -> Choose the python in your virtenv, in my case it was `~/.virtualenvs/brownie/bin/python`.

**Comment by theRealWeatherwax** [comment] 2021-12-27 04:53
I had this problem to. Fixed by looking at what interpreter brownie was using:

    cat `which brownie` |head -n1
    
And then using that as interpreter path in VSCode. Ctrl+Cmd+P on Mac) -> Python: select Interpreter -> Add new interpreter

**Comment by Dcamy** [comment] 2022-01-09 05:53
> .virtualenvs/brownie/bin/python

I keep finding this solution all over the web however I can only follow that path upto eth-brownie/ there is no "bin" folder :(

**Comment by astepanii** [comment] 2022-01-29 14:19
Installed `brownie` with `pipx` and faced the same issue.

What helped me:
- find where `brownie` sources are located; in my case: `/home/user/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages`
- open vs code settings, find `Python -> Analysis: Extra Paths` under `Extensions -> Pylance` and add the path from above
- note that using `~` shortcut instead of `/home/user` didn't seem to work

**Comment by avigdorkahalani** [comment] 2023-04-21 07:38
> Installed `brownie` with `pipx` and faced the same issue.
> 
> What helped me:
> 
> * find where `brownie` sources are located; in my case: `/home/user/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages`
> * open vs code settings, find `Python -> Analysis: Extra Paths` under `Extensions -> Pylance` and add the path from above
> * note that using `~` shortcut instead of `/home/user` didn't seem to work

Thank you for this.

Adding the site-packages path to the vscode setting you mentioned solved that irritating issue for me!
