### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by rem-163** [microsoft/pylance-release#5620] opened 2024-03-07 22:25 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: syntax highlighting is proper for functions/classes/modules
Actual: syntax highlighting becomes incorrect upon editting a script.

## Steps to reproduce:

Running:
Microsoft Windows [Version 10.0.22631.3155]
WSL2 2.1.4.0
Linux Kernel 5.15.146.1
Ubuntu 22.04
Visual Studio Code 1.87.0
Remote-WSL Extension 0.86.0 or Remote-SSH Extension 0.109.0
Python Extension 2024.2.1
Jupyter Extension 2024.2.0

1. Generate Python script in Jupyter in VS Code running either Remote-WSL or Remote-SSH (the error occurs in both)
2. If syntax highlighting is correct, re-load session and begin editing code.
3. Syntax highlighting should become incorrect.
4. Re-load script and highlighting should be correct but again become incorrect upon editing.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2024.2.1
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 4.18.0-294.el8.x86_64
Remote OS version: Linux x64 3.10.0-1160.81.1.el7.x86_64
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (31.07GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/remdw/Research --remote=wsl+Ubuntu --crash-reporter-id e8b86b92-5ba7-4c7a-9fe7-f5a8d1e3a5a5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: braid2.cnsi.ucsb.edu|
|OS|Linux x64 4.18.0-294.el8.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz (96 x 1201)|
|Memory (System)|187.31GB (79.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pod.cnsi.ucsb.edu|
|OS|Linux x64 3.10.0-1160.81.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (40 x 1000)|
|Memory (System)|187.60GB (131.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|Memory (System)|31.19GB (29.19GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by rchiodo** [comment] 2024-03-11 17:11
Thanks for the issue. This should be a dupe of #5543

Which was a bug in VS code that has since been fixed. You can get the fix in the VS code insider's build.

**Closed by rchiodo** 2024-03-11 17:11 UTC
Labels: needs repro
