### ISSUE TITLE
Renaming a variable results in "Cancelled" message and no actual renaming

### ISSUE THREAD

**Issue by douglasrizzo** [microsoft/pylance-release#258] opened 2020-08-18 21:57 UTC
## Environment data

-   Language Server version: 2020.8.1
-   OS and version: Manjaro Linux 20.1 kernel 5.7.14
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3 in Anaconda
## Expected behaviour

When using the "Rename" functionality in a variable in Python code (e.g. through the F2 shortcut), I expect the name of the variable to change after filling the provided textbox and pressing Enter.

## Actual behaviour

VS Code takes some time to process the request then shows a notification with the message "Cancelled" and the variable is not renamed.

My issue if very similar to https://github.com/microsoft/python-language-server/issues/1190 in the original Python Language Server. Even the behavior in the GIF is similar.

## Logs

When I execute the failed rename attempt, nothing new shows up in the Python output panel.

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Microsoft Python language server.
> conda env list
Python interpreter path: ~/.anaconda3/bin/python
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/Code/agent/agent/training/run.py
cwd: ~/Code/agent
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers ~/Code/agent/agent/training/run.py
cwd: ~/Code/agent
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py pylama --format=parsable ~/Code/agent/agent/training/run.py
cwd: ~/Code/agent
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py pylama --format=parsable ~/Code/agent/agent/training/run.py
cwd: ~/Code/agent
> conda env list
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/.anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2020.8.101144/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
##########Linting Output - pylama##########
agent/training/run.py:61:1: [W] W0612 local variable 'n_agent_features' is assigned to but never used [pyflakes]
agent/training/run.py:62:1: [W] W0612 local variable 'n_enemy_features' is assigned to but never used [pyflakes]
agent/training/run.py:428:20: [C] E125 continuation line with same indent as next logical line [pycodestyle]
agent/training/run.py:645:1: [C] C901 'If 645' is too complex (12) [mccabe]
##########Linting Output - mypy##########
agent/training/run.py:74:28: error: Incompatible types in assignment (expression has type "Tensor", variable has type "List[Any]")
agent/training/run.py:77:28: error: Incompatible types in assignment (expression has type "Tensor", variable has type "List[Any]")
agent/training/run.py:80:28: error: Incompatible types in assignment (expression has type "Tensor", variable has type "List[Any]")
agent/training/run.py:82:25: error: "List[Any]" has no attribute "int"
agent/training/run.py:83:21: error: "List[Any]" has no attribute "unique"
agent/training/run.py:95:36: error: "List[Any]" has no attribute "tolist"
agent/training/run.py:534:20: error: Too few arguments for "make_agent"
Found 7 errors in 1 file (checked 1 source file)
```

**Comment by bschnurr** [comment] 2020-08-19 23:15
Thank you for the issue report.

In your settings.json file can you turn on tracing?
` "python.analysis.logLevel": "Trace",`

then please upload the text in "Python Language Server" Output window. 

Thank you.

**Comment by jakebailey** [comment] 2020-10-08 01:02
It's been over a month since we asked for info and added the label; I'm going to close this. If it still reproduces with the latest version and you can provide the trace logs, we can reopen this.

**Closed by jakebailey** 2020-10-08 01:02 UTC
Labels: waiting for info
