### ISSUE TITLE
Support contextlib.suppress

### ISSUE THREAD

**Issue by Yajo** [microsoft/pylance-release#598] opened 2020-11-11 11:37 UTC
Issue Type: <b>Bug</b>

This syntax highlighting is wrong because the code grayed out can actually be executed:

![imagen](https://user-images.githubusercontent.com/973709/98807210-999ec180-241a-11eb-8775-794f1b0b7e0b.png)

Extension version: 2020.10.332292344
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.8.18-300.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.48GB (1.23GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id abab7a42-9f41-495c-b7c0-99224e53627a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by jakebailey** [comment] 2020-11-11 19:01
Duplicate of #494; please vote on that issue.

**Closed by jakebailey** 2020-11-11 19:01 UTC
Labels: triage
