### ISSUE TITLE
"Request textDocument/completion failed" was the first thing I saw when starting to type in vscode.dev 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/pylance-release#2876] opened 2022-05-31 17:48 UTC
Testing https://github.com/microsoft/vscode-jupyter/issues/10170

Approx repro:

1. Open https://insiders.vscode.dev/
2. Install Python/Jupyter extensions
3. Connect to a Jupyter server (probably doesn't matter)
4. Open a folder
5. Create test.py in folder root
6. Type something

<img width="955" alt="Screen Shot 2022-05-31 at 10 43 51 am" src="https://user-images.githubusercontent.com/2193314/171250584-29cfb9a6-1d0b-4876-8976-0871f6322bfd.png">

This might be related to the save dialog, if so this should be a silent failure imo.

Python language server log:

```
[Info  - 10:39:03] Pylance language server 2022.5.3 (pyright 73c82fab) starting
[Info  - 10:39:03] Server root directory: /
Notebook support: Legacy
[Info  - 10:39:04] No configuration file found.
[Info  - 10:39:04] No pyproject.toml file found.
[Warn  - 10:39:04] stubPath /vscode/typings is not a valid directory.
[Info  - 10:39:04] Searching for source files
[Error - 10:39:04] File or directory "/vscode" does not exist.
[Info  - 10:39:04] No source files found.
[Error - 10:43:25] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: request cancelled
  Code: -32603 
[Error - 10:43:26] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: request cancelled
  Code: -32603 
```

**Comment by Tyriar** [comment] 2022-05-31 22:48
Saw this one when reloading vscode.dev with a notebook open:
<img width="1096" alt="Screen Shot 2022-05-31 at 3 46 02 pm" src="https://user-images.githubusercontent.com/2193314/171296416-f5d28a36-0486-405e-8898-805d61a50df4.png">

```
[Info  - 15:45:40] No pyproject.toml file found.
[Warn  - 15:45:40] stubPath typings is not a valid directory.
[Info  - 15:45:41] Searching for source files
[Info  - 15:45:41] No source files found.
[Info  - 15:45:41] No pyproject.toml file found.
[Warn  - 15:45:41] stubPath typings is not a valid directory.
[Info  - 15:45:41] Searching for source files
[Info  - 15:45:41] No source files found.
[Info  - 15:45:43] [FG] Long operation: parsing: [virtual] /typeshed-fallback/stdlib/builtins.pyi (2543ms)
[Error - 15:45:46] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: request cancelled
  Code: -32603 
[Error - 15:45:46] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: request cancelled
  Code: -32603 
```

**Comment by Tyriar** [comment] 2022-06-01 14:40
While playing around with notebooks/variable viewer:
<img width="474" alt="Screen Shot 2022-06-01 at 7 39 41 am" src="https://user-images.githubusercontent.com/2193314/171431329-cd636d4d-e630-46dc-ba12-84eee553738f.png">

**Comment by heejaechang** [comment] 2022-06-02 18:05
dupe of https://github.com/microsoft/pylance-release/issues/2743

**Closed by heejaechang** 2022-06-02 18:05 UTC
Labels: needs investigation
