### ISSUE TITLE
No parameter hints for keras/Tensorflow

### ISSUE THREAD

**Issue by moritzwilksch** [microsoft/pylance-release#99] opened 2020-07-13 08:51 UTC
## Environment data
-   Language Server version: 2020.7.1
-   OS and version: MacOS 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.7 (Anaconda)

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

## Expected behaviour

Parameter hints for the function signature are shown like so: 
![image](https://user-images.githubusercontent.com/58488209/87284056-4103fa00-c4f6-11ea-9ebe-d9d634629f5e.png)

(This is using the standard MS Python Language Server)

## Actual behaviour

![image](https://user-images.githubusercontent.com/58488209/87283679-d5ba2800-c4f5-11ea-9d1f-b22ee109fa6e.png)

- only parameters shown are *args and **kwargs

## Code Snippet / Additional information

```python
import keras
model = keras.Sequential(
    keras.layers.Dense()
)
```

**Comment by CatNofishing** [comment] 2020-07-13 09:05
Similiar issue in pytorch module!!!  Type hints does not work for some third-party module.

**Comment by bschnurr** [comment] 2020-07-15 23:24
Thank you for entering an issue.

What version of tensorflow are you using?

with tensorflow 1.13.1

and following this guide (https://keras.io/guides/sequential_model/), changing the imports to 

`import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers`


i'm getting more info for Dense()
![image](https://user-images.githubusercontent.com/1946977/87609426-5d9b6000-c6b7-11ea-819a-de087f0f0e47.png)

**Comment by moritzwilksch** [comment] 2020-07-17 09:30
Hey, 
i'm using TF 2.0.0 and also a separate installation of Keras 2.3.1.
Changing the imports like you suggested didn't work. I remember that I had autocomplete Issues when TF 2.0 was first released (back then with the MS Python Language Server), but using the direct installation of Keras had fixed it. Now with pylance it stopped working again.

**Comment by bschnurr** [comment] 2020-07-21 17:15
I too am seeing the issue with just TF 2.0.0 but the issue goes away for me after installing Keras 2.4.3.

I'm going to try again with just a single python file.

**Comment by bschnurr** [comment] 2020-07-21 17:21
Yes just a single file with a virtual environment in a peer folder is working for me on windows using pip install instead of anaconda.  Maybe there is difference in the mac version of keras
```
import keras
model = keras.Sequential(
    keras.layers.Dense()
)
```
[requirements.txt](https://github.com/microsoft/pylance-release/files/4955109/requirements.txt)

**Comment by zhen8838** [comment] 2020-07-22 12:46
if you use tf2.x you can specify `tensorflow_core` dir as `extraPaths` like:
```sh
ln -s ~/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
```
in setting.json:
```json
    "python.autoComplete.extraPaths": [
        "~/.local/virtual-site-packages"
    ]
or
    "python.analysis.extraPaths": [
        "~/.local/virtual-site-packages"
    ],
```

**Comment by zhen8838** [comment] 2020-07-22 13:12
I didn't install `Pylance` extension but use the `Pylance language server`:
```sh
    // "python.languageServer": "Microsoft",
    "python.languageServer": "Pylance",
```
It get better performence than `Microsoft`.

![Screenshot from 2020-07-22 20-52-33](https://user-images.githubusercontent.com/26156999/88180047-58ae5180-cc5f-11ea-82db-bf145126cf6a.png)


but when install Pylance, **it can't autocomplete  somethings**:

![Screenshot from 2020-07-22 21-10-34](https://user-images.githubusercontent.com/26156999/88180373-dd996b00-cc5f-11ea-9863-1afd8ea331e9.png)

**Comment by moritzwilksch** [comment] 2020-07-22 13:39
When I (1) disable the pylance extension and (2) keep the pylance language server in settings.json I get the following error:

`Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.`

the output console says:

`Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at u._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:836)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3944:717
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Error while activating Python: {}`

I suspect VSC falls back to jedi or MS Python Language server in this case, and then I also get great parameter hints again (similar to your screen shots). Is there any way to confirm that its actually pylance generating these suggestions? And if this is the case, why do I get the afore mentioned error?

**Comment by bschnurr** [comment] 2020-07-22 16:27
@moritzwilksch In step one you say you disabled the Pylance extension, so that is why you are getting the error. To confirm Pylance is running check the output- "Python Langauage Server" window for something like this.

`[Info  - 9:26:23 AM] Pylance language server 2020.7.3 (pyright 5004efe5) starting `

**Comment by zhen8838** [comment] 2020-07-23 02:02
@moritzwilksch, I think you are right. Now I found Its actually using Jedi. 

So now still need to specify `tensorflow_core` dir as `extraPaths` and install `Pylance`. But its automatic completion is not very good in function parameters.

**Comment by moritzwilksch** [comment] 2020-07-30 06:41
Tried it with the extra path to /Users/moritz/opt/miniconda3/lib/python3.7/site-packages/tensorflow_core, but as you said, still doesn't work well.

@bschnurr just checked, when pylance is running the parameter hints are as bad as described above, when jedi is running (like @zhen8838) they are looking good again

**Comment by bschnurr** [comment] 2020-08-17 16:55
You shouldn't need to set "extra paths".

I believe the issue is with decorators that anaconda version of keras is using. 
![image](https://user-images.githubusercontent.com/1946977/90422325-92605580-e06f-11ea-944d-a0d91f97e874.png)

I'll investigate further, but in the mean time I recommend using the requirements file i posted above, or create your own environment using pip install instead of conda

**Comment by moritzwilksch** [comment] 2020-09-05 16:13
Ok. I also noticed that if you use the keras import recommended by TensorFlow:
```python
from tensorflow import keras
```
pylance does not even recognized the contained modules:
![image](https://user-images.githubusercontent.com/58488209/92309153-63207280-efa3-11ea-9f9b-68158cc43ccb.png)

Is that one of the needs-stub issues? Or can this be fixed?

**Comment by shifengzhao** [comment] 2020-10-23 02:55
For tensorflow 2.x, there contains no module in "env path/tensorflow". I  find the modules of tensorflow is in "env path/tensorflow_core", and  tensorflow/__init__.py sets modules in sys from tensorflow_core:
![image](https://user-images.githubusercontent.com/39286101/96950762-a025d180-151d-11eb-9e27-faad7e8749d2.png)

So Pylance can not handle import rightly.
If the above reason is right, I hope Pylance can solve it.

**Comment by saeedizadi** [comment] 2021-02-20 00:23
is there update on this issue?

**Comment by bschnurr** [comment] 2021-03-23 17:19
> Ok. I also noticed that if you use the keras import recommended by TensorFlow:
> 
> ```python
> from tensorflow import keras
> ```
> 
> pylance does not even recognized the contained modules:
> ![image](https://user-images.githubusercontent.com/58488209/92309153-63207280-efa3-11ea-9f9b-68158cc43ccb.png)
> 
> Is that one of the needs-stub issues? Or can this be fixed?

I see layers now showing up. Tested with `pip install tf-nightly` on python 3.9 windows

**Comment by bschnurr** [comment] 2021-03-23 17:26
with `pip install tf-nightly` on python 3.9 windows 

signatureHelp
![image](https://user-images.githubusercontent.com/1946977/112190308-1bb9a680-8bc2-11eb-8a8e-413e16accd8f.png)


onHover
![image](https://user-images.githubusercontent.com/1946977/112190292-16f4f280-8bc2-11eb-98cc-b8e8680c6dbd.png)

**Comment by sikanrong** [comment] 2021-06-07 12:39
Just wanted to chime in on this issue and say that I found a way to fix it for TF 1.x. 

The problem is the non-standard structure of the tensorflow packages, such that there is never a folder structure such that the path `tensorflow/keras` exists. Generally the strategy here is to use POSIX symbolic links ("symlinks") to make the folder structure we want, and then let pylance know about it via the `python.analysis.extraPaths` setting. Specifically, I put it in the `settings` block of my workspace config JSON. 

So on my machine, I've got my tensorflow package installed in `/home/windfish/.pyenv/versions/3.7.9/lib/python3.7/site-packages/tensorflow_core`. 

So first think I make a folder `.virtual_site_packages` in my home directory. Then I make a symlink from the tensorflow python modules directory to the new directory in my home folder, but rename the link to "tensorflow". This creates the much-needed path "tensorflow/keras" so that pylance can find tensorflow internal packages the same way that we specify them with module syntax within python itself.

First we make the symlink as described above:

`ln -s ~/.pyenv/versions/3.7.9/lib/python3.7/site-packages/tensorflow_core/python ~/.virtual_site_packages/tensorflow`

Note the added `/python` at the end of the tensorflow core directory, in tensorflow 1.x, this is where the python modules are located - I think this may have changed in 2.x, according to comments above.

Finally just add the desired configuration to pylance in your workspace settings (in the `settings` block).

```
"python.analysis.extraPaths": [ "/home/windfish/.virtual_site_packages" ]
```

Finally restart VSCode to see the changes

**Comment by erictraut** [comment] 2021-06-16 03:43
This appears to work fine with the latest versions of tensorflow and keras.

**Comment by jakebailey** [comment] 2021-06-24 17:56
Closing; `keras` is a part of tensorflow 2 now (and is no longer published individually). The latest tensorflow should work fine.

**Closed by jakebailey** 2021-06-24 17:56 UTC
Labels: needs investigation

**Comment by BlueskyFR** [comment] 2021-12-01 12:19
@jakebailey kerns has been separated again, please reopen

**Comment by jakebailey** [comment] 2021-12-01 17:10
If you have a problem with a newer split out keras, I don't think the issue will be related. I'd suggest opening a new issue with the template filled out.

**Comment by Raraku** [comment] 2021-12-04 07:30
I installed keras on a new conda environment and activated it in vscode. But, Pylance returns an "Import "keras.models" could not be resolved and intellisense doesn't work. Numpy, which is also installed in the conda environment works.
![Capture](https://user-images.githubusercontent.com/37752943/144701614-90417516-429e-4052-982a-624f9d8ffc97.PNG)

**Comment by bahalbach** [comment] 2022-02-11 05:43
This issue is happening with keras/tensorflow version '2.7.0' and pylance

When using
`from tensorflow import keras`
there are no hints.

A workaround is using
```
import tensorflow.keras
keras = tensorflow.keras
```

**Comment by juanagsolano** [comment] 2022-02-28 07:11
Any solution for the issue? I hace the same problem.

**Comment by Garve** [comment] 2022-04-30 23:33
Type hints do not work.
TF '2.8.0'
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by leaver2000** [comment] 2022-08-02 23:26
This is the workaround I found for the time being

```
tensorflow==2.9.1
keras==2.9.0
```

``` python
from importlib import import_module

import tensorflow as tf
from keras.api._v2 import keras as KerasAPI
# using the import module import the tensorflow.keras module
# and typehint that the type is KerasAPI module
keras: KerasAPI = import_module("tensorflow.keras")


tf.TensorArray

keras.models.Model
keras.layers.Dense
keras.layers. Flatten
keras.layers.Conv2D
keras.losses.binary_crossentropy
keras.losses.SparseCategoricalCrossentropy
```
![image](https://user-images.githubusercontent.com/76945789/182493183-94ebba12-5dd8-4e85-b320-cb78cfbc5baa.png)

**Comment by bschnurr** [comment] 2022-09-06 22:26
new stable release has the partial fix https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0


and using 
```
import tensorflow as tf
tf.keras
```

**Comment by schauppi** [comment] 2022-11-04 17:42
> new stable release has the partial fix https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0
> 
> and using
> 
> ```
> import tensorflow as tf
> tf.keras
> ```

THX! - working for me with miniforge, tensorflow 2.10.0 on Mac M1 in Dataspell Version 2022.2.3

**Comment by akashagarwal7** [comment] 2022-12-05 04:34
`keras = tf.keras` works on 2.11.0 as well on intel Mac using Anaconda.

**Comment by yusufsaif0** [comment] 2022-12-05 04:37
working fine
