### ISSUE TITLE
Pylance not finding PyTorch type stubs in _C folder

### ISSUE THREAD

**Issue by gramster** [microsoft/pylance-release#515] opened 2020-10-23 21:11 UTC
Pytorch puts stub files for C++ code in this folder in site_packages/torch. For example, for the top-level `from_numpy` function. These are not being found by Pylance.

## Environment data

-   Language Server version: 2020.10.2 
-   OS and version: MacOS 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

We should find and use these stubs.

## Actual behaviour

We don't.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment] 2020-10-23 21:18
Is this a dupe of #418 or #484?

Pytorch is currently not functioning because in their current release, they have a lot of code wrapped in `if False` blocks (#418), and for the RC, some things don't work either as they are relying on import side effects in place of explicit exporting (or asking the user to import modules): https://github.com/microsoft/pylance-release/issues/484#issuecomment-707896507

**Comment by judej** [comment] 2020-10-26 18:00
Closing as dupe of #418

**Closed** 2020-10-26 17:59 UTC
Labels: triage
