### ISSUE TITLE
Workspace folder names are evaluated as regular expressions

### ISSUE THREAD

**Issue by nils-soderman** [microsoft/pylance-release#5645] opened 2024-03-15 09:57 UTC
## Environment data

-   Language Server version: v2024.3.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2

## Code Snippet

`example.code-workspace`
```json
{
    "folders": [
        {
            "name": "[ --- Hello World ---- ]",
            "path": "."
        }
    ]
}
```

## Repro Steps

1. Create a VS Code workspace with the settings above.

2. Open a python file in the workspace to make sure Pylance extension initialize. Then check the Python Language Server output logs.

## Expected behavior

No errors

## Actual behavior

All settings are not properly read, and e.g. `python.analysis.extraPaths` might not be resolved _(sometimes they still get resolved, and sometimes not)_.

## Logs

```
2024-03-15 10:37:53.582 [info] [Error - 10:37:53 AM] (3596) Error reading settings: SyntaxError: Invalid regular expression: /\$\{workspaceFolder:[ --- Hello World ---- ]\}/g: Range out of order in character class
```

**Comment by heejaechang** [comment] 2024-03-28 17:50
expand var seems not escaping user provided string.

**Comment by LeeviOlander** [comment] 2024-04-05 15:31
I have recently encountered this issue on two separate computers, starting sometime in late March. Thus, it is likely that this issue is caused by a relatively recent update.

**Comment by cwebster-99** [comment] 2024-09-06 21:14
Thank you for the report! Given our current limited resources, it's unlikely we will be able to fix this issue in the near future. [We're closing it so we can focus on higher priority issues](https://github.com/microsoft/pylance-release/wiki/Issue-Management). However, if this is a critical issue for you let us know and we can reevaluate. Thanks!

**Closed by cwebster-99** 2024-09-06 21:14 UTC
Labels: bug
