### ISSUE TITLE
pylance requires i use quickfix to import local modules

### ISSUE THREAD

**Issue by Axzurey** [microsoft/pylance-release#3322] opened 2022-09-13 00:26 UTC
## Environment data

-   Language Server version: 2022.9.10
-   Os windows 11, vscode version 1.71.0
-   Python version: 3.10.7

I have a python file with another module in the same directory.
However, I must first use quickfix, directly open the file, or manually import the module for it to be on the import list

https://imgur.com/a/YK50hxe -- the behavior

I should be able to type a partial name, and pylance will show a list of modules including the local one

[this issue](https://github.com/microsoft/pylance-release/issues/139) highlighted the same problem but it was marked as resolved and yes, going back to that version does work, but I won't have all the features.

## Additional information:

my related settings.json looks like this:
`
{
"python.analysis.indexing": true,
"python.languageServer": "Pylance",
"python.analysis.autoSearchPaths": true,
"python.analysis.typeCheckingMode": "strict",
"python.analysis.diagnosticMode": "workspace",
}
`

**Comment by heejaechang** [comment] 2022-09-13 18:31
we do not add user types in auto import unless it is already used. code action on the other hand, adds all user types. this was a decision to make sure we do not add hundreds of user types in completion list.

**Comment by luabud** [comment] 2022-09-13 18:45
I believe this is a dupe of https://github.com/microsoft/pylance-release/discussions/2681, so closing in favour of that. Let us know if that's not the case, though :)

**Closed by luabud** 2022-09-13 18:45 UTC
Labels: triage-needed

**Comment by heejaechang** [comment] 2022-09-13 21:08
this is also dup of this - https://github.com/microsoft/pylance-release/issues/3324
