### ISSUE TITLE
better warning message for reportMissingImports 

### ISSUE THREAD

**Issue by qci-amos** [microsoft/pylance-release#4848] opened 2023-09-19 16:31 UTC
All (?) users of workspaces with >1 editable installation will run into [this](https://github.com/microsoft/pylance-release/issues/3473) issue by default. Many of them, like myself until today, will not know why they're getting orange squiggles in their code and they will give up trying to fix it. I'd suggest that naive browser searches won't easily lead them to #3473. 

At least for me, one of the most confusing aspects of this is that *some* of my editable installations would be found, but not others (even though they were all installed using `pip` the same way). This made me think that it was some kind of `PATH` or WSL problem and that somehow I wasn't selecting the correct interpreter somewhere. Retrospectively, perhaps the confusion was exacerbated by uninstalls not removing everything and/or going back and forth between WSL and Git Bash.

The quick fixes suggested include:
* changing interpreter. This does not resolve this problem.
* "learn more" link to this help [page](https://code.visualstudio.com/docs/python/editing#_importresolvefailure). Clicking the pyright documentation page leads to [this](https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs). I'd argue that the wording is a bit misleading because it states "and is currently set up to use import hooks" and also uses language suggesting it's optional, however, since I didn't (knowingly) make such a choice it's not obvious that it applies to me. I'm not even sure what an "import hook" is... 😓 

I doubt there's a quick fix available. Could you add a helpful recommendation to the `reportMissingImports` tooltip? Maybe a new category of error if pylance thinks it's a misconfigured editable install? Or maybe rewrite some of the text on the help page to be obvious?

Or maybe just by writing this up this issue, people will be able to find it more easily...

**Comment by debonte** [comment] 2023-09-20 18:36
We could detect that there are problematic `.pth` files in your environment and warn you about that in every import failure diagnostic message. Unfortunately we don't see a way to reliably connect a particular import failure to a particular `.pth` file.

@qci-amos, would that have helped in your situation?

**Comment by debonte** [comment] 2023-09-20 18:53
FYI, I also opened https://github.com/microsoft/pylance-release/issues/4855 to improve the language in our docs.

**Comment by qci-amos** [comment] 2023-09-20 20:04
> @qci-amos, would that have helped in your situation?

I'm not sure if this would have been sufficient... but yea, while I generally don't know details about how editable installations happen, informing me that there's more than one way to install them (that's the part that was news to me) should have set me on the right track!

I don't know if it helps, but feel free to cite me if it helps prod things in the right direction a la your comment [here](https://github.com/microsoft/pylance-release/issues/3473#issuecomment-1619179711)! 😁

**Comment by StellaHuang95** [comment] 2023-09-21 17:29
I'll go ahead and close this issue as a duplicate of #4855 for now. Feel free to keep an eye on the progress of the documentation improvement over there. Thanks

**Closed by StellaHuang95** 2023-09-21 17:29 UTC
Labels: needs repro
