### ISSUE TITLE
after some time pylance stops with Message: Client is not running

### ISSUE THREAD

**Issue by Morriz** [microsoft/pylance-release#5212] opened 2023-12-05 12:12 UTC
## Environment data

-   Language Server version: 2023.11.10 (pyright 088ebaa5)
-   OS and version: Sonoma 14.1.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.12.0

## Code Snippet

happens in any python project.
I am using venv

Is 3.12 not supported yet?

**Comment by StellaHuang95** [comment] 2023-12-06 02:02
Thanks for the report. Could you add the logs described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by nkarim496** [comment] 2023-12-06 14:36
I have the same problem. I use python 3.11 and venv. 
```
2023-12-06 17:33:29.788 [info] [Error - 17:33:29] Notify file events failed.
2023-12-06 17:33:29.789 [info]   Message: Client is not running
  Code: -32096 
```

**Comment by ianzone** [comment] 2023-12-07 13:22
@StellaHuang95 more logs here
```
2023-12-07 21:16:17.125 [info] [Info  - 21:16:17] (21400) Pylance language server 2023.11.10 (pyright 088ebaa5) starting
2023-12-07 21:16:17.125 [info] [Info  - 21:16:17] (21400) Server root directory: C:\Users\yihen\.vscode\extensions\ms-python.vscode-pylance-2023.11.10\dist
2023-12-07 21:16:17.130 [info] [Info  - 21:16:17] (21400) Starting service instance "DiveIntoDeepLearning"
2023-12-07 21:16:17.162 [info] [Info  - 21:16:17] (21400) Setting pythonPath for service "DiveIntoDeepLearning": "C:\Users\yihen\Mamba\envs\torch\python.exe"
2023-12-07 21:16:17.162 [info] [Info  - 21:16:17] (21400) Setting environmentName for service "DiveIntoDeepLearning": "C:\Users\yihen\Mamba\envs\torch\python.exe"
2023-12-07 21:16:17.222 [info] [Info  - 21:16:17] (21400) Assuming Python version 3.11
2023-12-07 21:16:17.299 [info] [Info  - 21:16:17] (21400) Found 2 source files
2023-12-07 21:16:17.703 [info] ERROR: The process "13284" not found.

2023-12-07 21:16:50.764 [info] [Error - 21:16:50] Server process exited with code 1.
2023-12-07 21:16:50.765 [info] [Error - 21:16:50] Connection to server got closed. Server will not be restarted.
2023-12-07 21:16:50.765 [info] [Error - 21:16:50] Handling connection close failed
2023-12-07 21:16:50.765 [info] TypeError: e.clear is not a function
	at _.cleanUp (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2412859)
	at _.handleConnectionClosed (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2417283)
	at _.handleConnectionClosed (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2578252)
	at c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2416709
	at o.invoke (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
	at s.fire (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
	at te (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2349784)
	at o.invoke (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2363387)
	at s.fire (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2364152)
	at d.fireClose (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2372012)
	at ChildProcess.<anonymous> (c:\Users\yihen\.vscode\extensions\ms-python.python-2023.20.0\out\client\extension.js:2:2384364)
	at ChildProcess.emit (node:events:525:35)
	at maybeClose (node:internal/child_process:1091:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-12-07 21:16:54.327 [info] [Error - 21:16:54] Notify file events failed.
2023-12-07 21:16:54.327 [info]   Message: Client is not running
  Code: -32096 
```

**Comment by debonte** [comment] 2023-12-07 14:31
> TypeError: e.clear is not a function

This is a duplicate of https://github.com/microsoft/pylance-release/issues/5000, which has been fixed in our prerelease builds. Please try 2023.11.13 or later.

**Closed by debonte** 2023-12-07 14:31 UTC
Labels: waiting for user response
