### ISSUE TITLE
Lambda input type is not inferred via an overridden operator

### ISSUE THREAD

**Issue by aabdagic** [microsoft/pylance-release#5239] opened 2023-12-11 02:41 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.11.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
from typing import Callable, Generic, TypeVar

InT = TypeVar("InT")
OutT = TypeVar("OutT")

class Arg(Generic[InT]):
    def __init__(self, value: InT) -> None:
        self._value = value

    def __or__(self, other: Callable[[InT], OutT]) -> OutT:
        return other(self._value)

arg = Arg(42)

result_1 = arg | (lambda x: x*2)
reveal_type(result_1)

result_2 = arg.__or__(lambda x: x*2)
reveal_type(result_2)
```

<h3> Repro Steps </h3>

Run code above

<h3> Expected behavior </h3>

`reveal_type(result_1)` -> `int`

<h3> Actual behavior </h3>

`reveal_type(result_1)` -> `Any`

Note: `result_2` already has the correct type

<h3> Logs </h3>

023-12-11 03:25:41.060 [info] [Info  - 3:25:41 AM] (19100) Pylance language server 2023.11.10 (pyright 088ebaa5) starting
2023-12-11 03:25:41.060 [info] [Info  - 3:25:41 AM] (19100) Server root directory: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist
2023-12-11 03:25:41.060 [info] [Info  - 3:25:41 AM] (19100) Starting service instance "pylance_test"
2023-12-11 03:25:41.079 [info] [Info  - 3:25:41 AM] (19100) Setting environmentName for service "pylance_test": "python"
2023-12-11 03:25:41.369 [info] [Info  - 3:25:41 AM] (19100) Found 1 source file
2023-12-11 03:32:22.820 [info] [Info  - 3:32:22 AM] (19100) Setting environmentName for service "pylance_test": "python"
2023-12-11 03:32:22.878 [info] [Info  - 3:32:22 AM] (19100) Found 1 source file
2023-12-11 03:32:53.816 [info] (19100) No configuration file found.
2023-12-11 03:32:53.816 [info] (19100) No pyproject.toml file found.
2023-12-11 03:32:53.816 [info] [Info  - 3:32:53 AM] (19100) Setting environmentName for service "pylance_test": "python"
2023-12-11 03:32:53.816 [info] (19100) Assuming Python platform Darwin
2023-12-11 03:32:53.867 [info] [Info  - 3:32:53 AM] (19100) Search paths for /Users/aabdagic/pylance_test
2023-12-11 03:32:53.867 [info] [Info  - 3:32:53 AM] (19100)   /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Users/aabdagic/pylance_test
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Users/aabdagic/pylance_test/typings
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stubs/...
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/bundled/stubs
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib-dynload
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100)   /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages
2023-12-11 03:32:53.868 [info] (19100) Searching for source files
2023-12-11 03:32:53.868 [info] [Info  - 3:32:53 AM] (19100) Found 1 source file
2023-12-11 03:32:53.874 [info] (19100) pytest configurations: {"message":"spawn python ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-12-11 03:32:53.875 [info] (19100) pytest configurations: {"message":"spawn python ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2023-12-11 03:32:53.899 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py ...
2023-12-11 03:32:53.899 [info] (19100) [BG(1)]   parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (10ms)
2023-12-11 03:32:53.922 [info] (19100) [BG(1)]   parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 0ms] (23ms)
2023-12-11 03:32:53.932 [info] (19100) [BG(1)]   binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/builtins.pyi (10ms)
2023-12-11 03:32:53.932 [info] (19100) [BG(1)]   binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:32:53.940 [info] (19100) [BG(1)]   checking: /Users/aabdagic/pylance_test/lambda_type_inference.py ...
2023-12-11 03:32:53.940 [info] (19100) [BG(1)]     parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing.pyi [fs read 2ms] (7ms)
2023-12-11 03:32:53.942 [info] (19100) [BG(1)]     binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing.pyi (3ms)
2023-12-11 03:32:53.945 [info] (19100) [BG(1)]     parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (3ms)
2023-12-11 03:32:53.946 [info] (19100) [BG(1)]     binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing_extensions.pyi (0ms)
2023-12-11 03:32:53.949 [info] (19100) [BG(1)]     parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (2ms)
2023-12-11 03:32:53.950 [info] (19100) [BG(1)]     binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2023-12-11 03:32:53.953 [info] (19100) [BG(1)]     parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (3ms)
2023-12-11 03:32:53.954 [info] (19100) [BG(1)]     binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/types.pyi (1ms)
2023-12-11 03:32:53.956 [info] (19100) [BG(1)]     parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/abc.pyi [fs read 1ms] (1ms)
2023-12-11 03:32:53.959 [info] (19100) [BG(1)]     binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
2023-12-11 03:32:53.959 [info] (19100) [BG(1)]   checking: /Users/aabdagic/pylance_test/lambda_type_inference.py (26ms)
2023-12-11 03:32:53.960 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py (69ms)
2023-12-11 03:32:53.961 [info] (19100) [BG(1)] indexing: /Users/aabdagic/pylance_test/lambda_type_inference.py [found 6] (0ms)
2023-12-11 03:32:54.152 [info] (19100) [IDX(4)] scan packages /Users/aabdagic/pylance_test ...
2023-12-11 03:32:54.152 [info] (19100) [IDX(4)]   read stdlib indices (12ms)
2023-12-11 03:32:54.206 [info] (19100) [IDX(4)] scan packages /Users/aabdagic/pylance_test (67ms)
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)] index packages /Users/aabdagic/pylance_test ...
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)]   index execution environment /Users/aabdagic/pylance_test ...
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/__init__.py [skipped: no '__all__' defined] (1ms)
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib2to3/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.228 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pydoc_data/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.229 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/turtledemo/__init__.py [skipped: no '__all__' defined] (1ms)
2023-12-11 03:32:54.229 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.230 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/wsgiref/__init__.py [skipped: no '__all__' defined] (1ms)
2023-12-11 03:32:54.230 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/xmlrpc/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.230 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/altgraph/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.230 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/future/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.231 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/libfuturize/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.232 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/libpasteurize/__init__.py [skipped: no '__all__' defined] (1ms)
2023-12-11 03:32:54.232 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/macholib/__init__.py [skipped: no '__all__' defined] (1ms)
2023-12-11 03:32:54.232 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/past/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.232 [info] (19100) [IDX(4)]     indexing: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/wheel/__init__.py [skipped: no '__all__' defined] (0ms)
2023-12-11 03:32:54.232 [info] (19100) [IDX(4)]   index execution environment /Users/aabdagic/pylance_test [found 98 in 4 files] (6ms)
2023-12-11 03:32:54.233 [info] (19100) [IDX(4)] index packages /Users/aabdagic/pylance_test [found 98 in 1 exec envs] (10ms)
2023-12-11 03:33:03.677 [info] (19100) [FG] parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (2ms)
2023-12-11 03:33:03.695 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 0ms] (17ms)
2023-12-11 03:33:03.713 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/builtins.pyi (17ms)
2023-12-11 03:33:03.715 [info] (19100) [FG] binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (1ms)
2023-12-11 03:33:04.123 [info] (19100) [BG(1)] getSemanticTokens delta previousResultId:1702261768758 at /Users/aabdagic/pylance_test/lambda_type_inference.py (2ms)
2023-12-11 03:33:14.862 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (18ms)
2023-12-11 03:33:14.866 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing.pyi (4ms)
2023-12-11 03:33:14.869 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (3ms)
2023-12-11 03:33:14.870 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/typing_extensions.pyi (1ms)
2023-12-11 03:33:14.874 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (3ms)
2023-12-11 03:33:14.875 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2023-12-11 03:33:14.880 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (5ms)
2023-12-11 03:33:14.882 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/types.pyi (2ms)
2023-12-11 03:33:15.065 [info] (19100) [FG] parsing: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
2023-12-11 03:33:15.065 [info] (19100) [FG] binding: /Users/aabdagic/.vscode/extensions/ms-python.vscode-pylance-2023.11.10/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
2023-12-11 03:33:28.065 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py ...
2023-12-11 03:33:28.065 [info] (19100) [BG(1)]   parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (2ms)
2023-12-11 03:33:28.065 [info] (19100) [BG(1)]   binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:33:28.074 [info] (19100) [BG(1)]   checking: /Users/aabdagic/pylance_test/lambda_type_inference.py (9ms)
2023-12-11 03:33:28.074 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py (11ms)
2023-12-11 03:33:28.075 [info] (19100) [FG] parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (1ms)
2023-12-11 03:33:28.076 [info] (19100) [FG] binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (1ms)
2023-12-11 03:33:28.076 [info] (19100) [BG(1)] indexing: /Users/aabdagic/pylance_test/lambda_type_inference.py [found 6] (0ms)
2023-12-11 03:33:28.254 [info] (19100) [BG(1)] getSemanticTokens delta previousResultId:1702261984121 at /Users/aabdagic/pylance_test/lambda_type_inference.py ...
2023-12-11 03:33:28.255 [info] (19100) [BG(1)]   parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:33:28.255 [info] (19100) [BG(1)]   binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:33:28.260 [info] (19100) [BG(1)] getSemanticTokens delta previousResultId:1702261984121 at /Users/aabdagic/pylance_test/lambda_type_inference.py (6ms)
2023-12-11 03:33:28.323 [info] (19100) [FG] parsing: /Users/aabdagic/pylance_test/lambda_type_inference.py (1ms)
2023-12-11 03:33:28.324 [info] (19100) [FG] binding: /Users/aabdagic/pylance_test/lambda_type_inference.py (1ms)
2023-12-11 03:33:28.452 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py ...
2023-12-11 03:33:28.452 [info] (19100) [BG(1)]   checking: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:33:28.452 [info] (19100) [BG(1)] analyzing: /Users/aabdagic/pylance_test/lambda_type_inference.py (0ms)
2023-12-11 03:33:28.452 [info] (19100) [BG(1)] indexing: /Users/aabdagic/pylance_test/lambda_type_inference.py [found 6] (0ms)

```
XXX
```

**Comment by erictraut** [comment] 2023-12-11 02:53
Pyright (the type checker upon which pylance is built) is working as designed here. 

This doesn't have anything to do with overloads, since the function in question has no `@overload`. I suspect you meant "overridden" rather than "overloaded".

In Python, the `|` operator does not simply call the `__or__` magic method. It's much more complex than that. It first calls `__or__` on the left-hand operator and then calls `__ror__` on the right-hand operator. Because of this complex behavior, type checkers cannot use [bidirectional type inference](https://microsoft.github.io/pyright/#/type-inference?id=bidirectional-type-inference-expected-types) in this situation. The type of the left-hand and right-hand operands must be inferred upfront without knowledge of an "expected type".

When you directly call the `__or__` method, it is possible for pyright to make use of bidirectional type inference.

If you want this to work with static type checking, you have a couple of options.
1. As you discovered, you can call `__or__` explicitly.
2. You can provide an explicit type annotation for the lambda.
```python
x: Callable[[int], int] = lambda x: x * 2
result_1 = arg | x
```
3. You can use a `def` statement with type annotations.
```python
def double(x: int): return x * 2
result_1 = arg | double
```

**Comment by aabdagic** [comment] 2023-12-11 03:00
Yup, I meant overridden - fixed up the title to avoid confusion.

One thing to note is that this inference seems to just-work in mypy. Not sure if because of an unsound assumption though...

**Comment by heejaechang** [comment] 2023-12-15 00:13
tagging @erictraut to see whether he has any more feedback. otherwise, I will close it as by design.

**Comment by erictraut** [comment] 2023-12-15 03:50
Inference rules differ between type checkers. Pyright is working as designed. This isn't a bug. Please close.

**Closed** 2024-01-08 18:56 UTC
Labels: needs repro
