### ISSUE TITLE
Semantic highlighting broken for imports

### ISSUE THREAD

**Issue by Squirrel623** [microsoft/pylance-release#1287] opened 2021-05-14 15:28 UTC
## Environment data

-   VS Code version: 1.55.2
-   Extension version (available under the Extensions sidebar): 2021.5.840043038
-   OS and version: Ubuntu 18.04.5 LTS, remoting in via SSH
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance 2021.5.2 
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Using python extension version v2021.4.765268190:
![image](https://user-images.githubusercontent.com/8680248/118291494-e7ad8400-b494-11eb-8e49-de399b292f4b.png)

## Actual behaviour

Using python extension version 2021.5.840043038:
![image](https://user-images.githubusercontent.com/8680248/118291564-fb58ea80-b494-11eb-9f59-6736248a3f1b.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

I tried to reproduce this by opening a new window, installing the python extension, and creating/saving a new python file but I saw the extension behaving correctly. For the examples/data given here the only change is the python extension version (changed by right clicking and installing another version)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

v2021.4.765268190:
```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
Python interpreter path: ./pcgenv/bin/python
Starting Pylance language server.
> conda --version
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --config-file ./mypy.ini --no-check-untyped-defs ~/Documents/git/pcglender/pcgapp/waterfall.py
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --config-file ./mypy.ini --no-check-untyped-defs ~/Documents/git/pcglender/pcgapp/waterfall.py
cwd: ~/Documents/git/pcglender
##########Linting Output - mypy##########
Found 1 error in 1 file (checked 1 source file)
```

I think that 2021.5 is trying to load the Jedi language server instead of Pylance but I don't think it should be doing that based on my configuration. When using 2021.5 the "Python Language Server" output pane is not even present.

2021.5.840043038:
```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
Python interpreter path: ./pcgenv/bin/python
Starting Jedi Python language engine.
> conda --version
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --config-file ./mypy.ini --no-check-untyped-defs ~/Documents/git/pcglender/pcgapp/waterfall.py
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --config-file ./mypy.ini --no-check-untyped-defs ~/Documents/git/pcglender/pcgapp/waterfall.py
cwd: ~/Documents/git/pcglender
##########Linting Output - mypy##########
Found 1 error in 1 file (checked 1 source file)
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Documents/git/pcglender
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/completion.py
> ~/Documents/git/pcglender/pcgenv/bin/python ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.5.840043038/pythonFiles/completion.py

```

</p>
</details>

**Comment by Squirrel623** [comment] 2021-05-14 16:23
Throughout this entire process I have been using my virtualenv's Python 3 interpreter and never explicitly used Python 2, but I am encountering https://github.com/microsoft/vscode-python/issues/16197 so I haven't always seen the Python 3 interpreter being used in the status bar.

I have the `languageServer` explicitly set to "Pylance" - here is my `settings.json`

```json
{
  "python.pythonPath": "pcgenv/bin/python",
  "python.linting.pylintEnabled": false,
  "python.linting.mypyEnabled": true,
  "python.languageServer": "Pylance",
  "python.analysis.typeCheckingMode": "off",
  "mypy.targets": [
    "pcgapp/tasks.py",
    "pcgapp/funds/fund.py",
    "pcgapp/loans/payment.py",
    "pcgapp/utils.py",
    "pcgapp/company.py",
    "pcgapp/views.py",
    "pcgapp/loans/loan.py",
    "pcgapp/notifications.py",
    "pcgapp/waterfall.py"
  ],
  "mypy.executable": "~/Documents/git/pcglender/pcgenv/bin/mypyls",
  "python.linting.enabled": true
}
```

**Comment by jakebailey** [comment] 2021-05-14 16:25
Sure, thanks. I think we'll have to wait for https://github.com/microsoft/vscode-python/pull/16246 to me merged and released to verify the root cause here. Your logs imply that the core extension is picking Jedi when it shouldn't be.

This issue got transferred to this repo, but I don't think this is a Pylance bug.

**Comment by jakebailey** [comment] 2021-05-14 18:26
The Python extension just updated; can you test with version `2021.5.842923320`?

**Comment by Squirrel623** [comment] 2021-05-14 18:37
That seems to have fixed it, thanks!

**Closed** 2021-05-14 18:37 UTC
Labels: waiting for info
