### ISSUE TITLE
tfio.audio.AudioIOTensor not found, but found in invalid tfio.audio.audio.AudioIOTensor

### ISSUE THREAD

**Issue by busFred** [microsoft/pylance-release#849] opened 2021-01-18 14:55 UTC
## Environment data

-   Language Server version: Pylance v2021.1.1
-   OS and version: Windows 10 Pro 19042.746
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Expected behaviour
Pylance says `"AudioIOTensor" is not a known member of module`, but Python interpreter executes without error.
```
import tensorflow_io as tfio
audio = tfio.audio.AudioIOTensor('/path/to/filename')
```

## Actual behaviour
Intellisense/Pylance suggest AudioIOTensor class is in tfio.audio.audio, but it is actually in tfio.audio
Pylance is happy with the below code, but python interpreter is not happy.
```
import tensorflow_io as tfio
audio = tfio.audio.audio.AudioIOTensor('/path/to/filename')
```
When executed, tfio.audio.audio.AudioIOTensor is not found
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\Fred\Documents\Research\fire_detection\sound_detection_tensorflow_py\src\spectrogram_test\spectrogram_test.py in 
      8 # audio file are loaded lazily
      9 # incorrect, keep for intellisense
----> 10 audio = tfio.audio.audio.AudioIOTensor(
      11     '../../bin/data/chunk/audio_dataset_15/fire/0.wav')
      12 # audio = tfio.audio.AudioIOTensor(

AttributeError: module 'tensorflow_io.core.python.api.v0.audio' has no attribute 'audio'
```

## Logs

Nothing is shown

## Code Snippet / Additional information

Shown above.

**Comment by clusidc** [comment] 2021-02-12 11:57
I've got a similar issue with some PyQt Packages. Although this seems more to be a problem of a specific package/module layout.

- Language Server Version: v2021.2.3-pre1
- Win 10 Pro 19042.804
- Python: Anaconda, Python=3.8.5
- PyQt and PyQtDataVisualization were installed with pip in the conda environment. Both Version 5.15.2

The following Code works fine in Python, although there is no indication by the VSCode Autocompletion and Syntax Highlighting that `Q3DScatter` is a member of `QtDataVisualization`
```python
from PyQt5 import QtDataVisualization

scatterplot = QtDataVisualization.Q3DScatter()
```

The following gives typing information, but an error in Python:
```python
from PyQt5 import QtDataVisualization

scatterplot = QtDataVisualization.QtDataVisualization.Q3DScatter()
```
```
Traceback (most recent call last):
  File "[...]/test.py", line 3, in <module>
    scatterplot = QtDataVisualization.QtDataVisualization.Q3DScatter()
AttributeError: module 'PyQt5.QtDataVisualization' has no attribute 'QtDataVisualization'
```

Digging a bit into the `[...]\envs\[myenvironment]\lib\site-packages\PyQt5\QtDataVisualization.pyi` file, I find following.
```python
import typing
import sip

from PyQt5 import QtGui
# some other code
class QtDataVisualization(sip.simplewrapper):
    # other classes
    class Q3DScatter('QAbstract3DGraph'):
            # class interface
```

The pylance logs don't give any useful information besides (i left out the pretty long path name ->[...]):
```
Background analysis message: getDiagnosticsForRange
[FG] parsing: [...]\test.py (1ms)
[FG] binding: [...]\test.py (0ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: [...]\test.py (0ms)
[BG(1)] binding: [...]\test.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: [...]\test.py ...
[BG(1)]   checking: [...]\test.py (0ms)
[BG(1)] analyzing: [...]\test.py (0ms)
Background analysis message: resumeAnalysis
Background analysis message: markFilesDirty
```


![grafik](https://user-images.githubusercontent.com/2925320/107765097-8a892180-6d31-11eb-8fcc-f6a6ff88dac3.png)
![grafik](https://user-images.githubusercontent.com/2925320/107765145-a12f7880-6d31-11eb-8e11-9d6ff018ed64.png)

**Comment by bschnurr** [comment] 2021-09-14 17:23
Seems fixed. can't repo with the latest `pip install tensorflow-io' version 0.21.0
```
pip install tensorflow-io                                                                                         pwsh  10:14:51  
Collecting tensorflow-io
  Downloading tensorflow_io-0.21.0-cp39-cp39-win_amd64.whl (21.3 MB)
     |████████████████████████████████| 21.3 MB 6.4 MB/s
```
python 3.9.6 but should also work with 3.8

**Comment by bschnurr** [comment] 2021-09-14 17:39
closing for now. if the issue is still occurs please reopen.

**Closed by bschnurr** 2021-09-14 17:39 UTC
Labels: waiting for user response
