### ISSUE TITLE
Recent pylance is striking out `Union` imports as deprecated

### ISSUE THREAD

**Issue by gwk** [microsoft/pylance-release#6390] opened 2024-09-14 22:30 UTC
# Summary

As of Python 3.12, `typing.Union` is not documented as deprecated. Furthermore, the type `|` operator is not a perfect replacement for `Union`, because union can mix string and type arguments whereas `|` cannot.

Unfortunately, Pylance is reporting that `Union` is deprecated. It also seems to be suffering from a bug where the version number is reported as `[object Object]`. Perhaps this is the reason for the error?

<h3> Environment data </h3>

-   Language Server version: 2024.9.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda):  CPython 3.12.2
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
from typing import Union
```

<h3> Expected behavior </h3>
I would expect Plyance to not be so aggressive about reporting `typing.Union` as deprecated, when it really is not. It seems that this is somebody's style preference that has been turned into a non-optional warning in the language server. Please consider that the recommended `|` type operator is not a perfect replacement for `Union`, because union can mix string and type arguments whereas `|` cannot. Pylance should not report it as deprecated or strike it through. At very least, it should display a hint to turn off such aggressive warnings like this in the hover explanation.

Note that `Union` is not documented as deprecated in 3.13 RC2 either. See:
* https://docs.python.org/3.12/library/typing.html#typing.Union
* https://docs.python.org/3.13/library/typing.html#typing.Union

<h3> Actual behavior </h3>
Pylance strikes out the `Union` import and displays this message on hover:
> This type is deprecated as of Python [object Object]; use "|" insteadPylance

<h3> Logs </h3>

```
2024-09-14 09:51:10.848 [info] (Client) Pylance async client (2024.9.1) started with python extension (2024.15.2024091301)
2024-09-14 09:51:11.173 [info] [Info  - 9:51:11 AM] (50297) Pylance language server 2024.9.1 (pyright version 1.1.378, commit ce64adc1) starting
2024-09-14 09:51:11.217 [info] [Info  - 9:51:11 AM] (50297) Assuming Python version 3.12.2.final.0

```

**Comment by erictraut** [comment] 2024-09-14 23:24
Thanks for reporting the `[object Object]` issue. That hasn't been previously reported. I just introduced a fix in pyright, and it will be fixed in the next pyright release.

As for the other issue, this is by design. By default, pyright doesn't mark `Union` as deprecated. This is true even in strict mode. I presume that you've opted to enable the `deprecateTypingAliases` option in your pyright configuration. Only when this is enabled will you see pyright treat `typing.Union`, `typing.List`, etc. as deprecated. While none of these older-style `typing` special forms are unlikely to go away any time soon, their use does make your code look outdated in general. Many pyright users requested that we provide a way to identify and report their usage to facilitate the modernization of their code base. If you prefer to use older forms like `Union`, simply revert the `deprecateTypingAliases` configuration option back to its default value of "false".

**Comment by StellaHuang95** [comment] 2024-09-19 00:24
This issue has been fixed in prerelease version 2024.9.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249101-18-September-2024-PreRelease)

**Closed by StellaHuang95** 2024-09-19 00:24 UTC
Labels: bug, fixed in next version (pyright)

**Comment by agkphysics** [comment] 2024-09-26 00:56
> This issue has been fixed in prerelease version 2024.9.101

The release notes state:
> Bug fix: Recent pylance is striking out Union imports as deprecated [pylance-release#6390](https://github.com/microsoft/pylance-release/issues/6390)

But this is not correct. `Optional` and `Union` are both still marked as deprecated with Pylance v2024.9.101:
![deprecated](https://github.com/user-attachments/assets/334e7586-1a83-4e60-acba-34f2dcb5f00b)

**Comment by debonte** [comment] 2024-09-26 15:40
@agkphysics, do you have `deprecateTypingAliases` enabled? See [this comment](https://github.com/microsoft/pylance-release/issues/6390#issuecomment-2351215828) above.

**Comment by rchiodo** [comment] 2024-09-26 15:41
Did you turn off the 'deprecateTypingAliases' setting? That's what causes the error to show up for me.

**Comment by erictraut** [comment] 2024-09-26 17:20
The pylance team wrote the release notes, so we'd need to ask them for clarification, but I suspect that it's referring to the fact that I fixed the `[object Object]` issue that you reported above. Perhaps their automated scripts just copied the title of your bug report into the release notes. If you look in the [pyright release notes](https://github.com/microsoft/pyright/releases), there is no reference to "Union imports".

**Comment by debonte** [comment] 2024-09-26 17:24
> Perhaps their automated scripts just copied the title of your bug report into the release notes.

Yes, that's correct. We don't write our release notes by hand anymore.
