### ISSUE TITLE
Bug in new version of autocompletion for python

### ISSUE THREAD

**Issue by ParisNeo** [microsoft/pylance-release#1941] opened 2021-10-14 12:09 UTC
Issue Type: Bug

Since the last update, my autocompletion (python) is not working properly. Either it is not showing any thing or it is partially working. For example with tensorflow, it can see that there is a submodule called keras, but can't see what's inside keras!!!

VS Code version: Code 1.61.0 (ee8c7de, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by ParisNeo** [comment] 2021-10-17 08:48
Unfortunately, I'm still getting the same result over and over again. I didn't have any issue untill last update, so something must have hapened.

I don't quite understand what's happening exactly and I'm not expert in vscode modules.
I just use it to code in python with a basic configuration.

**Comment by bersbersbers** [comment] 2021-12-23 08:40
Sounds a lot like a duplicate of #1066.

**Comment by bschnurr** [comment] 2022-01-26 17:35
try adding this to the bottom of your  `tensorflow/__init__.py`
```
# Explicitly import lazy-loaded modules to support autocompletion.
# pylint: disable=g-import-not-at-top
if _typing.TYPE_CHECKING:
  from tensorflow_estimator.python.estimator.api._v2 import estimator as estimator
  from keras.api._v2 import keras
  from keras.api._v2.keras import losses
  from keras.api._v2.keras import metrics
  from keras.api._v2.keras import optimizers
  from keras.api._v2.keras import initializers
# pylint: enable=g-import-not-at-top
```

**Comment by ParisNeo** [comment] 2022-01-26 20:49
It worked !!!
Thank you very much.

Can you explain why is required? I didn't have the problem before!

**Comment by bschnurr** [comment] 2022-01-26 21:04
the issue is in tensorflow, and how they lazyload their imports. 
I'll create a PR in tensorflow so that it gets checked in there.

**Comment by erictraut** [comment] 2022-04-20 05:40
@judej, I think this can be closed. This is an issue with tensorflow.

**Closed** 2022-04-21 19:10 UTC
Labels: needs investigation
