### ISSUE TITLE
type checking doesn't work well with some libs

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/pylance-release#245] opened 2020-08-15 06:45 UTC
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/57612792/90307055-a8520700-df05-11ea-81af-e73c97d2f1ce.png)

it runs well, but still get errors. Pylance doesn't work well with pygame too.

Extension version: 2020.8.1
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.42GB (6.39GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/桌面/python.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by erictraut** [comment] 2020-08-15 19:58
I think this is a duplicate of #138.

**Closed** 2020-08-17 16:51 UTC
Labels: duplicate, needs stub
