### ISSUE TITLE
Symlinks lead to "Received redundant open text document command"

### ISSUE THREAD

**Issue by mrichtarsky** [microsoft/pylance-release#5039] opened 2023-10-28 08:30 UTC
## Environment data

-   Language Server version: v2023.10.50
-   OS and version: Windows 10 22H2 19045.3570 (client), Ubuntu 22.04.3 LTS (remote machine, where the language server runs)
-   Python version (& distribution if applicable, e.g. Anaconda):  3.10.12 (remote machine)

## Code Snippet

```python
a=1
```

## Repro Steps

1. `mkdir repro && cd repro && mkdir proj1 && ln -s proj1 syml && (echo 'a=1' > syml/f1.py) && code syml/f1.py`
2. Rename "a" to "b"

## Expected behavior

- "a" renamed to "b" in current editor

## Actual behavior

- New editor opens in background where "a" is renamed to "b". New editor points to the file with the symlink resolved (`repro/proj1/f1.py`)
- Old editor remains in focus without any changes

## Logs

```
2023-10-28 10:13:40.881 [info] (970088) [FG] parsing: /projects/root/repro/proj1/f1.py (18ms)
2023-10-28 10:13:41.050 [info] (970088) [FG] parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (171ms)
2023-10-28 10:13:41.114 [info] (970088) [FG] binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/builtins.pyi (64ms)
2023-10-28 10:13:41.115 [info] (970088) [FG] binding: /projects/root/repro/proj1/f1.py (1ms)
2023-10-28 10:13:41.124 [info] (970088) [BG(1)] analyzing: /projects/root/repro/proj1/f1.py ...
2023-10-28 10:13:41.124 [info] (970088) [BG(1)]   parsing: /projects/root/repro/proj1/f1.py (1ms)
2023-10-28 10:13:41.284 [info] (970088) [BG(1)]   parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 0ms] (160ms)
2023-10-28 10:13:41.325 [info] (970088) [BG(1)]   binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/builtins.pyi (37ms)
2023-10-28 10:13:41.326 [info] (970088) [BG(1)]   binding: /projects/root/repro/proj1/f1.py (0ms)
2023-10-28 10:13:41.333 [info] (970088) [BG(1)]   checking: /projects/root/repro/proj1/f1.py (4ms)
2023-10-28 10:13:41.334 [info] (970088) [BG(1)] analyzing: /projects/root/repro/proj1/f1.py (212ms)
2023-10-28 10:13:41.339 [info] (970088) [BG(1)] getSemanticTokens full at /projects/root/repro/proj1/f1.py (3ms)
2023-10-28 10:13:41.340 [info] (970088) [BG(1)] getSemanticTokens range 0:0 - 1:0 at /projects/root/repro/proj1/f1.py (1ms)
2023-10-28 10:13:46.759 [info] [Error - 10:13:46 AM] (970088) Received redundant open text document command for /projects/root/repro/proj1/f1.py
2023-10-28 10:13:47.023 [info] (970088) [BG(1)] analyzing: /projects/root/repro/proj1/f1.py ...
2023-10-28 10:13:47.023 [info] (970088) [BG(1)]   parsing: /projects/root/repro/proj1/f1.py (1ms)
2023-10-28 10:13:47.023 [info] (970088) [BG(1)]   binding: /projects/root/repro/proj1/f1.py (0ms)
2023-10-28 10:13:47.067 [info] (970088) [BG(1)]   checking: /projects/root/repro/proj1/f1.py ...
2023-10-28 10:13:47.068 [info] (970088) [BG(1)]     parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (54ms)
2023-10-28 10:13:47.088 [info] (970088) [BG(1)]     binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/typing.pyi (20ms)
2023-10-28 10:13:47.105 [info] (970088) [BG(1)]     parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (16ms)
2023-10-28 10:13:47.131 [info] (970088) [BG(1)]     binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/typing_extensions.pyi (26ms)
2023-10-28 10:13:47.163 [info] (970088) [BG(1)]     parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (11ms)
2023-10-28 10:13:47.168 [info] (970088) [BG(1)]     binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (4ms)
2023-10-28 10:13:47.181 [info] (970088) [BG(1)]     parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/types.pyi [fs read 1ms] (13ms)
2023-10-28 10:13:47.202 [info] (970088) [BG(1)]     binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/types.pyi (20ms)
2023-10-28 10:13:47.211 [info] (970088) [BG(1)]     parsing: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (2ms)
2023-10-28 10:13:47.211 [info] (970088) [BG(1)]     binding: /projects/root/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
2023-10-28 10:13:47.215 [info] (970088) [BG(1)]   checking: /projects/root/repro/proj1/f1.py (202ms)
2023-10-28 10:13:47.216 [info] (970088) [BG(1)] analyzing: /projects/root/repro/proj1/f1.py (204ms)

```

## Note

- It seems Pylance does not deal correctly with symlinks which is quite surprising. But I could reproduce the issue on two hosts. This seems to be the problem:

```
2023-10-28 10:13:46.759 [info] [Error - 10:13:46 AM] (970088) Received redundant open text document command for /projects/root/repro/proj1/f1.py
```

**Comment by mrichtarsky** [comment] 2023-10-28 08:47
- I'm pretty sure this worked sometime in the past
- Could this be due to some extension/setting of mine? Although checking the settings for above scenario, I had no changes to the `python.*` settings except for the tracing, and only Pylance and Python extensions enabled on the remote

**Comment by debonte** [comment] 2023-10-28 22:15
Dupe of #5030

**Closed by debonte** 2023-10-28 22:15 UTC
Labels: needs repro
