### ISSUE TITLE
Go to symbol in a library

### ISSUE THREAD

**Issue by crabhi** [microsoft/pylance-release#5092] opened 2023-11-07 13:15 UTC
I'd like to be able to search for symbols (or at least strings) in the whole virtual environment. I'm coming from PyCharm and trying to switch to VS Code.

### Introduce the concept of "dependencies"

For my workflow, it's important to distinguish "project" and "dependecies". When I tried adding virtualenv into the workspace, I found the search results too cluttered. _Usually, I search only within the project._ But sometimes, it's useful to broaden the search scope.

I like how it's possible to browse the dependencies in JetBrains' IDEs, regardless of their physical location. Then actions like "search in folder" work intuitively.

### Example workflow:

In this code, I'd like to be able to go to the `RedisChannelLayer` definition:

```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}
```

When using the action "Go to Symbol in Workspace...", I don't get `RedisChannelLayer` as an option. 

Now, consider this code:

```python
from channels_redis.core import RedisChannelLayer
```

With this kind of code, the action "Go to Definition" works. So VS Code knows where to find the symbol and access the file. It just doesn't let me search or browse the dependencies.

### Related Issues

I've found the issue https://github.com/microsoft/vscode-python/issues/15018 which I think is closely related but I feel there may have been a slight misunderstanding between @brettcannon and the other posters with regards to the intended workflow and VS Code capabilities. Since that issue is closed, I created this one.

**Comment by debonte** [comment] 2023-11-07 18:13
Dupe of https://github.com/microsoft/pylance-release/discussions/3187?

**Comment by rchiodo** [comment] 2023-11-07 18:13
We do have this option: 

![image](https://github.com/microsoft/pylance-release/assets/19672699/a8fe831e-3cfa-427a-9569-0bed2ab40bcd)

That would have at least let you goto definition in the string you quoted.

**Comment by crabhi** [comment] 2023-11-08 08:05
> Dupe of https://github.com/microsoft/pylance-release/discussions/3187?

Most probably yes. I posted this issue into a different repo and I didn't find that one.

@rchiodo thanks, I didn't know about that option. The ability to search (both text and symbols) and browse dependencies would still be useful.

**Comment by debonte** [comment] 2023-11-08 16:55
> I posted this issue into a different repo and I didn't find that one.

Sure. No worries.

Please up-vote https://github.com/microsoft/pylance-release/discussions/3187 if you haven't already.

**Closed by debonte** 2023-11-08 16:55 UTC
Labels: needs repro
