### ISSUE TITLE
pylance keep crashing

### ISSUE THREAD

**Issue by fredvol** [microsoft/pylance-release#6369] opened 2024-09-09 16:21 UTC
Type: <b>Bug</b>

One several project  i now have the message that pylance has crashed 5 times in the last 3 min.
This was not the case few version before.
I tryed to swith to the pre-release version hoping this was just a bad version. 
But I have the feeling that it happen on more ans more of my project , ( computer on linux and windows) 
Thanks 

Extension version: 2024.8.2
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Linux x64 6.8.0-41-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3432)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.53GB (12.17GB free)|
|Process Argv|--crash-reporter-id 966be742-5724-47fe-bb1f-2032ba0f847f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by rchiodo** [comment] 2024-09-09 16:22
Would you happen to be using the interactive window?

Might be this issue here:
#6357

**Comment by fredvol** [comment] 2024-09-09 16:23
yes using interactive windows.

**Comment by rchiodo** [comment] 2024-09-09 16:24
Closing as a dupe of #6357

**Closed by rchiodo** 2024-09-09 16:24 UTC
Labels: needs repro
