### ISSUE TITLE
Go to Definition(F12) of the pytest fixture does not work in a workspace project.   

### ISSUE THREAD

**Issue by yakkle** [microsoft/pylance-release#5114] opened 2023-11-14 03:46 UTC
The pylance `2023.09.30` version works, but later versions do not.
Works when a single project, but not when changed to a workspace project.

## Environment data

-   Language Server version: 2023.11.10
-   OS and version: MacOS Monterey 12.6(21G115) M1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6

## Code Snippet

```python
import pytest

@pytest.fixture
def foo() -> str:
    return "foo"


@pytest.fixture
def bar(foo):
    print(foo)
    return "bar"
```

## Repro Steps

1. Open python project
2. Create `conftest.py` with above sample code.
3. File -> Add Folder to Workspace...
4. `cmd + click` or `F12` on parameter `foo` in fixture `bar`

## Expected behavior

Go to definition of fixture `foo`

https://github.com/microsoft/pylance-release/issues/3727

## Actual behavior

Go to `print(foo)` in fixture `bar`

**Comment by qmmp123** [comment] 2023-12-19 12:55
+1

**Comment by debonte** [comment] 2023-12-19 20:44
This appears to be fixed in our latest prerelease build (2023.12.100). Can you give it a try?

**Comment by qmmp123** [comment] 2023-12-19 21:06
Still doesn't work. May be I can provide some logs or anything else?

```
Pylance - 2023.12.100

VsCode
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.4.7-arch1-2
```

**Comment by debonte** [comment] 2023-12-20 01:24
@qmmp123, can you provide source code that reproduces what you're seeing?

Also please confirm that you have `python.analysis.enablePytestSupport` set to `true`. And that the file you code is in is either named `conftest.py`, `test_*.py`, or `*_test.py`.

**Comment by qmmp123** [comment] 2023-12-20 03:45
![image](https://github.com/microsoft/pylance-release/assets/6360702/7eef9023-1f11-4351-b8f0-da9e48c7858a)

Sorry I can't share the code but here is screenshot that shows problem

**Comment by debonte** [comment] 2023-12-20 07:00
Thanks. I'm able to repro it now. I'll investigate.

**Comment by debonte** [comment] 2023-12-20 07:37
Sorry, I was wrong. I can't reproduce what you're seeing. It's pretty odd that hover says the type of the parameter is `Unknown` while the inlay hint says that it's `LibvirtVMResource` though.

@yakkle, can you try 2023.12.100 and see if your issue is fixed? I'm pretty sure that what @qmmp123 is seeing is unrelated.

@qmmp123, without a repro we can't fix this. Could you give me temporary access to your repo? If not, could you reduce your repro case to something simple and shareable?

**Comment by qmmp123** [comment] 2023-12-20 22:29
I will try to do it

**Comment by qmmp123** [comment] 2023-12-21 03:44
I've reproduced it. That problem caused by code-workspace file. Try it https://github.com/qmmp123/sandbox

**Comment by debonte** [comment] 2023-12-21 06:50
> That problem caused by code-workspace file. Try it https://github.com/qmmp123/sandbox .

Thanks. I still can't reproduce it. Maybe it's settings related? Can you provide your user `settings.json`?

**Comment by qmmp123** [comment] 2023-12-21 13:30
```json
{
    "workbench.colorTheme": "GitHub Dark",
    "window.titleBarStyle": "custom",
    "window.customMenuBarAltFocus": false,
    "cmake.configureOnOpen": true,
    "explorer.autoReveal": false,
    "workbench.colorCustomizations": {
        "statusBar.background": "#005f5f",
        "statusBar.noFolderBackground": "#005f5f",
        "statusBar.debuggingBackground": "#005f5f"
    },
    "vscode-neovim.logPath": "~/.vscode-neovim.log",
    "vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
    "vscode-neovim.neovimInitVimPaths.linux": "~/.config/nvim/init-vscode.vim",
    "editor.lineNumbers": "relative",
    "workbench.iconTheme": "material-icon-theme",
    "python.analysis.diagnosticSeverityOverrides": {
        "reportUndefinedVariable": "warning"
    },
    "vscode-neovim.neovimExecutablePaths.darwin": "/usr/local/bin/nvim",
    "vscode-neovim.neovimInitVimPaths.darwin": "~/.config/nvim/init-vscode.vim",
    "editor.minimap.enabled": false,
    "problems.showCurrentInStatus": true,
    "editor.suggest.showStatusBar": true,
    "editor.unicodeHighlight.ambiguousCharacters": false,
    "python.analysis.useLibraryCodeForTypes": true,
    "workbench.editor.enablePreview": false,
    "editor.suggest.showColors": true,
    "editor.suggest.showWords": true,
    "python.analysis.autoImportCompletions": false,
    "editor.suggest.preview": true,
    "editor.suggest.localityBonus": true,
    "explorer.confirmDelete": false,
    "editor.largeFileOptimizations": false,
    "workbench.editor.empty.hint": "hidden",
    "extensions.experimental.affinity": {
        "asvetliakov.vscode-neovim": 1
    },
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.inlayHints.pytestParameters": true,
    "python.testing.pytestEnabled": true,
    "git.autofetch": true,
}
```

**Comment by qmmp123** [comment] 2023-12-21 13:33
Did you open project as workspace?
![image](https://github.com/microsoft/pylance-release/assets/6360702/d8a97827-4bdd-44b2-9f7a-bc1d8a653ee6)

**Comment by yakkle** [comment] 2023-12-25 14:38
@debonte I will try with `2023.12.100`. thanks.

**Comment by yakkle** [comment] 2023-12-26 00:42
@debonte 

I've tested it with the `2023.12.100` and `2023.12.101` prerelease versions and it works fine.
However, looking at the [changelog](https://github.com/microsoft/pylance-release/blob/b07167f903f16c65012b1589aecff936b7b365b5/CHANGELOG.md#202312100-14-december-2023-prerelease), I'm not sure which issue fix made it work.

**Closed** 2024-01-03 20:23 UTC
Labels: bug
