### ISSUE TITLE
False positive reportUndefinedVariable

### ISSUE THREAD

**Issue by janosh** [microsoft/pylance-release#417] opened 2020-09-25 08:33 UTC
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: 10.15.7
-   Python version: 3.8.5

```py
from torch.nn import functional as F
```

In the above import, `functional` is red-underlined with the error

```
(module) functional
"functional" is not definedPylance (reportUndefinedVariable)
```

![false-error](https://user-images.githubusercontent.com/30958850/94245447-8c854c00-ff1a-11ea-8f80-8d7ce996af5e.png)

**Comment by huguesv** [comment] 2020-09-25 16:13
Duplicate of https://github.com/microsoft/pylance-release/issues/376
It is fixed for the next release

**Closed by huguesv** 2020-09-25 16:13 UTC
Labels: triage
