### ISSUE TITLE
already install Pylance but python.languageserver setting no exsit Pylance option

### ISSUE THREAD

**Issue by joewen85** [microsoft/pylance-release#145] opened 2020-07-20 15:34 UTC
-   Language Server version: XXX
-   OS and version: Mac os 10.15.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.6

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9345083/87956172-4ad2c200-cae1-11ea-930f-b412418f1e42.png">

i test delete all vscode app and user setting, reinstall vscode and extension, but still problem

**Comment by judej** [comment] 2020-07-20 17:46
Duplicate of #16

**Closed by judej** 2020-07-20 17:46 UTC
