### ISSUE TITLE
type checking error with numpy

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/pylance-release#304] opened 2020-09-01 09:30 UTC
Issue Type: <b>Bug</b>

The code runs well but get error report.

![image](https://user-images.githubusercontent.com/57612792/91832828-7caa7d00-ec78-11ea-9e6d-52ed562ae6e3.png)

Extension version: 2020.8.3
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4091)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (7.98GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/Desktop/Physics.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by qiansen1386** [comment] 2020-09-01 14:56
And also how to set python.analysis.extraPaths? It's so frustrating... 
For instance, should I put 
```
~/.local/lib/python3.8/site-packages/
```
or 
```
~/.local/bin
```
or 
```
~/.local/lib/python3.8/site-packages/numpy
```

**Comment by jakebailey** [comment] 2020-09-01 17:41
Duplicate of #150. The next numpy release should contain stubs to help with the quality of our numpy analysis.

**Closed by jakebailey** 2020-09-01 17:41 UTC
Labels: triage
