### ISSUE TITLE
Offer different pylance modes to enable light vs full IntelliSense experience    

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#5434] opened 2024-02-01 18:13 UTC
Right now we can tweak settings such as enabling/disabling indexing, changing indexing limit, packageIndexDepths etc to decrease/increase the amount of resources that are used (https://github.com/microsoft/pylance-release/wiki/Pylance-Configuration-Tips), which also impacts the type of information we are able to offer as part of our IntelliSense features. It'd be nice if we had different language service "modes" (e.g. `lightweight` - only supports editor related features with minimum stuff enabled, `default` for what we do now, and `full` which indexes as much as we can and enable expensive features on by default)  that users can change depending on what they want and need.

**Comment by heejaechang** [comment] 2024-02-13 19:08
this will require some groundwork before doing this work.

1. resolve indexing perf regression we are having (or improve it better than before)
2. support requirements.txt and pyproject.toml to limit how much we index, show in completion and etc in full mode (otherwise, it will be too much)
3. support alias in user files's indexing (we have cut it due to perf issue)

**Comment by heejaechang** [comment] 2024-04-15 21:10
`1. resolve indexing perf regression we are having (or improve it better than before)` 

this has been handled by https://github.com/microsoft/pyrx/pull/5007 and https://github.com/microsoft/pyright/pull/7652

**Comment by luabud** [comment] 2024-06-25 19:06
One idea inspired by cases like https://github.com/microsoft/pylance-release/issues/6055 is to have `lightweight` mode disable workspace wide features, and offer open file support only

**Comment by heejaechang** [comment] 2024-06-27 17:39
there is another issue that UX could be improved by light mode - https://github.com/microsoft/pylance-release/issues/5881

**Comment by heejaechang** [comment] 2024-07-09 18:02
another PR related to this issue - https://github.com/microsoft/pyrx/pull/5437

**Comment by nineteendo** [comment] 2024-07-09 20:03
Did you mean: https://github.com/microsoft/pyright/issues/5437?

**Comment by heejaechang** [comment] 2024-07-23 22:12
@nineteendo no, that's not related to this work. might be related to something @debonte working on that's about doc annotation?

**Comment by nineteendo** [comment] 2024-07-24 06:35
Is microsoft/pyrx just a private repo?

**Comment by rchiodo** [comment] 2024-07-24 16:37
> Is microsoft/pyrx just a private repo?

Yes it's the source location for Pylance. Which is based on Pyright.

**Comment by heejaechang** [comment] 2024-07-30 22:54
we should enhance indexing experience such as this - https://github.com/microsoft/pylance-release/issues/6209#issuecomment-2259012941 - to make full mode indexing works better.

**Comment by noklam** [comment] 2024-08-05 15:22
What's the progress on this issue? As a library/extension developer, I would like to set the index depth automatically. 

I've read most of the related thread, I think reading requirements.txt/pyproject.toml is a sensible default (And the source code of current project of course).

As temporary workaround, If I want to change this settings in a VS Code extension, is it possible? I may able to override the default but what I want is merge with the exist PyLance settings and I am not sure how it will works.

For example, if an user have default `Flask` and `Django` will index with depth 2, when he/she also installed `Kedro` extension, I'd like it to add `kedro` index with depth 2 automatically. Is something like this possible?

**Comment by heejaechang** [comment] 2024-08-05 17:35
@noklam I am working on it. if you have suggestion, leaving it here will help us designing the feature.

**Comment by KacieKK** [comment] 2024-11-19 22:12
This issue has been fixed in prerelease version 2024.11.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202411101-18-November-2024-PreRelease)

**Closed by KacieKK** 2024-11-19 22:12 UTC
Labels: enhancement, fixed in next version (main)

**Comment by noklam** [comment] 2025-01-17 16:38
Sorry I am late to the conversation as I didn't get the notification from GitHub. I see there are some progress on this, but most of it seems to coming from a regular user perspective. 

As a extension developer, do we have any control over this or the only solution is to ask user to manually updating settings? My goal here is that, I want the user that installed my extension, will automatically index the corresponding libraries. I understand this may cause conflict when user choose to index it "light", but the extension may choose to index fully. Is there an API for developer to merge settings or at least try to resolve/surface the conflicts?
