### ISSUE TITLE
Folding not working properly

### ISSUE THREAD

**Issue by jerryc05** [microsoft/pylance-release#4408] opened 2023-05-23 10:24 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Create a file like this
```py
from pathlib import Path

with Path(
    "veryloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong"
).open("r", encoding="utf-8") as f:
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())
    print(f.read())

```

and then try to fold this block on line 5 so that line 5 to 22 will be folded, but it did not pop up the button for the user to fold

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.3
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2023.9.11251005
VS Code version: Code - Insiders 1.79.0-insider (f6be5461f8bc69013a605f5baea834651c6589fb, 2023-05-20T01:18:53.811Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by debonte** [comment] 2023-05-23 20:57
Thanks for the issue. This is a duplicate of https://github.com/microsoft/pylance-release/issues/4036.

**Closed by debonte** 2023-05-23 20:57 UTC
Labels: duplicate
