### ISSUE TITLE
Auto-complete function brackets and Syntax highlighting not working

### ISSUE THREAD

**Issue by SuperCoder-01** [microsoft/pylance-release#3836] opened 2023-01-14 14:21 UTC
Type: <b>Bug</b>

# Video link
You can see the bug recorded in video form [here](https://clipchamp.com/watch/rGWot8l4fbJ). (Read the following to get more context)

## Expected result
When I use auto-complete (Intellisense) to help me complete a function, built-in or user-defined, it should automatically add the parenthesis.
I already enabled the "python.analysis.completeFunctionParens".

## Actual result
It completes the function name but does not add the parenthesis.

### How to get around it
I have found a way to get around it. If I disable the Pylance extension and reload the window, then enable it again, it auto-completes the function parenthesis. However, the syntax highlighting is messed up.

How can I get both the auto-complete function parenthesis and the syntax highlighting at the same time?

### Version
_VSCode_
Version: 1.75.0-insider (user setup)
Commit: 243854703b7fa371abb752ec0df7817a615a308b
Date: 2023-01-13T07:48:05.934Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

_Pylance_
Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
**Version: 2023.1.21**
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

Extension version: 2023.1.21
VS Code version: Code - Insiders 1.75.0-insider (243854703b7fa371abb752ec0df7817a615a308b, 2023-01-13T07:48:05.934Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.78GB free)|
|Process Argv|--crash-reporter-id 10ff7c4b-c688-4270-bff2-e82107a989a7|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by rchiodo** [comment] 2023-01-17 16:53
This should be a dupe of https://github.com/microsoft/pylance-release/issues/3831

**Closed by rchiodo** 2023-01-17 16:53 UTC
Labels: triage-needed
