### ISSUE TITLE
Broken code folding

### ISSUE THREAD

**Issue by blaylockbk** [microsoft/pylance-release#2269] opened 2022-01-20 23:54 UTC
There are a few cases in which code folding that was once available now appears broken.

## Environment data

-   Language Server version: v2022.1.1 (Pylance language server 2022.1.1 (pyright 4f61d443))
-   OS and version: Windows 10 PC, VS Code 1.63.2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9 anaconda

## Expected behaviour
When I turn off the python/pylance extension, I get code folding where I expect it for dictionaries and multi-line function arguments (per Black formatting).
![image](https://user-images.githubusercontent.com/6249613/150440034-59ebc1c2-9b3e-47c1-9f9d-3be418466485.png)

## Actual behaviour
When the python/pylance extension is turned on, the code folding is unavailable for multi-line dictionaries created with the `{'key':'value'}` notation and for multi-line function arguments.
![image](https://user-images.githubusercontent.com/6249613/150439756-fcdd5e2a-0f95-4dce-9d55-a32f5f0acf52.png)

**Comment by debonte** [comment] 2022-01-21 00:59
Thanks @blaylockbk, the dict issue will be fixed in our next release.

For function folding, I'm considering three options:
1. **The old behavior** -- The arguments and function body are separately collapsible. If you want to collapse both, you need to toggle both ^ icons. This is how C# folding works.
2. **Typescript's behavior** -- Only one folding icon on the def line (line 18 below). Toggling it collapses the entire function -- arguments and body, just showing line 18.
3. **Old toggle locations, but line 18 collapses the entire function** -- So in the example below, you'd still see folding icons on both line 18 and line 22, but folding line 18 would collapse the entire function rather than just the arguments. Folding line 22 would collapse the body as it does today.

Your "expected behavior" above is # 1, but is that really what you want? The fact that collapsing the whole function requires two clicks seems awkward to me. For what it's worth, we generally copy TypeScript's behavior on things of this sort.

![image](https://user-images.githubusercontent.com/12820898/150444603-9316354a-fca9-4670-a39c-e8e6b485d963.png)

**Comment by blaylockbk** [comment] 2022-01-21 03:49
Glad to hear about the fix for dict folding 🎉

Function folding: I always wished it did option 2 instead. It's only my opinion, but I might prefer option 3.

**Comment by debonte** [comment] 2022-01-21 04:00
Ok, I'm going to go with 2 for now since that's how TypeScript behaves. We can always switch to 3 in the future if we get more feedback.

**Comment by debonte** [comment] 2022-01-25 02:26
This will be fixed in the next release.

**Closed** 2022-01-26 19:09 UTC
Labels: enhancement, fixed in next version

**Comment by lzkelley** [comment] 2022-02-09 00:33
I'm still getting the same behavior for functions in v2022.2.0, where there are two folding icons, and the top level (function definition line) folding icon does *not* fold the full function, only the argument list.

![Screen Shot 2022-02-08 at 6 32 54 PM](https://user-images.githubusercontent.com/3839265/153099186-9aa2a23f-b093-482d-b665-69c11c6088b6.png)

**Comment by Irmitya** [comment] 2022-03-09 20:47
> For function folding, I'm considering three options:
> 
> ![image](https://user-images.githubusercontent.com/12820898/150444603-9316354a-fca9-4670-a39c-e8e6b485d963.png)

I prefer `#1`.  `#3` can be done by just changing the end's indentation. 
`#1` allows splitting different blocks of code and comments/notes, instead of leaving the only option of minimizing them to be minimizing the whole function.

**Comment by debonte** [comment] 2022-03-09 21:06
> #3 can be done by just changing the end's indentation.

What do you mean by "the end"?

> #1 allows splitting different blocks of code and comments/notes, instead of leaving the only option of minimizing them to be minimizing the whole function.

@Irmitya can you show me an example?

**Comment by Irmitya** [comment] 2022-03-09 21:26
```py
def func1(
    vars  # Fold me
): 
    pass  # Don't fold me with vars

def func2(
    vars  # Fold me
    ):
    pass  # Same column, fold us

def func3(
        vars  # Fold me
    ):
    pass  # We shouldn't fold because different column but it's okay to fold us
```

option 3 disallows function 1.  
option 2 just treats everything like function 2/3

function 3 behaves as function 2, and is for someone that just doesn't like function 2's alignment.
It does not work like I'd expect, in option 1, which is to only fold the variable line, due to it's indentation, which would make it ideally an option 4 but I'm okay with it working as option 1

**Comment by debonte** [comment] 2022-03-10 00:54
>which is to only fold the variable line, due to it's indentation

Thanks for the explanation. However, in my mind, functions should all fold the same way regardless of the indentation of the parameters or ending `):`, and that is the current behavior.

It seems confusing that two functions whose only difference is their parameter formatting would fold differently, especially since that formatting difference may well have been unintentional. And we definitely don't want users to feel compelled to change their coding style simply to get different folding behavior.

I understand that Pylance used to make folding decisions strictly based on indentation, but that was because it was easy to implement not because we felt it was desirable.

Feel free to open a new issue for the behavior you want. We will consider it based on feedback/up-votes from other users.
