### ISSUE TITLE
highlight `__something__` as a variable

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1657] opened 2021-08-10 08:49 UTC
I hope that module attributes are highlighted like variables. As you can see, they are just white.
![屏幕截图 2021-08-10 164512](https://user-images.githubusercontent.com/62426149/128837254-67835fbf-ff58-41f0-a592-ee3ea1cdc18c.png)

**Comment by jakebailey** [comment] 2021-08-10 17:48
Duplicate of #964.

**Closed by jakebailey** 2021-08-10 17:48 UTC
Labels: triage
