### ISSUE TITLE
Syntax highlighting broken in regex+format strings

### ISSUE THREAD

**Issue by sparr** [microsoft/pylance-release#5089] opened 2023-11-05 14:14 UTC
Type: <b>Bug</b>

```python
foo = r'(?P<foo>as)df'
bar = rf'(?P<foo>{as}df)'
```

This highlights the second string as only a format string, with coloring for `{}` and `as`. The highlights for a regex string are lost, as noted by all the other text being the same plain string contents color rather than the regex syntax colors for `?P<foo>` and `df`. (github doesn't understand `r''` at all, so please ignore the highlighting in this issue itself)

Extension version: 2023.20.0
VS Code version: Code - OSS 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-06T10:42:02.233Z)
OS version: Linux x64 5.10.194-1-MANJARO
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4047)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.37GB (4.10GB free)|
|Process Argv|factorio/mods/factorio-mod-entity-symmetry|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by debonte** [comment] 2023-11-06 18:07
Dupe of https://github.com/microsoft/pylance-release/issues/5050?

**Comment by sparr** [comment] 2023-11-06 20:37
Oddly it seems to be backwards. I get regex highlighting in `r` and format highlighting but not regex in `rf`

**Comment by StellaHuang95** [comment] 2023-11-09 20:14
closing it as a dupe of https://github.com/microsoft/pylance-release/issues/5050, and also make it a sub item of bigger work (shipping textmate grammar ourselves - https://github.com/microsoft/pyrx/issues/4026)

**Closed by StellaHuang95** 2023-11-09 20:14 UTC
Labels: duplicate, fixed in next version (main), textmate bug

**Comment by sparr** [comment] 2023-11-09 20:44
This is fixed in MagicPython but hasn't made it into the VSCode Python extension yet.
https://github.com/MagicStack/MagicPython/commit/5b5f388fc46e45dff7e48edc90242c7f578d8705
