### ISSUE TITLE
Pylance should include Pyright configurations in its description

### ISSUE THREAD

**Issue by Ovsyanka83** [microsoft/pylance-release#755] opened 2020-12-20 13:37 UTC
Pylance is based on pyright and, as far as I've tested, all of pyright configurations work on pylance. But there is no description indicating these extra configurations on this github page or on visualstudio marketplace. Hence the only way to actually find out about these configurations is to go to this github page, follow the link to pyright and guess that pylance will support all of them.

At least for me it made them essentially undocumented. I believe that it would be great to add a short description of pyright configurations to the visualstudio marketplace and this github page.

**Comment by bschnurr** [comment] 2021-09-23 19:12
duplicate of https://github.com/microsoft/pylance-release/issues/688

**Closed by bschnurr** 2021-09-23 19:12 UTC
Labels: needs documentation, duplicate
