### ISSUE TITLE
DOUBLE language server started in vscode with conda

### ISSUE THREAD

**Issue by Fadelis98** [microsoft/pylance-release#3042] opened 2022-07-14 09:06 UTC
<h3> Environment data </h3>

-   Language Server version: 2022.7.30
-   OS and version: linux x64
-   Python version :3.7 in anaconda env named 'scf'
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

Reproduce: just open any python file, then 2 different language servers started

![image](https://user-images.githubusercontent.com/43640976/178945685-ca14af7b-4410-488a-a13f-195fc0ddc153.png)

the hint is doubled as well

![image](https://user-images.githubusercontent.com/43640976/178946039-e9a5a75f-af4e-48ee-8ebf-5c331036bb1a.png)

**Comment by Fadelis98** [comment] 2022-07-14 11:04
I find it is the same as #3027

**Comment by maxwellzh** [comment] 2022-07-19 05:08
same issue here.

**Comment by dtczest** [comment] 2022-08-01 20:31
Also having this issue

**Comment by Fadelis98** [comment] 2022-08-10 09:13
More information: This bug happens after both .py file and  .ipynb notebook are opened. It seems that the pylance server starts for each type of file once, but each server finally acts on both types of files.

**Comment by SimonL888** [comment] 2022-08-18 07:32
same issue on windows 11

**Comment by cyclux** [comment] 2022-11-05 01:13
Had the same issue. The suggestion from https://github.com/microsoft/pylance-release/issues/3027 -> "python.pylanceLspNotebooksEnabled: true" seems to have solved it for me.

**Comment by debonte** [comment] 2022-11-05 01:19
> Had the same issue. The suggestion from https://github.com/microsoft/pylance-release/issues/3027 -> python.pylanceLspNotebooksEnabled: true seems to have solved it for me.

@Fadelis98, do you have `python.pylanceLspNotebooksEnabled` set to `false`?

**Comment by cyclux** [comment] 2022-11-05 17:35
> > Had the same issue. The suggestion from #3027 -> python.pylanceLspNotebooksEnabled: true seems to have solved it for me.
> 
> @Fadelis98, do you have `python.pylanceLspNotebooksEnabled` set to `false`?

No, I set it to `true` . In another post you said the default is `true` now. Wondering why including `pylanceLspNotebooksEnabled` changed anything then, because I did not see this option anywhere before, so it should have been set to `true` anyway. You also said the default is depending on the implementation, maybe that's why. However, my setup should be up to date, including extensions. (btw: I'm using conda and Jupyter as well)

**Comment by Kerybas** [comment] 2022-11-07 10:17
I have the same issue but I don't find `python.pylanceLspNotebooksEnabled` in my settings.  
I added this in a workspace settings.json but that doesnt change anything:
```
{
    "python.pylanceLspNotebooksEnabled": true
}
```

**Comment by cyclux** [comment] 2022-11-07 13:54
> I have the same issue but I don't find `python.pylanceLspNotebooksEnabled` in my settings. I added this in a workspace settings.json but that doesnt change anything:
> 
> ```
> {
>     "python.pylanceLspNotebooksEnabled": true
> }
> ```
> 
> Additionally, how can I stop a language server?

That's exactly what I did.
Did not try to stop a running one. But you can try `"python.languageServer": "None"` as a "hotfix" until a decent solution works for you.

**Comment by debonte** [comment] 2022-11-07 20:13
May be related to / dupe of https://github.com/microsoft/vscode-jupyter/issues/11938

**Comment by rchiodo** [comment] 2022-11-07 20:51
An indicator that this problem is caused by the jupyter issue is this shows up in the jupyter output tab:

```
LSP Notebooks experiment is disabled -- not in treatment group
```

If you see that, you should switch to the Jupyter prerelease version.
```

**Comment by raulguarini** [comment] 2022-11-15 18:07
I have discovered that disabling the Pylance extension from within VSCode fixes it. I still get the suggestions from the Language Protocol.

I might be totally wrong, but I think this started after the Python extension was "decoupled" and Pylance and isort became separate ones.

**Comment by Fadelis98** [comment] 2022-11-17 04:25
I've tried some of the solutions above, but this bug still exists. My solution is to keep both notebook and python files opened in workplace, and restart vscode, then only one language server started.

**Comment by debonte** [comment] 2022-11-17 23:42
@raulguarini, @Fadelis98, have you tried the pre-release version of the Jupyter extension?

**Comment by Fadelis98** [comment] 2022-11-18 04:46
> @raulguarini, @Fadelis98, have you tried the pre-release version of the Jupyter extension?

Not yet, I'll try it later

**Comment by debonte** [comment] 2022-11-18 17:56
There was an issue with similar behavior that was fixed in the Jupyter extension recently. Please try their latest pre-release build and see if that fixes this for you.

**Comment by kylebarron** [comment] 2022-12-08 18:33
I was able to update to 1.74.0 (released today?) which fixed it without switching to the insiders build

**Closed** 2023-04-12 18:08 UTC
Labels: needs investigation
