### ISSUE TITLE
"Code is unreachable" for reachable code

### ISSUE THREAD

**Issue by chilipepperpizza** [microsoft/pylance-release#6021] opened 2024-06-17 16:14 UTC
## Environment data

-   Language Server version: v2024.6.1
-   OS and version: Windows 10 Enterprise Build 19045
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7

## Code Snippet

```python
def test(arg1: str = None, arg2 = False):
    if arg2:
        print('Made it this far')
        return
    elif arg1 is not None:
        print('Made it to here')
        return

    print('Made it all the way')

test()
#>>> Made it all the way
```

## Repro Steps

1. Have a function with a basic if-elseif statement checking argument conditions with returns.

![Pylance Incorrect Unreachable Code Error](https://github.com/microsoft/pylance-release/assets/67929330/1cac1db8-d9ea-4160-91cd-cecdfe32c022)

## Expected behavior

This error shouldn't appear for code after the if statement.

## Actual behavior

Despite the default values for arguments, it still says any code beyond the if statement is unreachable.

## Logs

```
2024-06-17 12:00:06.927 [info] (Client) Pylance async client (2024.6.1) started with python extension (2024.8.1)
2024-06-17 12:00:08.388 [info] [Info  - 12:00:08 PM] (17708) Pylance language server 2024.6.1 (pyright version 1.1.364, commit 0618acc5) starting
2024-06-17 12:00:08.389 [info] [Info  - 12:00:08 PM] (17708) Server root directory: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist
2024-06-17 12:00:08.400 [info] [Info  - 12:00:08 PM] (17708) Starting service instance "Test"
2024-06-17 12:00:08.480 [info] Auto-Indent enabled
2024-06-17 12:00:08.509 [info] Auto-Indent enabled
2024-06-17 12:00:08.511 [info] (17708) No configuration file found.
2024-06-17 12:00:08.512 [info] (17708) No pyproject.toml file found.
2024-06-17 12:00:08.512 [info] [Info  - 12:00:08 PM] (17708) Setting pythonPath for service "Test": "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\python.exe"
2024-06-17 12:00:08.512 [info] [Info  - 12:00:08 PM] (17708) Setting environmentName for service "Test": "3.10.7 (global)"
2024-06-17 12:00:08.834 [info] [Info  - 12:00:08 PM] (17708) Assuming Python version 3.10.7.final.0
2024-06-17 12:00:08.834 [info] (17708) Assuming Python platform Windows
2024-06-17 12:00:09.201 [info] [Info  - 12:00:09 PM] (17708) Search paths for file:///c%3A/Temp/Test
2024-06-17 12:00:09.206 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\.vscode\extensions\ms-python.vscode-pylance-2024.6.1\dist\typeshed-fallback\stdlib
2024-06-17 12:00:09.207 [info] [Info  - 12:00:09 PM] (17708)   c:\Temp\Test
2024-06-17 12:00:09.207 [info] [Info  - 12:00:09 PM] (17708)   c:\Temp\Test\typings
2024-06-17 12:00:09.207 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\.vscode\extensions\ms-python.vscode-pylance-2024.6.1\dist\typeshed-fallback\stubs\...
2024-06-17 12:00:09.207 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\.vscode\extensions\ms-python.vscode-pylance-2024.6.1\dist\bundled\stubs
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\DLLs
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\Lib
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\Lib\site-packages
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Program Files (x86)\Cyme\CYME 8.1.3
2024-06-17 12:00:09.208 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\Lib\site-packages\win32
2024-06-17 12:00:09.209 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\Lib\site-packages\win32\lib
2024-06-17 12:00:09.209 [info] [Info  - 12:00:09 PM] (17708)   c:\Users\USERNAME\AppData\Local\Programs\Python\Python310\Lib\site-packages\pythonwin
2024-06-17 12:00:09.209 [info] [Info  - 12:00:09 PM] (17708) Adding fs watcher for library directories:
 file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/DLLs
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages
file:///c%3A/Program%20Files%20%28x86%29/Cyme/CYME%208.1.3
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/win32
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/win32/lib
file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/pythonwin
2024-06-17 12:00:09.209 [info] [Info  - 12:00:09 PM] (17708) Adding fs watcher for directories:
 file:///c%3A/Temp/Test
2024-06-17 12:00:09.209 [info] (17708) Searching for source files
2024-06-17 12:00:09.297 [info] (17708) Found module pdfminer : 20191125
2024-06-17 12:00:09.297 [info] (17708) Found module pip : 22.2.2
2024-06-17 12:00:09.298 [info] (17708) Found module setuptools : 63.2.0
2024-06-17 12:00:09.298 [info] [Info  - 12:00:09 PM] (17708) Found 1 source file
2024-06-17 12:00:09.301 [info] (17708) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-06-17 12:00:09.305 [info] Auto-Indent enabled
2024-06-17 12:00:09.308 [info] (17708) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-06-17 12:00:09.425 [info] (17708) Attempting to resolve using local imports: __builtins__
2024-06-17 12:00:09.430 [info] (17708) [FG] parsing: file:///c%3A/Temp/Test/test.py (116ms)
2024-06-17 12:00:09.564 [info] (17708) [FG] parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 4ms] (125ms)
2024-06-17 12:00:09.659 [info] (17708) [FG] binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/builtins.pyi (93ms)
2024-06-17 12:00:09.660 [info] (17708) [FG] binding: file:///c%3A/Temp/Test/test.py (1ms)
2024-06-17 12:00:09.670 [info] [Info  - 12:00:09 PM] (17708) Background analysis(1) root directory: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist
2024-06-17 12:00:09.671 [info] [Info  - 12:00:09 PM] (17708) Background analysis(1) started
2024-06-17 12:00:09.901 [info] (17708) Found module pdfminer : 20191125
2024-06-17 12:00:09.901 [info] (17708) Found module pip : 22.2.2
2024-06-17 12:00:09.904 [info] (17708) Found module setuptools : 63.2.0
2024-06-17 12:00:09.971 [info] (17708) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-06-17 12:00:10.066 [info] (17708) Attempting to resolve using local imports: __builtins__
2024-06-17 12:00:10.071 [info] (17708) [BG(1)] analyzing: file:///c%3A/Temp/Test/test.py ...
2024-06-17 12:00:10.072 [info] (17708) [BG(1)]   parsing: file:///c%3A/Temp/Test/test.py (103ms)
2024-06-17 12:00:10.178 [info] (17708) [BG(1)]   parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (104ms)
2024-06-17 12:00:10.232 [info] (17708) [BG(1)]   binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/builtins.pyi (50ms)
2024-06-17 12:00:10.232 [info] (17708) [BG(1)]   binding: file:///c%3A/Temp/Test/test.py (2ms)
2024-06-17 12:00:10.284 [info] (17708) [BG(1)]   checking: file:///c%3A/Temp/Test/test.py ...
2024-06-17 12:00:10.287 [info] (17708) [BG(1)]     parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (29ms)
2024-06-17 12:00:10.290 [info] (17708) [BG(1)]     binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/typing.pyi (14ms)
2024-06-17 12:00:10.334 [info] (17708) [BG(1)]     parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 3ms] (17ms)
2024-06-17 12:00:10.341 [info] (17708) [BG(1)]     binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/types.pyi (7ms)
2024-06-17 12:00:10.373 [info] (17708) [BG(1)]     parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (11ms)
2024-06-17 12:00:10.373 [info] (17708) [BG(1)]     binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (4ms)
2024-06-17 12:00:10.385 [info] (17708) [BG(1)]     parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 1ms] (2ms)
2024-06-17 12:00:10.386 [info] (17708) [BG(1)]     binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/abc.pyi (2ms)
2024-06-17 12:00:10.420 [info] (17708) [BG(1)]     parsing: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (8ms)
2024-06-17 12:00:10.426 [info] (17708) [BG(1)]     binding: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (6ms)
2024-06-17 12:00:10.470 [info] (17708) [BG(1)]   checking: file:///c%3A/Temp/Test/test.py (237ms)
2024-06-17 12:00:10.471 [info] (17708) [BG(1)] analyzing: file:///c%3A/Temp/Test/test.py (501ms)
2024-06-17 12:00:10.496 [info] (17708) [BG(1)] SemanticTokens range 0:0 - 10:6 at file:///c%3A/Temp/Test/test.py (5ms)
2024-06-17 12:00:10.496 [info] (17708) [BG(1)] SemanticTokens full at file:///c%3A/Temp/Test/test.py (1ms)
2024-06-17 12:00:10.496 [info] (17708) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-06-17 12:00:10.511 [info] (17708) [BG(1)] indexing: file:///c%3A/Temp/Test/test.py [found 1] (1ms)
2024-06-17 12:00:10.511 [info] (17708) Indexing Done: file:///c%3A/Temp/Test/test.py
2024-06-17 12:00:10.598 [info] [Info  - 12:00:10 PM] (17708) Indexer background runner(2) root directory: file:///c%3A/Users/USERNAME/.vscode/extensions/ms-python.vscode-pylance-2024.6.1/dist (index)
2024-06-17 12:00:10.601 [info] [Info  - 12:00:10 PM] (17708) Indexing(2) started
2024-06-17 12:00:10.978 [info] (17708) [IDX(2)] scan packages file:///c%3A/Temp/Test ...
2024-06-17 12:00:10.979 [info] (17708) [IDX(2)]   read stdlib indices (25ms)
2024-06-17 12:00:11.782 [info] (17708) [IDX(2)] scan packages file:///c%3A/Temp/Test (828ms)
2024-06-17 12:00:11.782 [info] [Info  - 12:00:11 PM] (17708) scanned(2) 22 files over 1 exec env
2024-06-17 12:00:11.810 [info] (17708) [BG(1)] SemanticTokens delta previousResultId:1718640010476 at file:///c%3A/Temp/Test/test.py (0ms)
2024-06-17 12:00:12.085 [info] (17708) [IDX(2)] index packages file:///c%3A/Temp/Test ...
2024-06-17 12:00:12.085 [info] (17708) [IDX(2)]   index execution environment file:///c%3A/Temp/Test ...
2024-06-17 12:00:12.086 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/concurrent/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.086 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/distutils/__init__.py [skipped: no '__all__' defined] (1ms)
2024-06-17 12:00:12.086 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/idlelib/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.086 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/lib2to3/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.087 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/pydoc_data/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.087 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/test/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.087 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/turtledemo/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.088 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/urllib/__init__.py [skipped: no '__all__' defined] (1ms)
2024-06-17 12:00:12.088 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/wsgiref/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.088 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/xmlrpc/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.089 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/adodbapi/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.089 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/pdfminer/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.089 [info] (17708) [IDX(2)]     indexing: file:///c%3A/Users/USERNAME/AppData/Local/Programs/Python/Python310/Lib/site-packages/pythonwin/pywin/__init__.py [skipped: no '__all__' defined] (0ms)
2024-06-17 12:00:12.093 [info] (17708) [IDX(2)]   index execution environment file:///c%3A/Temp/Test [found 848 in 9 files] (12ms)
2024-06-17 12:00:12.093 [info] (17708) [IDX(2)] index packages file:///c%3A/Temp/Test [found 848 in 1 exec envs] (23ms)
2024-06-17 12:00:12.094 [info] [Info  - 12:00:12 PM] (17708) indexed(2) 9 files over 1 exec env
2024-06-17 12:00:12.124 [info] [Info  - 12:00:12 PM] (17708) Indexing finished(2).
```

**Comment by rchiodo** [comment] 2024-06-17 16:22
Thanks for your issue. This is by design. You're not fully typing your function. From the typechecker's perspective, argument a can never be none because you assigned it type `str`.

This code would fix the problem:

```python
def test(arg1: str | None = None, arg2 = False):
    if arg2:
        print('Made it this far')
        return
    elif arg1 is not None:
        print('Made it to here')
        return

    print('Made it all the way')

test()
```

or this:

```python
def test(arg1 = None, arg2 = False):
    if arg2:
        print('Made it this far')
        return
    elif arg1 is not None:
        print('Made it to here')
        return

    print('Made it all the way')

test()
```

If you switch to `typeCheckingMode=basic`, Pylance will actually show an error on your original function definition:

![image](https://github.com/microsoft/pylance-release/assets/19672699/9c74ecc7-49cc-424a-9ad9-52f78fcb06c2)

**Closed by rchiodo** 2024-06-17 16:22 UTC
Labels: needs repro

**Comment by chilipepperpizza** [comment] 2024-06-17 16:29
Ah that makes sense, did not know it was looking for nullability to be explicitly specified. Thanks for the heads up on the typecheckingmode setting.
