### ISSUE TITLE
Best effort behavior based on the current directory like c# microsoft python language server.

### ISSUE THREAD

**Issue by smekkley** [microsoft/pylance-release#1312] opened 2021-05-19 20:05 UTC
I hope the title is self-explanatory but here is how to check such behavior.

1. git clone https://github.com/Yggdroot/LeaderF.git
2. cd LeaderF/autoload/leaderf/python/leaderf
3. Open cli.py
4. Try to find references of `def input(self, callback)` method.
5. Pyright doesn't suggest reference from the other file(manager.py) but c# microsoft python language server does.  
 
The best effort behavior should probably happen only when pyproject.toml or equivalent isn't available.

**Comment by jakebailey** [comment] 2021-05-19 20:19
You can read our FAQ here: https://github.com/microsoft/pylance-release/blob/main/FAQ.md#what-is-the-relationship-between-pylance-pyright-and-the-python-extension

We handle most issues related to editor functionality in this repo; the other repo is largely type checker changes. It's more than a "wrapper".

**Comment by smekkley** [comment] 2021-05-20 08:00
That's a shame, I hope this feature gets incorporated to pyright as well. Thanks for the explanation.

**Comment by jakebailey** [comment] 2021-05-20 16:56
This wasn't a statement of where the code lives, just which issue tracker is used and who typically works on implementing it.

In your case, this sounds more like a bug than anything, but we'd need to clone your example to test and see.

**Comment by smekkley** [comment] 2021-05-20 17:33
Ok. I misunderstood, pyright only being type checker and language server functions like find references get first incorporated in pylance.  Thank you for clearing it up.
  
Yeah, it could be called a bug. I thought pyproject.toml is a requirement.  
What would be nicer is that it first try pyproject.toml, then current directory, and then the directory of the file as root. The last feature is something even c# microsoft python language server doesn't have.

**Comment by heejaechang** [comment] 2021-05-20 18:04
I opened vscode in "LeaderF/autoload/leaderf/python/leaderf" and did "find all references" and it works as expected.

![find all references](https://user-images.githubusercontent.com/1333179/119027243-f5fb1480-b95a-11eb-91ac-fadd7d85bc01.gif)

by the way, did you open just cli.py or opened folder "LeaderF/autoload/leaderf/python/leaderf"?

**Comment by jakebailey** [comment] 2021-05-20 18:05
Since this issue was transferred, I don't think that this came from VS Code. I don't know what other editors do, but this would likely be a dupe of #1301.

**Comment by smekkley** [comment] 2021-05-20 22:30
@heejaechang Thanks a lot for immediately confirming! 
Yes, it looks like a dupe of #1301. I guess this issue can be closed. Thank you all for such a prompt responses even though I'm a personal pyright user.  
I'm happy to try making a patch btw.

**Closed** 2021-05-20 22:32 UTC
Labels: waiting for user response
