### ISSUE TITLE
Wrong code highlight

### ISSUE THREAD

**Issue by wangkechun** [microsoft/pylance-release#486] opened 2020-10-13 10:22 UTC
## Environment data

-   VS Code version:  1.50.0
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: OSX 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Actual behaviour

![image](https://user-images.githubusercontent.com/4022174/95848323-7b449800-0d80-11eb-83d5-1045d15666a9.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by judej** [comment] 2020-10-13 17:58
@wangkechun, was the file in this state when you opened it? Or was this after edit? 
Also, would you please navigate to the token that is incorrect and "inspect editor tokens and scopes" (from the command palette?

**Comment by wangkechun** [comment] 2020-10-14 09:23
No file edited.
Maybe after switching git branch or switching tabs multiple times.
I can’t reproduce this problem stably now, next time I reproduce it, I will try "inspect editor tokens and scopes"

**Comment by wangkechun** [comment] 2020-10-19 08:31
cc @judej

**Comment by savannahostrowski** [comment] 2020-11-19 21:29
It looks like this problem is no longer reproducible and hasn't been updated in 30 days. I'm going to close this ticket but if you run into this issue again, please re-open.

**Closed by savannahostrowski** 2020-11-19 21:29 UTC
Labels: waiting for info
