### ISSUE TITLE
missing member(s) of module numpy

### ISSUE THREAD

**Issue by iori-ichinose** [microsoft/pylance-release#208] opened 2020-08-07 09:44 UTC
## Environment data

-   Language Server version: v2020.8.0
-   OS and version: Arch Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3

## Expected behaviour

When pylance is disabled, there's no error. The script runs normally.

## Actual behaviour
![pylance_numpy](https://user-images.githubusercontent.com/58081463/89632430-bcc64c00-d8d4-11ea-87bc-1b639f069377.png)

Pylance reported that log10 is not a known member (despite it is), however, the script can run as expected as well.  
I wonder if it's same as issue with [#150](https://github.com/microsoft/pylance-release/issues/150), but I'm not sure enough.

## Code Snippet / Additional information

```python
import numpy as np
x = np.linspace(1, 100)
y = np.log10(x)
```

**Comment by jakebailey** [comment] 2020-08-07 17:34
Duplicate of #150. Will work once numpy releases with stubs.

**Closed by jakebailey** 2020-08-07 17:34 UTC
Labels: triage
