### ISSUE TITLE
How to disable "code is not reachable" warning and greying out the code? I find this feature to be unreliable quite often.

### ISSUE THREAD

**Issue by yury-tokpanov** [microsoft/pylance-release#248] opened 2020-08-16 04:19 UTC

**Comment by jakebailey** [comment] 2020-08-17 16:55
We don't have any way to disable that, no. Can you provide some examples of how this feature is unreliable?

For auto-imports, see: https://github.com/microsoft/pylance-release/issues/64#issuecomment-669604900

**Comment by yury-tokpanov** [comment] 2020-08-18 04:04
Thanks for the reply! Unfortunately, I cannot provide details, since I'm working on a proprietary code. I'm pretty sure "code is unreachable" warning is generated due to how the code is structured, and, unfortunately, pylance analyzer doesn't dig deep enough.

**Comment by amachanic** [comment] 2020-08-18 14:08
Here is one example I'm hitting. We have a base class with a method that's expected to be overridden by children, and the base class also has another method that calls the (presumably overridden) base method. Herein lies the issue: PyLance seems to see our NotImplementedError on the base/non-overridden version of the method and doesn't realize that what we're referencing is in fact the overridden version. See the comment in `function()` for where I would expect things to properly work -- or to be able to disable the check so I don't have to see the greyed out code.

```
class MyBaseClass:
    @classmethod
    def get(cls):
         raise NotImplementedError

    @classmethod
    def get2(cls):
        blat = cls.get()
        # First hint: Code below here is "unreachable"
        # ... technically true out of context, but ...
        return blat

class MyClass(MyBaseClass):
    @classmethod
    def get(cls):
        return None

def function():
    r = MyClass.get2()
    # Anything from here down is "unreachable"
    return r
```

**Comment by erictraut** [comment] 2020-08-18 14:47
Thanks for providing the example. This is the most common cause of code being marked as unreachable. In your example, the `get` method in the `MyBaseClass` has no return type annotation, so Pylance is forced to infer its type based on code analysis. The method always raises an exception, and it's not properly marked as abstract (using an `@abstractmethod` decorator). So Pylance concludes that the return type is `NoReturn`.

There are two ways to work around this issue:
1. Add a return type annotation to the `get` method so Pylance doesn't need to infer the return type.
2. Mark `MyBaseClass` as abstract by deriving from `abc.ABC` and marking `get` as abstract using the `@abc.abstractmethod` decorator.

**Comment by yury-tokpanov** [comment] 2020-08-18 20:06
Thanks for a constructive reply!

We have a lot of similar to @amachanic 's situations, and it would be a pain to rework everything to accommodate PyLance reachability analyzer. I'd definitely prefer to just disable it for these kind of projects. I'm sure a lot of people would welcome an additional PyLance option to control this setting. :)

**Comment by erictraut** [comment] 2020-08-18 20:15
The reachability analyzer doesn't ever produce errors or warnings, so the worst thing that happens if you decide not to change your code is that you will see some text grayed out in your editor.

**Comment by amachanic** [comment] 2020-08-18 20:19
Thanks @erictraut. I went with the return annotation and it did the trick. Probably should have had one on there anyway.

@yury-tokpanov, it took me less than five minutes to change a few impacted base classes, and it's a nearly zero-risk modification. I highly recommend giving it a shot if the gray text bothers you.

**Comment by yury-tokpanov** [comment] 2020-08-18 20:29
@erictraut Sometimes not just some text, but all the text, if Pylance didn't correctly analyze beginning portion of the code.

@amachanic There are too many cases in my project, and I don't feel saying "adding support for Pylance" is a good justification to other people working on it.

**Comment by krooq** [comment] 2020-08-26 04:35
If the library you are using doesn't use type hints then you are reduced to 2 options:
1. use type hints in your code and deal with the greyed out text
2. don't use the type hints in your code

Seems a bit odd to me that Pylance would make an opinionated decision on this sort of thing.
Interested to know how Typescript handles this situation.

**Comment by erictraut** [comment] 2020-08-26 06:13
Library code doesn't need to contain type annotations to avoid this condition. If it makes proper use of @abstractmethod decorators, that will suffice. There are advantages to using both type annotations and @abstractmethod decorators, so I would encourage library authors to use both. But one or the other is sufficient in this case. Please submit bug reports or PRs to fix these issues in your favorite libraries. The entire Python community will benefit from such improvements.

It is important for Pylance to infer when a method or function is a "NoReturn" type. Failure to do this will result in false-positive errors because it will analyze code that is not meant to be executed. It's a tradeoff between false-positive errors (something that we try hard to avoid) versus grayed-out text when using a library that is missing annotations and proper use of @abstractmethod.

**Comment by yury-tokpanov** [comment] 2020-08-26 07:05
@erictraut I understand the motives, but it's infeasible to do what you suggest in all of the Python code out there. Why not just give a user an option whether to perform reachability analysis or not? Otherwise, Pylance is great, it's fast and gives useful suggestions, but having sometimes significant portion of the code greyed out is annoying at least.

**Comment by erictraut** [comment] 2020-08-26 15:04
As I mentioned, disabling reachability analysis will produce more problems than it solves. 

One potential solution is to provide a setting that allows you to disable the _reporting of unreachable code_ (i.e. don't show any gray text), but you can already effectively do that by adjusting your theme settings if the gray text really bothers you.

**Comment by krooq** [comment] 2020-08-30 09:29
That was an really clear explanation :)

It seems that the main issue is that `NotImplementedError` is a visual marker to developers that some class will implement the method but Pylance only considers `@abstractmethod` to be the marker.
Fair enough, they can have different semantic meanings, the just usually don't, which makes the grey text somewhat confusing to the developer.

If there was a setting, it would be to make `NotImplementedError` work the same as `@abstractmethod`.
But I don't think it's worth the extra maintainence burden.

**Comment by erictraut** [comment] 2020-08-30 15:17
After thinking about this further, I think it's reasonable for Pyright to assume that if a function meets all of the criteria below that it should be considered an abstract method for purposes of type inference:

1. Is a method (as opposed to a function declared outside of a class)
2. Has no return statements
3. Has no yield statements
4. Contains one or more raise statements
5. All raise statements raise NotImplementedError exception types

I've changed Pyright to infer the return type of such methods as "Unknown" rather than "NoReturn". This should address most of the cases that have been cited.

This change will be in the next version of Pyright and Pylance.

**Comment by jakebailey** [comment] 2020-09-03 22:56
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020

**Comment by daviskirk** [comment] 2020-10-15 10:40
Another example is when using `contextlib.suppress`: 

```
with suppress(AttributeError):
    return something.a 
return something_else
```

pylance will not understand that the suppress context manager is basically doing a try/catch pass and mark `return something_else` as unreachable.

**Comment by luksfarris** [comment] 2020-12-21 23:29
Hi, thank you for your support and for this extension.
This also happens after a `reset()` call of any `gym` environment. It happens on other places as well for me.
If someone wants to use a type of a parent class, and the parent class has a `raise NotImplementedError` in its body, how is this code unreachable? This is a super common design pattern.

Regardless of this feature being unreliable or not (because this is subjective), I believe there should really be a way to disable it. I have to choose now between using proper typing in my code or using PyLance :(

**Comment by sect2k** [comment] 2021-02-03 14:41
> After thinking about this further, I think it's reasonable for Pyright to assume that if a function meets all of the criteria below that it should be considered an abstract method for purposes of type inference:
> 
>     1. Is a method (as opposed to a function declared outside of a class)
> 
>     2. Has no return statements
> 
>     3. Has no yield statements
> 
>     4. Contains one or more raise statements
> 
>     5. All raise statements raise NotImplementedError exception types
> 
> 
> I've changed Pyright to infer the return type of such methods as "Unknown" rather than "NoReturn". This should address most of the cases that have been cited.
> 
> This change will be in the next version of Pyright and Pylance.

Not sure if this is by design, or a bug, but this doesn't work for methods marked as @classmethod. 

Example:
```python
class Test(object):
    @classmethod
    def do_something(cls):
        val = cls.get_value()
        print(val)

    @classmethod
    def get_value(cls):
        raise NotImplementedError
  ```
  `print(val)` is still grayed out, if decorator is removed, then it works fine.

**Comment by erictraut** [comment] 2021-02-03 17:33
I'm able to repro the problem using the above code snippet, but it only happens with Pylance (not with Pyright), and it seems to happen intermittently. In other words, I can make it go away by making a small edit in the file.

These symptoms indicate there's a bug related to type evaluation ordering. Pylance's semantic token highlighting feature tends to cause the types of identifiers to be evaluated in a different order than they otherwise would. In theory, the order of evaluation shouldn't affect the type evaluation results, but we have had bugs in the past where this is not the case. I'll need to look into the problem more deeply.

**Comment by erictraut** [comment] 2021-02-04 05:54
As I suspected, there was a bug that resulted in different results depending on the order of evaluation. The fix will be in the next release. Thanks for reporting the problem.

**Comment by jakebailey** [comment] 2021-02-11 01:25
This issue has been fixed in version 2021.2.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202121-10-february-2021

**Closed by jakebailey** 2021-02-11 01:25 UTC
Labels: bug, fixed in next version

**Comment by StephanDDX** [comment] 2022-02-04 10:16
> As I mentioned, disabling reachability analysis will produce more problems than it solves.
> 
> One potential solution is to provide a setting that allows you to disable the _reporting of unreachable code_ (i.e. don't show any gray text), but you can already effectively do that by adjusting your theme settings if the gray text really bothers you.

@jakebailey hey, was there any working done on providing such a setting? Or how do I can adjust my color-setting of my theme to not show greyed text? unfortunately the greyed text influence the readabilty of the code (color-wise) 
I would be very happy to able to disable the "greyed out text". the "information/warning" is still a good thing to have.
for me it is just a color-problem. (and i am quite happy with my current theme so far, so if possible i would like to stay with it)

**Comment by erictraut** [comment] 2022-02-04 16:22
We don't have plans to provide a setting to disable this.

**Comment by luabud** [comment] 2022-02-15 19:46
@StephanDDX it seems VS Code offers this setting called `Editor: Show Unused` that allows you to enable/disable the greyed out text. 

![image](https://user-images.githubusercontent.com/45497113/154137205-58bcdec4-a87a-46ed-a060-83580e5a4666.png)

**Comment by StephanDDX** [comment] 2022-02-16 06:18
@luabud thank you!

**Comment by luabud** [comment] 2022-02-16 20:12
for those interested in making the setting specifically applied for Python only, opening the settings.json file (View > Command Palette... an run "Preferences: Open Settings (JSON)) you can add the following:
```
"[python]": {
        "editor.showUnused": true,
    },
```

**Comment by 3Proto** [comment] 2022-02-18 13:54
@luabud This is just what I was looking for! Thanks so much!

**Comment by amunozj** [comment] 2022-07-29 16:39
@luabud Thank you so much for this!!!  I also find this an issue and it is not something I can fix because the problem comes from a python module I have no control over.   I'm glad there is an alterantive to the our way or the highway seen above.

**Comment by ielenik** [comment] 2022-11-01 11:09
What wrong is with this code:

`import numpy as np

mat_local = np.zeros((3,3))
# some lines are deleted, to show minimal example
mat_local[0] = np.cross(mat_local[1], mat_local[2])

# from this line code is unreachable
mat_local = np.transpose(mat_local)
`

**Comment by rchiodo** [comment] 2022-11-01 16:16
@ielenik what is your version of numpy? This might be a bug in the numpy type stubs. Works for me with 1.23.3

![image](https://user-images.githubusercontent.com/19672699/199282684-4a9ecea9-0d3f-43b8-a17d-574de254f3ce.png)

**Comment by erictraut** [comment] 2022-11-01 16:20
Yes, this is a duplicate of #3373, #3302, #3295, #3288, and #3277. It is a bug in earlier versions of numpy.

**Comment by OmarAI2003** [comment] 2023-03-26 10:08
help

**Comment by OmarAI2003** [comment] 2023-03-26 10:17
![Capture](https://user-images.githubusercontent.com/126517794/227769057-65c6dd7c-e4df-46b3-8be0-12fe986407c1.PNG)
![Capt3ure](https://user-images.githubusercontent.com/126517794/227769059-a0d70d2c-b927-4e4a-873c-75e246106246.PNG)


why can't declare a variable after a while loop but when I write break it works

**Comment by debonte** [comment] 2023-03-27 16:01
> why can't declare a variable after a while loop but when I write break it works

@OmarAI2003, without the `break` your `while True` loop is an infinite loop so the code after the loop is unreachable. If you believe there's a problem here with Pylance's behavior, please open a new issue. But if the code after the loop is marked as unreachable, that would be by design.

**Comment by OmarAI2003** [comment] 2023-03-31 09:16
> > why can't declare a variable after a while loop but when I write break it works
> 
> @OmarAI2003, without the `break` your `while True` loop is an infinite loop so the code after the loop is unreachable. If you believe there's a problem here with Pylance's behavior, please open a new issue. But if the code after the loop is marked as unreachable, that would be by design.

Yes, it should have been written before the while loop. Thank you for your assistance

**Comment by erictraut** [comment] 2023-03-31 19:05
By default, pyright (the type checker that underlies pylance) analyzes your code assuming the current platform. If you want it to analyze your code for a different platform, you can specify the desired platform via the `pythonPlatform` [configuration setting](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options). If you want it to assume that your code will run on all platforms, you can specify a `pythonPlatform` of "" (empty string).

Here's a simple `pyproject.toml` file that will accomplish this:
```toml
[tool.pyright]
pythonPlatform = ""
```

**Comment by NSQY** [comment] 2023-09-22 09:17
Still broken.

else is reachable:
```py
if type_checking:
    annotation = str
else:
    annotation = float
```

else is unreachable:
```py
if TYPE_CHECKING:
    annotation = str
else:
    annotation = float
```

**Comment by rchiodo** [comment] 2023-09-22 15:58
> Still broken.
> 
> else is reachable:
> 
> ```python
> if type_checking:
>     annotation = str
> else:
>     annotation = float
> ```
> 
> else is unreachable:
> 
> ```python
> if TYPE_CHECKING:
>     annotation = str
> else:
>     annotation = float
> ```

That's by design. TYPE_CHECKING is known for the type checker. `type_checking` is not so it can't predict which branch to take.

**Comment by NSQY** [comment] 2023-09-23 02:30
> > Still broken.
> > else is reachable:
> > ```python
> > if type_checking:
> >     annotation = str
> > else:
> >     annotation = float
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > else is unreachable:
> > ```python
> > if TYPE_CHECKING:
> >     annotation = str
> > else:
> >     annotation = float
> > ```
> 
> That's by design. TYPE_CHECKING is known for the type checker. `type_checking` is not so it can't predict which branch to take.

How do you suggest that I read other projects code when they're structured like this

```py
if TYPE_CHECKING:
    def foo(arg: str = 'whatever'):
        ...
else:
    def foo(arg: str = 'whatever'):
        x = 5
        y = 2
        z = 1
        return x + y + z
```

**Comment by rchiodo** [comment] 2023-09-25 16:03
> How do you suggest that I read other projects code when they're structured like this?

I would assume most people write libraries with the intent that you don't look at their source. I would assume in that example you gave, they're defining the function under the TYPE_CHECKING branch because it's easier to describe the return value of `foo`, which is what they expect you to care about.

**Comment by NSQY** [comment] 2023-10-25 12:30
> > How do you suggest that I read other projects code when they're structured like this?
> 
> I would assume most people write libraries with the intent that you don't look at their source. I would assume in that example you gave, they're defining the function under the TYPE_CHECKING branch because it's easier to describe the return value of `foo`, which is what they expect you to care about.

I was going to ignore this and just assume that I was in the wrong but after dealing with this constantly it has been driving me crazy. The library does not get to decide what I should and should not have access to. In fact, I first discovered this when trying to diagnose a bug where a method was mistakenly returning ``None``.

It is beyond frustrating that perfectly working code is supposedly "unreachable".

![image](https://github.com/microsoft/pylance-release/assets/34185288/5f7dc5ba-c2b0-472e-a920-cab8f2a2480e)

**Comment by NSQY** [comment] 2023-10-26 05:29
> You could log an issue on the library then. If the library author is not returning the correct types for their functions, it would be a bug on them to fix.

Everything in the image I posted is correctly typed. **Enabling plyance reduces the functionality of vs-code since it completely disables all interaction with the function since it thinks the code is unreachable**. I may as well be using Notepad.

**Comment by rchiodo** [comment] 2023-10-26 16:04
> Everything in the image I posted is correctly typed. Enabling plyance reduces the functionality of vs-code since it completely disables all interaction with the function since it thinks the code is unreachable. I may as well be using Notepad.

Sorry now I'm confused. Pylance is getting the wrong types then? Do you want to open another bug? I thought the original problem was the `if TYPE_CHECKING` code would mark items in the else case as unreachable. If you have a situation where there's a different reason for that and you're suspecting Pylance is not computing types correctly, please log another issue.

If the complaint that some code is marked as unreachable (and the types are computed correctly) but you want it to just skip the unreachable behavior, that would be an enhancement. You could also open a new issue for that as well. I don't think it would work though. If Pylance thinks it's unreachable, it can't compute the types of anything in that section. As far as Pylance is concerned, everything has a type of 'Never'.

**Comment by rchiodo** [comment] 2023-10-26 16:08
I guess what I'm asking is do you think Pylance is computing types incorrectly or not?

**Comment by NSQY** [comment] 2023-10-29 07:11
The problem is when inside a ``if TYPE_CHECKING`` block half of the features either stop working or become unavailable.

x is an int here:

if TYPE_CHECKING:
![image](https://github.com/microsoft/pylance-release/assets/34185288/7e168b3b-9989-4c1c-95a5-1507c7da0b39)

Without:
![image](https://github.com/microsoft/pylance-release/assets/34185288/75197417-7aed-4588-ac07-4b5c9b17ecbb)

Pylance extension disabled:
![image](https://github.com/microsoft/pylance-release/assets/34185288/ce5f85ff-0462-4944-9075-344c527f0f88)

**Comment by NSQY** [comment] 2023-10-29 07:15
Using pylance with projects that make use of ``if TYPE_CHECKING`` results in significantly degraded functionality compared to vs-code with the extension disabled.

if TYPE_CHECKING:

![image](https://github.com/microsoft/pylance-release/assets/34185288/ae78a682-aa7a-4249-b980-751d7a14cda5)

Without:

![image](https://github.com/microsoft/pylance-release/assets/34185288/e100aaee-b2a2-4c43-89c9-eb85f099b548)

Pylance extension disabled:

![image](https://github.com/microsoft/pylance-release/assets/34185288/0817cd87-25b7-4f83-897f-3b35b52b4f62)
