### ISSUE TITLE
Pylance claims `from . import builtins as ...` does not exist as a module

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#432] opened 2020-09-28 18:37 UTC
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: macOS 10.15
-   Python version (& distribution if applicable, e.g. Anaconda): Cpython 3.8.3

## Expected behaviour

Not mark an import of the form `from . import builtins as debuiltins` as not defined (specifically `builtins` has the squiggle).

## Actual behaviour

`builtins` is being flagged as not being defined in a relative import even though it does exist. It seems to require an `as` clause to trigger.

## Logs

```
XXX
```

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/54418/94471666-6364f580-017e-11eb-8c56-5873c3dcc5bd.png)

```python
from . import builtins as debuiltins
```

Repo is at https://github.com/brettcannon/desugar, and the specific line is https://github.com/brettcannon/desugar/blob/066f16c00a2c78784bfb18eec31476df045cefe5/desugar/operator.py#L9.

**Comment by jakebailey** [comment] 2020-09-28 18:40
Duplicate of #376, and will be fixed in the next release.

Disabling semantic highlighting is a workaround (see the linked issue).

**Closed by jakebailey** 2020-09-28 18:40 UTC
Labels: triage
