### ISSUE TITLE
pylance reportMissingImports

### ISSUE THREAD

**Issue by discdisk** [microsoft/pylance-release#1345] opened 2021-05-26 03:22 UTC
## Environment data
-   Language Server version: 2021.5.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): python3.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

## Expected behaviour
pakage import correctly

## Actual behaviour

When I install this pakage with conda  `conda install -c huggingface transformers` , it report Import "transformers" could not be resolved, but when I install this with pip `pip install transformers`, it work just fine.
But the code runs fine in both enviroments.

## Code Snippet / Additional information
The file in conda installed is like this
```
- site-packages
   ├─ transformers.pth
   └─ transformers-4.6.1-py3.8.egg
```

The file in pip installed is like this
```
- site-packages
   └─ transformers
          ├─ trainer.py
          ├─ activations.py
              ...
```
## Logs

```
[Info  - 下午12:05:02] Pylance language server 2021.5.3 (pyright 1f57ad5c) starting
[Info  - 下午12:05:02] Server root directory: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist
[Info  - 下午12:05:02] No configuration file found.
[Info  - 下午12:05:02] No pyproject.toml file found.
[Info  - 下午12:05:02] Setting pythonPath for service "python_assistant": "D:\miniconda3\envs\assistant\python.exe"
[Warn  - 下午12:05:02] stubPath e:\python_assistant\typings is not a valid directory.
[Info  - 下午12:05:02] Assuming Python version 3.8
[Info  - 下午12:05:02] Assuming Python platform Windows
Search paths for e:\python_assistant
  c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib
  e:\python_assistant
  e:\python_assistant\typings
  c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stubs\...
  c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\bundled\stubs
  d:\miniconda3\envs\assistant\dlls
  d:\miniconda3\envs\assistant\lib
  d:\miniconda3\envs\assistant
  c:\users\chen\appdata\roaming\python\python38\site-packages
  d:\miniconda3\envs\assistant\lib\site-packages
[Info  - 下午12:05:02] Searching for source files
[Info  - 下午12:05:02] Found 4 source files
[Info  - 下午12:05:02] Background analysis(1) root directory: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist
[Info  - 下午12:05:02] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at e:\python_assistant\main.py ...
[BG(1)]   parsing: e:\python_assistant\main.py (15ms)
[BG(1)]   parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 3ms] (127ms)
[BG(1)]   binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\builtins.pyi (40ms)
[BG(1)]   binding: e:\python_assistant\main.py (0ms)
[BG(1)]   parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing.pyi [fs read 1ms] (35ms)
[BG(1)]   binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing.pyi (11ms)
[BG(1)]   parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 2ms] (7ms)
[BG(1)]   binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (1ms)
[BG(1)]   parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (3ms)
[BG(1)]   binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing_extensions.pyi (2ms)
[BG(1)]   parsing: e:\python_assistant\train.py [fs read 0ms] (6ms)
[BG(1)]   binding: e:\python_assistant\train.py (1ms)
[BG(1)]   parsing: e:\python_assistant\test.py [fs read 1ms] (4ms)
[BG(1)]   binding: e:\python_assistant\test.py (2ms)
[BG(1)] getSemanticTokens full at e:\python_assistant\main.py (278ms)
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at e:\python_assistant\custom_dataset.py ...
[BG(1)]   parsing: e:\python_assistant\custom_dataset.py (9ms)
[BG(1)]   binding: e:\python_assistant\custom_dataset.py (4ms)
[BG(1)]   parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\__init__.py [fs read 0ms] (72ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\__init__.py ...
[BG(1)]     parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\_C\__init__.pyi [fs read 0ms] (126ms)
[BG(1)]     binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\_C\__init__.pyi (35ms)
[BG(1)]     parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\_C\_VariableFunctions.pyi [fs read 0ms] (48ms)
[BG(1)]     binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\_C\_VariableFunctions.pyi (28ms)
[BG(1)]     parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\functional.py [fs read 0ms] (13ms)
[BG(1)]     binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\functional.py (10ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\__init__.py (274ms)
[BG(1)]   parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\utils\data\__init__.py [fs read 0ms] (1ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\utils\data\__init__.py (0ms)
[BG(1)]   parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\utils\data\dataset.py [fs read 0ms] (4ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\utils\data\dataset.py (2ms)
[BG(1)]   parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\types.py [fs read 0ms] (1ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\types.py (0ms)
[BG(1)]   parsing: d:\miniconda3\envs\assistant\lib\site-packages\torch\tensor.py [fs read 0ms] (27ms)
[BG(1)]   binding: d:\miniconda3\envs\assistant\lib\site-packages\torch\tensor.py (7ms)
[BG(1)]   parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\abc.pyi [fs read 0ms] (0ms)
[BG(1)]   binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\abc.pyi (1ms)
[BG(1)] getSemanticTokens full at e:\python_assistant\custom_dataset.py (453ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 36:53 at e:\python_assistant\custom_dataset.py (15ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 1:11 at e:\python_assistant\main.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: e:\python_assistant\custom_dataset.py ...
[BG(1)]   checking: e:\python_assistant\custom_dataset.py (14ms)
[BG(1)] analyzing: e:\python_assistant\custom_dataset.py (14ms)
[BG(1)] analyzing: e:\python_assistant\main.py ...
[BG(1)]   checking: e:\python_assistant\main.py (0ms)
[BG(1)] analyzing: e:\python_assistant\main.py (0ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: e:\python_assistant\custom_dataset.py (27ms)
[FG] parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 3ms] (85ms)
[FG] binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\builtins.pyi (34ms)
[FG] binding: e:\python_assistant\custom_dataset.py (3ms)
Background analysis message: getDiagnosticsForRange
[FG] parsing: e:\python_assistant\main.py (7ms)
[FG] binding: e:\python_assistant\main.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing.pyi [fs read 2ms] (42ms)
[FG] binding: c:\Users\CHEN\.vscode\extensions\ms-python.vscode-pylance-2021.5.3\dist\typeshed-fallback\stdlib\typing.pyi (8ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

**Comment by erictraut** [comment] 2021-05-26 03:27
Could you provide the import statement that you're using? Is it `import transformers`? Or `from transformers import trainer`? Or something else?

**Comment by erictraut** [comment] 2021-05-26 03:30
Ah, it looks like the conda install is using a ".pth" file. Could you check whether it's a symlink or a text file? If it's a text file, please provide the contents. If it's a symlink, where does it point?

**Comment by jakebailey** [comment] 2021-05-26 03:47
This is a duplicate of #1260, something I'm currently working on. Some dependencies distributed on conda (including transformers) are in old-school egg files, which are zip files that need to be treated as directories and opened transparently by the FS abstraction (as python does at runtime).

**Closed** 2021-05-26 03:47 UTC
Labels: triage
