### ISSUE TITLE
Pylance completely breaks after using VS Code for extended period of time

### ISSUE THREAD

**Issue by VerathianHD** [microsoft/pylance-release#3649] opened 2022-11-18 16:40 UTC
Type: <b>Bug</b>

Pylance completely breaks after using VS Code for a long time.
I used VS Code for several hours last night, Pylance had broken before this but I simply did a hard re-install to fix it (delete all VS Code related files and uninstall it). However, after 4 hours or so of coding, it broke again.

For some reason, the moment I type anything, Pylance completely breaks highlighting and starts throwing up errors in random places. It feels like it's detecting me typing over other lines, as the errors show up in places where I didn't type at all.

I've attempted some solutions:
1) Reinstall Pylance
2) Disable Pylance (works but I want the highlighting that Pylance provides)
3) Restart VS Code

I looked all over the internet if anyone had similar issues, which they did not.

Extension version: 2022.11.30
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.24GB free)|
|Process Argv|--crash-reporter-id 5dcfe160-bdf3-450c-b224-958d596c3a05|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by ooliver1** [comment] 2022-11-18 23:00
#3554

**Comment by craigholm** [comment] 2022-11-20 00:37
I encountered this same problem with 2022.11.30.  The issue went away after rolling back to 2022.11.20.

**Comment by schlunma** [comment] 2022-11-21 09:48
Same problem for me with Pylance running on Remote Extension host.

-   Language Server version: Pylance language server 2022.11.30 (pyright 04a10583)
-   OS and version (remote host): Red Hat Enterprise Linux release 8.5 (Ootpa)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6 (ha86cf86_0_cpython; conda-forge)

**Comment by rchiodo** [comment] 2022-11-21 17:45
@VerathianHD or @schlunma can you include the contents of the 'Python Language Server' output tab? 

Thanks.

**Comment by schlunma** [comment] 2022-11-22 08:39
After running VS Code for about 30 min I get 70 wrong issues in my file. They appeared around 9:20 AM.

![grafik](https://user-images.githubusercontent.com/32543114/203265837-14cfb914-01a2-4f76-a082-8bacd440b947.png)

<details>
<summary>Python Language Server Output</summary>

```bash
[Info  - 8:49:51 AM] (1987600) Pylance language server 2022.11.30 (pyright 04a10583) starting
[Info  - 8:49:51 AM] (1987600) Server root directory: /home/b/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.30/dist
[Info  - 8:49:51 AM] (1987600) Starting service instance "ESMValCore"
[Info  - 8:49:51 AM] (1987600) Starting service instance "ESMValTool"
[Info  - 8:49:51 AM] (1987600) Notebook support: LSP
[Info  - 8:49:51 AM] (1987600) Interactive window support: LSP
[Info  - 8:49:51 AM] (1987600) Starting service instance "<default>"
[Info  - 8:49:52 AM] (1987600) No pyproject.toml file found.
[Info  - 8:49:52 AM] (1987600) Setting pythonPath for service "<default>": "/work/mambaforge/envs/esm/bin/python"
[Warn  - 8:49:52 AM] (1987600) stubPath typings is not a valid directory.
[Info  - 8:49:52 AM] (1987600) Assuming Python version 3.10
[Info  - 8:49:52 AM] (1987600) Assuming Python platform Linux
[Info  - 8:49:52 AM] (1987600) Searching for source files
[Info  - 8:49:52 AM] (1987600) No source files found.
[Info  - 8:49:52 AM] (1987600) Background analysis(1) root directory: /home/b/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.30/dist
[Info  - 8:49:52 AM] (1987600) Background analysis(1) started
[Info  - 8:49:52 AM] (1987600) Background analysis(2) root directory: /home/b/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.30/dist
[Info  - 8:49:52 AM] (1987600) Background analysis(2) started
[Info  - 8:49:52 AM] (1987600) Background analysis(3) root directory: /home/b/user/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.30/dist
[Info  - 8:49:52 AM] (1987600) Background analysis(3) started
[Info  - 8:49:52 AM] (1987600) No pyproject.toml file found.
[Info  - 8:49:52 AM] (1987600) Setting pythonPath for service "<default>": "/work/mambaforge/envs/esm/bin/python"
[Warn  - 8:49:52 AM] (1987600) stubPath typings is not a valid directory.
[Info  - 8:49:52 AM] (1987600) Assuming Python version 3.10
[Info  - 8:49:52 AM] (1987600) Assuming Python platform Linux
[Info  - 8:49:52 AM] (1987600) Searching for source files
[Info  - 8:49:52 AM] (1987600) No source files found.
[Info  - 8:49:52 AM] (1987600) No configuration file found.
[Info  - 8:49:52 AM] (1987600) pyproject.toml file found at /home/b/user/repos/ESMValCore.
[Info  - 8:49:52 AM] (1987600) Setting pythonPath for service "ESMValCore": "/work/mambaforge/envs/esm/bin/python"
[Info  - 8:49:52 AM] (1987600) Loading pyproject.toml file at /home/b/user/repos/ESMValCore/pyproject.toml
[Error - 8:49:52 AM] (1987600) Pyproject file "/home/b/user/repos/ESMValCore/pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 8:49:52 AM] (1987600) stubPath /home/b/user/repos/ESMValCore/typings is not a valid directory.
[Info  - 8:49:52 AM] (1987600) Assuming Python version 3.10
[Info  - 8:49:52 AM] (1987600) Assuming Python platform Linux
[Info  - 8:49:52 AM] (1987600) Searching for source files
[Info  - 8:49:52 AM] (1987600) Found 485 source files
[Info  - 8:49:52 AM] (1987600) No configuration file found.
[Info  - 8:49:52 AM] (1987600) pyproject.toml file found at /home/b/user/repos/ESMValTool.
[Info  - 8:49:52 AM] (1987600) Setting pythonPath for service "ESMValTool": "/work/mambaforge/envs/esm/bin/python"
[Info  - 8:49:52 AM] (1987600) Loading pyproject.toml file at /home/b/user/repos/ESMValTool/pyproject.toml
[Error - 8:49:52 AM] (1987600) Pyproject file "/home/b/user/repos/ESMValTool/pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 8:49:52 AM] (1987600) stubPath /home/b/user/repos/ESMValTool/typings is not a valid directory.
[Info  - 8:49:52 AM] (1987600) Assuming Python version 3.10
[Info  - 8:49:52 AM] (1987600) Assuming Python platform Linux
[Info  - 8:49:53 AM] (1987600) Searching for source files
[Info  - 8:49:53 AM] (1987600) Found 365 source files
[Info  - 8:49:56 AM] (1987600) [BG(3)] Long operation: checking: /home/b/user/repos/ESMValCore/tests/sample_data/multimodel_statistics/test_multimodel.py (2635ms)
[Info  - 8:49:56 AM] (1987600) [BG(3)] Long operation: analyzing: /home/b/user/repos/ESMValCore/tests/sample_data/multimodel_statistics/test_multimodel.py (2664ms)
[Info  - 8:52:42 AM] (1987600) Searching for source files
[Info  - 8:52:42 AM] (1987600) Found 485 source files
[Info  - 8:55:14 AM] (1987600) Searching for source files
[Info  - 8:55:14 AM] (1987600) Found 485 source files
[Info  - 8:55:47 AM] (1987600) Searching for source files
[Info  - 8:55:47 AM] (1987600) Found 485 source files
[Info  - 8:59:54 AM] (1987600) Searching for source files
[Info  - 8:59:54 AM] (1987600) Found 485 source files
[Info  - 9:08:29 AM] (1987600) Searching for source files
[Info  - 9:08:29 AM] (1987600) Found 485 source files
[Info  - 9:08:34 AM] (1987600) Searching for source files
[Info  - 9:08:34 AM] (1987600) Found 485 source files
[Info  - 9:08:56 AM] (1987600) Searching for source files
[Info  - 9:08:56 AM] (1987600) Found 365 source files
[Info  - 9:14:24 AM] (1987600) Searching for source files
[Info  - 9:14:24 AM] (1987600) Found 485 source files
[Info  - 9:14:26 AM] (1987600) Searching for source files
[Info  - 9:14:26 AM] (1987600) Found 485 source files
[Info  - 9:23:18 AM] (1987600) Searching for source files
[Info  - 9:23:18 AM] (1987600) Found 485 source files
[Info  - 9:23:20 AM] (1987600) Searching for source files
[Info  - 9:23:20 AM] (1987600) Found 485 source files
[Info  - 9:25:26 AM] (1987600) Searching for source files
[Info  - 9:25:26 AM] (1987600) Found 485 source files
[Info  - 9:25:26 AM] (1987600) Searching for source files
[Info  - 9:25:26 AM] (1987600) Found 485 source files
[Info  - 9:27:08 AM] (1987600) Searching for source files
[Info  - 9:27:08 AM] (1987600) Found 485 source files
[Info  - 9:29:53 AM] (1987600) Searching for source files
[Info  - 9:29:53 AM] (1987600) Found 485 source files
[Info  - 9:29:56 AM] (1987600) Searching for source files
[Info  - 9:29:56 AM] (1987600) Found 485 source files
```

</details>

**Comment by subhash686** [comment] 2022-11-23 02:23
Another weird behavior I noticed is that 
My VS code was running for more than a week and the Pylance process kept running at >100% CPU even when I completely quit VS Code. on MacOS 12.5.1,  my VS Code shows that I am using Pylance `v2022.11.30` 

When I check Activity monitor, there are two Pylance processes running one from `ms-python.vscode-pylance-2022.10.30` and the other from `ms-python.vscode-pylance-2022.10.40` (I did not restart my Mac in a while)

I killed the processes manually and no issues yet. I would imagine that the extension version when upgraded cleans the old version processes, but that does not seem to be the case.

**Comment by jonasreiher** [comment] 2022-11-24 08:50
I'm encountering this issue as well, for quite some time now. Example:
![Pylance issues](https://user-images.githubusercontent.com/58821240/203733783-bfbaabb4-d8ea-4d5c-b7f1-6ba0e7a6d099.png)

I am currently only working on a remote development host but I'm pretty certain to have had this problem locally as well.
Closing and reopening the affected file works temporarily but the problem always reoccurs at some point when switching back to VS Code from other programs.
It seems to mainly affect the first few lines of code, though not just import statements.

I'm also attaching the Python Language Server Output here (goes from opening workspace to problem occurrence to file close and reopening):
[Python Language Server Output](https://github.com/microsoft/pylance-release/files/10082285/PythonLanguageServerOutput.txt)

**Comment by LeShaunJ** [comment] 2022-11-25 00:07
> I encountered this same problem with 2022.11.30. The issue went away after rolling back to 2022.11.20.

I concur. Tried everything OP did to no avail until a rollback to `2022.11.20` did the trick.

**Comment by rchiodo** [comment] 2022-11-28 17:36
This looks like a dupe of https://github.com/microsoft/pylance-release/issues/3652 which was caused by incorrectly assigning files to the wrong workspace folder. It repros when you have more than one folder in your workspace. Going back to 2022.11.20 fixes that problem.

@LeShaunJ and @jonasreiher can you verify if you have more than one folder open?

**Comment by martinlbrook** [comment] 2022-11-28 18:18
I'm having the same issue. Also seems to be resolved by going back to 2022.11.20 and I'm experiencing it in a few different workspaces, all containing multiple folders.

**Comment by rchiodo** [comment] 2022-11-28 18:22
Thanks for verifying.

The reason it looks so weird is that the `textDocument/didOpen` will go to one server and your `textDocument/didChange` events will go to another. 

Internally this messes up the contents of the file that the server has. Meaning it doesn't even come close to matching what's on the screen.

Example:

File starts out as this:

```python
def hello_world():
    print("Hello")
```

You add this:

```python
def hello_world():
    print("Hello World")
```

Server sees this as the contents of the file because it missed the 'open' contents.

```python
World
```

**Comment by jonasreiher** [comment] 2022-11-28 19:46
> This looks like a dupe of #3652 which was caused by incorrectly assigning files to the wrong workspace folder. It repros when you have more than one folder in your workspace. Going back to 2022.11.20 fixes that problem.
> 
> @LeShaunJ and @jonasreiher can you verify if you have more than one folder open?

I can confirm. This happens to me when multiple folders are open in a single workspace. I tried with a single folder for some time now and did not yet encounter the problem again.

**Comment by rchiodo** [comment] 2022-11-28 20:22
Thanks. Closing as dupe of #3652

**Closed by rchiodo** 2022-11-28 20:22 UTC
Labels: waiting for user response

**Comment by LeShaunJ** [comment] 2022-11-28 21:47
> @LeShaunJ and @jonasreiher can you verify if you have more than one folder open?

Thanks for the reply, @rchiodo. Yes, I had multiple folders in my workspace when the issue occurred.
