### ISSUE TITLE
pylance suggestions not showing info about functions in matplotlib.pyplot

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1337] opened 2021-05-24 11:44 UTC
## Environment data

-   Python extension version: v2021.6.864643163-dev
-   Language Server version: 2021.5.4-pre.1
-   OS and version: ubuntu 21.04
-   Python version: 3.9.4 64-bit

## Expected behaviour

showing info of the functions like plot, etc.

## Actual behaviour

not showing info of the some of the function located in the module

**Comment by jakebailey** [comment] 2021-05-24 16:37
Can you please be more specific? "Info" isn't specific enough to indicate the problem. Are the types missing or wrong? Is there a missing function? Are you talking about docstrings?

**Comment by arian47** [comment] 2021-05-25 08:13
so if you look at the picture below, after importing the library and typing `cv2.` it does not show the functions and classes in it; that is what i meant

![Screenshot from 2021-05-25 12-40-38](https://user-images.githubusercontent.com/26442126/119462916-799b7380-bd56-11eb-99f2-4a9fee427608.png)

**Comment by arian47** [comment] 2021-05-25 08:19
with the snippet below, after importing the pyplot and using it, the suggestions does not contain information on some functions like plot in it, just the arguments it takes and what it returns, which even does not contain all of them
`import matplotlib.pyplot
matplotlib.pyplot.`

![Screenshot from 2021-05-25 12-48-29](https://user-images.githubusercontent.com/26442126/119463968-87052d80-bd57-11eb-8240-1140064388b0.png)

**Comment by jakebailey** [comment] 2021-05-25 17:54
It seems like what you're looking for is the docstring; the type information there is "correct", but not enough information for your use.

pyplot's layout makes it very difficult to find the docstrings in the original source (a lot of dynamic behavior to copy code from `matplotlib.axes`, so will require extra effort to support.

**Comment by jakebailey** [comment] 2021-09-08 00:35
I'm going to close this as a dupe of #1212, as it's the same.

**Closed by jakebailey** 2021-09-08 00:35 UTC
Labels: enhancement, in backlog, bundled typestub bug, docstrings, in iteration
