### ISSUE TITLE
Pylance is crashing even with own node.js

### ISSUE THREAD

**Issue by kubotty** [microsoft/pylance-release#6365] opened 2024-09-09 05:52 UTC
Pylance has crashed 5 times in the last 3 minutes even with own node.js setup.

Here is the steps:
1. Use the Python Interactive Window (which works with `# %%` in the code).
2. Create heavy object that involved opening CSV files with pandas, each file being ~50MB.
3. Restart VSCode.
4. Pylance crashes and encounter the following logs.

I followed [this link](https://aka.ms/AApf7ox) and installed and set the path for node.js but this persists.
Are there any constraints with opening large files in Python interactive mode? If there are any potential solutions. could you let me know?

```log
2024-09-09 14:23:39.846 [info] (Client) Pylance async client (2024.8.2) started with python extension (2024.14.0)
2024-09-09 14:23:40.236 [info] [Info  - 14:23:40] (21868) Server root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:40.236 [info] [Info  - 14:23:40] (21868) Experimental Pylance language server 2024.8.2 (pyright version 1.1.373, commit ee424479) starting
2024-09-09 14:23:40.245 [info] [Info  - 14:23:40] (21868) Starting service instance "module_name"
2024-09-09 14:23:40.542 [info] [Info  - 14:23:40] (21868) Setting pythonPath for service "module_name": "d:\work\module_name\.venv\Scripts\python.exe"
2024-09-09 14:23:40.543 [info] [Info  - 14:23:40] (21868) Setting environmentName for service "module_name": "3.10.14 (.venv venv)"
2024-09-09 14:23:40.543 [info] [Info  - 14:23:40] (21868) Loading pyproject.toml file at d:\work\module_name\pyproject.toml
2024-09-09 14:23:40.543 [info] [Info  - 14:23:40] (21868) Assuming Python version 3.10.14.final.0
2024-09-09 14:23:40.543 [info] [Info  - 14:23:40] (21868) Auto-excluding **/node_modules
2024-09-09 14:23:40.543 [info] [Info  - 14:23:40] (21868) Auto-excluding **/__pycache__
2024-09-09 14:23:40.544 [info] [Info  - 14:23:40] (21868) Auto-excluding **/.*
2024-09-09 14:23:40.544 [info] [Info  - 14:23:40] (21868) Found 8 source files
2024-09-09 14:23:40.717 [info] [Info  - 14:23:40] (21868) Background analysis(1) root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:40.717 [info] [Info  - 14:23:40] (21868) Background analysis(1) started
2024-09-09 14:23:40.997 [info] [Info  - 14:23:40] (21868) Indexer background runner(2) root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist (index)
2024-09-09 14:23:41.007 [info] [Info  - 14:23:41] (21868) Indexing(2) started
2024-09-09 14:23:41.999 [info] [Error - 14:23:41] Server process exited with code 1.
2024-09-09 14:23:41.999 [info] [Info  - 14:23:41] (21868) scanned(2) 153 files over 1 exec env
2024-09-09 14:23:42.001 [info] [Info  - 14:23:41] Connection to server got closed. Server will restart.
2024-09-09 14:23:42.001 [info] true
2024-09-09 14:23:42.483 [info] [Info  - 14:23:42] (17712) Server root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:42.488 [info] [Info  - 14:23:42] (17712) Experimental Pylance language server 2024.8.2 (pyright version 1.1.373, commit ee424479) starting
2024-09-09 14:23:42.489 [info] [Info  - 14:23:42] (17712) Starting service instance "module_name"
2024-09-09 14:23:42.904 [info] [Error - 14:23:42] Client Pylance: connection to server is erroring.
write EPIPE
2024-09-09 14:23:42.904 [info] [Error - 14:23:42] Client Pylance: connection to server is erroring.
write EPIPE
2024-09-09 14:23:42.904 [info] [Error - 14:23:42] Request textDocument/documentSymbol failed.
2024-09-09 14:23:42.904 [info]   Message: write EPIPE
  Code: -32099
2024-09-09 14:23:42.908 [info] [Info  - 14:23:42] Connection to server got closed. Server will restart.
2024-09-09 14:23:42.908 [info] true
2024-09-09 14:23:42.913 [info] [Error - 14:23:42] Server process exited with code 1.
2024-09-09 14:23:43.351 [info] [Info  - 14:23:43] (17752) Server root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:43.352 [info] [Info  - 14:23:43] (17752) Experimental Pylance language server 2024.8.2 (pyright version 1.1.373, commit ee424479) starting
2024-09-09 14:23:43.364 [info] [Info  - 14:23:43] (17752) Starting service instance "module_name"
2024-09-09 14:23:43.628 [info] [Info  - 14:23:43] Connection to server got closed. Server will restart.
2024-09-09 14:23:43.628 [info] true
2024-09-09 14:23:43.633 [info] [Error - 14:23:43] Server process exited with code 1.
2024-09-09 14:23:43.983 [info] [Info  - 14:23:43] (21604) Server root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:43.983 [info] [Info  - 14:23:43] (21604) Experimental Pylance language server 2024.8.2 (pyright version 1.1.373, commit ee424479) starting
2024-09-09 14:23:43.990 [info] [Info  - 14:23:43] (21604) Starting service instance "module_name"
2024-09-09 14:23:44.274 [info] [Info  - 14:23:44] Connection to server got closed. Server will restart.
2024-09-09 14:23:44.274 [info] true
2024-09-09 14:23:44.279 [info] [Error - 14:23:44] Server process exited with code 1.
2024-09-09 14:23:44.621 [info] [Info  - 14:23:44] (5720) Server root directory: file:///c%3A/Users/xxxx/.vscode/extensions/ms-python.vscode-pylance-2024.8.2/dist
2024-09-09 14:23:44.621 [info] [Info  - 14:23:44] (5720) Experimental Pylance language server 2024.8.2 (pyright version 1.1.373, commit ee424479) starting
2024-09-09 14:23:44.630 [info] [Info  - 14:23:44] (5720) Starting service instance "module_name"
2024-09-09 14:23:44.969 [info] [Error - 14:23:44] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
2024-09-09 14:23:44.976 [info] [Error - 14:23:44] Server process exited with code 1.
```

**Comment by rchiodo** [comment] 2024-09-09 16:03
I wonder if this is the same root cause as this issue:
https://github.com/microsoft/pylance-release/issues/6366

 Looks like a problem specifically with the interactive window.

**Comment by rchiodo** [comment] 2024-09-09 16:19
Marking as a dupe of #6357.

**Closed by rchiodo** 2024-09-09 16:19 UTC
Labels: needs repro
