### ISSUE TITLE
Wrong Unbound Warning in for loop

### ISSUE THREAD

**Issue by shalomori123** [microsoft/pylance-release#4268] opened 2023-04-20 15:31 UTC
## Environment data

`[Info  - 13:22:24] (2477) Pylance language server 2023.3.41 (pyright d7616109) starting`

## Code Snippet

```python
for i in [1, 2, 3]:
    if i == 1:
        a = 1
        break
    a = 2
print(a)
```

## Expected behavior
It's fine

## Actual behavior

`"a" is possibly unbound` Warning

**Comment by rchiodo** [comment] 2023-04-20 16:27
Thanks for the issue. I believe this is by design at the moment. Pylance (or Pyright which Pylance is based upon) already had this issue and it was marked as by design:

https://github.com/microsoft/pyright/issues/3784

I believe the reason being there's no way for Pyright to know if the loop runs or not. The suggestion is to either put in an `# type: ignore` where using the `a` or define it before entering the loop.

**Closed by rchiodo** 2023-04-20 16:27 UTC

**Comment by erictraut** [comment] 2023-04-20 17:10
Rather than a `# type: ignore`, you may also prefer to assign a value to the variable `a` before the loop, say with a value of `None`.

**Comment by shalomori123** [comment] 2023-04-20 17:20
Oh, thank you, I thought this is other specific issue.
@erictraut, I think that `None` itself is problematic, because when I use `a` in any opration like `a+b` or pass it as argument to function that need int, I will get other warning.
