### ISSUE TITLE
Automatically Implementing Abstract Methods

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#1725] opened 2021-08-25 08:52 UTC
Can the Python extension provide a feature like this?

![B8YVS](https://user-images.githubusercontent.com/21306413/130759959-d4820920-5b65-4740-9cb9-2e17366bae34.gif)

**Comment by jakebailey** [comment] 2021-09-23 22:52
This is a dupe of #146.

**Closed by jakebailey** 2021-09-23 22:52 UTC
Labels: enhancement
