### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by emi7718** [microsoft/pylance-release#3695] opened 2022-11-30 16:56 UTC
![image](https://user-images.githubusercontent.com/108490310/204858306-fb298c16-c008-4a05-9967-1c0778266e33.png)
![image](https://user-images.githubusercontent.com/108490310/204859487-e434ae89-108c-4c56-9845-89487070ea2d.png)

<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

delete some code, write it again, and the code loses colors and gives the error shown in the image

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by rchiodo** [comment] 2022-11-30 17:08
Do you happen to have multiple folders open? If so this is a dupe of #3652

**Comment by krosburg** [comment] 2022-12-07 19:17
@rchiodo I am having the same problem as @emi7718. I have multiple folders open.

**Comment by rchiodo** [comment] 2022-12-07 19:23
@krosburg our latest prerelease version should have the fix for your problem then. Today's stable release will also have it when it goes out in a few hours.

**Comment by emi7718** [comment] 2022-12-07 19:25
I think so, I'm a newbie sorry. I'm using Jedi now, disabled pylance, problem solved

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Closed** 2022-12-07 19:29 UTC
Labels: waiting for user response
