### ISSUE TITLE
no linting for sub-modules

### ISSUE THREAD

**Issue by ain-soph** [microsoft/pylance-release#823] opened 2021-01-11 21:15 UTC
```python3
import torch

layer = torch.nn.Linear(3,4)  # However, torch.nn is not recognized by Pylance.
```

## Workaround: 

```python3
import torch.nn

layer = torch.nn.Linear(3,4)  # This works well
```

But it should be a bug for sure. Please fix it. I know it could result in much slower linting speed if traverse __init__.py for all import sentences. So maybe some `stub` files designed for pytorch could help?

**Comment by jakebailey** [comment] 2021-01-11 21:16
Duplicate of #484.

**Closed by jakebailey** 2021-01-11 21:16 UTC
Labels: triage
