### ISSUE TITLE
Type stubs: class' init function docstring is used instead of class' docstring

### ISSUE THREAD

**Issue by qumusabel** [microsoft/pylance-release#1074] opened 2021-03-20 19:12 UTC
**Describe the bug**
When using type stubs, a class' `__init__` docstring is used instead of class' docstring.

**To Reproduce**
Make a stub class definition with a class docstring and `__init__()` docstring.

**Expected behavior**
The class' docstring is printed in the hint.

**Screenshots or Code**
```python
class Test:
    """This is a test class"""
    def __init__(self):
        """This is __init__()"""
        ...
```
```python
Test( # trigger docs
# "This is __init__()" is displayed in the docs
```

The actual docstring is longer:
![image](https://user-images.githubusercontent.com/18624304/111883093-f4ed4b80-89da-11eb-979e-2a882d382129.png)

**VS Code extension or command-line**
`coc-pyright` for `coc.nvim`

**Comment by jakebailey** [comment] 2021-03-22 18:07
The reason we're choosing the `__init__` docstring here is because it's a call expression thanks to the `(` being typed; we've found this to be consistent with other editors and languages where a class is "called" like a function. What's being called is that `__init__` function and if it has a doc we show it. This was by design (and we committed code to explicitly do this)

Other uses of the class will show the class docstring instead, where it's not in a call expression.

**Comment by jakebailey** [comment] 2021-03-22 18:09
I'm going to close this as we intended this behavior; we can revisit this later if there's more input that says this should be changed.

Moderately related, but if you look at the docstrings for classes in the builtins, they have the same docstring for the class themselves and for `__init__`; I'm not sure how common it is elsewhere to make them differ, though.

**Closed by jakebailey** 2021-03-22 18:09 UTC
Labels: triage
