### ISSUE TITLE
Excessive memory usage - how to debug?

### ISSUE THREAD

**Issue by dkbarn** [microsoft/pylance-release#1079] opened 2021-03-23 02:54 UTC
My running instance of the Pylance server regularly consumes 3GB of resident memory and 6.5GB of virtual memory, which I would consider excessive given the size of my workspace.

I just upgraded to the latest everything, but the issue remains. I'm now running:
VSCode 1.54.3
Pylance 2021.3.2
I use the SSH extension because all of my source code lives on my Linux server, but I dev on it from my Windows laptop. So the Pylance extension is enabled remotely and disabled locally.

My workspace consists of 9 Python projects, many of which contain a local virtualenv living inside the project's directory, which I activate as the Python interpreter in VSCode when working on that project.

In total there are 18,900 .py files in these projects, of which 17,820 live inside the venv directories.

What I'm wondering is how I can debug what the extension is doing, where the memory is going, and how many / which files it is indexing. If I open the Process Explorer in VSCode, it gives me no information about memory usage on the remote side (memory says 0 MB for everything), it can only tell me memory usage locally. But it's the remote machine's Pylance that is consuming all the memory.

I also have yet to find a way to see what files the indexer is working on. If I have multiple Python interpreters in various venvs, are all of the venvs indexed all the time? Or does the indexer only keep the currently active venv indexed in memory?

**Comment by bschnurr** [comment] 2021-03-23 04:16
try turning on trace `"python.analysis.logLevel": "Trace"` in your settings.json and view the `Python Language Server` output window. 

see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by erictraut** [comment] 2021-03-23 07:54
A few follow-up questions...
You mentioned that you have 9 Python projects. Are you using a multi-root workspace, one root for each project? If not, what do you mean by "project"?

Do you have the diagnosticMode set to "openFilesOnly" or "workspace"? The default is "openFilesOnly".

Do you have the indexer enabled? By default, it is currently disabled. If it's enabled, can you disable it and see if that changes the memory usage in a measurable way?

**Comment by dkbarn** [comment] 2021-03-25 18:29
Yes, I'm using a multi-root workspace. The 9 Python projects have been added via "Add Folder to Workspace..."

Here are all the python.* settings that are overridden in my settings.json:
```
    "python.languageServer": "Pylance",
    "python.venvPath": "${workspaceFolder}/venv",
    "python.analysis.autoImportCompletions": false,
    "python.analysis.diagnosticMode": "workspace"
    "python.analysis.typeCheckingMode": "basic",
```

I'm not sure how to check if the indexer is enabled -- is it a separate thing from the analyzer? My status bar constantly says "X files to analyze". In fact this is one of the things I wanted to flag - the analyzer doesn't seem to ever rest. It's always got files to be analyzed. Just when I think it's done, the number remaining jumps back up into the hundreds.

Since upgrading to the latest version of Pylance, a new behaviour I have noticed is that it now regularly consumes > 100% CPU. When this happens, everything in VSCode is laggy -- there is a ~10s delay for syntax highlighting to update, for a debug session to launch, for a debug session to terminate, for Ctrl+hover
 boxes to appear, etc.

Below is the (very large) dump of the Python Language Server trace log, after launching a fresh session of VSCode with no open editors. I just sat there for about 30 minutes watching this log get dumped, and not touching VSCode. Pylance was consuming 130-160% CPU throughout. And the analysis never seemed to finish -- it still said "394 files to analyze" when I quit. 

[pylance.log](https://github.com/microsoft/pylance-release/files/6207058/pylance.log)

**Comment by jakebailey** [comment] 2021-03-25 18:36
From the above logs, indexing is not enabled. You're on a stable build and have not set `"python.analysis.indexing": true`.

There are loads of files in those logs that appear to take multiple seconds to analyze, which is a bit concerning. Is this code available anywhere to take a look at what patterns may be causing a performance problem?

Note that in multi-root, each root gets its own analysis, because each have their own distinct import roots, selected interpreters, etc. With the diagnostic mode set to workspace, all of them are going to analyze all of the code in all of their folders for all info, which will likely cause high memory usage.

**Comment by dkbarn** [comment] 2021-03-25 18:50
Most of the code is not open source, but I could possibly share some select files if there any specific ones you'd like to see?

> With the diagnostic mode set to workspace, all of them are going to analyze all of the code in all of their folders for all info

Is there really no way to exclude certain directories from analysis? For example I see it going into a bunch of temp spaces auto-generated by pip/setuptools, like build/lib/ and dist/ and .eggs/ . I already have these excluded in my .gitignore files. Why is code analysis not respecting .gitignore?

In my workspace, I have only about ~1000 source files that belong to the projects, which I wouldn't consider an unreasonable number. The vast majority of the spurce code lives in the venv/ directories. But why venv/ directories included in analysis? It seems like the only thing that needs to happen here is type inference for any objects/functions my code may be referencing. But I don't see why full analysis would be needed on source code that isn't mine -- i.e. I don't need code errors highlighted in venv/ files.

How does Pylance decide that a file needs re-analysis? On the surface it looks like the same files are getting analyzed again and again when nothing has changed in their contents. I see "Background analysis message: invalidateAndForceReanalysis" a bunch of times in the log.

Given that code analysis is the most time-consuming and resource-intensive task that Pylance performs, does it have the ability to cache the result of analysis and persist this across VSCode sessions? Or does it throw everything away and start again from scratch re-analyzing the entire universe every time VSCode is launched?

**Comment by jakebailey** [comment] 2021-03-25 18:59
> Why is code analysis not respecting .gitignore?

I'm not aware of any analysis that respects .gitignore in this way. A language specific analyzer shouldn't be expected to respect a VSC's settings like that.

You can make a `pyrightconfig.json` in each workspace root, and then use the `exclude` to omit folders you don't want to be open: https://github.com/microsoft/pyright/blob/master/docs/configuration.md#main-pyright-config-options

I'd also consider switching to `openFile` mode and see how much of a difference that makes.

We try and ignore venvs, but if you are opening a folder that has more than one, maybe each workspace doesn't know about each others and is going through. Note that simply printing logs that contain venv folders is not a bad thing; we need to analyze the libraries you reference in order to analyze your code. If you're saying that we are showing diagnostics for unopened files in the venvs, then that's unintentional.

> I see Background analysis message: invalidateAndForceReanalysis a bunch of times in the log.

It could be that we are picking up file change events and are reanalzying. Events like file deletions and such force us to throw away analysis because that invalidates things like imports (which are very difficult to reason about). If you make that `pyrightconfig.json` file and add `"verboseOutput": true`, the logs will get even more verbose and show file change events. You can check and see if those `invalidateAndForceReanalysis` events are correlated with anything.

> Given that code analysis is the most time-consuming and resource-intensive task that Pylance performs, does it have the ability to cache the result of analysis and persist this across VSCode sessions? Or does it throw everything away and start again from scratch re-analyzing the entire universe every time VSCode is launched?

No, we reanalyze on open (and on invalidations). Persisting analysis is a pretty difficult task, and much of the analysis we do doesn't cleanly serialize.

**Comment by erictraut** [comment] 2021-03-25 19:47
With a multi-root workspace, we instantiate the type analyzer once for each root. So you're effectively running nine instances in parallel, and each has its own in-memory type cache.

Since diagnosticMode is set to "workspace", you're analyzing all files under each root rather than just the files you have open. As Jake suggested, switching to "openFilesOnly" will decrease the memory usage and time spent analyzing.

Pylance is smart about when files are re-analyzed, but files that are imported by code in different roots will get parsed and analyzed separately. This is required since the settings for each root can be different, and settings can affect the analysis. If you are seeing that files are getting analyzed multiple times without any edits, that probably explains why.

By default, Pylance assumes that it should include all ".py" and ".pyi" files under a workspace root. As Jake said, if you want to include a subset of files, you can create a pyrightconfig.json file within the root that specifies an "include" and/or "exclude" section.

**Comment by dkbarn** [comment] 2021-03-25 20:19
I've enabled ```verboseOutput``` in ```pyrightconfig.json``` and have attached the output here, in case there's anything helpful in it: 
[pylance-verbose.log](https://github.com/microsoft/pylance-release/files/6207614/pylance-verbose.log)

From what you've said, it sounds like the method of code discovery in the analyzer is file-based -- it starts at ```project-root/``` and recursively walks the directory tree collecting .py files. But using that approach, how can the analyzer know whether the statement ```import sqlalchemy``` should link to the contents of:
```build/lib/sqlalchemy``` or
```.eggs/sqlalchemy-1.3-py3.8.egg/``` or
```venv/lib/python3.8/site-packages/sqlalchemy/``` or
```venv2/lib/python3.8/site-packages/sqlalchemy/``` or
```.tox/testenv/lib/python3.8/site-packages/sqlalchemy/``` ?

My (naive) gut feeling is that it would make more sense for code discovery to be ```importlib``` based. Starting with a project's ```setup.py```, the package source directory can be discovered, and then only crawl into modules that the source package actually imports, resolving modules into file paths with ```importlib```. This would completely avoid the risk of wasting CPU cycles analyzing irrelevant .py files in directories like ```build/lib/```, ```dist/```, ```.eggs/``` or any redundant/inactive ```venv*/``` directories.

Looking at my output log I see a huge amount of time devoted to analyzing the contents of ```dkbarn-apiclient/.eggs/*``` which is a hidden temp directory that got made because I ran ```python setup.py build``` one time. It just feels like the code discovery built into Pylance would be smarter if the paths it chose to crawl were more informed by the actual imports of the package in question, rather than relying on path exclusion lists hard-coded in the analyzer (```.git```, ```__pycache__```, ```node_modules```) or manually curated in config files.

**Comment by erictraut** [comment] 2021-03-25 20:46
Import resolution is different from determining which files are in your local project. Imports can be (and often are) resolved by following paths outside of your workspace directory. 

Imported files are not analyzed completely. They are analyzed only to the extent that their types can be determined to satisfy the imports. You'll notice that errors and warnings are not displayed for source files that are imported from outside of your workspace.

The files that comprise your "project" are assumed to be the source files under your workspace root. There are situations where you may want to include only a subset of those files, but including all files under the root is the correct answer for the vast majority of Python projects. You can override this behavior if you want. This approach is consistent with VS Code language servers for similar languages (e.g. TypeScript).

**Comment by dkbarn** [comment] 2021-03-25 22:30
Thank you both for taking the time to answer all my questions, I'm learning a lot about how Pylance works and how I can best configure my settings to improve its performance.

> The files that comprise your "project" are assumed to be the source files under your workspace root. There are situations where you may want to include only a subset of those files, but including all files under the root is the correct answer for the vast majority of Python projects.

I'm not sure I completely agree with that assumption. The vast majority of Python projects are setuptools-based, and every setuptools project is going to include a mixture of code that should be analyzed and code that shouldn't, since tools like pip and ezinstall by default use the project root as scratch space for storing temporary build artifacts, like those in ```build/```, ```dist/```, and ```.eggs/```. It would be helpful if Pylance did not place the burden on every individual Python developer to manually add these paths to an exclusion list in a VSCode setting.

This is where I think it would be really useful for Pylance to respect the .gitignore file. Note that VSCode itself already has an awareness of .gitignore -- there is a setting for excluding its contents from search results: ```search.useIgnoreFiles```

If Pylance had a similar boolean flag, then all of these standard temp locations, which are very likely to be in every Python project's .gitignore, will not have to be added to multiple exclusion lists.

**Comment by jakebailey** [comment] 2021-03-25 22:38
> The vast majority of Python projects are setuptools-based

From what I've seen from the editor tooling end, the vast majority of Python projects aren't installable packages at all, and contain no build artifacts. Most people are opening up leaf projects that are never consumed by anyone else or are deployed as-is (webapps, scripts, data science code, student code, the works). You'd be surprised how limited the userbase is that has ever written or contributed to an installable package, compared to other types of projects.

I'm sympathetic to having a better default for our "include" configs. While I can think of cases where people may want code analyzed in gitignored files, I think that it's rare. But it's also the case that at the end of the day, we still may need to analyze files that are ignored, especially virtual envs.

**Comment by erictraut** [comment] 2021-03-25 22:40
I agree with what Jake said. The vast majority of Python projects are not setuptools-based. They're simple scripts or programs that are deployed as-is. It sounds like you have a pretty atypical project. Pylance provides the configuration knobs to accommodate more complex projects, but the defaults are tuned for the common case.

`.gitgnore` is a configuration file for source control. It specifies which files should be checked in to the repo or not. It would be very odd to conflate that with "Python source files that should be type analyzed". I can't think of any precedent for this in other tooling, and for good reason.

**Comment by dkbarn** [comment] 2021-03-26 00:30
To be honest what's feeling so awkward to me about VSCode is how it conflates "project folder" with "source folder". These *aren't* the same concepts, and other IDEs that I've used (like PyCharm) rightly make a distinction between the two. Very often the actual source code lives in a ```src/``` or ```<package_name>/``` subdirectory within the project, and when the IDE allows the user to register this subdirectory as its entry point for code analysis, it completely removes the need to maintain exclusion lists.

Going back to the original problem... I now have a paired-down workspace. It is still multi-root, but it now contains *only* these 3 directories:
```/share/dev/src/dkbarn/dkbarn-apiclient```
```/share/dev/src/dkbarn/dkbarn-wdb```
```/share/dev/src/dkbarn/dkbarn-wdb-ui```

Here's the mystery: according to the output log [pylance-verbose2.log](https://github.com/microsoft/pylance-release/files/6208583/pylance-verbose2.log) the analyzer is descending into directories that are not in my workspace, and not referenced by anything in my workspace. Directories like:
```/share/dev/src/dkbarn/dkbarn-backup```
```/share/dev/src/dkbarn/dkbarn-finance```
```/share/dev/src/dkbarn/dkbarn-stats```
```/share/dev/src/dkbarn/dkbarn-media_filer```
Why is it doing that??

**Comment by erictraut** [comment] 2021-03-26 01:15
By default, all source files within a workspace are considered to be part of the project. All IDEs I've used make the same assumption. I think PyCharm does the same, right? In any case, you can configure Pylance further if your needs dictate. The pyrightconfig.json file supports inclusion lists, exclusion lists, "extra paths" (for import resolution), and even multiple "execution environments". For full details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

To the best of my knowledge, very few Pylance users are making use of multi-root workspaces, so it's possible that you're encountering issues that have not been experienced/reported previously.

I just tried to recreate the scenario you've described above, and I'm not able to repro the behavior you're seeing. I created a multi-root workspace with two root folders. I placed a third folder next to them. I placed code files in all three folders. The structure looks like this. I then created a workspace and added the starred directories ("src1" and "src2" but not "src3").

```
temp
|- src1*
|     |- test1.py
|- src2*
|     |- test2.py
|- src3
      |- test3.py
```

I then set diagnosticMode to "workspace" for each of the two folders.

I confirmed that only `test1.py` and `test2.py` were analyzed. The third file `test3.py` was not opened or parsed.

Would you be willing to create a simplified version of your setup that demonstrates what you're seeing? Thanks!

**Comment by dkbarn** [comment] 2021-03-26 01:53
I'm unable to reproduce the issue with a simplified setup similar to yours. So I'm going to continue poking around at my workspace to see what about it is causing this behaviour.

However, I did notice something strange when I created the simplified setup. These were my steps:

1. "File > Close Workspace" to close down the original workspace.
2. Created the following directory structure:
```
/share/dev/src/test/
                  |- proj1/
                      |- foo.py
                  |- proj2/
                      |- bar.py
                  |- proj3/
                      |- baz.py
```
3. "File > Add Folder to Workspace... > /share/dev/src/test/proj1"

At this point, I noticed a bizarre thing in the Pylance log:
```
[Info  - 6:37:56 PM] Pylance language server 2021.3.3 (pyright be28f16e) starting
[Info  - 6:37:56 PM] Server root directory: /home/dkbarn/.vscode-server/extensions/ms-python.vscode-pylance-2021.3.3/dist
[Info  - 6:37:56 PM] No configuration file found.
[Info  - 6:37:56 PM] Setting pythonPath for service "proj1": "/share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8"
```
Something somewhere remembered the dkbarn-apiclient/venv from my previous workspace, even though I closed it and started a new one.

4. "File > Add Folder to Workspace... > /share/dev/src/test/proj2"
5. "File > Save Workspace As... > /share/dev/src/test/workspace.code-workspace"

Saving the workspace caused the whole window to reload and the output logs to restart. This time the Pylance logs said this:
```
[Info  - 6:46:18 PM] Setting pythonPath for service "proj1": "/usr/bin/python"
...
[Info  - 6:46:21 PM] Setting pythonPath for service "proj2": "/share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8"
```
So proj1 was using a more sensible python path, but proj2 was still set to some ghost of a previous workspace's venv.

**Comment by dkbarn** [comment] 2021-03-26 02:03
This is the content of the Python log window. More references to the dkbarn-apiclient/venv, as if it's set as my master Python interpreter or something. I can't find where this might be coming from in the settings.
```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonFindInterpretercf'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> conda --version
> pyenv root
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-03-25 18:56:33: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+dkbarn-htpc/home/dkbarn/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+dkbarn-htpc/home/dkbarn/.config/Code/User/settings.json')
	at _handleError (/home/dkbarn/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostProcess.js:87:151863)
	at async y.readText (/home/dkbarn/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (/home/dkbarn/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:578263)
	at async /home/dkbarn/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577390
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/dkbarn/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:577336)
	at async p.updateTestSettings (/home/dkbarn/.vscode-server/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:576963)] {
  code: 'FileNotFound'
}
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Pylance language server.
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: ./venv/bin/python
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-03-25 18:56:36: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /share/dev/src/dkbarn/dkbarn-apiclient/venv/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
```

**Comment by jakebailey** [comment] 2021-03-26 17:20
The above troubles sound like a core extension bug than anything; Pylance just uses the interpreter selected by the core extension so it's possible there's some bug in the interpreter detection/management code.

**Comment by dkbarn** [comment] 2021-04-04 19:51
> I just tried to recreate the scenario you've described above, and I'm not able to repro the behavior you're seeing. I created a multi-root workspace with two root folders. I placed a third folder next to them. I placed code files in all three folders. The structure looks like this. I then created a workspace and added the starred directories ("src1" and "src2" but not "src3").
> 
> ```
> temp
> |- src1*
> |     |- test1.py
> |- src2*
> |     |- test2.py
> |- src3
>       |- test3.py
> ```
> 
> I then set diagnosticMode to "workspace" for each of the two folders.
> 
> I confirmed that only `test1.py` and `test2.py` were analyzed. The third file `test3.py` was not opened or parsed.
> 
> Would you be willing to create a simplified version of your setup that demonstrates what you're seeing? Thanks!

Hi @erictraut , I think I've got a reproducible scenario now. The problem is caused the existence of the pyrightconfig.json file. If you create the same directory structure as before, but this time put a pyrightconfig.json file inside the top-level temp/ directory, which contains only the following contents:
```
{
    "verboseOutput": true
}
```
When you launch VSCode, the Python Language Server log will include a line like this:
```[Info  - 12:44:35 PM] No include entries specified; assuming /share/dev/src/temp```
And it will then start crawling into src3/test3.py, despite these files not being a part of your workspace.

This feels like a bug to me. Simply having a pyrightconfig.json file shouldn't change the file discovery behavior of Pylance just because the include setting is not defined.

**Comment by erictraut** [comment] 2021-04-04 20:58
Thanks for following up.

In a multi-root workspace, a different pyrightconfig.json file should be specified for each root. All of the paths in a pyrightconfig.json file are assumed to be relative to the root directory, so it wouldn't make sense to have a common pyrightconfig.json file for all roots.

A pyrightconfig.json file that is located in a directory that is not a workspace root should probably be ignored. I'll investigate that issue.

**Comment by erictraut** [comment] 2021-04-04 21:10
I confirmed that the code currently walks up the directory hierarchy until it reaches the root of the drive or it finds a config file. This behavior makes sense for the pyright command-line tool because you may be invoking it from deep within a project. But it doesn't make sense for an IDE-based language server because the IDE (in this case, VS Code) will define the project root(s), which dictate where the config file(s) should be located.

**Comment by erictraut** [comment] 2021-04-04 21:14
@jakebailey, here's a PR to review when you have a chance: https://github.com/microsoft/pyright/pull/1726

**Comment by jakebailey** [comment] 2021-04-14 19:44
The above PR made it into the last release; AFAIK this effectively "fixes" this issue by no longer having this "walking up" behavior, at the expense of each root requiring its own config. For now, this is the right way to do things; our current configuration system isn't designed to share configs between workspaces and the old behavior was unintended.

If sharing configs more generally is desired, that'd be an enhancement to consider separately from this performance bug. (There is prior art for this, like `tsconfig.json`.)

**Closed by jakebailey** 2021-04-14 19:44 UTC
Labels: waiting for info
