### ISSUE TITLE
How to use a modified build of Pyright with Pylance?

### ISSUE THREAD

**Issue by xSetech** [microsoft/pylance-release#377] opened 2020-09-16 20:27 UTC
Is it possible to integrate modifications to Pyright with Pylance? There's a static typing issue I'm running into for which I have a patch, but there are no apparent instructions on how to test the change with Pylance. On the other hand, Pyright has plenty of documentation on how to build and test; but I do not have Pyright installed as an extension. It'd be helpful if the readme addressed how modifications to Pyright can be tested in the context of an installed Pylance.

**Comment by jakebailey** [comment] 2020-09-16 20:37
This is probably a dupe of #33, but with the way Pylance is designed and distributed, it's not currently possible to do something like this.

If you're changing something to do with static typing in general, I would recommend working in the context of pyright, as we pull changes from there and things that are more type-check specific are better reported there. I recently refactored that repo to make it more straightforward to test changes with the type checker and extension, so if you disable Pylance and just follow their instructions you should be able to test your changes.

I'm not sure what the benefit of running it within pylance would be, but if you think there's something specific where running pyright alone is not enough, I'd be curious to know what that is.

**Closed** 2020-11-24 01:02 UTC
Labels: duplicate
