### ISSUE TITLE
how can restart server

### ISSUE THREAD

**Issue by hmouradova** [microsoft/pylance-release#4386] opened 2023-05-18 11:15 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.5.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by debonte** [comment] 2023-05-18 15:59
Dupe of #4385

**Closed by debonte** 2023-05-18 15:59 UTC
