### ISSUE TITLE
Unable to find member of the module for Numpy and Pytorch

### ISSUE THREAD

**Issue by Dylan-H-Wang** [microsoft/pylance-release#690] opened 2020-12-05 02:38 UTC
### Environment

- Pylance: 2020.12.0
- OS: Ubuntu 16.04.6
- Pytorch: 1.7.0
- Numpy: 1.17.4

### Expected Behaviour

The following modules or functions should not give any error messages:

<img width="727" alt="Screen Shot 2020-12-05 at 10 24 20 am" src="https://user-images.githubusercontent.com/37757585/101231336-78fa1c80-36e5-11eb-9f61-55658c8b2f6b.png">
<img width="241" alt="Screen Shot 2020-12-05 at 10 27 23 am" src="https://user-images.githubusercontent.com/37757585/101231341-81eaee00-36e5-11eb-8667-57ddb2804c04.png">

<img width="376" alt="Screen Shot 2020-12-05 at 10 24 34 am" src="https://user-images.githubusercontent.com/37757585/101231338-7eeffd80-36e5-11eb-8f68-6709a9c14c36.png">
<img width="819" alt="Screen Shot 2020-12-05 at 10 37 57 am" src="https://user-images.githubusercontent.com/37757585/101231405-03428080-36e6-11eb-9187-1f234be4239f.png">

### Logs
```
[Info  - 12:58:39 PM] Pylance language server 2020.12.0 (pyright ea581b3f) starting
[Info  - 12:58:39 PM] Server root directory: /home/path/.vscode-server/extensions/ms-python.vscode-pylance-2020.12.0/dist
[Error - 12:58:39 PM] stubPath /mnt/HDD2/path/typings is not a valid directory.
[Error - 1:11:33 PM] stubPath /mnt/HDD2/path/typings is not a valid directory.
```

**Comment by jakebailey** [comment] 2020-12-07 18:49
Duplicate of #150 and #484.

**Closed by jakebailey** 2020-12-07 18:49 UTC
Labels: triage
