### ISSUE TITLE
Type aliases are expanded out in tooltips

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#265] opened 2020-08-20 23:25 UTC
Version: Pylance language server 2020.8.2-dev.19.gfaa9ac5b (pyright fbe2eb4d) starting

Not sure if this is a bug or not, but it makes the user experience less than optimal

When the type alias is in the file scope the behavior is fine - as seen below:
![image](https://user-images.githubusercontent.com/547753/90835154-aff81e00-e300-11ea-9d99-9c5402c76e9e.png)

However in the case when the alias is in the global scope of an imported module as in Pygame Colors module
![image](https://user-images.githubusercontent.com/547753/90835354-3dd40900-e301-11ea-92eb-3a6670c057ea.png)
![image](https://user-images.githubusercontent.com/547753/90837673-93131900-e307-11ea-90dc-9749f467d593.png)

When trying to call a function that uses the alias in the sig, the alias is expanded out
![image](https://user-images.githubusercontent.com/547753/90835468-8f7c9380-e301-11ea-8c13-ba2052db9148.png)

**Comment by erictraut** [comment] 2020-08-21 00:07
I noticed this earlier today too, and it's on my list of things to fix. It's a bug, and I understand the cause, but it's going to be a relatively complex changed.

**Comment by jakebailey** [comment] 2020-08-28 20:03
This issue has been fixed in version 2020.8.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202083-28-august-2020

**Closed by jakebailey** 2020-08-28 20:03 UTC
Labels: bug, fixed in next version
