### ISSUE TITLE
Broken syntax highlighting when editor.semanticHighlighting.enabled is True

### ISSUE THREAD

**Issue by HMaker** [microsoft/pylance-release#342] opened 2020-09-04 16:34 UTC
## Environment data
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic snap
Python version: 3.7.7
Type of virtual environment used: None, using only python's std libraries
Language Server: Pylance

## Expected behaviour
![Print1](https://user-images.githubusercontent.com/23155511/92262858-2032a200-eeb2-11ea-8a91-e080453619b9.png)

## Actual behaviour
![Print2](https://user-images.githubusercontent.com/23155511/92263014-53753100-eeb2-11ea-914c-a82b0194bc54.png)

**Comment by judej** [comment] 2020-09-08 17:52
@HMaker, could you specify which syntax highlight is broken?

**Comment by mgresko** [comment] 2020-09-08 19:14
Related: https://github.com/Binaryify/OneDark-Pro/issues/439

**Comment by rhklite** [comment] 2020-09-09 17:58
i think the `self.` part should be colored differently. I encountered the same problem yesterday

**Comment by tnakaicode** [comment] 2020-09-11 15:44
I use Dark++ https://marketplace.visualstudio.com/items?itemName=DryWolf.dark-plus-plus-theme .

**Comment by jakebailey** [comment] 2020-09-14 19:56
I believe this is a dupe of #323.

**Closed by jakebailey** 2020-09-14 19:56 UTC
Labels: waiting for info
