### ISSUE TITLE
can not chat 

### ISSUE THREAD

**Issue by jeffy17668** [microsoft/pylance-release#6439] opened 2024-09-24 06:29 UTC
Type: <b>Bug</b>

chat is dificult,can not send message

Extension version: 2024.8.1
VS Code version: Cursor 0.41.2 (297991d169fa3a11975c5aa95adc69be73250c70, 2024-09-21T04:18:39.370Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jeffy17668** [comment] 2024-09-24 06:30
Extension host terminated unexpectedly 3 times within the last 5 minutes.

**Comment by jeffy17668** [comment] 2024-09-24 06:31
Extension Bisect is active and has disabled 3 extensions. Check if you can still reproduce the problem and proceed by selecting from these options.

**Comment by rchiodo** [comment] 2024-09-24 15:53
I would expect this is a dupe of #6357. Please upgrade your extension to the latest version.

**Closed by rchiodo** 2024-09-24 15:53 UTC
Labels: needs repro
