### ISSUE TITLE
Docstrings display broken for dataclasses

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#640] opened 2020-11-22 16:02 UTC
## Environment data

-   Language Server version: 2020.11.371526539
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9

## Actual behaviour
Docstrings of dataclasses are not show for class instantiation:

![image](https://user-images.githubusercontent.com/5834577/99908680-36e3da80-2ce4-11eb-9fa3-c245c863f6ed.png)

You should attach the class docstring to your internally synthesized `__init__` function.

## Expected behaviour
Display docstrings for dataclass instantiation like you already do for normal classes:
![image](https://user-images.githubusercontent.com/5834577/99908660-1c116600-2ce4-11eb-8324-3dd71cc01b3e.png)

**Comment by erictraut** [comment] 2020-11-22 16:16
Thanks for the suggestion.

Pylance doesn't display class docstrings for constructors in any class, so this issue isn't specific to dataclasses. I guess it's more of an issue with dataclasses because the constructor is implicit.

Maybe Pylance should always display the class docstring if the constructor (`__init__` or `__new__` method) has no docstring. Needs more thought & discussion.

**Comment by ARF1** [comment] 2020-11-22 20:41
> Maybe Pylance should always display the class docstring if the constructor (`__init__` or `__new__` method) has no docstring. Needs more thought & discussion.

FWIW This suggestion gets a definite **yes** from me. If a programmer has made the effort of actually writing a docstring, it should be displayed if it is even remotely relevant.

I cannot imagine a single instance where a programmer did not write a docstring for their constructor because they explicitly did not want a docstring to be displayed for the constructor. It simply means that they are lazy and felt that they explained everything in the class docstring.

And if a unicorn programmer should exist that explicitly does not want any docstring being shown for their constructor, they can always write an empty docstring for their constructor.

**Comment by savannahostrowski** [comment] 2021-06-08 18:56
We've changed the behaviour so that we display the docstring as you described above.

![image](https://user-images.githubusercontent.com/8949415/121241627-7f15b500-c850-11eb-9867-d6f5b6a7404b.png)

**Comment by ARF1** [comment] 2021-06-08 19:44
@savannahostrowski That's great. Many thanks!

**Comment by Antyos** [comment] 2021-06-14 15:02
@savannahostrowski Was this change included in Pylance v2021.6.1 or has it not been released yet?

I can repeat the example you showed above, but I cannot get the class docstring to appear if the `__init__()` docstring is not present. 
![image](https://user-images.githubusercontent.com/17516195/121913772-4a45aa00-ccf7-11eb-9832-4b8e2860119f.png)

Additionally, no docstrings will show up in the constructor if the class is decorated as `@dataclass`:
![image](https://user-images.githubusercontent.com/17516195/121913979-79f4b200-ccf7-11eb-962c-5dea54c44c8d.png)

**Comment by jakebailey** [comment] 2021-06-14 18:47
You're right, it doesn't work.

![image](https://user-images.githubusercontent.com/5341706/121943180-2c337600-cd06-11eb-979c-2b67e0c95880.png)

I mistakenly tested with the "expected behavior" snippet in the original issue, which was of course a simulation of what was expected.

**Comment by erictraut** [comment] 2021-06-16 03:37
This will be fixed in the next release.

**Comment by bschnurr** [comment] 2021-06-17 06:00
This issue has been fixed in version 2021.6.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202162-16-june-2021

**Closed by bschnurr** 2021-06-17 06:00 UTC
Labels: bug, fixed in next version
