### ISSUE TITLE
Duplicate code hints

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/pylance-release#3606] opened 2022-11-10 06:44 UTC
Type: <b>Bug</b>

Currently there are duplicate code prompts for modules in python code.

[![](https://imgur.com/PRGP5FC.png)](https://imgur.com/PRGP5FC.png)

[![](https://imgur.com/8zo4w0F.png)](https://imgur.com/8zo4w0F.png)

Problem solved after downgrading python extension to `2022.16.1`.

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (2.90GB free)|
|Process Argv|--crash-reporter-id eff41e00-9cca-49eb-98d7-445f3a050d2c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30605430
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by rchiodo** [comment] 2022-11-10 18:06
This is an issue with the jupyter extension that should be fixed in their latest version. See this issue here:
https://github.com/microsoft/vscode-jupyter/issues/11938

**Closed by rchiodo** 2022-11-10 18:06 UTC
Labels: triage-needed

**Comment by karthiknadig** [comment] 2022-11-10 19:05
@rchiodo Is pylance generating the additional logs seen here:
![image](https://user-images.githubusercontent.com/19380579/201144695-079cd724-8ffe-4ac9-8fb8-e5eb605d23bd.png)

**Comment by rchiodo** [comment] 2022-11-10 19:09
No those are caused by the language server started by the older jupyter extension.
