### ISSUE TITLE
An internal error occurred while type checking file filename.py: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ReagentX** [microsoft/pylance-release#475] opened 2020-10-12 17:14 UTC
## Environment data

-   Language Server version: v2020.9.114305
-   OS and version: MacOS 10.14.6 (18G6032)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 (pyenv)

## Expected behaviour

Pylance works

## Actual behaviour

Pylance crashes with error on line 1, char 1 of every file

```
An internal error occurred while type checking file "~/app/file.py": RangeError: Maximum call stack size exceeded
    at v (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:453945)
    at ~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:459847
    at Map.forEach (<anonymous>)
    at Object.a [as isSameGenericClass] (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:459804)
    at v (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:454072)
    at v (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:454345)
    at v (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:454588)
    at v (~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:455104)
    at ~/.vscode/extensions/ms-python.vscode-pylance-2020.10.0/dist/pyright.bundle.js:1:459847
    at Map.forEach (<anonymous>) Pylance

```

**Comment by erictraut** [comment] 2020-10-12 17:27
Thanks for reporting the problem. 

By any chance, is your project available in a public github repo? If so, I can take a look at the problem. If not, I'll need to ask that you help us narrow down the problem further. I find I can usually find the cause by doing a binary search (deleting half the code to see if it still repros, etc.).

**Comment by ReagentX** [comment] 2020-10-12 21:35
The repo cannot be made public. What do you need from me?

**Comment by erictraut** [comment] 2020-10-12 23:12
There's unfortunately not enough information available in the logs for me to diagnose the problem. You'd need to narrow it to a self-contained code snippet that exhibits the problem.

**Comment by savannahostrowski** [comment] 2020-11-12 18:22
This issue has been open for 30 days waiting for info so I'm going to close this. If this is still an issue, please reopen!

**Closed by savannahostrowski** 2020-11-12 18:22 UTC
Labels: waiting for info

**Comment by Jeff1995** [comment] 2020-12-05 14:55
I have the same problem. Commenting out my code part by part led to the following minimal example:

```python
import torch.distributions as D
normal = D.Normal(0.0, 1.0)
D.kl_divergence(normal, normal)
```

It is the "D.kl_divergence(normal, normal)" line that causes the problem.

**Comment by erictraut** [comment] 2020-12-05 17:20
I'm not able to repro a problem with this code example. There must be something specific about your configuration that I'm missing. Which version of pytorch do you have installed? Which version of Python? Which platform (Windows, Mac, Linux)?

**Comment by Jeff1995** [comment] 2020-12-05 17:36
I'm using pylance through a remote Linux machine. Here's my environment:

Local system: macOS 11.0.1
Remote system: Ubuntu 20.04.1
Pylance: 2020.12.0

Python: 3.8.5 (conda build h7579374_1)
PyTorch: 1.7.0 (conda build py3.8_cuda11.0.221_cudnn8.0.3_0)

All Pylance settings are left as default.

**Comment by ehossack** [comment] 2020-12-07 01:49
I also am having this same problem. I also don't have a public codebase :(

Local System: macOS 10.15.6
No remote
Pylance as part of vscode python language tools (v2020.11.371526539): 
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
Python 3.9.0 as part of poetry (1.1.4) in a virtualenv installed via pyenv.
No adjustments to pylance.

**Comment by erictraut** [comment] 2020-12-07 02:05
@ehossack, could you open the Output tab corresponding to Pylance and paste the output related to the error? It should start with the statement "An internal error occurred while type checking file" and include a partial stack crawl. Thanks!

**Comment by ehossack** [comment] 2020-12-07 02:07
Hmmm is this it?
```
[Error - 6:04:27 PM] An internal error occurred while type checking file "/Users/ehossack/code/<project>/<path/to/folder>/<file>.py": RangeError: Maximum call stack size exceeded
    at Object.b [as lookUpClassMember] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:454089)
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:296050)
    at ue (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275120)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297159
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297619)
    at pe (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275028)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:322073
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451636
    at Array.forEach (<anonymous>)
    at Object.c [as mapSubtypes] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451513)
[Error - 6:04:27 PM] Error performing analysis: RangeError: Maximum call stack size exceeded
    at Object.b [as lookUpClassMember] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:454089)
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:296050)
    at ue (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275120)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297159
    at Be (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:297619)
    at pe (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:275028)
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:322073
    at /Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451636
    at Array.forEach (<anonymous>)
    at Object.c [as mapSubtypes] (/Users/ehossack/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:451513)
[Error - 6:04:27 PM] Request textDocument/semanticTokens/full failed.
  Message: Request textDocument/semanticTokens/full failed unexpectedly without providing any details.
  Code: -32603 
```

**Comment by erictraut** [comment] 2020-12-07 02:10
Yes, that's it. Based on this stack crawl, this appears to be a different but than the one originally reported in this issue.

**Comment by ehossack** [comment] 2020-12-07 02:11
Mmm gotcha. Should I retain this info and open a new bug?

**Comment by erictraut** [comment] 2020-12-07 02:12
Yeah, that would be really helpful for tracking this issue. Thanks!

**Comment by yury-tokpanov** [comment] 2020-12-08 01:53
Cannot disclose code, but recently started seeing similar error message (it was working fine before, not sure what changed):
`An internal error occurred while type checking file "file.py": RangeError: Maximum call stack size exceeded
    at An (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:415174)
    at kn (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:412899)
    at /Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:410997
    at Dn (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:411548)
    at An (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:418429)
    at Fn (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:414900)
    at An (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:415758)
    at Vn (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:428144)
    at Un (/Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:427186)
    at /Users/yury/.vscode/extensions/ms-python.vscode-pylance-2020.12.0/dist/pyright.bundle.js:1:299349`

**Comment by jakebailey** [comment] 2020-12-08 02:01
The next release should contain at least one recursion fix, but I am working on getting source mappings included to better make sense of these.

I think we'd still appreciate fresh issues if the stack trace matches, though, as the issue is almost certainly different than this old bug.

**Comment by alexkudryavtsev88** [comment] 2023-11-01 11:10
Issue is reproduced in:

**OS**: MacOS Monterey version 12.3
**Python 3.11**
**pyright: 1.1.333**

Pyright fails when checking the file with the code with xlsxwriter.WorkBook usage:

`An internal error occurred while type checking file "/Users/aliakseikudrautsau/Projects/portal-backend/portal_backend/serializers/xlsx_serializer.py": RangeError: Maximum call stack size exceeded
    at isTypeVar (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/types.ts:2724:17)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11734:22)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:647:13)
    at Array.forEach (<anonymous>)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:646:18)
    at validateArgType (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11733:13)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11264:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11263:32)
    at validateFunctionArgumentTypesWithContext (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10986:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8586:28)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19913:28)
    at validateOverloadsWithExpandedTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8585:36)
    at validateOverloadedFunctionArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8997:32)
    at validateCallForOverloadedFunction (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9488:28)
    at validateCallArgumentsForSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9257:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9164:44)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19907:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9161:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3852:39)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:650:9)
    at expandSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3842:13)
    at mapSubtypesExpandTypeVars (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3881:13)
    at validateCallArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9157:26)
    at getTypeOfCall (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8056:36)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1014:30)
    at evaluateTypesForAssignmentStatement (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15501:39)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19011:25)
    at a.evaluateTypesForStatement [as timeOperation] (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:360:31)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19125:9)
    at a.evaluateTypeForSubnode [as timeOperation] (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at evaluateAssignmentFlowNode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:359:34)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:469:37)
    at preventRecursion (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:368:36)
    at getTypeFromFlowNode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:468:54)
    at Object.getTypeFromCodeFlow (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:1101:20)
    at getFlowTypeOfReference (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19193:25)
    at getTypeOfName (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4454:48)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:999:30)
    at validateArgType (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11784:40)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11264:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11263:32)
    at validateFunctionArgumentTypesWithContext (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10986:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8586:28)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19913:28)
    at validateOverloadsWithExpandedTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8585:36)
    at validateOverloadedFunctionArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8997:32)
    at validateCallForOverloadedFunction (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9488:28)
    at validateCallArgumentsForSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9257:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9164:44)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19907:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9161:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3852:39)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:650:9)
    at expandSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3842:13)
    at mapSubtypesExpandTypeVars (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3881:13)
    at validateCallArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9157:26)
    at getTypeOfCall (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8056:36)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1014:30)
    at evaluateTypesForAssignmentStatement (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15501:39)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19011:25)
    at a.timeOperation (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
Error performing analysis: RangeError: Maximum call stack size exceeded
    at isTypeVar (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/types.ts:2724:17)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11734:22)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:647:13)
    at Array.forEach (<anonymous>)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:646:18)
    at validateArgType (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11733:13)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11264:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11263:32)
    at validateFunctionArgumentTypesWithContext (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10986:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8586:28)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19913:28)
    at validateOverloadsWithExpandedTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8585:36)
    at validateOverloadedFunctionArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8997:32)
    at validateCallForOverloadedFunction (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9488:28)
    at validateCallArgumentsForSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9257:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9164:44)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19907:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9161:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3852:39)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:650:9)
    at expandSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3842:13)
    at mapSubtypesExpandTypeVars (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3881:13)
    at validateCallArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9157:26)
    at getTypeOfCall (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8056:36)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1014:30)
    at evaluateTypesForAssignmentStatement (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15501:39)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19011:25)
    at a.evaluateTypesForStatement [as timeOperation] (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:360:31)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19125:9)
    at a.evaluateTypeForSubnode [as timeOperation] (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at evaluateAssignmentFlowNode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:359:34)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:469:37)
    at preventRecursion (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:368:36)
    at getTypeFromFlowNode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:468:54)
    at Object.getTypeFromCodeFlow (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/codeFlowEngine.ts:1101:20)
    at getFlowTypeOfReference (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19193:25)
    at getTypeOfName (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4454:48)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:999:30)
    at validateArgType (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11784:40)
    at forEach (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11264:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:11263:32)
    at validateFunctionArgumentTypesWithContext (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10986:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8586:28)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19913:28)
    at validateOverloadsWithExpandedTypes (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8585:36)
    at validateOverloadedFunctionArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8997:32)
    at validateCallForOverloadedFunction (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9488:28)
    at validateCallArgumentsForSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9257:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9164:44)
    at useSpeculativeMode (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19907:20)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9161:24)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3852:39)
    at doForEachSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:650:9)
    at expandSubtype (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3842:13)
    at mapSubtypesExpandTypeVars (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3881:13)
    at validateCallArguments (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:9157:26)
    at getTypeOfCall (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8056:36)
    at getTypeOfExpression (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1014:30)
    at evaluateTypesForAssignmentStatement (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:15501:39)
    at callback (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19011:25)
    at a.timeOperation (/Users/aliakseikudrautsau/.cache/pyright-python/1.1.333/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
`

**Comment by erictraut** [comment] 2023-11-01 15:59
@alexkudryavtsev88, the issue you're hitting is different from the one originally reported in this issue (which has been fixed). Could you please open a new issue and provide repro steps? The more detailed the better. Thanks!
