### ISSUE TITLE
VSCode keep disconnected in Ubuntu-22.04 WSL with Pylance v2023.10.30

### ISSUE THREAD

**Issue by samueltan3972** [microsoft/pylance-release#4988] opened 2023-10-20 03:33 UTC
Type: <b>Bug</b>

Software Version:
- Python: 3.10
- Ubuntu: 22.04 (WSL2)
- OS: Window 11
- Pylance VSCode extension: v2023.10.30 (This is the root cause)
- VSCode: 1.83.1

The above (recent) version of the Pylance VScode extension cause VSCode to keep disconnect from WSL. The problem is able to resolve by downgrade the Pylance VScode extension to v2023.10.20.

Extension version: 2023.10.20
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13400 (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (3.81GB free)|
|Process Argv|--crash-reporter-id 1febacc4-f6b8-4670-895b-c3223d01ada9|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i5-13400 (16 x 2495)|
|Memory (System)|7.59GB (5.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixt:30866405
pyreplss1:30865275
pythoncet0:30866520
h48ei257:30866288
pythontbext0:30864172

```

</details>

**Comment by neerajanil** [comment] 2023-10-20 03:35
Facing the same issue, might be related to https://github.com/microsoft/pylance-release/issues/4983

**Comment by debonte** [comment] 2023-10-20 03:36
Duplicate of #4983

**Closed by debonte** 2023-10-20 03:36 UTC
Labels: needs repro

**Comment by Nitro8923** [comment] 2023-10-20 09:30
A temporary solution for now: #4990, if downgrading through the vsc extension marketplace doesn't work.
