### ISSUE TITLE
False positive "variable/parameter/function is not accessed" warning

### ISSUE THREAD

**Issue by emrekara369** [microsoft/pylance-release#3225] opened 2022-08-21 05:23 UTC
<h3> Environment data </h3>

-   Language Server version: 2022.8.31
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

Pylance started to warn that when I added a try/except structure into the for loop, the variables, the functions I imported, and the parameters I gave to the functions were not accessed.

![image](https://user-images.githubusercontent.com/74061558/185776758-789b9c84-2ea4-4038-9bc9-8f4cd22466c3.png)
![image](https://user-images.githubusercontent.com/74061558/185776777-ae8ddd92-19c0-4ad9-9457-e2cdc7eb9764.png)

**Comment by erictraut** [comment] 2022-08-21 05:25
Can you provide a minimal, self-contained code sample that exhibits the problem? If your code relies on imports from installed libraries, please specify the package and version that you are using. Partial code snippets and screen shots do not typically provide enough details for us to repro a problem of this type.

**Comment by erictraut** [comment] 2022-08-21 05:28
Also, if you open the "Output" tab and view the output for "Python Language Server", do you see any logs that might indicate a crash of any sort? If you see a stack crawl, that would be really helpful.

**Comment by emrekara369** [comment] 2022-08-21 05:37
Unfortunately, the code is within the scope of company confidentiality. For this reason, I cannot share any part of it. However, as I mentioned above, when I want to use a try/except structure to log which element of the iterated list I got an error in case I get any error in the for loop, Pylance specifies many variables, parameters and functions in the modules I wrote and imported as "is not accessed". Also, I don't see any crashes or errors in the "Python Language Server" logs in the "Output" tab.

**Comment by erictraut** [comment] 2022-08-21 05:40
Understood on the confidentiality. We don't need you to share the code as is, but are you able to extract a simplified (minimal) code sample into a stand-alone file that still exhibits the issue? It's fine if you anonymize the variable names to obscure what the code is doing.

**Comment by emrekara369** [comment] 2022-08-21 05:51
I think I could share a similar code example like this, but strangely Pylance doesn't seem to have any issues here
```python
import datetime
import traceback

my_items = ["a","b",2,"c","d"]

for my_item in my_items:
    try:
        print(my_item/2)
    except BaseException as ex:
        error_msg = "".join(traceback.format_exception(type(ex), value=ex, tb=ex.__traceback__))
        with open("bugs.txt","a") as file:
            file.write(datetime.datetime.now().__str__()+"\n"+str(my_item)+"\n"+error_msg+"\n\n")
```
![image](https://user-images.githubusercontent.com/74061558/185777590-5ddf4d66-456e-4595-afb5-17b509832559.png)

**Comment by erictraut** [comment] 2022-08-21 12:56
Yeah, it looks like you removed the part of the code that is essential to repro the problem. Perhaps try adding back more code from the original file until the problem manifests itself. If we're going to diagnose and fix the problem, we need a reproducible case first.

**Comment by Commaster** [comment] 2022-09-17 18:36
I am experiencing the same problem, should I open a separate Issue?
If I rollback to 2022.7.40 it works fine.
This happens in a ~4000 lines long file inside a 300 lines long function.
Console shows:
```
[Info  - ] (5447) [BG(1)] Long operation: checking: myfile.py (4508ms)
[Info  - ] (5447) [BG(1)] Long operation: analyzing: myfile.py (4763ms)
[Info  - ] (5447) [BG(1)] Long operation: getSemanticTokens full at myfile.py (4219ms)
```
Maybe this is somehow related to changes introduced in 2022.8.xx ?
I have `"python.analysis.diagnosticMode": "workspace"` as the only non-default setting.

**Comment by erictraut** [comment] 2022-09-17 18:40
@Commaster, yes, it would be good to open a new issue. We'll need a repro case. Is your code checked in to a public repo? If not, would you be willing to share a repro (whatever part of your code base is necessary to repro the problem) in a private repo that you temporarily give me access to? Without a local repro, diagnosis of the problem will probably not be possible.

**Comment by Commaster** [comment] 2022-09-17 19:00
@erictraut I will set up a private repo per your suggestion.

P.S. The only difference I see is that 2022.7.40 does not show the "getSemanticTokens full" line for this file. Might be a clue 🤔

**Comment by erictraut** [comment] 2022-09-17 20:02
If you enable type checking errors, you'll see the reason for the behavior you're seeing:
`Code is too complex to analyze; reduce complexity by refactoring into subroutines or reducing conditional code paths`

The problem is that the cyclomatic complexity of this function is too high for pyright (the type checker that underlies pylance) to analyze the function. As such, it cannot properly determine which symbols are accessed. As suggested by the diagnostic message, you can address this by refactoring into subroutines or otherwise simplifying the function.

**Comment by Commaster** [comment] 2022-09-17 20:15
So 2022.7.40 somehow did not have this limitation? Can you double check using 2022.7.40 and see that it tracks the variables properly?

**Comment by erictraut** [comment] 2022-09-17 20:24
There will always be some limit beyond which a type analyzer will need to give up and say "this is too complex". We've been improving the techniques for measuring complexity and adjusting the heuristics and constants accordingly. There is a usability tradeoff here. If we attempt to analyze a function that is too complex, performance and responsiveness suffers. It appears that your function is now classified as "too complex to analyze". You can address this by refactoring it into subroutines or otherwise simplifying the function.

**Comment by Commaster** [comment] 2022-09-18 09:37
So it happened at https://github.com/microsoft/pyright/commit/c3ee402007fc7dda6989761343b9af61efc03c64 , finally found it. Thank you for the explanation! 👍

**Comment by erictraut** [comment] 2022-09-18 15:34
This is an internal implementation detail, not something we'd want to expose as a setting. Like I said, there will always be some limit beyond which a type analyzer needs to give up. The analysis time increases exponentially as the complexity of the code increases, so small increases in complexity can result in very large increases in analysis time. 

With the current limit, it is extremely rare for a function to exceed the limit. There are many reasons why such complex functions should be avoided. If you refactor your code into subroutines, it will help with readability and maintainability.

**Closed** 2022-10-04 17:55 UTC
Labels: triage-needed
