### ISSUE TITLE
Auto-imports for submodules

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/pylance-release#4515] opened 2023-06-20 16:09 UTC
when:
```
import email
email.utils.
```
no auto-completing and pylance reported:
```
"utils" is not a known member of modulePylance[reportGeneralTypeIssues]
(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```
But email is a stdlib.
The question is that:
should pylance add `email` to some ignore lists,
or should the stdlib `email` import `utils` in its `__init__.py`,
or should the user import `email.utils` explicitly?

**Comment by rchiodo** [comment] 2023-06-20 16:29
Thanks for the issue but this is by design behavior. 

If you want to use `email.utils`, you need to explicitly import it. There is no implicit import of submodules in Python.

The runtime shows that too:

```
llLibrary/test_mytypedlibrary.py
Traceback (most recent call last):
  File "c:\Users\rchiodo\source\testing\Testing_InstallLibrary\test_mytypedlibrary.py", line 2, in <module>
    email.utils.decode_params([("1", "2")])
    ^^^^^^^^^^^
AttributeError: module 'email' has no attribute 'utils'
```

Whereas if you do this:

```
import email.utils
email.utils.decode_params([("1", "2")])
```

There is no runtime error.

**Comment by NewUserHa** [comment] 2023-06-20 16:31
but in my report, Python didn't throw `module 'email' has no attribute 'utils'`

**Comment by NewUserHa** [comment] 2023-06-20 16:34
![image](https://github.com/microsoft/pylance-release/assets/32261870/1ad4ca2a-6fcc-4ff2-ba3a-a7468d6343bb)

**Comment by rchiodo** [comment] 2023-06-20 16:34
Are you saying when you run this code:

```python
import email
email.utils.decode_params([("1", "2")])
``` 

It runs without a problem? 

Pylance is mimicking what the runtime would do, and shows an error for that exact code. Perhaps you have some implicit import happening with some other code?

**Comment by NewUserHa** [comment] 2023-06-20 16:38
but can't pylance detect the `email.utils` already in the namespace?

**Comment by rchiodo** [comment] 2023-06-20 16:40
The module isn't loaded as far as Pylance can tell. It knows nothing of the dynamic state of the Jupyter kernel.

**Comment by NewUserHa** [comment] 2023-06-20 16:41
Is the auto-complete of the notebook one part of pylance?

**Comment by rchiodo** [comment] 2023-06-20 16:42
Yes notebook support is part of Pylance, but the fact that `email.utils` is loaded is an accident. It's not part of any documentation on the part of IPython: 

https://ipython.readthedocs.io/en/stable/search.html?q=implicit&check_keywords=yes&area=default

**Comment by NewUserHa** [comment] 2023-06-20 16:45
Ok.

I thought it could make pylance for the notebook work better.
but if pylance is unable to, then it's ok too.

**Comment by rchiodo** [comment] 2023-06-20 16:57
I'm wondering if we could still provide completions even when there's an error.

Doing this should cause an error:

```
import email
email.utils.
```

But that doesn't mean we can't autocomplete `email.utils.`. The user may have just not typed in the import yet.

![image](https://github.com/microsoft/pylance-release/assets/19672699/657d42df-9486-4fd0-a916-1fed451ff3fe)

**Comment by debonte** [comment] 2023-06-20 18:45
Let's look into enabling auto-import for submodules.

**Comment by rchiodo** [comment] 2023-10-12 19:10
This is a dupe of #4955

**Closed by rchiodo** 2023-10-12 19:10 UTC
Labels: enhancement
