### ISSUE TITLE
Incorrect type/operator error for numpy ArrayLike

### ISSUE THREAD

**Issue by theelderbeever** [microsoft/pylance-release#1198] opened 2021-04-28 19:29 UTC
PyLance doesn't handle `numpy` types appropriately and shows them as type errors when attempting to perform operations with them that do exist. Possibly related to https://github.com/numpy/numpy/pull/16515 or #150.

## Environment data

-   Language Server version: 2021.4.2
-   OS and version: XXX
-   Python version: 3.8.8 (installed with `pyenv`)

## Expected behaviour

Numpy arrays can be added, subtracted, multiplied, etc and shouldn't show up as an error.

## Actual behaviour

![image](https://user-images.githubusercontent.com/29295582/116460397-42ec3f00-a824-11eb-9918-a04f1a6ae80d.png)

![image](https://user-images.githubusercontent.com/29295582/116460468-54cde200-a824-11eb-961f-b5069f73012e.png)

## Code Snippet / Additional information

```python
from numpy.typing import ArrayLike

def test_func(x: ArrayLike, y: ArrayLike):
    return x + y
```

**Comment by jakebailey** [comment] 2021-04-28 19:30
I think this is a duplicate of #1182, and will likely be fixed in the next release.

**Comment by jakebailey** [comment] 2021-04-28 19:34
Hm, maybe not. `ArrayLike` is a union (not a constrained TypeVar, though `numpy.typing` does have those available), so there's no guarantee that the two parameters will be compatible with each other when added (or have `+`, as far as I can tell).

**Comment by jakebailey** [comment] 2021-05-07 00:34
I'm inclined to believe that this is working as intended. Take this call for example:

```python
test_func(1234, [1, 2, 3])
```

This fails at runtime, but the definition of `ArrayLike` is:

```python
ArrayLike = Union[
    _ScalarLike,
    Sequence[_ScalarLike],
    Sequence[Sequence[Any]],  # TODO: Wait for support for recursive types
    _SupportsArray,
]
```

Two things being in this union doesn't imply that they are actually compatible. Under the hood, I believe numpy converts its array-like parameters as needed depending on the operation, but a function that tries to just do `a + b` isn't the same.

**Comment by jakebailey** [comment] 2021-05-07 00:37
If you wanted to be able to handle numpy arrays, you'd probably want:

```python
from numpy import ndarray


def test_func(x: ndarray, y: ndarray) -> ndarray:
    return x + y
```

This _does_ type check. Or, something like:


```python
import numpy as np
from numpy.typing import ArrayLike

def test_func(x: ArrayLike, y: ArrayLike) -> np.ndarray:
    return np.array(x) + y
```

**Closed by jakebailey** 2021-05-07 00:37 UTC
Labels: needs investigation
