### ISSUE TITLE
Magic commands (for example "%ls") cause errors in a valid python data science notebook script

### ISSUE THREAD

**Issue by oleg-butko** [microsoft/pylance-release#575] opened 2020-11-06 14:55 UTC
## Expected behaviour

No errors or easy way to disable some rules for some parts of a file

## Actual behaviour

The example of the "Expected expression" error:
```
{
	"resource": "/s:/somepath/init.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Expected expression",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 2
}
```

## Code Snippet / Additional information

This is a valid .py file to open in vscode (data science notebook mode)
Each cell causes the "Expected expression" error.

```python
# %%
%ls
# %%
!ps -efww
# %%
%cd '/somepath'
```

Alternative:

```python
# In[1]:
%ls
# In[2]:
!ps -efww
# In[3]:
# here the warning about the "display" built-in function
display(123)
```

```
{
	"resource": "/s:/path/file.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "\"display\" is not defined",
	"source": "Pylance (reportUndefinedVariable)",
	"startLineNumber": 33,
	"startColumn": 1,
	"endLineNumber": 33,
	"endColumn": 8
}
```

**Comment by jakebailey** [comment] 2021-02-05 01:42
#894 is technically a dupe of this, but since discussion has been happening there, I'll close this one and treat #894 as the canonical "magic commands in notebooks" issue.

**Closed by jakebailey** 2021-02-05 01:42 UTC
Labels: enhancement
