### ISSUE TITLE
Pylance stuck in endless loop, causing high CPU load

### ISSUE THREAD

**Issue by xmatthias** [microsoft/pylance-release#1368] opened 2021-05-29 19:10 UTC
## Environment data

-   Language Server version: 2021.5.4
-   OS and version: arch-linux
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.9.2 with pyenv 

## Expected behaviour

Pylance analyzes workspace once and stops (and saves results)

## Actual behaviour

Pylance continues to analyze workspace over and over - causing high CPU load.

this bug happens from time to time in my workspace (but not always - sometimes i start vscode, and it analyzes once and that's it, without any visible change).
As it's not happening all the time, i don't think it's related to my environment / setup (Then it would have to happen every time ...).

Unfortunately, it's a rather large project, which makes analyzing difficult.

While looking at the logs below - searching for bybit will show it's happening 28 times. 9 times is normal for 1 run - then it starts to repeat.

## Logs

```
[Info  - 8:59:40 PM] Pylance language server 2021.5.4 (pyright fd334302) starting
[Info  - 8:59:40 PM] Server root directory: /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist
[Info  - 8:59:40 PM] No configuration file found.
[Info  - 8:59:40 PM] pyproject.toml file found at /home/xmatt/development/cryptos/freqtrade.
[Info  - 8:59:40 PM] Loading pyproject.toml file at /home/xmatt/development/cryptos/freqtrade/pyproject.toml
[Error - 8:59:40 PM] Pyproject file "/home/xmatt/development/cryptos/freqtrade/pyproject.toml" is missing "[tool.pyright] section.
[Info  - 8:59:40 PM] Setting pythonPath for service "freqtrade": "/home/xmatt/.pyenv/versions/3.9.2/envs/trade_392/bin/python"
[Warn  - 8:59:40 PM] stubPath /home/xmatt/development/cryptos/freqtrade/typings is not a valid directory.
[Info  - 8:59:40 PM] Assuming Python version 3.9
[Info  - 8:59:40 PM] Assuming Python platform Linux
Search paths for /home/xmatt/development/cryptos/freqtrade
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stdlib
  /home/xmatt/development/cryptos/freqtrade
  /home/xmatt/development/cryptos/freqtrade/typings
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stubs/...
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/bundled/stubs
  /home/xmatt/.pyenv/versions/3.9.2/lib/python3.9
  /home/xmatt/.pyenv/versions/3.9.2/lib/python3.9/lib-dynload
  /home/xmatt/.pyenv/versions/3.9.2/envs/trade_392/lib/python3.9/site-packages
  /home/xmatt/development/cryptos/freqtrade
[Error - 8:59:41 PM] Exception received when installing recursive file system watcher
[Info  - 8:59:41 PM] Searching for source files
[Info  - 8:59:41 PM] Found 200 source files
[Info  - 8:59:41 PM] Background analysis(1) root directory: /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist
...
```
(full log in attachement)

[pylance_debug.log](https://github.com/microsoft/pylance-release/files/6565225/pylance_debug.log)

**Comment by erictraut** [comment] 2021-05-29 19:42
Based on the logs, it looks like something is repeatedly creating or deleting files within your workspace, and these are triggering a reanalysis. If you set the `verboseOutput` configuration key to True, you should see log output for each file system change event that pylance receives. That should make it obvious which file event (create or delete) is being generated and the path for each event.

**Comment by xmatthias** [comment] 2021-05-30 04:31
Where would that configuration key be?
VSCode does not know a setting called `verboseOutput` ... ?

**Comment by erictraut** [comment] 2021-05-30 05:13
Ah apologies, I should have provided more details. Please create a file called "pyrightconfig.json" at the root of your workspace. Copy the following into that file:

```json
{
    "verboseOutput": true
}
```

Pylance is built on the open-source type checker called pyright, so it honors pyright's configuration file documented [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

**Comment by xmatthias** [comment] 2021-05-30 06:44
Seems like you're right - saving one file (unmodified, just "ctrl+s" - in the test directory, for that matter) will trigger a FULL reload/reparse (whatever the right terminology is) of pylance.

I'd expect it to reparse only that one file - not the full tree.

Also adding (or removing) a simple csv file in the project root will trigger the same.
While i understand it's watching for file-level changes - i think this should be limited to files relevant for python typing (which is basically `*.py` and probably some type files) - but not for unrelated files (like .json or .csv files).

**Comment by erictraut** [comment] 2021-05-30 07:29
Simple saves of a single file shouldn't trigger full analysis. What event type are you seeing in the logs? Is it a 'change' event? Or is it an 'add' or something else?

If you are simply updating the contents of a `*.py` or `*.pyi` file, pylance is smart enough to invalidate only that file and its dependencies. And for its dependencies, it's smart enough to skip analysis phases that are guaranteed not to change.

There are some tools, such as code formatters, that save temporary files within the code tree. We have logic in place to detect these and ignore them, but that involves looking for specific file name patterns. Perhaps you're using a tool that generates temporary file names that are not covered by our current logic.

It would be useful if you could post some of the verbose logging output that lists the file system events.

**Comment by xmatthias** [comment] 2021-05-30 14:43
The only think i'm using that's formatting is autopep ... but i'd assume that "standard enough" to not cause any issues.

I've now tried again - saving 2 files (without modification) - first a "non-test" file - which didn't cause a full analyze
`[Info  - 4:36:44 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/freqtrade/freqtradebot.py'
Background analysis message: markFilesDirty
Background analysis message: analyze`

followed by a test-file - which seems to cause a "full" reanalyze.


full log:
```
Background analysis message: resumeAnalysis
[BG(1)] indexing: /home/xmatt/development/cryptos/freqtrade/tests/data/test_history.py [found 44] (1ms)
Indexing Done: /home/xmatt/development/cryptos/freqtrade/tests/data/test_history.py
[Info  - 4:37:11 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tests/data/test_history.py'
Background analysis message: markFilesDirty
Background analysis message: analyze
[Info  - 4:37:14 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/freqtrade/__pycache__/freqtradebot.cpython-39.pyc'
[Info  - 4:37:14 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/.pytest_cache/v'
[Info  - 4:37:14 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/.pytest_cache/v/cache/stepwise'
Background analysis message: invalidateAndForceReanalysis
Background analysis message: invalidateAndForceReanalysis
[Info  - 4:37:14 PM] Searching for source files
[Info  - 4:37:14 PM] Found 200 source files
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
...
```

I then copy/pasted the file into a editor window and stored it as `pylance2.log.

I then used a terminal to rename the file to "pylance22.log" - which caused a `invalidateAndForceReanalysis` event ... resulting in a full reanalyze.

```
...
Background analysis message: getDiagnosticsForRange
[Info  - 4:40:47 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/.git/FETCH_HEAD'
[Info  - 4:40:48 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/.git/FETCH_HEAD'
[Info  - 4:40:50 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tests/data/test_converter.py.git'
[Info  - 4:40:50 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/freqtrade/freqtradebot.py.git'
[Info  - 4:40:50 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tests/data/test_history.py.git'
[Info  - 4:40:50 PM] SourceFile: Received fs event 'add' for path '/home/xmatt/development/cryptos/freqtrade/pylance2.log'
[Info  - 4:40:50 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/pylance2.log'
[Info  - 4:41:08 PM] SourceFile: Received fs event 'add' for path '/home/xmatt/development/cryptos/freqtrade/pylance22.log'
[Info  - 4:41:08 PM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/pylance2.log'
Background analysis message: invalidateAndForceReanalysis
[Info  - 4:41:08 PM] Searching for source files
[Info  - 4:41:08 PM] Found 200 source files
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /home/xmatt/development/cryptos/freqtrade/freqtrade/freqtradebot.py ...
...
```


The full log is attached below and should include all 3 cases.

[pylance22.log](https://github.com/microsoft/pylance-release/files/6566373/pylance22.log)

**Comment by heejaechang** [comment] 2021-05-30 20:48
Thank you for the logs. I think we are too eagerly invalidating whole world when something we don't understand happen. we will get back to you once we have more detail.

**Comment by xmatthias** [comment] 2021-06-21 04:57
Based on the above provided link / information, i've tried to fix this for myself by adding some paths to the pyright configuration (`pyrightconfig.json`)

```
{
        "verboseOutput": true,
        "exclude": [
                "**/node_modules",
                "**/__pycache__",
                "src/experimental",
                "src/typestubs",
                ".pytest_cache",
                ".pytest_cache/*",
                "*.sqlite",
                "*.sqlite-journal"
        ]
}

```

It doesn't seem to work however, even after a full reload of vscode, i still get these messages in the logs - which indicate that neither sqlite, nor sqlite-journal have been properly excluded.


```
[Info  - 6:54:32 AM] SourceFile: Received fs event 'add' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'add' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite'
[Info  - 6:54:32 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'

```

Does pylance overwrite this "exclude" parameter from the configuration somehow? 
Is there a way to log what config is finally used? (the one i'm configuring seems to be ignored)...

**Comment by jakebailey** [comment] 2021-06-21 17:38
`exclude` controls which files are in the workspace, used in the initial workspace scan for source files and hiding diagnostic for the `workspace` diagnostic mode. It doesn't affect file watching; you can feasibly exclude file that is referenced from another file, and if that file changes on disk we'd need to know so that the files that depend on it can be updated.

**Comment by jakebailey** [comment] 2021-06-21 17:39
Are these files being changed causing issues for the analysis?

**Comment by xmatthias** [comment] 2021-06-21 20:18
The analysis result is (probably) unaffected - however it's triggering a full refresh (note the `markAllFilesDirty`).

As it's a database, this happens whenever the process is running (and the database is being written to) - which results in pylance constantly refreshing and taking ~1 cpu core at almost all times.


```
[Info  - 6:54:21 AM] SourceFile: Received fs event 'add' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
[Info  - 6:54:21 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite'
[Info  - 6:54:21 AM] SourceFile: Received fs event 'change' for path '/home/xmatt/development/cryptos/freqtrade/tradesv3.dryrun.sqlite-journal'
Background analysis message: invalidateAndForceReanalysis
Background analysis message: invalidateAndForceReanalysis
[Info  - 6:54:21 AM] Searching for source files
[Info  - 6:54:21 AM] Found 212 source files
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
```

If `exclude` can't exclude these files (they're not referenced by files directly - only by the running process (which should not matter for pylance) - is there another setting that can? 
this is turning into a higly obstructing bug as it makes using pylance basically impossible ...

**Comment by erictraut** [comment] 2021-06-21 20:25
You are writing your database files to a location within your source tree? That's pretty atypical — and normally undesirable for a variety of reasons. Is it feasible for you to store your database outside of your source tree?

On the pylance/pyright side, I think we could potential ignore "add" or "change" fs events for files (as opposed to directories) that don't end in one of the file extensions that the analyzer cares about (py, pyi, pyc, pyd, so, etc.).

**Comment by jakebailey** [comment] 2021-06-21 20:28
> On the pylance/pyright side, I think we could potential ignore "add" or "change" fs events for files (as opposed to directories) that don't end in one of the file extensions that the analyzer cares about (py, pyi, pyc, pyd, so, etc.).

This is the tricky bit as IIRC folder change events don't come in with enough information for us to know what they are. E.g., if it's a change due to the deletion of a directory, we may not know that a path we're given was actually a directory (we can't ask the FS about it anymore), so I think the current code is pretty conservative.

**Comment by xmatthias** [comment] 2021-06-21 20:37
> within your source tree?

it's not "within" the sourcetree - but at the root of the project (cwd) - which is pretty typical - and i've seen in quite many examples too, which use a sqlite database (especially in webproject samples that use sqlite).

For sure i **can** write the file to other places outside of the project - but to me, that's a poor workaround only suitable for this very particular instance of the problem, not a general solution.
it will still fail in other instances (which also have log included above - which were not related to sqlite databases, but to other, random files pylance should not care about).


why does pylance even look at files (and invalidate cache because of them)  it  shouldn't care about? (a sqlite file will not contain something valuable / usable for pylance ...) - so i think pylance should work based off of a extension whitelist, instead of assuming the whole tree as "fair game". 

You should never rely on what lives / doesn't live within a projects tree.

**Comment by jakebailey** [comment] 2021-06-21 20:39
> why does pylance even look at files (and invalidate cache because of them) it shouldn't care about? (a sqlite file will not contain something valuable / usable for pylance ...)

The problem is distinguishing which things are files and folders. I can make a folder named `foo.bar`, then add that to `PYTHONPATH`, and that's a valid code structure. If I then change something in that folder or delete it entirely, then things that depend on it need to be notified of that change. It's not always as simple as ignoring non-python files; the original code only watched `.py*` and we had to change it in order to get directory events.

Clearly we need to do better, but it's tricky.

**Comment by xmatthias** [comment] 2021-06-21 20:48
i don't disagree _on delete events_ - but for `add` + `change` events (which are the ones i experience this with the sqlite database) - it's as simple as `Path.is_file()` (obviously in python terms) to check if it's a file (it's not deleted, so you can simply check instead of invalidating everything).


Maybe a simple / quick solution is to provide a "proper" `exclude` list, which is completely ignored (maybe not by the file-watcher - but by what triggers the "markAllFilesDirty" event, so "known" bad directories or files can easily be excluded.
This might even be based on the .gitignore - however that might be dangerous as it would exclude potential settings files ...

**Comment by jakebailey** [comment] 2021-06-21 21:34
It's trickier than that, unfortunately, due to the watcher (from my experience anyway) sending deletion events or directory moves as "change" (not a deletion). That's why I said "change" above, anyway. It's also a pretty significant performance hit to check existence, but it's certainly the case that if we receive an event that would have previously resulted in a full reanalysis, that we would stand to do less work by prechecking in some conditions, among other improvements.

Again, I do not in any way disagree that our watcher handling needs to be redone, but file watching is super fickle and attempts to change it have usually resulted in breakages that have to be rolled back, so we've opted to try and not go too far (see also #923). It's certainly on the backlog to start looking into this more carefully and come up with a plan to work around the shortcomings with VS Code's file watcher and the ones we attempt (and fail) to use for libraries outside the workspace.

Now, for files in the workspace, VS Code provides those events. Can you see if you can add those bad items to `files.watcherExclude` in your VS Code settings and see if those events are no longer provided? That may be a good way to work around this in the meantime.

**Comment by xmatthias** [comment] 2021-06-22 04:53
For now i've added the following two settings - but it doesn't seem to change anything in this regard, i still get the "add" + "changed" events.

``` json
    "files.watcherExclude": {
        "**.sqlite": true,
        "**.sqlite-journal": true
    },
```


> It's also a pretty significant performance hit to check existence

I'd say running a full analysis of a big workspace (possibly not on a small workspace) is a bigger hit in performance - so maybe it can be done in an "when needed" way - to only make this check if the result would be a full analysis?

**Comment by mattmilten** [comment] 2021-11-06 12:31
I have similar issues with pylance consuming lots of CPU due to some background analysis. Switching to the insider's channel did not help. My only solution currently is disabling pylance :-(

**Comment by xmatthias** [comment] 2021-11-06 14:34
@mattmilten
i think this is related to the latest changes to both the test runner - as well as to how vscode now watches files.



You can find out which files trigger a full background analysis by following the instruction in this comment: https://github.com/microsoft/pylance-release/issues/1368#issuecomment-850941455 (don't forget to restart vscode after this) , and then looking at the output window of "python language server". 

for me, it's fixed with the following config (note that the first 2 are specific to my project)
```
    "files.watcherExclude": {
        "**.sqlite": true,
        "**.sqlite-journal": true,
        "**/.pytest_cache/**": true,
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/.hg/store/**": true,
        "**/.git/**": true,
        "**/__pycache__/**": true,
    },

```

**Comment by mattmilten** [comment] 2021-11-07 11:32
Thanks, @xmatthias! I excluded my git directories and now pylance is quiet, again.

**Comment by ewerybody** [comment] 2022-01-20 16:57
Hmm I also thought the `files.watcherExclude` would do something... I mean it did: We have pylint in our repo and there is literally a file called `huge.py` in its tests. **Python Language Server** logs showed that it took around 10 seconds to analyze. So this is fixed but my fans are still spinning up regularily with Pylance showing up in VS Code Process Explorer:
![image](https://user-images.githubusercontent.com/218956/150382656-b4c0c6a6-2701-4708-ae21-a71eef0450a6.png)

This is the line copied:
```
"C:\Users\techarteric\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  --ms-enable-electron-run-as-node c:\Users\techarteric\.vscode\extensions\ms-python.vscode-pylance-2022.1.1\dist\server.bundle.js
  --cancellationReceive=file:c8755e22c0176b26a0ed7edda33be58351f42c8e26 --node-ipc --clientProcessId=916
14 970 19144
```

So I turned on `"verboseOutput"` but there is nothing more shown in the **Python Language Server** logs it keeps quiet in there but still this Pylance job keeps at around 12-14% load all the time roughly eating one CPU core alone.

And analysis is weirdly slow. Usually all is super fluent and updates immediately. Now it tells me about things that have long been fixed.

A `>Deveoper: Reload Window` fixes things for a moment.

**Comment by bschnurr** [comment] 2022-01-20 19:10
@ewerybody try add this to your settings.json, and post the Python Language Server logs
```
"python.analysis.logLevel": "Trace",    
"python.analysis.logTypeEvaluationTime": true,    
"python.analysis.typeEvaluationTimeThreshold": 1000,

```

**Comment by ewerybody** [comment] 2022-01-21 13:06
Thanks @bschnurr! Well ... OK there seems to be nothing interesting really.
With these settings it now just logs what I'm actually doing and when I don't do anything it doesn't log.

It's not spamming like we'd expect from this kind of CPU load 🤷‍♀️

```
...
[FG] completion at c:\Users\eric\...\test\test_common.py:110:36 [found 1 items] (32ms)
[FG] completion at c:\Users\eric\...\test\test_common.py:113:80 ...
[FG]   parsing: c:\Users\eric\...\test\test_common.py (3ms)
[FG]   binding: c:\Users\eric\...\test\test_common.py (1ms)
[FG] completion at c:\Users\eric\...\test\test_common.py:113:80 [found 1 items] (29ms)
[FG] parsing: c:\Users\eric\...\test\test_common.py (2ms)
[FG] binding: c:\Users\eric\...\test\test_common.py (1ms)
[FG] parsing: c:\Users\eric\...\test\test_common.py (2ms)
[FG] binding: c:\Users\eric\...\test\test_common.py (1ms)
[FG] parsing: c:\Users\eric\...\test\test_common.py (2ms)
[FG] binding: c:\Users\eric\...\test\test_common.py (2ms)
```

After window restart there are some instances of 
```
[Info  - 13:34:23]   Looking for typeshed path
[Info  - 13:34:23]   Looking for typeshed stubs path
[Info  - 13:34:23]   Typeshed path not found
...
[Info  - 13:34:23]   Looking for typeshed stdlib path
[Info  - 13:34:23]   Attempting to resolve using root path 'c:\Users\eric\.vscode\extensions\ms-python.vscode-pylance-2022.1.1\dist\typeshed-fallback\stdlib'
[Info  - 13:34:23]   Typeshed path not found
```

`typeshed-fallback` exists tho! And stdlib things resolve from there.


Btw: the logging starts like:
```
[Info  - 13:34:19] Pylance language server 2022.1.1 (pyright 4f61d443) starting
[Info  - 13:34:19] Server root directory: c:\Users\eric\.vscode\extensions\ms-python.vscode-pylance-2022.1.1\dist
[Info  - 13:34:19] Setting pythonPath for service "st_main": "c:\Users\eric\work\st_main\python\python39\python.exe"
[Info  - 13:34:19] Loading configuration file at c:\Users\eric\work\st_main\pyrightconfig.json
[Info  - 13:34:19] Assuming Python version 3.9
[Info  - 13:34:19] Assuming Python platform Windows
[Info  - 13:34:19] No include entries specified; assuming c:\Users\eric\work\st_main
[Info  - 13:34:19] Auto-excluding **/node_modules
[Info  - 13:34:19] Auto-excluding **/__pycache__
[Info  - 13:34:19] Auto-excluding .git
...
```

**Comment by ewerybody** [comment] 2022-01-21 13:25
Btw: these two are **dimmed** in the `settings.json` saying `Unknown Configuration Setting`
> ```
> "python.analysis.logTypeEvaluationTime": true,    
> "python.analysis.typeEvaluationTimeThreshold": 1000,
> ```
I dunno if that's any more interesting? 🤷‍♀️

**Comment by ewerybody** [comment] 2022-01-21 15:26
OK I just tried sth.: Reloaded, Waited for everything to settle like around 0% CPU load. Then flushed the Pylance log.
Started typing a little and see if it gets stuck in the loop again. It did. Now I have 45k lines of log stuff... ~5mb.

Well it just stopped logging after I stopped typing. But Process Explorer CPU load is still on at "...ms-python.vscode-pylance-2022.1.1\dist\server.bundle.js ..." What can this be? Can there be something in this log? If you want it ... 
> [pylance log.txt](https://github.com/microsoft/pylance-release/files/7914780/pylance.log.txt)

I'll see if this is any different with the Insider build ...

**Comment by ewerybody** [comment] 2022-01-21 17:18
Same in Insider ☹
![image](https://user-images.githubusercontent.com/218956/150571026-12c4bcae-3bbb-4f88-a4cc-008b6c78bc2a.png)
🌬 wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww 
This is really really annoying.

**Comment by bschnurr** [comment] 2022-01-21 18:54
R you using python 2 or python 3?
I'm looking for the search path logs like this.
```
Search paths for /home/xmatt/development/cryptos/freqtrade
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stdlib
  /home/xmatt/development/cryptos/freqtrade
  /home/xmatt/development/cryptos/freqtrade/typings
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stubs/...
  /home/xmatt/.vscode/extensions/ms-python.vscode-pylance-2021.5.4/dist/bundled/stubs
  /home/xmatt/.pyenv/versions/3.9.2/lib/python3.9
  /home/xmatt/.pyenv/versions/3.9.2/lib/python3.9/lib-dynload
  /home/xmatt/.pyenv/versions/3.9.2/envs/trade_392/lib/python3.9/site-packages
  /home/xmatt/development/cryptos/freqtrade
```

Also  Please create a file called "pyrightconfig.json" at the root of your workspace. Copy the following into that file:

```json
{
    "verboseOutput": true
}
```

**Comment by heejaechang** [comment] 2022-01-21 19:15
having verboseOutput and full logs (not part of logs but full logs) will help us figure out what is causing invalidateAndForceReanalysis to happen.

**Comment by ewerybody** [comment] 2022-01-23 12:59
> having verboseOutput and full logs (not part of logs but full logs) will help us figure out what is causing invalidateAndForceReanalysis to happen.

wouldn't `invalidateAndForceReanalysis` be something that's logged?
In my case its like:
* everything loads up
* CPU load settles ~0%
* I start editing
* CPU goes up
* I **stop** editing
* logging **stops**
* CPU is still on.

> R you using python 2 or python 3? I'm looking for the search path logs like this.

Mostly 3 but also 2. So both.

> Also Please create a file called "pyrightconfig.json" at the root of your workspace. Copy the following into that file:
> 
> ```json
> {
>     "verboseOutput": true
> }
> ```
Yes. I have that 👍 . OK. full logs as in all from "Python Language Server" output? right?

**Comment by ewerybody** [comment] 2022-01-24 14:54
OK. Here is another trove of Python Language Server logs:
[pylance.log.zip](https://github.com/microsoft/pylance-release/files/7926362/pylance.log.zip)

I hope that helps

**Comment by bschnurr** [comment] 2022-01-24 18:19
I'm not 100% sure but it seems you might have third parties libraries and tests being seen as your user code.
 `Found 16776 source files`

in your settings.json try turning off indexing
`   "python.analysis.indexing":false,`

What is your diagnosticMode? I recommend the default `openFilesOnly`
 "python.analysis.diagnosticMode": "openFilesOnly"

normally I would expect your numpy files to be under `site-packages`
`c:\Users\eric\work\st_main\python\python39\Lib\site-packages`

but i see your numpy files are here. How r you installing numpy?  I see it parsing tests from numpy
`c:\Users\eric\work\st_main\python\packages\python_3\numpy\`

have you tried adding relative paths on folders that aren't your code to the `exclude` ?

example
```
{
        "verboseOutput": true,
        "exclude": [
                "**/node_modules",
                "**/__pycache__",
                ".pytest_cache",
                ".pytest_cache/*",
				"python/packages"
        ]
}
```

**Comment by bschnurr** [comment] 2022-01-24 19:38
Normally we would auto exclude your `venv` folder but our heuristic doesn't seem to be working in your case.

what files/folders do you have under 'c:\Users\eric\work\st_main\python\' ?

we are expecting 'Scripts\activate', 'activate' or 'bin"..

maybe just manually exclude your 'python' folder

{
        "verboseOutput": true,
        "exclude": [
                "**/node_modules",
                "**/__pycache__",
                ".pytest_cache",
                ".pytest_cache/*",
				"python"
        ]
}

**Comment by ewerybody** [comment] 2022-01-24 20:58
@bschnurr : yeah its a bit of a mess. We're developing one library and dedicated tools for different environments that may have Python2 or 3. Like things should be working in an old version of Autodesk 3ds Max, Blender and as standalone with latest Python.

under `python` we have:
* our own library
* 3rd party packages
  * py2 packages
  * py3 packages
  * dev packages
* python27 (only built-in modules and pth-file to point to lib^)
* python39 (only built-in modules and pth-file to point to lib^)
* typing stubs

This `exclude` also goes to the `pyrightconfig.json`?

**Comment by bschnurr** [comment] 2022-01-24 21:28
correct.

**Comment by ewerybody** [comment] 2022-01-26 12:53
Ok. I excluded my python dir but included our library like:
```
{
    "exclude": [
        "python",
    ],
    "include": [
        "python/lib",
    ]
}
```
Seems to work so far! 👍

Just seems bad that I'd have to put the `pyrightconfig.json` into the root and not into the `.vscode` dir or even better into the `settings.json` right away. But it is because Pyright is a separate project that doesn't necessarily know about VS Code?

**Comment by bschnurr** [comment] 2022-01-27 07:36
Are you manually setting your `python.path`?

"c:\Users\eric\work\st_main\python\python39\python.exe"

**Comment by ewerybody** [comment] 2022-01-27 09:32
You mean instead of `python.defaultInterpreterPath` might have been for historic reasons 🤷‍♀️
what about it?

Btw: this is definitely working for me now! And what a blessing that is! 😇 Thanks for looking into this! 🙇‍♀️

**Comment by heejaechang** [comment] 2022-01-28 19:01
now, with python.analysis.indexing on, we won't too eagerly re-index all user files, and only re-index user file that are directly changed.

**Comment by heejaechang** [comment] 2022-01-28 19:12
the fix for this issue should help part of issues happening on this (https://github.com/microsoft/pylance-release/issues/2270)

**Comment by debonte** [comment] 2022-02-04 15:16
This issue has been fixed in version 2022.2.0, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202220-2-February-2022)

**Closed by debonte** 2022-02-04 15:16 UTC
Labels: fixed in next version, in backlog, needs investigation

**Comment by eromoe** [comment] 2023-08-23 05:38
@debonte it doesn't
latest version : 
![image](https://github.com/microsoft/pylance-release/assets/3938751/9acaea13-aaba-4a45-9ae8-841a2fe1e8d1)

**Comment by debonte** [comment] 2023-08-23 06:12
@eromoe, this is a very old issue. If you're seeing a problem in recent builds of Pylance, please open a new issue.
