### ISSUE TITLE
Extension is watching files outside of the workspace

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/pylance-release#2914] opened 2022-06-10 12:17 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: Python extension does not watch files outside of the workspace

Actual: Log (Window):
```
[<timestamp>] [renderer15] [error] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: <some/path/that/is/not/the/workspace>)
```
where the path is sometimes a neighbouring python project workspace or `~/.conda/envs/<env_name>/lib/python3.9`. The neighbouring projects in question are not imported by any of the python files in this workspace (but they are the locations of editable pip installs in the conda environment).

## Steps to reproduce:

1. Open a python project workspace

## Additional context

This only started happening recently.

If I disable the Python extension for the workspace and close + reopen, I don't get the ENOSPC error until I re-enable the extension.

```
$ cat /proc/sys/fs/inotify/max_user_watches
32768
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
N/A
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

condaPath: "<placeholder>"

languageServer: "Pylance"

linting
• flake8Enabled: true
• mypyArgs: "<placeholder>"
• mypyEnabled: true
• pycodestylePath: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

Extension version: 2022.8.0
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 3.10.0-1160.66.1.el7.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (4 x 2599)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|7.62GB (0.59GB free)|
|Process Argv|--unity-launch --crash-reporter-id 4cb3165e-6680-471f-992f-0c1e623756f7|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|1-gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|1-gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by heejaechang** [comment] 2022-06-13 18:41
this is by design. we watch all paths reported by python sys.path if we can. but I think we can improve it by removing any path part of multi workspace root since they should be already watched by other workspace.

**Comment by heejaechang** [comment] 2022-06-13 18:44
tagging this issue as one of improvement for multi workspace - https://github.com/microsoft/pylance-release/issues/2601

**Comment by karrtikr** [comment] 2022-06-13 18:44
I understand if it's by design, but if it's exceeding the watcher limits we should probably be doing something about it. Do we have to watch for all paths in `sys.path`, can we watch the root directory containing all environments instead?

**Comment by heejaechang** [comment] 2022-06-13 18:50
@karrtikr it is already root folder of each importing roots (such as site-packages or python/lib folder). but we are not actual one who watch, we just ask vscode to watch those folders. and actual implementation is done by vscode.

so for file watch max limitation, actual implementation (vscode) should take care, I am not sure there is much we can do since actual implementation is owned by host (vscode or vs)

**Comment by karrtikr** [comment] 2022-06-13 23:13
I understand we're not the actual ones who implement the watcher, but it looks like its not practical to ask to watch so many directories (I'm not sure if it's a bug). Also for me personally `sys.path` looks like:
```
['~\\OneDrive - Microsoft\\Desktop\\folders\\donj2', '~\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip', '~\\AppData\\Local\\Programs\\Python\\Python39\\DLLs', '~\\AppData\\Local\\Programs\\Python\\Python39\\lib', '~\\AppData\\Local\\Programs\\Python\\Python39', '~\\OneDrive - Microsoft\\Desktop\\folders\\donj2\\.venv', '~\\OneDrive - Microsoft\\Desktop\\folders\\donj2\\.venv\\lib\\site-packages']
```
If we're only watching the root directories: `~\\AppData\\Local\\Programs\\Python\\Python39` and `~\\OneDrive - Microsoft\\Desktop\\folders\\donj2\\.venv`, the count of the watcher is 2 instead of 7.

**Comment by heejaechang** [comment] 2022-06-14 18:01
@karrtikr if OS throws because of 7 directory watched, I think OS has an issue rather than us. also, those kind of dedup I think should be done by vscode, since we can only do over what we watch, if other extension watches same folders, we can't dedup. those kind of dedup better to be done by host (vscode) in my opinion.

that being said, there are some we can do to support multi workspace better. and I will work on those soon.

**Comment by karrtikr** [comment] 2022-06-14 18:10
Right, I understand. Someone has got to report this on VSCode though.

**Comment by karrtikr** [comment] 2022-06-16 20:39
Great, thanks for the update.

**Comment by muncok** [comment] 2022-06-21 06:01
> I talked with vscode file watcher owner. he said, deduping is not there yet but they have work item to implement it, and asked us to dedup for now. I have WIP PR, will check in soon.

I have tried to use`files.watcherExclude` to exclude `conda's env directory`, but it was not work.

**Comment by bschnurr** [comment] 2022-06-22 23:52
This issue has been fixed in version 2022.6.30, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022630-22-June-2022)

**Closed by bschnurr** 2022-06-22 23:52 UTC
Labels: enhancement, fixed in next version

**Comment by phord** [comment] 2022-06-26 01:08
@bschnurr Is the fix some kind of dedup like @heejaechang mentioned, or was a different bug identified?  

It seems unreasonable to me that you have to watch the hierarchy of `$PYTHONPATH` for this extension.  Mine has only one directory in it, but that directory has 1.2 million files beneath it.  Is there a real fix for this, or do I need to disable/move my python path?

**Comment by phord** [comment] 2022-06-26 01:13
By the way, I noticed if I disable the pylance extenstion and then reload the workspace, the issue goes away.  If I then re-enable pylance, the problem does not recur.  So it seems this `watch $PYTHONPATH` is something only done during startup.  Is that correct?

**Comment by MetRonnie** [comment] 2022-06-27 08:53
@phord I think the full features of the extension don't load until you have a python file as an open tab, could that be why?

**Comment by mic-e** [comment] 2022-06-27 15:19
I'm running Pylance 2022.6.30 using an ssh remote host.
Is it possible to blacklist Pylance from watching the standard library files?
On the remote host I'm not allowed to increase the inotify watchers limit, and Pylance uses up all resources while attempting to watch the standard library.
Pylance seems to ignore the "Watcher Exclude" setting.
