### ISSUE TITLE
Vs code intelliSense show double suggestion

### ISSUE THREAD

**Issue by Manishdeswal36** [microsoft/pylance-release#4841] opened 2023-09-15 10:10 UTC
Type: <b>Bug</b>

whenever I type vs code intelliSense show double suggestion 
and whenever i the the describtion of a function it also show double times
I use chagpt , watch youtube, read stackoverflow but did not solve my promblem please help me 

Extension version: 2023.9.12
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.09GB free)|
|Process Argv|--crash-reporter-id 86a92dec-106c-4f11-ad04-6cde7c65f00a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by Manishdeswal36** [comment] 2023-09-15 10:21
[](url)
![Screenshot (394)](https://github.com/microsoft/pylance-release/assets/114354904/4be0e634-b31d-41cb-894f-8eac43921553)

![Screenshot (395)](https://github.com/microsoft/pylance-release/assets/114354904/65900883-0d11-4d08-abca-0bb784b813e4)

Here are the images U see it 

here is my setting file in vscode user + workspace i use
{
    "workbench.sideBar.location": "right",
    "window.zoomLevel": 1,
    "workbench.iconTheme": "material-icon-theme",
    "python.analysis.completeFunctionParens": true,
    "editor.fontSize": 20,
    "terminal.integrated.fontSize": 18,
    "notebook.output.fontSize": 20,
    "security.workspace.trust.untrustedFiles": "prompt",
    "editor.quickSuggestions": {
        "comments": "off",
        "strings": "off"
    },
    "python.languageServer": "Default",
    
    "workbench.colorTheme": "Default Dark Modern"

}

**Comment by debonte** [comment] 2023-09-20 01:46
This is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13596.

**Closed by debonte** 2023-09-20 01:46 UTC
Labels: needs repro

**Comment by Manishdeswal36** [comment] 2023-09-22 00:56
What is the solution to the problem?

what setting i change 
what steps I  performed to solve problem 
I am a beginner in programming not find solution on youtube and chatgpt  please guide me

**Comment by debonte** [comment] 2023-09-22 04:52
It's a bug in the Jupyter extension which has no workaround as far as I know. You can get more details at the link I provided above. Follow that issue to be notified when there is more information. Up voting it might help them prioritize fixing it.
