### ISSUE TITLE
with ExitStack : Unreachable code

### ISSUE THREAD

**Issue by mlamarre** [microsoft/pylance-release#842] opened 2021-01-16 18:20 UTC
```
from contextlib import ExitStack
with ExitStack() as exit_stack:
    print('Hey')
print('You')
```
Get:
Code below `with ExitStack() as exit_stack` is grey, unreachable.

Expected:
Reachable

This is regression, it was working this morning.

-   Language Server version: 2021.1.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): miniconda python 3.7
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

**Comment by erictraut** [comment] 2021-01-16 18:22
Thanks for reporting.

This is a duplicate of https://github.com/microsoft/pylance-release/issues/717. It will be fixed in the next release.

**Comment by jakebailey** [comment] 2021-01-19 18:14
Closing as a dupe of #494.

**Closed by jakebailey** 2021-01-19 18:14 UTC
Labels: duplicate
