### ISSUE TITLE
reportMissingModuleSource: requests.packages.urllib3.util.retry

### ISSUE THREAD

**Issue by andreighinea1** [microsoft/pylance-release#1323] opened 2021-05-20 18:12 UTC
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: Windows 10 Pro, 20H2, 19042.985
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.4

## Expected behaviour

It should find "requests.packages.urllib3.util.retry"

## Actual behaviour

Import "requests.packages.urllib3.util.retry" could not be resolved from source Pylance(reportMissingModuleSource)

## Logs

```
Nothing is printed just for importing
```

## Code Snippet / Additional information

```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
```

**Comment by jakebailey** [comment] 2021-05-20 18:15
Duplicate of #597.

`requests` does some shady at-runtime things to reexport these modules.

**Closed by jakebailey** 2021-05-20 18:15 UTC
Labels: triage
