### ISSUE TITLE
rename symbol not working across files

### ISSUE THREAD

**Issue by wardy3** [microsoft/pylance-release#3390] opened 2022-09-23 03:46 UTC
Type: <b>Bug</b>

1. create a function in file a.py
2. import that function in file b.py
3. rename the function using F2 (rename symbol) in file a.py
3.  b.py import should be changed but it isn't, and causes an error

The function name is changed but that change isn't reflected in the importing file. It works in VSCode on the same file on the same laptop

VSCode Insiders:

Version: 1.72.0-insider (Universal)
Commit: ba515cdbb48470c116884deb6de17981d341ec06
Date: 2022-09-22T07:26:17.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

VSCode (not insiders):

Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

---

Extension version: 2022.15.12631011
VS Code version: Code - Insiders 1.72.0-insider (Universal) (ba515cdbb48470c116884deb6de17981d341ec06, 2022-09-22T07:26:17.254Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (0.52GB free)|
|Process Argv|--crash-reporter-id e45c21e3-3270-4be4-bf1b-d02853448a5e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30568093
vscccc:30564267
pyindex848:30568094

```

</details>

**Comment by judej** [comment] 2022-09-26 17:57
Thanks for the report. Could you please specify what the Pylance version is for the two cases?

Also, do you have a pyproject.toml?

Finally, would you please include the logs? [found in troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by wardy3** [comment] 2022-09-27 00:47
Thanks Jude

This morning’s updates seem to have fixed it. I just did a simple `from b import thing` change and it’s working across files.

I’ll create a new case if I find a non-trivial case and include info as below

Thanks again

From: Jude Kavalam ***@***.***>
Date: Tuesday, 27 September 2022 at 03:57
To: microsoft/pylance-release ***@***.***>
Cc: Wardy ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/pylance-release] rename symbol not working across files (Issue #3390)

Thanks for the report. Could you please specify what the Pylance version is for the two cases?

Also, do you have a pyproject.toml?

Finally, would you please include the logs? found in troubleshooting guide<https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue>?

**Comment by debonte** [comment] 2022-09-27 02:58
Likely a duplicate of #3348

**Closed by debonte** 2022-09-27 02:58 UTC
Labels: duplicate
