### ISSUE TITLE
Recognize context manager contextlib.suppress as a hidden try/except

### ISSUE THREAD

**Issue by fredrikw** [microsoft/pylance-release#503] opened 2020-10-19 12:36 UTC
## Environment data

-   Language Server version: v2020.10.1
-   OS and version: Windows10 Pro v1903
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

## Expected behaviour

Pylance should recognize the context manager `contextlib.suppress` as a hidden try/except

## Actual behaviour

Code appearing after a `with suppress(exception):` block will be marked as unreachable.

## Code Snippet / Additional information

```python
from contextlib import suppress

test = 'test'


def testfunction():
    with suppress(IndexError):
        return test[10]
    print("Did reach this code")
    return 't'


testfunction()
```

Running this as a script will print "Did reach this code" but Pylance will mark lines 9 and 10 as unreachable.

**Comment by erictraut** [comment] 2020-10-19 14:46
This appears to be a duplicate of #494

**Comment by jakebailey** [comment] 2020-10-19 17:04
Yep.

**Closed by jakebailey** 2020-10-19 17:04 UTC
Labels: triage
