### ISSUE TITLE
Stub files 

### ISSUE THREAD

**Issue by Masynchin** [microsoft/pylance-release#1663] opened 2021-08-09 17:53 UTC
Issue Type: <b>Bug</b>

I use default settings, and unable to do pyi stub files. How to do python stub files in VS Code?

Extension version: 2021.8.1105858891
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:31.568Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Turion(tm) II Dual-Core Mobile M520 (2 x 2294)|
|GPU Status|2d_canvas: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.12GB (0.54GB free)|
|Process Argv|--crash-reporter-id 6f544008-845b-4f8c-81f4-28fa832f4a01|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473
bridge0723:30346310

```

</details>

**Comment by jakebailey** [comment] 2021-08-11 17:03
Writing stubs is just creating `pyi` files in the location of the modules you're trying to stub out; is there something else you're trying to do here? Pylance definitely supports writing stub files.

**Comment by Masynchin** [comment] 2021-08-11 17:33
> Writing stubs is just creating `pyi` files in the location of the modules you're trying to stub out; is there something else you're trying to do here? Pylance definitely supports writing stub files.

I created two files in one directory right now:

`example.py`
```python
def adder(left, right):
    return left + right
```

`example.pyi`
```python
def adder(left: int, right: int) -> int: ...
```

Hover at `adder` in `example.py` tell me `(function) adder: (left, right) -> Any`.
Is I placed stub in incorrect place or something else?

**Comment by erictraut** [comment] 2021-08-11 17:41
Type stubs describe the interface contract for a library so consumers of that library can apply static type checking. If you want to apply type checking to your own code, you need to include the type annotations within the ".py" file, like this:

```python
def adder(left: int, right: int) -> int:
    return left + right
```

**Comment by jakebailey** [comment] 2021-08-11 17:43
Yeah, this is a dupe of #1238, then. We don't apply types from a stub back to the py file it describes.

**Closed by jakebailey** 2021-08-11 17:43 UTC
Labels: triage

**Comment by Masynchin** [comment] 2021-08-11 17:55
> If you want to apply type checking to your own code, you need to include the type annotations within the ".py"

So sad because the reason of my issue is that I don't want to write this (in my opinion) ugly code right in the ".py" files. But I have no choice :)
