### ISSUE TITLE
Allow wildcard (*) on `extraPaths` options 

### ISSUE THREAD

**Issue by pattrickrice** [microsoft/pylance-release#1515] opened 2021-07-01 17:21 UTC
- [x] Searched existing issues

**Description**
People who use tools like bazel and https://github.com/lhftio/io_bazel_rules_python may find that each dep ends up in isolated folders that are not discoverable if you just list the parent. It would be nice to be able to wildcard a set of directories that may be used for extra paths. Apologies if this feature exists and I may be using it wrong.  

**Example**
```json
"${workspaceFolder}/python_modules/some_prefix__*_ my_deps"
```

**Comment by erictraut** [comment] 2021-07-01 17:30
One potential challenge... For import resolution, the order of paths is important. A wildcard or globs specifier would be ambiguous in ordering.

**Comment by pattrickrice** [comment] 2021-07-01 23:31
Hmm, I see the challenge, maybe if users specified order for the ones that mattered and then globbed, the glob could be filtered to remove the duplicates already specified? 

Something like 
```json
{
    "python.analysis.extraPaths": [
        "${workspaceFolder}/python_modules/some_prefix__module_b_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_a_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__*_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_c_ my_deps",
    ]
}
```
Would resolve to 
```javascript
[
        "${workspaceFolder}/python_modules/some_prefix__module_b_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_a_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_d_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_e_ my_deps",
        "${workspaceFolder}/python_modules/some_prefix__module_c_ my_deps",
]
```

**Comment by jakebailey** [comment] 2021-07-06 17:12
This is a duplicate of #973; please comment/vote there.

**Closed by jakebailey** 2021-07-06 17:12 UTC
Labels: enhancement, needs decision
