### ISSUE TITLE
%%time in jupyter cell causes incorrect Pylance warning

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/pylance-release#3859] opened 2023-01-24 02:01 UTC
-   Language Server version: v2023.1.30
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

## Code Snippet

```python
%%time
x = 1
```

```python
x
```

## Repro Steps

Introduction of `%%time` magic command above results in `"x" is not defined` message from Pylance (when hovering over the yellow squiggle) in subsequent cells.

![image](https://user-images.githubusercontent.com/5028974/214197340-6ae7470f-b57b-458b-baf8-0d1f44d94d84.png)

If  `%%time`  is removed the warning disappears.

**Comment by debonte** [comment] 2023-01-24 20:12
Duplicate of https://github.com/microsoft/pylance-release/discussions/3851?

**Comment by judej** [comment] 2023-01-24 21:49
Yes, will be resolved with we resolved #3851

**Closed by judej** 2023-01-24 21:49 UTC
Labels: triage-needed
