### ISSUE TITLE
Imports of installed packages are often not resolved in Jupyter notebooks

### ISSUE THREAD

**Issue by kirilllzaitsev** [microsoft/pylance-release#6541] opened 2024-10-08 21:43 UTC
## Environment data

-   Pylance version: v2024.10.1
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14, Anaconda

## Code Snippet

```python
import typing
import torch
```

`import torch` might get `Import "torch.nn" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)`. `import typing` (standard library) works correctly.

![image](https://github.com/user-attachments/assets/caee92d6-8d1e-4ba7-993e-54488054de2f)

Although some non-standard libraries may nonetheless be navigated to:

![image](https://github.com/user-attachments/assets/551abd85-bcb7-4aba-a540-78cdb3127f14)

Two notes:
1. The problem correlates with current CPU/memory usage.
2. Sometimes it may appear due to Jupyter unable to repetitively load the selected Python kernel, but it is gone as soon as the kernel is selected.

## Repro Steps

1. It is not deterministic, may appear occasionally upon opening a notebook. Does not disappear after calling `Restart language server`

## Expected behavior

The imports of installed modules are found

## Actual behavior

The imports are not found

## Logs

```
2024-10-08 23:39:11.807 [info] [Info  - 11:39:11 PM] Server process exited successfully
2024-10-08 23:39:12.301 [info] (Client) Pylance async client (2024.10.1) started with python extension (2024.14.1)
2024-10-08 23:39:12.862 [info] [Info  - 11:39:12 PM] (925816) Server root directory: file:///home/master/.vscode/extensions/ms-python.vscode-pylance-2024.10.1/dist
2024-10-08 23:39:12.863 [info] [Info  - 11:39:12 PM] (925816) Pylance language server 2024.10.1 (pyright version 1.1.382, commit e46efc6b) starting
2024-10-08 23:39:12.869 [info] [Info  - 11:39:12 PM] (925816) Starting service instance "pose_estimation"
2024-10-08 23:39:12.923 [info] [Info  - 11:39:12 PM] (925816) Loading configuration file at /user/pyrightconfig.json
2024-10-08 23:39:12.925 [info] [Info  - 11:39:12 PM] (925816) Setting pythonPath for service "pose_estimation": "/opt/miniconda3/envs/pt/bin/python"
2024-10-08 23:39:12.926 [info] [Info  - 11:39:12 PM] (925816) No include entries specified; assuming /user
2024-10-08 23:39:12.961 [info] [Info  - 11:39:12 PM] (925816) Assuming Python version 3.10.14.final.0
2024-10-08 23:39:13.411 [info] [Info  - 11:39:13 PM] (925816) Found 497 source files
2024-10-08 23:39:13.806 [info] [Info  - 11:39:13 PM] (925816) Background analysis(1) root directory: file:///home/master/.vscode/extensions/ms-python.vscode-pylance-2024.10.1/dist
2024-10-08 23:39:13.807 [info] [Info  - 11:39:13 PM] (925816) Background analysis(1) started
2024-10-08 23:39:13.892 [info] [Info  - 11:39:13 PM] (925816) Starting service instance "pose_estimation"
2024-10-08 23:39:13.919 [info] [Info  - 11:39:13 PM] (925816) Loading configuration file at /user/pyrightconfig.json
2024-10-08 23:39:13.920 [info] [Info  - 11:39:13 PM] (925816) Setting pythonPath for service "pose_estimation": "/user"
2024-10-08 23:39:13.920 [info] [Info  - 11:39:13 PM] (925816) No include entries specified; assuming /user
2024-10-08 23:39:14.296 [info] [Info  - 11:39:14 PM] (925816) Found 497 source files
2024-10-08 23:39:14.429 [info] [Info  - 11:39:14 PM] (925816) Indexer background runner(2) root directory: file:///home/master/.vscode/extensions/ms-python.vscode-pylance-2024.10.1/dist (index)
2024-10-08 23:39:14.429 [info] [Info  - 11:39:14 PM] (925816) Indexing(2) started
2024-10-08 23:39:14.568 [info] [Info  - 11:39:14 PM] (925816) Background analysis(3) root directory: file:///home/master/.vscode/extensions/ms-python.vscode-pylance-2024.10.1/dist
2024-10-08 23:39:14.571 [info] [Info  - 11:39:14 PM] (925816) Background analysis(3) started
2024-10-08 23:39:15.020 [info] [Info  - 11:39:15 PM] (925816) scanned(2) 588 files over 1 exec env
2024-10-08 23:39:15.566 [info] [Info  - 11:39:15 PM] (925816) indexed(2) 588 files over 1 exec env
2024-10-08 23:39:16.056 [info] [Info  - 11:39:16 PM] (925816) scanned(2) 4 files over 1 exec env
2024-10-08 23:39:16.327 [info] [Info  - 11:39:16 PM] (925816) indexed(2) 4 files over 1 exec env
2024-10-08 23:39:16.339 [info] [Info  - 11:39:16 PM] (925816) Indexing finished(2).
2024-10-08 23:39:16.609 [info] [Info  - 11:39:16 PM] (925816) [BG(1)] Long operation: SemanticTokens full at file:///user/notebooks/train_baseline_exp.ipynb.py#X14sZmlsZQ%3D%3D (2398ms)

```

**Comment by rchiodo** [comment] 2024-10-08 21:53
I would hazard a guess this is a dupe of this issue here:
https://github.com/microsoft/vscode-jupyter/issues/15965

What's your version of the jupyter extension?

**Comment by kirilllzaitsev** [comment] 2024-10-08 22:11
v2024.8.1

**Comment by rchiodo** [comment] 2024-10-08 22:19
That would explain the error then. I don't believe this fix has shipped in anything but the latest prerelease for the Jupyter extension.

**Closed by rchiodo** 2024-10-08 22:19 UTC
Labels: needs repro

**Comment by kirilllzaitsev** [comment] 2024-10-18 07:24
Unfortunately, the pre-release version has the same problem
