### ISSUE TITLE
Internal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/pylance-release#2427] opened 2022-03-02 09:26 UTC
Hope this is enough to track the issue - if necessary I could do log it. Alas, this error pops up after several minutes...

## Environment data
Visual Studio 17.1.0
Python with Pylance - 17.0.21344.1
Windows 10
Python 3.9.7
Conda 4.11.0

## Actual behaviour
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		An internal error occurred while type checking file "C:\Users\Admin\Documents\Visual Studio 2019\Projects\xx.py": RangeError: Maximum call stack size exceeded
    at Set.has (<anonymous>)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:896:40)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at isFlowNodeReachableRecursive (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)
    at e (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:966:29)

**Comment by erictraut** [comment] 2022-03-02 15:49
Thanks for reporting this. I've seen this stack trace in our crash reporting telemetry, but there's not enough information in the stack trace for me to diagnose the problem. I will need additional details. The easiest and fastest way for me to diagnose the problem is to get access to the code in question. By any chance, is your code checked in to a public github repo? If not, would you be willing & able to create a minimal repro case and either post it here or create a temporary private repo for me? Thanks for your help in tracking this down.

**Comment by excubo-jg** [comment] 2022-03-02 18:50
Many thanks for coming back. I sent you an invite for a repository pylancedemo. At my end I got this pylance-output which seems to recreate the error:

Info: Info: Background analysis(1) root directory: c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started

Info: Info: [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (8147ms)[BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (8785ms)

Info: Info: [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (3400ms)[BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (3400ms)

Error: An internal error occurred while type checking file "C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py": RangeError: Maximum call stack size exceeded
    at forEach (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:484:52)
    at Array.forEach (<anonymous>)
    at getTypeFromFlowNode (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:483:47)
    at Object.getTypeFromCodeFlow (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:875:20)
    at getTypeFromCodeFlow (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:15049:39)
    at getFlowTypeOfReference (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:15027:16)
    at getTypeFromName (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3227:44)
    at Object.getTypeOfExpression (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:734:30)
    at getTypeNarrowingCallback (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeGuards.ts:195:49)
    at t (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:674:59)
Info: [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (110210ms)Info: Error: 
[BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (110210ms)Error performing analysis: RangeError: Maximum call stack size exceeded
    at forEach (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:484:52)
    at Array.forEach (<anonymous>)
    at getTypeFromFlowNode (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:483:47)
    at Object.getTypeFromCodeFlow (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:875:20)
    at getTypeFromCodeFlow (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:15049:39)
    at getFlowTypeOfReference (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:15027:16)
    at getTypeFromName (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3227:44)
    at Object.getTypeOfExpression (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeEvaluator.ts:734:30)
    at getTypeNarrowingCallback (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\typeGuards.ts:195:49)
    at t (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\analyzer\codeFlowEngine.ts:674:59)

Info: [BG(1)] Long operation: getSemanticTokens full at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (103668ms)
Info: [BG(1)] Long operation: getSemanticTokens full at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (105691ms)

**Closed** 2022-04-12 20:58 UTC
Labels: needs investigation

**Comment by excubo-jg** [comment] 2022-04-21 21:42
I have updated the bug report in pyright #3138 as the problems are still present in 2022.3.3
