### ISSUE TITLE
Library is overriding the stdlib module. 

### ISSUE THREAD

**Issue by mohsinzz** [microsoft/pylance-release#4293] opened 2023-04-28 08:33 UTC
I am getting below warning and my program does not run.

"c:\Machine Learning Project\pyenv\Lib\datetime.py" is overriding the stdlib module "datetime"

The warning is being shown for many libraries and my program does not run.

How do I fix this issue.

**Comment by debonte** [comment] 2023-04-28 13:41
@mohsinzz, my first thought is this sounds like a duplicate of #3751 where Pylance is not automatically excluding your virtual environment directory and you need to manually exclude it with:

```json
  "python.analysis.exclude": ["pyenv"],
```

If that doesn't work, please provide more detail on your project directory and virtual environment directory structure.

**Closed** 2023-05-29 00:23 UTC
Labels: waiting for user response

**Comment by genericHuman12** [comment] 2024-02-20 19:36
Datetime is a module, so you need to change your file name.
