### ISSUE TITLE
Syntax Highlighting fails in jupyter notebook

### ISSUE THREAD

**Issue by grapland0** [microsoft/pylance-release#5543] opened 2024-02-28 22:03 UTC
## Environment data

-   Language Server version: Pylance (sync) language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c)
-   OS and version: win 11 10.0.22631
-   Python: 3.11.6

## Repro Steps

Open a ipynb file in notebook mode, do some operation, switch focus to other docs and switch back. the highlighting goes broken after that.

I can always see error like `Received change text document command for closed file file:///workspaces/moana-cxx-3/moana/analysis/item_sel_ab.ipynb.py#W5sdnNjb2RlLXJlbW90ZQ%3D%3D` just after I find the highlighting dies. (precisely, when start typing something on notebook cell after focus switch back)

Previous version of pylance extension with previous version of vscode (1.86.x) doesn't have this issue.

## Logs

```
2024-02-28 21:39:34.361 [info] (1359660) [FG] binding: file:///root/miniforge3/envs/moana/lib/python3.11/collections/__init__.py (20ms)
2024-02-28 21:39:34.497 [info] [Error - 9:39:34 PM] (1359660) Received change text document command for closed file file:///workspaces/moana-cxx-3/moana/analysis/item_sel_ab.ipynb.py#W5sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-02-28 21:39:35.003 [info] (1359660) Background analysis message: getSemanticTokens delta
2024-02-28 21:39:35.003 [info] (1359660) [BG(2)] getSemanticTokens delta previousResultId:1709156194982 at file:///workspaces/moana-cxx-3/moana/analysis/item_sel_ab.ipynb.py#W5sdnNjb2RlLXJlbW90ZQ%3D%3D (0ms)
2024-02-28 21:39:39.865 [info] [Info  - 9:39:39 PM] (1359660) SourceFile: Received fs event 'change' for path '/workspaces/moana-cxx-3/moana/analysis/item_sel_ab.ipynb'
```

**Comment by rchiodo** [comment] 2024-02-28 22:57
I believe the problem here is a change in the order of `textDocument/didOpen` vs `notebook/didOpen` events. In VS code stable we seem to always get a `notebook/didOpen` event before the `textDocument/didOpen` events for the cells.

**Comment by rchiodo** [comment] 2024-02-28 22:57
@rebornix do you know if the ordering around text document events might have changed recently in VS code?

**Comment by rchiodo** [comment] 2024-02-28 23:10
Actually it seems in stable we NEVER get `textDocument/didOpen` for notebook cells.

**Comment by rchiodo** [comment] 2024-02-28 23:10
Nor on windows. So something in VS code insiders is suddenly sending these for WSL/Linux notebooks.

**Comment by rchiodo** [comment] 2024-02-28 23:36
To workaround this issue, switch back to VS code stable.

**Comment by grapland0** [comment] 2024-02-29 02:11
1.87 is already on the stable channel.

**Comment by JannisZeller** [comment] 2024-02-29 11:11
Hello everybody. I have a similar issue in VS code 1.87 (stable). When first starting VS code Notebooks getting parsed and displayed correctly (also when opening them from the files-tab). As soon as I change anything, Pylance is not working and logs (for every keystroke):
```log
<time> [info] [Error - <time>] (<some-int>) Received change text document command for closed file file://<path-to-notebook>#<some-hash>
```
Note, that not only the syntax highlighting breaks, but also suggestions etc. Keywords like `def`, `if`, and alike still get highlighted correctly though.

If I close and reopen the notebook, the error does not occur for existing cells, but occurs again for newly created cells, in which Pylance is then also not working. Though Pylance still keeps working in the cells, that already existed when opening the notebook. The issue has been present since this morning, when I updated VS code to 1.87.

I am using WSL2. Pylance in VS code used in Windows directly works without issues.

### Environment-Infos:
OS: Windows 11 Pro (10.0.22631 Build 22631) with WSL 2 (Ubuntu 22.04.4 LTS)
VS Code: 1.87 sable

_Extensions:_
- Jupyter: v2024.2.0
- Jupyter Notebook Renderers: v1.0.17
- Python: v2024.2.0
- Python Debugger: v2024.2.0
- Pylance: v2024.2.0

### Logs (from startup)
```log
2024-02-29 12:01:33.818 [info] (Client) Pylance async client (2024.2.2) started with python extension (2024.2.0)
2024-02-29 12:01:34.232 [info] [Info  - 12:01:34 PM] (39698) Pylance language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c) starting
2024-02-29 12:01:34.258 [info] [Info  - 12:01:34 PM] (39698) Server root directory: file:///home/<username>/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-29 12:01:34.258 [info] [Info  - 12:01:34 PM] (39698) Starting service instance "<foldername>"
2024-02-29 12:01:34.309 [info] [Info  - 12:01:34 PM] (39698) Setting pythonPath for service "<foldername>": "/bin/python3"
2024-02-29 12:01:34.309 [info] [Info  - 12:01:34 PM] (39698) Setting environmentName for service "<foldername>": "3.10.12 (global)"
2024-02-29 12:01:34.330 [info] [Info  - 12:01:34 PM] (39698) Assuming Python version 3.10
2024-02-29 12:01:34.375 [info] [Info  - 12:01:34 PM] (39698) Found 1 source file
2024-02-29 12:01:34.380 [info] [Info  - 12:01:34 PM] (39698) Starting service instance "<foldername>"
2024-02-29 12:01:34.401 [info] [Info  - 12:01:34 PM] (39698) Setting pythonPath for service "<foldername>": "/home/miniconda3/bin/python"
2024-02-29 12:01:34.402 [info] [Info  - 12:01:34 PM] (39698) Setting environmentName for service "<foldername>": "3.10.12 (global)"
2024-02-29 12:01:34.421 [info] [Info  - 12:01:34 PM] (39698) Assuming Python version 3.12
2024-02-29 12:01:34.455 [info] [Info  - 12:01:34 PM] (39698) Found 1 source file
2024-02-29 12:01:34.883 [info] [Info  - 12:01:34 PM] (39698) Background analysis(1) root directory: file:///home/<username>/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-29 12:01:34.883 [info] [Info  - 12:01:34 PM] (39698) Background analysis(1) started
2024-02-29 12:01:34.953 [info] [Info  - 12:01:34 PM] (39698) Indexer background runner(3) root directory: file:///home/<username>/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist (index)
2024-02-29 12:01:34.953 [info] [Info  - 12:01:34 PM] (39698) Indexing(3) started
2024-02-29 12:01:34.959 [info] [Info  - 12:01:34 PM] (39698) Background analysis(2) root directory: file:///home/<username>/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-02-29 12:01:34.961 [info] [Info  - 12:01:34 PM] (39698) Background analysis(2) started
2024-02-29 12:01:35.522 [info] [Info  - 12:01:35 PM] (39698) scanned(3) 115 files over 1 exec env
2024-02-29 12:01:36.130 [info] [Info  - 12:01:36 PM] (39698) indexed(3) 81 files over 1 exec env
2024-02-29 12:01:36.214 [info] [Info  - 12:01:36 PM] (39698) Indexing finished(3).
```
Now I start making changes:
```logs
2024-02-29 12:01:46.117 [info] [Error - 12:01:46 PM] (39698) Received change text document command for closed file file://<path-to-notenook>#<some-hash>
2024-02-29 12:01:46.280 [info] [Error - 12:01:46 PM] (39698) Received change text document command for closed file file://<path-to-notenook>#<some-hash>
```
If I now close the notebook and open it again, I can change existing cells without issues, but when working in newly created cells, the same error occurs.

**Comment by cyclux** [comment] 2024-02-29 14:08
Same issue here, so for now only option is to downgrade VSCode to https://code.visualstudio.com/updates/v1_86?

**Comment by JannisZeller** [comment] 2024-02-29 14:41
> Same issue here, so for now only option is to downgrade VSCode to https://code.visualstudio.com/updates/v1_86? Edit: Can confirm, downgrade to 1.86.2 fixes it, auto update set to none for now

Downgrading indeed worked for me. For people like me: You can simply downgrade VS code in Windows. There is no separate install in the WSL's OS (trust me, I searched it for 15 minutes...).

**Comment by DavidArmendariz** [comment] 2024-03-03 21:30
When downgrading to 1.82.2 now I can't select a kernel for jupyter notebooks.

**Comment by trailfog** [comment] 2024-03-03 21:46
> When downgrading to 1.82.2 now I can't select a kernel for jupyter notebooks.

@DavidArmendariz I had the same issue. You will need to re-install the Jupyter extension. I did this by selecting "Install Another Version..." from the Gear-Icon menu and simply selecting the latest version. Everything worked without reloading the window.

**Comment by DavidArmendariz** [comment] 2024-03-03 22:06
@trailfog Thank you very much. Do we know when this issues is going to be fixed?

**Comment by JannisZeller** [comment] 2024-03-04 06:22
> @trailfog Thank you very much. Do we know when this issues is going to be fixed in the future versions?

You probably need to follow https://github.com/microsoft/vscode/issues/206532 for updates.

**Comment by JannisZeller** [comment] 2024-03-04 06:25
> > When downgrading to 1.82.2 now I can't select a kernel for jupyter notebooks.
> 
> @DavidArmendariz I had the same issue. You will need to re-install the Jupyter extension. I did this by selecting "Install Another Version..." from the Gear-Icon menu and simply selecting the latest version. Everything worked without reloading the window.

This is also true when downgrading to 1.86.x. This is because the newest version of the Jupyter extension seems to be already incompatible with anything below 1.87, and therefore gets deactivated, which is also clearly visible in the extensions tab. Just install some version of the Jupyter extension from before the 1.87 update should work - at least it did for me.

**Comment by rchiodo** [comment] 2024-03-05 18:08
This has been fixed in the latest VS code insiders. Using this version:

Version: 1.88.0-insider (user setup)
Commit: d73fa8b14a6c873958d00a7d7ad13fcb540a052c
Date: 2024-03-05T05:47:29.930Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

I can no longer reproduce the problem.

**Closed by rchiodo** 2024-03-05 18:08 UTC
Labels: waiting for upstream
