### ISSUE TITLE
Pylance does not show correct function parameters for TypedDict

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/pylance-release#5360] opened 2024-01-17 16:12 UTC
Type: <b>Bug</b>

I have a TypedDict `BatchItem`:

```py
class BatchItem(TypedDict):
    url: str
    capture_dupe_status: Literal["New capture", "Already captured", ""]
    new_capture_status: str | Literal[""]
    archive_message: str
    archive_info: str | Literal[""]
    first_archive_status: Literal["First Archive", ""]
```

However, when I do `BatchItem()` and my cursor is in the middle of the parentheses, I get `(*args, **kwargs) -> BatchItem`. I would have expected the parentheses to be `(*args, *, url: str, capture_dupe_status: Literal["New capture", "Already captured", ""], new_capture_status: str | Literal[""], archive_message: str, archive_info: str | Literal[""], first_archive_status: Literal["First Archive", ""]) -> BatchItem`.

Extension version: 2023.12.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:16.874Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 2b0708f4-d206-4f56-bb5c-21ca647cc418|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by PythonCoderAS** [comment] 2024-01-17 16:13
![Screenshot 2024-01-17 at 11 03 27 AM](https://github.com/microsoft/pylance-release/assets/13932583/406d77dc-4d58-45cd-886d-c65e81850ec1)
![Screenshot 2024-01-17 at 11 03 18 AM](https://github.com/microsoft/pylance-release/assets/13932583/9e1c3729-33a0-4a40-9556-002f3212dc06)

**Comment by debonte** [comment] 2024-01-17 18:05
Duplicate of #5151

**Closed by debonte** 2024-01-17 18:05 UTC
Labels: needs repro
