### ISSUE TITLE
Pylance Error 

### ISSUE THREAD

**Issue by lg93lggt** [microsoft/pylance-release#1398] opened 2021-06-04 07:26 UTC
<p>Issue Type: <b>Bug</b></p>
<p>[Info  - 下午3:20:21] Pylance language server 2021.6.0 (pyright 209c8040) starting<br>
[Info  - 下午3:20:21] Server root directory: /home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:20:21] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
Libzip Error: Not a zip archive<br>
at makeLibzipError 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipFS.js:149:29)<br>
at new m 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipFS.js:121:28)<br>
at getZipSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:784:28)<br>
at g.makeCallSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:665:21)<br>
at g.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:232:21)<br>
at c.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:71:28)<br>
at r.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:71:28)<br>
at T.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/common/fileSystem.ts:213:23)<br>
at t.PyrightFileSystem.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/pyrightFileSystem.ts:63:29)<br>
at /home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/analyzer/service.ts:1027:53<br>
[Info  - 下午3:23:43] Connection to server got closed. Server will restart.<br>
[Error - 下午3:23:43] Request textDocument/semanticTokens/full failed.<br>
Error: Connection got disposed.<br>
at Object.dispose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:68124)<br>
at Object.dispose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:177951)<br>
at E.handleConnectionClosed 
(/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:178163)<br>
at E.handleConnectionClosed 
(/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:21817)<br>
at t (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:176256)<br>
at invoke (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:322271)<br>
at o.fire (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:323032)<br>
at X (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:57486)<br>
at invoke (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:322271)<br>
at o.fire (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:323032)<br>
at d.fireClose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:47555)<br>
at ChildProcess. (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:318001)<br>
at ChildProcess.emit (events.js:327:22)<br>
at maybeClose (internal/child_process.js:1048:16)<br>
at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)<br>
[Info  - 下午3:23:43] Pylance language server 2021.6.0 (pyright 209c8040) starting<br>
[Info  - 下午3:23:43] Server root directory: /home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:23:44] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
Libzip Error: Not a zip archive<br>
at makeLibzipError 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipFS.js:149:29)<br>
at new m 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipFS.js:121:28)<br>
at getZipSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:784:28)<br>
at g.makeCallSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:665:21)<br>
at g.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ZipOpenFS.js:232:21)<br>
at c.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:71:28)<br>
at r.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:71:28)<br>
at T.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/common/fileSystem.ts:213:23)<br>
at t.PyrightFileSystem.existsSync 
(/home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/pyrightFileSystem.ts:63:29)<br>
at /home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist/pyright-internal/src/analyzer/service.ts:1027:53<br>
[Info  - 下午3:25:13] Connection to server got closed. Server will restart.<br>
[Error - 下午3:25:13] Request textDocument/semanticTokens/full failed.<br>
Error: Connection got disposed.<br>
at Object.dispose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:68124)<br>
at Object.dispose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:177951)<br>
at E.handleConnectionClosed 
(/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:178163)<br>
at E.handleConnectionClosed 
(/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:21817)<br>
at t (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:176256)<br>
at invoke (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:322271)<br>
at o.fire (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:323032)<br>
at X (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:57486)<br>
at invoke (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:322271)<br>
at o.fire (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:323032)<br>
at d.fireClose (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:47555)<br>
at ChildProcess. (/home/veily3/.vscode/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:318001)<br>
at ChildProcess.emit (events.js:327:22)<br>
at maybeClose (internal/child_process.js:1048:16)<br>
at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)<br>
[Info  - 下午3:25:14] Pylance language server 2021.6.0 (pyright 209c8040) starting<br>
[Info  - 下午3:25:14] Server root directory: /home/veily3/.vscode/extensions/ms-python.vscode-pylance-2021.6.0/dist<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js<br>
[Error - 下午3:25:14] Exception received when installing recursive file 
system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The 
feature watch recursively is unavailable on the current platform, which 
is being used to run Node.js</p>
<p>VS Code version: Code 1.56.2 (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/microsoft/vscode/commit/054a9295330880ed74ceaedda236253b4f39a335/hovercard" href="https://github.com/microsoft/vscode/commit/054a9295330880ed74ceaedda236253b4f39a335"><tt>054a929</tt></a>, 2021-05-12T16:45:26.313Z)<br>
OS version: Linux x64 5.4.0-71-generic</p>
<details open="">
<summary>System Info</summary>

Item | Value
-- | --
CPUs | AMD Ryzen 5 2600X Six-Core Processor (12 x 2083)
GPU Status | 2d_canvas: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offopengl: enabled_onrasterization: disabled_softwareskia_renderer: enabled_onvideo_decode: disabled_softwarevulkan: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 0
Memory (System) | 15.63GB (3.14GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id f3a2fa84-eeb0-4026-8fe4-6a4badf9b815
Screen Reader | no
VM | 0%
DESKTOP_SESSION | ubuntu
XDG_CURRENT_DESKTOP | Unity
XDG_SESSION_DESKTOP | ubuntu
XDG_SESSION_TYPE | x11

</details><details open=""><summary>Extensions (56)</summary>

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.1.0
matlab-formatter | Aff | 2.8.7
matlab-interactive-terminal | apo | 0.3.4
code-gnu-global | aus | 0.2.2
matlab-extension-pack | bat | 0.1.0
blender-python-code-templates | ble | 0.9.6
matlab-code-run | bra | 1.0.2
bracket-pair-colorizer | Coe | 1.0.61
doxdocgen | csc | 1.3.2
docs-markdown | doc | 0.2.94
simply-view-image-for-python-debugging | ela | 0.1.0
matlab | Gim | 2.0.1
vscode-pull-request-github | Git | 0.26.0
gc-excelviewer | Gra | 3.0.42
beautify | Hoo | 1.5.0
comment-translate | int | 1.4.2
path-autocomplete | ion | 1.17.1
latex-workshop | Jam | 8.18.0
better-cpp-syntax | jef | 1.15.5
simply-view-image-for-python-opencv-debugging | joh | 0.0.8
vsc-python-indent | Kev | 1.14.2
vscode-gutter-preview | kis | 0.27.1
kite | kit | 0.146.0
vscode-cudacpp | kri | 0.1.1
MagicPython | mag | 1.1.0
theme-monokai-pro-vscode | mon | 1.1.19
vscode-docker | ms- | 1.13.0
vscode-language-pack-zh-hans | MS- | 1.56.2
anaconda-extension-pack | ms- | 1.0.1
python | ms- | 2021.6.897246044-dev
vscode-pylance | ms- | 2021.6.0
jupyter | ms- | 2021.6.832593372
remote-containers | ms- | 0.177.2
remote-ssh | ms- | 0.65.4
remote-ssh-edit | ms- | 0.65.6
remote-wsl | ms- | 0.56.4
cmake-tools | ms- | 1.7.3
cpptools | ms- | 1.4.0
cpptools-extension-pack | ms- | 1.0.0
vsliveshare | ms- | 1.0.4360
vsliveshare-audio | ms- | 0.1.91
vscode-sanddance | msr | 3.2.0
autodocstring | njp | 0.5.4
vscode-python-typehint | njq | 1.4.1
material-icon-theme | PKi | 4.7.0
vscode-commons | red | 0.0.6
vscode-yaml | red | 0.19.2
matlab-complete | Sla | 1.1.1
vscode-3dviewer | sle | 0.2.2
cmake | twx | 0.0.17
codelf | unb | 11.7.0
vscodeintellicode | Vis | 1.2.14
vscode-icons | vsc | 11.4.0
better-align | wwm | 1.1.6
pyqt-integration | zho | 0.2.0
material-theme | zhu | 3.10.14

<p>(7 theme extensions excluded)</p>
</details><details open="">
<summary>A/B Experiments</summary>
<div class="snippet-clipboard-content position-relative"><pre><code>vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

</code></pre></div></details>

**Comment by jakebailey** [comment] 2021-06-04 21:32
Duplicate of #1398.

**Closed by jakebailey** 2021-06-04 21:32 UTC
Labels: triage

**Comment by jakebailey** [comment] 2021-06-04 21:34
Err, #1397, I mean. 🙂
