### ISSUE TITLE
Symbol renaming does not work.

### ISSUE THREAD

**Issue by L117** [microsoft/pylance-release#1517] opened 2021-07-01 22:16 UTC
**Describe the bug**
When you open freestanding python file and try to rename symbol, nothing happens.

**To Reproduce**
1. Create empty directory.
2. Create empty python file inside it.
3. Open it with your editor of choice (Tried with Visual Studio Code and Sublime Text 4).
4. Type something like:
   ```
   def foo():
       pass
   ```
5. Save it.
6. Try to rename symbol by clicking on function name and choosing "Rename symbol" (VS Code).
7. See a popup message "No result". 

**Expected behavior**
Symbol gets renamed.

**VS Code extension or command-line**
Both? v2021.6.944021595

**Comment by L117** [comment] 2021-07-01 23:12
I'm opening a file, not a directory.
Oh, I should have mentioned: I'm using Fedora 34, not Windows.
Here's a video https://0x0.st/-fPD.mkv . Sorry for mkv.

**Comment by bschnurr** [comment] 2021-07-05 21:05
thank you for the report. 
Yes we are aware open file mode is lacking in some features.

**Comment by jakebailey** [comment] 2021-07-06 17:09
This is a duplicate of #1300.

**Closed by jakebailey** 2021-07-06 17:09 UTC
Labels: in backlog
