### ISSUE TITLE
Conflict with pylance syntax highlighting and code completion

### ISSUE THREAD

**Issue by Koowah** [microsoft/pylance-release#4724] opened 2023-08-10 15:18 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Pylance syntax highlighting works at first before giving way to jupyter syntax highlighting after a few seconds (20/30) at which point code completion stops working aswell.
Any idea why this might be ? This started fairly recently.

Thanks for your help 😄 

### VS Code Version

Version: 1.81.0 (user setup) Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97 Date: 2023-08-02T12:37:13.485Z Electron: 22.3.18 ElectronBuildId: 22689846 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.7.1002162226

### Coding Language and Runtime Version

Python 3.11.4

### Language Extension Version (if applicable)

v2023.14.0

### Anaconda Version (if applicable)

23.5.2

### Running Jupyter locally or remotely?

Local

**Comment by Koowah** [comment] 2023-08-17 14:26
Please let me know if there are any type of logs I can provide to help with your task 😃

**Comment by debonte** [comment] 2023-08-17 14:51
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

You might be hitting https://github.com/microsoft/pylance-release/issues/4685.

**Comment by Aegis1863** [comment] 2023-08-21 12:39
I actually think this is the same as microsoft/pylance-release/issues/4708.

**Comment by Koowah** [comment] 2023-08-21 14:37
> Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
> 
> You might be hitting #4685.

@debonte
Hi Erik, 
I think you hit the nail on the head, after playing with my notebook it appears to be #4685 .

Please find the logs attached : to obtain them i reloaded the dev window, ran all the notebook's cells, added one, ran it and deleted it. On deletion, the syntax highlighting did in fact stop working.

[pylogs.txt](https://github.com/microsoft/pylance-release/files/12397090/pylogs.txt)

**Comment by debonte** [comment] 2023-08-23 19:50
It's possible that this behavior was caused by #4733 which is fixed in our latest prerelease build, [2023.8.41](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023841-23-August-2023-PreRelease)

Could you please all to 2023.8.41 and see if your issues are resolved?

**Comment by debonte** [comment] 2023-08-26 16:15
@Koowah, when you see this issue, if you add/delete/reorder a cell, do you see Pylance crash with an error similar to this?

```text
2023-08-26 09:07:01.700 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\temp\temp\4685repro_3\test.ipynb:pylance-notebook-cell:W3sZmlsZQ==.py
    at _0x35bbe7 (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1025282)
    at c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032550
    at _0x114e49.<computed> (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032582)
    at _0x4600bc._onDidChangeNotebookDocumentAsync (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1010710)
```

**Comment by Koowah** [comment] 2023-08-27 12:16
@debonte Pylance works fine when adding or reordering cells. The issue only happens on cell deletion. There is however no error message in the output tab.

**Comment by debonte** [comment] 2023-08-27 15:16
> Pylance works fine when adding or reordering cells. The issue only happens on cell deletion. There is however no error message in the output tab.

I want to make sure we're talking about the same thing. It sounds like you're saying that syntax highlighting, etc stops working when you delete a cell. I'm asking if _after that occurs_, does adding/deleting/reordering a cell cause Pylance to crash.

I'm trying to determine if this is a duplicate of #4685. There are two stages to that bug. First you lose language server functionality (ex. hover, semantic highlighting) as you described above and then if you change the structure of a notebook, Pylance will crash with the `Chained file path...doesn't match cellFilePaths` error.

**Comment by Koowah** [comment] 2023-08-27 18:46
@debonte Sorry I misunderstood. It does indeed cause pylance to crash ! Probably a duplicate of #4685 then 😄

**Comment by debonte** [comment] 2023-08-27 20:12
Excellent, thanks for confirming! I'll resolve this issue as a duplicate. Keep an eye on #4685 for updates.

**Closed by debonte** 2023-08-27 20:12 UTC
Labels: user responded
