### ISSUE TITLE
np.array_split  has type "Module" and is not callable

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#158] opened 2020-07-22 11:40 UTC
## Environment data

-   Language Server version: v2020.7.2
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.10

## Expected behaviour

No type error

## Actual behaviour

Pylance (reportGeneralTypeIssues):
```
"np.array_split(range(1000), 100)" has type "Module" and is not callable
```

## Code Snippet / Additional information

```python
import numpy as np

splits = np.array_split(range(1000), 100)
```

numpy 1.18.1

**Comment by jakebailey** [comment] 2020-07-22 18:43
Closing as a dupe of #150.

**Closed by jakebailey** 2020-07-22 18:43 UTC
