### ISSUE TITLE
No completions for symbol in another file when using sync server in the browser

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4785] opened 2023-09-01 18:43 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.8.51
-   OS and version: web 
-   Python version (and distribution if applicable, e.g. Anaconda): N/A
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off
-   python.analysis.enableSyncServer: true

<h3> Code Snippet </h3>

https://vscode.dev/github/luabud/wordle?vscode-coi=

<h3> Repro Steps </h3>

1. In the wordle.py file, add a comment to line 4 where encoded_words is declared
2. Now try to import encoded_words from the process_words file
3. See that there isn't any completions for both
4. Even after importing it, trying to access process_words doesn't work 

https://github.com/microsoft/pylance-release/assets/45497113/ba44690d-29be-4a2d-b6ce-a428a084901b

<h3> Logs </h3>

```
[Info  - 11:35:50 AM] Pylance (sync) language server 2023.8.51 (pyright c70adefc) starting
[Info  - 11:35:50 AM] Server root directory: /
[Info  - 11:35:50 AM] virtual workspace: vscode-vfs://github/luabud/wordle
[Info  - 11:35:50 AM] Starting service instance "wordle"
[Warn  - 11:35:51 AM] stubPath /luabud/wordle/typings is not a valid directory.
[Error - 11:35:51 AM] File or directory "/luabud/wordle" does not exist.
[Info  - 11:35:51 AM] Found 1 source file
[Info  - 11:35:56 AM] [FG] Long operation: parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/builtins.pyi (4058ms)
[Info  - 11:36:02 AM] [FG] Long operation: checking: /luabud/wordle/wordle.py (5603ms)
[Info  - 11:36:02 AM] [FG] Long operation: analyzing: /luabud/wordle/wordle.py (5605ms)
[Warn  - 11:36:14 AM] stubPath /luabud/wordle/typings is not a valid directory.
[Error - 11:36:14 AM] File or directory "/luabud/wordle" does not exist.
[Info  - 11:36:14 AM] Found 1 source file
[Info  - 11:36:19 AM] [FG] Long operation: parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/builtins.pyi (3885ms)
[Info  - 11:36:25 AM] [FG] Long operation: checking: /luabud/wordle/wordle.py (5211ms)
[Info  - 11:36:25 AM] [FG] Long operation: analyzing: /luabud/wordle/wordle.py (10472ms)
No configuration file found.
No pyproject.toml file found.
[Warn  - 11:38:24 AM] stubPath /luabud/wordle/typings is not a valid directory.
[Info  - 11:38:24 AM]   /bundled/stubs
Searching for source files
[Error - 11:38:25 AM] File or directory "/luabud/wordle" does not exist.
[Info  - 11:38:25 AM] Found 1 source file
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   parsing: /luabud/wordle/wordle.py (704ms)
[FG]   parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 18ms] (3568ms)
[Info  - 11:38:29 AM] [FG] Long operation: parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/builtins.pyi (3568ms)
[FG]   binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/builtins.pyi (792ms)
[FG]   binding: /luabud/wordle/wordle.py (22ms)
[FG]   checking: /luabud/wordle/wordle.py ...
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/typing.pyi [fs read 8ms] (1453ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/typing.pyi (186ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 10ms] (508ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/typing_extensions.pyi (76ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 7ms] (447ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (74ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/types.pyi [fs read 12ms] (911ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/types.pyi (149ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/abc.pyi [fs read 6ms] (71ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/abc.pyi (9ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/random.pyi [fs read 20ms] (295ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/random.pyi (24ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/base64.pyi [fs read 5ms] (79ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/base64.pyi (9ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/collections/abc.pyi [fs read 3ms] (7ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/collections/abc.pyi ...
[FG]       parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_collections_abc.pyi [fs read 3ms] (64ms)
[FG]       binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_collections_abc.pyi (10ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/collections/abc.pyi (77ms)
[FG]     parsing: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_random.pyi [fs read 4ms] (18ms)
[FG]     binding: /ms-python/vscode-pylance/2023.8.51/extension/dist/typeshed-fallback/stdlib/_random.pyi (5ms)
[FG]   checking: /luabud/wordle/wordle.py (4912ms)
[Info  - 11:38:35 AM] [FG] Long operation: checking: /luabud/wordle/wordle.py (4912ms)
[FG] analyzing: /luabud/wordle/wordle.py (10003ms)
[Info  - 11:38:35 AM] [FG] Long operation: analyzing: /luabud/wordle/wordle.py (10003ms)
[FG] parsing: /luabud/wordle/wordle.py (123ms)
[Info  - 11:38:36 AM] Could not import 'e' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:36 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:36 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:36 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:36 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:36 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:36 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:36 AM]   Looking for typeshed stdlib path
[Info  - 11:38:36 AM]   Looking for typeshed stdlib path
[Info  - 11:38:36 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:36 AM]   Typeshed path not found
[Info  - 11:38:36 AM]   Looking for typeshed stubs path
[FG] binding: /luabud/wordle/wordle.py (22ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (551ms)
[FG] analyzing: /luabud/wordle/wordle.py (551ms)
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:37 AM]   No access to python executable.
[Info  - 11:38:37 AM]   Attempting to resolve stub package using root path '/bundled/stubs'
[Info  - 11:38:37 AM]   Looking for typeshed stdlib path
[Info  - 11:38:37 AM]   Typeshed path not found
[Info  - 11:38:37 AM]   Looking for typeshed third-party path
[Info  - 11:38:37 AM]   Looking for typeshed stubs path
[Info  - 11:38:37 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (17ms)
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:37 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:37 AM]   No access to python executable.
[Info  - 11:38:37 AM]   No python interpreter search path
[Info  - 11:38:37 AM]   Attempting to resolve stub package using root path '/bundled/stubs'
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:37 AM]   Looking for typeshed stdlib path
[Info  - 11:38:37 AM]   Looking for typeshed stdlib path
[Info  - 11:38:37 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:37 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (31ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (68ms)
[FG] analyzing: /luabud/wordle/wordle.py (68ms)
[FG] parsing: /luabud/wordle/wordle.py (103ms)
[Info  - 11:38:39 AM] Could not import 'p' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:39 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:39 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:39 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:39 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:39 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:39 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:39 AM]   Finding python search paths
[Info  - 11:38:39 AM]   No access to python executable.
[Info  - 11:38:39 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:39 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:39 AM]   Looking for typeshed stdlib path
[Info  - 11:38:39 AM]   Looking for typeshed stdlib path
[Info  - 11:38:39 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:39 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (18ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (547ms)
[FG] analyzing: /luabud/wordle/wordle.py (548ms)
[FG] parsing: /luabud/wordle/wordle.py (129ms)
[Info  - 11:38:40 AM] Could not import 'proc' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:40 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:41 AM]   Finding python search paths
[Info  - 11:38:41 AM]   No access to python executable.
[Info  - 11:38:41 AM]   No python interpreter search path
[Info  - 11:38:41 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/bundled/stubs'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:41 AM]   Looking for typeshed stdlib path
[Info  - 11:38:41 AM]   Typeshed path not found
[Info  - 11:38:41 AM]   Looking for typeshed stubs path
[FG] binding: /luabud/wordle/wordle.py (15ms)
[FG] parsing: /luabud/wordle/wordle.py (127ms)
[Info  - 11:38:41 AM] Could not import 'process_wo' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:41 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:41 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:41 AM]   Finding python search paths
[Info  - 11:38:41 AM]   No access to python executable.
[Info  - 11:38:41 AM]   No python interpreter search path
[Info  - 11:38:41 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:41 AM]   Attempting to resolve stub package using root path '/bundled/stubs'
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:41 AM]   Looking for typeshed stdlib path
[Info  - 11:38:41 AM]   Looking for typeshed stdlib path
[Info  - 11:38:41 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:41 AM]   Typeshed path not found
[Info  - 11:38:41 AM]   Looking for typeshed third-party path
[Info  - 11:38:41 AM]   Looking for typeshed stubs path
[Info  - 11:38:41 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (13ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (53ms)
[FG] analyzing: /luabud/wordle/wordle.py (53ms)
[FG] parsing: /luabud/wordle/wordle.py (81ms)
[Info  - 11:38:42 AM] Could not import 'process_wor' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:42 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   No access to python executable.
[Info  - 11:38:42 AM]   No python interpreter search path
[Info  - 11:38:42 AM]   Attempting to resolve stub package using root path '/bundled/stubs'
[Info  - 11:38:42 AM]   Typeshed path not found
[Info  - 11:38:42 AM]   Looking for typeshed third-party path
[Info  - 11:38:42 AM]   Looking for typeshed stubs path
[FG] binding: /luabud/wordle/wordle.py (17ms)
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:42 AM]   No access to python executable.
[Info  - 11:38:42 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:42 AM]   Typeshed path not found
[Info  - 11:38:42 AM]   Looking for typeshed third-party path
[Info  - 11:38:42 AM]   Looking for typeshed stubs path
[Info  - 11:38:42 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (15ms)
[FG] parsing: /luabud/wordle/wordle.py (111ms)
[Info  - 11:38:42 AM] Could not import 'process_words' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:42 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:42 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:42 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:42 AM]   Finding python search paths
[Info  - 11:38:42 AM]   No python interpreter search path
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:42 AM]   Looking for typeshed stdlib path
[Info  - 11:38:42 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:42 AM]   Looking for typeshed third-party path
[Info  - 11:38:42 AM]   Looking for typeshed stubs path
[Info  - 11:38:42 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (12ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (80ms)
[FG] analyzing: /luabud/wordle/wordle.py (80ms)
[FG] parsing: /luabud/wordle/wordle.py (94ms)
[Info  - 11:38:43 AM] Could not import 'process_words' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:43 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:43 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:43 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:43 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:43 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:43 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:43 AM]   Finding python search paths
[Info  - 11:38:43 AM]   No access to python executable.
[Info  - 11:38:43 AM]   No python interpreter search path
[Info  - 11:38:43 AM]   Looking for typeshed stdlib path
[Info  - 11:38:43 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:43 AM]   Typeshed path not found
[Info  - 11:38:43 AM]   Looking for typeshed third-party path
[Info  - 11:38:43 AM]   Looking for typeshed stubs path
[Info  - 11:38:43 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (13ms)
[FG] parsing: /luabud/wordle/wordle.py (113ms)
[Info  - 11:38:43 AM] Could not import 'process_words' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:43 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:43 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:43 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:43 AM]   Looking in bundled stubs path '/bundled/stubs'
[Info  - 11:38:43 AM]   Looking for typeshed stdlib path
[Info  - 11:38:43 AM]   Looking for typeshed third-party path
[Info  - 11:38:43 AM]   Looking for typeshed stubs path
[FG] binding: /luabud/wordle/wordle.py (21ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (106ms)
[FG] analyzing: /luabud/wordle/wordle.py (107ms)
[FG] parsing: /luabud/wordle/wordle.py (122ms)
[Info  - 11:38:44 AM] Could not import 'process_words' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:44 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:44 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:44 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:44 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
ubs'
[Info  - 11:38:44 AM]   Attempting to resolve using root path '/bundled/stubs'
[Info  - 11:38:44 AM]   Looking for typeshed stdlib path
[Info  - 11:38:44 AM]   Looking for typeshed stdlib path
[Info  - 11:38:44 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:44 AM]   Typeshed path not found
[Info  - 11:38:44 AM]   Looking for typeshed third-party path
[Info  - 11:38:44 AM]   Looking for typeshed stubs path
[Info  - 11:38:44 AM]   Typeshed path not found
38:44 AM] Could not import 'process_words' in file '/luabud/wordle/wordle.py'
[Info  - 11:38:44 AM]   Looking in stubPath '/luabud/wordle/typings'
[Info  - 11:38:44 AM]   Attempting to resolve stub package using root path '/luabud/wordle/typings'
[Info  - 11:38:44 AM]   Attempting to resolve using root path '/luabud/wordle/typings'
[Info  - 11:38:44 AM]   Looking in root directory of execution environment '/luabud/wordle'
[Info  - 11:38:44 AM]   Attempting to resolve stub package using root path '/luabud/wordle'
[Info  - 11:38:44 AM]   Attempting to resolve using root path '/luabud/wordle'
[Info  - 11:38:44 AM]   No access to python executable.
stub package using root path '/bundled/stubs'
[Info  - 11:38:44 AM]   Attempting to resolve using root path '/bundled/stubs'
:38:44 AM]   Attempting to resolve using root path '/typeshed-fallback/stdlib'
[Info  - 11:38:44 AM]   Typeshed path not found
[Info  - 11:38:44 AM]   Looking for typeshed third-party path
[Info  - 11:38:44 AM]   Looking for typeshed stubs path
[Info  - 11:38:44 AM]   Typeshed path not found
[FG] binding: /luabud/wordle/wordle.py (11ms)
[FG] analyzing: /luabud/wordle/wordle.py ...
[FG]   checking: /luabud/wordle/wordle.py (61ms)
[FG] analyzing: /luabud/wordle/wordle.py (62ms)

```

**Comment by rchiodo** [comment] 2023-09-01 20:59
Hmm, this might be because it's a virtual workspace. That's not supported yet. Let me try with a local workspace. No repros there too.

**Comment by rchiodo** [comment] 2023-09-01 23:13
Blech, it works fine in vscode-test-web (which is supposed to mimic vscode.dev).

**Comment by rchiodo** [comment] 2023-09-01 23:28
Oh I had the wrong query. Didn't even realize you had this as the query.
https://vscode.dev/?vscode-coi

Using that I can get completions using vscode.dev if I open a local folder.

Browsing from github doesn't. Github is virtual workspaces so that is likely the same issue as virtual workspaces in the desktop.

**Comment by rchiodo** [comment] 2023-09-01 23:29
This would be a dupe of #4617

**Closed by rchiodo** 2023-09-01 23:28 UTC
Labels: needs repro
