### ISSUE TITLE
reportGeneralTypeIssues category is too generic

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [microsoft/pylance-release#497] opened 2020-10-16 12:34 UTC
Summary:

`reportGeneralTypeIssues` errors are issued both for certain and assumed errors (for unknown types in compiled packages). It would be useful to be able to handle these cases differently (e.g. turn off or change the level of severity for assumed cases), so I think that for assumed cases a different error message should be used, or that the error category be more specific.

Long version:

This feature request is related to `reportGeneralTypeIssues` error messages pylance emits in various situations for compiled packages without type stubs. See #150 for `numpy`, and in my experience similar problems exist with `PyQt(5)/PySide2`, `tobii-research`, etc. For me these error messages are not important, so I'd like to turn them off. The discussion in #150 seems to have gone in the direction that this is an omission on the part of the compiled packages, which should be providing typing information. While `numpy` may be supplying stubs or in some way fixing the problem on their end in the future, I don't expect that all compiled packages will follow the same course.

However, the `reportGeneralTypeIssues` error is also used in other, in my view, much more valid situations, e.g.:

    def a(b: int):
        pass

    a("aa")

    >>Argument of type "Literal['aa']" cannot be assigned to parameter "b" of type "int" in function "a" "Literal['aa']" is incompatible with "int" Pylance (reportGeneralTypeIssues)

These are two very different cases: one is where pylance *knows* that the typing is wrong, and one (in the case of missing typing information) pylance *assumes* that something is wrong. Quoting jakebailey in #150, "[...] we aren't able to actually find the definition (so assume Unknown)".

In my opinion, assumptions should be treated differently as certain errors. For example, just because pylance doesn't know that a function exists in a package, it shouldn't tell me that "... is unknown import symbol" or "... is not a known member of module" and other severe-looking error messages. Pylance should admit its ignorance and say "hey, I don't know what's inside this package. What you're doing could be wrong, so I'm letting you know. You should try to get typing information for that package, if you can." Not necessarily this verbose, but something similar in spirit. Whereas for certain errors (such as in the above example), say "Buddy, this is just wrong."

To this end, I suggest that a different error category be emitted for the assumed cases, which would allow users to treat them separately.

I only mentioned two cases here that the error message covers, but there could be many more, so I'm not certain that my suggested solution to the problem is the best one. Also, I've searched for similar issues / feature requests and found none, but I may have overlooked some discussion that makes this request unnecessary.

**Comment by erictraut** [comment] 2020-10-16 16:48
Thanks for the suggestion.

The `reportGeneralTypeIssues` diagnostic rule is somewhat of a catch-all. In the past, we have split off rules that are more specific, so there is precedent for doing this.

Could you provide a full and precise list of errors that you are seeing that you think should be split off? It would be helpful to have the full text of the error and details about the circumstances in which the error is reported. You mentioned "is unknown import symbol" and "is not a known member of module". Could you provide more details? And are there any others, or is that the full list? Once we have those details, we can discuss internally and get back to you. Thanks!

We'd also like to understand what packages are missing types, so if you could file separate bugs for each of those, that will help us prioritize our efforts to work with package maintainers. In the long term, we really need all Python packages to provide proper type information. We're currently in this unfortunate situation where package authors are not yet all onboard.

**Comment by zEdS15B3GCwq** [comment] 2020-10-19 02:51
Thanks for taking a positive approach to my suggestion. I'll do my best to reply to your questions, though I'm neither experienced enough to give you a "full and precise list of errors", nor have I taken notes in the past when I saw a few errors here and there. So, my list will inevitably be far from comprehensive. Perhaps a developer with deeper knowledge into what `reportGeneralTypeIssues` actually covers could probably come up with a much more useful list than me - maybe my few examples will give some ideas to such people. Other than that, is there no way to isolate such cases starting from the idea that pylance is assuming _unknown_ types? Or is that anything but specific enough?

Anyhow, the two packages in particular that made me open the request are **PySide2** (not **PyQt5,** that was a mistake - their typing seems to be much more complete) and **tobii_research**, a package for accessing Tobii eye trackers. PySide2 should be well known enough, and you can find information on the other package [on the Tobii website](http://developer.tobiipro.com/python.html).

Errors:

1. `Cannot access member "mediaStatusChanged" for type "QMediaPlayer" \ Member "mediaStatusChanged" is unknown`: PySide2; the function exists, just pylance doesn't see it somehow. This is a prime example of an "error" that I'd like to disable.

2. `"x" is unknown import symbol`: e.g. `from tobii_research import find_all_eyetrackers`

3. `"x" is not a known member of module "y"`: e.g. `import tobii_research as tr; tr.find_all_eyetrackers()`. In both these cases, pylance doesn't know something, which is all right, but it should be possible to disable the error or change it into a warning.

4. `Arguments missing for parameter(s) ...`: This is a mixed bag that occurs mostly with overloaded functions in PySide2. In some cases, it seems pylance is assuming types and overreaching, e.g. `QMediaContent` has an overloaded constructor, one of which takes no parameters, so `QMediaContent()` is valid - pylance, however, assumes the type to be `QMediaContent(resources: Sequence[Unknown] | Unknown)`. Other overloaded functions such as `QMargins()` or `QWidget.setGeometry(QRect)` etc. are reported invalid by pylance, but that could be due to bad typing information from PySide2 - there doesn't seems to be _Unknown_ type in their reported signature, only that pylance expects a different signature to be used. PyQt5 doesn't have this problem, so I'm guessing they got their typing info down correctly.

5. `Argument of type "x" cannot be assigned to parameter "y"`: same as the previous one, just in situations when the parameters supplied in an overloaded function call don't match the signature pylance expects. E.g. `QRect(0, 0, 640, 480)` should be valid whereas pylance wants QPoints etc.

I'm pretty sure there's more, but this is what I could remember and find browsing through code from the past week or so. Even if this list isn't comprehensive enough to cover the entirety of my feature request, the root causes for cases 1 to 3 are hopefully similar enough to isolate into a separate error - that would already make me very happy. Cases 4 and 5 might not be pylance's problem at all.

Lastly, with respect, I think your philosophy of (quote)

> In the long term, we really need all Python packages to provide proper type information. We're currently in this unfortunate situation where package authors are not yet all onboard.

might be too idealistic. AFAIK, typing in Python is not a MUST, and there always will be not well-maintained packages and package suppliers who are too busy or don't care.

**Comment by erictraut** [comment] 2020-10-19 05:07
Thanks for the additional information.

I've looked at PySide2. It includes very good type information in the form of type stub files included in the package. This package is already way ahead of most in terms of types. When a type stub is present, it is assumed to be complete and to represent the public interface contract for the package. That includes the classes, functions, and types that are supported by the library author. If a symbol is not included in the type stub, it means either 1) that symbol is not meant to be part of the interface contract of the package (e.g. it is deprecated or an internal implementation detail), or 2) there is a bug in the type stub.

`mediaStatusChanged` is not included in the type stub. If you think that it should be, you should submit a bug report or a PR for the PySide2 package.

An attempt to access a symbol that is not part of a well-defined interface contract is one of the most fundamental errors that a type checker should report. As such, I don't think it makes sense to provide fine-grained ways to silence this error.

If you want to work around this error temporarily, you can cast the object to Any. I realize that's not pretty, but it will hopefully be temporary until the next release of the library.

```python
a = QMediaPlayer()
cast(Any, a).mediaStatusChanged()
```

As for the `tobii_research` package, no type information is provided within the package. To make matters worse, the top-level package is doing some unfortunate dynamic manipulation of global symbols. These make it impossible for a static analyzer to understand what symbols are being exported from the top-level module. That means you won't get any type checking information, completion suggestions, hover text, doc strings, etc.

My recommendations for this package are as follows:
1. Reach out to the package authors and ask them to replace the dynamic global symbol manipulations with `import` statements.
2. Create your own type stub file called `tobii_research.pyi` and place it in your local stub directory (by default called `typings`). Within this stub file, add the line:
```python
def __getattr__(name: str) -> Any: ...  # incomplete
```

This will tell a type checker that any symbol that you access in that package should be treated as an `Any` type. This will eliminate any errors you're seeing from this package.

**Comment by zEdS15B3GCwq** [comment] 2020-10-19 05:59
> def __getattr__(name: str) -> Any: ...  # incomplete

This is very useful. I wish there was a simpler way, e.g. doing the same in a line comment directive, or even better, having another error message as I suggested, but this will do for now.

As for the overloaded functions in PySide2, as I mentioned, I don't believe that this is certainly a problem that pylance should solve. In this specific package's case, if the maintainers want to provide correct and complete typing stubs, it's possible to defer the problem to them. Nevertheless, to respond to your points, I argue that it's not a small issue of fine-graining, so I don't think that PySide2's typing is as advanced as you described. For one, PyQt5, which has the same purpose of providing a Python interface to Qt and has basically the same classes, functions etc., doesn't have any of these typing issues. In addition, to the points mentioned earlier:

1. `mediaStatusChanged` is THE signal to check whether a media (video etc.) has started playing, stopped, etc. It's usage is basic.

2. As per the Qt doc site, a `QMediaContent` object created by an empty constructor (null QMediaContent) is THE way to reset a media player's inner state before setting another media file. Again, PySide2 seems to be missing something important here.

My main point is, that instead of solving these issues for individual packages, if pylance were aware of its "limitations" and treat missing information differently, that would also cover a lot of other, badly maintained packages that will not/never get typing information. Of course, as long as I'm the only one bringing this up, and I can only showcase 2 problematic packages (well, PySide2 is improving so maybe soon just 1), that's probably not a good enough reason for you to get into anything (possibly) complicated.

**Comment by erictraut** [comment] 2020-10-19 07:37
Pylance does offers a mode where you can suppress type checking errors. Just set `python.analysis.typeCheckingMode` to `off`. That's actually the default value for this setting.

If you want to enable type checking, the most basic check that Pylance can perform is to notify you that you are calling a method or accessing an attribute that doesn't exist. Disabling this is the equivalent of disabling the type checker altogether.

There are situations where types are unknown, in which case Pylance does not emit such errors. But when types are defined — especially within type stubs that were written by the author of a package with the express intent of accurately and completely describing the interface of that package, it wouldn't make sense to suppress these errors if the user has indicated that he wants basic type checking to be enabled.

**Comment by zEdS15B3GCwq** [comment] 2020-10-19 09:40
I think I've already presented my opinion and arguments I have. I'm sure you already understand what I meant; I'll just add a brief clarification because I'm now somewhat confused by your previous post.

1. I wouldn't want to completely disable pylance's type checking - see my original post about valid errors.

2. I absolutely agree that when pylance does have typing information, it should use it and report errors it finds. PySide2's typing may be incorrect, it's not pylance's fault. In retrospect, mentioning PySide2 was a mistake - it made my point less clear and took attention away from the next, more important point.

3. Compiled packages with no typing information. E.g. tobii_research; most likely plenty similar packages out there. I want to be able to disable those type-related errors for such packages which are based on pylance's assumptions. The solution you given (custom stub) is a step ahead, though it feels a bit like a workaround. I hope you, VSCode developers, will deem it important enough to provide a more general solution, e.g. splitting such cases off into a different error category.

**Comment by erictraut** [comment] 2020-10-19 14:44
For point number 3, there is another option that I should have mentioned previously. You can change the setting "python.analysis.useLibraryCodeForTypes" to false. This will tell Pylance to use type information from type stubs and libraries that claim to have inlined type information (i.e. include a py.typed marker file as per PEP 561). Other packages, such as tobii_research, will be treated as typeless. All symbols will be unknown, and no type errors will result from symbols used in those packages.

**Comment by zEdS15B3GCwq** [comment] 2020-10-22 01:22
BtW, I've found another library with typing issues: **sounddevice v0.4.1** (I'm actually using **python-sounddevice** from conda-forge) [(doc](https://python-sounddevice.readthedocs.io/en/0.4.1/index.html)). This library is distributed as source code, without type hints.

1. Having `sounddevice.default.reset()` or `default.__init__()` in the code (member functions of `class default`) is rewarded with an `Argument missing for parameter "self"` pylance error. Class member functions shouldn't require self to be supplied. Reading `@property default.hostapi` produces no errors.

2. `sounddevice.default.channels` (number of input, output channels) expects a tuple of integers or a single integer. Pylance thinks it's strictly _Tuple[None, None]_ (which is the initialisation value), so any integer or tuple of integers assignment gets a `cannot be assigned ... is incompatible with ...` error.

**Comment by jakebailey** [comment] 2020-10-22 02:11
I don't think this is related to the issue of the "general type issues" category being too large.

Those sound like either bugs/improvements to type inference (as you say, it is unannotated), or issues in general that could be handled upstream with stubs (or put into typeshed if popular enough). I think you should make another issue so we can track those in particular.

**Comment by zEdS15B3GCwq** [comment] 2020-10-22 02:24
Back to your response. I've checked briefly if disabling the setting you mentioned produces the desired effect, and in a way it does, but it's not perfect.

I have a little project, which, spread over several source files, does the following:

    from numpy import sin, pi  # -> "unknown import symbol" error for both
    import numpy as np
    <use np.array, np.linspace, np.argmin, np.concatenate etc. in some way>  # no problem initially, but... see below

    from tobii_research import find_all_eyetrackers  # "unknown import symbol"

    import sounddevice as sd
    sd.default.channels = 2  # pylance things channels is Tuple[None, None]; Literal[2] or tuple of literals isn't accepted

    sd.default.reset()  # Argument missing for parameter "self"

I also added 2 test functions. In util.test.py:

    def a(b: int):
        pass

In test.py:

    from util.test import a

    def c(d: int):
        pass

    a("text")  # Literal["text"] is incompatible with "int"
    b("text")  # same

With this setup and initial pylance settings of `python.analysis.typeCheckingMode` set to _Basic_, `useLibraryForCodeTypes` _enabled_, pylance is throwing the errors as in comments above.

Now, when I turn off `useLibraryForCodeTypes` (type checking mode still _basic_), these things happen:
1. Errors regarding `sounddevice` are gone - good.
2. Errors about bad parameters in test functions a() and b() are still there - good.
3. Unknown import symbol error regarding `find_all_eyetrackers` - not good.
4. Same unknown import symbol errors for `sin`, `pi` are also still there - not good.
5. Weirdly, now I'm getting "not a known member of module" errors for the numpy functions that had no errors before: `array`, `linspace` etc. - not good!

Next, I set `analysis.typeCheckingMode` to _off_. This is what happens:
- 4 and 5 from the previous list are gone - good.
- 3 (find_all_eyetrackers error) is still there - strange.
- 2 is still there - good!

Finally, I turn `analysis.typeCheckingMode` back to _Basic_, and NOTHING changes! So, what does it do really?

My takeaways from these results are:
1. The settings don't work in a consistent way. I got the best results after turning useLibraryForCodeTypes off, setting typeCheckingMode to _off_ and then back to _Basic_.
2. Some import errors remain.
3. (+1) Documentation for these settings is very sparse.

In your previous posts, you showed me several workarounds to make the typing-related errors disappear. In my particular situation, these kind of seem to work. However, I still argue that `reportGeneralTypeIssues` is an overly vague error category. For one, bad _imports_ are very different from badly typed function calls - I cannot imagine why the former is in general _type_ issues at all.

Also, I have a feeling that by turning off `useLibraryForCodeTypes`, I'm missing out on some useful functionality of Pylance. There must be some cases in which that kind of analysis is helpful, but without more documentation in detail, it's difficult to say what. Instead of turning it off completely, I prefer the other workaround you mentioned, i.e. adding a "dummy" typing stub, which offers a much more specific solution. Even better, if there was a _directive_ (such as an inline comment, for example) to achieve the same without having to create a stub file, that would be much simpler.

Lastly, the most unquestionably useful errors here are the ones that report incorrect parameters for the test functions `a()` and `b()`, and I get the same errors from `mypy` as well. Some documentation with details into what actually pylance offers over mypy, and how much of that functionality is lost by disabling the above setting would be helpful.

**Comment by zEdS15B3GCwq** [comment] 2020-10-22 02:27
> I don't think this is related to the issue of the "general type issues" category being too large.
> 
> Those sound like either bugs/improvements to type inference (as you say, it is unannotated), or issues in general that could be handled upstream with stubs (or put into typeshed if popular enough). I think you should make another issue so we can track those in particular.

Jake, thanks for your response. Eric mentioned above that he was interested in knowing which libraries have typing problems with pylance, so my comment above was just an addition to this list and wasn't intended as a continuation of the main topic. I split it off into a separate comment as my main response was overly long.

**Comment by zEdS15B3GCwq** [comment] 2020-10-22 03:03
Jake, perhaps my above response was too hasty. What did you mean by "this" not being related to the error category being too large? My entire suggestion or those specific examples about the sounddevice library?

I brought all the examples I could think of that were related, but without a deep understanding of that pylance actually does, so maybe some were not very suitable examples. I can open separate issues for individual libraries if that's how you want to process these problems, however, I do believe that these examples illustrate very nicely how many different things are covered by _the general type issues_ category at this point.

Even if issues with the particular libraries I mentioned here can be handled individually, that's not a solution for all libraries out there. Errors for imports, assumed (missing) typing and known type errors (such as test functions `a()` and `b()`), to me these feel very different. Even though some differentiation can be achieved with the workarounds Eric has mentioned in practice, I think, in theory, a more general approach would be preferable.

**Comment by zEdS15B3GCwq** [comment] 2020-10-22 06:20
*Correction*:

The cause for the `find_all_eyetrackers` error being still present above was the existence of a `typings\tobii_research.pyi` file that I created based on Eric's recommendations. After removing that file, now there is no error whatsoever regarding the `tobii_research` package, so overall the messages I didn't want to see are now gone. There's still the quirk with having to toggle the `type checking mode` setting, and that having `use library for code types` off may have disabled useful functionality, I just don't know it yet.

Another note about the `tobii_research.pyi` stub; the way Eric suggested only eliminated one of the import errors:

    from tobii_research import find_all_eyetrackers  # still unknown import symbol error
    import tobii_research as tr  # OK
    tr.find_all_eyetrackers()  # OK

If you tell me what to add to the file to cover both errors, I might prefer this solution to switching off `use library for code types` completely.

**Comment by jakebailey** [comment] 2020-11-30 21:59
Trying to regain context on this after a break; I'm still a bit confused as to what all is going on here. There's a lot of information relating to various different related/unrelated parts of the type checker, and I'm having trouble figuring out what the actionable problem is to address.

We can certainly expand out the general type issues category as needed, but that wouldn't address the behavior when it comes to `useLibraryCodeForTypes` (which is distinct and has its own affects across the board). Pylance is intended to be sort of a "pretty face" for pyright, which has a good amount of documentation about its options as well: https://github.com/microsoft/pyright/tree/master/docs

If you really want the "purest" type checking experience, then I would definitely be disabling `useLibraryCodeForTypes`, as it's really there to try and extract information from common libraries for the average user who has no knowledge of stubs. For someone that's all-in, it's best to try and get the most correct info (but the libraries may be useful even if not marked as py.typed).

**Comment by zEdS15B3GCwq** [comment] 2020-12-02 03:13
Jake, thanks for returning to this topic despite it being as messy and unclear as it is. Perhaps it would've been better had I refrained from posting my thoughts until had more experience with PyLance and typing in general so as to be able to formulate a clearer message. I was hoping that you, experts, would pick up on something useful and figure out what to do.

I'm surprised nobody has shown any interest in this thread (aside from you helpful PyLance developers, which I appreciate - thank you), because I can't believe that there aren't (many) more 3rd party libraries that have similar problems.

For the last month, I've been coding Python with PyLance _general type_ errors disabled, relying only on *mypy* for type checking, occasionally switching PyLance's checks back on to see the difference. In a simplified, but perhaps not entirely incorrect view, mypy and PyLance are at two ends of a spectrum: the former stays away from assumptions [(doc)](https://mypy.readthedocs.io/en/stable/common_issues.html) , whereas the latter tries to figure out as much as it can. PyLance's approach is certainly useful and requires less work from the developer, but such behaviour is best when it can be fine-tuned.

When it comes to reported errors (warnings, hints, etc.), I (and I'm assuming developers in general) want to be able to minimize annoyances while maximizing  useful information;  more specifically, I don't want to see type errors that I cannot do anything about, but I want to keep errors that actually break the program and that I must fix.

I'll try to clarify my point by looking at 3 categories of code, based on how useful type errors are:

1. My own code

2. Libraries that have typing that's either incorrect or doesn't work well with PyLance. Best example I have is PySide2 - tons(!) of errors for correct, working code. The same code in PyQt5 (which is basically a twin sibling to PySide2) doesn't produce the same errors, so I'm assuming the problem is with PySide2's typing. (While I'm aware that _incorrect_ may not be the _correct_ term to use for PySide2's typing, there are certainly errors that should not be there; therefore, I'll keep using this term for lack of a better one.)

3. Libraries without typing, e.g. tobii_research. While types inferred from source code, if available, can be useful, they can also be incorrect. In addition, I had some issues with errors regarding importing (see earlier example).

*Point 1* is a no-brainer: when I choose to write typed code, I want "all" the feedback to improve my code.

*Point 3* is something that can be mostly managed: in the best case, PyLance can provide useful insights by inferring types from source code; however, when PyLance doesn't work well with a library, it's possible to turn off `useLibraryCodeForTypes` or use a custom stub for that particular library as explained by Eric above. Preferably, there would be a more convenient way to achieve the latter without writing a custom stub, e.g. by inline comment directive, but I can live with what's there already. _However, custom stubs don't fix import errors._

***Point 2* is perhaps the most pressing, here I've yet to find an acceptable solution.** Ideally, I want to keep using typing in PySide2 and only see useful errors; to this end, developers from PyLance or PySide2 should work ceaselessly to make sure that the library typing is corrected... but I guess developer enthusiasm and work hours are limited, and even in the best case things take time. Until that happens (maybe never), what can I do to disable the errors regarding PySide2? The setting `useLibraryCodeForTypes` is, as far as I understand, irrelevant, as the code has typing information, just one that doesn't work well with PyLance. Disabling `general type issues` en bloc is an overkill - see *point 1*. I'm not aware of a configuration that would preserve checking for *point 1* while disabling checking for *point 2*; basically, the solutions available now either disable checking for all 3 points, or just help with *point 3*.

**As I see it, the current situation could be improved in the following ways**.  (These are just general suggestions thrown up in the air, a bit like brainstorming. You may have much better, more practical ideas than me with my limited knowledge.)

- **Allow disabling type analysis for specific libraries.** Currently, I would use this for `tobii_research` to also eliminate import errors that exist even with a custom stub, and, for now, with `PySide2` as there are too many errors that I cannot do anything about. Convenient implementation would be something I can put in the code, e.g. inline comment.

- **Break up _general type issues_ into sub-categories to allow fine-grained control**. A few ideas: _import errors_ so that I can separately disable _tobii_research_ import problems; _3rd party library errors_ vs _own code errors_ so that I can keep type analysis for my own code (point 1 vs point 2); _inferred type errors_ vs _explicitly declared type errors_ (mypy's approach comes to mind), etc. I'm aware most of these categories are vague - I leave it up to you to decide which are even remotely feasible.

If you still cannot find anything _actionable_ here, I give up; I don't think I can explain my thoughts more clearly. Meanwhile, I'll look into `PyRight` configuration options, see what I can do with those.

**Comment by zhongjimeiying** [comment] 2021-02-18 02:20
I got similar problems in **pandas** 1.0.3. I installed PyLance 2021.2.2.
![code](https://user-images.githubusercontent.com/41845617/108295430-a594df00-71d2-11eb-95de-fccbc7f536e1.JPG)

**Comment by zhongjimeiying** [comment] 2021-02-18 11:15
@zEdS15B3GCwq Hello, I find a way. Maybe you can close reportGeneralTypeIssues and open mypy linting.

```json
{
  "python.analysis.diagnosticSeverityOverrides": {
      "reportGeneralTypeIssues": "none",
  },
  "python.linting.mypyEnabled": true,
}
```

**Comment by acnebs** [comment] 2021-02-23 18:07
What I don't understand is why apparently mypy is able to know about various methods that exist on objects, but Pylance is not.  When I autocomplete with Pylance, it frequently does not know about all the methods, even though that package is right there for the methods to be pulled out of.

**Comment by jakebailey** [comment] 2021-02-23 18:09
@acnebs Please file a new issue; I don't think your issue is related to deciding the set of diagnostics we put into the generalTypeIssues bin.

**Comment by zEdS15B3GCwq** [comment] 2021-10-22 02:39
If I may add my opinion. Just as when I opened this topic, I see this conversation going in a similar direction: user complains about the error messages being too many/annoying/generic; brings up an example; developers dissect the specific example(s) and show that pylance works correctly. With all respect, I think this approach misses the main issue. OK, so you, developers, have convinced me that pylance is _correct_; I cannot bring any example that will show otherwise. But is this enough? I mean, from an end user perspective, is pylance useful? In my opinion, if some users turn off a significant part of its functionality because the messages aren't useful and are too annoying to deal with, then it's proof that something should be done differently. The reason why I opened this topic, and I believe why @taldcroft joined in, is because we feel that `reportGeneralTypeIssues` messages are too generic and not helpful at all - even though technically, logically, mathematically they may be correct if you dig down deep enough. The issue usability and not correctness. I think where I went in the wrong direction in my posts, is that I was bringing specific examples to show what _felt wrong_ (doesn't mean it's incorrect), and I was trying to offer my views on how it could be fixed - all these may be _incorrect_ or _infeasible_, but neither invalidates my initial point about _usability_. In the meantime, I keep the setting `off` and use other code checkers.

**Comment by erictraut** [comment] 2021-10-22 03:11
Yes, you make a good point. Correctness is objective, but "usable", "helpful" and "annoying" are much more subjective. Opinions will differ from one person to the next.

In any case, we appreciate all the input. These data points and opinions help guide us.

**Comment by AndreasADL** [comment] 2023-02-19 11:38
I got the same error with the following message:

> Argument of type "dict[Unknown, Unknown] | Unknown | str" cannot be assigned to parameter "__s" of type "str" in function "write"
>   Type "dict[Unknown, Unknown] | Unknown | str" cannot be assigned to type "str"
>     "dict[Unknown, Unknown]" is incompatible with "str"

I'm somewhat of a newbe but doen't the type explicitly specify that "str" is allowed?

**Comment by erictraut** [comment] 2023-02-19 15:16
@AndreasADL, if you have a specific question about a type checking error, I recommend opening a new discussion topic. You'll need to provide some additional context (preferable, a self-contained minimal code sample) for us to help you with your question.

**Comment by PabloLION** [comment] 2023-11-17 17:54
I find something similar:
```py3
def optional_string_set(s: set[None | str]) -> None:
    ...


s = {"a", "b"}
optional_string_set(s)
""" Error reported at last line:
Argument of type "set[str]" cannot be assigned to parameter "s" of type "set[str | None]" in function "optional_string_set"
  "set[str]" is incompatible with "set[str | None]"
    Type parameter "_T@set" is invariant, but "str" is not the same as "str | None"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
"""
```
hope it helps

**Comment by erictraut** [comment] 2023-11-17 18:19
@PabloLION, this is a simple type violation. The value `s` has the type `set[str]`, and you're attempting to pass it to a parameter that requires a type `set[None | str]`. If your intent is for the type of expression `{"a", "b"}` to be inferred as `set[None | str]`, you can declare the type of `s` with a type annotation:

```python
s: set[None | str] = {"a", "b"}
```

You may want to read [this documentation](https://microsoft.github.io/pyright/#/type-concepts) to learn more about the basics of static typing.

**Comment by PabloLION** [comment] 2023-11-17 18:44
@erictraut Now I see it's working as designed. Thanks for the education. 
Btw there's a shorter `s = {"a", "b" or None}` to avoid the type check but it's not as clear as what Eric offered.

## What I learnt

For curious people only, here's what happened:

I thought it was requiring more info than it needs, I incorrectly thought `str` was a subtype of `None|str` so `set[str]` is a subtype of `set[None|str]`, but this is wrong.

I knew there was a PEP about it, so I went to check [PEP 484](https://peps.python.org/pep-0484/#covariance-and-contravariance), which says:

> Consider a class Employee with a subclass Manager. Now suppose we have a function with an argument annotated with List[Employee]. Should we be allowed to call this function with a variable of type List[Manager] as its argument? Many people would answer “yes, of course” without even considering the consequences. But unless we know more about the function, a type checker should reject such a call: the function might append an Employee instance to the list, which would violate the variable’s type in the caller.

In [PEP 483](https://peps.python.org/pep-0483/#subtype-relationships), there's an example explaining why:

> Let us also consider a tricky example: If List[int] denotes the type formed by all lists containing only integer numbers, then it is not a subtype of List[float], formed by all lists that contain only real numbers. The first condition of subtyping holds, but appending a real number only works with List[float] so that the second condition fails:
> ```py3
> def append_pi(lst: List[float]) -> None:
>     lst += [3.14]
> 
> my_list = [1, 3, 5]  # type: List[int]
> 
> append_pi(my_list)   # Naively, this should be safe...
> 
> my_list[-1] << 5     # ... but this fails
> ```

**Comment by debonte** [comment] 2024-01-17 21:58
Closing in favor of https://github.com/microsoft/pyright/issues/6973

**Closed by debonte** 2024-01-17 21:58 UTC
Labels: needs decision, type checking
