### ISSUE TITLE
CI type check failing with: "object*" is not iterable

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#4392] opened 2023-05-19 01:05 UTC
https://github.com/microsoft/vscode-python/actions/runs/5019545181/jobs/9000282148?pr=21272#step:7:24
```
pyright 1.1.309, node v16.16.0, pyright-action 1.5.1
/home/runner/runners/2.304.0/externals/node16/bin/node /opt/hostedtoolcache/pyright/1.1.309/x64/package/index.js --outputjson
/home/runner/work/vscode-python/vscode-python/pythonFiles/normalizeSelection.py:63:9 - error: "object*" is not iterable
  "__iter__" method not defined (reportGeneralTypeIssues)
Error: "object*" is not iterable
  "__iter__" method not defined (reportGeneralTypeIssues)
/home/runner/work/vscode-python/vscode-python/pythonFiles/tests/unittestadapter/helpers.py:[27](https://github.com/microsoft/vscode-python/actions/runs/5019545181/jobs/9000282148?pr=21272#step:7:28):38 - error: "object*" is not iterable
  "__iter__" method not defined (reportGeneralTypeIssues)
Error: "object*" is not iterable
  "__iter__" method not defined (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations
```
This is the code it is complaining about:
https://github.com/microsoft/vscode-python/blob/a74f1d15b58e2a835f5564449918452ff30d62d6/pythonFiles/normalizeSelection.py#L63

This started happening with pyright version 1.1.309

**Comment by erictraut** [comment] 2023-05-19 01:50
Apologies for the regression. This is a duplicate of https://github.com/microsoft/pyright/issues/5126, which I've already fixed. It will be addressed in next week's pyright release. You can roll back to 1.1.308 if this is blocking you.

**Comment by luabud** [comment] 2023-12-19 20:18
@bschnurr can this be closed?

**Closed** 2023-12-19 23:06 UTC
