### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by RiseUpToTheSky** [microsoft/pylance-release#1774] opened 2021-09-06 17:53 UTC
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.9.1191016588`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.60.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 862,
		"activateCallTime": 19,
		"activateResolvedTime": 671,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-python.vscode-pylance",
				"_lower": "ms-python.vscode-pylance"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by judej** [comment] 2021-09-07 17:47
Dupe of #1773

**Closed by judej** 2021-09-07 17:47 UTC
Labels: duplicate, triage
