### ISSUE TITLE
Pylance thinks my code is unreachable!

### ISSUE THREAD

**Issue by Saya47** [microsoft/pylance-release#6152] opened 2024-07-16 14:54 UTC
## Environment data

-   Pylance version: v2024.7.1
-   OS and version: Windows 11 23H2 22631.3447 WSL2 version: 2.2.4.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5, (Miniconda) conda 23.11.0

## Code Snippet

```python
from collections import OrderedDict
from functools import singledispatchmethod


class AV:
    @singledispatchmethod
    def __init__(self, a: list, b: OrderedDict[str, list] = None):
        if b == None:
            self.from_list(a)
        else:
            print(a, b)

    def from_list(self, a):
        print(a)

```

## Repro Steps

1. Paste this code on your editor, Pylance will think `self.from_list(a)` on line 9 is unreachable:

![image](https://github.com/user-attachments/assets/e22ca39a-3f6b-4069-9502-69927908344c)

![image](https://github.com/user-attachments/assets/4b96af71-149c-431d-b6eb-2a5bcece4cae)

## Expected behavior

The code is absolutely reachable and works fine, Pylance should not mark that if block as unreachable. It should not darken it.

## Actual behavior

Pylance marks the line as unreachable code.

## Logs

```

```

**Comment by debonte** [comment] 2024-07-16 15:22
Pylance is working correctly here. This is a duplicate of https://github.com/microsoft/pylance-release/issues/6131. See my explanation at https://github.com/microsoft/pylance-release/issues/6131#issuecomment-2227140366.

If you change the type annotation of `b` to `OrderedDict[str, list] | None`, Pylance will behave as you expected.

**Closed by debonte** 2024-07-16 15:22 UTC
Labels: needs repro
