### ISSUE TITLE
np.equal is not a known member of module Pylance

### ISSUE THREAD

**Issue by fnl** [microsoft/pylance-release#504] opened 2020-10-19 20:26 UTC
## Environment data

-   Language Server version: 2020.10.1
-   OS and version: OSX 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7

## Expected behaviour

no error highlight when typing:

    import numpy as np
    np.equal(1, np.ones(2))

## Actual behaviour

an error is indicated:

	"message": "\"equal\" is not a known member of module",
	"source": "Pylance (reportGeneralTypeIssues)",

## Logs

```
N/A
```

## Code Snippet / Additional information

```python
import numpy as np
np.equal(1, np.ones(2))
```

**Comment by jakebailey** [comment] 2020-10-19 20:31
Duplicate of #150; this should be improved once numpy releases with type stubs.

Numpy has some dynamic behaviors that prevent us from knowing if certain values exist, or should be re-exported from modules. Their new stub is much more clear.

**Closed by jakebailey** 2020-10-19 20:31 UTC
Labels: triage

**Comment by fnl** [comment] 2020-10-20 20:21
Thanks for the explanations; Am I correct in deducing that Pylance and Numpy will only play well together with future versions of Numpy, whenever they support type stubs?

**Comment by jakebailey** [comment] 2020-10-20 20:23
Some things work, but others don't. At some point we may add back compiled code scraping, but that is difficult to do correctly and doesn't fit nicely into the type system/analysis without some more thought.
