### ISSUE TITLE
Docsting cannot be displayed correctly after pylance is upgraded to v2021.3.1-pre.1

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#1014] opened 2021-03-04 12:01 UTC
## Environment data

-   **Language Server version**: Pylance language server v2021.3.1-pre.1
-   **OS and version**: Windows_NT x64 10.0.19042
-   **Python version**: Python 3.8.6
-   **Torch version**: 1.7.1+cu110

## Expected behaviour

As shown in the figure below, we can see the docstring of `MNIST` when the mouse hovers over it.
![正常](https://user-images.githubusercontent.com/65096819/109960799-2d76ff00-7d24-11eb-9eb2-90d75774b860.png)

We can also see the docstring of `load_iris()` when the mouse hovers over it.
![正常iris](https://user-images.githubusercontent.com/65096819/109960827-336ce000-7d24-11eb-8d1f-db6ff12b83a3.png)

## Actual behaviour

When the mouse hovers over MNIST, only the docstring of the superclass can be seen. 
![错误](https://user-images.githubusercontent.com/65096819/109960863-3d8ede80-7d24-11eb-8ef3-c13a7d8e92a1.png)

And we can’t see the docstring of `load_iris()`. **This happened after I upgraded pylance to v2021.3.1-pre.1**
![错误iris](https://user-images.githubusercontent.com/65096819/109960885-441d5600-7d24-11eb-8811-f168222c73e1.png)

## Code Snippet

```python
import torchvision
from sklearn.datasets import load_iris

train_set = torchvision.datasets.MNIST()
X, y = load_iris()
```

**Comment by jakebailey** [comment] 2021-09-02 19:17
This issue is older, but I'm going to close this as a duplicate of #1047, which has a more constrained repro (and I've retitled it to be more clear).

**Closed by jakebailey** 2021-09-02 19:17 UTC
Labels: in backlog, needs investigation, docstrings, in iteration
