### ISSUE TITLE
Most features stopped working on 2021.3.3

### ISSUE THREAD

**Issue by matejcik** [microsoft/pylance-release#1103] opened 2021-03-30 08:49 UTC
Issue Type: <b>Bug</b>

symbol under cursor is not highlighted, autocompletion is "Loading..." forever, `if False` blocks are not greyed out, etc.

i can't find any remotely relevant error messages in any of the logs, so let's hope the autoreporter attaches something useful

downgrading to 2021.3.2 restores all functionality

Extension version: 2021.3.2
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.53GB (7.19GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 0fa4fd55-8423-48c9-a007-bdcaf5801901|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontbcf:30265426
pythonvspyt943:30280189
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by vikramjit-sidhu** [comment] 2021-03-30 09:41
I faced the same issue with 2021.3.3, pylance has stopped working

**Comment by jakebailey** [comment] 2021-03-30 17:30
Without the trace logs our bug template asks for, it's not really possible to look into this. Can you please enable trace logging and attach the logs?

See https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue for a copy of the instructions.

**Comment by matejcik** [comment] 2021-03-31 08:33
well i should have known to do that ... but the bug reporter from inside vscode does not show the template. Would it be possible to do something about it?

Anyway, unfortunately these logs don't show anything particularly interesting either:
<details><summary>language server trace log</summary>

```
[Info  - 10:31:08] Pylance language server 2021.3.3 (pyright be28f16e) starting
[Info  - 10:31:08] Server root directory: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.3/dist
[Info  - 10:31:08] No configuration file found.
[Info  - 10:31:08] Setting pythonPath for service "trezor-firmware": "/home/matejcik/projekty/prace/trezor-firmware/.venv/bin/python"
Search paths found for configured python interpreter:
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/matejcik/projekty/prace/trezor-firmware/.venv/lib/python3.8/site-packages
  /home/matejcik/projekty/prace/trezor-firmware/python/src
[Warn  - 10:31:08] stubPath /home/matejcik/projekty/prace/trezor-firmware/typings is not a valid directory.
[Info  - 10:31:08] Assuming Python version 3.8
[Info  - 10:31:08] Assuming Python platform Linux
[Info  - 10:31:08] Searching for source files
[Info  - 10:31:08] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/.venv
[Info  - 10:31:09] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py36
[Info  - 10:31:09] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py37
[Info  - 10:31:09] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py38
[Info  - 10:31:09] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py39
[Info  - 10:31:09] Background analysis(1) root directory: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.3/dist
[Info  - 10:31:09] Background analysis(1) started
Background analysis message: setConfigOptions
IntelliCode model /home/matejcik/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.12/cache/E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19
Loading ONNX runtime...
Loaded ONNX runtime. Creating IntelliCode session...
2021-03-31 09:31:09.979405470 [I:onnxruntime:, inference_session.cc:226 operator()] Flush-to-zero and denormal-as-zero are off
2021-03-31 09:31:09.979475391 [I:onnxruntime:, inference_session.cc:233 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-03-31 09:31:10.007574234 [I:onnxruntime:, inference_session.cc:1107 Initialize] Initializing session.
2021-03-31 09:31:10.007600251 [I:onnxruntime:, inference_session.cc:1132 Initialize] Adding default CPU execution provider.
2021-03-31 09:31:10.010721777 [I:onnxruntime:, reshape_fusion.cc:37 ApplyImpl] Total fused reshape node count: 0
2021-03-31 09:31:10.011190730 [I:onnxruntime:, reshape_fusion.cc:37 ApplyImpl] Total fused reshape node count: 0
2021-03-31 09:31:10.018129962 [V:onnxruntime:, inference_session.cc:893 TransformGraph] Node placements
2021-03-31 09:31:10.018151589 [V:onnxruntime:, inference_session.cc:895 TransformGraph] All nodes have been placed on [CPUExecutionProvider].
2021-03-31 09:31:10.018330017 [V:onnxruntime:, session_state.cc:76 CreateGraphInfo] SaveMLValueNameIndexMapping
2021-03-31 09:31:10.018382503 [V:onnxruntime:, session_state.cc:122 CreateGraphInfo] Done saving OrtValue mappings.
2021-03-31 09:31:10.018654831 [I:onnxruntime:, session_state_utils.cc:103 SaveInitializedTensors] Saving initialized tensors.
2021-03-31 09:31:10.018731533 [I:onnxruntime:, session_state_utils.cc:177 SaveInitializedTensors] [Memory] SessionStateInitializer statically allocates 35748096 bytes for Cpu

2021-03-31 09:31:10.039429764 [I:onnxruntime:, session_state_utils.cc:219 SaveInitializedTensors] Done saving initialized tensors
2021-03-31 09:31:10.041757392 [I:onnxruntime:, inference_session.cc:1282 Initialize] Session successfully initialized.
Created IntelliCode session.
```
</details>

fwiw i tried to toggle different Python interpreters, nothing helped either

**Comment by matejcik** [comment] 2021-03-31 08:36
for comparison, here is a working log from 2021.3.2.

this line is conspicuously missing from the new one; presumably things stop at that
```
[Info  - 10:34:23] Found 4792 source files
```

<details><summary>pylance 2021.3.2 trace log</summary>

```
[Info  - 10:34:22] Pylance language server 2021.3.2 (pyright 85309906) starting
[Info  - 10:34:22] Server root directory: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist
[Info  - 10:34:22] No configuration file found.
[Info  - 10:34:22] Setting pythonPath for service "trezor-firmware": "/home/matejcik/projekty/prace/trezor-firmware/.venv/bin/python"
Search paths found for configured python interpreter:
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/matejcik/projekty/prace/trezor-firmware/.venv/lib/python3.8/site-packages
  /home/matejcik/projekty/prace/trezor-firmware/python/src
[Error - 10:34:22] stubPath /home/matejcik/projekty/prace/trezor-firmware/typings is not a valid directory.
[Info  - 10:34:22] Assuming Python version 3.8
[Info  - 10:34:22] Assuming Python platform Linux
[Info  - 10:34:22] Searching for source files
[Info  - 10:34:22] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/.venv
[Info  - 10:34:23] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py36
[Info  - 10:34:23] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py37
[Info  - 10:34:23] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py38
[Info  - 10:34:23] Auto-excluding /home/matejcik/projekty/prace/trezor-firmware/python/.tox/py39
[Info  - 10:34:23] Found 4792 source files
[Info  - 10:34:23] Background analysis(1) root directory: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist
[Info  - 10:34:23] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
IntelliCode model /home/matejcik/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.12/cache/E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19
Background analysis message: markAllFilesDirty
Background analysis message: ensurePartialStubPackages
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py ...
[BG(1)]   parsing: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (67ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 4ms] (137ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/builtins.pyi (46ms)
[BG(1)]   binding: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (5ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/gc.pyi [fs read 0ms] (8ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/gc.pyi (1ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/sys.pyi [fs read 0ms] (8ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/sys.pyi (4ms)
[BG(1)]   parsing: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/generated/trezorutils.pyi [fs read 0ms] (2ms)
[BG(1)]   binding: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/generated/trezorutils.pyi ...
[BG(1)]     parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 0ms] (31ms)
[BG(1)]     binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/typing.pyi (19ms)
[BG(1)]   binding: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/generated/trezorutils.pyi (51ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (18ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 0ms] (5ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (5ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (4ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
[BG(1)]   parsing: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/uos.pyi [fs read 0ms] (0ms)
[BG(1)]   binding: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/uos.pyi (1ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (28ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/types.pyi (8ms)
[BG(1)]   parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_importlib_modulespec.pyi [fs read 0ms] (2ms)
[BG(1)]   binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_importlib_modulespec.pyi (1ms)
[BG(1)]   parsing: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/micropython.pyi [fs read 1ms] (3ms)
[BG(1)]   binding: /home/matejcik/projekty/prace/trezor-firmware/core/mocks/micropython.pyi (0ms)
[BG(1)] getSemanticTokens full at /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (616ms)
Background analysis message: getSemanticTokens range
Loading ONNX runtime...
Loaded ONNX runtime. Creating IntelliCode session...
2021-03-31 09:34:24.804706327 [I:onnxruntime:, inference_session.cc:226 operator()] Flush-to-zero and denormal-as-zero are off
2021-03-31 09:34:24.804774259 [I:onnxruntime:, inference_session.cc:233 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-03-31 09:34:24.831947705 [I:onnxruntime:, inference_session.cc:1107 Initialize] Initializing session.
2021-03-31 09:34:24.831976102 [I:onnxruntime:, inference_session.cc:1132 Initialize] Adding default CPU execution provider.
2021-03-31 09:34:24.835085434 [I:onnxruntime:, reshape_fusion.cc:37 ApplyImpl] Total fused reshape node count: 0
2021-03-31 09:34:24.835569873 [I:onnxruntime:, reshape_fusion.cc:37 ApplyImpl] Total fused reshape node count: 0
2021-03-31 09:34:24.842620703 [V:onnxruntime:, inference_session.cc:893 TransformGraph] Node placements
2021-03-31 09:34:24.842636391 [V:onnxruntime:, inference_session.cc:895 TransformGraph] All nodes have been placed on [CPUExecutionProvider].
2021-03-31 09:34:24.842793846 [V:onnxruntime:, session_state.cc:76 CreateGraphInfo] SaveMLValueNameIndexMapping
2021-03-31 09:34:24.842843568 [V:onnxruntime:, session_state.cc:122 CreateGraphInfo] Done saving OrtValue mappings.
2021-03-31 09:34:24.843122028 [I:onnxruntime:, session_state_utils.cc:103 SaveInitializedTensors] Saving initialized tensors.
2021-03-31 09:34:24.843206822 [I:onnxruntime:, session_state_utils.cc:177 SaveInitializedTensors] [Memory] SessionStateInitializer statically allocates 35748096 bytes for Cpu

2021-03-31 09:34:24.863334846 [I:onnxruntime:, session_state_utils.cc:219 SaveInitializedTensors] Done saving initialized tensors
2021-03-31 09:34:24.865116699 [I:onnxruntime:, inference_session.cc:1282 Initialize] Session successfully initialized.
Created IntelliCode session.
[BG(1)] getSemanticTokens range 31:0 - 145:23 at /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (11ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py ...
[BG(1)]   checking: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (49ms)
[BG(1)] analyzing: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (49ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (105ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 6ms] (168ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/builtins.pyi (51ms)
[FG] binding: /home/matejcik/projekty/prace/trezor-firmware/core/src/trezor/utils.py (7ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (26ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (3ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 3ms] (53ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/typing.pyi (11ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 2ms] (5ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (1ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/sys.pyi [fs read 0ms] (9ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/sys.pyi (8ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (21ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/types.pyi (4ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_importlib_modulespec.pyi [fs read 0ms] (1ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/_importlib_modulespec.pyi (1ms)
[FG] parsing: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
[FG] binding: /home/matejcik/.vscode/extensions/ms-python.vscode-pylance-2021.3.2/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```
</details>

**Comment by matejcik** [comment] 2021-03-31 17:15
in general, yes. In python sources, I don't think so but I'll need to verify

**Comment by jakebailey** [comment] 2021-03-31 17:17
Given the large number of files, are you running pylance in `workspace` mode, as opposed to the default `openFilesOnly` mode?

There may be a fix that affects you in today's release, but there may be another lurking symlink issue. It doesn't really matter what the symlink is, we're likely going to encounter it during import resolution, file scanning, etc. I'm guessing there's some broken link or other strange problem that's breaking the file scanning.

**Comment by jakebailey** [comment] 2021-03-31 23:12
Can you retry with 2021.3.4, which we've just released?

**Comment by akhti** [comment] 2021-04-01 08:04
I confirm a similar problem on 2021.3.4 in `openFilesOnly` mode

My workspace contains a symlink to huge folder with notebooks (`ln -s /some/path notebooks`) and it hangs Pylance. Last 2 messages in the log are:
```
[Info  - 7:58:20 AM] Searching for source files
[Warn  - 7:58:28 AM] Skipping recursive symlink "/home/akhti/src/rep/notebooks/hey/root/bin/X11" -> "/usr/bin"
```

A few additional data points:
* It works if I delete the symlink
* Adding `**/notebooks` to all excludes (files.exclude, search.exclude) doesn't help
* Setting `"search.followSymlinks": false` doesn't help

**Comment by matejcik** [comment] 2021-04-01 08:29
> Can you retry with 2021.3.4, which we've just released?

2021.3.4 fixes the problem for me.

for the record, i'm in the default `openFilesOnly` mode

**Comment by vikramjit-sidhu** [comment] 2021-04-01 12:05
For me as well 2021.3.4 fixes the issue with pylance

**Comment by jakebailey** [comment] 2021-04-01 16:33
Thanks for confirming the fix.

@akhti That doesn't seem like exactly the same issue; it appears as though you have a symlink to `/usr` itself... I can't see that being what you intended.

Those "excludes" and "search" settings are for VS Code itself, and are not used for any analysis options. I'm not aware of any LS that reuses VS Code's UI/search options for its own configuration.

Can you try creating a `pyrightconfig.json` in your project and configure `excludes` there? See https://github.com/microsoft/pyright/blob/master/docs/configuration.md for info.

I'm sort of surprised we search for source files when in `openFilesOnly` mode, honestly. I'd think we'd avoid that step and rely on file opens to look for things, and that sounds like a bug to me.

Would you consider filing a new issue with your case so we can treat it separately? It sounds like those who reported this issue originally are fixed, so I want to be able to handle your case and close this.

**Comment by akhti** [comment] 2021-04-01 16:48
@jakebailey adding excludes to `pyrightconfig.json` helped. Thanks a ton!

**Comment by erictraut** [comment] 2021-04-01 16:57
>I'm sort of surprised we search for source files when in openFilesOnly mode, honestly. I'd think we'd avoid that step and rely on file opens to look for things, and that sounds like a bug to me.

This is by design, not a bug. We need that to do "find all references", "go to symbols in workspace", auto-import, etc. We need to understand what files comprise the project.

**Comment by jakebailey** [comment] 2021-04-01 17:00
I think we may want to look into that in the future for improvement, then. MPLS was lazy in that when you tried to find references, it'd do a scan of files in the workspace for files containing the string you were referring to, and then ensure they are open and present in the analysis. That's potentially better, though doesn't really fix the "I symlinked `/usr`" case.

Symbols/auto-import we get from indexing, and use the analysis data if present. Not so much in pyright, though.

In any case, the original issue here is fixed, so I'll close this.

**Closed by jakebailey** 2021-04-01 17:00 UTC
Labels: waiting for info

**Comment by erictraut** [comment] 2021-04-01 17:04
>Symbols/auto-import we get from indexing

Indexing relies on understanding which files are in the project too, so I don't see any way that we can get around this scan. It's a very cheap thing to do (assuming we've eliminated symlink bugs that result in infinite loops :) ). It normally takes a fraction of a second even for large code bases, so I don't worry about doing it upfront.
