### ISSUE TITLE
Code View/Quick Look/Intellisense - Docstrings newlines not displayed correctly

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/pylance-release#476] opened 2020-10-12 17:30 UTC
## Environment data

-   Language Server version: v2020.10.0
-   OS and version: Mac OS Catalina, 10.15.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.1

## Expected behaviour

Docstring newlines and tab indents are displayed as separate lines and indented (without having to add "\n", "\t"):

<img width="754" alt="Screen Shot 2020-10-12 at 10 19 21" src="https://user-images.githubusercontent.com/29611875/95774682-b5754300-0c75-11eb-8155-f066ac469418.png">

## Actual behaviour

Docstring newlines are joined together into single line, unless "\n" or "\t" is manually added to docstring:

<img width="752" alt="Screen Shot 2020-10-12 at 10 18 11" src="https://user-images.githubusercontent.com/29611875/95774344-1a7c6900-0c75-11eb-82b5-78b1c40bf4d7.png">

**Comment by jakebailey** [comment] 2020-10-12 17:40
Duplicate of #48. This is a known issue with the docstring converter; it tries to produce readable output for all possible docstring formats, and this particular case isn't converted perfectly and stands to be improved.

**Closed by jakebailey** 2020-10-12 17:40 UTC
Labels: triage
