### ISSUE TITLE
Pylance keeps crashing

### ISSUE THREAD

**Issue by wadelamb** [microsoft/pylance-release#6235] opened 2024-08-06 06:45 UTC
Type: <b>Bug</b>

Pylance keeps crashing 

Extension version: 2024.7.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.0-190-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.37GB free)|
|Process Argv|--crash-reporter-id 548ace5e-f44d-40e5-a9e8-651ce714e892|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|7.65GB (6.50GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: WXI_Server|
|OS|Linux x64 5.4.0-190-generic|
|CPUs|Intel(R) Xeon(R) E-2224G CPU @ 3.50GHz (4 x 4449)|
|Memory (System)|7.59GB (0.93GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

**Comment by rchiodo** [comment] 2024-08-06 16:29
Thanks for the issue. Can you provide the logs as described here (or code that causes the crash)?
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by Jacob-Stevens-Haas** [comment] 2024-08-11 22:51
@rchiodo, I'm running into this problem on the current and previous version of Pylance.  I've been able to trigger it reliably.  My system is slightly different than OP's: 
local: windows 11 Home; Version 10.0.22621; Build 22621
Remote: Linux 6.5.0-44-generic; 22.04.1-Ubuntu

I don't _think_ it's an out of memory error: this is a small repository with unimportant directories (`/env, __pycache__/, etc`) gitignored.  Remote is a lambda machine with 500GB available memory.  (Unless pylance runs on the local machine, not the remote?)

When I open the repository I'm fine.  I run a script debug.py in a Jupyter interactive window.  When I run another script, debug2.py in a Jupyter interactive window, pylance crashes.

<details>

<summary> My (trace) logs </summary>

</details>

**Comment by rchiodo** [comment] 2024-08-13 16:27
Thanks @Jacob-Stevens-Haas , your issue is likely different than the original poster. Yours is this:

```
Error: Debug Failure. False expression: Duplicate path in cellFilePaths: untitled:/Interactive-1.interactive.py#W1sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W2sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#X44sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#X45sdW50aXRsZWQ%3D
```

Which is likely related to the regression we caught here:
https://github.com/microsoft/pylance-release/issues/6178

**Comment by janosh** [comment] 2024-09-10 17:27
@rchiodo i'm using v2024.9.1 but still having the same issue. don't think [20247104-31-july-2024-prerelease](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20247104-31-july-2024-prerelease) actually solved the issue as stated here https://github.com/microsoft/pylance-release/issues/6178#issuecomment-2261398211

```
2024-09-10 13:23:29.941 [info] Error: Debug Failure. False expression: Duplicate path in cellFilePaths: untitled:/Interactive-1.interactive.py#W1sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W2sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W3sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W4sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W5sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W6sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#X10sdW50aXRsZWQ%3D



untitled:/Interactive-1.interactive.py
    at _0x3b1d9a (/Users/janosh/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1040515)
    at _0x3c03f1 (/Users/janosh/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1044937)
    at _0x4e65cb (/Users/janosh/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1045372)
    at /Users/janosh/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1001232

2024-09-10 13:23:29.971 [info] [Error - 1:23:29 PM] Server process exited with code 1.
2024-09-10 13:23:29.973 [info] [Error - 1:23:29 PM] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.

```

**Comment by rchiodo** [comment] 2024-09-10 17:36
Thanks, that should be this error here:
#6357 

Which should be fixed this week.

**Comment by rchiodo** [comment] 2024-09-10 17:37
You can workaround the issue by closing all interactive windows and restarting VS code.

**Comment by rchiodo** [comment] 2024-09-11 16:56
Going to just close this as a dupe of #6357.  I don't think the original poster had #6357, but since they haven't responded, closing this one.

**Closed by rchiodo** 2024-09-11 16:56 UTC
Labels: waiting for user response, needs repro
