### ISSUE TITLE
Renaming a folder is abnormally slow on macOS 12.4 with pylance version >= 2021.10.1

### ISSUE THREAD

**Issue by XinzeZhang** [microsoft/pylance-release#3130] opened 2022-08-03 10:44 UTC
## Environment data

-   Language Server version: 2021.10.1
-   OS and version: macOS 12.4
-   Python version (& distribution if applicable, e.g. Anaconda):  python 3.8.11

## Repro Steps
![bug10 1](https://user-images.githubusercontent.com/17476403/182588160-12019452-afa4-40c8-b988-1870f05a1521.gif)

1. Under the above-mentioned environment, open a folder with vs coder, select the pylance version >= 2021.10.1
2. Renaming a sub-folder, then the bug will show as the uploaded gif.
3. If the pylance version  is <= 2021.10.0, renaming a folder will be as normal as usual.

## Expected behavior

Renaming the folder or file quickly.

## Actual behavior

Renaming the folder or file with too much time, and if the process is manually stopped, the file name or the folder name is still changed.

## Logs

```
[Info  - 6:43:11 PM] Found 137 source files
[Info  - 6:43:11 PM] Searching for source files
[Error - 6:43:21 PM] Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.

```

**Comment by XinzeZhang** [comment] 2022-08-03 10:49
However, as pointed above, if downgrade the version of pylance <= v2021.10.0, the same opreation works normally
![bug10 0](https://user-images.githubusercontent.com/17476403/182590629-82f4e7c2-2c81-44ee-b85b-e5d089a28a76.gif)
.

**Comment by heejaechang** [comment] 2022-08-03 18:44
that is happening because we are parsing all files to update import references. before we didn't have this feature so user had to manually find and update all imports. the feature is added in 2021.10.1 version.

**Comment by heejaechang** [comment] 2022-08-03 18:48
> the file name or the folder name is still changed

this is by design so that user can cancel reference updates if they don't want but still get rename they did.

**Comment by XinzeZhang** [comment] 2022-08-03 18:53
Thanks for response.

Is there an option to  manually close this feature？
If this feature be closed，would the scenario i met be solved？



Sincerely，

Xinze Zhang
------
Ph.D Candidate,
John Hopcroft Lab,
School of Computer & Science,
Huazhong University of Science & Technology

在 2022年8月4日，02:49，Heejae Chang ***@***.***> 写道：

﻿

the file name or the folder name is still changed

this is by design so that user can cancel reference updates if they don't want but still get rename they did.

**Comment by heejaechang** [comment] 2022-08-03 18:54
if you have a specific bug such as "import didn't update properly and etc" or performance issue, please provide us instructions to repro the issue so that we can take a look. otherwise, there is not much we can do.

the perf of updating imports is linear to number of references * number of files in the folder.

**Comment by heejaechang** [comment] 2022-08-03 18:54
> Thanks for response.
Is there an option to  manually close this feature？
If this feature be closed，would the scenario i met be solved？

unfortunately, the cancellation is the escape patch

**Comment by heejaechang** [comment] 2022-08-03 18:59
ah, by the way, vscode had a bug on cancellation that got fixed. I can't remember exactly when that got fixed but latest vscode should have the fix. before that, even if you click the cancellation, vscode won't let us know about the cancellation causing perf issue.

the latest vscode and pylance shouldn't have that problem.

thank you.

**Closed** 2022-08-03 19:00 UTC
Labels: by design

**Comment by XinzeZhang** [comment] 2022-08-03 19:43
Thanks so much.

Indeed, I have so much files in this workspace.

> the latest vscode and pylance shouldn't have that problem.

I have updated to the latest vscode as well as pylance,  and closed the ‘auto import completions’, 'auto search paths', and complete function parens', updating the folder name is still so slow.

Sincerely, hope the future version provide an option or a feature that, if the auto import function of pylance is closed,  parsing all the files in the workspace when updating the file or folder name would also be closed.
Or, provide an option to exclude the folder of parsing.

Thanks.
![bug10 2](https://user-images.githubusercontent.com/17476403/182695477-b1ef2755-8229-41b7-b6f6-0d3b6f7f9696.gif)

**Comment by XinzeZhang** [comment] 2022-08-03 19:47
> > Thanks for response.
> > Is there an option to  manually close this feature？
> > If this feature be closed，would the scenario i met be solved？
> 
> unfortunately, the cancellation is the escape patch

Sorry, my response is misleading.
I want to close the feature of parsing, rather the cancellation.
