### ISSUE TITLE
pytest fixture type resolved as function but not as fixture return value

### ISSUE THREAD

**Issue by hellozyemlya** [microsoft/pylance-release#4574] opened 2023-06-30 19:00 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
example_fixture does not show autocomplete for list, but it is expected to.

## Steps to reproduce:
1. create file
```
import pytest

@pytest.fixture()
def example_fixture() -> list:
    return []


def test_my_fixture(example_fixture):
    assert example_fixture == "value"
```

2. ensure there is no list autocomplete for example_fixture param in test_my_fixture

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.3
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

Extension version: 2023.9.11461009
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|. --crash-reporter-id 83c6201b-6769-4da6-96fe-fb868d824980|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnoceb:30776495

```

</details>

**Comment by rchiodo** [comment] 2023-07-06 19:08
Thanks for the issue. This is actually a dupe of https://github.com/microsoft/pylance-release/discussions/4388. Please upvote the discussion.

[Pyright ](https://github.com/Microsoft/pyright)(the type analyzer that Pylance is based upon) doesn't know about the type of the parameter (well because the fixture return value is very specific to pytest and Pyright doesn't have any special logic for pytest). Pylance has special code to handle the parameters for test functions, but it doesn't currently inject the type back into Pyright so that completions work. That discussion item is there to see how important this is to customers.

**Closed by rchiodo** 2023-07-06 19:08 UTC
Labels: needs investigation
