### ISSUE TITLE
"Expected expression" incorrectly reported for valid nested f-string

### ISSUE THREAD

**Issue by amachanic** [microsoft/pylance-release#200] opened 2020-08-04 20:40 UTC
## Environment data

-   Language Server version: 2020.7.4
-   OS and version: CentOS 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.3

## Expected behaviour

No problems reported.

## Actual behaviour

Pylance reports "Expected expression" and "Unexpected token at end of expression" problems in valid code.

![image](https://user-images.githubusercontent.com/39809964/89343701-afaa2280-d672-11ea-8130-dc3834699505.png)

## Code Snippet / Additional information

```python
x = f"""
    {
        f'''
        '''
    }
"""
```

**Comment by erictraut** [comment] 2020-08-04 21:19
Thanks for the bug report. 

The issue isn't with the nested f-string, it's with the newline tokens within the outer f-string expression. The Python spec doesn't indicate that f-string expressions should be treated as though they are surrounded by parentheses, but clearly they are treated that way by the Python interpreter. I've fixed the issue, and it will work as expected in the next release.

In the meantime, you can work around the problem by either 1) removing the newline characters from within the curly brackets, or 2) surrounding the expression within the curly brackets with parentheses.

**Comment by jakebailey** [comment] 2020-08-05 23:56
This issue has been fixed in version 2020.8.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202080-5-august-2020

**Closed by jakebailey** 2020-08-05 23:56 UTC
Labels: bug, fixed in next version
