### ISSUE TITLE
Navigate to source code rather than typeshed

### ISSUE THREAD

**Issue by JeroenBos** [microsoft/pylance-release#742] opened 2020-12-16 00:19 UTC
I'm looking for a way to navigate to source code of a third-party library. In my experience over the past months sometimes the command "Goto definition" navigates to the actual source code and sometimes to a `.pyi` file from the pylance typeshed, for the same function. 
I have not been able to figure out what affects this. 

Given that I prefer the actual source code over the typeshed, is there a setting such that this preference is adhered to, specifically for navigation?

And more generally I'm interested in what settings and state are involved in determining to which to navigate.

There are of course workaround. What I tend to do is to trigger code in the file that I want to use to and let the debugger navigate to that file (the debugger can consistently find the file, so no problem there).
Alternatively I could look up the file manually, but that's often more time consuming. Both feel rather like workarounds.

**Comment by jakebailey** [comment] 2020-12-16 00:21
Duplicate of #65.

**Closed by jakebailey** 2020-12-16 00:21 UTC
Labels: triage
