### ISSUE TITLE
Jupyter extension stops working on remote session

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/pylance-release#5591] opened 2024-03-06 17:40 UTC
## Environment data

-   VS Code version: 1.87.0
-   Jupyter Extension version (available under the Extensions sidebar): 2024.2.0
-   Python Extension version (available under the Extensions sidebar): 2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Linux SUSE 12, Linux 4.12.14-122.136-default
-   Python and/or Anaconda version: Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Using pixi package manager to create an environment
-   Jupyter server running: Remote

## Expected behaviour

Show autocomplete options as I type variable names

## Actual behaviour

If the variable already exists, then the variable names sometimes show up, but it is very flaky. Also, as I type an error marker appears at the very first line of the cell

![image](https://github.com/microsoft/vscode-jupyter/assets/8355965/3c6348d9-420d-4e38-ad90-0d09bc7bcfd5)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

I don't know how I ended up here but all of my Jupyter sessions have the same problem.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.87.0, ssh-remote, desktop)
Jupyter Extension Version: 2024.2.0.
Python Extension Version: 2024.2.1.
Pylance Extension Version: 2024.2.3.
Platform: linux (x64).
Workspace folder ~/myworkspace, Home = /nfs/site/home/adavoody
09:27:01.768 [info] Start refreshing Kernel Picker (1709746021768)
09:27:01.780 [info] Using Pylance
09:27:02.496 [warn] Password for http://remote.server.address:8888/ was invalid.
09:27:02.808 [info] Starting Kernel connectToLiveRemoteKernel, 793ba9ff-717e-494d-823b-7c18cd8d9f58  for '~/myworkspace/analysis.ipynb' (disableUI=true)
09:27:02.814 [warn] Password for http://remote.server.address:8888/ was invalid.
09:27:02.930 [info] Started session for kernel connectToLiveRemoteKernel:793ba9ff-717e-494d-823b-7c18cd8d9f58
09:27:02.935 [info] Registering Kernel Completion Provider from kernel Python 3 (ipykernel) (analysis.ipynb) for language python
09:27:03.477 [info] End refreshing Kernel Picker (1709746021768)
09:27:03.575 [error] Error downloading from http://remote.server.address:8888/nbextensions/jupyter-js-widgets/extension.js: Not Found
09:27:03.577 [warn] Password for http://remote.server.address:8888/ was invalid.
09:27:03.579 [error] Error downloading from http://remote.server.address:8888/nbextensions/jupyter-js-widgets/extension.js using custom fetch: Not Found
09:27:03.579 [warn] Failed to fetch script sources [Error: Error downloading from http://remote.server.address:8888/nbextensions/jupyter-js-widgets/extension.js using custom fetch: Not Found
	at UT.getWidgetScriptSourceUsingFetch (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:86265)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async UT.getConfigFromWidget (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:82598)
	at async Promise.all (index 0)
	at async UT.getWidgetModuleMappingsImpl (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:83022)
	at async MT.getWidgetScriptSources (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:79137)
	at async /nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:23296
	at async Promise.all (index 1)
	at async Gy.getWidgetScriptSources (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:23207)
	at async yT.sendWidgetScriptSources (/nfs/site/disks/tadm_work_19/.vscode-server/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:341:27573)]
09:27:03.630 [info] Start refreshing Kernel Picker (1709746023630)
09:27:04.114 [error] Failed to get activated conda env vars for /nfs/site/disks/tadm_work_19/.pixi/envs/default/bin/python
                 in 411ms
09:27:04.116 [error] Unable to determine site packages path for python /nfs/site/disks/tadm_work_19/.pixi/envs/default/bin/python (Conda)
09:27:04.123 [info] Process Execution: /nfs/site/disks/tadm_work_19/.pixi/envs/default/bin/python -m pip list
09:27:04.168 [info] Process Execution: /nfs/site/disks/tadm_work_19/.pixi/envs/default/bin/python -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:27:06.055 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0549fa5e0646bd4db490c293a1c9bc552746aee0a5af14aa4eff56c0ed6965828./usr/include/python./usr/include/python.-m#ipykernel_launcher' for view = 'jupyter-notebook'
09:27:06.055 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0549fa5e0646bd4db490c293a1c9bc552746aee0a5af14aa4eff56c0ed6965828./usr/include/python./usr/include/python.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
09:27:06.212 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd09872c1d112b0de58b80ebd0ec1be9a5b8f9ab2530e0ef55cfaa211b5b396a226./usr/lib64/python./usr/lib64/python.-m#ipykernel_launcher' for view = 'jupyter-notebook'
09:27:06.213 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd09872c1d112b0de58b80ebd0ec1be9a5b8f9ab2530e0ef55cfaa211b5b396a226./usr/lib64/python./usr/lib64/python.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/include/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:06.229 [error] Failed to get env details from Python API for /usr/lib64/python without an error
09:27:07.323 [info] End refreshing Kernel Picker (1709746023630)
```

</p>
</details>

**Comment by rchiodo** [comment] 2024-03-06 19:54
This is likely a dupe of this issue here:
https://github.com/microsoft/vscode/issues/206487

I'm marking your issue as a dupe of this one:
https://github.com/microsoft/pylance-release/issues/5543

If you switch to the insiders version of VS code the problem should be fixed.

**Closed by rchiodo** 2024-03-06 19:54 UTC
Labels: bug, needs repro
