### ISSUE TITLE
"module" is not a known member of module Pylance(reportGeneralTypeIssues)

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#1860] opened 2021-09-22 09:43 UTC
I cooked this down to a tiny setup:
* `test.py` - see snippet below
* `mypack` - folder
    * `__int__.py` - empty
    * `module1.py` - containing function stub `def do_something():\n    return`
    * `module2.py` - empty
 
In `test.py` there is:
```py
import mypack.module1


def main():
    import mypack.module2

    mypack.module1.do_something() # <-


if __name__ == '__main__':
    main()
```
So I do a lazy import in my function and now I get `module1` highlighted:
![image](https://user-images.githubusercontent.com/218956/134319926-50d7ced3-67fb-4e53-993f-2c74f05a4bba.png)

Although this never seems to be a problem! I'm aaalmost sure we discussed this somewhere else already but currently I can't remember what was wrong with this. In this setup when I debug step through it or even print `mypack.module1` is always there and seems untouched by the import. In any Python version! Is there a way to make it break like that? 🤔

## Environment data
-   Language Server version: v2021.9.2
-   Python Extension: v2021.9.1246542782
-   Python version: 3.9.7, 3.8.10, 2.7.18

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z (1 wk ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by erictraut** [comment] 2021-09-22 15:32
This is a duplicate of https://github.com/microsoft/pylance-release/issues/1834.

**Closed** 2021-11-16 19:04 UTC
Labels: duplicate

**Comment by ewerybody** [comment] 2021-11-17 12:30
Some explanation like [this one from @erictraut  in #1834](https://github.com/microsoft/pylance-release/issues/1834#issuecomment-922347058) should be on the report about this.

To the user this seems super broken while the code obviously works.

To my question:
> Is there a way to make it break like that? 🤔

was no answer.

So this should rather be a "**warning**" with a tip on how to fix it than an red-underlined issue.
