### ISSUE TITLE
Python interactive 5 times crashed!

### ISSUE THREAD

**Issue by moghadas76** [microsoft/pylance-release#6370] opened 2024-09-09 20:54 UTC

**Comment by rchiodo** [comment] 2024-09-09 21:31
I would hazard a guess that you're using the interactive window?

If so, this would likely be a dupe of #6357 

Otherwise, can you include the output of the `Python Language Server` output tab?

**Comment by justinsolms** [comment] 2024-09-12 07:14
Hi. I have and issue with Pylance v2024.8.2. To get on with my project I rolled back arbitrarily to 2023.9.10 and the issue went away. This morning, in hope, I updated to Pylance v2024.9.1 and the issue came back.

The notification is:
"Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details."

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-41-generic snap

Please see output attached in file [pylance.txt](https://github.com/user-attachments/files/16974960/pylance.txt).

**Comment by rchiodo** [comment] 2024-09-12 16:18
@justinsolms this a dupe of #6357. This output in the log indicates that:

Error: Debug Failure. False expression: Duplicate path in cellFilePaths: untitled:/Interactive-1.interactive.py#W1sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W2sdW50aXRsZWQ%3D
untitled:/Interactive-1.interactive.py#W3sdW50aXRsZWQ%3D

**Comment by DaiZack** [comment] 2024-09-18 00:50
The v2024.9.1 still has this issue. The v2024.9.100 (pre-released) version seems working well.

**Comment by justinsolms** [comment] 2024-09-20 11:31
I'm now on v2024.9.101 (pre-release) and its working fine for me.

**Closed** 2024-10-04 22:10 UTC
Labels: waiting for user response, needs repro
