### ISSUE TITLE
The new auto-indent feature is dangerous for Python users

### ISSUE THREAD

**Issue by netw0rkf10w** [microsoft/pylance-release#3997] opened 2023-02-23 10:51 UTC
Hello,

The new auto-indent feature is very dangerous. If the user is not careful then it can introduce hidden bugs into their code.

If I have something like this:

```python
for a in some_list:
  # do something
for b in some_list:
  # do some other thing
```

And if I place the cursor at the beginning of the second `for` and press Enter, then it becomes
```python
for a in some_list:
  # do something

  for b in some_list:
    # do some other thing
```

And this happens even if I change the mode from "Full" to "Keep".

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.1
- OS Version: macOS 10.15.7

Steps to Reproduce: Create a Python file and use the above example.

**Comment by rchiodo** [comment] 2023-02-23 19:38
Thanks for the issue. Seems like we shouldn't auto indent in this case:

```python
for a in some_list:
  # do something
<hit enter here>for b in some_list:
  # do some other thing
```

**Comment by debonte** [comment] 2023-02-23 19:41
I believe this is a dupe of https://github.com/microsoft/pylance-release/issues/3974. I'll look at these two today.

**Closed** 2023-02-23 19:42 UTC
Labels: bug
