### ISSUE TITLE
Auto-import fails in standalone files

### ISSUE THREAD

**Issue by papple23g** [microsoft/pylance-release#5519] opened 2024-02-26 16:02 UTC
## Environment data
-   Language Server version: Any release version above 2024.2.1
-   OS and version:  Windows 10
-   Python version: 3.11.8

## Code Snippet
```python
wordList: List[str]
```
## Repro Steps
1. Open a Python file individually using VSCode.
2. Attempting auto-fix on `List` fails with no response, and it does not automatically import the missing module (`from typing import List`).

Note: This issue does not occur within a .code-workspace environment.

## Expected behavior
![1708961101791](https://github.com/microsoft/pylance-release/assets/28220061/9d18e31c-edb8-41d9-93ea-6ce97d6d4e37)

## Actual behavior
![1708961032369](https://github.com/microsoft/pylance-release/assets/28220061/f152a4b0-7213-4add-8f5e-af68c0449041)

## Logs
2023.12.1 (working version)
[working.txt](https://github.com/microsoft/pylance-release/files/14407093/working.txt)

2024.2.2 (not working version)
[not_working.txt](https://github.com/microsoft/pylance-release/files/14407101/not_working.txt)

**Comment by rchiodo** [comment] 2024-02-26 17:18
This seems to work fine in English. There must be an error parsing the UTF characters in the code action.

I can't repro this with 2023.2.2 myself, but my action list looks like so:

![image](https://github.com/microsoft/pylance-release/assets/19672699/74ba226c-c8dc-4382-9023-0c014b3a0c7d)

@heejaechang can you try it with Korean? I can't reproduce it with Korean either.

**Comment by heejaechang** [comment] 2024-02-26 20:30
I can repro this.

**Comment by heejaechang** [comment] 2024-02-26 20:44
this is a dup of https://github.com/microsoft/pyrx/issues/4740

**Comment by heejaechang** [comment] 2024-02-26 23:02
also related to https://github.com/microsoft/pyrx/issues/4762

**Comment by papple23g** [comment] 2024-04-14 09:00
Looks like the bug has been fixed in v2024.4.1.

**Comment by debonte** [comment] 2024-04-18 19:52
> Looks like the bug has been fixed in v2024.4.1.

You're correct. Sorry that we forgot to mark this as fixed. It was fixed in prerelease version 2024.3.101

**Closed by debonte** 2024-04-18 19:52 UTC
Labels: bug
