### ISSUE TITLE
Pylance suggests wrong import

### ISSUE THREAD

**Issue by LeoGSA** [microsoft/pylance-release#567] opened 2020-11-05 13:22 UTC
## Environment data
2020.11.0
-   Language Server version: XXX
-   OS and version: Windows 10 x64
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.4. -32

## Expected behaviour

import re

## Actual behaviour

import request from urllib
![image](https://user-images.githubusercontent.com/25363946/98245811-8a36f880-1f82-11eb-956b-11cbaef4e867.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment] 2020-11-05 18:54
Thanks @LeoGSA, thanks for the report. Could you please try enabling the indexer and seeing if that fixes the problem?

To enable the indexer, add the following setting to your settings JSON file
```
"python.analysis.indexing": true
```
thanks

**Comment by LeoGSA** [comment] 2020-11-05 22:46
Hi Jude )
Thanks for answering.

Do you mean that I should add this line

"python.analysis.indexing": true

to a VSCode settings json file?

If yes, then I've done it right now:

[image: image.png]

Restarted VSCode.
After that it started to prompt a BIG number of imports.

[image: image.png]

[image: image.png]

Well. It is definitely better than trying to import "from urllib import
requests"
but... if it is "re.something" - there is no sense searching for all words
having "re" in it.
I mean - it is "re" with a dot. It's a complete module name.

On the other hand, situation with requests got much better.

[image: image.png]

Thank you, Jude. ) Good luck in your job. )
Let me know if I can be of any help.

чт, 5 нояб. 2020 г. в 21:55, Jude Kavalam <notifications@github.com>:

**Comment by jakebailey** [comment] 2020-11-05 22:48
I think your email client and GitHub didn't get along; you may need to use the web UI to upload screenshots.

The expected behavior with indexing enabled is that `re` is presented at the very top of the quick fix list. There may be others below it (and we are working on the volume), but `re` should be there regardless of if it's been used yet.

**Comment by jakebailey** [comment] 2020-12-14 20:48
@LeoGSA I believe we are still waiting for a screenshot with indexing enabled. That should have gotten `re` back into the list, but it appearing by default without being loaded some other way isn't expected at the moment due to the indexer still being disabled (outside of insiders).

If you have indexing enabled and don't see `re` at the top of the list of choices, we can open this, but I'm going to close it for now as it's been sitting for more than a month.

**Closed by jakebailey** 2020-12-14 20:48 UTC
Labels: waiting for info

**Comment by LeoGSA** [comment] 2020-12-15 16:15
hi,
thank you for your letter.

it works fine for me after enabling indexing.
so if you ask me - yes, it may be closed now.

пн, 14 дек. 2020 г. в 23:49, Jake Bailey <notifications@github.com>:
