### ISSUE TITLE
Display full docstring in tooltip, as in Jupyter Lab

### ISSUE THREAD

**Issue by droumis** [microsoft/pylance-release#5710] opened 2024-03-29 16:59 UTC
Working with Python in VS code would be much improved if the full docstring was presented on hover. Often, there is nothing useful provided.

In Jupyter notebook, a useful docstring is provided with `shift` + `tab`.

The significant discrepancy can be seen in this demo. The top is VS Code (Jupyter notebook and python script), the bottom is Jupyter Lab.

https://github.com/microsoft/vscode-python/assets/6613202/c4388582-d916-4a81-ae90-d5f146c35322

**Comment by rchiodo** [comment] 2024-03-29 17:53
I believe this is a dupe of https://github.com/microsoft/pylance-release/discussions/2711. The root cause (I think) is that the doc strings returned in a notebook are dynamic. They're generated by running Python code.

Pylance (at least at the moment) is a static analyzer. We can only get docstrings from the strings that are in the python script itself.

**Comment by rchiodo** [comment] 2024-03-29 18:05
That specific example is a particularly bad one. The STL class doesn't even exist in python code. It's Cython which requires a type stub for us to understand it. See this for more information:
https://microsoft.github.io/pyright/#/type-stubs?id=type-stub-files

**Comment by rchiodo** [comment] 2024-03-29 18:05
Here's the link for the source for that class:
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/stl/_stl.pyx

**Closed by rchiodo** 2024-03-29 18:05 UTC
Labels: needs repro

**Comment by rchiodo** [comment] 2024-03-29 18:12
You can see for the MSTL class (which is in Python code), we do get the doc string:

![image](https://github.com/microsoft/pylance-release/assets/19672699/55298461-ca55-4684-9a6b-db7a0c442f11)
