### ISSUE TITLE
Cannot access member "create_user" for type "BaseManager[CustomUser]"   Member "create_user" is unknown

### ISSUE THREAD

**Issue by Qasemt** [microsoft/pylance-release#5513] opened 2024-02-25 07:26 UTC
<h3> Environment data </h3>

-   Language Server version: 2024.2.103
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by debonte** [comment] 2024-02-26 22:55
@Qasemt, can you provide a small, self-contained code sample that reproduces this issue? I suspect that the answer is that Django's behavior in your scenario is too dynamic for a static type checker to understand, but providing more detail would help us tell you for sure.

Possibly a dupe of https://github.com/microsoft/pylance-release/issues/3701

**Comment by heejaechang** [comment] 2024-03-04 20:48
closing since there is no response from users.

**Closed by heejaechang** 2024-03-04 20:48 UTC
Labels: waiting for user response, needs repro
