### ISSUE TITLE
TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined

### ISSUE THREAD

**Issue by cSDes1gn** [microsoft/pylance-release#1403] opened 2021-06-06 21:04 UTC
## Environment data
-   Language Server version: v2021.6.1-pre.1
-   OS and version: M1 MacOSX Big Sur v11.2.3 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5 64-bit ('homebrew')

## Expected behavior

Pylance should load properly. Was working fine for me Friday night.

## Actual behavior

According to the thread in [this](https://github.com/microsoft/pylance-release/issues/50) issue this problem seems to be related to`pylance` and not `intellisense`. Pylance is crashing on window load and falls back to the `jedi` language server.

## Logs
```
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'DeprecatePythonPath - control'
Python interpreter path: /opt/homebrew/bin/python3
Starting Pylance language server.
Error 2021-06-06 16:56:48: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-06 16:56:48: Failed to start language server, Class name = r, completed in 59ms, has a falsy return value, Arg 1: <Uri:/Users/christiansargusingh/Library/Application Support/Code - Insiders/User/settings.json>, Arg 2: {"sysPrefix":"/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9","envType":"Unknown","envName":"homebrew","envPath":"/opt/homebrew","path":"/opt/homebrew/bin/python3","architecture":3,"sysVersion":"3.9.5 (default, May  3 2021, 19:12:05) \n[Clang 12.0.5 (clang-1205.0.22.9)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.5 64-bit ('homebrew')"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-06 16:56:48: TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-06 16:56:48: Failed to activate language server, Class name = a, completed in 61ms, has a falsy return value, Arg 1: <Uri:/Users/christiansargusingh/Library/Application Support/Code - Insiders/User/settings.json>, Arg 2: {"sysPrefix":"/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9","envType":"Unknown","envName":"homebrew","envPath":"/opt/homebrew","path":"/opt/homebrew/bin/python3","architecture":3,"sysVersion":"3.9.5 (default, May  3 2021, 19:12:05) \n[Clang 12.0.5 (clang-1205.0.22.9)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.5 64-bit ('homebrew')"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/christiansargusingh/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/Projects/leap/spatial-codec
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py ~/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py
```

## Code Snippet / Additional information
![Screen Shot 2021-06-06 at 4 58 09 PM](https://user-images.githubusercontent.com/26971036/120939917-64283100-c6e8-11eb-846f-2c948c9a0297.png)

Thanks.

**Comment by judej** [comment] 2021-06-07 17:49
This is a dupe of #1387

**Comment by judej** [comment] 2021-06-07 17:49
@joyceerhl

**Closed by judej** 2021-06-07 17:49 UTC
Labels: triage

**Comment by joyceerhl** [comment] 2021-06-07 17:56
@cSDes1gn This is resolved in the latest daily Insiders builds of the Python extension. https://github.com/microsoft/vscode-python/suites/2904962837/artifacts/65133411 should contain the fix if you'd like to try it out now (you should get the same build if you opt into daily insiders builds for the Python extension).

**Comment by cSDes1gn** [comment] 2021-06-07 20:17
Cheers guys
