### ISSUE TITLE
Intellisense error with numpy

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#620] opened 2020-11-17 20:29 UTC
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9
-   Numpy version: 1.19.4

## Actual behaviour

```
import numpy as np

np.maximum([1, 2])
```

Pylance complains:
`"maximum" is not a known member of module`

Similarly for `numpy.absolute()` and `numpy.less_equal()` and presumably many, many more.

**Comment by jakebailey** [comment] 2020-11-17 20:32
Duplicate of #150. This is compiled code we don't currently have access too (but soon).

**Closed by jakebailey** 2020-11-17 20:32 UTC
Labels: triage
