### ISSUE TITLE
Regression: class init type checking is lost when metaclass has a generic __call__ override

### ISSUE THREAD

**Issue by smphhh** [microsoft/pylance-release#4384] opened 2023-05-18 09:50 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.5.30
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.11
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class FooMeta(type):
    def __call__(self, *args, **kwds):
        return super().__call__(*args, **kwds)

class Foo(metaclass=FooMeta):
    def __init__(self, name: str):
        pass

Foo()
```

<h3> Expected behavior </h3>

The instantiation of the class Foo should be flagged with an error because of the missing argument.

<h3> Actual behavior </h3>

No error is flagged. Auto-completion does show the correct signature though. I'm pretty sure this is a regression in Pylance `v2023.5.30`.

In practice this is causing issues with libraries that use the same generic metaclass for many different classes.

Probably related to these changes in Pyright 1.1.307?

```
Behavior Change: Modified the logic (and associated behavior) for constructor validation in cases where a metaclass has a custom __call__ method. This is part of a larger effort to clean up constructor validation and make it more consistent with runtime behaviors.
```

**Comment by smphhh** [comment] 2023-05-18 10:23
The issue is causing pretty much complete loss of type checking for all classes in the libraries of the [CDK](https://constructs.dev) ecosystem as they all share the same metaclass. Simplest example using the `constructs` library (pip install constructs):

```python
from constructs import Construct

Construct()
```

**Comment by erictraut** [comment] 2023-05-18 14:48
This was an intentional change. The standard `type` metaclass implements `__call__` in a particular documented manner. When a custom metaclass provides its own `__call__` override, a static type checker can no longer make assumptions about the behavior of the `__call__` method. It cannot, for example, assume that the `__call__` method is going to invoke the `__new__` or `__init__` method of the associated class. There were cases where pyright's previous behavior was causing problems because it was making incorrect assumptions about a custom metaclass `__call__` method. The recent rewrite of this logic was an attempt to address this problem.

It sounds like in the case of this particular library, the custom metaclass implements a `__call__` method that effectively has the same behaviors as `type.__call__`. 

I don't see a good solution here. If a static type checker assumes that a custom metaclass `__call__` method acts like `type.__call__`, it may be wrong and cause false positives, but if it doesn't make this assumption, then there is a loss of type checking for `__new__` and `__init__`. In general, pyright tries to avoid making assumptions where false positives are likely to result, so I think the new behavior is more consistent with the type checking decisions made elsewhere in pyright (preferring false negatives over false positives). That said, I can understand how this would be problematic for this particular library. I wonder if this affects other libraries as well or is limited to just this one?

If there were a good way for a static type checker to determine whether a metaclass `__call__` overrides the standard `type.__call__` behavior in ways that make it no longer safe to type check `__new__` and `__init__`, then it could make a better choice here, but I don't see a way to make this determination. At best, it would be a heuristic (e.g. the presence of a call to `super().__call__()`).

Do you have a sense for why this library has chosen to provide an override of `__call__` within its metaclass? Maybe we could work with the library maintainer to eliminate this?

**Comment by erictraut** [comment] 2023-05-18 15:25
Digging into this issue more... The problem is exacerbated for this library because of a bad type annotation in the custom metaclass. The library is explicitly annotating the return type of the `__call__` method as `Any`. That's a clear signal to a type checker that it shouldn't make assumptions about the return result.

```python
class JSIIMeta(_ClassPropertyMeta, type):
    ...
    def __call__(cls: Type[Any], *args: Any, **kwargs) -> Any:
        inst = super().__call__(*args, **kwargs)

        # Register this instance with our reference map.
        _reference_map.register_reference(inst)

        return inst
```

I recommend filing a bug with the author of this library. The type annotation here should use a type variable to preserve the type of the constructed class. Something like this...

```python
T = TypeVar("T")

...

    def __call__(cls: Type[T], *args: Any, **kwargs) -> T: ...
```

This would restore type checking for all but the `__new__` and `__init__` methods.

**Comment by smphhh** [comment] 2023-05-18 17:16
Thanks for the prompt reply (as always).

I can totally see that technically Pyright is doing the right thing here. I guess we could argue that Python being such a dynamic language as it is, statical type checkers are always going to need to make certain assumptions about the user code to remain useful. However I can also see why in this particular case the users might just as well expect the other (new) behavior.

Regarding your suggestion for improving the type annotations I'm afraid that for this particular library the `__init__` signature is extremely important as the class instantiation is a way to define a particular type of a cloud resource instance (such as a virtual server), and there are hundreds if not thousands of different classes each with their own set of arguments.

While playing with this myself I thought about just adding a `if not typing.TYPE_CHECKING` guard for the whole `__call__` method definition in the metaclass i.e.

```python
    if not TYPE_CHECKING:
        def __call__(cls: Type[Any], *args: Any, **kwargs) -> Any:
            inst = super().__call__(*args, **kwargs)

            # Register this instance with our reference map.
            _reference_map.register_reference(inst)

            return inst
```

 It seems to work but I'm not an expert so not sure if it would have any downsides? Do you think that would be a reasonable solution that could be proposed to the library authors?

**Comment by erictraut** [comment] 2023-05-18 17:31
Thinking about this more, I see three potential options:

1. * Revert to old behavior *: Pyright always assumes that a metaclass with a `__call__` override performs the same behavior as `type.__call__` unless it is explicitly annotated to return `NoReturn`. This was the behavior prior to my recent changes.
2. * Stick with new behavior *: Pyright assumes that any metaclass with a `__call__` override is potentially doing something unusual. In this case, it skips validation of `__new__` and `__init__`. This is behavior of the latest version of pyright (1.1.309).
3. * Implement hybrid behavior with heuristic *: Pyright assumes that a metaclass with a `__call__` override performs the same behavior as `type.__call__` if the evaluated return type is the same type as the `cls` parameter (i.e. the class being constructed). If the evaluated return type (whether it is explicitly annotated or inferred) is anything other than the type of the class being constructed (including `Any`), the pyright will assume that the `__call__` override is doing something unusual, and it will skip validation of the `__new__` and `__init__` methods.

The old behavior was problematic, which prompted the recent changes. For that reason, I'd prefer not to revert back to that behavior unless we have good evidence that other options are more painful for pyright users.

I think option 3 is worth exploring. This would require the library authors to make the change I suggested above. (I think they should do this regardless because annotating a return type as `Any` is almost always a bad idea if it can be avoided.)

If we stick with option 2, then your suggestion of using `if not TYPE_CHECKING` is a reasonable workaround.

Thoughts? Are there any other variants of option 3 (e.g. different heuristics) that would work better? If we apply a heuristic, I want it to be logically defensible. I think the heuristic I suggested above in option 3 meets that criteria.

**Comment by smphhh** [comment] 2023-05-18 18:11
Because changing the type signature of the `__call__` method would significantly benefit Pyright only in the particular case that the heuristic of option 3 is also implemented, and because currently MyPy and PyCharm completely ignore the method in the metaclass, I think it might be harder to argue for that change compared to the `TYPE_CHECKING` workaround.

I don't know in what ways the old behaviour was problematic so it's a bit hard to comment on the possible heuristics. How about the one that PyCharm seem to have gone with according to the linked issue, i.e. the `__call__` method is ignored if it only has `*args, **kwargs` as arguments ? The existence of the `__init__` method could be though of as a heuristic as well so maybe even the `*args, **kwargs` signature could be respected if there are no `__init__` methods?

**Comment by smphhh** [comment] 2023-05-19 08:06
> I think that asking the library maintainers to add an `if not TYPE_CHECKING` is harder to defend. This is effectively lying to the type checker about the runtime code — something that I try to avoid if I can help it.

My argument would be that since the method is only overriden to add the side effect of registering the instance the override contains no useful information to the type checker.

> I'm not crazy about a heuristic based on the input parameters (e.g. has only `*args` and `**kwargs`). Why would that correlate to cases where a `__call__` override is doing something non-standard? For example, a custom metaclass `__call__` method could inject new positional or keyword arguments before calling through to `__new__`, or it could change the standard rule about when to call (or not call) `__init__`. I don't see how the input parameter signature of `__call__` would correlate with these behaviors. So I'm not convinced these are defensible rules.

Well it doesn't necessary correlate with the behavior of course, but neither does the return type I think, the `__call__` method might just as well use some non-standard logic to build an instance of the standard type.

> One thing we might want to do here is to leave this issue open and wait to see if we get additional feedback. If this issue is limited to this one library, that's quite different from the situation where it's a widespread issue that affects many libraries.

I'll see if I can get some comment on the issue from the library authors.

**Comment by hmc-cs-mdrissi** [comment] 2023-05-23 23:01
The argument that is pyright specific thing is mainly due to mypy not handling `__call__`. It is long open issue by one mypy maintainer [here](https://github.com/python/mypy/issues/14122) and mainly low priority as metaclass behavior is niche and complex. When mypy fixes that issue then the library will have same problem.

**Comment by rchiodo** [comment] 2023-07-13 23:57
Closing as it seems this would be a bug for the library to fix.

**Closed by rchiodo** 2023-07-13 23:57 UTC

**Comment by bhperry** [comment] 2023-07-20 21:15
This also affects every implementation of fsspec because of `AbstractFileSystem(metaclass=_Cached)` (_Cached implements __call__ with no typing)
