### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by duartegameiro** [microsoft/pylance-release#5048] opened 2023-10-30 16:17 UTC
Type: <b>Bug</b>

Intellisense stopped working and this is the error on the Output of the Language Server.

TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:898287)
    at _0x170d92.<computed> (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (c:\Users\duart\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1019982)
    at async Promise.all (index 0)

Extension version: 2023.10.50
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by rchiodo** [comment] 2023-10-30 16:32
Thanks for the issue. This should be a dupe of #5009. This was fixed in our latest prerelease build 2023.10.53.

**Closed by rchiodo** 2023-10-30 16:32 UTC
Labels: needs repro

**Comment by duartegameiro** [comment] 2023-10-30 16:58
Thank you!
