### ISSUE TITLE
while keywords cause the Intellisense works too slowly 

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#1691] opened 2021-08-18 06:37 UTC
## Environment data

-   VS Code version: 1.59
-   Extension version (available under the Extensions sidebar): newest or older
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Intellisense works as normally

## Actual behaviour

Too slowly, takes about three minutes to give out one simplest Intellisense error.

## Steps to reproduce:

Paste this code into a python file and open it in the VSCode.

```
import random
from string import ascii_uppercase
from datetime import datetime as dt
from pandas import read_csv
from numpy import arange

# planet_name = input("What's the name of the planet?")

# start_time = dt.now()
error_message = "Variable undefined"


def csv_parser(path):
    a = read_csv(path, header=0, sep=";")
    return a


def rollDice(numDice):
    results = []
    for x in range(numDice):
        results.append(random.choice(range(1, 7)))
    return sum(results)


old_results = ""

loop_count = 0
while loop_count < 3:
    letters = ascii_uppercase
    numbers = "0123456789"
    letters_numbers = letters + numbers
    planet_name = f"""{random.choice(letters)}T{random.choice(letters_numbers)}-{random.choice(numbers)}{random.choice(numbers)}{random.choice(numbers)}"""

    # STEP 2: World Type (pg 74)
    overall_type_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\1 - Overall Type Table.csv"
    )
    world_type_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\2 - World Type Table.csv"
    )

    overall_type_roll = rollDice(3)
    # print("Ovr Type Roll: " + str(overall_type_roll))

    world_type_roll = rollDice(3)
    # print("World Type Roll" + str(world_type_roll))

    world_type = error_message
    rowN = 0
    for x in range(3):  # Overall Type Loop
        if overall_type_roll <= overall_type_table.iloc[rowN, 0]:
            overall_type = overall_type_table.iloc[rowN, 1]
            break

        rowN = rowN + 1

    rowN = 0
    if overall_type == overall_type_table.iloc[0, 1]:  # World Type loop for Hostiles
        for x in range(16):
            if world_type_roll <= world_type_table.iloc[rowN, 0]:
                world_type = world_type_table.iloc[rowN, 1]
                break
            rowN = rowN + 1

    elif overall_type == overall_type_table.iloc[1, 1]:  # World Type loop for Barrens
        for x in range(16):
            if world_type_roll <= world_type_table.iloc[rowN, 0]:
                world_type = world_type_table.iloc[rowN, 2]
                break
            rowN = rowN + 1

    elif overall_type == overall_type_table.iloc[2, 1]:  # World Type loop for Gardens
        for x in range(16):
            if world_type_roll <= world_type_table.iloc[rowN, 0]:
                world_type = world_type_table.iloc[rowN, 3]
                break
            rowN = rowN + 1

    overall_type = "Hostile"
    world_type = "Standard (Chthonian)"
    # world_type = "Asteroid Belt"
    # world_type = "Tiny (Ice)"

    # STEP 3: Atmosphere (pg 78)
    # Atmospheric Mass

    atmo_mass_roll = rollDice(3)
    if (
        (world_type == world_type_table.iloc[9, 2])
        or (world_type == world_type_table.iloc[5, 2])
        or (world_type == world_type_table.iloc[3, 2])
        or (world_type == world_type_table.iloc[7, 2])
        or (world_type == world_type_table.iloc[0, 2])
        or (world_type == world_type_table.iloc[13, 2])
        or (world_type == world_type_table.iloc[6, 1])
        or (world_type == world_type_table.iloc[1, 1])
        or (world_type == world_type_table.iloc[15, 1])
    ):
        atmo_mass = 0

    else:
        atmo_mass = (atmo_mass_roll / 10) + (random.choice(range(-5, 5)) / 100)

    # Atmospheric Composition
    atmo_comp_roll = rollDice(3)

    if (
        (world_type == world_type_table.iloc[9, 2])
        or (world_type == world_type_table.iloc[5, 2])
        or (world_type == world_type_table.iloc[3, 2])
        or (world_type == world_type_table.iloc[7, 2])
        or (world_type == world_type_table.iloc[0, 2])
        or (world_type == world_type_table.iloc[13, 2])
        or (world_type == world_type_table.iloc[6, 1])
        or (world_type == world_type_table.iloc[1, 1])
        or (world_type == world_type_table.iloc[15, 1])
    ):
        atmo_comp = "Inexistent"

    elif world_type == world_type_table.iloc[1, 2]:
        if atmo_comp_roll <= 15:
            atmo_comp = "Nitrogen and Methane (Suffocating and Mildly Toxic)"
        else:
            atmo_comp = "Nitrogen and Methane (Suffocating and Highly Toxic)"

    elif world_type == world_type_table.iloc[9, 1]:
        atmo_comp = "Nitrogen, Ammonia and Methane (Suffocating, Lethally Toxic and Corrosive)"

    elif world_type == world_type_table.iloc[12, 2]:
        if atmo_comp_roll <= 12:
            atmo_comp = "Nitrogen and Carbon Dioxide (Suffocating)"
        else:
            atmo_comp = "Nitrogen and Carbon Dioxide (Suffocating and Mildly Toxic)"

    elif world_type == world_type_table.iloc[11, 2]:
        if atmo_comp_roll <= 12:
            atmo_comp = "Nitrogen and Carbon Dioxide (Suffocating)"
        else:
            atmo_comp = "Nitrogen and Carbon Dioxide (Suffocating and Mildly Toxic)"

    elif world_type == world_type_table.iloc[13, 3]:
        atmo_comp = "Nitrogen and Free Oxygen"

    elif (world_type == world_type_table.iloc[3, 1]) or (world_type == world_type_table.iloc[13, 1]):
        atmo_comp = "Inexistent"

    elif world_type == world_type_table.iloc[11, 1]:
        atmo_comp = "Helium Gas, Ammonia and Methane (Suffocating, Lethally Toxic and Corrosive"

    elif (world_type == world_type_table.iloc[15, 2]) or world_type_table.iloc[14, 2]:
        atmo_comp = "Helium and Nitrogen Gases (Suffocating and Highly Toxic"

    elif world_type == world_type_table.iloc[15, 3]:
        atmo_comp = "Nitrogen, Noble Gases and Free Oxygen"

    # Marginal Atmospheres
    marg_atmo_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\4 - Marginal Atmospheres Table.csv"
    )

    marg_atmo_presence_roll = rollDice(3)
    marg_atmo_roll = rollDice(3)

    rowN = 0
    if ("Garden" in world_type) and marg_atmo_presence_roll >= 12:
        for x in range(9):
            if marg_atmo_roll <= marg_atmo_table.iloc[rowN, 0]:
                atmo_comp = atmo_comp + marg_atmo_table.iloc[rowN, 1]
                break
            rowN = rowN + 1

    # STEP 4: Hydrographic Coverage
    hydrocover_math = error_message
    if (
        (world_type == world_type_table.iloc[9, 2])
        or (world_type == world_type_table.iloc[5, 2])
        or (world_type == world_type_table.iloc[3, 2])
        or (world_type == world_type_table.iloc[7, 2])
        or (world_type == world_type_table.iloc[0, 2])
        or (world_type == world_type_table.iloc[13, 2])
        or (world_type == world_type_table.iloc[6, 1])
        or (world_type == world_type_table.iloc[1, 1])
        or (world_type == world_type_table.iloc[15, 1])
    ):
        hydrocover_math = 0
        hydrocover = str(0) + "%"

    elif world_type == world_type_table.iloc[1, 2]:
        hydrocover_math = (rollDice(1) + 2) * 10
        hydrocover = str(hydrocover_math) + "% (Hydrocarbons)"

    elif (world_type == world_type_table.iloc[9, 1]) or (world_type == world_type_table.iloc[11, 1]):
        hydrocover_math = rollDice(2) * 10
        if hydrocover_math > 100:
            hydrocover_math = 100
        hydrocover = str(hydrocover_math) + "% (Ammonia + Water)"

    elif (world_type == world_type_table.iloc[12, 2]) or (world_type == world_type_table.iloc[15, 2]):
        hydrocover_math = (rollDice(2) - 10) * 10
        if hydrocover_math < 0:
            hydrocover_math = 0
        hydrocover = str(hydrocover_math) + "% (Water; Temporary)"

    elif (world_type == world_type_table.iloc[11, 2]) or (world_type == world_type_table.iloc[13, 3]):
        hydrocover_math = (rollDice(2) + 4) * 10
        if hydrocover_math > 100:
            hydrocover_math = 100
        hydrocover = str(hydrocover_math) + "% (Water)"

    elif (world_type == world_type_table.iloc[14, 2]) or (world_type == world_type_table.iloc[15, 3]):
        hydrocover_math = (rollDice(2) + 6) * 10
        if hydrocover_math > 100:
            hydrocover_math = 100
        hydrocover = str(hydrocover_math) + "% (Water)"

    elif (world_type == world_type_table.iloc[3, 1]) or (world_type == world_type_table.iloc[13, 1]):
        hydrocover_math = (rollDice(2) - 7) * 10
        if hydrocover_math < 0:
            hydrocover_math = 0
            hydrocover = str(0) + "%"

        else:
            hydrocover = str(hydrocover_math) + "% (Water; Temporary)"

        if hydrocover_math > 0:
            atmo_comp = "Nitrogen, Water Vapor and Free Oxygen (Suffocating, Lethaly Toxic and Corrosive)"

        else:
            atmo_comp = "Carbon Dioxide (Suffocating, Lethaly Toxic and Corrosive)"

    # STEP 5: Climate (pg 83)
    avg_surf_temp_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\5 - Average Surface Temperature Table.csv"
    )
    world_climate_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\6 - World Climate Table.csv"
    )
    temp_factors_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\7 - Temperature Factors Table.csv"
    )

    # Climate Type
    avg_surf_temp_roll = rollDice(3) - 3

    rowN = 0  # Finding average surface temperature
    for x in range(20):
        if world_type == avg_surf_temp_table.iloc[rowN, 0]:
            avg_surf_temp = (avg_surf_temp_roll * avg_surf_temp_table.iloc[rowN, 3]) + avg_surf_temp_table.iloc[rowN, 1]
            break

        rowN = rowN + 1

    rowN = 0  # Defining world climate
    for x in range(12):
        if avg_surf_temp <= world_climate_table.iloc[rowN, 1]:
            world_climate = world_climate_table.iloc[rowN, 2]
            break

        rowN = rowN + 1

    # Determining Blackbody Temperature
    rowN = 0
    for x in range(20):  # Defining Absorption and Greenhouse factor to calculate blackbody temperature
        if world_type == temp_factors_table.iloc[rowN, 0]:
            absorp_factor = temp_factors_table.iloc[rowN, 1]
            greenhouse_factor = temp_factors_table.iloc[rowN, 2]
            break

        elif (("Ocean" in world_type) or ("Garden" in world_type)) and (hydrocover_math <= 20):
            absorp_factor = temp_factors_table.iloc[12, 1]
            greenhouse_factor = temp_factors_table.iloc[12, 2]
            break

        elif (("Ocean" in world_type) or ("Garden" in world_type)) and (hydrocover_math <= 50):
            absorp_factor = temp_factors_table.iloc[13, 1]
            greenhouse_factor = temp_factors_table.iloc[13, 2]
            break

        elif (("Ocean" in world_type) or ("Garden" in world_type)) and (hydrocover_math <= 90):
            absorp_factor = temp_factors_table.iloc[14, 1]
            greenhouse_factor = temp_factors_table.iloc[14, 2]
            break

        elif (("Ocean" in world_type) or ("Garden" in world_type)) and (hydrocover_math <= float("inf")):
            absorp_factor = temp_factors_table.iloc[15, 1]
            greenhouse_factor = temp_factors_table.iloc[15, 2]
            break

        rowN = rowN + 1

    blackbody_correction = absorp_factor * (1 + (atmo_mass * greenhouse_factor))

    blackbody_temp = avg_surf_temp / blackbody_correction

    # STEP 6: World Size (pg 84)
    world_density_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\8 - World Density Table.csv"
    )

    if "Asteroid Belt" not in world_type:
        if ("Sulfur" in world_type) or ("Ice" in world_type) or ("Hadean" in world_type) or ("Ammonia" in world_type):
            core_type = "Icy Core"

        elif "Rock" in world_type:
            core_type = "Small Iron Core"

        else:
            core_type = "Large Iron Core"

        world_density_roll = rollDice(3)

        rowN = 0
        for x in range(5):
            if world_density_roll <= world_density_table.iloc[rowN, 0]:
                if "Icy" in core_type:
                    world_density_ratio = world_density_table.iloc[rowN, 1] + (random.choice(range(-5, 5)) / 100)
                    break

                elif "Small" in core_type:
                    world_density_ratio = world_density_table.iloc[rowN, 2] + (random.choice(range(-5, 5)) / 100)
                    break

                elif "Large" in core_type:
                    world_density_ratio = world_density_table.iloc[rowN, 3] + (random.choice(range(-5, 5)) / 100)
                    break

            rowN = rowN + 1

        world_density_cm3 = world_density_ratio * 5.52

        # Diameter and Surface Gravity
        size_constraints_table = csv_parser(
            R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\9 - Size Constraints Table.csv"
        )

        diameter_roll = rollDice(2) - 2
        min_constraint = "You shouldn't be getting this output."
        max_constraint = "You shouldn't be getting this output."

        if "Large" in world_type:
            min_constraint = size_constraints_table.iloc[0, 1]
            max_constraint = size_constraints_table.iloc[0, 2]

        elif "Standard" in world_type:
            min_constraint = size_constraints_table.iloc[1, 1]
            max_constraint = size_constraints_table.iloc[1, 2]

        elif "Small" in world_type:
            min_constraint = size_constraints_table.iloc[2, 1]
            max_constraint = size_constraints_table.iloc[2, 2]

        elif "Tiny" in world_type:
            min_constraint = size_constraints_table.iloc[3, 1]
            max_constraint = size_constraints_table.iloc[3, 2]

        min_diameter = ((blackbody_temp / world_density_ratio) ** 1 / 2) * min_constraint
        max_diameter = ((blackbody_temp / world_density_ratio) ** 1 / 2) * max_constraint

        world_diameter_ratio = (diameter_roll * ((max_diameter - min_diameter) / 10)) + min_constraint
        world_diameter_meter = world_diameter_ratio * 6378

        surface_gravity = world_density_ratio * world_diameter_ratio
        gravity_acceleration = surface_gravity * 9.807

        world_mass = world_density_ratio * (world_diameter_ratio ** 3)

    else:
        core_type = "Not Applicable"
        world_density_roll = "Not Applicable"
        world_density_ratio = "Not Applicable"
        world_density_cm3 = "Not Applicable"
        diameter_roll = "Not Applicable"
        min_constraint = "Not Applicable"
        max_constraint = "Not Applicable"
        min_diameter = "Not Applicable"
        max_diameter = "Not Applicable"
        world_diameter_ratio = "Not Applicable"
        world_diameter_meter = "Not Applicable"
        surface_gravity = "Not Applicable"
        gravity_acceleration = "Not Applicable"
        world_mass = "Not Applicable"

    # Determining Atmospheric Pressure
    pressure_factors_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\10 - Pressure Factors Table.csv"
    )
    atmo_pressure_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\3 - Atmospheric Pressure Categories Table.csv"
    )

    if ("Asteroid" in world_type) or ("Tiny" in world_type) or ("Hadean" in world_type):
        atmo_pressure = 0

    elif ("Rock" in world_type) or ("Chthonian" in world_type):
        atmo_pressure = random.choice(arange(0, 0.01, 0.001))

    else:
        rowN = 0
        for x in range(11):
            if world_type in pressure_factors_table.iloc[rowN, 0]:
                pressure_factor = pressure_factors_table.iloc[rowN, 1]
                break
            rowN = rowN + 1

        atmo_pressure = atmo_mass * pressure_factor * surface_gravity

    if atmo_pressure == 0:
        atmo_pressure_category = "(Non-Existent)"

    else:
        rowN = 0
        for x in range(7):
            if atmo_pressure <= atmo_pressure_table.iloc[rowN, 1]:
                atmo_pressure_category = atmo_pressure_table.iloc[rowN, 2]
                break
            rowN = rowN + 1

    # STEP 7: Resources and Habitability
    resources_value_table = csv_parser(
        R"H:\01 Libraries\Documents\Tosh0kan Studios\Coding\GURPS Space\Tables\11 - Resource Value Table.csv"
    )

    resources_value_roll = rollDice(3)

    rowN = 0
    if "Asteroid" in world_type:
        for x in range(11):
            if resources_value_roll <= resources_value_table.iloc[rowN, 0]:
                resources_value_mod = resources_value_table.iloc[rowN, 3]
                resources_value_category = resources_value_table.iloc[rowN, 2]
                break
            rowN = rowN + 1

    else:
        for x in range(11):
            if resources_value_roll <= resources_value_table.iloc[rowN, 1]:
                resources_value_mod = resources_value_table.iloc[rowN, 3]
                resources_value_category = resources_value_table.iloc[rowN, 2]
                break
            rowN = rowN + 1

    habitability_mod = 0
    if atmo_pressure <= 0.009:
        habitability_mod = 0

    elif "Suffocating" in atmo_comp:
        if ("Toxic" in atmo_comp) and ("Corrosive" in atmo_comp):
            habitability_mod = habitability_mod - 2

        elif "Toxic" in atmo_comp:
            habitability_mod = habitability_mod - 1

        else:
            habitability_mod = habitability_mod + 0

    elif ("Frozen" in world_climate) or ("Very" in world_climate) or ("Infernal" in world_climate):
        habitability_mod = habitability_mod + 0

    elif ("Cold" in world_climate) or ("Hot" in world_climate):
        habitability_mod = habitability_mod + 1

    elif (
        ("Chilly" in world_climate)
        or ("Coll" in world_climate)
        or ("Normal" in world_climate)
        or ("Warm" in world_climate)
        or ("Tropical" in world_climate)
    ):
        habitability_mod = habitability_mod + 2

    if (
        ("Very Thin" in atmo_pressure_category)
        or ("Very Dense" in atmo_pressure_category)
        or ("Superdense" in atmo_pressure_category)
    ):
        habitability_mod = habitability_mod + 1

    elif "Thin" in atmo_pressure_category:
        habitability_mod = habitability_mod + 2

    elif ("Standard" in atmo_pressure_category) or ("Dense" in atmo_pressure_category):
        habitability_mod = habitability_mod + 3

    if marg_atmo_presence_roll <= 11:
        habitability_mod = habitability_mod + 1

    if ("Water" in hydrocover) and not ("Ammonia" in hydrocover) and not ("Temporary" in hydrocover):
        if hydrocover_math <= 59:
            habitability_mod = habitability_mod + 1

        elif hydrocover_math <= 90:
            habitability_mod = habitability_mod + 2

        elif hydrocover_math <= 99:
            habitability_mod = habitability_mod + 1

        else:
            habitability_mod = habitability_mod + 0

    affinity_score = habitability_mod + resources_value_mod

    results = f"""==================================================================

    Name: {planet_name}

    Overall Type Roll: {overall_type_roll} World Type Roll:{world_type_roll}
    World  Type: {world_type} ({overall_type}),


    Atmospheric Mass Roll: {atmo_mass_roll}, Atmospheric Comp Roll: {atmo_comp_roll},
    Marginal Atmosphere Roll: {marg_atmo_presence_roll} Marginal Atmo. Table Roll: {marg_atmo_roll}

    Atmospheric Mass: {atmo_mass}, Atmospheric Composition: {atmo_comp},
    Atmospheric Pressure: {atmo_pressure} ({atmo_pressure_category})


    Hydrographic Math: {hydrocover_math} Hydrographic Cover: {hydrocover}


    Avg. Surf. Temp. Roll: {avg_surf_temp_roll}

    Avg Surf Temp: {avg_surf_temp}, World Climate: {world_climate}

    Absorption Factor: {absorp_factor}, Greenhouse Factor: {greenhouse_factor},
    Blackbody Correction: {blackbody_correction}, Blackbody Temperature: {blackbody_temp}


    World Density Roll: {world_density_roll}
    Core Type: {core_type}, World Density: {world_density_ratio} Earth's or {world_density_cm3}g/cm3

    Diameter Roll: {diameter_roll}
    Min. Constraint: {min_constraint}, Max. Constrain: {max_constraint},
    Min. Diameter: {min_diameter}, Max. Diameter: {max_diameter},
    Diameter : {world_diameter_ratio} Earth's or {world_diameter_meter}m,
    Surface Gravity: {surface_gravity}Gs or {gravity_acceleration} m/s2
    World's Mass: {world_mass}


    Resources Value Roll: {resources_value_roll}
    Resources Value Mod: {resources_value_mod}, Resources Value Category: {resources_value_category}

    Habitability Score: {habitability_mod}, Affinity Score: {affinity_score}"""

    new_results = old_results + results
    old_results = new_results
    loop_count = loop_count + 1

results = old_results


with open("GURPS Space/output.txt", "a") as f:
    write_data = f.write(results)

print(fesfsaf)

```

It will take more than two minutes to prompt you the error of `print(fesfsaf)`:  `_"fesfsaf" is not defined_.`

But if you change **while** to the **if** keyword, the Intellisense will work normally:

`while loop_count < 3:` to `if loop_count < 3:`

Or you can annotate the lines from `425` to `498`.

So, it looks like the Pylance can get better in the performance and the arithmetic.

## Logs

I get these errors in the **Log(Extension Host)** channel under the OUTPUT panel.

> [2021-08-18 14:28:58.440] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:28:58.440] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:147263
> 	at async w.provideDocumentHighlights (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:165580)
> [2021-08-18 14:28:58.514] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:28:58.514] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:147263
> 	at async w.provideDocumentHighlights (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:165580)
> [2021-08-18 14:29:04.420] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:29:04.420] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)
> [2021-08-18 14:29:04.880] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:29:04.881] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)
> [2021-08-18 14:31:56.177] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:31:56.177] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)
> [2021-08-18 14:31:56.192] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:31:56.192] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)
> [2021-08-18 14:34:58.883] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:34:58.883] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)
> [2021-08-18 14:34:59.002] [exthost] [error] [ms-python.python] provider FAILED
> [2021-08-18 14:34:59.002] [exthost] [error] Canceled: Canceled
> 	at E.makeCancelError (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183478)
> 	at E.handleFailedRequest (c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:183329)
> 	at c:\Users\Administrator\.vscode\extensions\ms-python.python-2021.5.926500501\out\client\extension.js:9:151190
> 	at async k.provideCodeActions (c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:166936)

**Comment by erictraut** [comment] 2021-08-18 16:53
This is a duplicate of https://github.com/microsoft/pylance-release/issues/1686

**Comment by jakebailey** [comment] 2021-08-18 16:59
Yes, seemingly the same code (but from another user?).

**Closed by jakebailey** 2021-08-18 16:59 UTC
Labels: triage
