### ISSUE TITLE
Refactoring multiline context manager statement into new method results in invalid syntax

### ISSUE THREAD

**Issue by ThisIsAlsoMyPassword** [microsoft/pylance-release#2029] opened 2021-11-03 20:19 UTC
## Environment data

-   Language Server version: 2021.10.3
-   OS and version: MacOS 11.6 / Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): -

## Expected behaviour

Refactoring a multiline context manager statement like this (via lightbulb menu):

```python
with aiohttp.ClientSession() as session:
    with session.get(
        "http://some/quite/long/link", params={"aparam": 1, "anotherparam": 2}
    ) as response:
        assert response.ok
```

should yield this:

```python
def new_func():
    with aiohttp.ClientSession() as session:
        with session.get(
            "http://some/quite/long/link", params={"aparam": 1, "anotherparam": 2}
        ) as response:
            assert response.ok


new_func()
```

## Actual behaviour

...but actually yields invalid python:

```python
def new_func():
    with aiohttp.ClientSession() as session:
        with session.get(
        "http://some/quite/long/link", params={"aparam": 1, "anotherparam": 2}
    )
        as response:
            assert response.ok

new_func()
```

**Comment by judej** [comment] 2021-11-04 17:50
Thanks for the report. Will investigate the issue

**Comment by debonte** [comment] 2024-03-01 22:40
Duplicate of https://github.com/microsoft/pylance-release/issues/2146.

**Closed by debonte** 2024-03-01 22:40 UTC
Labels: bug, P2
