### ISSUE TITLE
Ignore `cls` argument on `@classmethod`s when unused

### ISSUE THREAD

**Issue by pzelnip** [microsoft/pylance-release#933] opened 2021-02-10 21:10 UTC
In Python it is convention with methods decorated with the `@classmethod` decorator to be named `cls`.  As such one might define a method like:

```
class Foo:
    @classmethod
    def bar(cls):
        pass
```

But if `cls` happens to be unused (as is the case in this example), then Pylance will report `cls` as being "not accessed":

![image](https://user-images.githubusercontent.com/414933/107572283-ebcdbb00-6ba0-11eb-803d-0fd50fb26232.png)

It would be nice if in this specific scenario Pylance was aware enough to recognize that `cls` is a convention, and ignore this warning when the method is decorated with `@classmethod`.

One might argue that if `cls` is unused, then they should use the `@staticmethod` decorator instead (since that decorator doesn't require the implicit first argument), but many people have a strong preference to `@classmethod` over `@staticmethod`.

**Comment by jakebailey** [comment] 2021-02-10 21:12
This is a duplicate of #194; please vote there if you want to see this changed.

**Closed by jakebailey** 2021-02-10 21:12 UTC
Labels: duplicate, triage
