### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kingluda** [microsoft/pylance-release#3513] opened 2022-10-21 16:13 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2022.10.30`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.72.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Michael/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bschnurr** [comment] 2022-10-21 16:29
do you have a public code repository? or code example to repro?

**Comment by zzzeek** [comment] 2022-10-25 15:10
I'm also having CPU issues for several days now.  This is using the [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/) repository, Fedora linux.   It starts out fine then after some minutes builds up to 100/200%  of CPU under top and vscode functions like hover, outline, etc. become unresponsive.    Closing vscode will often leave the pylance process still running and it has to be manually killed.

**Comment by bschnurr** [comment] 2022-10-25 16:04
r you using pytest?

**Comment by rchiodo** [comment] 2022-10-25 16:04
@zzzeek can you paste your user settings.json file? I'm trying this now with sqlalchemy and not reproing the issue.

**Comment by zzzeek** [comment] 2022-10-25 18:06
settings is attached   
[settings.json.txt](https://github.com/microsoft/pylance-release/files/9862791/settings.json.txt)

**Comment by zzzeek** [comment] 2022-10-25 18:37
so locally it's not doing it now.   It goes away after a restart and sometimes takes awhile before it appears again.   I will try to turn on the node.js debugging stuff when it does.

**Comment by rchiodo** [comment] 2022-10-25 18:42
Was finally able to repro. Root cause was this commit: 

https://github.com/microsoft/pyright/commit/50e12b4bea4fcdb61d96f855ca1e430bb8b41ca8

We should have a fix soon.

**Comment by rchiodo** [comment] 2022-10-25 18:53
I repro'd after I ran setup.py in sqlalchemy and then started pip installing more stuff into the venv. Eventually it repros on hover.

**Comment by eioe** [comment] 2022-10-26 12:51
I'm suffering from the same issue. A quick fix would be so much appreciated from here. 🙏

**Comment by heejaechang** [comment] 2022-10-27 00:22
This issue has been fixed in prerelease version 2022.10.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221041-26-October-2022-PreRelease)

**Closed by heejaechang** 2022-10-27 00:22 UTC
Labels: bug, fixed in next version
