### ISSUE TITLE
autoimport stopped working when using workspaces

### ISSUE THREAD

**Issue by palankai** [microsoft/pylance-release#4144] opened 2023-03-24 18:52 UTC
## Environment data

-   Language Server version: 2023.3.30
-   OS and version: MacOS 13.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

I tried with different pythons, and 3.9 has the same issue.
I've identified the auto-import stopped working in the **2023.3.24** release but worked in the 2023.3.23.
I experienced the same behaviour with the v2023.3.31 pre-release as well.

## Code Snippet

![pylance-autoimport-bug-detailed](https://user-images.githubusercontent.com/424344/227613477-e182a72d-1b6a-4dc0-b46d-f4546439aa07.gif)

## Repro Steps

- Start in an empty folder
- Make two folders, `client/` and `server/` (the name doesn't seem to be relevant)
- Add a `sever.py` to the `server/` folder to the 
- Auto-import should work as expected when pressing Ctrl+Space
- Add the `server/` folder to the workspace
- Auto-import offers import but doesn't import anything (via Ctrl+Space)
- Removing `server/` from the workspace makes it work again (in a single root workspace)

## Expected behavior

- Regardless of the workspaces, Auto-import should add the import to the file.

## Actual behavior

- The Auto-import doesn't add import the file if the workspace has multiple root folders.

## Logs

[pylance-autoimport-bug.log](https://github.com/microsoft/pylance-release/files/11065531/pylance-autoimport-bug.log)

**Comment by debonte** [comment] 2023-03-24 20:05
@rchiodo, this behavior changed after https://github.com/microsoft/pyrx/pull/3276.

**Comment by rchiodo** [comment] 2023-03-27 17:42
I repro this in the older version too. At least 2023.3.23. It's worse though.

**Comment by rchiodo** [comment] 2023-03-27 17:47
Yeah repros for me in 2023.3.20 as well. 

I don't know that this was ever working?

**Comment by rchiodo** [comment] 2023-03-27 17:47
There's some weird behavior around if we reindex everything or not.

**Comment by rchiodo** [comment] 2023-03-28 00:00
This looks to be potentially caused by changes in how VS code behaves (or maybe because of our dynamic vs static workspace folder configuration).

The root cause of the problem is that the subfolder workspace we generate doesn't have the server.py file marked as open.

**Comment by levrik** [comment] 2023-03-28 07:24
I can also confirm this behavior. This slows me down a lot as I have to manually go through all unimported symbols again and import them via Quick Fix.

**Comment by debonte** [comment] 2023-03-30 01:06
This issue has been fixed in prerelease version 2023.3.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023341-29-March-2023-PreRelease)

**Closed by debonte** 2023-03-30 01:07 UTC
Labels: bug, fixed in next version

**Comment by palankai** [comment] 2023-04-06 08:22
Thank you for the quick resolution!
