### ISSUE TITLE
Pylance: Missing Imports

### ISSUE THREAD

**Issue by ajaykamal3** [microsoft/pylance-release#1453] opened 2021-06-16 07:22 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Miniconda

<h3> Expected behaviour </h3>

Pylance should recognize the import from the package six
```
from six.moves import urllib
```
<h3> Actual behaviour </h3>

Pylance is not recognizing the import and it is giving a message "Import "six.moves" could not be resolved from source"

<h3> Logs </h3>

Python Language Server Log
```
[Info  - 11:11:11 AM] Pylance language server 2021.6.1 (pyright e3f7cccc) starting
[Info  - 11:11:11 AM] Server root directory: /home/ajay/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.1/dist
```

**Comment by savannahostrowski** [comment] 2021-06-16 18:06
Closing as this is a duplicate of #1343

**Closed by savannahostrowski** 2021-06-16 18:06 UTC
Labels: triage
