### ISSUE TITLE
Too many repeated parameters are recommended after I update pylance！

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#215] opened 2020-08-08 01:55 UTC
## Environment data
version: 1.47.3 (user setup)
commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Pylance: 2020.8.0
To find your version, you can either:

## Incredibly repeated parameters
![image](https://user-images.githubusercontent.com/33288114/89699901-fb9fe480-d95c-11ea-9e1b-f73332013fbd.png)

This issue is similiar to [#12503](https://github.com/microsoft/vscode-python/issues/12503)，now pylance has the similiar problem.

**Comment by erictraut** [comment] 2020-08-08 02:14
Thanks for the bug report. I've introduced a fix, and it will be in the next release of Pylance.

In case you're curious of the cause of the bug, Pylance was adding symbols from the current scope and all outer scopes (which is correct), but it wasn't properly detecting and dedup'ing symbol names that appeared in outer scopes.

**Comment by CatNofishing** [comment] 2020-08-08 02:18
Thanks for your reply.😁

**Comment by jakebailey** [comment] 2020-08-13 20:45
This issue has been fixed in version 2020.8.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202081-13-august-2020

**Closed by jakebailey** 2020-08-13 20:45 UTC
Labels: bug, fixed in next version

**Comment by CatNofishing** [comment] 2020-11-23 05:08
![image](https://user-images.githubusercontent.com/33288114/99930667-d65ca800-2d8c-11eb-9521-d29e427b21a6.png)
This issue appears in pylance v2020.11.3-pre.1

**Comment by jakebailey** [comment] 2020-11-30 19:49
@CatNofishing That's a different issue, actually; we probably don't want to be offering autoimports for things that are already named parameters, or at least ranking them differently. Would you mind opening a new issue with that screenshot so we can track it? This is a closed issue that was fixed a different way.
