### ISSUE TITLE
Support dataclasses-json

### ISSUE THREAD

**Issue by reconman** [microsoft/pylance-release#926] opened 2021-02-07 10:04 UTC
Right now, usage of https://pypi.org/project/dataclasses-json/ does not work with pylance.  Take this code:
```python
from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass
class SimpleExample:
    int_field: int

simple_example = SimpleExample(1)
simple_example.to_json()
```

It will produce this error:
```
Cannot access member "to_json" for type "SimpleExample"
  Member "to_json" is unknown
```

**Comment by jakebailey** [comment] 2021-02-08 19:27
Curiously, this library is typed (even has a `py.typed` marker), but the `dataclasses_json` function itself is not. I'm not sure if there's anything in the typing specs that would allow this behavior to be statically understood, though.

Their docs do suggest using an alternative form to appease tooling: https://github.com/lidatong/dataclasses-json#approach-2-inherit-from-a-mixin

**Comment by jakebailey** [comment] 2021-02-08 19:28
If you use `DataClassJsonMixin`, does it work as expected?

**Comment by jakebailey** [comment] 2021-03-12 01:12
It seems like the author intends for the mixin to be used if strict typing is required, and is marked as py.typed but isn't completely typed. We use the type information given to us by the library and follow the typing specs.

If the author's suggestion to use the mixin doesn't work, then we can reopen (as it seems like it'd work), but past that things seem to be working as intended and as the library author described.

**Closed by jakebailey** 2021-03-12 01:12 UTC
Labels: waiting for info
