### ISSUE TITLE
Rename fails in Untitled notebook

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3276] opened 2022-09-03 00:16 UTC
-   Language Server version: 2022.8.51

## Code Snippet

Cell 0:
```python
class Foo:
    pass
```

Cell 1:
```python
Foo()
```

### Scenario 1: Rename in bottom cell
1. Use `Create: New Jupyter Notebook` command to create a notebook
2. Setup cells as shown above
3. Right-click `Foo()` in cell 1 and select `Rename Symbol`

#### Expected behavior
Rename experience starts.

#### Actual behavior
Popup error: "The element can't be renamed"

### Scenario 2: Rename in top cell
4. Right-click `Foo` in cell 0 and select `Rename Symbol`
5. Enter new name in rename text box and press Enter

#### Expected behavior
`Foo` is renamed in both cells.

#### Actual behavior
Name only changes in cell 0.

### Scenario 3: Rename in saved file
6. Undo rename (Ctrl-Z)
7. Save file
8. Try rename again.

#### Result
Now you can rename in either cell and `Foo` in both cells is updated.

### Scenario 4: Opening another Untitled notebook breaks experience again
9. Use `Create: New Jupyter Notebook` command to create a second notebook
10. Switch back to saved notebook.
11. Now rename experience in saved notebook is broken -- same as in Scenario 1 and 2 above.

## Logs
[UntitledNotebookRenameLog2.txt](https://github.com/microsoft/pylance-release/files/9481535/UntitledNotebookRenameLog2.txt)

**Comment by debonte** [comment] 2022-09-03 00:17
On my machine, when rename fails `_getRenameSymbolMode` is returning `"none"`. When it succeeds (saved file), it is returning `"mutliFileMode"`. Should it be `"singleFileMode"` in both cases?

**Comment by rchiodo** [comment] 2022-10-28 20:33
This also fails in an untitled python file:

- Create new file
- Change language to python
- Add this code
```
class Foo():
    pass

Foo()
```

Try to rename on the second `Foo` and it fails.

Root cause is untitled files are marked as untracked.

**Closed** 2022-11-10 02:14 UTC
Labels: fixed in next version

**Comment by rchiodo** [comment] 2022-11-10 02:16
This issue has been fixed in prerelease version 2022.11.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221121-9-November-2022-PreRelease)
