### ISSUE TITLE
Pylance keeps crashing when using the Jupyter notebook extension

### ISSUE THREAD

**Issue by thierry-bm** [microsoft/pylance-release#4698] opened 2023-08-08 11:56 UTC
Whenever I delete a notebook cell, the Pylance server seems to crash. I have no way to restart it without reloading the whole notebook.

Side question : is there any command to reload the pylance engine? I saw github issues mentioning it but they were closed. The only thing I can do is close/reopen the notebook tab or reload the window, but I lose my workflow. 

<h3> Environment data </h3>

-   Language Server version: 2023.8.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.5
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

Here's the stack trace I get in the console : 
```
2023-08-08 07:49:39.052 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\xxxx\my_notebook.ipynb:pylance-notebook-cell:X26sZmlsZQ==.py
    at _0x301f2e (c:\yyy\.vscode\extensions\ms-python.vscode-pylance-2023.8.10\dist\server.bundle.js:1:997269)
    at c:\yyy\.vscode\extensions\ms-python.vscode-pylance-2023.8.10\dist\server.bundle.js:1:1004473
    at _0x69059c.<computed> (c:\yyy\.vscode\extensions\ms-python.vscode-pylance-2023.8.10\dist\server.bundle.js:1:1004505)
    at _0x27861c._onDidChangeNotebookDocumentAsync (c:\yyy\.vscode\extensions\ms-python.vscode-pylance-2023.8.10\dist\server.bundle.js:1:983463)
```

**Comment by rchiodo** [comment] 2023-08-08 16:14
Sorry for the problem. This is a dupe of https://github.com/microsoft/pylance-release/issues/4685

**Closed by rchiodo** 2023-08-08 16:14 UTC
Labels: needs repro
