### ISSUE TITLE
Code mistakenly marked as unreachable after Pandas `concat` of `Any` types

### ISSUE THREAD

**Issue by torext** [microsoft/pylance-release#5631] opened 2024-03-13 10:14 UTC
<h3> Environment data </h3>

-   Language Server version: 2024.3.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.11.6, Miniforge
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

The following code shows the last line wrongly as unreachable in VSCode:
```python
from typing import Any

import pandas as pd


def generate_series() -> Any:
    return pd.Series([1, 2, 3])


df = pd.concat({k: generate_series() for k in range(10)}, axis=1)

print("Unreachable?!")
```
![image](https://github.com/microsoft/pylance-release/assets/10012123/36c04508-c440-45aa-b497-d59318b3266c)

<h3> Repro Steps </h3>

The key step is to make sure that whatever is called within `pd.concat` doesn't have an immediately inferable `DataFrame` or `Series` type; I achieve this here by annotating `generate_series` with the return type `Any`.

The key reason the subsequent code is unreachable seems to be that `pd.concat` is considered in this instance to have a return type `Never` by Pylance:

![image](https://github.com/microsoft/pylance-release/assets/10012123/1335384a-5a62-44b3-93ea-7de31d084466)

However it is not clear to me where this stub comes from. Hitting F12 on `pd.concat` gives me 6 definitions (5 overloads) none if which match the above instance, i.e. this is not an overload provided by Pandas it seems.
<h3> Expected behavior </h3>

With Pylance v2024.2.3 there was no issue. In that case the last line was reachable and the hover for `pd.concat` showed one of the generic stubs I could find with F12:

![image](https://github.com/microsoft/pylance-release/assets/10012123/582f6fe9-fead-4694-883f-93105e1823fc)

**Comment by debonte** [comment] 2024-03-13 14:42
Duplicate of #5630

**Closed by debonte** 2024-03-13 14:42 UTC
Labels: needs repro

**Comment by ydmykr** [comment] 2024-03-14 01:36
Related in StackOverflow: https://stackoverflow.com/questions/78156640/how-do-i-disable-vscode-graying-out/78157665#78157665

**Comment by Dr-Irv** [comment] 2024-03-14 12:14
Please see #5640 .  pylance is doing the unreachable analysis by looking at the stubs even if type checking is off.

**Comment by debonte** [comment] 2024-03-14 16:10
> Why is this closed? Is it fixed? If it is not, which open issue will fix the OP's question?

It's closed because it's a duplicate of an issue filed earlier -- https://github.com/microsoft/pylance-release/issues/5630

**Comment by Dr-Irv** [comment] 2024-03-14 16:30
> It's closed because it's a duplicate of an issue filed earlier -- #5630

I don't think these are duplicates.  In #5630 , the issue was that the line `pd.concat([])` caused lines following it to be unreachable.  This conclusion is absolutely correct.

Here, the issue is that you have untyped code (i.e., the type of an argument could not be inferred), which the type checker says is fine if you use it from the command line, but the reachability analysis combined with the type checker infers that an `Iterable[Any]` argument matches `Iterable[None]`, so it concludes that the code below the `pd.concat()` call is unreachable.

**Comment by debonte** [comment] 2024-03-14 17:17
> Here, the issue is that you have untyped code...the type checker infers that an `Iterable[Any]` argument matches `Iterable[None]`

That's true in both cases. In #5630, the user is passing `[]` to `concat` and the type of `[]` is `list[Unknown]` which is equivalent to `list[Any]`.

**Comment by zorion** [comment] 2024-03-14 17:58
Let's trust you when you say this issue is equivalent. So I'd like to ask why #5630 is closed. I will ask there, Thanks!
