### ISSUE TITLE
The code after webdriver.XX() is grayed out.

### ISSUE THREAD

**Issue by kawagoe6884** [microsoft/pylance-release#3400] opened 2022-09-28 02:43 UTC
<h3> Environment data </h3>

-   Language Server version: 2022.9.40
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.7 64-bit
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element(By.NAME, "q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

<h3> Expected behavior </h3>

Version 2022.9.30
![2022 9 30](https://user-images.githubusercontent.com/97506026/192670796-655567ef-0172-40df-b48c-6080b06f11cd.jpg)

<h3> Actual behavior </h3>

Version 2022.9.40
![2022 9 40](https://user-images.githubusercontent.com/97506026/192670864-913fd0b5-9700-4820-9c93-4484480e1f42.jpg)

I was able to reproduce it in webdriver.Opera(), webdriver.IE(), etc.
The grayed out areas worked fine. But it is very hard to see.

**Comment by erictraut** [comment] 2022-09-28 03:05
Duplicate of https://github.com/microsoft/pylance-release/issues/3196.

**Comment by kawagoe6884** [comment] 2022-09-28 03:28
Thanks for the reply.
I upgraded to selenium 4 and the problem solved, thank you.

**Closed** 2022-09-28 03:28 UTC
Labels: triage-needed
