### ISSUE TITLE
GeneralTypeIssues: "mymod.MyClass" is incompatible with "mymod.MyClass" 🤷‍♀️ 

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#2056] opened 2021-11-09 12:12 UTC
Hello! I have multiple of these "problems" highlighted:
```
Argument of type "Self@A2Window" cannot be assigned to parameter "parent" of type "A2Window" in function "setup_ui"
  "a2ui.A2Window" is incompatible with "a2ui.A2Window"
```
![image](https://user-images.githubusercontent.com/218956/140907000-e5399fb0-cad8-402d-a242-1118a80fa64e.png)

The setup is with `.pyi` files in a `/typings` dir. I'll line out on of these quickly:
- [`a2app.py`](https://github.com/ewerybody/a2/blob/master/ui/a2app.py#L75)
    ```py
    import a2ui
    import a2core
    from singlesiding import QSingleApplication
    # ...

    class A2App(QSingleApplication):
        # ...
        def do_stuff(self):
            self._core = a2core.A2Obj()
            #                        v____v<--HERE----------------
            self._win = a2ui.A2Window(self)
            # Argument of type "Self@A2App" cannot be assigned to parameter "app"
            # of type "A2App" in function "__init__"
            # "a2app.A2App" is incompatible with "a2app.A2App"

            #         v___v<--HERE----------------
            self._core.app = self
            # Cannot assign member "app" for type "A2Obj"
            # Expression of type "Self@A2App" cannot be assigned to member "app" of class "A2Obj"
            # "a2app.A2App" is incompatible with "a2app.A2App"
    ```
- [`a2ui.pyi`](https://github.com/ewerybody/a2/blob/master/ui/typings/a2ui.pyi#L17)
    ```py
    import a2app
    from a2qt import QtWidgets
    # ...

    class A2Window(QtWidgets.QMainWindow):
        app: a2app.A2App
        # ...
        def __init__(self, app: a2app.A2App): ...
    ```
- [`a2core.pyi`](https://github.com/ewerybody/a2/blob/master/ui/typings/a2core.pyi#L19)
    ```py
    import a2app
    # ...
    class A2Obj:
        app: a2app.A2App = ...
        # ...
    ```

This is Qt for Python 5.12 stuff.

## Environment data
<details summary="bla">
• Language Server version: v2021.11.1-pre.1<br>
• Python version: 3.9.7<br>
• Version: 1.63.0-insider (user setup)<br>
• Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8<br>
• Date: 2021-11-08T05:14:49.440Z<br>
• Electron: 13.5.1<br>
• Chrome: 91.0.4472.164<br>
• Node.js: 14.16.0<br>
• V8: 9.1.269.39-electron.0<br>
• OS: Windows_NT x64 10.0.19043<br>
</details>

This "seems" like a bug. Even if its my fault (of course) this information is not helping ☹

**Comment by erictraut** [comment] 2021-11-09 16:58
There's not quite enough information here for me to reproduce the problem because the sample isn't complete.

One thing that jumps out at me is the cyclical dependency between the three modules in your example. The fact that you're importing a non-stub file from a stub is a red flag; normally that's not something you would do. 

Pylance supports detection of module cylces, but it's disabled by default. If you want to enable it, the configuration option is called `reportImportCycles`.

I don't know if that's the real cause of the problem in this case because I'm not able to repro the actual error. If you're able to provide a complete example or point me to the repo where this code is checked in, I can investigate further.

**Comment by ewerybody** [comment] 2021-11-09 21:07
The file names are links to my repository. But i'll also try to cook it down further...

**Comment by ewerybody** [comment] 2021-11-10 20:32
Hello @erictraut ! I created a mini repo: https://github.com/ewerybody/_typing_test

Same issue in https://github.com/ewerybody/_typing_test/blob/main/app.py#L6
```
Argument of type "Self@MyApp" cannot be assigned to parameter "backend" of type "MyApp" in function "__init__"
  "app.MyApp" is incompatible with "app.MyApp"
```
Hope that helps 🙇‍♀️

**Comment by erictraut** [comment] 2021-11-11 05:10
Thanks for the repro.

The problem here is that you're using type stubs in an inappropriate manner. A type stub is meant to describe the interface of a module, typically part of an external library that your program imports. Think of it as a stand-in for a source file when that source file isn't available (e.g. it is written in another language).

You have created type stubs that have the same names as modules within your own source base. When `app.py` imports from `ui`, the type checker resolves the import using `ui.pyi` (consistent with the rules documented in PEP 484 and PEP 561). The file `ui.pyi` imports the module `app`, and this is being resolved using `app.pyi`. Both `app.py` and `app.pyi` declare a class called `MyApp`, but these are different classes from the perspective of the type checker. That's why you're receiving this (somewhat confusing) error message.

The typings folder is normally where you place type stubs for external libraries that your code consumes. If your intent is to use static type checking on your own code, you should delete the type stubs and add the type annotations directly to your code (your ".py" files). There's no need for type stubs in this case, and the use of type stubs will cause lots of problems like the one you're seeing here.

When you add types to your source files directly, you're may run into another issue. You have a rather gnarly cyclical dependency between `app.py` and `ui.py`. Each is using a class declared in the other. As a general rule of good software development, that's something I always try to avoid. If these classes are so tightly related that they depend on each other, then the should probably be in the same module. There are other ways to refactor code to eliminate cyclical dependencies, but this is the most straightforward.

**Comment by ewerybody** [comment] 2021-11-11 08:47
Yeah the idea was to try to keep the typing stuff out of the source files as it serves no runtime benefits.
Being able to offload all this to a stub file seemed SO enticing to me!!

And yes, I had the illusion that the stub files don't suffer from this cyclical imports problem and it DOES work for a lot of things! :(

Well, this code is years old, one of my hobby projects. I just started learning Python when writing this. And well, I try to keep learning. Unfortunately I dislike huge files and rather separate things into dedicated modules...
So the right thing to do here is probably "just" to resolve the downstream dependencies.

**Comment by ewerybody** [comment] 2021-11-11 09:17
After all: I DO want to write good code.

On the one hand we're still in **Python**, a scripting language! Anything goes! Pylance won't even flinch overriding a built-in type. (That's where other linters as pylint come in handy.) 

On the other: I DO want some help. Having no code completion is a no-go. Also obvious errors like misspelled members must be highlighted! So turning "basic" type checking OFF is out of the question.
Its just that it feels like there is not much middle ground. Investing in this ... Stepping into this feels like your code either needs to be good for rocket-surgery or you don't get help.

So. Thanks again for explaining. 🙏
I'm having a hard time not feeling put down again. But that's just me. Nothing personal. We're here because **there are** specifications to keep out opinions. :)

... this. Pardon me, probably needs to go to some blog post.

**Closed** 2021-12-01 19:26 UTC
Labels: waiting for user response
