### ISSUE TITLE
Regression of issue #471

### ISSUE THREAD

**Issue by onet-git** [microsoft/pylance-release#1132] opened 2021-04-06 20:08 UTC
**Environment data**
Language Server version: 2021.3.4
OS and version: Ubuntu Bionic
Python version (& distribution if applicable, e.g. Anaconda): 3.6

The exact same thing as failed in https://github.com/microsoft/pylance-release/issues/471 is failing again. Same test setup fails in the same was as before. The console log shows that it doesn't even look at the "python.analysis.extraPaths" once it finds a file within a matching module directory.

I suspect this is due to recent performance improvements, as that was the reason for the original issue.

**Comment by erictraut** [comment] 2021-04-06 20:53
Thanks for reporting this (again). It turns out that the original fix was incomplete and happened to work because of the order in which we were enumerating directories. That changed recently when we added symlink support, so it exposed this bug.

I've fixed the original bug and added more robust unit tests to cover this case so we don't introduce another regression in the future.

**Comment by jakebailey** [comment] 2021-04-07 23:31
This issue has been fixed in version 2021.4.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202140-7-april-2021

**Closed by jakebailey** 2021-04-07 23:31 UTC
Labels: bug, fixed in next version
