### ISSUE TITLE
Semantic highlight is wrong for some matplotlib classes

### ISSUE THREAD

**Issue by alex180500** [microsoft/pylance-release#6105] opened 2024-07-08 13:53 UTC
Given the following code
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

print(ax.transData.transform((0, 0)))
print(fig.transFigure.transform((0, 0)))
```
![image](https://github.com/microsoft/pylance-release/assets/30732244/40a0ffc3-1cb1-4f19-9af5-d629af5ee9e0)

Why are the two print statement of different colors?

**Pylance:** v2024.6.1
**VS Code:** 1.91.0

**Comment by debonte** [comment] 2024-07-08 17:25
I'm unable to reproduce this and the semantic token type, modifiers, and textmate scopes on these two calls appear to be the same.

Some questions for you:
1. Have you tried disabling your other extensions temporarily? Perhaps one of them is also providing semantic tokenization?
2. Which theme are you using? It's possible that we could repro it using the same theme, but given what I said about the token type, etc above, that seems unlikely to me.
3. What version of matplotlib are you using? I'm using 3.9.1.

**Comment by rchiodo** [comment] 2024-07-08 17:36
I can reproduce it with matplotlib 3.8. The type of `ax` is `Any` so the overload for print is different. With 3.9.1, the type of `ax` is `Axes` and both prints are the same.

**Comment by debonte** [comment] 2024-07-08 18:00
I see. It's because `ndarray` (the return type of `fig.transFigure.transform` declares a `__str__` method. So we're trying to tell the user that there's custom `print` behavior in play here.

Here's a repro without matplotlib:

```python
from typing import Any

class Foo:
    def __str__(self):
        return "foo"

def returns_any() -> Any: ...

foo = Foo()
print(foo) # Has `overridden` semantic token modifier
foo = returns_any()
print(foo) # Does not have `overridden` modifier
```

**Comment by rchiodo** [comment] 2024-07-09 16:58
This issue should be by design then. The different colors are because the two prints are semantically different. Well based on the types returned by matplotlib. They would be the same once updating to a newer matplotlib.

**Comment by bschnurr** [comment] 2024-07-09 16:58
closing as designed.

**Closed** 2024-07-09 16:58 UTC
Labels: needs repro
