### ISSUE TITLE
Pylance is not work for jupyter notebook in VScode

### ISSUE THREAD

**Issue by mikeyau1** [microsoft/pylance-release#4742] opened 2023-08-13 17:45 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Pylance is not stable. When I open the notebook, it works for 1-2 hours. Then, the color of variables become white, and Pylance is unable to scan error. I check some issue in GitHub (https://github.com/microsoft/vscode-jupyter/issues/8374#issuecomment-985925070). I try to add a new cell. but it gives nothing to jx:
![image](https://github.com/microsoft/vscode-jupyter/assets/45174150/43f21342-860a-4a9f-87ee-ed7c134c13ae)

Also, it detect a comment line as error. it also cannot show the object selector
![image](https://github.com/microsoft/vscode-jupyter/assets/45174150/6a69bdbc-af50-4583-896e-dfe5aaad1519)

### VS Code Version

Version: 1.81.1 (user setup) Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794 Date: 2023-08-09T22:22:42.175Z Electron: 22.3.18 ElectronBuildId: 22689846 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.7.1002162226

### Coding Language and Runtime Version

Python 3.11.0

### Language Extension Version (if applicable)

Pylance: v2023.8.20

### Anaconda Version (if applicable)

2023.07

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by debonte** [comment] 2023-08-21 21:06
Possibly related to https://github.com/microsoft/pylance-release/issues/4733 and https://github.com/microsoft/pylance-release/issues/4685

**Comment by videogameplayer909** [comment] 2023-08-22 05:02
Just chipping in, same issue here. Python 3.9 in vscode, no conda or other env. Pylance works flawlessly in native .py files, but has zero presence in ipynb files. All ran locally.

**Comment by renanklehm** [comment] 2023-08-22 10:54
Same issue, Pylance does work in Jupyter VSCode, but sometimes it just stops working and everything breaks, as a side note, I'm also using GitHub Copilot, and it seems that when Pylance stops working so does Copilot, it starts spiting no-sense code that does not relate to my work.

I've tried disabling Copilot to see if it is some sort of incompatibility, but Pylance still breaks if I scroll too fast or change something abruptly in the notebook.

**Comment by debonte** [comment] 2023-08-22 17:48
If this is the same as #4733, I believe you could work around this by rolling back to 2023.5.40 or earlier.

Note that despite the word "crash" in the issue title, the underlying issue [can cause all semantic highlighting, hovering, etc to break](https://github.com/microsoft/pylance-release/issues/4733#issuecomment-1684666246) and you won't hit a Pylance crash until you attempt to add/remove/reorder cells.

**Comment by JustinSmith66** [comment] 2023-08-22 19:23
I am having the exact same issue (as described in https://github.com/microsoft/vscode/issues/190981#event-10161999101)

But i know many other people have been having similar issues for what seems a while (see https://stackoverflow.com/questions/59775038/visual-studio-code-syntax-highlighting-not-working#:~:text=In%20my%20case%20I%20needed,as%20source%20for%20the%20problem.) im really not sure about the fix. I have also done everything to try fix this issue from reinstalling to formatting my pc (i did that for other reasons too). 


i used to find when my Python notebook got really large with lots of figures then the color syntax highlighting broke. Now it seems it just breaks after having the notebook open for a few minutes or it just breaks randomly.

**Comment by jzazo** [comment] 2023-08-23 10:06
Just wanted to mention the issue is not only with jupyter notebooks or interactive python, but happens in every python module.

**Comment by mikeyau1** [comment] 2023-08-23 17:25
I would like to thanks all of you. 
Today, I tried to open the file locally, not open in folder or workplace. After some hours, Pylance still works fine. 
I will keep this issue open for discussion and keep monitor the issue of Pylance. It seems a lot of people who facing similar problem.

**Comment by debonte** [comment] 2023-08-23 19:49
@mikeyau1, and others that chimed in here, it's possible that this behavior was caused by #4733 which is fixed in our latest prerelease build, [2023.8.41](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023841-23-August-2023-PreRelease)

Could you please all upgrade to 2023.8.41 and see if your issues are resolved?

**Comment by FlorinAndrei** [comment] 2023-08-24 00:41
2023.5.40 appears to work well, I've used it for maybe 2 - 3 hours today without any problem.

2023.8.41 pre-release worked fine for about 30 min on a large notebook, but after that again I lost syntax highlighting and tab completion, just like before.

**Comment by jzazo** [comment] 2023-08-24 13:35
I agree, `2023.5.40` appeared to be working fine on this matter and `2023.8.41` stopped working at some point.

**Comment by debonte** [comment] 2023-08-26 16:13
@mikeyau1, when you see this issue, if you add/delete/reorder a cell, do you see Pylance crash with an error similar to this?

```text
2023-08-26 09:07:01.700 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths c:\temp\temp\4685repro_3\test.ipynb:pylance-notebook-cell:W3sZmlsZQ==.py
    at _0x35bbe7 (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1025282)
    at c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032550
    at _0x114e49.<computed> (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1032582)
    at _0x4600bc._onDidChangeNotebookDocumentAsync (c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2023.8.41\dist\server.bundle.js:1:1010710)
```

**Comment by mikeyau1** [comment] 2023-08-26 16:45
I hit the same error again by opening a folder like [#4733](https://github.com/microsoft/pylance-release/issues/4733).

How can I see the log which related to the pylance because I see some error in OUTPUT of Extension Host page? But I am not sure it is Pylance related. My environment setting and VS Code version is the same as beginning. I did not update to 2023.8.41.

![image](https://github.com/microsoft/pylance-release/assets/45174150/5a50c610-c833-48b4-a7d2-31d2e77dab44)

**Comment by debonte** [comment] 2023-08-26 16:51
Change the combo box at the top right of the Output pane from "Extension Host" to "Python Language Server"

![image](https://github.com/microsoft/pylance-release/assets/12820898/eaf0a881-ee58-4b7f-94f5-98a4b1585d86)

**Comment by mikeyau1** [comment] 2023-08-26 16:56
I got the similar message

```
2023-08-27 00:51:38.463 [info] [Info  - 12:51:38 AM] (15936) Pylance language server 2023.8.40 (pyright 03f79a81) starting
2023-08-27 00:51:38.464 [info] [Info  - 12:51:38 AM] (15936) Server root directory: c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.8.40\dist
2023-08-27 00:51:38.471 [info] [Info  - 12:51:38 AM] (15936) Starting service instance "FinancialDataAnalyst"
2023-08-27 00:51:38.528 [info] [Info  - 12:51:38 AM] (15936) Setting pythonPath for service "FinancialDataAnalyst": "C:\Python311\python.exe"
2023-08-27 00:51:38.528 [info] [Warn  - 12:51:38 AM] (15936) stubPath e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst\typings is not a valid directory.
2023-08-27 00:51:38.595 [info] [Info  - 12:51:38 AM] (15936) Assuming Python version 3.11
2023-08-27 00:51:38.750 [info] [Info  - 12:51:38 AM] (15936) Found 1 source file
2023-08-27 00:51:38.838 [info] [Info  - 12:51:38 AM] (15936) Starting service instance "FinancialDataAnalyst"
2023-08-27 00:51:38.853 [info] [Info  - 12:51:38 AM] (15936) Setting pythonPath for service "FinancialDataAnalyst": "c:\Python311\python.exe"
2023-08-27 00:51:38.853 [info] [Warn  - 12:51:38 AM] (15936) stubPath e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst\typings is not a valid directory.
2023-08-27 00:51:38.930 [info] [Info  - 12:51:38 AM] (15936) Assuming Python version 3.11
2023-08-27 00:51:39.075 [info] [Info  - 12:51:39 AM] (15936) Found 1 source file
2023-08-27 00:51:43.779 [info] [Info  - 12:51:43 AM] (15936) [IDX(3)] Long operation: index execution environment e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst (2817ms)
2023-08-27 00:51:43.780 [info] [Info  - 12:51:43 AM] (15936) [IDX(3)] Long operation: index packages e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst (2841ms)
2023-08-27 00:52:19.585 [info] [Info  - 12:52:19 AM] (15936) Starting service instance "FinancialDataAnalyst"
2023-08-27 00:52:19.606 [info] [Info  - 12:52:19 AM] (15936) Setting pythonPath for service "FinancialDataAnalyst": "c:\Python311\python.exe"
2023-08-27 00:52:19.607 [info] [Warn  - 12:52:19 AM] (15936) stubPath e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst\typings is not a valid directory.
2023-08-27 00:52:19.696 [info] [Info  - 12:52:19 AM] (15936) Assuming Python version 3.11
2023-08-27 00:52:19.841 [info] [Info  - 12:52:19 AM] (15936) Found 1 source file
2023-08-27 00:53:45.898 [info] [Info  - 12:53:45 AM] (15936) [IDX(5)] Long operation: index execution environment e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst (2785ms)
2023-08-27 00:53:45.899 [info] [Info  - 12:53:45 AM] (15936) [IDX(5)] Long operation: index packages e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst (2804ms)
2023-08-27 00:53:52.071 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths e:\Desktop\Program\Python\FinancialDataAnalyst\FinancialDataAnalyst\FinancialDataAnalyst.ipynb:pylance-notebook-cell:X24sZmlsZQ==.py
    at _0x4ba240 (c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.8.40\dist\server.bundle.js:1:900729)
    at c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.8.40\dist\server.bundle.js:1:907846
    at _0x2599f4.<computed> (c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.8.40\dist\server.bundle.js:1:907878)
    at _0x872478._onDidChangeNotebookDocumentAsync (c:\Users\user\.vscode\extensions\ms-python.vscode-pylance-2023.8.40\dist\server.bundle.js:1:886358)


```

**Comment by amirhosss** [comment] 2023-08-26 18:06
@debonte Yes, I get the exact same error on my linux desktop.

**Comment by debonte** [comment] 2023-08-27 04:36
Ok, then this is a duplicate of #4685. Note that there are two stages to this bug. First you lose language server functionality (ex. hover, semantic highlighting) as you described above and then if you change the structure of an affected notebook Pylance will crash with the `Chained file path...doesn't match cellFilePaths` error.

So far I've found two ways that this problem can happen. One is described in #4733 and was fixed in 2023.8.41. The other is described in https://github.com/microsoft/pylance-release/issues/4685#issuecomment-1694060355, and I expect to be fixed in our next prerelease build.

**Closed by debonte** 2023-08-27 04:36 UTC
Labels: bug, needs repro

**Comment by sayedabdallah** [comment] 2024-07-21 21:32
I am still facing the same issue on 2024-July. I have vscode updated to latest version and I am using Ubuntu

**Comment by rchiodo** [comment] 2024-07-22 16:22
@sayedabdallah, can you open a new issue? Your problem is likely not related to this and we'd need logs and/or repro steps to fix your issue.

**Comment by sattary** [comment] 2024-07-26 22:52
what r u guys doing on Pylance? this problem is going from last year and u did not fix it. are u joking with us?

**Comment by the-rich-piana** [comment] 2024-08-05 17:49
Still happening to me as well. But the fix from @yehaixuan4428  appears to work

**Comment by heejaechang** [comment] 2024-08-05 17:57
there was some notebook bug in a package we depend on. we updated that dependency on the latest pylance (104) and python extension prerelease. can you try the latest pylance/python prerelease to see whether the issue still happening. 

and if it still happens, it could be better for us to track the issue if you open new issue for your issue.

**Comment by the-rich-piana** [comment] 2024-08-05 18:05
I switched to pre-release and restarted VSCode, still appears to be happening even after I select my Poetry .venv ):

Happy to provide more info. @heejaechang Thanks.

**Comment by heejaechang** [comment] 2024-08-05 19:23
@the-rich-piana can you open a new issue with log? so we can track it separately and see what's going on?

**Comment by the-rich-piana** [comment] 2024-08-08 16:32
@heejaechang https://github.com/microsoft/pylance-release/issues/6247

**Comment by byronthecoder** [comment] 2024-10-05 10:44
My problem is in the Jupyter Notebook; when you hover the mouse over a function name or a variable, it doesn't show the docstring nor allow you to cross-reference to the line where it is defined. Just something needs to show up.

I am using the latest Mac version of VS Code. I tested it with a remote connection and a local environment - both must be fixed. But the Windows version works fine.

Does anyone share the same problem?

**Comment by rchiodo** [comment] 2024-10-07 16:04
@byronthecoder I recommend opening a new issue. We'd need logging information and what your version of the extension and VS code is that you're using.

**Comment by rchiodo** [comment] 2025-01-24 18:11
@DePasqualeOrg I recommend you open a new issue. It's unlikely it's related to this item.
