### ISSUE TITLE
2024.4.1 Breaks my stubs python path

### ISSUE THREAD

**Issue by CEXT-Dan** [microsoft/pylance-release#5720] opened 2024-04-03 06:42 UTC
2024.3.2 this works
2024.4.1 wont read my stubs

  "python.analysis.extraPaths": ["M:/Dev/Projects/PyRxGit/PyRxStubs"],
    "terminal.integrated.env.windows": {
        "PYTHONPATH": "M:/Dev/Projects/PyRxGit/PyRxStubs;${env:PYTHONPATH}"
    }

**Comment by debonte** [comment] 2024-04-03 06:58
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by CEXT-Dan** [comment] 2024-04-03 07:10
Sorry too lazy : )

**Comment by CEXT-Dan** [comment] 2024-04-03 13:41
Hi, I read the docs you posted, there's no logs or I don't see any.
just that my stubs can't be resolved, but they are in 2024.3.2

**Comment by CEXT-Dan** [comment] 2024-04-03 13:44
![v2024 3 2](https://github.com/microsoft/pylance-release/assets/26830697/1a0ed125-651a-4dd7-b96b-be80391a10f9)
![2024 4 1](https://github.com/microsoft/pylance-release/assets/26830697/130b8cb0-ebf9-462a-b539-87effe8cdafe)

**Comment by debonte** [comment] 2024-04-06 00:58
I'm unable to reproduce this. Here's what I did:

0. Installed Pylance 2024.4.1
1. git clone https://github.com/CEXT-Dan/PyRx.git
2. Created `.vscode\settings.json` with the settings you provided above. Changed the `extraPaths` to match my clone location.
3. Opened `PySamples\testAnno.py`

I'm not seeing diagnostics on the `pyrx_imp` imports. Go to def on them takes me to `PyRxStubs\pyrx_imp.py`.

What is the warning that you are seeing?

**Comment by CEXT-Dan** [comment] 2024-04-06 01:18
Thanks for testing

I change versions to 2024.4.1
open the file and this is what I see 
![pylance](https://github.com/microsoft/pylance-release/assets/26830697/87a7aa61-2d7e-4139-ad02-33c0825edf34)

it goes away as soon as I revert back to v2024.3.2

**Comment by debonte** [comment] 2024-04-09 16:44
> Hi, I read the docs you posted, there's no logs or I don't see any.

So when you go to the Output pane and expand the combo box for selecting amongst the various logs, you don't see "Python Language Server"?

![image](https://github.com/microsoft/pylance-release/assets/12820898/37a52cb9-8faf-43e7-9a8d-aaf7878b17f0)

> I change versions to 2024.4.1
open the file and this is what I see

Are you able to reproduce this with the steps I listed [above](https://github.com/microsoft/pylance-release/issues/5720#issuecomment-2040836109) using a new/clean copy of the PyRx repo? If not, that would indicate that there's some configuration in your current copy of the PyRx repo that is causing this behavior.

Btw, are you aware that VS Code supports both user config settings (for all workspaces that you open) and workspace-specific settings (for a single workspace)? When you provided your settings [above](https://github.com/microsoft/pylance-release/issues/5720#issuecomment-2034658631), was that your user settings, workspace settings, or both?

You can access the two sets of settings via the command palette using these two commands:
![image](https://github.com/microsoft/pylance-release/assets/12820898/5ff702cc-1c0d-4210-a855-6622cdd233f9)

**Comment by CEXT-Dan** [comment] 2024-04-09 23:01
Hi, 
Thank you for your time

I found how to do the logs, which I have attached. 
Apparently, I don’t have workspace settings, so I’m using windows settings.

I have not don’t a clean repo. 
> there's some configuration in your current copy of the PyRx repo that is causing this behavior

I was thinking about this because there’s .vs folders littered about because I am mostly doing work in visual studio 2022
But I have deleted that once, If I were to do the clean repo and it works, then we’ve lost what caused the bug in vscode, right?

[logs.txt](https://github.com/microsoft/pylance-release/files/14924613/logs.txt)

**Comment by debonte** [comment] 2024-04-09 23:05
> If I were to do the clean repo and it works, then we’ve lost what caused the bug in vscode, right?

Could you create a second clone of your repro and leave the existing one unchanged?

**Comment by CEXT-Dan** [comment] 2024-04-09 23:15
guess that wasn't the problem.
I've also attached new logs for this repo
![clean repo](https://github.com/microsoft/pylance-release/assets/26830697/ea7f945d-c069-46a4-ad75-acfe2a40975c)
[logs2.txt](https://github.com/microsoft/pylance-release/files/14924674/logs2.txt)

**Comment by debonte** [comment] 2024-04-09 23:17
> I found how to do the logs, which I have attached.

Thanks for the log. I'm not sure what the issue is yet, but I did see something interesting.

The lines where I'd expect to see your `extraPaths` logged are blank as is the workspace path that should appear before the list of search paths (following the text "Search paths for ").

Compare your log output:

```text
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172) Search paths for 
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   c:\Users\Dan\.vscode\extensions\ms-python.vscode-pylance-2024.4.100\dist\typeshed-fallback\stdlib
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   c:\Users\Dan\.vscode\extensions\ms-python.vscode-pylance-2024.4.100\dist\typeshed-fallback\stubs\...
2024-04-10 06:48:52.257 [info] [Info  - 6:48:52 AM] (3172)   c:\Users\Dan\.vscode\extensions\ms-python.vscode-pylance-2024.4.100\dist\bundled\stubs
```

versus mine:

```text
2024-04-09 16:08:40.212 [info] [Info  - 4:08:40 PM] (5552) Search paths for file:///c%3A/issues/pylance/5720/PyRx
2024-04-09 16:08:40.213 [info] [Info  - 4:08:40 PM] (5552)   c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.2\dist\typeshed-fallback\stdlib
2024-04-09 16:08:40.213 [info] [Info  - 4:08:40 PM] (5552)   c:\issues\pylance\5720\PyRx
2024-04-09 16:08:40.213 [info] [Info  - 4:08:40 PM] (5552)   c:\issues\pylance\5720\PyRx\PyRxStubs
2024-04-09 16:08:40.213 [info] [Info  - 4:08:40 PM] (5552)   c:\issues\pylance\5720\PyRx\typings
2024-04-09 16:08:40.214 [info] [Info  - 4:08:40 PM] (5552)   c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.2\dist\typeshed-fallback\stubs\...
2024-04-09 16:08:40.214 [info] [Info  - 4:08:40 PM] (5552)   c:\Users\erikd\.vscode-insiders\extensions\ms-python.vscode-pylance-2024.3.2\dist\bundled\stubs
```

This appears to be the same issue as https://github.com/microsoft/pylance-release/issues/5740 and what was mentioned in [this comment](https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674).

**Comment by debonte** [comment] 2024-04-09 23:19
I'm guessing that this is a URI issue of some sort. Is there anything unusual about `M:\Dev\Projects` from a file system perspective? Is it a symlink? Or a mounted network drive? Or anything of that sort?

**Comment by CEXT-Dan** [comment] 2024-04-09 23:22
Nothing special, a local SSD drive

**Comment by debonte** [comment] 2024-04-10 05:45
Thanks. Resolving this as a dupe of https://github.com/microsoft/pylance-release/issues/5740. @heejaechang is actively working on a fix for it.

**Closed by debonte** 2024-04-10 05:45 UTC
Labels: user responded, needs repro
