### ISSUE TITLE
Statements failed in pylance but passed in mypy again

### ISSUE THREAD

**Issue by TheNightmareX** [microsoft/pylance-release#871] opened 2021-01-23 04:05 UTC
## Environment data

-   Language Server version: 2021.1.1
-   OS and version: Windows 10 Work Station 1909
-   Python version: Python 3.9.0 64-bit

## Actual behaviour

```Python
from typing import TypedDict


class MyDict(TypedDict):
    k: int


# ok
mydict: MyDict = {'k': 1}


class BaseClass:
    # ok
    mydict: MyDict = {'k': 1}


class SubClass(BaseClass):
    # failed!!!!!
    mydict = {'k': 1}
    """
    "mydict" overrides symbol of same name in class "BaseClass"
      "dict[str, int]" is incompatible with "MyDict"PylancereportIncompatibleVariableOverride
    test.py(13, 5): Overridden symbol
    """
```

**Comment by erictraut** [comment] 2021-01-23 04:10
This is a duplicate of https://github.com/microsoft/pylance-release/issues/861. A fix is already in place and will be included in next week's pylance release.

**Comment by TheNightmareX** [comment] 2021-01-23 04:12
I've updated pylance and the previous bug in #861 is already fixed, this is a new one

**Comment by erictraut** [comment] 2021-01-23 04:20
We haven't published a new version of pylance since that bug was fixed. We typically publish on Wed of each week. We close the associated bug reports just after we publish, so watch for that notification.

**Comment by jakebailey** [comment] 2021-01-27 20:27
Closing as a duplicate of #861.

**Closed by jakebailey** 2021-01-27 20:27 UTC
Labels: duplicate, fixed in next version
