### ISSUE TITLE
"Code is unreachable Pylance" when it isn't

### ISSUE THREAD

**Issue by codeIs4Me** [microsoft/pylance-release#2981] opened 2022-06-29 14:59 UTC
## Environment data
Pylance v2022.6.30

-   Language Server version: python-3.10.5-amd64
-   OS and version: 19043.1766, version 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): v2022.8.0

## Code Snippet

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait

opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach", True)
driver_location = "./chromedriver"
driver = webdriver.Chrome(executable_path=driver_location,options=opts)
wait = WebDriverWait(driver, 20)
driver.get("https://github.com/")

driver.quit()

```python
XXX
```

## Repro Steps

If you take out the line "driver = webdriver.Chrome(executable_path=driver_location,options=opts)", then the "wait = WebDriverWait(driver, 20)" will be highlighted correctly and obviously the line after that say issue with driver not being defined.

## Expected behavior

Should not grayed out my code thinking it is unreachable.

## Actual behavior

My code runs and is fine.  But VSCode is wrong in saying that all lines after the  "driver = webdriver.Chrome(executable_path=driver_location,options=opts)" are unreachable.

## Logs

```
XXX
```
![Screenshot 2022-06-29Pylance](https://user-images.githubusercontent.com/108414186/176467691-b99fb29c-0231-493e-b006-b14e98dfd36e.png)

**Comment by erictraut** [comment] 2022-06-29 16:21
This is a duplicate of https://github.com/microsoft/pylance-release/issues/2869. It's a bug in older versions of the selenium library. If you upgrade to a recent version (4.2.0), the problem should go away.

**Comment by bschnurr** [comment] 2022-06-29 16:23
yes. couldn't repro on newer version

**Comment by erictraut** [comment] 2022-06-29 17:37
Or you could do `pip install selenium --upgrade`.

**Comment by codeIs4Me** [comment] 2022-06-29 17:40
Thank you for your help.

**Closed** 2022-06-29 18:09 UTC
Labels: triage

**Comment by junyg418** [comment] 2023-02-04 07:06
my selenium version is 4.7.2 but this problom happen
![image](https://user-images.githubusercontent.com/91041950/216753978-cdbded06-79f0-4c3f-8ddf-0a91ea1ff08a.png)
![image](https://user-images.githubusercontent.com/91041950/216754029-be832d18-ccba-433f-9053-c79edadda1cf.png)
i think this is same stuation...

**Comment by Nandinimishra17** [comment] 2024-03-27 16:29
I updated selenium in vs code, still its showing the same problem. Help

**Comment by rchiodo** [comment] 2024-03-27 16:53
Generally this problem happens when the type information for one of the methods you're calling indicates it will return `Never`. The intent here is to catch an exception statically. Meaning if you call that code with the arguments provided, it will throw an exception.

This particular issue was with the type stubs for selenium. The older version indicated a return of `Never` incorrectly, but the newer version fixed that problem.

@Nandinimishra17, it would be better if you opened a new issue. We'd need to have a self contained repro and a list of the packages you have installed.

This works for me with selenium version 4.19.0

![image](https://github.com/microsoft/pylance-release/assets/19672699/b0d58223-83ac-43f2-82b8-124d9b385833)

**Comment by Nandinimishra17** [comment] 2024-03-27 17:39
omg great it worked! i added a new file w the same code in project folder and it worked.Can you explain the logic behind this?

> Generally this problem happens when the type information for one of the methods you're calling indicates it will return `Never`. The intent here is to catch an exception statically. Meaning if you call that code with the arguments provided, it will throw an exception.
> 
> This particular issue was with the type annotations for selenium. The older version indicated a return of `Never` incorrectly, but the newer version fixed that problem.
> 
> @Nandinimishra17, it would be better if you opened a new issue. We'd need to have a self contained repro and a list of the packages you have installed.
> 
> This works for me with selenium version 4.19.0
> 
> ![image](https://private-user-images.githubusercontent.com/19672699/317362659-b0d58223-83ac-43f2-82b8-124d9b385833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTg3MzIsIm5iZiI6MTcxMTU1ODQzMiwicGF0aCI6Ii8xOTY3MjY5OS8zMTczNjI2NTktYjBkNTgyMjMtODNhYy00M2YyLTgyYjgtMTI0ZDliMzg1ODMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2NTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMjhlOTdiNGIxYzYxOGY1OGQyMWM0Yjc1ZTRjM2ZhZWU3M2EwMTE3OTc4ZDVlOTdiYmIyYmI3MWNkNDhhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5XiM9VN1OzQaf0i88no67JBpR4fIp8FxiCLJE1WJYcc)

**Comment by rchiodo** [comment] 2024-03-27 18:03
> Can you explain the logic behind this?

 If you're calling a function that we know is going to never return, it means the code after that can't be analyzed.

Suppose there was a function like so:

```python

def foo():
    raise Exception("Foo crashes")
```

And then you called foo in your code.

```python

x = foo()

print(x) # This code is marked as unreachable.
```

In selenium's case, the function definition for `webdriver.Chrome` was marked as throwing an exception.
