### ISSUE TITLE
Comment does not fold with function body if at end of function

### ISSUE THREAD

**Issue by LunarLanding** [microsoft/pylance-release#3099] opened 2022-07-22 08:35 UTC
# Behaviour
## Expected vs. Actual

Comment does not fold with function body, if at end of function.

## Steps to reproduce:

1. Type this in a python file
```
def f(x):
    pass
    # this does not fold with function, even though it has the correct indentation
````

<img width="177" alt="image" src="https://user-images.githubusercontent.com/4441338/180398936-fb8032ac-5c98-407b-94c7-6ab5bf32a691.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/4441338/180398976-54e66bff-b543-4183-b463-9a8d4c782d96.png">

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

linting
• enabled: false
• mypyEnabled: true

formatting
• provider: "black"

```

</p>
</details>

**Comment by debonte** [comment] 2022-08-08 23:31
Dupe of #2321

**Closed by debonte** 2022-08-08 23:31 UTC
Labels: bug, duplicate
