### ISSUE TITLE
Pylance fails to detect import structure for a module it seemingly found

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#664] opened 2020-12-01 11:10 UTC
## Environment data
0. VScode 1.47.2
1. Win7x64
2. Python 3.7 win64, release (set up via pythonPath in VSCode)
3. Pylance language server 2020.8.2
4. Installed [custom BlenderPy wheel module](https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph?usp=sharing) via pip successfully
5. Added scripts and modules folder into PYTHONPATH in .env

## Expected behaviour

Imports from `bpy` namespace are picked up

## Actual behaviour

Import of base  `bpy` is picked up by Pylance as valid. Any nested/included imports marked as invalid:
![image](https://user-images.githubusercontent.com/623756/100709212-c06b6a80-33be-11eb-8cf5-8b67d7d3408b.png)
I can assure you that they are there.

## Logs

```
[Info  - 10:12:10 am] Pylance language server 2020.8.2 (pyright fbe2eb4d) starting
[Info  - 10:12:10 am] Server root directory: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server
[Info  - 10:12:10 am] No configuration file found.
[Info  - 10:12:10 am] Setting pythonPath for service "BlenderAddonTools": "c:\Programs\Python37\python.exe"
[Error - 10:12:10 am] stubPath d:\Unlinked\GIT\BlenderAddonTools\typings is not a valid directory.
[Info  - 10:12:10 am] Assuming Python version 3.7
[Info  - 10:12:10 am] Assuming Python platform Windows
[Info  - 10:12:10 am] Searching for source files
[Info  - 10:12:10 am] Found 10 source files
[Info  - 10:12:10 am] Background analysis root directory: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server
[Info  - 10:12:10 am] Background analysis started
[BG] analyzing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py ...
[BG]   parsing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (210ms)
[BG]   parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\builtins.pyi (133ms)
[BG]   binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\builtins.pyi (69ms)
[BG]   binding: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (36ms)
[BG]   checking: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py ...
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\struct.pyi (10ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\struct.pyi (1ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\os\__init__.pyi (44ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\os\__init__.pyi (8ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\io.pyi (9ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\io.pyi (7ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\binascii.pyi (6ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\binascii.pyi (3ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\codecs.pyi (6ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\codecs.pyi (20ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\enum.pyi (4ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\enum.pyi (6ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\abc.pyi (1ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\abc.pyi (1ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\math.pyi (2ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\math.pyi (2ms)
[BG]     parsing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonUtils.py (11ms)
[BG]     binding: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonUtils.py (3ms)
[BG]     parsing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonNodeMat.py (11ms)
[BG]     binding: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonNodeMat.py (4ms)
[BG]     parsing: d:\Unlinked\GIT\BlenderAddonTools\timing.py (7ms)
[BG]     binding: d:\Unlinked\GIT\BlenderAddonTools\timing.py (1ms)
[BG]     parsing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonMenuIcon.py (5ms)
[BG]     binding: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonMenuIcon.py (0ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\typing.pyi (20ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\typing.pyi (19ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\third_party\2and3\typing_extensions.pyi (2ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\third_party\2and3\typing_extensions.pyi (1ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\array.pyi (3ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\array.pyi (5ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\mmap.pyi (8ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\mmap.pyi (2ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (3ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (1ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\types.pyi (18ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\types.pyi (4ms)
[FG] parsing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (221ms)
[FG] parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\builtins.pyi (160ms)
[FG] binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\builtins.pyi (97ms)
[FG] binding: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (37ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\os\path.pyi (4ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\3\os\path.pyi (2ms)
[BG]     parsing: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\genericpath.pyi (1ms)
[BG]     binding: d:\Unlinked\Users\Kein\.vscode\extensions\ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\stdlib\2and3\genericpath.pyi (1ms)
[BG]   checking: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (1435ms)
[BG] analyzing: d:\Unlinked\GIT\BlenderAddonTools\BlenderAddonImporter.py (1884ms)
```
## Code Snippet / Additional information

*(only first import is resolved.)*
```python
import bpy
from bpy_extras.wm_utils.progress_report import (
    ProgressReport,
    ProgressReportSubstep,
)
from bpy_extras.io_utils import ImportHelper
from bpy.props import StringProperty, BoolProperty, EnumProperty
from bpy.types import Operator
from mathutils import Quaternion, Vector, Matrix
```

**Comment by judej** [comment] 2020-12-03 00:37
@Kein, Thanks for the report. Since blenderpy is a compiled module, Pylance is unable to navigate the module structure and find the nested modules. In order the this discover to work and for completions, signature help, tooltips and all the other goodness to work, it will need type stubs. 

Regarding PYTHONPATH, we are currently looking at when to we can start supporting it. Should have a decision soon. Sorry did not have a more positive answer for you. Thank you for using Pylance and reporting the issue.

**Comment by jakebailey** [comment] 2020-12-03 00:38
See #275 for PYTHONPATH.

**Comment by Kein** [comment] 2020-12-03 14:50
> Since blenderpy is a compiled module, Pylance is unable to navigate the module structure and find the nested modules. In order the this discover to work and for completions, signature help, tooltips and all the other goodness to work, it will need type stubs.

So as i understand it - it is not supported by design?

**Comment by judej** [comment] 2020-12-03 18:13
Correct. Scraping compiled modules for completion or type info is not supported by design. But as more type stubs become available, completions and type info will be available through those stubs. 

I'll close this issue, but feel free to reopen if you need to.

thanks!

**Closed by judej** 2020-12-03 18:13 UTC
Labels: compiled

**Comment by Kein** [comment] 2020-12-05 02:24
Hey, I cant re-open the issue but I dont want to create a junk new one so let's re-use it, since it is relevant. The issue I'm encountering is:
https://github.com/nutti/fake-bpy-module/issues/83

project's **settings.json**
```json
{
    "python.linting.enabled": false,
    "python.analysis.typeCheckingMode": "basic",
    "python.autoComplete.extraPaths": [
        "d:\\Unlinked\\Python\\FakeStubs\\bpy"
    ],
    "python.analysis.extraPaths": [
        "d:\\Unlinked\\Python\\FakeStubs\\bpy"
    ],
    "python.analysis.stubPath": "d:\\Unlinked\\Python\\FakeStubs\\bpy",
}
```
