### ISSUE TITLE
Multiple custom code folds in the same method do not take effect

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3336] opened 2022-09-14 02:55 UTC
```
from time import sleep


def a():
    # region sleep
    sleep(10)
    # endregion sleep

    # region print
    print("sleep")
    # endregion print


```
I can give a simple example. When I perform folding twice in the same method, only the first folding area can take effect, but the second one cannot. 

![image](https://user-images.githubusercontent.com/100815370/190048118-8312cc54-bec7-4b5f-a5ed-a37543ad8da9.png)

I read the docs about folding in vscode and she did not mention this problem. Is this a bug?

**Comment by debonte** [comment] 2022-09-14 16:36
@DamonStamper, this is a duplicate of https://github.com/microsoft/pylance-release/issues/3290. There are some more details on the underlying problem there if you're curious.

**Closed by debonte** 2022-09-14 16:36 UTC
Labels: triage-needed
