### ISSUE TITLE
Language server syntax highlighting not working in notebooks on WSL

### ISSUE THREAD

**Issue by Ssslakter** [microsoft/pylance-release#5547] opened 2024-02-29 07:40 UTC
Type: <b>Bug</b>

# Behaviour
This problem actually has appeared after I've updated vscode to the latest update as well as all python extensions to their latest versions. Before that it worked fine on WSL.
## Expected vs. Actual

On native windows this works fine.

Expected behaviour: 
- when I type module name in a cell it gets highlighted as module and will show hints about its classes or functions.

Actual behaviour: 
- when I type module name in a cell it's not highlighted
![image](https://github.com/microsoft/vscode-python/assets/67190162/4ce70795-ee91-4316-adbc-97263d75161c)

## Steps to reproduce:

1. Open vscode in wsl
2. Create new notebook
3. Select some kernel
4. Run cell with e.g. `import math`
5. Start typing `math.` in a new cell

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details open>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-02-29 14:33:18.233 [info] [Info  - 2:33:18 PM] (20132) [IDX(2)] Long operation: index execution environment file:///home/slakter/coding/py-playground(5257ms)
2024-02-29 14:33:18.276 [info] [Info  - 2:33:18 PM] (20132) [IDX(2)] Long operation: index packages file:///home/slakter/coding/py-playground(5314ms)
2024-02-29 14:33:18.276 [info] [Info  - 2:33:18 PM] (20132) indexed(2) 240 files over 1 exec env
2024-02-29 14:33:18.519 [info] [Info  - 2:33:18 PM] (20132) Indexing finished(2).
2024-02-29 14:33:32.854 [info] [Error - 2:33:32 PM] (20132) Received change text document command for closed file file:///home/slakter/coding/py-playground/abc.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-02-29 14:33:33.115 [info] [Error - 2:33:33 PM] (20132) Received change text document command for closed file file:///home/slakter/coding/py-playground/abc.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-02-29 14:33:33.210 [info] [Error - 2:33:33 PM] (20132) Received change text document command for closed file file:///home/slakter/coding/py-playground/abc.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-02-29 14:33:33.261 [info] [Error - 2:33:33 PM] (20132) Received change text document command for closed file file:///home/slakter/coding/py-playground/abc.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D
2024-02-29 14:33:33.510 [info] [Error - 2:33:33 PM] (20132) Received change text document command for closed file file:///home/slakter/coding/py-playground/abc.ipynb.py#W1sdnNjb2RlLXJlbW90ZQ%3D%3D
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2024.2.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
dsvsc020:30973508

```

</details>

**Comment by debonte** [comment] 2024-02-29 17:56
Thanks for the issue. This should be a bug in VS code:
https://github.com/microsoft/vscode/issues/206487

I'm marking your issue as a dupe of this one:
https://github.com/microsoft/pylance-release/issues/5543

Which is already tracking the VS code problem.

**Closed by debonte** 2024-02-29 17:56 UTC
