### ISSUE TITLE
Python duplicate auto complete / suggestions

### ISSUE THREAD

**Issue by parasurama** [microsoft/pylance-release#3072] opened 2022-07-20 15:23 UTC
Issue Type: <b>Bug</b>

All auto complete and suggestions are duplicated

<img width="503" alt="image" src="https://user-images.githubusercontent.com/13189566/180020752-ef05f68f-66ce-4b95-ad02-227649fe157a.png">

Extension version: 2022.10.1
VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.1.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 6e12eef0-82c9-4388-a94f-15aca63692e4|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prasannac7|
|OS|Linux x64 3.10.0-1062.1.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (8 x 2100)|
|Memory (System)|62.76GB (13.54GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912cf:30529770
vsclangdf:30486550

```

</details>

**Comment by syncoding** [comment] 2022-07-20 16:42
I was going to report the same issue and found it here. Addition to code suggestions, the peek hints for objects and methods on mouseover are also duplicated. I don't know exactly but think it's a Jupyter originated issue because
I spot it whenever I get connected to Jupyter. Language server is set to Pylance by the way.


Issue Type: <b>Bug</b>

Extension version: 2022.10.1
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.99GB free)|
|Process Argv|--crash-reporter-id ea1bf98c-fa08-4525-824c-77a436dc733f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549

```

</details>

**Comment by debonte** [comment] 2022-07-20 18:18
Dupe of https://github.com/microsoft/pylance-release/issues/3027

**Closed** 2022-07-27 21:27 UTC
Labels: needs investigation
