### ISSUE TITLE
Editor semantic Token Color Customizations different colors for property token type - method and argument in Python

### ISSUE THREAD

**Issue by nonoash** [microsoft/pylance-release#5972] opened 2024-04-12 15:29 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Win 10

Steps to Reproduce:

1. set in settings.json "editor.semanticTokenColorCustomizations": {
    "enabled": true,}
2. write a class in python with 2 methods in a structure simular to the picture below
3. Impossible to change in editor.semanticTokenColorCustomizations the color of the "choice" method (light blue) to something different than the argument "self.states1" (light blue) passed as parameter.

They both have the same semantic token type or foreground, changing "property" semantic token type change the color of both

Ultimately i would prefer at least having this "self.states1" argument color (light blue) as the same color as "self.test1" (white) in the first method which is recognized as scope property.declaration.

Preferably having 2 different scopes for these.

![semantichl](https://github.com/microsoft/vscode/assets/116904212/1437ac57-337e-478b-a931-41b26d8855ee)

---

On a side note: The only way to make it work is disabling semantic coloring and use respective Textmaterule scope but if i do that i get another problem (which made me enable semantic coloring in the first place) where i can't have the color of parameters passed in a function the same as parameters in the body of the function. 

Using "source.python" scope is too wide and will change a lot more unwanted code color that just that.
![image](https://github.com/microsoft/vscode/assets/116904212/ba09f71d-e90e-44dc-a8e3-82de26b28a74)

**Comment by debonte** [comment] 2024-06-06 21:53
This is a duplicate of https://github.com/microsoft/pylance-release/issues/5841. Please up-vote that issue.

If you Go to Definition on `np.random.choice` you'll see that it is a variable that is aliasing a function (`_rand.choice`). Because of that, our semantic token provider currently colors it as a variable rather than a function. https://github.com/microsoft/pylance-release/issues/5841 has a discussion about whether it would be possible to change that behavior without dramatically decreasing semantic token perf.

![image](https://github.com/microsoft/pylance-release/assets/12820898/93f588fe-4257-4458-9715-d7d908d54326)

**Closed by debonte** 2024-06-06 21:53 UTC
Labels: needs repro
