### ISSUE TITLE
Pylance fails with a too many open files issue

### ISSUE THREAD

**Issue by jdwestbrook** [microsoft/pylance-release#939] opened 2021-02-11 16:19 UTC
Issue Type: <b>Bug</b>

With the latest release of v2021.2.1 of Pylance and 
Insiders  build.

Version: 1.54.0-insider
Commit: 93f705ab40b37aade9d3b5165ed09114a8c87ac9
Date: 2021-02-11T05:43:26.672Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

The following traceback is displayed in the Terminal Problems Tab when multiple vsode window are open.   The open file 
issue is not observed when editing a single simple repo.  

{
	"resource": "/Users/jwest/MY_FILES/Developing/RCSB/py-rcsb_utils_chemref/rcsb/utils/tests-chemref/testRcsbLigandScoreProvider.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "An internal error occurred while parsing file \"/Users/jwest/MY_FILES/Developing/RCSB/py-rcsb_utils_chemref/rcsb/utils/tests-chemref/testRcsbLigandScoreProvider.py\": Error: EMFILE: too many open files, scandir '/Users/jwest/MY_FILES/Developing/RCSB/py-rcsb_utils_chemref'\n    at Object.readdirSync (fs.js:959:3)\n    at h.readdirEntriesSync (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:609711)\n    at B._getFilesInDirectory (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:160020)\n    at B.resolveAbsoluteImport (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:152915)\n    at B._resolveBestAbsoluteImport (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:155203)\n    at B.resolveImport (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:147689)\n    at t.SourceFile._resolveImports (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:255546)\n    at /Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:247540\n    at i.timeOperation (/Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:631349)\n    at /Users/jwest/.vscode-insiders/extensions/ms-python.vscode-pylance-2021.2.1/dist/pyright.bundle.js:1:247507",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

Extension version: 2021.2.1
VS Code version: Code - Insiders 1.54.0-insider (93f705ab40b37aade9d3b5165ed09114a8c87ac9, 2021-02-11T05:43:26.672Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.30GB free)|
|Process Argv|. --crash-reporter-id b92874fa-6087-44b6-a84a-b516454ef044|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30251590
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by jdwestbrook** [comment] 2021-02-11 16:39
As a follow up, I am seeing failure and the traceback even in simple repos with a few hundred files in a single vscode session.

**Comment by jakebailey** [comment] 2021-02-11 16:45
Duplicate of #936.

**Closed by jakebailey** 2021-02-11 16:45 UTC
Labels: triage
