### ISSUE TITLE
Pylance causes Python Tools to crash: cannot find module server.bundle.js

### ISSUE THREAD

**Issue by pjanowski** [microsoft/pylance-release#807] opened 2021-01-05 19:44 UTC
## Environment data

-   Language Server version: v2020.12.2
-   OS and version: WSL Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda, issue reproduces with all python versions/conda envs (tried Python 2.7, 3.7, 3.8)

## Expected behaviour

Install Python Tools. Install Pylance. Enable both. Reload VSCode. Pylance should work.

## Actual behaviour

Install Python Tools. Install Pylance. Enable both. Reload VSCode. 
Get notification:
"The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.

Jedi works fine. 

Tried uninstalling and manually deleting extensions from /home/wsluser/.vscode-server/extensions/ 
Issue persists.

## Logs
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/home/wsluser/.vscode-server/extensions/ms-python.python-2020.12.424452561/nodeLanguageServer.0.0.346/server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 11:34:41 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by jakebailey** [comment] 2021-01-05 19:49
Dupe of #307/#615/microsoft/vscode-python#15085. You have some old dogfooding settings that need to be removed.

If you have any of these in your settings, remove them:

```
    "python.downloadLanguageServer": ...,
    "python.analysis.downloadChannel": "...",
    "python.blobName": "...",
    "python.packageName": "...",
```

**Closed** 2021-01-05 19:50 UTC
Labels: duplicate, triage

**Comment by pjanowski** [comment] 2021-01-05 20:43
Thanks @jakebailey, that worked.

**Comment by ayush7** [comment] 2022-08-29 12:52
I 

> Dupe of #307/#615/[microsoft/vscode-python#15085](https://github.com/microsoft/vscode-python/issues/15085). You have some old dogfooding settings that need to be removed.
> 
> If you have any of these in your settings, remove them:
> 
> ```
>     "python.downloadLanguageServer": ...,
>     "python.analysis.downloadChannel": "...",
>     "python.blobName": "...",
>     "python.packageName": "...",
> ```

I had the same issue, although these options were not present in my settings.json. 
To fix the issue, I had to uninstall all Python extensions (pylance, jupyter etc) and then remove the residual files from the extension folder  at ```{username}\.vscode\extensions``` . They were the ones causing the issue for me. 
Reinstalled python extension. Worked for me.
