### ISSUE TITLE
Folding issues on regular methods

### ISSUE THREAD

**Issue by JOJ0** [microsoft/pylance-release#2492] opened 2022-03-20 10:53 UTC
Issue Type: <b>Bug</b>

I just realise that in a Python project I did not open for a couple of months I have a lot of folding issues, meaning that on regular methods inside classes there is no > sign on the left border to click on to fold/unfold. Also when I try to use the vim shortcut (using a vim extension), folding does not work on these methods but does flawlessly on others that have the usual > sign.

Is this a known issue already? If yes, sorry, I did a quick search on issues in the github repo for the Python extensions but couldn't find anything related to keywords fold/folding.

I am not sure how to reproduce, just want to open for now and probably need advice on how to proceed with analysis.

Thanks in advance!

Extension version: 2022.2.1924087327
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.09GB free)|
|Process Argv|--crash-reporter-id 45d2b621-90df-47f2-b744-7a96085529e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvspyt640:30450904
vscscmwlcmc:30438804
cppdebug:30451566
dockersurvey3:30453609
pynewfile477:30450038

```

</details>

**Comment by debonte** [comment] 2022-03-21 16:16
> using a vim extension

@JOJ0, What language server are you using? The Python team transferred this issue to Pylance, but Pylance is not supported in vim.

> I am not sure how to reproduce

Does the issue not reproduce consistently? That is, for a particular chunk of code, do you sometimes see a folding node and sometimes not?

Regardless of how consistently it repros, can you please provide a small sample of code where you've seen this issue, along with details on which folding nodes (>) were missing?

**Comment by JOJ0** [comment] 2022-04-06 12:14
Sorry for not getting back earlier.

Is there a misunderstanding: I ment vim extension for vscode, not an extension for the vim editor itself. 

I'm using pylance, yes.

**Comment by debonte** [comment] 2022-04-06 16:55
> Is there a misunderstanding? I ment vim extension for vscode, not an extension for the vim editor itself.

Oh, yes, I misunderstood. Thanks for clarifying.

**Comment by debonte** [comment] 2022-06-09 21:04
@JOJ0, I'm closing this issue since you haven't provided a code sample that reproduces this issue.

For what it's worth, I would not expect folding via the vim shortcut to work if there's no > control in the margin.

Provide some code that repros the issue and we'll take a look.

**Closed by debonte** 2022-06-09 21:04 UTC
Labels: needs investigation
