### ISSUE TITLE
IntelliSense marking issues that do not exist

### ISSUE THREAD

**Issue by PiranhaV** [microsoft/pylance-release#3698] opened 2022-11-30 21:58 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: IntelliSense marks errors where they happen and colors imports etc.

Actual: IntelliSense marks errors somewhere in the first few lines. These errors mostly have existed but have been resolved by then. When for example importing a library (from flaks import Flask,..) from and import are colored but flask, Flask... are not. Same happens with variables. Gets fixed with restart until anything is edited.

## Steps to reproduce:

Not found just randomly starts happening.

![image](https://user-images.githubusercontent.com/95772518/204916839-f96750d6-5b47-4ebb-b563-46abc0000e33.png)
![image](https://user-images.githubusercontent.com/95772518/204917017-c8eb0215-3a79-4d83-9601-d795c2baa55e.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonaa' is active
Experiment 'pythonSurveyNotification' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: ~\AppData\Local\Programs\Python\Python311\python.exe
> ~\AppData\Local\Programs\Python\Python311\python.exe ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\interpreterInfo.py
Starting Pylance language server.

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.87GB (36.08GB free)|
|Process Argv|--crash-reporter-id a8bf20ed-6375-459d-9b3a-90d48d723a15|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by rchiodo** [comment] 2022-12-01 17:45
This should be a dupe of #3652. If you upgrade pylance to the latest prerelease, this issue should be fixed.

**Comment by rchiodo** [comment] 2022-12-01 17:46
It's a problem with synchronization when using a multi folder workspace.

**Closed by rchiodo** 2022-12-01 17:45 UTC
Labels: triage-needed
