### ISSUE TITLE
Pylance suggestions show indirect imports through files opened in the site-packages folder

### ISSUE THREAD

**Issue by justin-snyder-slgg** [microsoft/pylance-release#3760] opened 2022-12-14 17:30 UTC
**Describe the bug**
The first time or two (in a session?) when importing a module, Pyright will often suggest a litany of weird indirect imports of modules, with the direct standard library import you actually want buried sometimes 10-20 entries down. This weird behavior corrects itself after selecting the correct one from the dropdown (I don't know how long this lasts), but I often import the module manually out of frustration, so the correction doesn't happen.

While it does occasionally make sense to use an indirect import (e.g. going through `six.moves` when you're working on a library that still needs to support Python 2 for some reason), this is not a commonly desired behavior.

**To Reproduce**
In a fresh session of a project that uses boto3 (any project with a number of external dependencies will do, but this is the most extreme example), type `logging` and observe a large number of indirect import suggestions of the standard `logging` module.

**Expected behavior**
The direct import suggestion should always appear first in a fresh session.

**VS Code extension or command-line**
command-line, as I am using Sublime Text + LSP + pyright

**Comment by heejaechang** [comment] 2022-12-14 18:52
@justin-snyder-slgg can you provide some screenshot that shows the issue?

**Comment by justin-snyder-slgg** [comment] 2022-12-15 22:42
I will make sure to get one the next time I see the bug. Since the suggestions get re-ordered after selecting an import, my most recent run-in with the bug isn't happening anymore.

Is there some way to reset the memory of pylance/the lsp so that I can get a screenshot sooner?

**Comment by justin-snyder-slgg** [comment] 2022-12-15 22:47
I found an import it suggests importing indirectly

<img width="340" alt="Screen Shot 2022-12-15 at 3 45 14 PM" src="https://user-images.githubusercontent.com/104024666/207983037-288c3299-ae59-481d-9c51-e7a9da92ce6f.png">

the direct import from the standard library is at the bottom of the list of suggestions

<img width="337" alt="Screen Shot 2022-12-15 at 3 46 38 PM" src="https://user-images.githubusercontent.com/104024666/207983251-98b12d73-86ec-4505-b91d-949ab113be86.png">

**Comment by heejaechang** [comment] 2022-12-19 02:29
@justin-snyder-slgg I am sorry but the screenshot is missing the info I want to see. I want to see where all other urllib3 came from but your screentshot cut out that info.

by the way, is this screenshot from pylance? if it is, it should show something like this.

![image](https://user-images.githubusercontent.com/1333179/208336117-1c12f682-509f-4c5a-987a-50e475630893.png)

**Comment by justin-snyder-slgg** [comment] 2022-12-20 18:01
I use SublimeText, so the interface looks different. It should be the same functionality when it comes down to the language server.

Some packages it prefers using indirectly for the `urllib3` example from earlier:

- `rockset.swagger_client.rest`
- `rockset.swagger_client.configuration`
- `botocore.vendored.requests.packages`
- `botocore.exceptions`

It really likes trying to import via third party packages.

I have configured the language server to look at a particular venv if that matters.

**Comment by rchiodo** [comment] 2023-02-01 00:51
I'm having trouble reproing this with Pylance.

This setting has to be off to get more than exact matches:

```json
  "python.analysis.indexing": false,
```

But I still get items from the stdlib first.

Here's what I get for 'log':



![Image](https://user-images.githubusercontent.com/19672699/215915072-71236fd2-e3b1-4064-a1a7-a0958068fce3.png)



I get nothing for urllib3 without indexing on. 

With indexing on, I get just this:



![Image](https://user-images.githubusercontent.com/19672699/215915236-6050c53d-b5e8-4ff6-b337-e4301d654a72.png)

So I tried this with just pyright (instead of pylance). In the botocore project (which I'm guessing is what you're working on @justin-snyder-slgg )

I get this for logging:



![Image](https://user-images.githubusercontent.com/19672699/215917077-de7e57a8-913f-4bc3-9a05-66e107095eda.png)

And nothing for urllib3.


Perhaps you're using a different version of Pyright? Or maybe Sublime isn't using the [sortText](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) field for completions.

Can you repro this in VS code?

**Comment by rchiodo** [comment] 2023-02-01 17:20
Seems I get more imports from opening files when indexing is off. Trying to repro again with a bunch of files open.

**Comment by rchiodo** [comment] 2023-02-01 17:26
After opening 30 files or so I do get local versions (from opened files) before I get system libs.

![image](https://user-images.githubusercontent.com/19672699/216117091-cebb069b-17a8-4dc9-8dd7-375c6f952b13.png)

That's by design. Modules in your own workspace should sort before system libs. 

For me this local 'urllib3' is coming first:

![image](https://user-images.githubusercontent.com/19672699/216117497-3591d558-3781-4695-b1b9-8558eda4707e.png)

**Comment by justin-snyder-slgg** [comment] 2023-02-03 17:35
Looks to me like you reproduced the bug. The second option is the correct one, most likely. Except you don't seem to agree with me that this is a bug. Let me explain myself.

It makes perfect sense for modules in my workspace to take priority over system libs- that is something I have no complaints about because it's a sensible behavior.

What doesn't make sense is for suggested imports to be _indirect_ imports. When I ask for `logging`, I want to import it directly from the standard library, not through `boto` or some other module that happens to import that module. This logic also applies to a third party library like `requests`. I want to get `requests` from the direct import, not some other library that happens to use `requests`. The import path that matches the module's `__name__` (i.e. the one that is _blank_ to the right) should always come first by default, not last or somewhere awkwardly in the middle.

This issue comes up for me frequently. Always with a different module.

I request this to be re-opened because the issue I described has not been resolved.

**Comment by rchiodo** [comment] 2023-02-03 17:47
In the repro I had it wasn't an indirect reference to a stdlib module. It was boto's own copy of urllib3. A local version. 

It's on disk here in the boto repo:

![image](https://user-images.githubusercontent.com/19672699/216672004-062bc4bc-49e4-4275-b224-da501f78be6d.png)


I don't believe we show indirect imports anywhere, but I could be wrong. If that was the case, that would seem like a bug.

**Comment by justin-snyder-slgg** [comment] 2023-02-03 17:48
Happened to me just now with `functools`

<img width="397" alt="Screenshot 2023-02-03 at 10 45 17 AM" src="https://user-images.githubusercontent.com/104024666/216672046-051cd5d7-e16d-470f-93e1-fb22fdfeb9d7.png">

The expected import is at the bottom

<img width="402" alt="Screenshot 2023-02-03 at 10 45 27 AM" src="https://user-images.githubusercontent.com/104024666/216671892-490ae3c0-073c-4027-a77f-c2f17e818b87.png">

**Comment by rchiodo** [comment] 2023-02-03 17:50
What is the list of functools that it's putting there? Are you still doing this in botocore?

**Comment by rchiodo** [comment] 2023-02-03 17:53
Functools is also in the vendored list:

![image](https://user-images.githubusercontent.com/19672699/216672987-77a33df6-125c-456e-a81a-17bc210ff119.png)

Botocore seems to have its own version of a lot of system modules.

**Comment by justin-snyder-slgg** [comment] 2023-02-03 17:55
This indirect import is going through `flask_caching`, not `botocore`. When opening up the file, it's pretty clearly an indirect import from the standard library.

If it's helpful to you at all, I'm using a virtualenv in my workspace.

**Comment by justin-snyder-slgg** [comment] 2023-02-03 17:57
When running the python repl in the same venv that my workspace is using, you can see it's an indirect import:

```
>>> import flask_caching
>>> flask_caching.functools.__file__
'/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py'
>>> flask_caching.functools.__name__
'functools'
>>> flask_caching.__name__
'flask_caching'
```

**Comment by rchiodo** [comment] 2023-02-03 17:58
So maybe the root cause of the problem here is that you don't want any workspace copies of system libs to come up in that list? 

I believe this might work:

```json
"python.analysis.exclude": [
   "${workspaceRoot}/botocore/vendored"
]
```

At least it did for me to get it to exclude the vendored urllib3.

**Comment by rchiodo** [comment] 2023-02-03 18:00
Yes flask_caching is coming from the system lib, but the auto import on the completions doesn't know that the 'local' copy is actually a copy of a system lib. It just thinks it's a local module that matches the text you typed in.

**Comment by justin-snyder-slgg** [comment] 2023-02-03 18:01
So... is this essentially just an artifact of using virtualenvs? I feel like that should be a properly handled use case.

**Comment by rchiodo** [comment] 2023-02-03 18:04
Yeah functools isn't actually in botocore. It does seem like it's picking it up under the .venv. That shouldnt' be the case unless we can't distinguish between files opened in the .venv and those in the workspace. 

That might be what you're seeing. If you goto def on something in the .venv, it opens the file in the site-packages folder. Then the 'local' copy of functools is ending up in the list first.

**Comment by rchiodo** [comment] 2023-02-03 18:09
I think the urllib3 case was a bad example for me to repro with. The functools problem sounds much more like a bug.

**Comment by heejaechang** [comment] 2023-02-03 18:20
does functools all point to the same symbol when alias is resolved? or it is actually different symbol with same name?

if it is a different symbol with the same name, then it is a sorting improvement request. if it is the same symbol exported by multiple different packages/modules showing up, then it is due to import dedup not working issue. 

With `python.analysis.indexing` on, we do `symbol deduplication` when we do indexing, but @justin-snyder-slgg is not using `vscode` or `pylance`, so there is no indexing. 

need to take a look how we do dedup in those case if it is the second case.

if it is the first case, we can change our sorting text a bit from completion item, but ultimately, it is up to the host (`vscode` in our case) on how to sort it. We can suggest the sorting, but host has the final say. so even if we change our sorting text, there is no guarantee host (`SublimeText` for the user) will show it that way.

**Comment by heejaechang** [comment] 2023-02-03 18:26
since `pyright` suggests `auto import` from all modules currently loaded in the memory (regardless how it is loaded), we might want to improve both `sorting` and `deduplication` for `auto import` especially with `indexing` off.

**Comment by rchiodo** [comment] 2023-02-03 18:30
`functools` points to different symbol with same name. 

One is this one:

`.venv\Lib\site-packages\setuptools\_vendor\jaraco\functools.py`

The real one would be this one:

`.venv\Lib\site-packages\jaraco\functools.py`

You can get this to repro if you open anything in setuptools in the editor.

**Comment by rchiodo** [comment] 2023-02-06 19:36
We could potentially sort the stdlib entries first. Otherwise from pyright's point of view the symbol is different and should show up.

**Comment by heejaechang** [comment] 2023-03-17 19:27
made sort order to prefer symbol from shortest module path first. so for cases described above, one from stdlib will be at the top.

**Comment by rchiodo** [comment] 2023-03-17 23:54
This issue has been addressed in prerelease version 2022.3.25, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022325-17-March-2023-PreRelease)

It should be sorting the syspath entries first now.

**Closed by rchiodo** 2023-03-17 23:54 UTC
Labels: bug, fixed in next version

**Comment by ssbarnea** [comment] 2023-05-01 06:12
@heejaechang I think that the path lenght is a mistake because too many 3rd party have shorter names than stdlib ones.

Too often I see suggestions from other packages instead of those from stdtin, here is an example for `Path`.

![](https://sbarnea.com/ss/Screen-Shot-2023-05-01-07-08-21.74.png)

Install stuff like click or git and you will be surprised.

IMHO, stdlib should always be prioritized, ideally it should be a configurable list of stdlib modules which are prioritized, changing it could allow us to define other preferred modules.

**Comment by heejaechang** [comment] 2023-05-01 08:43
@ssbarnea change for this issue is for `completion` and what you describe is `code action` and these 2 are different features.

so, change for this issue won't affect `code action`'s behavior. that said, it would be nice if you can open a new issue with some details and actual examples on what you prefer rather than just saying put `stdlib` at the top.

that would make it a lot easier for us to discuss.

**Comment by ssbarnea** [comment] 2023-05-01 09:01
@heejaechang I raised it as https://github.com/microsoft/pylance-release/issues/4299 - feel free to polish it if I missed something important.
