### ISSUE TITLE
numpy.cross is reported as NoReturn

### ISSUE THREAD

**Issue by szabimollia** [microsoft/pylance-release#3287] opened 2022-09-06 09:01 UTC
## Environment data

-   Language Server version: 2022.8.50 (pyright f107f0f3)
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

## Code Snippet

correct highlight:

![image](https://user-images.githubusercontent.com/81617573/188592201-ccdbfee4-9c23-4c79-9021-97700347d33c.png)

incorrect highlight:

![image](https://user-images.githubusercontent.com/81617573/188591522-618fbb3b-fa93-48bc-a877-ebfcee17e67e.png)

```python
import numpy as np

def temp(a, b):
    z = np.cross(a, b)
    return z + z

print('hello')
k = temp([1.0, 0.0, 0.0], [0.0, 1.0, 0.0])
print('world')
print(k)
```

```
hello
world
[0. 0. 2.]
```

## Repro Steps

Make a function that uses np.cross with 2 arguments of not identified type.

the function will be detected as:

```
(function)
cross(a: _ArrayLikeBool_co, b: _ArrayLikeBool_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NoReturn

cross(a: _ArrayLikeUInt_co, b: _ArrayLikeUInt_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NDArray[unsignedinteger]

cross(a: _ArrayLikeInt_co, b: _ArrayLikeInt_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NDArray[signedinteger]

cross(a: _ArrayLikeFloat_co, b: _ArrayLikeFloat_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NDArray[floating]

cross(a: _ArrayLikeComplex_co, b: _ArrayLikeComplex_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NDArray[complexfloating]

cross(a: _ArrayLikeObject_co, b: _ArrayLikeObject_co, axisa: int = ..., axisb: int = ..., axisc: int = ..., axis: int | None = ...) -> NDArray[object_]
```

The first result finds np.cross to return a `NoReturn`.
This makes the rest of the code render as deadcode.

## Expected behavior

A single `NoReturn` out of many other possibilities should not render the rest of the file as deadcode.

I have tested with older numpy versions and the problem seems to persist.
The render broke when my vscode updated the python related extensions.

**Comment by erictraut** [comment] 2022-09-06 12:52
See https://github.com/microsoft/pylance-release/issues/3277#issuecomment-1237782014.

**Comment by judej** [comment] 2022-09-06 17:46
duplicate of #3277

**Closed by judej** 2022-09-06 17:46 UTC
Labels: triage-needed
