### ISSUE TITLE
Type `type[Any]` should not be treated as type `Any`

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#748] opened 2020-12-16 10:23 UTC
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5(Anaconda

## Expected behavior

```python
from typing import Any

def foo(a: type[Any]):
    # Type of `a` is `type[Any]` or just `type`.
    a
```

## Actual behavior

```python
from typing import Any

# Got "(parameter) a: type[Any]" when mousing over `a` in next line.
def foo(a: type[Any]):
    # Got "(parameter) a: Any" when mousing over `a` in next line.
    a
```

Same situation when using `typing.Type` instead of `type`.

**Comment by Azureblade3808** [comment] 2020-12-16 10:46
If using `type` instead of `type[Any]`, the issue remains in another form.

```python
# Got "(parameter) a: type[Unknown]" when mousing over `a` in next line.
def foo(a: type):
    # Got "(parameter) a: Unknown" when mousing over `a` in next line.
    a
```

But if using `type[object]` or any other concrete types, things seem to be right.

```python
# Got "(parameter) a: type[object]" when mousing over `a` in next line.
def foo(a: type[object]):
    # Got "(parameter) a: Type[object]" ("Type" vs. "type") when mousing over `a` in next line.
    a
```

**Comment by erictraut** [comment] 2020-12-16 16:24
This is a duplicate of #747. As I explained in that issue, this is a result of PEP 585, and I think the behavior is correct.

**Closed** 2020-12-16 18:51 UTC
Labels: triage
