### ISSUE TITLE
Problem about the code hints

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1548] opened 2021-07-13 02:26 UTC
## Environment data

-   Language Server version: 2021.7.2
-   OS and version: Windows10 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6

## Expected behaviour

See the screenshot below. As I type `Class1(`, The text marked red should be "Docstring of Class1".

## Actual behaviour

The text is actually "Built-in mutable sequence. If no argument is given, the constructor creates a new empty list. The argument must be an iterable if specified.", which is actually the docstring of `list`, i.e. the super class of `Class1`.
When I hover on `Class1`, what I see is "Docstring of Class1", which is as expected.

## Logs

```
None
```

## Code Snippet / Additional information

```python
class Class1(list):
    '''
    Docstring of Class1
    '''
    pass
# These empty lines are to avoid the box from occluding the code above.








Class1()  # Please don't just copy & paste this line but type "Class1(" instead.
```
![屏幕截图 2021-07-13 100537](https://user-images.githubusercontent.com/62426149/125380153-52f7d180-e3c4-11eb-9ff0-3d436d56f06d.png)

**Comment by judej** [comment] 2021-07-13 17:42
Dupe of #653 and #1047

**Closed by judej** 2021-07-13 17:42 UTC
Labels: triage
