### ISSUE TITLE
Random errors with imports after update

### ISSUE THREAD

**Issue by sebbie** [microsoft/pylance-release#3713] opened 2022-12-04 22:10 UTC
After the update to v2022.11.40 extension randomly reports non-existing "errors" in import statements. Some examples below:

![image](https://user-images.githubusercontent.com/255401/205518285-9027b6ef-24a8-4deb-ba29-8d6125641f4b.png)

![image](https://user-images.githubusercontent.com/255401/205518295-7f2f0b30-6619-48c4-bf3f-b9026e016afd.png)

![image](https://user-images.githubusercontent.com/255401/205518300-e57f148d-f50b-4a16-b0a1-b9f6f0ad3cdc.png)

This was working fine before the update.

**Comment by rchiodo** [comment] 2022-12-05 17:26
This should be a dupe of #3652. The fix for 3652 is in the prerelease version or 2022.11.41 (or 2022.12.11 which has it too).

The root cause is a synchronization issue when multiple folders are open. If you have multiple folders in your workspace, this should be fixed by the latest prerelease bits.

**Closed** 2022-12-05 19:10 UTC
Labels: triage-needed
