### ISSUE TITLE
Latest Version of VS Code (Pylance) Doesn't Recognize Site-Package Import

### ISSUE THREAD

**Issue by YTKme** [microsoft/pylance-release#4813] opened 2023-09-08 15:38 UTC
<img width="1425" alt="s-1" src="https://github.com/microsoft/pylance-release/assets/3649725/ea232601-f5cd-4299-809a-c90996f9b043">
Type: <b>Bug</b>

Running in a Python virtual environment (venv), the venv have the package installed (in this case Flask), but when the workspace is set to the virtual environment, and try to import that package, Pylance show missing import.

Extension version: 2023.9.11
VS Code version: Code - Insiders 1.83.0-insider (5a400e53e985dc5e24f6ee574b07ab23943841c5, 2023-09-07T17:36:06.641Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (3.12GB free)|
|Process Argv|--crash-reporter-id f9036e4b-e00d-411e-91dc-287ea91b369d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2023-09-08 16:06
This is likely a dupe of #https://github.com/microsoft/pylance-release/issues/4806

**Comment by YTKme** [comment] 2023-09-08 18:01
> This is likely a dupe of ##4806

seems like it or very similar, please feel free to close if it is

**Closed** 2023-09-08 18:07 UTC
Labels: needs repro

**Comment by YTKme** [comment] 2023-09-09 15:20
just want to confirm that my issue was also fixed with Pylance `v2023.9.12`.
