### ISSUE TITLE
Symbolic links to files not working for analysis

### ISSUE THREAD

**Issue by artemiogr97** [microsoft/pylance-release#4869] opened 2023-09-22 09:34 UTC
## Environment data

Pylance version: v2023.9.20
Os: windows 11
Python version: tested with 3.8.8 and 3.10.7

## Repro Steps

- open any folder in vs code
- create a python file in this folder (e.g. "my_file.py")
- create a symbolic link to this file next to it (e.g. "my_file_symbolic.py")
- create a third file (e.g. "my_test_file.py") and add the following code:

```python
import my_file

import my_file_symbolic
```

## Expected behavior

pylance should recognize both modules, this used to work for Pylance version v2023.9.10

## Actual behavior

pylance shows the following error: "Unable to import 'my_file_symbolic'"

## Notes

there is not an error at runtime, it's just the static analysis that is failing

**Comment by rchiodo** [comment] 2023-09-22 16:00
This is a dupe of https://github.com/microsoft/pylance-release/issues/4852 which was fixed 2023.9.21.

**Closed by rchiodo** 2023-09-22 16:00 UTC
Labels: needs repro
