### ISSUE TITLE
Option to delay error checking.

### ISSUE THREAD

**Issue by ThomasAJ05** [microsoft/pylance-release#2018] opened 2021-11-01 02:29 UTC
Sorry but I'm darned if I can find a way to search for existing Feature Requests.

Every time I type say, "if whatever:", the code below sometimes is lit up like a Christmas tree because it is not indented and is quite distracting. A delay of some seconds would be very useful to give some time to enter the appropriate code under the "if".

**Comment by CodeCrazy-ywt** [comment] 2021-11-01 08:53
Maybe can be taken into consideration. 🤔

**Comment by blackpancake** [comment] 2021-11-01 13:46
Agree.

**Comment by jakebailey** [comment] 2021-11-01 17:41
This is technically a duplicate of #237, but this is more feedback on that idea than we had since that issue was open.

Do you see this for any and all code, where typing `if something:` causes the parser to spit out a load of errors, or is it just specific code? Our parser should be able to recover, then stop emitting errors, so I would be looking to improve that before changing the way we report diagnostics.

**Comment by ThomasAJ05** [comment] 2021-11-02 01:02
I just did `if something:` and there was no Xmas tree effect. Just a slight squiggle on the same line while typing and a squiggle under the 1st whatever on the next line as it's not indented.

But for me this is the next morning and I suspect that Pylance gets a bit tired after a big day of error checking and whatnot.
Meaning, the Xmas effect seems to happen after some hours of coding. But off the top of my head I am not sure.

I'll see if I can reproduce and report back.

**Comment by judej** [comment] 2022-04-20 17:40
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Closed by judej** 2022-04-20 17:40 UTC
Labels: enhancement
