### ISSUE TITLE
Intellisense not working for some packages

### ISSUE THREAD

**Issue by ww2406** [microsoft/pylance-release#957] opened 2021-02-17 02:13 UTC
## Environment data

-   Language Server version: v2021.2.2
-   OS and version: OS X 10.15.7, but also happens on Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 (Anaconda), but also on x64 3.8.6 and 3.8.4 on Windows 10 (regular)

## Expected behaviour

When importing pyodbc, its methods and types are available through IntelliSense, as occurs with Jedi.

![2021-02-16_21-36-02 (1)](https://user-images.githubusercontent.com/57472892/108148567-14711b80-709f-11eb-8996-0ed078946ecf.gif)

## Actual behaviour

Nothing is available in the IntelliSense menu.

![2021-02-16_21-08-14 (1)](https://user-images.githubusercontent.com/57472892/108146494-55ffc780-709b-11eb-8a09-b3e1a82234e5.gif)

## Logs

```
[Info  - 9:11:24 PM] Pylance language server 2021.2.2 (pyright 8ca2c14a) starting
[Info  - 9:11:24 PM] Server root directory: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist
[Info  - 9:11:24 PM] Setting pythonPath for service "<default>": "/opt/anaconda3/bin/python"
Search paths found for configured python interpreter:
  /opt/anaconda3/lib/python3.8
  /opt/anaconda3/lib/python3.8/lib-dynload
  /opt/anaconda3/lib/python3.8/site-packages
  /opt/anaconda3/lib/python3.8/site-packages/aeosa
[Error - 9:11:24 PM] stubPath typings is not a valid directory.
[Info  - 9:11:24 PM] Assuming Python version 3.8
[Info  - 9:11:24 PM] Assuming Python platform Darwin
[Info  - 9:11:24 PM] Searching for source files
[Info  - 9:11:24 PM] No source files found.
[Info  - 9:11:24 PM] Background analysis(1) root directory: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist
[Info  - 9:11:24 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (13ms)
[BG(1)] parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (125ms)
[BG(1)] binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/builtins.pyi (34ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: getSemanticTokens
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (0ms)
[BG(1)] analyzing: Untitled-1 (0ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:1 ...
[FG]   parsing: Untitled-1 (15ms)
[FG]   parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (97ms)
[FG]   binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/builtins.pyi (31ms)
[FG]   binding: Untitled-1 (1ms)
[FG] completion at Untitled-1:0:1 [found 96 items] (151ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:2 ...
[FG]   parsing: Untitled-1 (1ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:0:2 [found 13 items] (3ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (1ms)
[BG(1)] binding: Untitled-1 (0ms)
[BG(1)] parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (19ms)
[BG(1)] binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[BG(1)] parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 3ms] (37ms)
[BG(1)] binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/typing.pyi (10ms)
[BG(1)] parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 2ms] (4ms)
[BG(1)] binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (2ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:3 ...
[FG]   parsing: Untitled-1 (0ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:0:3 [found 11 items] (2ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   parsing: Untitled-1 (0ms)
[BG(1)]   binding: Untitled-1 (0ms)
[BG(1)]   checking: Untitled-1 (6ms)
[BG(1)] analyzing: Untitled-1 (6ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: Untitled-1 (1ms)
[FG] binding: Untitled-1 (0ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (1ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (1ms)
[BG(1)] analyzing: Untitled-1 (1ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   parsing: Untitled-1 (0ms)
[BG(1)]   binding: Untitled-1 (1ms)
[BG(1)]   checking: Untitled-1 (0ms)
[BG(1)] analyzing: Untitled-1 (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:8 ...
[FG]   parsing: Untitled-1 (5ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:0:8 [found 168 items] (14ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (5ms)
[BG(1)] binding: Untitled-1 (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:9 ...
[FG]   parsing: Untitled-1 (5ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:0:9 [found 39 items] (10ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   parsing: Untitled-1 (6ms)
[BG(1)]   binding: Untitled-1 (0ms)
[BG(1)]   checking: Untitled-1 ...
[BG(1)]     parsing: /opt/anaconda3/lib/python3.8/site-packages/py/__init__.pyi [fs read 0ms] (4ms)
[BG(1)]     binding: /opt/anaconda3/lib/python3.8/site-packages/py/__init__.pyi (1ms)
[BG(1)]   checking: Untitled-1 (6ms)
[BG(1)] analyzing: Untitled-1 (12ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:0:10 ...
[FG]   parsing: Untitled-1 (3ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:0:10 [found 8 items] (7ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (4ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: Untitled-1 (3ms)
[FG] binding: Untitled-1 (0ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (0ms)
[BG(1)] analyzing: Untitled-1 (0ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: Untitled-1 (6ms)
[FG] binding: Untitled-1 (0ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (5ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (0ms)
[BG(1)] analyzing: Untitled-1 (0ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   parsing: Untitled-1 (0ms)
[BG(1)]   binding: Untitled-1 (0ms)
[BG(1)]   checking: Untitled-1 (0ms)
[BG(1)] analyzing: Untitled-1 (0ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   parsing: Untitled-1 (0ms)
[BG(1)]   binding: Untitled-1 (0ms)
[BG(1)]   checking: Untitled-1 (1ms)
[BG(1)] analyzing: Untitled-1 (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:2:1 ...
[FG]   parsing: Untitled-1 (0ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:2:1 [found 45 items] (2ms)
[FG] completion at Untitled-1:2:2 ...
[FG]   parsing: Untitled-1 (1ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:2:2 [found 4 items] (2ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (0ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:2:3 ...
[FG]   parsing: Untitled-1 (0ms)
[FG]   binding: Untitled-1 (0ms)
[FG] completion at Untitled-1:2:3 [found 2 items] (1ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (0ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: Untitled-1 (0ms)
[FG] binding: Untitled-1 (0ms)
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (1ms)
[BG(1)] analyzing: Untitled-1 (1ms)
Background analysis message: resumeAnalysis
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: Untitled-1 (1ms)
[FG] binding: Untitled-1 (0ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] completion at Untitled-1:2:7 ...
[FG]   parsing: Untitled-1 (0ms)
[FG]   binding: Untitled-1 (0ms)
[FG]   parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (15ms)
[FG]   binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[FG]   parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (32ms)
[FG]   binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stdlib/typing.pyi (11ms)
[FG]   parsing: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi [fs read 2ms] (3ms)
[FG]   binding: /Users/ww/.vscode/extensions/ms-python.vscode-pylance-2021.2.2/dist/typeshed-fallback/stubs/typing-extensions/typing_extensions.pyi (1ms)
[FG] completion at Untitled-1:2:7 [found 0 items] (83ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: Untitled-1 (0ms)
[BG(1)] binding: Untitled-1 (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: analyze
[BG(1)] analyzing: Untitled-1 ...
[BG(1)]   checking: Untitled-1 (6ms)
[BG(1)] analyzing: Untitled-1 (6ms)
Background analysis message: resumeAnalysis
[FG] completion at Untitled-1:2:7 [found 0 items] (0ms)
```

## Code Snippet / Additional information

```python
import pyodbc

pyodbc.

```

**Comment by savannahostrowski** [comment] 2021-02-17 18:38
This is a duplicate of https://github.com/microsoft/pylance-release/issues/605.

**Closed by savannahostrowski** 2021-02-17 18:38 UTC
Labels: triage
