### ISSUE TITLE
Pylance is linting standard library and venv site-packages

### ISSUE THREAD

**Issue by Spitfire1900** [microsoft/pylance-release#1514] opened 2021-07-01 15:28 UTC
## Environment data

-   Language Server version: v2021.6.3
-   OS and version: Windows 10 x64 1910
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4

## Expected behaviour

Only the current workspace, excluding site-packages should be linted for issues.

## Actual behaviour

Pylance is linting the standard library and venv site-packages

## Logs

[pylance log.txt](https://github.com/microsoft/pylance-release/files/6750278/pylance.log.txt)

![image](https://user-images.githubusercontent.com/6462596/124147580-d2001800-da5c-11eb-9269-9cad26e4d613.png)
![image](https://user-images.githubusercontent.com/6462596/124147642-e217f780-da5c-11eb-8d47-1e0a3ce20aef.png)

**Comment by bschnurr** [comment] 2021-07-05 20:54
by default pylance should only be returning diagnostics for "opened" files.

can you confirm you haven't set this setting to something besides `openFilesOnly`?

settings.json
```
"python.analysis.diagnosticMode": "openFilesOnly",
```

**Comment by jakebailey** [comment] 2021-07-06 17:19
It also shouldn't show those files even in workspace diagnostics mode, so long as that interpreter is selected.

**Comment by Spitfire1900** [comment] 2021-07-07 15:04
This has been reproduced with both diagnostic modes.

**Comment by erictraut** [comment] 2021-07-07 15:16
The log shows that `c:\Users\ACCOUNT\Repos\WORKSPACE\.venv` is being auto-excluded (presumably because it's the selected Python environment). 

I'm unable to reconcile the screen shot above with the provided logs. In particular, the files displayed in the "Problems" section in the screen shot are not mentioned in the log, which means that pylance has not opened or analyzed those files. For example, `os.py` does not appear anywhere in the log.

**Comment by Spitfire1900** [comment] 2021-07-07 17:52
I noticed, but some are, such as `json\decoder.py`

**Comment by Spitfire1900** [comment] 2021-07-07 17:55
What's also been observed is that this doesn't happen immediately, or always happens even. When it does happen it's frequently 10-15min after the project had been opened.

**Comment by erictraut** [comment] 2021-07-07 18:18
Do you remember ever opening these files in the editor?

Also, could you please answer the question asked by @bschnurr above? Is "python.analysis.diagnosticMode" set to the default value of "openFilesOnly", or have you changed it to "workspace"?

**Comment by Spitfire1900** [comment] 2021-07-07 19:13
1. Do you remember ever opening these files in the editor?
A. When opening a stdlib file this does reproduce, for example doing a "Go to definition" on `logging.getLogger()` will trigger  `C:\Program Files\Python39\Lib\logging\__init__.py` to be linted, the errors are retained in the Problems pane after closing `logging\__init__.py`
2. Also, could you please answer the question asked by @bschnurr above? Is "python.analysis.diagnosticMode" set to the default value of "openFilesOnly", or have you changed it to "workspace"?
A. This is with `"python.analysis.diagnosticMode": "workspace"` set in the workspace's `settings.json`. However this reproduces with 'openFilesOnly' (but only for the file that was opened, references are not followed).

Doing a "Go to definition" on a method reference when `"python.analysis.diagnosticMode": "workspace"` is set is what triggers this issue. 

**The easiest way to reproduce this** is to "Go to Definition" on `jinja2.filters` while  `"python.analysis.diagnosticMode": "workspace"` is set.

**Comment by jakebailey** [comment] 2021-07-07 20:56
Thanks for the info. The errors being retained on file close is the bug, but I can't seem to reproduce it on my machine using any of my available interpreters. Closing the open file always hides the diagnostics, so I don't know what's going on there.

(Sounds similar in behavior to #1404, but that's triggered by some yet-to-be-known behavior.)

**Comment by Spitfire1900** [comment] 2021-07-08 18:56
On systems with slower harddrives or especially aggressive AV on-demand scanners this behavior also will trigger heavy bottlenecking of harddisk or CPU respectively.

**Comment by jakebailey** [comment] 2021-07-08 19:08
I don't see how any of this has anything to do with performance. We will only analyze the files when they are opened or changed; the stdlib is stubbed, so we don't analyze the files that are in your screenshots unless they are explicitly opened, and the stdlib doesn't change, so we won't do any more work than we are required to do.

**Comment by jakebailey** [comment] 2021-07-14 21:07
I think @erictraut figured this out and fixed it in https://github.com/microsoft/pyright/commit/d01295d0ed91096c45ae06bd08a55d93faa14797, but we can see in today's release.

**Comment by bschnurr** [comment] 2021-07-15 00:14
This issue has been fixed in version 2021.7.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202173-14-july-2021

**Closed by bschnurr** 2021-07-15 00:14 UTC
Labels: fixed in next version

**Comment by IrfanAkram5** [comment] 2021-08-31 17:08
I was going to comment that I too have been having this issue( running VS code with a miniconda venv on WSL2 ) for a couple of months.  See example picture:  My workaround had been to switch to the Jedi language server.

![Pylance - Screenshot 2021-08-31 171340](https://user-images.githubusercontent.com/87219625/131542851-2762b01d-ab2f-4ed4-aa28-d1ee2e618004.jpg)

On further trying today, it was the `"python.analysis.diagnosticMode": "openFilesOnly"` after all!  On my User tab setting, it was set to workspace, whilst in Remote and Workspace tab settings, it was "openFilesOnly".  Once it was synced across the board to "openFilesOnly", it stopped analyzing everything.  Hopefully it helps anyone facing same issue.

**Comment by Spitfire1900** [comment] 2021-09-08 17:37
Unfortunately "python.analysis.diagnosticMode": "openFilesOnly" isn't a valid workaround. If you're entire project is error free setting it to `workspace` detects api breakages across modules to the file you're editing.
