### ISSUE TITLE
docstring of google format cannot be displayed properly

### ISSUE THREAD

**Issue by MikuAndRabbit** [microsoft/pylance-release#4339] opened 2023-05-10 04:01 UTC
Type: <b>Bug</b>

As shown in the figure below, the `Args` part in docstring (google format) of the function is not displayed properly. Normally, each parameter should have its own line, but here all of them are shown on one line.

![issue](https://github.com/microsoft/vscode-python/assets/52323820/991ec560-b79a-4b24-8225-f4bb2850c964)

Extension version: 2023.9.11292255
VS Code version: Code 1.78.1 (Universal) (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:57:42.343Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (34.76GB free)|
|Process Argv|--crash-reporter-id 47054ebe-a07c-4e57-a6e2-92540d051a25|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2023-05-10 16:28
Thanks for the issue. 

This is a dupe of #4317

**Closed by rchiodo** 2023-05-10 16:28 UTC
Labels: triage-needed
