### ISSUE TITLE
False "variable is not accessed" message

### ISSUE THREAD

**Issue by tweakimp** [microsoft/pylance-release#107] opened 2020-07-14 15:42 UTC
## Environment data
-   Language Server version: Pylance language server 2020.7.1
-   OS and version: Windows 10 64bit
-   Python version: 3.8.2

## Expected behaviour

No message at variable `string` in line 6, just like in line 13.

## Actual behaviour

Variable `msg` in Test.func is marked as `"string" is not accessed`, while it is clearly being accessed in the next line.

## Code Snippet / Additional information
```python
class Test:
    def func(self):
        try:
            1 / 0
        except ZeroDivisionError as exc:
            string = "A string"  # pylance: "string" is not accessed
            raise exc(string)


try:
    1 / 0
except ZeroDivisionError as exc:
    string = "A string"  # No pylance message here (?)
    raise exc(string)
```

**Comment by erictraut** [comment] 2020-07-14 17:56
Thanks for the bug report.

If you turn on the type checker (i.e. set "python.analysis.typeCheckMode" to "basic"), you'll see that Pylance finds a bug in the above code. The variable `exc` contains an instance of `ZeroDivisionError`, which is not callable. It appears that your code assumes that `exc` refers to the `ZeroDivisionError` class, which it doesn't. So your code will crash (i.e. generate another exception) within your exception handler.

That said, Pylance should not mark the symbol `string` as unreferenced.

**Comment by erictraut** [comment] 2020-07-14 18:05
This will be fixed in the next version of Pylance & Pyright.

**Comment by tweakimp** [comment] 2020-07-14 18:25
Thank you for your fast reply.
While you are right, the code was not working as intended, why was that only a problem in the class version, not also in the other one?

If I use the following code, pylance does not think that `string` is not accessed.
```python
class Test:
    def func(self):
        try:
            1 / 0
        except ZeroDivisionError as exc:
            string = "A string"
            raise exc.__class__(string)
```

**Comment by erictraut** [comment] 2020-07-14 18:41
The problem wasn't reported for the second version because Pylance assumes that symbols within the module-level scope should never be marked as "not accessed" because they might be improted by other modules. The exception to this rule is if the name of the symbol starts with an underscore, which tells Pylance that it should be private to the module. So if you had named your variable `_string` rather than `string`, you would have seen the same behavior for both examples.

**Comment by jakebailey** [comment] 2020-07-15 22:50
This issue has been fixed in version 2020.7.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202072-15-july-2020

**Closed by jakebailey** 2020-07-15 22:50 UTC
Labels: bug, fixed in next version

**Comment by smuuf** [comment] 2020-08-07 10:52
I'd like to report this/similar issue with version `2020.8.0`.

![obrazek](https://user-images.githubusercontent.com/6860713/89638685-8543a980-d8ac-11ea-9495-4e1ceb72a5a1.png)

## Code to reproduce
```python
class WhateverClass:

    def some_method(self):
        some_variable = 123

        return type('Whatever', (object,), {
            'whatever': some_variable,
        })
```

## Pylance version
```
[Info  - 11:07:14 AM] Pylance language server 2020.8.0 (pyright 4b16a648) starting
```

## Using

`PyPy 7.3.1` in WSL1

```
Python 3.6.9 (7.3.1+dfsg-4~ppa2~ubuntu18.04, Apr 30 2020, 20:59:10)
[PyPy 7.3.1 with GCC 7.5.0]
```

**Comment by erictraut** [comment] 2020-08-07 14:26
@smuuf, thanks for the bug report. This is a different issue that is specific to the `type` call. It will be fixed in the next version of Pylance.
