### ISSUE TITLE
Hover tooltips (local vs web)

### ISSUE THREAD

**Issue by danchitnis** [microsoft/pylance-release#5081] opened 2023-11-03 19:59 UTC
Hello, I have noticed the web version of VScode (i.e. GitHub.dev) doesn't show tooltips and "Go to Definitions" for Python variables. This works fine in the local version. I have attached the screen recording below. Is there a known reason for this?

https://github.com/microsoft/pylance-release/assets/17278902/aaffebdc-6753-4402-a322-857f785cae00

## Python test code

```python
import matplotlib.pyplot as plt
import numpy as np

# Assume t and y1 are your data
t = np.linspace(-10, 10, 400)
y1 = np.sin(t)

# Create a figure and axis object
fig, ax = plt.subplots()

# Plot your data
ax.plot(t, y1)

# Turn on the grid
ax.grid(True)

# Draw horizontal and vertical lines at y=0 and x=0
ax.axhline(y=0, color='black', linewidth=0.5)
ax.axvline(x=0, color='black', linewidth=0.5)

# Show the plot
plt.show()
```

tagging @isEmmanuelOlowe

**Comment by debonte** [comment] 2023-12-01 00:28
My guess is that you are using different versions of `matplotlib` in these two cases. I'm able to reproduce both behaviors in the desktop version of VS Code. If I use `matplotlib` `3.7.3`, I'm able to "go to def" on `axhline`. If I use `3.8.x`, I can't.

The difference is that starting with `3.8.0`, `matplotlib` is a `py.typed` library (there's a `py.typed` file in the root of the install) and we therefore honor the inline types in the library.

In `3.8.x`, the inline type annotation for `plt.subplots` states that the return type is `tuple[Figure, Any]`. Therefore, the type of `ax` is `Any`, and we have no idea what methods or attributes exist on it.

In `3.7.3`, since it's not a `py.typed` library, we use the `matplotlib` stubs that Pylance ships with. These stubs state that the return type of `plt.subplots` is `tuple[Figure, Axes]`. Therefore, the type of `ax` is `Axes`, and we recognize that `axhline` is a method that exists on that type.

When using `3.8.x`, you could work around this issue by putting an explicit annotation on `ax`:

```
from matplotlib.axes import Axes
...
fig, ax = plt.subplots()
ax: Axes
```

There's a `matplotlib` issue about this: https://github.com/matplotlib/matplotlib/issues/27025. So hopefully they'll improve the typing of `plt.subplots` as it seems to be confusing a lot of people.

I'm closing this issue because I'm pretty confident this is the cause of the behavior you are seeing. Let me know if you disagree.

**Closed by debonte** 2023-12-01 00:28 UTC
Labels: needs repro
