### ISSUE TITLE
Type checking during cross-versioned import

### ISSUE THREAD

**Issue by Vlod-github** [microsoft/pylance-release#4455] opened 2023-06-06 09:06 UTC
## Environment data
-   Language Server version: v2023.5.51
-   Windows 10
-   Python version : 3.11

I'm trying to import StrEnum, but older versions of python don't have it. So I'm writing the following code as a stub.
```
from enum import Enum
try:
    from enum import StrEnum
except ImportError:
    class StrEnum(str, Enum):
        value: str

T = TypeVar('T', bound=StrEnum)
R = TypeVar('R')


def get_valid_enum(cls_enum: Type[T], value: Union[T, str, None], default: R) -> Union[T, R]:
    if isinstance(value, cls_enum):
        return value
    return cls_enum.__dict__['_value2member_map_'].get(value, default)


class FontWeight(StrEnum):
    FADE = "fade"
    ROTATION = "rotation"
    SCALE = "scale"


get_valid_enum(FontWeight, FontWeight.FADE, FontWeight.FADE)
```
The error occurs when I import StrEnum from another file and create a class there. In this case an error occurs: Type "Type[FontWeight]" cannot be assigned to type "Type[T@get_valid_enum]".
```
from test_module import get_valid_enum, StrEnum


class FontWeight(StrEnum):
    FADE = "fade"
    ROTATION = "rotation"
    SCALE = "scale"


get_valid_enum(FontWeight, FontWeight.FADE, FontWeight.FADE)
```
To be honest I managed to overcome this problem by using MyStrEnum, but it seems to me that this is a crutch and cross-version import should work
```
try:
    from enum import StrEnum
except ImportError:
    class StrEnum(str, Enum):
        value: str

MyStrEnum = StrEnum
```

**Comment by erictraut** [comment] 2023-06-06 15:52
Dynamic runtime constructs like `try` statements create ambiguities for static analysis tools like pyright (the type checker upon which pylance is built). You are, in effect, defining the symbol `StrEnum` twice in incompatible ways.

Some background and terminology... Pyright differentiates between "type declarations" and "value assignments". A type declaration declares the type of a symbol, effectively declaring what value types it can be assigned. A symbol can have only one type declaration, but it can have multiple value assignments. Examples of type declarations include variable type annotations (e.g. `x: int`), `def` statements and `class` statements. A value assignment assigns a value to a symbol, and pyright verifies that the assigned type conforms to the declared type. For example, `x = ""` will generate a type violation error if `x` is declared as type `int`. For more details about type declarations and value assignments, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts).

In your code sample, you are declaring the type of the symbol `StrEnum` with the `class` statement in the `except` clause. You're also assigning it a value using an `import` statement in the `try` clause. The value you're assigning it is incompatible with the declared type. If you have type checking enabled, you'll notice that pyright emits an error telling you about this type violation.

Within the file `test_module.py`, pyright assumes that the type of `StrEnum` is the declared type — i.e. the `class` statement in the `except` clause.

The technique you're using to conditionally import a symbol within a `try` block is used in several popular libraries, and pyright includes some special logic to handle this case when the symbol is imported from these libraries by app code. In this case, pyright ignores the type declaration in the `except` clause and uses the `try` statement. Without this "hack", these libraries would not work correctly with pyright.

In short, the behavior you're seeing is "as designed", although I admit that the behavior appears inconsistent here. Removing this inconsistency isn't an option because it would break the use of various libraries.

You've already identified one potential way to fix this in your code. Here are a couple of other options that you may find more palatable.

The following code declares a private class symbol called `_StrEnum` (note the underscore) and then assigns this to a variable called `StrEnum`. Since `StrEnum` doesn't have a declaration, its type is inferred based on assignments.

```python
try:
    from enum import StrEnum
except ImportError:

    class _StrEnum(str, Enum):
        value: str

    StrEnum = _StrEnum
```

Alternatively, you could eliminate the `try` statement and replace it with a simple version check. This is the technique I personally prefer. Because `enum` is part of the stdlib, the `StrEnum` symbol is guaranteed to be present if you're using Python 3.11 or newer. Static type checkers are required to understand `sys.version_info` checks (as per PEP 484) and ignore code that is unreachable based on these checks.

```python
import sys

if sys.version_info >= (3, 11):
    from enum import StrEnum
else:
    class StrEnum(str, Enum):
        value: str
```

**Closed** 2023-06-06 15:55 UTC
Labels: reference, by design

**Comment by Vlod-github** [comment] 2023-06-07 07:06
@erictraut, I also like the `sys.version_info` option, thank you very much for the detailed explanation
