### ISSUE TITLE
Import "django.urls" could not be resolved from sourcePylance (reportMissingModuleSource)

### ISSUE THREAD

**Issue by alex1the1great** [microsoft/pylance-release#207] opened 2020-08-07 02:27 UTC
## Environment data

-   Language Server version: Pylance
-   OS and version: Windows 10 Home
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment] 2020-08-07 17:52
Hi Alex, thanks for the bug report. Would you please verify that you have the right interpreter and Django installed?
thanks!

**Comment by alex1the1great** [comment] 2020-08-08 01:54
# 1
Now it is not showing the error (reportMissingModuleSource). It is working fine.

# 2 
"python.languageServer": "Pylance",

Defines type of the language server.
Value is not accepted. Valid values: "Jedi", "Microsoft", "None".(1)

Vscode not taking Pylance a valid language server. I have already install Pylance extension.

**Comment by jakebailey** [comment] 2020-08-08 07:09
See #16; it will be fixed in the next Python extension release, which should be in a week or so. You can try their insiders if it bugs you.

Since the warning is gone, I'll close this.

**Closed by jakebailey** 2020-08-08 07:09 UTC
Labels: waiting for info

**Comment by amanagarwal-x** [comment] 2021-04-08 10:03
This still seems to be a problem for me

**Comment by jakebailey** [comment] 2021-04-08 17:14
@amanagarwal-x Could you please file a new issue with a reproduction? This issue is pretty old (and should be fixed); I doubt the cause is the same.

**Comment by khakhalifa** [comment] 2021-06-30 04:19
Thats because you have not chosen your bath correctly, 
type : pipenv --venv 
then it will show you where your virtual env installed, check where the packages are installed in your env, and then type what comes to you from the shell \scripts or whatever\ python , and the packages will work

**Comment by alexb7217** [comment] 2021-08-05 14:33
Sorry to add to an old issue. I found some VS Code documentation helpful in resolving this.

 I needed to set up my python interpreter for my local dev environment:

[https://code.visualstudio.com/docs/python/tutorial-django](https://code.visualstudio.com/docs/python/tutorial-django)

Just in case future people wander here

**Comment by PoSihDun** [comment] 2021-09-17 18:54
I am a little late to reply. I had the same issue this morning, and it was solved right away. I would open the folder that held my Django app instead of the folder that holds my Django app and virtual environment.

**Comment by aman-quartic** [comment] 2021-09-19 05:34
@PoSihDun Thanks man, I had figured it out a few days later.

**Comment by Damian-lab** [comment] 2022-01-06 07:28
changed my intepreter and it worked

**Comment by Danie12345** [comment] 2022-09-24 16:27
If this "didn't work" for you yet, you may be using a workspace  As previously mentioned, a change in your interpreter will make it work. In my case I was on a workspace with a different interpreter so changing it required a few more steps.
1. Close the VS Code instance.
2. Open the project manually via cmd or file explorer.
3. Change the interpreter to the correct one you need.
4. Create a new workspace for it (if you so wish it).
Now you can just open that workspace and it will automatically point to the right venv in your project.

**Comment by StanislavNemytov** [comment] 2023-02-18 18:04
How I solved this problem:
I created venv in the current project folder and everything worked

**Comment by irufaan2** [comment] 2023-04-25 19:24
How I solved this problem:
change the Python Interpreter to the virtual environment path in which Django is installed from VS code.
Veiw>>Command Palatte...>>Python: Select Interpreter

**Comment by Cyrille-18** [comment] 2023-12-27 10:03
> Comment j'ai résolu ce problème : remplacez l'interpréteur Python par le chemin de l'environnement virtuel dans lequel Django est installé à partir du code VS. Voir>>Command Palatte...>>Python : sélectionner un interprète

worked for me thanks !
