### ISSUE TITLE
LSP opens canonical path after modifications

### ISSUE THREAD

**Issue by alex-ong** [microsoft/pylance-release#5065] opened 2023-11-01 00:37 UTC
## Environment data
I don't have a `D:/` drive, so i use `C:/drive_d` and the following registry entry:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\DOS Devices]
"D:"="\\??\\C:\\DRIVE_D"
```

-   Language Server version: v2023.10.53
-   OS and version: Win10 22H2 19045.3570
-   Python version (& distribution if applicable, e.g. Anaconda): N/A, All versions

## Code Snippet
When i open a file in `D:\`  (e.g.) `D:\some_project\test.py`, and do a simple rename, it does the modifications on `C:\Drive_d\some_project\test.py` and then opens it. Since VScode thinks they are two different files, it opens a new tab.

```python
def simple_function(argument):
    argument = argument * 2
    return argument
```

Then use F2 to rename,
## Repro Steps
1. Mount a drive to a folder
2. Open the project from that drive
3. Do a rename

## Expected behavior
The file is modified, and then "reopened" or "refreshed" using the same path.

## Actual behavior
A new file is opened from the "real" path

**Comment by debonte** [comment] 2023-11-01 01:05
Duplicate of https://github.com/microsoft/pylance-release/issues/5030

**Closed by debonte** 2023-11-01 01:05 UTC
Labels: needs repro
