### ISSUE TITLE
Python intellisense is showing nonsense

### ISSUE THREAD

**Issue by zhong-yy** [microsoft/pylance-release#4105] opened 2023-03-18 04:50 UTC
## Environment data

-   Language Server version: v2023.3.20
-   OS and version: ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16 (miniconda)

## Code Snippet

```python
x=[1,2,3]
x[]
```

## Repro Steps

1. New a py file
2. Type `x=[1,2,3]`
3. Type `x[`

## Expected behavior

Do not give any suggestions ( or only intergers for list, keywords for dict)

## Actual behavior

Showing a lot of irrelevant  suggestions
![Screenshot from 2023-03-17 17-31-43](https://user-images.githubusercontent.com/38816011/226085336-aa5a5ef7-f3f9-4f28-8e14-ae4fac4dc015.png)

**Comment by debonte** [comment] 2023-03-18 16:17
Duplicate of https://github.com/microsoft/pylance-release/discussions/2599

**Closed by debonte** 2023-03-18 16:17 UTC
Labels: triage-needed

**Comment by debonte** [comment] 2023-03-18 17:08
@zhong-yy , btw, you should go up vote that discussion item, since we use vote counts to help prioritize enhancements.
