### ISSUE TITLE
(again...) No Syntax Highlighting for python

### ISSUE THREAD

**Issue by Juliandev02** [microsoft/pylance-release#4877] opened 2023-09-22 20:09 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.2
- OS Version: Windows 11 22621.2283

Again i have no syntax highlighting after updating vscode and some extensions. 
It looks like this: 
![image](https://github.com/microsoft/vscode/assets/81520713/29d8c917-6510-45c2-8f1d-a83a15d842b3)

Yes, I activated Pylance. And Yes it is selected. 
Also, i enabled this: `"editor.semanticHighlighting.enabled": true`
Restarted VSCode, nothing changed. Reinstalled Python Extension, nothing changed. 
I've opened this session on a network folder. But i added it to the "allowed" paths 
I'm tired of this.

**Comment by rchiodo** [comment] 2023-09-26 18:45
This should be a dupe of https://github.com/microsoft/pylance-release/issues/4862.

**Closed by rchiodo** 2023-09-26 18:45 UTC
Labels: triage-needed, needs repro

**Comment by Juliandev02** [comment] 2023-09-26 19:23
> My coworkers and I are struggling with the same issue. Here's bit of a breakdown of what syntax highlights are working and what aren't:
> 
> ![image](https://user-images.githubusercontent.com/72784952/270756349-122d233c-5170-4384-b8aa-5de21a13d614.png)
> 
> I also have the problem persist irrespective of enabled extensions.
> 
> Some more info: this seems to only be the case on network drives. Both my citrix environment and local machine have the same problem. However, opening local workspaces and files from my local machine is fine.
> 
> On both: VS Code 1.82.2 Windows 10

yeah. Just downgrade your pylance version.
