### ISSUE TITLE
Folds only argument list, not the entire function

### ISSUE THREAD

**Issue by eldarkurtic** [microsoft/pylance-release#934] opened 2020-12-04 13:41 UTC
- VSCode Version: 1.51.1
- OS Version: Big Sur 11.0.1 (Darwin x64 20.1.0)
- ms-python: v2020.11.371526539

VSCode folds only the argument list when closing parentheses have smaller indentation than the argument list.
Expected behavior: folds the entire function body.

![folding](https://user-images.githubusercontent.com/8884008/101170358-a0e27500-363e-11eb-94a2-605fb8e18775.gif)

**Comment by jakebailey** [comment] 2021-02-10 22:59
Duplicate of #372; I believe the folding behavior seen in the gif above is just VS Code's default.

(Similar is #266.)

**Closed by jakebailey** 2021-02-10 22:59 UTC
Labels: triage
