### ISSUE TITLE
Finding references analyzes excluded files

### ISSUE THREAD

**Issue by jahan01** [microsoft/pylance-release#123] opened 2020-07-16 03:39 UTC
## Environment data

-   Language Server version: 2020.7.2
-   OS and version: Mac 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.6

## Expected behaviour

When `Find references` is triggered search is only done files which not are excluded in the workspace

## Actual behaviour

When `Find references` is triggered scanning is also done on files which are excluded by `files.exclude`

**Comment by erictraut** [comment] 2020-07-16 14:52
Thanks for the suggestion.

The `files.exclude` setting is designed to hide files in the file browser within VS Code. I don't think it's intended to exclude files from language services. Other language service providers don't appear to honor the `files.exclude` setting. For example, the TypeScript LS returns references in files that are hidden by `files.exclude`. When you click on such a reference, VS Code temporarily "unhides" the file in the left panel and opens the file in a tab.

Could you explain your use case a bit more? Perhaps we can offer another way to accomplish what you're trying to do.

**Comment by jahan01** [comment] 2020-07-16 15:14
@erictraut Actually in my use case there are no references in the folders excluded. There couple of thousands python files in those excluded folders and find references just takes forever to scan them. In fact I was not able see any reference in this particular project even waiting for good 15 min.

Jedi or old MS Python language server doesn't have this issue.

It could be the case of slow scanning or having to scan the entire workspace for everytime when find references.

Anyways feel free to close this if you are intending to support it.

**Comment by erictraut** [comment] 2020-07-16 15:23
OK, thanks for the additional details. Let's see if we can figure out what's causing the performance issue. Even with thousands of python source files, I wouldn't expect "find references" to take more than a few seconds. So something is going on here that we should understand better.

Could you look in the Output window and paste logs that might be of relevance? Here are the instructions from the bug template:
- Select "View: Toggle Output" from the command palette (Ctrl+Shift+P on Windows/Linux, Command+Shift+P on macOS), then select "Python Language Server" in the dropdown on the right. Look for the line Pylance Language Server version X in the console.

Enable trace logging by adding "python.analysis.logLevel": "Trace" to your settings.json configuration file.

Adding this will cause a large amount of info to be printed to the Python output panel. This should not be left long term, as the performance impact of the logging is significant.

**Comment by jakebailey** [comment] 2020-07-16 15:25
FWIW MPLS does not respect this value for references either, only for workspace symbol searches. So I'd also be interested in finding the bug that's making it scan too heavily as well.

**Comment by jahan01** [comment] 2020-07-16 15:51
@erictraut: actually it turns out I have way more than couple of thousands. its around 4-6K python source files and analysis gets stuck around 10575th line in the log (there approximately 3 lines in log per file - `parsing`, `binding`, in some cases `checking` and `analyzing`).

Most of file gets analysed under 10ms, with few files taking more than 2000ms. I can pull up the histogram if you are really interested.

We are sort of working in "mono" repo, where in the excluded folder contains legacy code and site packages, which is never imported by current workspace code.

> FWIW MPLS does not respect this value for references either, only for workspace symbol searches. So I'd also be interested in finding the bug that's making it scan too heavily as well.

If I understand correctly old LS builds indexes on based on open python file and recursively navigates to sources that are reachable. If I open a code which was not reachable by the 1st file, I can see indexes building again. So the code in excluded folder is never indexed. And references are always pulled from this index, not scanned on every request. Anyways you guys should know it best.

**Comment by erictraut** [comment] 2020-07-16 16:12
My team also has a mono repo with somewhere between 3-4K python files, and "find references" completes after several seconds. It sounds like your source base is slightly bigger, but that shouldn't be a problem.

My hypothesis is that there's a particular file in your source base that is triggering a bug in the analyzer — something that breaks a performance or scalability assumption. If you look at your logs, does it appear to always stop after the same file? You mentioned that it stopped after the 10575th log line. Is that consistently the same file? If so, is there something unusual or unique about the contents of that file?

Thanks for your help with this!

**Comment by erictraut** [comment] 2020-07-16 17:05
There is a mechanism for excluding folders/globs, but it's not currently exposed as a VS Code setting. You would need to use the pyrightconfig.json config file, which is documented [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md). Go to the bottom of that page for an example that shows how to use the "exclude" config entry.

**Comment by jahan01** [comment] 2020-07-16 18:03
thanks @erictraut, after exclusion finding references is working perfectly fine

**Comment by ThiefMaster** [comment] 2020-08-18 10:46
Having the `build` dir included is very annoying. It's basically a duplicate of my code and a place I NEVER want to look at. Sure, I could delete it after building a wheel, but that's not the point...

![image](https://user-images.githubusercontent.com/179599/90504069-c65f7780-e150-11ea-8dd5-824850290b6d.png)

**Comment by erictraut** [comment] 2020-08-18 14:42
@ThiefMaster, have you added a "pyrightconfig.json" config file and added your build directory to the "exclude" section as suggested above? That should properly exclude it from symbol lookups. Let us know if it doesn't.

**Comment by ThiefMaster** [comment] 2020-08-18 14:43
didn't notice that comment, will give it a try!

**Comment by koaleksa** [comment] 2020-12-18 22:20
Just to confirm, adding excludes to pyrightconfig.json actually works.

This has been a major pain for me for quite some time and I've been waiting for vscode to resolve the issue here: https://github.com/microsoft/vscode/issues/46718

Thank you @erictraut for pointing this out! 👍 This makes a huge difference for large codebases.

**Comment by SowingSadness** [comment] 2021-01-24 23:13
@erictraut  `Find References` in all others languages works according with `search.exclude`

TypeScript example:
![image](https://user-images.githubusercontent.com/576443/105646778-d8d59e00-5eb2-11eb-8610-47b158bb26e3.png)

Pylance example:
![image](https://user-images.githubusercontent.com/576443/105646685-492fef80-5eb2-11eb-98d9-3438ce800523.png)

**Comment by untrix** [comment] 2021-02-09 22:44
pyrightconfig.json works, thanks.

However, this feature is certainly needed IMO in vscode-settings. In my use-case there is a run-logs folder to which wandb (weights and biases) copies a few python files when I execute a ML training run as a snapshot of the code that was run (it also saves diffs of files not committed to git). Over time, the folder ends up with 10s or 100s of run directories. However, it is in my .gitignore file, so these do not get checked into git. However, when I execute find-references, references from all these run folders show up as well and many times I inadvertently end-up editing these files. I have edited all possible 'exclude' settings in both User and Workspace, but those files keep showing up. setting up a pyrightconfig.json in the workspace folder works but it would be much better if the setting were exposed in the main IDE or within pylance.

**Comment by ehendrix23** [comment] 2021-02-26 21:57
Just want to add I ran into same issue. Would be good to have this within settings IDE.

**Comment by acnebs** [comment] 2021-03-09 17:06
+1 to exposing the pyright config in VSCode settings, maybe like this:

```json
{
  "python.analysis.pyrightConfig": {
    "exclude": [
      "**/dir"
    ]
}
```

**Comment by casassg** [comment] 2021-03-12 03:34
Same here, would be nice to have a way to surface this setting. Respecting `search.exclude` would also work! Due to monorepo, currently it's impossible to use PyLance (trying to use the pyrightconfig.json to see if I can manage it to make it work)

**Comment by nikiask** [comment] 2021-03-31 01:57
Adding excludes to pyrightconfig.json worked for me. For those who have venv's in their project directory, make sure to add that as well, otherwise find references will take forever. Pylance excludes venv directories by default, but when you add your own directories it doesn't merge them with pylance's defaults.

**Comment by picrots** [comment] 2021-07-07 12:22
Fantastic!
Using `pyrightconfig.json` file and monitoring trace logs for Python Language Server helped me find the directory that causes the issue.
When I excluded that folder it becomes fast again. 
The weird part is that trying to narrow down the search to find the exact file that cause the issue was unsuccessful. Maybe the issue is not caused by single file but a combination of conditions that certain files create.

**Comment by jakebailey** [comment] 2021-08-31 22:46
It seems as though everything has converged here on `exclude` being the option that fixes things, and that we should get that into a VS Code setting. That's #1150, so I'm going to close this issue in favor of it.

**Closed by jakebailey** 2021-08-31 22:46 UTC
Labels: needs investigation

**Comment by v3470** [comment] 2021-11-05 16:28
My problem is a bit different. When I jump to the declaration in the module of Python standard library, it still checked type for it. I tried to exclude both related path and absolute path in `search.exclude`, `pyright`'s exclude and `files.watcherExclude`, and none of them worked.
