### ISSUE TITLE
pylance is not resolving mypy comment typings

### ISSUE THREAD

**Issue by cebor** [microsoft/pylance-release#2815] opened 2022-05-15 15:13 UTC
## Environment data

-   Language Server version: 2022.5.1 
-   OS and version: macOS 12.3.1 and Windows 11 (WSL: Ubuntu 20.04)
-   Python version (& distribution if applicable, e.g. Anaconda): python3.9

## Code Snippet

```python
class A():
    def foo_a(self):
        print("foo from a")


class B():
    def foo_b(self):
        self.c = self.not_refable  # type: A
        
        self.c.foo_a() # ref does not work

```

## Repro Steps

Open Code above

## Expected behavior

Reference resolution and autocomplete works.

## Actual behavior

Currently the ref resolution and also the autocomplete feature does not work for me, if i'm using mypy comment typing. A while ago it worked fine.

**Comment by erictraut** [comment] 2022-05-15 15:21
Type comments are deprecated as of Python 3.6. Variable type annotations (see [PEP 526](https://peps.python.org/pep-0526/) for details) should be used instead.

That said, type comments for instance variables are supported by pyright (the type checker that underlies pylance). In your code sample, you are annotating the instance variable `c` to be of type `A`. But then you're assigning it a value that is a type error because the expression `not_refable` is not a valid member of class `B`. The assignment therefore narrows the type of the expression `self.c` to `Any` locally within the `foo_b` method.

For more details about type declarations and type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

So, pyright (and pylance) are working as intended in this case.

**Comment by erictraut** [comment] 2022-05-15 15:24
If you're using type annotations, you will probably find it beneficial to enable basic type checking by setting `python.analysis.typeCheckingMode` to "basic". This will highlight type consistency errors in your code.

**Comment by cebor** [comment] 2022-05-15 15:49
Ok cool and thanks that's working fine for me.

**Closed** 2022-05-15 15:49 UTC
Labels: triage
