### ISSUE TITLE
when using keyword "Type", the syntax is highlighted as white although the value is type (should be green by default)

### ISSUE THREAD

**Issue by ManiMozaffar** [microsoft/pylance-release#6635] opened 2024-11-05 14:16 UTC
## Environment data

-   Pylance version:3.12
-   OS and version: MacOS 15 Sequoia
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0

## Code Snippet

```python
type Foo = int
# foo should be green on vscode by default, but it's not.
```

## Repro Steps

1. XXX

## Expected behavior

The highlighted syntax should be green by default

## Actual behavior

It is highlighted as white

## Logs

```
XXX
```

**Comment by debonte** [comment] 2024-11-05 15:37
Duplicate of https://github.com/microsoft/pylance-release/issues/5541. See https://github.com/microsoft/pylance-release/issues/5824#issuecomment-2457476750 for the status of this class of issues.

**Closed by debonte** 2024-11-05 15:37 UTC
Labels: needs repro
