### ISSUE TITLE
Don't highlight literals

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#172] opened 2020-07-24 19:37 UTC
-   Language Server version: 2020.7.3
-   OS and version: Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.7 

![image](https://user-images.githubusercontent.com/26390254/88428706-a1563e00-ce0a-11ea-88fc-0c1a8f396932.png)

**Comment by erictraut** [comment] 2020-07-24 19:41
Thanks for submitting a bug report.

What behavior do you consider a bug?

Highlighting a string when you click in it is intended behavior — part of a language feature called "semantic highlighting". When you click on a string literal (or any identifier), the editor will highlight it and any other instances of it within the file. In the case of identifiers, it will also distinguish between writes and reads of that symbol, providing subtly different color hints for each.

**Comment by jakebailey** [comment] 2020-07-24 19:45
In MPLS, we disabled any sort of highlighting inside literals (sans fstrings) as they were a bit distracting, so this is probably a behavior difference from that.

**Comment by erictraut** [comment] 2020-07-24 19:47
We could consider doing there here too, but it would be inconsistent with other language servers.

**Comment by jakebailey** [comment] 2020-07-24 19:51
I don't think that's entirely true. I tested Go and TypeScript, and neither do this.

**Comment by erictraut** [comment] 2020-07-24 19:54
TypeScript's semantic highlight feature does highlight string literals. It doesn't include the quotes in the selection, but I decided when implementing the Python version that it made sense to include the quotes and the string type that precedes the quote.

**Comment by byehack** [comment] 2020-07-24 19:58
> Thanks for submitting a bug report.
> 
> What behavior do you consider a bug?
> 
> Highlighting a string when you click in it is intended behavior — part of a language feature called "semantic highlighting". When you click on a string literal (or any identifier), the editor will highlight it and any other instances of it within the file. In the case of identifiers, it will also distinguish between writes and reads of that symbol, providing subtly different color hints for each.

when i disabled pylance:

![image](https://user-images.githubusercontent.com/26390254/88430375-99e46400-ce0d-11ea-90fd-e818ac9a030e.png)

**Comment by jakebailey** [comment] 2020-07-24 20:01
Go differs in that literals are not types, so that's probably part of the reason they don't do it. But I was wrong about TypeScript. I had to pick a small string to get TypeScript do to it (my multi-line example did not have this behavior).

But, I still don't think highlighting literals like this is very useful. I'd rather we only did it to actual bound names.

@byehack For reference, that is VS Code's default behavior where it doesn't know anything but the words in the file. If you were to say write:

```python
test = 1234
"this is a test"
```

And then selected `test`, it's probably going to highlight it in both places.

The difference here is that we are highlighting the string literal as its own thing.

**Comment by byehack** [comment] 2020-07-24 20:08
![image](https://user-images.githubusercontent.com/26390254/88431003-b6cd6700-ce0e-11ea-962b-48e1f55161fd.png)


after disable pylance:

![image](https://user-images.githubusercontent.com/26390254/88431100-e5e3d880-ce0e-11ea-978e-829a855aa8fd.png)

**Comment by rwols** [comment] 2020-07-30 20:51
> But, I still don't think highlighting literals like this is very useful. I'd rather we only did it to actual bound names.

Agreed. Just to give another example, clangd also doesn't highlight literals.

**Comment by rholland** [comment] 2020-09-20 04:47
I agree that it is distracting.  I prefer that it can optionally be turned off.

**Comment by jakebailey** [comment] 2020-09-23 23:19
This issue has been fixed in version 2020.9.6, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202096-23-september-2020

**Closed by jakebailey** 2020-09-23 23:19 UTC
Labels: enhancement, fixed in next version
