### ISSUE TITLE
Enums with __new__ and __init__ method are not properly checked

### ISSUE THREAD

**Issue by schperplata** [microsoft/pylance-release#1483] opened 2021-06-22 11:44 UTC
Issue Type: <b>Bug</b>

I have a following working code, which VSC/Pylance/Pyright does not seem to understand and as a consequence, autocomplete does not work and error squiggles are everywhere.
```python
import enum

class Blocks(enum.Enum):
    ONE = (0, "Blue", "The one on the corner.")
    TWO = (1, "Pink", "The ugly one.")

    def __new__(cls, streetNumber: int, color: str, description: str):
        obj = object.__new__(cls)
        obj._value_ = streetNumber

        obj.streetNumber = streetNumber
        obj.color = color
        obj.description = description

        return obj

def main():
    theUglyBlock = Blocks(1)
    print(theUglyBlock)
    print(theUglyBlock.description)

if __name__ == "__main__":
    main()
```
Although it does show correct statements on execution:
```
Blocks.TWO
The ugly one.
```
... IDE shows:
![image](https://user-images.githubusercontent.com/8736111/122918628-9d56d700-d35f-11eb-835e-b5db68e402e3.png)
and:
![image](https://user-images.githubusercontent.com/8736111/122918679-a8116c00-d35f-11eb-8161-ec215f3b27a0.png)

Now, is this an unhandled scenario in VSC extensions or I don't understand something and it is as expected?

Extension version: 2021.6.2
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.04GB free)|
|Process Argv|--crash-reporter-id d9d15ca2-a021-4dcd-a140-bb0adc228360|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
vscextlang:30322306
binariesv615cf:30323120

```

</details>

**Comment by erictraut** [comment] 2021-06-22 14:38
This is a duplicate of https://github.com/microsoft/pyright/issues/1751, which we decided not to address.

**Closed** 2021-06-22 17:46 UTC
Labels: triage
