### ISSUE TITLE
Pylance doesn't respect `__all__` in imports

### ISSUE THREAD

**Issue by stolarczyk** [microsoft/pylance-release#1277] opened 2021-05-13 13:08 UTC
The following is a valid setup, but Pylance marks the variables as undefined:

const.py submodule:

```python
FOO = 1
BAR = 2

__all__ = ["FOO", "BAR"]
```

file.py submodule:

```python
from .const import *

FOO # Pylance marks as not defined

**Comment by erictraut** [comment] 2021-05-13 14:50
I'm not able to repro the problem as defined above. Could someone else on the pylance team give it a try as well? Perhaps I'm missing something here.

**Comment by bschnurr** [comment] 2021-05-13 16:15
Wasn't able to repro either. What is your folder structure?

**Comment by jakebailey** [comment] 2021-05-13 19:34
Yeah; I think we need some more info for this. Is this a reproduction on a larger project that we could look at?

**Comment by stolarczyk** [comment] 2021-05-14 13:09
thank you all for the prompt replies. Can't explain that, but either restarting VSCode or reinstalling the plugin (I did both) helped.

**Comment by stolarczyk** [comment] 2021-05-19 13:50
I take it back, it experienced this again. I have constructed a minimal example this time: [example_python_package.tar.gz](https://github.com/microsoft/pylance-release/files/6509202/example_python_package.tar.gz)

That's what I see in vscode:

![image](https://user-images.githubusercontent.com/22797900/118824119-94b64100-b887-11eb-8ea1-34836445aada.png)


But consts imports seem to work as I expected:
```python
Python 3.9.5 (default, May  4 2021, 03:36:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from packagename import MyClass

In [2]: mc = MyClass()

In [3]: print(mc)
fav: ['FOO', 'BAR']
foo;bar;baz
```

**Comment by erictraut** [comment] 2021-06-24 22:29
In your example, you're using an expression form to compute `__all__` that is not supported by pylance or other static type checkers.

```python
__all__ = FAV_CONSTS + ["BAZ", "FAV_CONSTS"]
```

The supported forms that were agreed upon by Python type checkers is documented [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface).

If you change your code to one of the following, it will work:
```python
__all__ = ["FOO", "BAR", "BAZ", "FAV_CONSTS"]
```

or 

```python
__all__ = ["FOO", "BAR"]
__all__.extend(["BAZ", "FAV_CONSTS"])
```

**Comment by rayzchen** [comment] 2021-07-06 17:57
I made a module called `pyunity` and in the `__init__.py`, I have a gigantic slab of code that defines `__all__`. However, all the submodules in `pyunity` are `.pyd` files, so no classes are actually loaded. However, they are defined in `__all__`, and do exist in the `.pyd` files, but i guess its just because pylance doesnt load C extensions. How can I make pylance not think that I have missing imports that actually exist and are in `__all__`?

`__all__` in my module:
![image](https://user-images.githubusercontent.com/54078384/124645761-ba28f980-de8b-11eb-8a2f-519ca069724c.png)

`Behaviour` is not imported:
![image](https://user-images.githubusercontent.com/54078384/124645725-ada4a100-de8b-11eb-9ac5-0b87eed672f7.png)

`Behaviour` does exist:
![image](https://user-images.githubusercontent.com/54078384/124645825-cdd46000-de8b-11eb-8578-0f54b2f6c58e.png)

Steps to reproduce (if needed):
Install wheel from this build job (https://ci.appveyor.com/project/rayzchen/pyunity/builds/39889374)
Paste this code
```python
from pyunity import *

class Rotator(Behaviour):
    def Update(self, dt):
        self.transform.eulerAngles += Vector3(0, 90, 135) * dt
```
Click `Behaviour`
![image](https://user-images.githubusercontent.com/54078384/124646007-0411df80-de8c-11eb-8772-56c9a864dd06.png)

**Comment by jakebailey** [comment] 2021-07-06 18:18
@rayzchen I think what you're describing is different than the original issue, though similar.

Normally, the solution here would be that the compiled modules themselves need stubs, then we analyze those and the variables are no longer undefined.

I don't think simply including things in `__all__` means we declare them, though that could be a thought (if `__all__` lists something we can't find, allow it as an `Unknown` externally), but I'd be more inclined to get the library fully stubbed out.

**Comment by jakebailey** [comment] 2021-09-23 19:52
I'm going to close this, as I believe the original issue has been addressed.

@rayzchen I would open a dedicated issue for that case; i.e. if adding something to `__all__` should "declare" it.

**Closed by jakebailey** 2021-09-23 19:52 UTC
Labels: needs investigation
