### ISSUE TITLE
Type of enum is lost after value check

### ISSUE THREAD

**Issue by Avasam** [microsoft/pylance-release#2077] opened 2021-11-16 16:41 UTC
## Environment data

-   Language Server version: v2021.11.1
-   OS and version: 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Expected behaviour

After checking if a variable is a specific enum value, it should still be of that enum type

## Actual behaviour

It becomes `Never`

## Logs

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
> conda info --json
> "C:\Program Files\Python39\python.exe" ~\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
Python interpreter path: C:\Program Files\Python39\python.exe
Starting Pylance language server.
> conda --version
> "C:\Program Files\Python39\python.exe" -m flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~\Documents\Git\Auto-Split\src\AutoSplit.py
cwd: ~\Documents\Git\Auto-Split
> "C:\Program Files\Python39\python.exe" -m pylint --msg-template='{line},{column},{category},{symbol}:{msg} --reports=n --output-format=text ~\Documents\Git\Auto-Split\src\AutoSplit.py
cwd: ~\Documents\Git\Auto-Split
> "C:\Program Files\Python39\python.exe" -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty ~\Documents\Git\Auto-Split\src\AutoSplit.py
cwd: ~\Documents\Git\Auto-Split
##########Linting Output - flake8##########
##########Linting Output - pylint##########
##########Linting Output - mypy##########
```

## Code Snippet / Additional information

```python
from PyQt6.QtWidgets import QApplication, QMessageBox, QMainWindow
import sys

application = QApplication(sys.argv)

window = QMainWindow()
warning = QMessageBox.warning(
    window,
    "AutoSplit",
    "Do you want to save changes made to settings file?",
    QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No | QMessageBox.StandardButton.Cancel)

print(warning, type(warning))

if warning == QMessageBox.StandardButton.Yes:
    # Do something
    exit()
if warning == QMessageBox.StandardButton.No:
    exit()
if warning == QMessageBox.StandardButton.Cancel:
    # Do something
    pass
```
![image](https://user-images.githubusercontent.com/1350584/142027344-4e970202-6e00-4d1b-9277-40bc988788e4.png)

**Comment by erictraut** [comment] 2021-11-16 17:15
The above code references a bunch of symbols whose declarations are not provided. Could you please create a self-contained minimal sample that repros the problem?

**Comment by Avasam** [comment] 2021-11-16 18:10
> The above code references a bunch of symbols whose declarations are not provided. Could you please create a self-contained minimal sample that repros the problem?

I have updated the code snippet with a minimal example

**Comment by erictraut** [comment] 2021-11-16 19:58
Thanks for the self-contained example. I'm able to repro the problem now.

The problem is due to a bug in the `PyQt6` library. It includes a type stub file `PyQt6/QtWidgets.pyi`. Within that file, it declares the class called `StandardButton`, but it incorrectly annotates the items within the enumeration. The elements should be annotated as `int`, but they are annotated as `QMessageBox.StandardButton`.

You can see the correct way to annotate an enum within a type stub file by looking at `socket.pyi` stdlib stub in typeshed: https://github.com/python/typeshed/blob/aa2290e160f7329514b590d4f85e59ae5e35803d/stdlib/socket.pyi#L487.

If I manually fix this bug in the `QtWidgets.pyi` type stub, pylance works as you would expect.

I recommend that you report the bug to the maintainers of `PyQt6` and/or submit a PR to fix the issue.

**Comment by Avasam** [comment] 2021-11-16 20:16
Thank you for looking into it! I'll report this to PyQt6.
In the mean time I noticed that if I do my comparison using `is` instead of `==` it seems to work and I get no warning.

**Comment by heejaechang** [comment] 2021-11-17 03:27
I tried what @erictraut suggested, and it seems it still repro.

**Comment by heejaechang** [comment] 2022-04-22 00:23
I can't repro it anymore. I will close it as not repro. please re-open issue if it still repro. I dont see PyQt6 pyi changed but working as expected.

**Closed by heejaechang** 2022-04-22 00:23 UTC
Labels: needs investigation
