### ISSUE TITLE
Word and snippet completions being shown when Pylance does not have any completions

### ISSUE THREAD

**Issue by prrao87** [microsoft/pylance-release#604] opened 2020-11-12 20:17 UTC
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Linux Mint 19.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9

## Expected behaviour

When typing in import statements with aliases (e.g., `import pandas as pd` or `import numpy as np`), the autocomplete suggestion should provide the currently entered alias (`pd` or `np`) as the top choice. Then, simply pressing Enter would allow the user to continue typing in the next line.

## Actual behaviour

The currently typed alias (`pd` or `np`) is not shown at all, so pressing Enter at the end of the import statement selects the library name (`pandas` or `numpy`), which is really annoying. The only way to retain this is to press space and then enter, which results in redundant spaces at the end of each import statement.

## Code Snippet / Additional information

```python
import pandas as pd
import numpy as np
```
![pylance](https://user-images.githubusercontent.com/35005448/98991558-f9b86500-24f9-11eb-8d2d-a1dad3568f54.gif)

**Comment by jakebailey** [comment] 2020-11-12 20:32
So, this is due to the fact that we're no longer offering completions in contexts we can't actually know the name for (#163). But it seems that since we now return empty, VS Code's word suggestion is taking over and suggesting things.

If you set this, I believe it should work around the issue:

```json
"[python]": {
    "editor.wordBasedSuggestions": false
}
```

The real fix may be to always give back something in the completion list, e.g. here offer up the thing the user already typed. I think TS does this.

**Comment by jakebailey** [comment] 2020-11-12 20:55
@heejaechang FYI

**Comment by prrao87** [comment] 2020-11-12 21:09
Thanks, the workaround makes sense! I can imagine offering the user-typed input as the first choice may have some edge cases that are not desirable. I wonder if it's possible to treat the case as in the example I gave, i.e., aliasing, differently from other situations where the user may not want the completion's first choice as what they just typed.

**Comment by jakebailey** [comment] 2020-11-12 21:10
We already know the context you're typing in (to know to explicitly return nothing), so adding this special case is likely to be okay. Just needs some investigation and testing.

**Comment by heejaechang** [comment] 2020-11-12 22:17
@prrao87 thank you for reporting.

so, I tried to see old experiences, typescript experiences and etc.

this is old
![defname](https://user-images.githubusercontent.com/1333179/98998824-99222b80-24eb-11eb-9666-446faca616d0.gif)

as you can see, we used to add what the user has written so far into the list. I don't believe it was by design, but it happens to add those since it basically showed any symbols defined in the current scope which includes what the user has written so far.

due to that, it won't work if there is a syntax error such as 
![defname2](https://user-images.githubusercontent.com/1333179/98999235-4c8b2000-24ec-11eb-9da2-9b49040172b5.gif)

I tried typescript to see how they behave
![defname3](https://user-images.githubusercontent.com/1333179/98999665-02566e80-24ed-11eb-9386-eee4e052bc15.gif)

it looks like typescript also behaves the same as us.

that being said, we can improve behavior around this if we want to (@savannahostrowski @judej)

options I can think on top of my head will be

1. tell users to use wordBasedSuggestions or we explicitly turn it off under python.
2. tell users to turn off acceptSuggestionOnEnter
3. ask to enable (SuggestionItemOptions)[https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.asynccompletion.data.suggestionitemoptions?view=visualstudiosdk-2019] support in vscode (VS LSP client supports it). see (here)[http://index/?leftProject=Microsoft.VisualStudio.Language&leftSymbol=h2fz5qctgkqx&rightProject=Microsoft.VisualStudio.LanguageServer.Client.Implementation&file=Impl%5CFeatures%5CCompletion%5CCompletionResults.cs&line=28] and we support it in the server
4. we just manually add what the user has written so far explicitly (similar experience as we used to have)
5. and more? (welcome any suggestion)

* doing (1), we explicitly turn wordBasedSuggestions off under python is cheapest. then (4). (2) and (3) either don't require changes on our side or require changes in other components than us.

**Comment by prrao87** [comment] 2020-11-13 14:43
Option 1 (turning off wordBasedSuggestions) is doing the trick quite well for me right now - but it's not at all obvious to new users to know that this is the option they need to turn off to get the right behaviour. In the end, it would be nice to have an easy, intuitive system for beginners within Pylance that doesn't require users to disable VS Code editor settings!

**Comment by heejaechang** [comment] 2020-11-13 21:47
@prrao87 I agree. so (1), what I meant was we change default for wordBasedSuggestions for python to off. so there is nothing user need to do. it will be automatically off for python file. but users who really want wordBasedSuggestion can explicitly turn it on. and only those people need to know the option. not the other way around.

**Comment by jakebailey** [comment] 2020-11-19 19:31
Also relevant is #629, as VSC will also try and offer up snippets. Since we don't send anything, they're highly ranked. (4) would fix that too.

**Comment by heejaechang** [comment] 2020-11-24 02:31
my opinion is just doing simplest thing first (1) and see whether we get any feedback from users.

**Comment by jakebailey** [comment] 2020-12-03 00:02
Pylance 2020.12.0 now includes (1). I don't want to close this quite yet to see how this works out, or if we need to try another method.

**Comment by jakebailey** [comment] 2020-12-15 18:50
Updating the title of this to better reflect; we did the word completion thing, but snippets remain a problem. We may need to attempt the method where we add a fake completion for the prefix.

**Comment by prrao87** [comment] 2020-12-16 01:26
@jakebailey  I'm really conflicted about snippets - on the one hand it's annoying to keep on because it does things like suggest `pdb.set_trace()` when I just want to `import pandas as pd`

![1](https://user-images.githubusercontent.com/35005448/102292513-4c2edc00-3f13-11eb-8a68-2fe8313ffd91.gif)

On the other hand, I really like the convenience of the `__main__` boilerplate using snippets, so I don't want to disable it.

![2](https://user-images.githubusercontent.com/35005448/102292559-61a40600-3f13-11eb-81e7-170125cf417d.gif)

Do you know whether there's a workaround to get the second behaviour but not the first? I'm unclear how exactly this ties into the original issue with Pylance completions. I know you're doing your best to track all these issues in various places, so thanks a lot for your efforts!

**Comment by jakebailey** [comment] 2020-12-16 01:36
It's a VS Code quirk. We answer the completion request with "there are no completions", but then it also offers up word and snippets. This means that those are the only choices, and then they get picked and do the wrong thing.

There isn't a way to do that as far as I remember, maybe there's a way to disable specific snippets but I haven't tried.

**Comment by jakebailey** [comment] 2021-02-05 01:51
The most recent version of the core extension dropped snippets altogether. With our word completion default set to false, I'm not entirely certain this is a problem anymore, but the idea to always offer "what was typed" as a completion may be a useful idea if we want to ensure we don't break if word completion is enabled.

**Comment by prrao87** [comment] 2021-02-05 21:27
I agree, the "what was typed" is definitely something I see as being useful in the long term.

**Comment by judej** [comment] 2022-03-23 17:10
Thanks for the report. This has been fixed. Please reopen if this is still an issue.

**Closed by judej** 2022-03-23 17:10 UTC
Labels: bug, needs investigation
