### ISSUE TITLE
Internal clickable for each function

### ISSUE THREAD

**Issue by b-y-f** [microsoft/pylance-release#4768] opened 2023-08-26 06:13 UTC
## Environment data

-   VS Code version: 1.81.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: macos
-   Python and/or Anaconda version: py3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX

## Expected behaviour

<img width="1016" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/13849223/9a142d00-bd83-45f4-b404-de4f028bb2a2">

Expected have color and can be click to track the function source code.

## Actual behaviour

when every time I start the ipynb it works fine with this function, but after a while I dont know why it becomes below color and can not clickable.

<img width="461" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/13849223/75140616-4894-4cd4-89a9-bea7fd5a2c3d">

<img width="342" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/13849223/ae9ed250-d16c-4b24-8956-4f6d28bd72e2">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Just start the ipynb file

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
2023-08-27 17:48:54.405 [info] [Info  - 17:48:54] (55645) Pylance language server 2023.8.40 (pyright 03f79a81) starting
2023-08-27 17:48:54.405 [info] [Info  - 17:48:54] (55645) Server root directory: /Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist
2023-08-27 17:48:54.408 [info] [Info  - 17:48:54] (55645) Starting service instance "ISLP"
2023-08-27 17:48:54.429 [info] [Info  - 17:48:54] (55645) Setting pythonPath for service "ISLP": "/Users/yif/miniconda3/envs/lake-influx/bin/python"
2023-08-27 17:48:54.430 [info] [Warn  - 17:48:54] (55645) stubPath /Users/yif/ISLP/typings is not a valid directory.
2023-08-27 17:48:54.446 [info] [Info  - 17:48:54] (55645) Assuming Python version 3.10
2023-08-27 17:48:54.509 [info] [Info  - 17:48:54] (55645) No source files found.
2023-08-27 17:48:54.532 [info] [Info  - 17:48:54] (55645) Starting service instance "ISLP"
2023-08-27 17:48:54.540 [info] [Info  - 17:48:54] (55645) Setting pythonPath for service "ISLP": "/Users/yif/miniconda3/envs/islp/bin/python"
2023-08-27 17:48:54.540 [info] [Warn  - 17:48:54] (55645) stubPath /Users/yif/ISLP/typings is not a valid directory.
2023-08-27 17:48:54.557 [info] [Info  - 17:48:54] (55645) Assuming Python version 3.10
2023-08-27 17:48:54.592 [info] [Info  - 17:48:54] (55645) No source files found.
2023-08-27 17:56:32.739 [info] [Info  - 17:56:32] (55645) Starting service instance "ISLP"
2023-08-27 17:56:32.767 [info] [Info  - 17:56:32] (55645) Setting pythonPath for service "ISLP": "/Users/yif/miniconda3/envs/islp/bin/python"
2023-08-27 17:56:32.767 [info] [Warn  - 17:56:32] (55645) stubPath /Users/yif/ISLP/typings is not a valid directory.
2023-08-27 17:56:32.789 [info] [Info  - 17:56:32] (55645) Assuming Python version 3.10
2023-08-27 17:56:32.824 [info] [Info  - 17:56:32] (55645) No source files found.
2023-08-27 18:07:28.910 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths /Users/yif/ISLP/ch3/app_11-14.ipynb:pylance-notebook-cell:X26sZmlsZQ==.py
    at _0x4ba240 (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:900729)
    at /Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:907846
    at _0x2599f4.<computed> (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:907878)
    at _0x872478._onDidChangeNotebookDocumentAsync (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:886358)

```

</p>
</details>

**Comment by heejaechang** [comment] 2023-08-28 18:34
@debonte is this dup of the issue you just fixed?

> 2023-08-27 18:07:28.910 [info] Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths /Users/yif/ISLP/ch3/app_11-14.ipynb:pylance-notebook-cell:X26sZmlsZQ==.py
    at _0x4ba240 (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:900729)
    at /Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:907846
    at _0x2599f4.<computed> (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:907878)
    at _0x872478._onDidChangeNotebookDocumentAsync (/Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.40/dist/server.bundle.js:1:886358)

**Comment by debonte** [comment] 2023-08-28 18:44
Yes, this looks like a dupe of #4685.

**Closed** 2023-08-28 18:44 UTC
Labels: bug, duplicate

**Comment by b-y-f** [comment] 2023-08-29 07:27
Still getting problem

```
Server root directory: /Users/yif/.vscode/extensions/ms-python.vscode-pylance-2023.8.41/dist
Starting service instance "ISLP"
Setting pythonPath for service "ISLP": "/Users/yif/miniconda3/envs/islp/bin/python"
Assuming Python version 3.10
No source files found.
```

**Comment by debonte** [comment] 2023-08-29 14:56
@b-y-f, we believe this is a duplicate of #4685. Please watch that issue for updates. We'll have a related fix in our next prerelease build, which will likely be released tomorrow.
