### ISSUE TITLE
Feature Request: Inline Type hints

### ISSUE THREAD

**Issue by Zomatree** [microsoft/pylance-release#2413] opened 2022-02-22 23:03 UTC
Currently to check a variables type you either need to hover over the variable or use `reveal_type`, this idea taken from rust-analyzer allows seeing type hints, parameter names, parameter types inside nameless functions and function returns inline, for example:
![image](https://user-images.githubusercontent.com/39768508/155234262-33d4ac1f-37d1-4f8c-8a0b-f252bb8876bf.png)

**Comment by judej** [comment] 2022-03-08 22:41
Thanks for the request. This is not something that is currently supported but will reevaluate based on upvotes or community feedback.

**Comment by JosephTLyons** [comment] 2022-03-18 23:18
VS Code 1.65 finalized the API for Inlay Hints.  Rust Analyzer just switched from their custom implementation to the new built-in one.  I think PyLance could take advantage of this.

https://code.visualstudio.com/updates/v1_65#_inlay-hints

**Comment by tomashphill** [comment] 2022-03-19 06:10
+1 for inline hints. It would definitely help in learning new code bases

**Comment by luabud** [comment] 2022-04-04 22:05
Dupe of https://github.com/microsoft/pylance-release/issues/1559.

**Closed by luabud** 2022-04-04 22:05 UTC
Labels: enhancement
