### ISSUE TITLE
Pylance reporting String Literal is unterminated if an fstring ends with \\

### ISSUE THREAD

**Issue by SrslyKail** [microsoft/pylance-release#4481] opened 2023-06-09 18:18 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.6.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.7 64-bit
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
testpath = f"test\\"
```

<h3> Expected behavior </h3>

Pylance should not report this as unterminated;

<h3> Actual behavior </h3>
This raises the following error

```python
testpath = f"test\\"
```
```String literal is unterminated```

This does not
```python
testpath = "test\\"
```

<h3> Logs </h3>

```
2023-06-09 11:11:38.091 [info] (37064) Background inlayHint message
2023-06-09 11:11:38.092 [info] (37064) [BG(1)] getInlayHints range 0:0 - 0:25 at d:\test.py (0ms)
2023-06-09 11:13:51.474 [info] [Info  - 11:13:51 AM] (37064) SourceFile: Received fs event 'change' for path 'd:\test.py'
2023-06-09 11:13:51.475 [info] [Info  - 11:13:51 AM] (37064) SourceFile: Received fs event 'change' for path 'd:\test.py'
2023-06-09 11:13:51.476 [info] (37064) Background analysis message: markFilesDirty
2023-06-09 11:13:51.476 [info] (37064) Background analysis message: markFilesDirty
2023-06-09 11:13:51.506 [info] (37064) Background analysis message: analyze
2023-06-09 11:13:51.507 [info] (37064) [BG(1)] indexing: d:\test.py [found 1] (0ms)
2023-06-09 11:13:51.507 [info] (37064) Indexing Done: d:\test.py
2023-06-09 11:13:51.507 [info] [Info  - 11:13:51 AM] (37064) Heap stats: total_heap_size=70MB, used_heap_size=66MB, total_physical_size=70MB, total_available_size=4028MB, heap_size_limit=4096MB
```

**Comment by debonte** [comment] 2023-06-09 18:29
This is a duplicate of https://github.com/microsoft/pylance-release/issues/4460 which is fixed in our latest prerelease build (2023.6.11).

**Closed by debonte** 2023-06-09 18:29 UTC
Labels: duplicate
