### ISSUE TITLE
Pylance sometimes infers str and int types as `Literal` types, which is something I have never wanted

### ISSUE THREAD

**Issue by jlxgcgcg** [microsoft/pylance-release#697] opened 2020-12-07 19:30 UTC
## Environment data

-   Language Server version: 2020.12.0
-   OS and version: macos catalina 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.8.5

## Expected behaviour

This code should be well-typed:

```python
xs = [("me", 1)]

def append_to_xs(who: str, count: int) -> None:
    xs.append((who, count))
```

## Actual behaviour

I get an error:

```
Argument of type "tuple[str, int]" cannot be assigned to parameter "__object" of type "tuple[Literal['me'], Literal[1]]" in function "append"
  Tuple entry 1 is incorrect type
    "str" cannot be assigned to type "Literal['me']"
```

If I add a type hint like

```python
xs: List[Tuple[str, int]] = [("me", 1)]
```

then it works, but I shouldn't have to do that. Having the types be `Literal['me']` and `Literal[1]` is something that I've basically never wanted (and I can't believe anyone else wants) and should not be the default inference.

--

Here's another instance of the same problem:

```python
d = {"a": ("b", 1)}
d["c"] = ("d", 3)  # pylance error
```

**Comment by erictraut** [comment] 2020-12-07 19:32
This is largely a duplicate of this issue: https://github.com/microsoft/pyright/issues/1249.

**Comment by jlxgcgcg** [comment] 2020-12-07 19:35
thanks, I googled "pylance github" and ended up at this repo, and then I actually searched the issues for "literal" before opening this one, but I didn't know to look in the pyright repo instead

**Comment by jakebailey** [comment] 2020-12-07 19:42
The fix for that issue will be in this week's Pylance release, so we'll be able to see what happens afterward.

**Comment by erictraut** [comment] 2020-12-07 19:43
@jlxgcgcg, no worries. I wouldn't have expected you to know about the other repo. Thanks for submitting the suggestion.

**Comment by jakebailey** [comment] 2020-12-09 22:22
This issue has been fixed in version 2020.12.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020121-9-december-2020

**Closed by jakebailey** 2020-12-09 22:22 UTC
Labels: fixed in next version

**Comment by tthommes** [comment] 2023-07-20 13:35
This issue seems to be hot again in the current version (2023.7.30)!
When I try to pass an Enum-value e.g.
```
class MyEnum(Enum):
  A = 0x1
  B = 0x2
```
to a function parameter type-hinted as `Integral` pylance infers `Literal[]` for the Enum-value and complains about incompatibility.

**Comment by erictraut** [comment] 2023-07-20 13:42
@tthommes, this issue was fixed and closed nearly three years ago. If you think that you are experiencing a new bug, please file a new issue and provide a minimal, self-contained code sample. In your code sample above, for example, I don't know what the symbol `Integral` refers to.

**Comment by tthommes** [comment] 2023-07-20 13:49
I opened a new issue and fixed the code-example above.
