### ISSUE TITLE
Syntax highlights, intellisense, and autocomplete not working in Jupyter Notebook (only) at the WSL2 Ubuntu

### ISSUE THREAD

**Issue by wahidluthfi** [microsoft/pylance-release#5574] opened 2024-03-03 00:10 UTC
Type: <b>Bug</b>

when I add some syntax, i.e. add a line for commenting, the highlights don't work and all syntax isn't colored properly. It looks like the color came from the previous line or line after it which seems like it was locked for each line with the color loaded during the first opening of my jupyter notebook. Then the autocorrection is not working, and the python intellisense is not working properly.

I have added this issue to Stackoverflow Q&A but I think I am going to uninstall all my Ubuntu (also the WSL) and reinstall everything on WSL with the hope that everything could be better, but if not, then I hope there will be some response to this problem. I think somehow, my setup is not working properly.
https://stackoverflow.com/questions/78089964/syntax-highlights-intellisense-and-autocomplete-not-working-in-jupyter-notebook

Extension version: 2024.2.1
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (2.60GB free)|
|Process Argv|--crash-reporter-id 525f9b13-9369-4102-9e03-b9e9b45221c4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|7.61GB (5.91GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
8082a590:30971561
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
dsvsc020:30976470

```

</details>

**Comment by rchiodo** [comment] 2024-03-04 18:08
Thanks for the issue. This should be a bug in VS code:
https://github.com/microsoft/vscode/issues/206487

I'm marking your issue as a dupe of this one:
https://github.com/microsoft/pylance-release/issues/5543

Which is already tracking the VS code problem.

You should be able to go back to the 1.86.2 version of VS code to fix this problem.

**Closed by rchiodo** 2024-03-04 18:08 UTC
Labels: needs repro

**Comment by wahidluthfi** [comment] 2024-03-05 02:49
Thank you for the update Rich Chiodo
