### ISSUE TITLE
Refactoring menu doesnt work

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5178] opened 2023-11-29 23:18 UTC
pylance has a few refactoring offerings such as `extract method`, `extract variable`, `add pytest fixture types` and etc but none of them show up in `refactoring...` menu

![image](https://github.com/microsoft/pylance-release/assets/1333179/c3b80a86-d338-42c7-8316-49819ce5621a)

**Comment by bschnurr** [comment] 2023-12-01 19:20
hmm. are you sure it wasn't due to your selection?

**Comment by luabud** [comment] 2024-01-19 01:52
I can't reproduce this. Whenever the code action is available, they also show under the refactor menu. I'm closing this but feel free to reopen if you can still repro it.

**Closed by luabud** 2024-01-19 01:52 UTC
Labels: needs repro
