### ISSUE TITLE
Better formatting for complex signature hints

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#830] opened 2021-01-13 12:54 UTC
When hovering over functions/method with complex signatures with a goal like "learn the exact name of some argument" it can be hard to read the hint since VSCode applies no formatting to the signature. Hints become especially difficult to parse when overloading is involved. For example, this is what I saw when trying to check if there are any arguments like "env" for the [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run) function:

<img width="1116" alt="Screenshot 2021-01-13 at 15 45 44" src="https://user-images.githubusercontent.com/8861742/104454524-0a975c80-55b7-11eb-87f4-572d3d441db8.png">

At the same time, when I did Cmd+click on the function, I saw a well-formatted signature and quickly found the argument I was looking for:
 
<img width="751" alt="Screenshot 2021-01-13 at 15 52 05" src="https://user-images.githubusercontent.com/8861742/104454717-54804280-55b7-11eb-95bb-854824dfd2b3.png">

So, the question is if it is possible to format complex hints in a way that enhances their readability?

**Comment by judej** [comment] 2021-01-13 19:15
Dupe of #612

**Closed by judej** 2021-01-13 19:15 UTC
Labels: duplicate, triage
