### ISSUE TITLE
Syntax highlighting still breaks when adding type hint function return values

### ISSUE THREAD

**Issue by JeffreyHuang06** [microsoft/pylance-release#1002] opened 2021-03-01 01:47 UTC
-   Pylance language server 2021.2.4
-   MacOS Big Sur 11.3
-   Python 3.8.3

I get this error message:
```
[Info  - 1:09:25 AM] Pylance language server 2021.2.4 (pyright a18e6fb4) starting
[Info  - 1:09:25 AM] Server root directory: /Users/jeffrey/.vscode/extensions/ms-python.vscode-pylance-2021.2.4/dist
[Error - 1:09:25 AM] stubPath /Users/jeffrey/Documents/GitHub/mancalaBot/typings is not a valid directory.
```
When adding type hints to the function `tree_search` return value
<img width="1440" alt="Screen Shot 2021-02-28 at 8 43 15 PM" src="https://user-images.githubusercontent.com/59666651/109442274-b977e680-7a05-11eb-9e2b-33827483ee0e.png">

When removing the type hint return value on line 84 I get the expected highlighting
<img width="1440" alt="Screen Shot 2021-02-28 at 8 46 07 PM" src="https://user-images.githubusercontent.com/59666651/109442384-0b207100-7a06-11eb-879c-816d011d6ba8.png">

**Comment by jakebailey** [comment] 2021-03-01 18:05
This is a duplicate of #732.

That error message is benign and doesn't affect the semantic highlighting.

**Closed by jakebailey** 2021-03-01 18:05 UTC
Labels: triage
