### ISSUE TITLE
Pylance not working while editing jupyter notebook file on remote server.

### ISSUE THREAD

**Issue by ThXrimson** [microsoft/pylance-release#5546] opened 2024-02-29 14:22 UTC
When I edit any .ipynb file on any remote server, Pylance doesn't work. For already exsiting text when I open the file, Pylance works fine to give the hints. But when I add or delete any text, Pylance doesn't give any info. It works all well on local machine.

<h3> Environment data </h3>

-   Language Server version: 2024.2.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.6
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import csv # random text
```

<h3> Repro Steps </h3>

1. Create a new .ipynb file and add a cell.
2. Reopen it or reload the window.
3. Edit the .ipynb file.

<h3> Expected behavior </h3>

Pylance works correctly and shows hints.

<h3> Actual behavior </h3>

Nothing happened, original existing text remains hinted, newly added text is still plain.
![image](https://github.com/microsoft/pylance-release/assets/37134284/9b56d3f8-efdb-44ad-b403-d2a8ebf6d402)

<h3> Logs </h3>

When I edited the .ipynb file, logs like this came out as long as I took any step (adding or deleting text).
```
2024-02-29 14:06:21.401 [info] [Error - 2:06:21 PM] (1476492) Received change text document command for closed file file:///home/testPrev/thx/test.ipynb.py#W0sdnNjb2RlLXJlbW90ZQ%3D%3D
```

**Comment by rchiodo** [comment] 2024-02-29 17:02
Thanks for the issue. This should be a bug in VS code:
https://github.com/microsoft/vscode/issues/206487

I'm marking your issue as a dupe of this one:
https://github.com/microsoft/pylance-release/issues/5543

Which is already tracking the VS code problem.

**Comment by rchiodo** [comment] 2024-02-29 17:03
You should be able to go back to the 1.86.2 version of VS code to fix this problem.

**Closed by rchiodo** 2024-02-29 17:02 UTC
