### ISSUE TITLE
Move symbol to doesn't work in typed context

### ISSUE THREAD

**Issue by oleg-golovanov** [microsoft/pylance-release#5498] opened 2024-02-21 15:51 UTC
![Peek 2024-02-21 20-48](https://github.com/microsoft/vscode-python/assets/1384910/7a71cb49-1b5d-4edb-8a90-2a66073ffe2d)

### VSCode info
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-0.deb12.4-amd64

### Python extension info
Name: Python
Id: ms-python.python
Version: 2024.0.1

**Comment by debonte** [comment] 2024-02-21 17:55
Dupe of https://github.com/microsoft/pylance-release/issues/5449. Please try the latest VS Code Insiders build. It's fixed there.

**Comment by oleg-golovanov** [comment] 2024-03-05 14:41
Still doesn't work after update. I would like to emphasize that `Move symbol to ...` doesn't work with typed variables **only**. It works correctly with untyped variables, as it was shown in the gif in the first post.

### VSCode info
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:16.599Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-0.deb12.4-amd64

### Python extension info
Name: Pylance
Id: ms-python.vscode-pylance
Version: 2024.2.3

**Comment by oleg-golovanov** [comment] 2024-03-07 15:51
@debonte

**Comment by StellaHuang95** [comment] 2024-03-14 00:36
This issue has been fixed in prerelease version 2024.3.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/2024.3.100/CHANGELOG.md#20243100-13-march-2024-prerelease)

**Closed by StellaHuang95** 2024-03-14 00:36 UTC
Labels: bug, fixed in next version
