### ISSUE TITLE
Issue related to pylance crashed

### ISSUE THREAD

**Issue by Kushaldotel** [microsoft/pylance-release#5068] opened 2023-11-02 04:45 UTC
2023-11-02 10:28:17.039 [info] TypeError: _0x2f33cc[(_0x1efd68(...) + _0x1efd68(...))] is not a function
    at _0xa6e677.dirExistsCached (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:902382)
    at _0xa6e677._resolveAbsoluteImport (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:303694)
    at _0xa6e677.resolveAbsoluteImport (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:296859)
    at _0xa6e677._resolveBestAbsoluteImport (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:305905)
    at _0xa6e677._resolveImportStrict (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:299332)
    at _0xa6e677.resolveImportInternal (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:294521)
    at _0xa6e677.resolveImport (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\pyright.bundle.js:1:290200)
    at _0xa6e677.resolveImport (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:898287)
    at _0x170d92.<computed> (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:272928)
    at _0x5e13d0._enableJinjaTelemetry (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1078110)
    at _0x5e13d0.updateSettingsForWorkspace (c:\Users\LENOVO\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist\server.bundle.js:1:1019982)
    at async Promise.all (index 0)

2023-11-02 10:28:17.039 [info] [Error - 10:28:17 AM] Server process exited with code 1.
2023-11-02 10:28:17.042 [info] [Error - 10:28:17 AM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

I am persisting this issue:
Please help me to solve this problem:
I uninstalled and installed every extensions. I tried numerous things but still facing the issue:
For other projects I am not facing this issue there is one project only where I am facing this issue

**Comment by debonte** [comment] 2023-11-02 05:23
Duplicate of #5009, which is fixed in our latest prerelease build (2023.10.53).

**Closed by debonte** 2023-11-02 05:23 UTC
Labels: needs repro
