### ISSUE TITLE
python.analysis.completeFunctionParens(Invalid)

### ISSUE THREAD

**Issue by jiayouzl** [microsoft/pylance-release#3843] opened 2023-01-17 06:34 UTC
- VS Code Version: 1.74.3 (Universal)
- OS Version: macos 13.1 arm64

Steps to Reproduce:

1. "python.analysis.completeFunctionParens": true
2. When writing Python code, typing print does not automatically add parentheses.

![iShot_2023-01-17_14 21 21](https://user-images.githubusercontent.com/7685337/212824494-a79aa4af-abfa-45f0-ab5c-d06d832d128e.gif)

<img width="385" alt="image" src="https://user-images.githubusercontent.com/7685337/212824176-7b7f2110-13ac-479d-ade8-13d19137b448.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/7685337/212824216-8857b59e-4628-41e6-aec4-eba789f55053.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/7685337/212824233-6f57b31b-4c94-4108-9929-ec5c5646ef0c.png">

**Comment by rchiodo** [comment] 2023-01-17 18:16
Yes this is a dupe of #3831. It will be fixed in our next release.

**Closed by rchiodo** 2023-01-17 18:16 UTC
Labels: triage-needed
