### ISSUE TITLE
Strange syntax highlighting in notebooks on github.dev.

### ISSUE THREAD

**Issue by dynamicwebpaige** [microsoft/pylance-release#1874] opened 2021-09-25 15:57 UTC
Am noticing inconsistent Python syntax highlighting in `.ipynb` files when using github.dev:

![Screen Shot 2021-09-25 at 8 48 16 AM](https://user-images.githubusercontent.com/3712347/134777670-ca71a791-9f43-419a-9b1c-fde1ae64ce39.png)

Highlighting in the first code cell (ex: `import sys`) looks as I would expect; but `import sklearn` and the `oecd_bli` variable name are, at times, multicolored. 

 **Browser**: Microsoft Edge Version 94.0.992.31 (Official build) (x86_64)
**OS**: MacOS Big Sur v11.6
**Repro link**: https://github.dev/ageron/handson-ml2/blob/master/01_the_machine_learning_landscape.ipynb

**Comment by jakebailey** [comment] 2021-09-25 17:16
Unless something changed, I don't think Pylance runs in the browser within notebooks; support is limited to regular python files.

Maybe this is breaking because the browser bundle isn't filtering out notebook cells (where the desktop one has special code for it). When I added browser support to the Python extension, I don't think notebooks worked there, so I wouldn't have tested it.

**Comment by jakebailey** [comment] 2021-09-27 17:45
@rchiodo I'm thinking the above is caused by the middleware not filtering in the browser case (since I didn't get the notebook extension there); maybe a better way is to just bulk filter these files in the core extension until we can support a full notebooks experience, or shift notebook cell support downward into Pylance?

**Comment by rchiodo** [comment] 2021-09-27 18:13
Not sure why the middleware piece would be involved? Shouldn't it just be a pass through in this situation since the middleware npm module won't load ?

**Comment by rchiodo** [comment] 2021-09-27 18:16
Or are you saying there's some problem in the base middleware implementation for syntax highlighting? (And that it's caused by the middleware npm module not being there?)

**Comment by jakebailey** [comment] 2021-09-27 18:16
That's sort of the problem, right? If there's no middleware to filter, we get all of the notebook cell activity directly, which we likely mishandle by treating all cells as the same file (leading to the odd semantic highlighting as above, where all cells get the colors of the first cell).

**Comment by jakebailey** [comment] 2021-09-27 18:17
Maybe I'm missing something; I would also expect it to break in the same way when a notebook is opened on the desktop but Jupyter isn't installed, since VS Code can now open them without it.

**Comment by rchiodo** [comment] 2021-09-27 18:18
Oh I see. Yeah that makes sense.

Next iteration we're going to remove intellisense from the python extension for notebooks. So this case won't happen as pylance won't be loaded for these document types. 

Instead intellisense for notebooks will be handled entirely in the jupyter extension (with the per kernel pylance running). That won't be loaded in this case until jupyter supports web. So this problem should go away when we submit that change.

**Comment by jakebailey** [comment] 2021-09-27 18:25
I don't think it will go away; the Python extension still has to register the LS with a document selector that says "all python", right? I would think there are too many valid schemes now to explicitly list out, and VS Code doesn't provide a negative document filter. So, we'll still get all of the notebook traffic, unless you've figured out a way to ensure it doesn't happen anymore.

**Comment by rchiodo** [comment] 2021-09-27 18:29
> So, we'll still get all of the notebook traffic, unless you've figured out a way to ensure it doesn't happen anymore.

Python registers them by scheme right now. Like this:

```
export const PYTHON = [
    { scheme: 'file', language: PYTHON_LANGUAGE },
    { scheme: 'untitled', language: PYTHON_LANGUAGE },
    { scheme: 'vscode-notebook', language: PYTHON_LANGUAGE },
    { scheme: NotebookCellScheme, language: PYTHON_LANGUAGE },
    { scheme: InteractiveInputScheme, language: PYTHON_LANGUAGE },
];
```

I'm going to change it to this:

```
export const PYTHON = [
    { scheme: 'file', language: PYTHON_LANGUAGE },
    { scheme: 'untitled', language: PYTHON_LANGUAGE },
];
```

That will mean notebook cells and interactive window cells won't use pylance.

**Comment by jakebailey** [comment] 2021-09-27 18:33
The browser case doesn't do that, it registers all Python: https://github.com/microsoft/vscode-python/blob/1b2d498eb2e30c81f089d7a9d415c928bd2a79d4/src/client/browser/extension.ts#L70

The browser has a load of schemes it can use to load files (`vscode-vfs:`, `github:`, `https`), so you can't effectively list them all out. That's probably why this is being hit in the browser but not on the desktop in your testing.

**Comment by rchiodo** [comment] 2021-09-27 18:39
We need to bring this up with vscode then. Registering for all schemes isn't going to work unless pylance understands all file schemes.

**Comment by rchiodo** [comment] 2021-09-28 16:25
Talked to VS code. Current solution is we need middleware that swallows messages for notebook cells.

**Comment by heejaechang** [comment] 2022-01-03 22:29
hmmm.. does pylance do anything on notebook in vscode.dev (web) ? jupyter extension is disabled on web?

**Comment by rchiodo** [comment] 2022-01-03 22:59
Jupyter extension is disabled on web at the moment.

**Comment by heejaechang** [comment] 2022-01-04 05:59
if we are going to support jupyter + pylance on the web, we should track them separately. work needed to be done is different than what we are trying to do now.

**Comment by rchiodo** [comment] 2022-10-14 21:28
This looks to be fixed now. 

Pylance running in the web should support notebooks:

![image](https://user-images.githubusercontent.com/19672699/195946757-b41eee7d-b450-4225-aaa6-fd95c766fceb.png)

**Closed** 2022-10-14 21:29 UTC
Labels: notebooks
