### ISSUE TITLE
Type Checking Working Inconsistently

### ISSUE THREAD

**Issue by FerretDetective** [microsoft/pylance-release#4495] opened 2023-06-13 08:20 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.6.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.3
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
def test(b: int) -> int:
    return b


def main() -> None:
    test("123123")


if __name__ == "__main__":
    main()

```

<h3> Repro Steps </h3>

I am not sure how to reproduce this issue since it just started happening seemingly out of no where.

<h3> Expected behavior </h3>

When opening VSCode the code snippet above should cause pyright to show an error message saying:
"Argument of type "Literal['123123']" cannot be assigned to parameter "b" of type "int" in function "test"
  "Literal['123123']" is incompatible with "int"

<h3> Actual behavior </h3>

After opening VSCode pyright does not show an error. However if I go into settings and change python settings like the default LSP to pyright or changing the type checking mode a few times it will start reporting the error.

<h3> Logs </h3>

I tried using the steps above; however, when I did, I was prevented from submitting the issue because the body was too long.

**Comment by StellaHuang95** [comment] 2023-06-13 18:24
Thanks for the issue. Does it still repro for you if you turn the python.analysis.indexing off?

**Comment by ErisFletcher** [comment] 2023-06-13 21:11
I tried turning it off and nothing happened, though when turning it back on again pyright started working. However, pyright did not continue working after I reloaded VSCode both with and without that setting enabled.

**Comment by erictraut** [comment] 2023-06-13 22:34
I wonder if you've set `typeCheckingMode` to "off" in your workspace settings or pyrightconfig.json or pyproject.toml file. Those will override the `typeCheckingMode` in the user settings. Here's a suggestion: add a `# pyright: strict` comment to the top of the file. This will override all of the above and guarantee that you've configured strict-mode settings for that file.

**Comment by ErisFletcher** [comment] 2023-06-13 22:40
> Could you clarify on what you meant by "nothing happened"? Do you still see the error message with `indexing` set to `off` and `typeCheckingMode` set to `strict`?
>
> Also, could you provide us more info like a sample repository or a self-contained, minimal code sample so that we can repro and diagnose your problem?


What I meant is that the error message that should show up since the types don't match doesn't. This was with `typeCheckingMode` set to `strict` and both with and without `indexing` turned on.

I am not sure how to reproduce the issue since it just started happening out of seemingly nowhere. I created a fresh project folder and pasted the code from the snippet in the original issue into a file, and Pylance isn't reporting the type error. If it helps to reproduce the issue, I can provide my VSCode environment/settings.

**Comment by ErisFletcher** [comment] 2023-06-13 22:48
> I wonder if you've set `typeCheckingMode` to "off" in your workspace settings or pyrightconfig.json or pyproject.toml file. Those will override the `typeCheckingMode` in the user settings. Here's a suggestion: add a `# pyright: strict` comment to the top of the file. This will override all of the above and guarantee that you've configured strict-mode settings for that file.

I created a blank project and the issue still happens, though when putting the comment as you suggested it seems to work. Even after a reload, pyright seems to be correctly reporting the issue.

**Comment by erictraut** [comment] 2023-06-13 22:52
When you say "pyright seems to be correctly reporting the issue", are you referring to the pyright VS Code extension or the pyright CLI tool? I presume it's the latter. The reason that's important is that the pyright CLI tool doesn't look at VS Code settings, but pylance and the pyright VS Code extension both do look at these settings. 

Based on what you're seeing, it sounds like you've inadvertently configured your user settings to set typeCheckingMode to "off" or disabled the `reportGeneralTypeIssue` diagnostic check. The reason I suspect it's your user settings is that it applies to the newly-created project as well as your previous project.

**Comment by ErisFletcher** [comment] 2023-06-13 23:17
I meant the Pylance/Pyright VSCode extension, the pyright CLI tools is working fine. If I did inadvertently misconfigure the type checking how would I fix this?

**Comment by StellaHuang95** [comment] 2023-06-14 00:51
You can open the `settings.json` file with the `Preferences: Open Settings (JSON)` command in the Command Palette (Ctrl+Shift+P), and make sure you have your `python.analysis.typeCheckingMode` set to "basic" or "strict", also make sure you don't have your `reportGeneralTypeIssues` set to `none`.

**Comment by ErisFletcher** [comment] 2023-06-14 01:01
I checked and the typeCheckingMode is set to strict and I don't see anything bout reportGeneralTypeIssues. I can attach my settings.json if needed. 

Also when in the settings.json there is a warning at the top saying "Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)".

**Comment by FindDefinition** [comment] 2023-06-14 02:12
same problem with newest pylance (2023.6.10). if I switch pylance to old version such as 2023.4.30, errors show correctly. all settings remain same.

**Comment by ErisFletcher** [comment] 2023-06-14 06:15
I checked, and it is set to strict both in the status bar and the settings.json.

**Comment by cmditch** [comment] 2023-06-14 07:20
I'm experiencing the same issue. Starting occurring tonight right after a VSCode update.

**Comment by heejaechang** [comment] 2023-06-14 16:31
@ErisFletcher are you saying with the option set, it still repro? or it doesn't? if it still repro, is the log above with the option set? if it is, we probably need actual repro to figure out. I don't see anything stand out from the log.

**Comment by StellaHuang95** [comment] 2023-06-14 17:08
> I checked and the typeCheckingMode is set to strict and I don't see anything bout reportGeneralTypeIssues. I can attach my settings.json if needed.
> 
> Also when in the settings.json there is a warning at the top saying "Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)".

@heejaechang Could it be a vscode issue? There's a vscode ticket tracking it, see https://github.com/microsoft/vscode/issues/177142, and the user said "nothing I do in my settings.json file has any effect."

**Comment by heejaechang** [comment] 2023-06-14 17:22
could be. but not sure how this (https://github.com/microsoft/pylance-release/issues/4495#issuecomment-1590336869) happen if `vscode` is the reason. or it could be a `race` bug that make it works randomly.

```
Tested pylance versions:
2023.6.10: not working
2023.5.50: not working
2023.5.40: works
2023.4.30: works
```

**Comment by ErisFletcher** [comment] 2023-06-14 17:55
@heejaechang It doesn't work with the option set, yes and the logs are with the option set.

**Comment by ErisFletcher** [comment] 2023-06-14 18:08
@StellaHuang95 @heejaechang When I change almost any Python-related settings around a few times in the settings.json and the actual settings menu, Pylance starts with work correctly again. Here is a link to a video of the issue happening: https://drive.google.com/file/d/1f95V51yokZNas4UEp27akk_QwtDxvA7I

**Comment by heejaechang** [comment] 2023-06-14 19:22
@ErisFletcher it does look like `vscode` bug. it seems `vscode` is not providing information from `settings.json` correctly at the start up. it seems that information only communicated to us when `setting.json` is updated.

**Comment by heejaechang** [comment] 2023-06-15 06:39
found issue. it was bug in our side. fix will be included in the next release.

**Closed** 2023-06-21 21:27 UTC
Labels: fixed in next version, user responded
