### ISSUE TITLE
Auto completion cannot add brackets with Pylance enabled 

### ISSUE THREAD

**Issue by eaglet123** [microsoft/pylance-release#180] opened 2020-07-28 04:35 UTC
## Environment data

-   Language Server version: Pylance 2020.7.3
-   OS and version: Windows 10 1809/2004, VS Code 1.47.2/1.47.3
-   Python version : 3.7.3, 3.8.3, 3.8.4, 3.8.5

## Expected behaviour

Auto completion of functions should add brackets, with the following settings: 

"python.autoComplete.addBrackets": true
"editor.tabCompletion": "on"

## Actual behaviour

Tried with print(), OS imported funtions, and self-defined functions, with Pylance enabled, the auto completion can only give "print", but not "print()".

As long as Pylance is disabled, the auto completion can give "print()". 

Turned Pylance back on, and the auto completion cannot give brackets again. Note that to replicate this step, VS Code should be closed completely and turn on again, or it could act normally. 

The problems stays the same with or without VS Intellicode installed. 

Also the languageserver setting is kept the same when experimenting: "python.languageServer": "Pylance"

**Comment by eaglet123** [comment] 2020-07-28 06:42
Tried again, uninstalled Pylance and installed Intellicode, and changed the languageserver to "Microsoft". The auto completion cannot add brackets, neither. 

Turns out if the languageserver is set to anything other than Jedi, "python.autoComplete.addBrackets" is over-written. 

Knowing that Pylance intends to depreciate the Python language server, hope this progress can be faster, so that I can have the convinience of auto-added brackets and Pylance together.

**Comment by jakebailey** [comment] 2020-07-28 17:15
Duplicate of #37.

**Closed by jakebailey** 2020-07-28 17:15 UTC

**Comment by nonoash** [comment] 2023-01-19 10:52
> Tried again, uninstalled Pylance and installed Intellicode, and changed the languageserver to "Microsoft". The auto completion cannot add brackets, neither.
> 
> Turns out if the languageserver is set to anything other than Jedi, "python.autoComplete.addBrackets" is over-written.
> 
> Knowing that Pylance intends to depreciate the Python language server, I hope this progress can be faster, so that I can have the convinience of auto-added brackets and Pylance together.

I'm having the same issue, checked https://github.com/microsoft/pylance-release/issues/37 added `"python.analysis.completeFunctionParens": true,` but it's just not working with Pylance as language server. As it never been fixed since 3years or am i missing something ?

**Comment by rchiodo** [comment] 2023-01-19 17:13
@nonoash, this was a recent regression https://github.com/microsoft/pylance-release/issues/3831. It should be fixed in the prerelease build.

**Comment by nonoash** [comment] 2023-01-20 11:32
> @nonoash, this was a recent regression #3831. It should be fixed in the prerelease build.


Yep indeed thanks for the heads up
