### ISSUE TITLE
Pylance does not respect `__builtins__.pyi` for notebooks.

### ISSUE THREAD

**Issue by kartikgupta-db** [microsoft/pylance-release#4949] opened 2023-10-11 18:31 UTC
Pylance does not respect `__builtins__.pyi` for notebooks. It does respect that for normal python files.

## Environment data

-   Language Server version: v2023.10.10
-   OS and version: Darwin arm64 22.6.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
# __builtins__.pyi
abc: int
```

## Repro Steps
1. Create a __builtins__.pyi file in the location specified by `python.analysis.stubPath` setting. 
2. Add the above snippet to builtins.pyi. 
3. Observe the following differing behaviour for notebooks and python files

#### notebook
![image](https://github.com/microsoft/pylance-release/assets/88345179/25be8ecd-b9b4-4ecc-9da2-cc9af3db3232)

#### python file
![image](https://github.com/microsoft/pylance-release/assets/88345179/4da83238-ae7b-4780-a48e-30ce5f354f3e)

## Expected behavior

The __builtins__.pyi file should be respected in both the cases. 

## Actual behavior

The __builtins__.pyi file is not respected for notebooks.

**Comment by rchiodo** [comment] 2023-10-11 20:14
Thanks for the issue. I can reproduce locally. Not sure yet why notebooks don't seem to pick up stub paths though.

**Comment by kartikgupta-db** [comment] 2023-10-13 08:46
@rchiodo, we are building an extension, that relies on this functionality for providing autocompletion support for some of our special variables. It is a critical requirement for us. Can you help prioritise this?

**Comment by rchiodo** [comment] 2023-10-13 17:16
All I can say is it's in our backlog. Probably be a month? before I get the time to look at it.

**Comment by rchiodo** [comment] 2023-10-24 23:52
Root caused the problem. We have an implicit import for the IPython display stub file in all notebooks. Because this implicit import was a 3rd party stub file, it wasn't using the builtins that a normal 1st party file would.

Fix should be out soon.

**Comment by heejaechang** [comment] 2023-10-26 18:45
This issue has been fixed in prerelease version 2023.10.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231051-26-October-2023-PreRelease)

**Closed by heejaechang** 2023-10-26 18:45 UTC
Labels: bug, fixed in next version, P1
