### ISSUE TITLE
Underscores are escaped with backslashes in Docstrings when writing Python in Visual Studio Code

### ISSUE THREAD

**Issue by StevenTeglman** [microsoft/pylance-release#528] opened 2020-10-27 10:05 UTC
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): v2020.9.114305
-   OS and version: Windows 10 Home, v10.0.18363 Build 18363
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 64-bit 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Microsoft and/or Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Show the document popup with a value of as:
tex_t (String): The text you want to print.

## Actual behaviour
Any underscores in the Docstrings are preceded by a backslash
tex\_t (String): The text you want to print.
![Capture](https://user-images.githubusercontent.com/53273394/97286457-d035e300-1843-11eb-8953-2e431ac9b0a0.PNG)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Copy and paste this:

```
def printl(text):
    """
    Clears the console and prints whatever text is inputed, under a heading.

    Parameters
    ----------
    tex_t (String) : The text you want to print.

    Returns
    -------
        Nothing
    """
    return
```
2.  Type in "printl(" and look the code preview

## Note
After changing the python.languageServer setting, I found out this is only produced if set to Microsoft or Pylance. Setting it to Jedi eliminates the problem.
</details>

**Comment by jakebailey** [comment] 2020-10-27 17:40
This doesn't reproduce as written above:

![image](https://user-images.githubusercontent.com/5341706/97340117-9fa07a00-1840-11eb-808c-f089a6590ced.png)

However, I believe you may be missing the indent in the `Parameters` section in your code snippet. Is that correct?

If you did have it indented, then this would be a dupe of #48, as we're treating indented blocks as code blocks (per RST and markdown), but this specific docstring format is I believe the numpy one which has a different syntax.

**Comment by StevenTeglman** [comment] 2020-10-28 11:49
I added an indent, yet the problem persists.
![image](https://user-images.githubusercontent.com/53273394/97432238-f2029900-191b-11eb-918a-c8e35bcb46da.png)

**Comment by jakebailey** [comment] 2020-10-28 16:33
The indent is what causes the problem; removing it makes the text not monospace and you don't see the escaping.

This is a dupe of #48, then, since this format will take special care due to the differences between it and regular reStructuredText or Markdown.

**Closed by jakebailey** 2020-10-28 16:33 UTC
Labels: waiting for info
