### ISSUE TITLE
Proper Syntax Highlighting for 3.12-Style Type Aliases

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pylance-release#5315] opened 2024-01-02 02:33 UTC
Python 3.12 adds a new way of declaring type aliases through the `type` statement.

```python
type Point = tuple[float, float]
```

However, the alias itself goes without any syntax highlighting, unlke 3.11 style aliases.

![CleanShot 2024-01-01 at 20 31 54](https://github.com/microsoft/pylance-release/assets/41130755/129a6f80-04b1-4ff2-951d-80db82d270e8)

**Comment by luabud** [comment] 2024-01-17 22:47
I believe this is a dupe of https://github.com/microsoft/pylance-release/issues/3100 but let me know if I got this wrong. Thanks!

**Closed by luabud** 2024-01-17 22:47 UTC
Labels: enhancement
