### ISSUE TITLE
Rename variable with F2 doesn't work: No result

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/pylance-release#1978] opened 2021-10-22 22:24 UTC
Issue Type: <b>Bug</b>

Description: Rename variable with F2 doesn't work

Reproduction: 

1. Click on a variable
2. Type F2
3. Type new variable name
4. Hit enter
5. Observe result

Expected result: variables renamed
Actual result: Variables not renamed, warning pops up

![2021-10-22 20 22 16](https://user-images.githubusercontent.com/25161793/138504594-01fdf81c-0aeb-45b4-9b3a-8be7772f39fe.gif)

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

First reported at vscode main repo: https://github.com/microsoft/vscode/issues/135664#event-5507350046

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): virt-conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

analysis
• completeFunctionParens: false
• autoImportCompletions: true
• autoSearchPaths: "<placeholder>"
• stubPath: "<placeholder>"
• diagnosticMode: "openFilesOnly"
• extraPaths: "<placeholder>"
• useLibraryCodeForTypes: true
• typeCheckingMode: "off"
• errors: []
• warnings: []
• information: []
• disabled: []
• typeshedPaths: "<placeholder>"
• cacheFolderPath: "<placeholder>"
• memory: {"keepLibraryAst":false}
• logLevel: "Error"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

autoComplete
• addBrackets: false
• extraPaths: "<placeholder>"
• showAdvancedMembers: true
• typeshedPaths: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2021.10.1365161279
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|. --crash-reporter-id dfe1fb5d-d600-4527-b9d0-dfe2e538f957|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by jakebailey** [comment] 2021-10-29 18:16
I _think_ this is a duplicate of #1636, actually.

**Comment by corneliusroemer** [comment] 2021-10-29 18:27
@jakebailey yes looks like it, though the way issue #1636 is phrased makes it more like a feature request, whereas the way this issue is phrased makes it clear that it's a bug and why it's a bug - not just some weird user expectation.

**Comment by jakebailey** [comment] 2021-10-29 21:51
I'll close this as a dupe, then.

Largely, we would be considering that to be an enhancement request as it's technically not one we tested for or explicitly attempted to support (so, is an improved set of features to also work in those), but I do agree that it is surprising and can also be thought of as a bug. In any case, we certainly know of the limitation and the other issue is the canonical issue for it.

**Closed by jakebailey** 2021-10-29 21:51 UTC
Labels: waiting for user response, needs investigation
