### ISSUE TITLE
Allow "Go To Definition" to work with fixtures in Pytest, similar to Pycharm

### ISSUE THREAD

**Issue by macintacos** [microsoft/pylance-release#1824] opened 2021-09-16 17:09 UTC
I searched existing issues, and couldn't find something exactly like what I'm describing.

When using `pytest`, you can use `conftest.py` to import a bunch of fixtures from various files to be used in your actual tests. These fixtures are passed in as parameters to the test methods themselves, and `pytest` figures out everything via some magic under the covers. VSCode doesn't seem to understand where to find these fixtures when using the "Go To Definition" command from the method that is using the fixtures, whereas Pycharm does seem to understand how to resolve it and allow their go to definition to function as I would have expected.

Is there any chance that we can get this to work with Pylance? Below is a video that I took demonstrating the issue - Pycharm on the left, VSCode on the right.

https://user-images.githubusercontent.com/8128941/133654689-aaf685a8-fb77-41dd-a703-1be9f717c7bb.mp4

Here's a minimal sample project to repro this: https://github.com/macintacos/fixtures-pylance-test

It uses Poetry for dependency management. You can repro what I gave above by just cloning the repo and doing:

```bash
poetry install
poetry run fix # this is just to test that the project runs fine
poetry run pytest tests # this will show you that the fixture is coming up okay - it's meant to fail.
```

Please let me know if there's any additional information I can provide. Thanks!

**Comment by jakebailey** [comment] 2021-09-16 17:25
This is a dupe of #1750.

**Closed by jakebailey** 2021-09-16 17:25 UTC
Labels: triage

**Comment by macintacos** [comment] 2021-09-16 22:05
Thanks @jakebailey, will follow that along with interest 🙂
