### ISSUE TITLE
Import Errors in Visual Studio Code with Python

### ISSUE THREAD

**Issue by MikevanDykehike** [microsoft/pylance-release#4873] opened 2023-09-23 21:40 UTC
I've encountered a persistent issue in Visual Studio Code (VSC) where I'm experiencing import errors when trying to import one Python file into another. The error is indicated by a yellow underline beneath the import statement, and the Problems tab states: "Import File could not be resolved Pylance(reportMissingImports)". The peculiar thing is, the same code runs perfectly fine in PyCharm, which suggests that this issue is specific to VSC or its extensions.

I have a simple project structure with two Python files in the same directory:

file1.py
```
import file2
file2.my_function()
```

file2.py
```
def my_function():
    print("Hallo aus file2!")
```

Example Test File:

test_file.py
```
import file2
def test_my_function():
    assert file2.my_function() == "Hallo aus file2!"
```

The issue appeared mid-coding session; previously working imports suddenly started showing the error. The file paths are "C:\Users[username]\import_test\file1.py" and "C:\Users[username]\import_test\file2.py". The issue persists even with a fresh installation of Python and VSC, and with all Python-related folders deleted. The code runs without any import errors in PyCharm. The import statement works to import a function or class, but it is labeled as a defect import, and pytest does not detect it unless it is testing right out of the file.

Steps Taken:

Ensured that there are no spaces or special characters in file and folder names.
Ensured the correct Python interpreter is selected in VSC. Even tried using the Python interpreter from PyCharm in VSC.
Verified that the Python extension is installed and enabled.
Only the Python extension is enabled.
Tried modifying sys.path to include the directory containing the Python files.
Checked and confirmed both Python files are set to UTF-8.
Completely uninstalled and reinstalled both Python and VSC, ensuring all configuration files and settings were cleared.
Changed the Python Language Server to Jedi in the settings.json file, and back after it became apparent it didn't cause the issue.
Compared the current working directories in different environments using os.getcwd() to ensure they are the same.
Cleared Cache and Extension Data.
Added an init.py file to the directory, with no result.
Tried using relative import from .file2 import my_function, with no result.
Uninstalled and reinstalled pytest, with no result.
Additional Step:

Modified the settings.json file in VSC to explicitly set Pylance as the Python Language Server and added the project directory to python.analysis.extraPaths:
```
{
    "security.workspace.trust.untrustedFiles": "open",
    "python.defaultInterpreterPath": "C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe",
    "python.languageServer": "Pylance",
    "python.analysis.extraPaths": ["C:\\Users\\user\\import_test"]
}
```
After saving the changes and restarting VSC, the issue still persists.
I'm continuing to explore other potential solutions and am open to any further suggestions or insights from the community. Any help would be greatly appreciated!

**Comment by jrraymond** [comment] 2023-09-24 15:14
Does the issue persist if you install a previous version (v2023.9.10) of the pylance extension? I noticed a regression in v2023.9.20 which broke imports.

**Comment by willdave865** [comment] 2023-09-24 19:06
I have just had this problem in the last couple of days. Using the latest VSC release I receive error: 'Import "common.generalModule" could not be resolvedPylance'. 

Version: 1.82.2 (user setup) Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d Date: 2023-09-14T05:55:25.390Z OS: Windows_NT x64 10.0.22621

I got this after switching back between my Python & Powershell repos. My local Python imports were not underlined with the  Pylance error before the switch. But are after. It is important to note that all my Python import files are still working as before. The only change I have experienced is the false error message.

**Comment by rchiodo** [comment] 2023-09-25 16:20
This could be a dupe of https://github.com/microsoft/pylance-release/issues/4869, which we fixed in the prerelease, but doesn't sound like it. I'm suspecting this:

https://github.com/microsoft/pylance-release/issues/4861.

2023.9.20 switched to using real paths for files. This had a bug when opening loose files (and not opening a folder).

**Comment by willdave865** [comment] 2023-09-25 18:00
I can confirm that by opening a folder before opening my Python-code-file
the false error reported was not present.

**Comment by thePmr** [comment] 2023-09-27 05:24
Also, symlinked modules no longer discovered and intellisense/navigate to definition stopped working. Downgrade to `v2023.9.10` resolved the issue for me.

**Comment by rchiodo** [comment] 2023-09-27 15:59
Closing as a dupe of #4861.

**Closed by rchiodo** 2023-09-27 15:59 UTC
Labels: needs repro
