### ISSUE TITLE
Rename symbol in a symbolic py file opens source file

### ISSUE THREAD

**Issue by Xiao-Chenguang** [microsoft/pylance-release#5030] opened 2023-10-27 15:56 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

rename in the symbolic file should work as in a normal file.

Currently, rename the variable in a symbolic py file automatically opens the corresponding source file in a new tab.
Then you have to save the change in the source file to finish the rename as the rename change nothing in the file I am editing.
Even I save the change in the source file and go back to the file I am editting, python extension stop work for this file. For example, the syntex hightlight not work.

## Steps to reproduce:

1. create a file 1/src.py with content like "a=1"
2. create a symbolic link for folder "1" with `ln -s 1/ 2`
3. edit the `2/src.py` and use `F2` rename symbol function to rename "a" to "b"
4. vscode automatically opens the "1/src.py" in a new tab and nothing change in `2/src.py` but in '1/src.py'.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.18.0
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.4.0
Modes:
Remote OS version: Linux x64 4.18.0-348.2.1.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 8bf86e78-090c-450d-8a5e-92c2976781c0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Bnode-1|
|OS|Linux x64 4.18.0-348.2.1.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (144 x 3048)|
|Memory (System)|503.53GB (479.62GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythonmypyd1:30859726
pythoncet00cf:30866519
h48ei257:30870396
pythontbext0cf:30864173

```

</details>

**Comment by Xiao-Chenguang** [comment] 2023-10-28 12:49
I confirm that roll back to Pylance(v2023.10.40) solve this problem. This could be a problem in the latest pylance.

**Comment by lgiraldi** [comment] 2023-10-30 14:31
Using the full path to the ${workspaceFolder} instead of a symlink also fixes the issue.

**Comment by zgaxddnhh** [comment] 2023-11-02 14:36
> Same issue here with similar settings, using the remote extensions from a windows computer to a linux station.
> 
> There are two error messages in the log of Output/Python Language Server:
> 
> ```
> 2023-10-30 15:15:36.276 [info] [Error - 15:15:36] (1012639) Received redundant open text document command for /path/to/__main__.py
> 2023-10-30 15:15:53.807 [info] [Error - 15:15:53] (1012639) Received change text document command for closed file /path/to/__main__.py
> ```

I also have the same problem, Can you tell me how to fix it ? Thank you.

**Comment by richard-berg** [comment] 2023-11-02 14:40
For me, opening `$(realpath workspaceFolder)` did not fix the issue, but reverting to `v2023.10.40` did.

**Comment by geckoy** [comment] 2023-11-02 15:38
> I confirm that roll back to Pylance(v2023.10.40) solve this problem. This could be a problem in the latest pylance.

yeah i tried this solution and problem fixed, pylance should fix this issue.

**Comment by richard-berg** [comment] 2023-11-07 17:55
Pylance auto-updated to `v2023.11.10`, breaking my language server once again.  Can you please not publish automatic upgrades until critical crashbugs like this one are resolved?

**Comment by rchiodo** [comment] 2023-11-07 18:03
2023.11.10 should be the same as 2023.10.40. So, it should have fixed the problem.

@richard-berg are you getting the same error? Can you double check you didn't update to 2023.11.11? That would have this issue in it.

**Comment by richard-berg** [comment] 2023-11-07 18:14
The stack trace has changed but the observed behavior is the same.

`2023.10.50`
```
Error: Cannot find module '/home/rberg/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.50/dist/server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
...
2023-11-01 22:13:13.015 [info] [Error - 10:13:13 PM] (88988) Received change text document command for closed file /local_scratch/$REDACTED.py
2023-11-01 22:13:13.306 [info] [Error - 10:13:13 PM] (88988) Received change text document command for closed file /local_scratch/$REDACTED.py
2023-11-01 22:13:13.414 [info] [Error - 10:13:13 PM] (88988) Received change text document command for closed file /local_scratch/$REDACTED.py
```

`2023.11.10`
```
2023-11-07 11:53:19.735 [info] [Error - 11:53:19 AM] Notify file events failed.
2023-11-07 11:53:19.736 [info] Error: Starting server failed
	at _.$start (/physical/$REDACTED/rberg/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2415678)
	at async _.sendNotification (/physical/$REDACTED/rberg/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2401167)
	at async t.Delayer.<anonymous> (/physical/$REDACTED/rberg/.vscode-server/extensions/ms-python.python-2023.20.0/out/client/extension.js:2:2413302)
```

**Comment by rchiodo** [comment] 2023-11-07 18:54
That sounds like a completely different issue. Your 2023.10.50 sounds like the extension wasn't installed correctly for some reason.

The 2023.11.10 is harder to tell what the problem is. There should be output in the Python Language Server tab for that. Maybe there isn't and that's why you're showing the output from the Python tab. If that's the case I don't think the extension was installed in that situation either.

**Comment by debonte** [comment] 2023-12-01 00:59
This is a regression from our most recent stable release (2023.11.10).

**Comment by debonte** [comment] 2023-12-01 04:37
The problem is that `RealFileSystem.realCasePath` skips calling `fs.realPathSync` only if the file/directory pointed at by `path` is a symlink. But we also need to skip that call if any of that file/directory's parent directories are symlinks.

**Comment by debonte** [comment] 2023-12-02 01:12
This issue has been fixed in prerelease version 2023.11.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312102-1-december-2023-prerelease)

**Closed by debonte** 2023-12-02 01:12 UTC
Labels: bug, fixed in next version, P0

**Comment by slingshotvfx** [comment] 2023-12-22 04:01
I have this same issue in pylance `v2023.12.1` when using a mapped drive in windows.

Say I have //server/storage mapped to z:\

Renaming a symbol in z:\test\test.py results in the following errors:
```
2023-12-21 19:58:52.027 [info] [Error - 7:58:52 PM] (51164) Received redundant open text document command for \\server\storage\test\test.py
```

**Comment by chuklee** [comment] 2023-12-27 10:11
Hello, i have the pre-release version v2023.12.101 (i also tried with the last stable version) but the bug is still present.
