### ISSUE TITLE
Do Not Work Well With Jupyter Notebook

### ISSUE THREAD

**Issue by zch0423** [microsoft/pylance-release#1684] opened 2021-08-17 13:25 UTC
Issue Type: <b>Bug</b>

While using jupyter notebook, Pylance fails to parse correctly. For instance, it always shows a red wavy line at the very beginning of every notebook cell, and the feedback claims "expected expression" while nothing works to remove it.

Extension version: 2021.8.1
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|32.00GB (8.59GB free)|
|Process Argv|. --crash-reporter-id 250d9344-26a8-4ab1-a05d-3cecae7fe36a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30353136

```

</details>

**Comment by jakebailey** [comment] 2021-08-17 17:49
Does it happen immediately after opening the notebook, or only after some amount of editing?

This could be a dupe of #1521.

**Comment by zch0423** [comment] 2021-08-18 00:31
> Does it happen immediately after opening the notebook, or only after some amount of editing?
> 
> This could be a dupe of #1521.

I find the situation quite similar to the issue #1521. It happened after some amount of editing, especially after Markdown text I guess. I have tried but it seems I cannot reproduce it consistently.

**Comment by jakebailey** [comment] 2021-08-18 19:05
Thanks. If it's going away on a reload, and returning after editing, then that sounds like the linked issue.

**Closed by jakebailey** 2021-08-18 19:05 UTC
Labels: waiting for user response
