### ISSUE TITLE
Escaped anti-slash at the end of f-string shows syntax error

### ISSUE THREAD

**Issue by Quent21** [microsoft/pylance-release#4460] opened 2023-06-07 12:06 UTC
## Environment data

- VSCode version : 1.78.2
-   Pylance version : v2023.5.50
-   OS and version: Ubuntu 22.04.2 LTS

## Code Snippet

```python
s = f"test\\"
```

## Expected behavior

Pylance should not show any error.
I can run this code with Python 3.10.6 without any problem.

## Actual behavior

I got the following syntax error: `String literal is unterminated`

**Comment by Quent21** [comment] 2023-06-07 12:09
Also, is there a way to temporary disable syntax errors for one specific line ?
I know about the comment `# type: ignore` that we can put at the end of a line, but it does not seem to work for syntax errors.

**Comment by erictraut** [comment] 2023-06-07 14:52
Thanks for reporting the problem. This was reported earlier and transferred to the [pyright repo](https://github.com/microsoft/pyright/issues/5240). It was fixed a few days ago and will be included in this week's insiders build of pylance (due out later today).

@rchiodo, you may want to consider cherry-picking this fix into this week's production release of pylance as well since it's very targeted and poses minor regression risk.

@Quent21, to answer your question, there's no way to suppress a syntax error. These are generated by the parser, not the type checker (i.e. the semantic analysis logic). The `# type: ignore` mechanism works on the parse tree (the output of the parser), but if the parser thinks that it has detected a syntax error, then the parse tree is likely incorrect or incomplete.

**Comment by heejaechang** [comment] 2023-06-08 01:35
This issue has been fixed in prerelease version 2023.6.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023611-7-June-2023-PreRelease)

**Closed by heejaechang** 2023-06-08 01:35 UTC
Labels: bug, fixed in next version
