### ISSUE TITLE
Pylance can not automatically detect the package change in global environment while it work in virtual environment 

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#1474] opened 2021-06-21 04:33 UTC
If I am using the global environment in VSCode. No matter I install the package or uninstall the package, the Pylance can not detect it automatically. This means I need to reload the VSCode after I install the package I want to import, then Pylance can detect it.

But when I am using the virtual environment, it works perfectly. After I install or uninstall the package the Pylance can detect it immediately.

If it is possible to make Pylance detect the package change in the global environment like in the virtual environment?

**Comment by judej** [comment] 2021-06-21 18:05
Dupe of #923

**Closed by judej** 2021-06-21 18:05 UTC
Labels: triage
