### ISSUE TITLE
Poor code completion behavior

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/pylance-release#741] opened 2020-12-14 20:21 UTC
## Environment data

-   VS Code version: 1.52.0
-   Extension version (available under the Extensions sidebar): 2020.11.2 
-   OS and version: macOS Big Sur
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Value of the `python.languageServer` setting: pylance

## Expected behaviour

If I type: `import pandas as pd` into VSCode and hit enter, I should see this line in the editor, plus a new line/carriage return.

## Actual behaviour

I end up with `import pandas as import pdb; pdb.set_trace()` because of overzealous code completion. The engine ought to know that the `as` expression is setting up an alias and not attempt to drop in a completely unrelated snippet. 

## Steps to reproduce:

1. Open a blank Python file
2. Type `import pandas as pd` and hit the return key

**Comment by jakebailey** [comment] 2020-12-15 18:46
This is due to the Python extension's snippets: microsoft/vscode-python#14781

See also #629.

You can disable snippets by setting:

```json
"[python]": {
    "editor.snippetSuggestions": "none"
}
```

**Comment by jakebailey** [comment] 2020-12-15 18:47
I'm going to close this as a dupe of #604, though, as it's rougly the same issue but wasn't entirely fixed.

**Closed by jakebailey** 2020-12-15 18:47 UTC
Labels: triage
