### ISSUE TITLE
False positive: context managers and unreachable code

### ISSUE THREAD

**Issue by rmorshea** [microsoft/pylance-release#610] opened 2020-11-15 05:51 UTC
In the following block of code pylance incorrectly claims the commented lines of code are unreachable:

```python
from contextlib import contextmanager

@contextmanager
def context_manager_suppresses_error():
    try:
        yield
    finally:
        pass

with context_manager_suppresses_error():
    raise Exception()

with context_manager_suppresses_error():  # <-- these linse are marked as unreachable
    raise Exception()  # <-- these linse are marked as unreachable
```

Of course this is not true because the context manager does not allow errors in its body to raise.

**Comment by george-gca** [comment] 2020-11-16 17:36
The same happens in the following code:
```python
from typing import NoReturn

def make_nothing() -> NoReturn:
    print('do nothing')

print('got here')
make_nothing()
print('also got here') # <-- this line is marked as unreachable
```

if I remove the `NoReturn` type hint from the function it works fine

**Comment by erictraut** [comment] 2020-11-16 17:45
This is a duplicate of #494

**Comment by jakebailey** [comment] 2020-11-16 17:48
Yep.

Note that explicitly marking it as "NoReturn" really does mean anything after is dead (that's the intent of the type), so I won't view that as a bug.

**Closed by jakebailey** 2020-11-16 17:48 UTC
Labels: duplicate

**Comment by george-gca** [comment] 2020-11-16 20:45
@jakebailey so `NoReturn` means that the function never finishes its execution instead of indicating it does not return anything? Wow never thought of it that way, thanks.

**Comment by jakebailey** [comment] 2020-11-16 20:46
Correct; a function that "doesn't return anything" is actually returning `None`, which you'd type as `-> None`.
