### ISSUE TITLE
Pylance still report problems in excluded or ignored directories, even in a closed file

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/pylance-release#5896] opened 2024-05-18 11:41 UTC
Type: <b>Bug</b>

1. Add a directory in "python.analysis.ignore" and "python.analysis.exclude"
2. Leave a problem in the py or ipynb file in this directory
3. Close the file

Extension version: 2024.5.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.37GB free)|
|Process Argv|--crash-reporter-id deaad0bf-2897-480e-b8cf-04d2a61dc2e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31049070
a69g1124:31046351
pythonprc:31047982
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by Saltsmart** [comment] 2024-05-18 11:44
Here are some screenshots.
This problem seems to happen in large files or projects, as in this workspace.
These files contain private contents so I am sorry for unable to provide them.
![3](https://github.com/microsoft/pylance-release/assets/40828952/27d5c798-56e9-4c4e-bfd8-bca65490a495)

**Comment by heejaechang** [comment] 2024-05-18 23:32
we will need logs to figure out.

Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs)?

**Comment by Saltsmart** [comment] 2024-05-19 01:39
> we will need logs to figure out.
> 
> Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs)?

[Python Language Server for issue #5896.log](https://github.com/microsoft/pylance-release/files/15367254/Python.Language.Server.for.issue.5896.log)

Here is the log.

**Comment by heejaechang** [comment] 2024-05-20 13:01
by the way, I see this in the log

[BG(3)] Long operation: analyzing: git:/e%3A/Project/batterynet/datapreprocessing_and_plots.ipynb.py?%7B%22path%22%3A%22e%3A%5C%5CProject%5C%5Cbatterynet%5C%5Cdatapreprocessing_and_plots.ipynb%22%2C%22ref%22%3A%22~%22%7D#pylancePrefixCell (3138ms)

the request is coming from `git:/`, do you have some extensions that might send us the unexpected request?

**Comment by Saltsmart** [comment] 2024-05-21 02:37
@heejaechang Please refer to issue #5895 , these two issues sees to be caused by the same reason.

**Comment by rchiodo** [comment] 2024-05-21 16:23
I believe this issue is a duplicate of this error:

https://github.com/microsoft/pylance-release/issues/5402

Which is caused by how VS code tracks notebooks. It doesn't actually send us a close notification when the tab closes.

**Closed by rchiodo** 2024-05-21 16:23 UTC
Labels: needs repro
