### ISSUE TITLE
I would like to request for CodeLens integration for better code navigating

### ISSUE THREAD

**Issue by microhobby** [microsoft/pylance-release#6566] opened 2024-10-16 02:14 UTC
Currently the only code lens support seems to be for the status of tests. I would like to see code lens added to code in general that assist with code navigation by showing references and implementation of functions/classes.

EDIT: Also is not possible to vote on closed requests, so I'm opening it again to take a try ...

**Comment by debonte** [comment] 2024-10-16 23:00
This is a duplicate of https://github.com/microsoft/pylance-release/discussions/4740. We use discussion items in the Enhancement discussion category to track things that are not currently on our backlog but could be prioritized if there was enough interest from users. Please up-vote the existing discussion item. Thanks!

**Closed by debonte** 2024-10-16 23:00 UTC
Labels: needs repro
