### ISSUE TITLE
IntelliSense doesn't recognize automatically `Any type` in autocomplete  for functions parameter without annotation

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#1828] opened 2021-09-17 11:43 UTC
## Environment data

-   Language Server version: Pylance language server 2021.9.2
-   OS and version: 10.0.19043.1237
-   Python version: Python 3.8.8, Anaconda

## Expected behaviour

According to [PEP 484 - `Any` type](https://www.python.org/dev/peps/pep-0484/#the-any-type):

> A function parameter without an annotation is assumed to be annotated with Any. If a generic type is used without specifying type parameters, they are assumed to be Any:

> ```
> from typing import Mapping
> 
> def use_map(m: Mapping) -> None:  # Same as Mapping[Any, Any]
>     ...
> 
> ```

## Actual behaviour

Parameter without an annotation are being assumed to be "unknown" in the autocompletion:

![image](https://user-images.githubusercontent.com/57204023/133776672-841821ab-a9e9-43bc-9756-8fc49a013309.png)

The expected behavior should assume parameter without an annotation to be annotated with Any:

![image](https://user-images.githubusercontent.com/57204023/133776947-0b424add-2e4f-4833-ae53-169d6506bb51.png)

**Comment by erictraut** [comment] 2021-09-17 15:26
The behavior you're seeing is expected.

Pyright (the type checker that underlies pylance) distinguishes between two forms of `Any`. The first form is explicit, where `Any` has been specified in a type annotation. The second is implicit, where `Any` results from an omission. To distinguish between the two, it refers to the second form as `Unknown`. In most contexts, the two forms act the same. However, if you enable strict mode (or some of the specific diagnostic rules that strict mode implies), you will receive diagnostics when using a value whose type contains an `Unknown`.

If you disable type checking completely, all references to `Unknown` are replaced with `Any` in the text output. It appears that you have enabled type checking.

**Comment by jakebailey** [comment] 2021-09-17 17:09
I'm going to close this; this is very much by design.

**Closed by jakebailey** 2021-09-17 17:09 UTC
Labels: triage
