### ISSUE TITLE
Jupyter Notebooks imports not being resolved

### ISSUE THREAD

**Issue by the-rich-piana** [microsoft/pylance-release#6247] opened 2024-08-08 16:31 UTC
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: Pop_OS! 6.8 LTS
-   Python version: 3.10
-   Poetry version: 1.35.0

## Code Snippet
```
python
import pandas as pd
from pydantic import BaseModel, Field
from langchain.output_parsers import PydanticOutputParser

from langchain_core.prompts import PromptTemplate
from langchain.schema import HumanMessage
from langchain_openai import ChatOpenAI
import matplotlib.pyplot as plt
import numpy as np
from typing import List
import nest_asyncio


import aiohttp
import asyncio
```

![image](https://github.com/user-attachments/assets/5d616132-93ed-4511-9f45-72303886a371)

## Repro Steps

1. Import any package or module that is installed via Poetry

## Expected behavior

No import errors

## Actual behavior

`Import "numpy" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)` 

## Logs

```
XXX
```

**Comment by rchiodo** [comment] 2024-08-08 16:40
Thanks for the issue. Which kernel have you selected? I assume it's the one matching your poetry environment. 

Does the problem go away if you save the notebook and reload the VS code window? If so, then this should be a dupe of 
https://github.com/microsoft/vscode/issues/199800

**Comment by the-rich-piana** [comment] 2024-08-09 19:40
Yes it does go away whenI save and reopen the window. Must be a dupe then :+1: 

Using my local poetry .venv kernel

**Comment by luabud** [comment] 2024-10-29 18:16
Closing via https://github.com/microsoft/vscode-jupyter/pull/15967

**Closed by luabud** 2024-10-29 18:16 UTC
Labels: waiting for upstream, user responded, needs repro
