### ISSUE TITLE
No function parameter prompt when there is a function decorator

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#968] opened 2021-02-20 03:30 UTC
## Environment data

-   **Language Server version**: Pylance language server 2021.2.4-pre.1 (pyright 44e42fe5)
-   **OS and version**: Windows_NT x64 10.0.19042
-   **Python version**: Python 3.8.6
-   **Scikit-learn version**: 0.24.1

## Expected behaviour

As shown in the figure below, when I enter `SVR ()`, a function parameter prompt should appear.
![microsoft_server](https://user-images.githubusercontent.com/65096819/108582347-a0b86280-736d-11eb-9ca3-bda947af26b9.gif)
## Actual behaviour

As shown in the figure below, when I enter `SVR ()`, there is no function parameter prompt.
![pylance_server](https://user-images.githubusercontent.com/65096819/108582360-b9287d00-736d-11eb-9d28-dea82abf1d86.gif)

## Logs

```
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
[FG] parsing: d:\Python_Study\sklearn学习\支持向量机\test.py (1ms)
[FG] binding: d:\Python_Study\sklearn学习\支持向量机\test.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: d:\Python_Study\sklearn学习\支持向量机\test.py (1ms)
[BG(1)] binding: d:\Python_Study\sklearn学习\支持向量机\test.py (0ms)
Background analysis message: analyze
[BG(1)] analyzing: d:\Python_Study\sklearn学习\支持向量机\test.py ...
[BG(1)]   checking: d:\Python_Study\sklearn学习\支持向量机\test.py (14ms)
[BG(1)] analyzing: d:\Python_Study\sklearn学习\支持向量机\test.py (14ms)
Background analysis message: resumeAnalysis
[BG(1)] indexing: d:\Python_Study\sklearn学习\支持向量机\test.py [found 1] (0ms)
Indexing Done: d:\Python_Study\sklearn学习\支持向量机\test.py
Background analysis message: markFilesDirty
Background analysis message: analyze
```

# Solution

I commented out the function decorator statement `@_deprecate_positional_args` on `SVR.__init__()` and found that Pylance can work normally.
![pylance_server_ok](https://user-images.githubusercontent.com/65096819/108582520-e295d880-736e-11eb-91cd-60b36dc97883.gif)

## Code Snippet / Additional information

```python
from sklearn.svm import SVR

svr = SVR()
```

**Comment by judej** [comment] 2021-02-22 18:55
Thanks for the report. We will investigate this.

thanks

**Comment by erictraut** [comment] 2021-02-22 19:07
This is a duplicate of https://github.com/microsoft/pylance-release/issues/442

**Closed** 2021-02-24 23:22 UTC
Labels: duplicate, needs investigation
