### ISSUE TITLE
PEP 695 style type annotations cause the return type arrow (->) to be rendererd as invalid.illegal.annotation.python

### ISSUE THREAD

**Issue by willfrey** [microsoft/pylance-release#5767] opened 2024-04-16 07:11 UTC
Type: <b>Bug</b>

# Behaviour

When using the new PEP 695 type annotation for generics, the literal `->` that comes after the closing `)` and the return type gets assigned the `invalid.illegal.annotation.python` Textmate scope, which makes it stand out as invalid syntax despite it being okay.

## Steps to reproduce:

Open up a new editor and enter the following:

```python
def foo[T](bar: T) -> T:
    return bar
```

and notice that the `->` is flagged as an illegal annotation.

Extension version: 2024.4.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

testing
• pytestEnabled: true

experiments
• enabled: false

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|autoDocstring - Python Docstring Generator|njpwerner.autodocstring|0.6.1|
|Black Formatter|ms-python.black-formatter|2024.2.0|
|Bluloco Dark Theme|uloco.theme-bluloco-dark|3.7.4|
|Bluloco Light Theme|uloco.theme-bluloco-light|3.7.3|
|C/C++|ms-vscode.cpptools|1.19.9|
|C/C++ Extension Pack|ms-vscode.cpptools-extension-pack|1.3.0|
|C/C++ Themes|ms-vscode.cpptools-themes|2.0.0|
|CMake|twxs.cmake|0.0.17|
|CMake Tools|ms-vscode.cmake-tools|1.17.17|
|Conventional Commits|vivaxy.vscode-conventional-commits|1.25.0|
|crates|serayuzgur.crates|0.6.6|
|Dev Containers|ms-vscode-remote.remote-containers|0.354.0|
|Docker|ms-azuretools.vscode-docker|1.29.0|
|Dotenv Official +Vault|dotenv.dotenv-vscode|0.28.1|
|EditorConfig for VS Code|EditorConfig.EditorConfig|0.16.4|
|Even Better TOML|tamasfe.even-better-toml|0.19.2|
|Fish|bmalehorn.vscode-fish|1.0.38|
|GitHub Actions|github.vscode-github-actions|0.26.2|
|GitHub Copilot|GitHub.copilot|1.180.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.14.1|
|GitHub Pull Requests|GitHub.vscode-pull-request-github|0.86.1|
|GitHub Repositories|GitHub.remotehub|0.62.0|
|JavaScript Debugger|ms-vscode.js-debug|1.88.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|Jupyter|ms-toolsai.jupyter|2024.3.1|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Makefile Tools|ms-vscode.makefile-tools|0.9.10|
|Markdown All in One|yzhang.markdown-all-in-one|3.6.2|
|markdownlint|DavidAnson.vscode-markdownlint|0.54.0|
|Monokai Pro|monokai.theme-monokai-pro-vscode|1.2.2|
|Prettier - Code formatter|esbenp.prettier-vscode|10.4.0|
|Pylance|ms-python.vscode-pylance|2024.4.1|
|Python|ms-python.python|2024.4.1|
|Python Debugger|ms-python.debugpy|2024.4.0|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.110.1|
|Remote - SSH: Editing Configuration Files|ms-vscode-remote.remote-ssh-edit|0.86.0|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Remote Repositories|ms-vscode.remote-repositories|0.40.0|
|Rewrap|stkb.rewrap|1.16.3|
|Ruff|charliermarsh.ruff|2024.16.0|
|Rust Syntax|dustypomerleau.rust-syntax|0.6.1|
|shell-format|foxundermoon.shell-format|7.2.5|
|ShellCheck|timonwong.shellcheck|0.37.1|
|Sourcery|sourcery.sourcery|1.16.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.8|
|vscode-icons|vscode-icons-team.vscode-icons|12.7.0|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by debonte** [comment] 2024-04-16 15:25
Duplicate of https://github.com/microsoft/pylance-release/issues/4645. In particular, see https://github.com/microsoft/pylance-release/issues/4645#issuecomment-1813073964.

**Closed by debonte** 2024-04-16 15:25 UTC
Labels: needs repro

**Comment by willfrey** [comment] 2024-04-17 04:32
@debonte — apologies, I did a quick search and didn't see anything pop up. Thank you for pointing me to those issues!

**Comment by debonte** [comment] 2024-04-17 04:33
No worries. It's a bit weird because the issue in this repo is closed and we're tracking it with an internal work item that isn't visible to the public.
