### ISSUE TITLE
How to pupulate ```python.analysis.extraPaths``` with a pattern?

### ISSUE THREAD

**Issue by ThanasisMattas** [microsoft/pylance-release#5134] opened 2023-11-21 15:22 UTC
The problem is that the details of the project mutate often, however the structure is stable. Thus, a pattern like the following would be useful:

```json
"python.analysis.extraPaths": [
  "src\\foo\\*\\bar"
]
```

How can this behavior be reproduced?

(Pylance v2023.11.13)

**Comment by erictraut** [comment] 2023-11-21 17:59
This is a duplicate of [https://github.com/microsoft/pylance-release/discussions/2712]. 

The problem with supporting a globs pattern in `extraPaths` is that the order directories is significant when it comes to import resolution. For a `globs` pattern, the order would be arbitrary.

**Comment by ThanasisMattas** [comment] 2023-11-23 19:14
Got it, thank you. My project includes a specification file with the import hierarchy. I will try populating ```extraPaths``` with a script on build, as mentioned in the above discussion. Thanks again.

**Closed** 2023-11-26 14:00 UTC
Labels: duplicate
