### ISSUE TITLE
Unexpected intellisense behavior. Intellisense will show duplicate options

### ISSUE THREAD

**Issue by trickyrat** [microsoft/pylance-release#3731] opened 2022-12-07 16:13 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected: only one intellisense option

Actula: shows duplicate options
## Steps to reproduce:

1. Install python extension. Opening py or ipynb file and writing import directive.
2. The intellisense window will show duplicate options

![Screenshot_20221207_115859](https://user-images.githubusercontent.com/19605145/206232233-ba55022f-6fb3-4bcd-9058-ade04d142e5d.png)

![Screenshot_20221207_115840](https://user-images.githubusercontent.com/19605145/206231901-24b885b4-e45a-4826-b5f0-452295f8776e.png)

![Screenshot_20221207_115817](https://user-images.githubusercontent.com/19605145/206231916-606074f9-788f-418a-9ce9-1deed7009b0d.png)

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonSurveyNotification' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
Python interpreter path: .\venv\Scripts\python.exe
> conda info --json
> ./venv/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/printEnvVariables.py
> "C:\Program Files\Python311\python.exe" ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\interpreterInfo.py
> .\venv\Scripts\python.exe ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\interpreterInfo.py
Starting Pylance language server.

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• enabled: false
• mypyEnabled: true

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 4300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.30GB free)|
|Process Argv|--crash-reporter-id 32a31208-0215-4fc0-a102-0a44fac35e89|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by rchiodo** [comment] 2022-12-07 17:54
This is likely a dupe of #3674. Please make sure you have the latest jupyter extension and or have this setting enabled:

```json
"python.pylanceLspNotebooksEnabled": true
```

**Closed by rchiodo** 2022-12-07 17:54 UTC
Labels: triage-needed
