### ISSUE TITLE
Extension no longer autocompleting parentheses in functions on newest versions of VSCodium

### ISSUE THREAD

**Issue by jjlrjjlr** [microsoft/pylance-release#4878] opened 2023-09-23 01:21 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Parentheses should be added at the end of  functions when autocompleting, but since VSCodium 1.82.0 this no longer works with VSCode-Python versions past 2023.8.0. 

### Expectation: 

[Screencast from 2023-09-22 18-07-57.webm](https://github.com/microsoft/vscode-python/assets/39641251/5fd5dded-31e9-49aa-88fc-72bde772bdfc)

### What's currently happening:

[Screencast from 2023-09-22 18-06-59.webm](https://github.com/microsoft/vscode-python/assets/39641251/3ea9341e-7f84-424c-8c32-414fa7a2b77e)

## Steps to reproduce:

1. Launch version 1.82.0 or newer of VSCodium, with version 2023.10.0 or newer of the Python extension installed.
2. Attempt to autocomplete any function, such as 'print'.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Jedi"

```

</p>
</details>

Extension version: 2023.8.0
VSCodium version: VSCodium 1.82.2 (a5004432af6600c99fa4f918a3f2f8df44df71e6, 2023-09-14T18:27:11.315Z)
OS version: Linux x64 6.4.15-200.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 4441)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.45GB (9.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by BobWobRobLobNobSobGobYobCobFobMobHobJob** [comment] 2023-10-08 01:53
With print I do get the parentheses, however tkinter .pack for example doesn't get them.

**Comment by debonte** [comment] 2023-10-09 20:40
Dupe of https://github.com/microsoft/pylance-release/issues/4747

**Closed** 2023-10-09 20:40 UTC
Labels: needs repro
