### ISSUE TITLE
Jupyter extension cause remote ssh disconnect at opening *.ipynb file

### ISSUE THREAD

**Issue by maxwellzh** [microsoft/pylance-release#4986] opened 2023-10-19 09:19 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Reproduce steps:
1. Connect to remote server via ssh (my local machine is mac, remote one is a linux server)
2. Install jupyter extension on remote machine
3. open a *.ipynb file
Then vscode will pop up with a window telling remote server disconnect.

Ablation:
after disabling jupyter extension, everything works fine.

### VS Code Version

1.83.1 (Universal)

### Jupyter Extension Version

v2023.9.1102792234

### Running Jupyter locally or remotely?

Remote

**Comment by luabud** [comment] 2023-10-19 23:41
Dupe of https://github.com/microsoft/pylance-release/issues/4983.

**Closed by luabud** 2023-10-19 23:41 UTC
Labels: needs repro
