### ISSUE TITLE
Unrecognized metaclass

### ISSUE THREAD

**Issue by laipz8200** [microsoft/pylance-release#336] opened 2020-09-08 02:00 UTC
Issue Type: <b>Bug</b>

Pylance will prompt that metaclass is not defined, but the code can actually run

Extension version: 2020.9.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.15.0-115-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|Memory (System)|15.76GB (3.89GB free)|
|VM|0%|
</details>

**Comment by erictraut** [comment] 2020-09-08 02:11
Can you please provide a minimal code sample that exhibits this problem?

**Comment by laipz8200** [comment] 2020-09-08 02:18
> Can you please provide a minimal code sample that exhibits this problem?

```python
import re
import typing


class DrawingSchedulerMetaclass(type):
    def __new__(cls, name, bases, attrs) -> typing.Any:
        count = 0
        attrs['__drawing_function__'] = []
        for k, _ in attrs.items():
            if re.match(r'^draw_.*$', k):
                attrs['__drawing_function__'].append(k)
                count += 1
        attrs['__number_of_drawing_functions__'] = count
        return type.__new__(cls, name, bases, attrs)


class DrawingScheduler(metaclass=DrawingSchedulerMetaclass):

    @property
    def number_of_drawing_functions(self):
        """Number of drawing functions.

        :return: A number representing the number of functions.
        """
        return self.__number_of_drawing_functions_
```

prompt:

![prompt](https://ihs.arcadia.cool//laipz8200/20200908101719.png)

**Comment by erictraut** [comment] 2020-09-08 03:10
Thanks for the additional details. This is a duplicate of #322, and it will be fixed in the next release.

**Comment by jakebailey** [comment] 2020-09-14 21:04
#322 is closed as fixed; closing this one.

**Closed by jakebailey** 2020-09-14 21:04 UTC
Labels: duplicate
