### ISSUE TITLE
Incorrect NoReturn Annotation In Async Functions

### ISSUE THREAD

**Issue by A-kirami** [microsoft/pylance-release#4791] opened 2023-09-02 23:11 UTC
## Environment data

-   Language Server version: 2023.8.50
-   OS and version: Win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

I have encountered a similar issue to #4788, which addresses `NoReturn` annotations in synchronous functions. However, my problem relates to `NoReturn` annotations in asynchronous functions.

Here is a simplified example:

```python
from typing import NoReturn, Optional

async def raise_exc() -> NoReturn:
    raise Exception()

def get() -> Optional[int]:
    ...

async def main():
    x = get()  # int | None
    if x is None:
        await raise_exc()
    x.as_integer_ratio()  # pylance: "as_integer_ratio" is not a known member of "None"
```

In this example, even though the function `raise_exc()` is annotated with `NoReturn`, Pylance incorrectly infers the return type, resulting in a type-checking error.

**Expected Behavior:**
I expect Pylance to correctly infer the return type annotated with `NoReturn` in asynchronous functions, similar to the issue discussed in #4788 for synchronous functions.

**Comment by erictraut** [comment] 2023-09-03 00:08
This is a duplicate of https://github.com/microsoft/pyright/issues/5876.

**Closed** 2023-09-03 00:14 UTC
Labels: needs repro
