### ISSUE TITLE
Expected expression to the right of "=" - Pylance - Occuring Frequently

### ISSUE THREAD

**Issue by bnapora** [microsoft/pylance-release#811] opened 2021-01-06 17:29 UTC
Issue Type: <b>Bug</b>

Expected expression to the right of "=" - Pylance

Not sure how to reproduce.  Occurs frequently when using a Jupyter notebook in vscode.  Doesn't occur at start of session, but eventually appears.  

Believe its happening because Pylance is evaluating a line before typing is complete.

Makes  Insiders build challenging to use.  Doesn't occur with Pylance in regular vscode

Extension version: 2020.12.2
VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:23:04.938Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.39GB free)|
|Process Argv|--crash-reporter-id 38506a2c-65d8-493f-9dfe-2452f844c51c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|12.43GB (1.12GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by judej** [comment] 2021-01-06 18:45
Thanks for the report @bnapora. Does the diagnostic eventually disappear or does it persist indefinitely? If it disappears in a while, this is probably a dupe of #237

**Comment by bnapora** [comment] 2021-01-06 18:54
It disappears if I reload window.  I don't think it disappears without some type of reload, but I'm not certain on that.  

Looking at #237, that may provide a solution.  

However, there does seem to be a need for a change in defaults, or something to limit the occurrence of these types of alerts.  In this case, as soon as I press space bar after an = sign, the alert appears.  It usually disappears after a value is entered, but frequently it does not disappear.  (I haven't figured out what causes alert to not disappear.)

![image](https://user-images.githubusercontent.com/33367141/103808788-625d2300-500d-11eb-8b75-4eca89db4bdb.png)

**Comment by jakebailey** [comment] 2021-01-06 18:56
If this is in the jupyter notebook, then this could be an issue with the diagnostic range translation. It should only be putting the diagnostic at the last character where the syntax error is, not the entire file.

**Comment by jakebailey** [comment] 2021-01-06 18:58
(Similar is #761.)

**Comment by bnapora** [comment] 2021-01-06 19:02
Yes...this in a Jupyter notebook.  Looks like 761 is for similar issue.  I didn't realize Pylance wasn't fully working with Jupyter Notebooks yet for Insiders build.  Should I watch 761 for a resolution to this?

**Comment by jakebailey** [comment] 2021-01-06 19:04
It should work, but this would appear to be a bug. I don't know if that one is precisely the same or not. That bugfix would likely occur in the Python or Jupyter extension, but we'd need to trace the LSP logs and see what ranges we're returning to the client.

**Comment by bnapora** [comment] 2021-01-06 19:59
What else can I provide for assistance?

**Comment by jakebailey** [comment] 2021-01-06 20:02
If you can make a gist with some raw LSP logs of this happening, that would be helpful, but note that doing so will expose all file names and contents (so don't share it if you don't want to).

You can do this by setting `"python.trace.server": "verbose"`, reloading, then reproducing the issue, and the "Python Language Server" output will have a huge output with every message sent. With it, we could check and see if we are sending reasonable ranges.

Otherwise, we'll have to test and see ourselves.

**Comment by bnapora** [comment] 2021-01-06 20:08
I see HTML, JSON, CSS & TypeScript Trace Server but no Python.  Even though I'm using the Python Extensions:
![image](https://user-images.githubusercontent.com/33367141/103815187-d7355a80-5017-11eb-8dcf-ff9802f9662f.png)

**Comment by jakebailey** [comment] 2021-01-06 20:09
Sorry, use the JSON editor. I forgot people use the UI... 🙂 

It's not a documented setting, so just stick it in your user setting and it will work.

![image](https://user-images.githubusercontent.com/5341706/103815319-0a77e980-5018-11eb-9402-65ade8109999.png)

**Comment by bnapora** [comment] 2021-01-06 20:23
All that work creating a cool setting UI...I have to use it. =) 

Ok...able to duplicate issue.

As soon as = and then a space is entered get the following:
![image](https://user-images.githubusercontent.com/33367141/103816402-c554b700-5019-11eb-8e23-488866156451.png)

I believe I captured the full trace log in this gist.  Let me know if it doesn't contain what is needed.
https://gist.github.com/bnapora/0522aa5002d83aa834d30a40f3f80fb6

**Comment by jakebailey** [comment] 2021-01-07 00:53
Thanks for those logs. I don't see anything immediately wrong with them, but I'll have to look harder. I was looking for diagnostics with ranges that were out of bounds, but these don't seem too bad. Will take some more consideration, I suppose.

Unrelated, but it's moderately concerning that we're getting sent semantic token requests for cells but no other requests; we shouldn't get anything for cells from the notebook system at the moment...

**Comment by bnapora** [comment] 2021-01-07 17:46
Anything else I can provide to pin point issue?

Brian

**Comment by jakebailey** [comment] 2021-01-07 18:40
No, nothing at the moment. This just needs to be debugged.

**Comment by jakebailey** [comment] 2021-02-18 00:41
The Jupyter extension had its update today; is there any chance you could test again to see if this still happens? There were a number of fixes there that could have impacted this.

**Comment by bnapora** [comment] 2021-02-18 17:24
Attempted to validate on VSCode Insiders (Version 1.54.0-insider).  Was unable to open a *.ipynb file or even create one with "Jupyter: Create new notebook...".  Not sure what is going on.  I have not rebooted workstation yet, and can try that later today.  But currently when attempting to create or open a notebook file get an error like this: `Unable to open 'Untitled-1.ipynb': Cannot read property 'Code' of undefined.`

**Comment by jakebailey** [comment] 2021-02-18 19:02
That sounds like https://github.com/microsoft/vscode-jupyter/issues/4796 to me. Insiders keeps changing the notebooks API which makes it hard to target; the extension supports the stable build of VS Code.

**Comment by bnapora** [comment] 2021-02-19 06:32
Gotcha.  Yes the excessive alerting from the linter is no longer highlighting yellow underline after an = sign.
Thanks.

**Comment by jakebailey** [comment] 2021-02-19 18:36
I think you're implying that this is fixed, and it's not squiggling the entire cell. In that case, I think the issue can be closed, but if I'm incorrect in my interpretation we can reopen.

**Closed by jakebailey** 2021-02-19 18:36 UTC
Labels: waiting for info

**Comment by bnapora** [comment] 2021-02-19 18:37
Yes…FIXED
