### ISSUE TITLE
Highlighting can't understand impact of `locals()` on variable use

### ISSUE THREAD

**Issue by aaronrudkin** [microsoft/pylance-release#1921] opened 2021-10-08 22:03 UTC
## Environment data

-   Language Server version: 2021.10.0
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7 64-bit Windows

## Expected behaviour

Given code input:
```python
def func1(arg1, arg2):
    return locals()
```

arg1 and arg2 variables in the function signature should be coloured as though they are used in the function body; locals() automatically uses every local variable, including arguments.

## Actual behaviour

arg1 and arg2 variables in the function signature are coloured as though they are unused in the function body.

## Other info

You can see the same issue was solved in PyCQA/pylint#641 in 2015. I literally can't tell if this is driven by Pylance's semantic highlighting or another VSC component doing syntax highlighting, so if I've misdirected the bug let me know and I'll file it elsewhere.

**Comment by erictraut** [comment] 2021-10-08 23:27
These variables aren't referenced by name within the function, so they marked as unreferenced. There are many ways in a language as dynamic as Python for variables to be implicitly accessed at runtime by code outside of a function, and a static analyzer won't have knowledge of these. This is just one such case. I suppose we could special-case the `local()` function, but I don't know that it would solve any problems, and it would introduce an inconsistency in that we would sometimes mark variables as referenced even though they are not.

**Comment by judej** [comment] 2021-10-11 17:52
closing as dupe of #500

**Closed by judej** 2021-10-11 17:52 UTC
Labels: triage
