### ISSUE TITLE
Pylance seems to forget the selected interpreter after a (short) while: reportMissingImports

### ISSUE THREAD

**Issue by janfrederik** [microsoft/pylance-release#4606] opened 2023-07-14 12:51 UTC
<h3> Environment data </h3>

- Language Server version: 2023.7.20
- VS Code with Remote-SSH
- Remote OS and version: ubuntu linux 22.04
- Python version: 3.11.4 installed with pyenv
- python.analysis.indexing: true
- python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import numpy
```

<h3> Repro Steps </h3>

1. Open the source file.
2. Select Python interpreter: point to the python executable in the pyenv environment where numpy, matplotlib, pandas, ... are installed.  
    ![image](https://github.com/microsoft/pylance-release/assets/18148910/be3dac2c-e8d6-48e8-b27a-ed308ec11ae3)
3. No warnings and code completion and type info works well.
4. After some editing, lots of problems are shown because the imports could not be resolved.
    - Nothing changed to the selected interpreter
    - However, Pylance trace output shows that (at least part of) Pylance is still using the standard interpreter of Ubuntu.

<h3> Expected behavior </h3>

Pylance should only use the selected interpreter.

<h3> Actual behavior </h3>

![image](https://github.com/microsoft/pylance-release/assets/18148910/82bf93c6-7b69-4c30-8b0e-59273424eddb)

<h3> Settings files </h3>

User:
```json
{
    "workbench.colorTheme": "Default Dark+",
    "git.confirmSync": false,
    "git.autofetch": true,
    "remote.SSH.remotePlatform": {
        "dev": "linux"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "[python]": {
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.black-formatter"
    },
    "remote.SSH.connectTimeout": 60,
    "remote.SSH.enableAgentForwarding": false,
    "remote.SSH.enableX11Forwarding": false,
    "terminal.integrated.copyOnSelection": true,
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        }
    },
    "files.autoSave": "afterDelay",
    "terminal.integrated.defaultProfile.windows": "PowerShell",
    "terminal.integrated.env.linux": {
        "PYTHONPATH": "${workspaceFolder}",
    },
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "right"
    },
    "jupyter.askForKernelRestart": false,
    "notebook.output.scrolling": true,
    "editor.inlineSuggest.enabled": true,
    "github.copilot.enable": {
        "*": true,
        "plaintext": true,
        "markdown": true,
        "scminput": false
    },
    "notebook.diff.ignoreMetadata": true,
    "notebook.diff.ignoreOutputs": true,
    "git.openRepositoryInParentFolders": "never"
}
```

Remote-SSH ("Machine"):
```json
{
    "files.autoSave": "afterDelay",
    "python.venvPath": "/home/janfr/.pyenv/versions",
    "python.analysis.autoImportCompletions": true,
    "python.analysis.disableSemanticOnNoPython": true,
    "python.analysis.inlayHints.callArgumentNames": false,
    "python.analysis.inlayHints.functionReturnTypes": false,
    "python.analysis.inlayHints.pytestParameters": false,
    "python.analysis.inlayHints.variableTypes": false,
    "python.analysis.packageIndexDepths": [
        {
            "name": "sklearn",
            "depth": 2
        },
        {
            "name": "matplotlib",
            "depth": 3,
            "includeAllSymbols": true
        },
        {
            "name": "scipy",
            "depth": 2
        },
        {
            "name": "django",
            "depth": 2
        },
        {
            "name": "flask",
            "depth": 2
        },
        {
            "name": "fastapi",
            "depth": 2
        }
    ],
    "python.analysis.persistAllIndices": false,
    "python.terminal.focusAfterLaunch": true
}
```

Workspace:
```json
{
    "jupyter.askForKernelRestart": false,
    "python.analysis.typeCheckingMode": "basic", // off, basic or strict
    "python.analysis.logLevel": "Trace"
}
```

<h3> Modules installed in environment jkx-3.11.4 </h3>

```
janfr@dev:~$ ls /home/janfr/.pyenv/versions/3.11.4/envs/jkx-3.11.4/lib/python3.11/site-packages
ansi2html                                      ipywidgets                                prompt_toolkit-3.0.38.dist-info
ansi2html-1.8.0.dist-info                      ipywidgets-8.0.6.dist-info                psutil
anyio                                          isoduration                               psutil-5.9.5.dist-info
anyio-3.7.0.dist-info                          isoduration-20.11.0.dist-info             psycopg
appdirs-1.4.4.dist-info                        itsdangerous                              psycopg-3.1.9.dist-info
appdirs.py                                     itsdangerous-2.1.2.dist-info              psycopg_binary
argon2                                         jedi                                      psycopg_binary-3.1.9.dist-info
argon2_cffi-21.3.0.dist-info                   jedi-0.18.2.dist-info                     psycopg_binary.libs
_argon2_cffi_bindings                          jinja2                                    ptyprocess
argon2_cffi_bindings-21.2.0.dist-info          Jinja2-3.1.2.dist-info                    ptyprocess-0.7.0.dist-info
arrow                                          jkx                                       pure_eval
arrow-1.2.3.dist-info                          jkx-0.0.2.dist-info                       pure_eval-0.2.2.dist-info
asttokens                                      json5                                     __pycache__
asttokens-2.2.1.dist-info                      json5-0.9.14.dist-info                    pycparser
async_lru                                      jsonpointer-2.4.dist-info                 pycparser-2.21.dist-info
async_lru-2.0.2.dist-info                      jsonpointer.py                            pygments
attr                                           jsonschema                                Pygments-2.15.1.dist-info
attrs                                          jsonschema-4.17.3.dist-info               pylab.py
attrs-23.1.0.dist-info                         jupyter_client                            PyNaCl-1.5.0.dist-info
babel                                          jupyter_client-8.3.0.dist-info            pyparsing
Babel-2.12.1.dist-info                         jupyter_core                              pyparsing-3.1.0.dist-info
backcall                                       jupyter_core-5.3.1.dist-info              pyproject_hooks
backcall-0.2.0.dist-info                       jupyter_dash                              pyproject_hooks-1.0.0.dist-info
bcrypt                                         jupyter_dash-0.4.2.dist-info              pyrate_limiter
bcrypt-4.0.1.dist-info                         jupyter_events                            pyrate_limiter-2.10.0.dist-info
beautifulsoup4-4.12.2.dist-info                jupyter_events-0.6.3.dist-info            pyrsistent
bleach                                         jupyterlab                                pyrsistent-0.19.3.dist-info
bleach-6.0.0.dist-info                         jupyterlab-4.0.2.dist-info                _pyrsistent_version.py
bs4                                            jupyterlab_plotly                         pysftp
build                                          jupyterlab_pygments                       pysftp-0.2.9.dist-info
build-0.10.0.dist-info                         jupyterlab_pygments-0.2.2.dist-info       python_dateutil-2.8.2.dist-info
bump2version-1.0.2.dev0.dist-info              jupyterlab_server                         pythonjsonlogger
bumpversion                                    jupyterlab_server-2.23.0.dist-info        python_json_logger-2.0.7.dist-info
cattr                                          jupyterlab_widgets                        pytz
cattrs                                         jupyterlab_widgets-3.0.7.dist-info        pytz-2023.3.dist-info
cattrs-23.1.2.dist-info                        jupyter_lsp                               PyYAML-6.0.dist-info
certifi                                        jupyter_lsp-2.2.0.dist-info               pyzmq-25.1.0.dist-info
certifi-2023.5.7.dist-info                     jupyter.py                                pyzmq.libs
cffi                                           jupyter_server                            requests
cffi-1.15.1.dist-info                          jupyter_server-2.7.0.dist-info            requests-2.31.0.dist-info
_cffi_backend.cpython-311-x86_64-linux-gnu.so  jupyter_server_terminals                  requests_cache
charset_normalizer                             jupyter_server_terminals-0.4.4.dist-info  requests_cache-1.0.1.dist-info
charset_normalizer-3.1.0.dist-info             kiwisolver                                requests_ratelimiter
click                                          kiwisolver-1.4.4.dist-info                requests_ratelimiter-0.4.0.dist-info
click-8.1.3.dist-info                          lxml                                      retrying-1.3.4.dist-info
comm                                           lxml-4.9.2.dist-info                      retrying.py
comm-0.1.3.dist-info                           markupsafe                                rfc3339_validator-0.1.4.dist-info
contourpy                                      MarkupSafe-2.1.3.dist-info                rfc3339_validator.py
contourpy-1.1.0.dist-info                      matplotlib                                rfc3986_validator-0.1.1.dist-info
cryptography                                   matplotlib-3.7.1.dist-info                rfc3986_validator.py
cryptography-41.0.1.dist-info                  matplotlib-3.7.1-py3.11-nspkg.pth         send2trash
cycler-0.11.0.dist-info                        matplotlib_inline                         Send2Trash-1.8.2.dist-info
cycler.py                                      matplotlib_inline-0.1.6.dist-info         setuptools
dash                                           mistune                                   setuptools-65.5.0.dist-info
dash-2.11.0.dist-info                          mistune-3.0.1.dist-info                   six-1.16.0.dist-info
dash_bootstrap_components                      mpl_toolkits                              six.py
dash_bootstrap_components-1.4.1.dist-info      multitasking                              sniffio
dash_core_components                           multitasking-0.0.11.dist-info             sniffio-1.3.0.dist-info
dash_core_components-2.0.0.dist-info           nacl                                      soupsieve
dash_html_components                           nbclient                                  soupsieve-2.4.1.dist-info
dash_html_components-2.0.0.dist-info           nbclient-0.8.0.dist-info                  sqlalchemy
dash_table                                     nbconvert                                 SQLAlchemy-2.0.17.dist-info
dash_table-5.0.0.dist-info                     nbconvert-7.6.0.dist-info                 stack_data
dateutil                                       nbformat                                  stack_data-0.6.2.dist-info
debugpy                                        nbformat-5.9.0.dist-info                  tenacity
debugpy-1.6.7.dist-info                        nest_asyncio-1.5.6.dist-info              tenacity-8.2.2.dist-info
decorator-5.1.1.dist-info                      nest_asyncio.py                           terminado
decorator.py                                   notebook_shim                             terminado-0.17.1.dist-info
defusedxml                                     notebook_shim-0.2.3.dist-info             test
defusedxml-0.7.1.dist-info                     numpy                                     tinycss2
_distutils_hack                                numpy-1.25.0.dist-info                    tinycss2-1.2.1.dist-info
distutils-precedence.pth                       numpy.libs                                tornado
executing                                      overrides                                 tornado-6.3.2.dist-info
executing-1.2.0.dist-info                      overrides-7.3.1.dist-info                 traitlets
fastjsonschema                                 packaging                                 traitlets-5.9.0.dist-info
fastjsonschema-2.17.1.dist-info                packaging-23.1.dist-info                  typing_extensions-4.6.3.dist-info
flask                                          pandas                                    typing_extensions.py
Flask-2.2.5.dist-info                          pandas-2.0.2.dist-info                    tzdata
fontTools                                      pandocfilters-1.5.0.dist-info             tzdata-2023.3.dist-info
fonttools-4.40.0.dist-info                     pandocfilters.py                          uri_template
fqdn                                           paramiko                                  uri_template-1.3.0.dist-info
fqdn-1.5.1.dist-info                           paramiko-3.2.0.dist-info                  urllib3
frozendict                                     parso                                     urllib3-2.0.3.dist-info
frozendict-2.3.8.dist-info                     parso-0.8.3.dist-info                     url_normalize
git_filter_repo-2.38.0.dist-info               pexpect                                   url_normalize-1.4.3.dist-info
git_filter_repo.py                             pexpect-4.8.0.dist-info                   wcwidth
greenlet                                       pickleshare-0.7.5.dist-info               wcwidth-0.2.6.dist-info
greenlet-2.0.2.dist-info                       pickleshare.py                            webcolors
gunicorn                                       PIL                                       webcolors-1.13.dist-info
gunicorn-20.1.0.dist-info                      Pillow-9.5.0.dist-info                    webencodings
html5lib                                       Pillow.libs                               webencodings-0.5.1.dist-info
html5lib-1.1.dist-info                         pip                                       websocket
idna                                           pip-23.1.2.dist-info                      websocket_client-1.6.1.dist-info
idna-3.4.dist-info                             pkg_resources                             werkzeug
ipykernel                                      platformdirs                              Werkzeug-2.2.3.dist-info
ipykernel-6.23.3.dist-info                     platformdirs-3.8.0.dist-info              widgetsnbextension
ipykernel_launcher.py                          plotly                                    widgetsnbextension-4.0.7.dist-info
ipympl                                         plotly-5.15.0.dist-info                   _yaml
ipympl-0.9.3.dist-info                         _plotly_future_                           yaml
IPython                                        _plotly_utils                             yfinance
ipython-8.14.0.dist-info                       prometheus_client                         yfinance-0.2.22.dist-info
ipython_genutils                               prometheus_client-0.17.0.dist-info        zmq
ipython_genutils-0.2.0.dist-info               prompt_toolkit
```

<h3> Logs </h3>

[Pylance Trace output](https://github.com/microsoft/pylance-release/files/12050553/pylance.trace.txt)

**Comment by rchiodo** [comment] 2023-07-14 16:15
It looks to me like something is changing the current interpreter. Do you perhaps have more than one workspace folder open and you're switching back and forth between files? 

This output here says the current interpreter is just 'python3':

```
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)   Executing interpreter: 'python3'
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)   Skipping '/usr/lib/python310.zip' because it is not a valid directory
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)   Received 4 paths from interpreter
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)     /usr/lib/python3.10
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)     /usr/lib/python3.10/lib-dynload
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)     /usr/local/lib/python3.10/dist-packages
2023-07-14 12:25:32.011 [info] [Info  - 12:25:32 PM] (14561)     /usr/lib/python3/dist-packages
```

And it oscillates between that setting and the other one in your log:

```
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)   Executing interpreter: '/home/janfr/.pyenv/versions/3.11.4/envs/jkx-3.11.4/bin/python'
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)   Skipping '/home/janfr/.pyenv/versions/3.11.4/lib/python311.zip' because it is not a valid directory
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)   Received 3 paths from interpreter
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)     /home/janfr/.pyenv/versions/3.11.4/lib/python3.11
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)     /home/janfr/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload
2023-07-14 12:25:31.311 [info] [Info  - 12:25:31 PM] (14561)     /home/janfr/.pyenv/versions/3.11.4/envs/jkx-3.11.4/lib/python3.11/site-packages
```

Like one right after the other.

Is this setting on purpose? This might be the cause of the problem:

```
"python.venvPath": "/home/janfr/.pyenv/versions",
```

What does your python extension log output look like? Perhaps that setting is causing it to attempt to change the current intepreter continually?

The Python log should show it telling pylance what the interpreter path is. You can turn on trace logging for python with the 'Developer : Set Log Level" command and changing this to Trace: 

![image](https://github.com/microsoft/pylance-release/assets/19672699/993f802c-6c97-4f2e-aebb-c3a218bb8acf)

That should generate output like so in the Python output channel:

```
2023-07-14 09:13:05.018 [debug] Extension ms-python.vscode-pylance accessed getActiveEnvironmentPath with args: undefined
2023-07-14 09:13:05.021 [debug] Extension ms-python.vscode-pylance accessed resolveEnvironment with args: {"id":"C:\\USERS\\RCHIODO\\SOURCE\\TESTING\\TESTING_PYRIGHT\\.VENV\\SCRIPTS\\PYTHON.EXE","path":"c:\\Users\\rchiodo\\source\\testing\\Testing_Pyright\\.venv\\Scripts\\python.exe"}
2023-07-14 09:13:05.025 [debug] Extension ms-python.vscode-pylance accessed getEnvironmentVariables with args: undefined
2023-07-14 09:13:06.004 [debug] Couldn't locate the conda binary.
```

Which is the result of Pylance asking the Python extension what the active environment is for a file.

**Comment by janfrederik** [comment] 2023-07-14 17:21
Hi @rchiodo, thanks for helping me out!

I added 
```
"python.venvPath": "/home/janfr/.pyenv/versions",
```
to the settings in an attempt to make vscode to only use the interpreters in that folder instead of the system Python. But it didn't help, so I'll remove it.

I restarted the Language Server and traced both Python and the Python Language Server.
First everything was ok. At the end, the problem returned: none of installed libraries were found.

![image](https://github.com/microsoft/pylance-release/assets/18148910/144f2440-1e38-4bf7-9ce3-a324bb3e9b59)

Here the Python trace:

[python.trace.txt](https://github.com/microsoft/pylance-release/files/12052524/python.trace.txt)

And the Python Language Server trace:

[pylance.trace2.txt](https://github.com/microsoft/pylance-release/files/12052526/pylance.trace2.txt)

I have Pylanve v2023.7.20 and Python v2023.12.0

**Comment by rchiodo** [comment] 2023-07-14 17:34
The beginning of the log shows we're resolving paths for a notebook. What is the kernel being used in the notebook? That trumps the python interpreter selected for python files.

Additionally, do you have more than one workspace folder open?

**Comment by rchiodo** [comment] 2023-07-14 17:45
And the 'short' while might be the Jupyter extension loading the kernel back into the notebook. Before that happens we don't show any warnings in the notebook.

**Comment by janfrederik** [comment] 2023-07-14 17:48
Indeed, I'm running a notebook next to developing .py files.

The notebook is running on a remote server, so it is a remote kernel, accessed through https://. It has the same Python version and packages installed.

Today I had only one workspace open.

**Comment by rchiodo** [comment] 2023-07-14 17:52
Are the warnings showing up in the notebook or a python file? 

If the notebook is using a remote kernel we should be hiding all import errors. In fact, we can't really provide completions and such for a remote kernel because pylance has no idea what's running on the remote machine. But the hiding of errors I believe requires a pretty new version of the Jupyter extension. They have to pass us nothing for the kernel python path.

If the errors are in a python file, then something else is happening. I'd probably likely need to repro locally.

**Comment by janfrederik** [comment] 2023-07-20 07:32
The warnings are showing up in the Python file.  
No errors are showing up in the notebooks. I have Jupyter extension v2023.6.1101941928.

I disabled the Jupyter extension a few days ago and the import errors didn't come up again in my Python files.  
So the problem is the combination of Pylance and the Jupyter extension (at least using a remote kernel).

**Comment by rchiodo** [comment] 2023-07-20 16:07
Thanks for the response. I have a vague idea of what the problem might be. The jupyter kernel is changing the python path we use to perform analysis. Which makes sense from the notebook's point of view. However, the analysis happens on ALL open files and it's mistakenly applying the same path to the other open files and then pushing new diagnostics for the other files that are open. 

I can repro with a jupyter notebook if I set its kernel to a python environment that is missing things that are in the environment used for python files and I open a python file and the notebook.

**Comment by rchiodo** [comment] 2023-07-26 23:36
This issue has been fixed in prerelease version 2023.7.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023741-26-July-2023-PreRelease)

**Closed by rchiodo** 2023-07-26 23:36 UTC
Labels: bug, fixed in next version

**Comment by janfrederik** [comment] 2023-07-27 19:24
@rchiodo Thanks for the fast resolution!

Is there a way to select the interpreter environment that Pylance uses for the remote jupyter kernel? Or is it now the same as the environment selected for normal .py files?

**Comment by rchiodo** [comment] 2023-07-27 19:43
No each notebook actually has their own 'python environment'. If you select a remote jupyter kernel (like one with an https url), then the environment is the one on the remote machine. However, Pylance knows nothing about this remote environment and is basically disabled for the notebook.  Completions in that case actually come from the kernel itself.

However, the python files will use a local interpreter.

The bug here was that the remote kernel disables any environment for the notebook, but then the analysis of the notebook was also analyzing all the open python files too. And it was doing so with NO environment set, and hence the errors. The fix was to skip errors for files that weren't part of the same environment.

**Comment by GF-Huang** [comment] 2024-03-15 08:20
I encountered similar problem. It seems sometimes can not resolve, but sometimes works well.

![image](https://github.com/microsoft/pylance-release/assets/4510984/3a6442e2-89f0-4966-8123-fdcb6d06ff42)

**Comment by debonte** [comment] 2024-03-15 13:39
@GF-Huang, you may be hitting https://github.com/microsoft/vscode/issues/199800. If not, please open a new issue.

**Comment by GF-Huang** [comment] 2024-03-15 13:46
> @GF-Huang, you may be hitting [microsoft/vscode#199800](https://github.com/microsoft/vscode/issues/199800). If not, please open a new issue.

Thanks your guide. It seems the same issue to me. Relative issue (https://github.com/microsoft/pylance-release/issues/5172) for some who need more clue.
