### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5578] opened 2024-03-04 21:48 UTC
> RKucharski
> The plug-in works incorrectly. It informs about missing libraries or missing functions while the code is correct and runs without problems

RKucharski,
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments. If this does not address the issue, could you please add the information in this report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md?rgh-link-date=2024-03-04T21%3A41%3A09Z#filing-an-issue)?

**Comment by rchiodo** [comment] 2024-03-05 17:00
I would hazard a guess this is a dupe of this error:
https://github.com/microsoft/vscode/issues/199800

We think the interpreter for the second notebook is not set because VS code never tells us it changed. 

If you run a cell in the other notebook and then reload VS code, does it start working? (That should save the kernel selected to the notebook so we don't have to get a change kernel event)

**Comment by bao-lei** [comment] 2024-03-14 11:39
![Screenshot 2024-03-14 at 19 38 57](https://github.com/microsoft/pylance-release/assets/40864577/580469bc-902e-4faf-b71e-53f9fc1d3f56)
VS Code report warning as in the screenshot above. File name is some unknown symbol. But the program runs fine.

**Comment by rchiodo** [comment] 2024-03-14 16:40
@bao-lei, I'd recommend you look here for help on resolving imports. 
https://code.visualstudio.com/docs/python/editing#_importresolvefailure

If that doesn't help, your issue is likely a different one. Please open a new issue.

**Closed** 2024-04-14 00:25 UTC
Labels: waiting for user response, needs repro
