### ISSUE TITLE
No issues are highlighted in files that are located on a network drive

### ISSUE THREAD

**Issue by Aran-Fey** [microsoft/pylance-release#5371] opened 2024-01-19 22:19 UTC
When opening a file from a network drive, the editor doesn't highlight issues with red/yellow squiggly lines as it should. See this screenshot:

![image](https://github.com/microsoft/pylance-release/assets/22036272/88f262fe-8b0e-4db3-90ba-93d02f2b32b4)

Despite the code being obviously incorrect, it's not highlighted.

As you can see at the top, the file in question is `Z:\demo.py`. However, in the "Problems" tab at the bottom, the path of the file is `\\192.168.0.100\srv\nfs\general\demo.py`. This explains why the problem isn't highlighted: Because it's in a "different" file.

## Environment data

-   Language Server version (I assume this means "Pylance"): v2023.12.1
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.12

**Comment by rchiodo** [comment] 2024-01-19 23:21
Thanks for the issue. This should be a dupe of #5260 which should be fixed soon.

**Closed by rchiodo** 2024-01-19 23:21 UTC
Labels: needs repro
