### ISSUE TITLE
Duplicate Results

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#3530] opened 2022-10-25 00:36 UTC
![image](https://user-images.githubusercontent.com/26390254/197655290-a00e1538-8863-4f05-a13f-48ab85dda779.png)

I think it sensitive to the path. (`\Lib\` and '\lib\')

**Comment by Mahmood10marde** [comment] 2022-10-25 07:21
Mahmood10marde

**Comment by bschnurr** [comment] 2022-10-25 16:12
yup. do you have the pyright extension installed as well?

**Comment by byehack** [comment] 2022-10-25 16:36
@bschnurr No.
@rchiodo :
<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
codesnap | adp | 1.3.4
vscode-fake-virtual-space | Ant | 0.1.3
converttoasciiart | Bit | 1.0.3
wwbd | bre | 2022.1.0
bracket-select | chu | 2.0.2
curlconverter | cur | 0.0.3
fastcompare | Dav | 1.1.0
python-environment-manager | don | 1.0.4
vscode-jupytext | don | 0.1.0
gitlens | eam | 12.2.2
py-paste-indent | hye | 0.3.0
vsc-python-indent | Kev | 1.18.0
indent-nested-dictionary | mge | 0.0.4
fluent-icons | mig | 0.0.18
compare-folders | mos | 0.22.3
python | ms- | 2022.16.0
vscode-pylance | ms- | 2022.10.30
jupyter | ms- | 2022.9.1202862440
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.10
vscode-jupyter-cell-tags | ms- | 0.1.6
vscode-jupyter-slideshow | ms- | 0.1.5
hexeditor | ms- | 1.9.9
material-icon-theme | PKi | 4.21.0
sqlite-viewer | qwt | 0.1.5
trailing-spaces | sha | 0.4.1
selectline-statusbar | tom | 0.0.2
errorlens | use | 3.6.0

<span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(60, 60, 60); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(1 theme extensions excluded)</span>
</body>
</html>

**Comment by rchiodo** [comment] 2022-10-25 17:07
@byehack not sure about the profiles. I guess the thing would be to try it without. 

Additionally, if you could disable all extensions except python and pylance and see if it repros still? I don't believe any of those other extensions are providing hover for python, but I could be wrong.

**Comment by byehack** [comment] 2022-10-25 17:27
after extension bisect found this problem is from Jupyter extension

**Comment by debonte** [comment] 2022-10-25 17:43
Dupe of https://github.com/microsoft/vscode-jupyter/issues/11038?

**Comment by byehack** [comment] 2022-10-25 17:49
@debonte 
![image](https://user-images.githubusercontent.com/26390254/197845816-232b5d43-0748-481c-9b07-6cca30515b7a.png)

**Comment by byehack** [comment] 2022-10-25 17:53
fixed after disable `jupyter.pylanceHandlesNotebooks`.

**Comment by debonte** [comment] 2022-10-25 17:58
Why do you have `python.pylanceLspNotebooksEnabled` disabled?

**Comment by byehack** [comment] 2022-10-25 18:07
I don't know what the exact issue was, but I remember about 1 month ago it has some issues, and after i disabled the `python.pylanceLspNotebooksEnabled` issues gone.
unfortunately, I didn't report issues at that time.

**Comment by debonte** [comment] 2022-10-25 18:10
Ok, would you mind re-enabling it and filing any issues you run into?

If you find bugs with `"python.pylanceLspNotebooksEnabled": false` we're unlikely to fix them, since that is using our "legacy" notebooks support.

**Comment by byehack** [comment] 2022-11-12 08:13
after update to latest version again i get duplicate results.
it seems `python.pylanceLspNotebooksEnabled` removed?
![image](https://user-images.githubusercontent.com/26390254/201465103-b4c8d356-2af5-4a02-b708-edfb81485700.png)

**Comment by byehack** [comment] 2022-11-12 08:16
downgraded to 2022.16.1 to get back that option and disable it for fixing this bug.

**Comment by debonte** [comment] 2022-11-14 18:12
@byehack, `pylanceLspNotebooksEnabled` is now always on in recent builds.

There was a recent regression in the Jupyter extension that was causing duplicates though. Can you try upgrading to the latest pre-release build of Jupyter and see if the issue goes away?

See https://github.com/microsoft/vscode-jupyter/issues/11938#issuecomment-1306103766

**Comment by whoeverim5** [comment] 2022-11-20 09:40
@debonte 

| Extension | Version |
| ---------- | --------- |
| Jupyter | v2022.11.1003241024(pre-release) |
| Pylance | v2022.11.30 |
| Python | v2022.18.2 |

After upgrading to the pre-release build of Jupyter, the problem is only partially solved:
Duplicate intellisense only appear in those variables I imported and only happen when I run the notebook once, otherwise everything works well.
## before running
![issue1](https://user-images.githubusercontent.com/76519998/202894788-acc2332a-6f71-4142-a281-29857465393f.png)

![issue2](https://user-images.githubusercontent.com/76519998/202894807-27dcb8c7-64bd-4ddd-ade1-8ef4d6309c5c.png)
## after running
![issue3](https://user-images.githubusercontent.com/76519998/202894812-148f98f9-8b1e-48ba-a349-eaccd1744ca3.png)
## only appear in those variables I import and other variables works well
![issue4](https://user-images.githubusercontent.com/76519998/202894822-eadd1a96-1054-4a4b-887e-cfa91dc5bc44.png)

**Comment by debonte** [comment] 2022-11-21 18:51
@whoeverim5, what you're seeing is https://github.com/microsoft/vscode-jupyter/issues/11038.

**Closed by debonte** 2022-11-21 18:51 UTC
Labels: bug
