### ISSUE TITLE
Countless false positive errors

### ISSUE THREAD

**Issue by roboserg** [microsoft/pylance-release#1710] opened 2021-08-23 02:58 UTC
Working with jupyter notebooks (.ipynb) inside VS Code. Pylance throws countless errors on my code + often doesn't show the docs. Something is broken with it (maybe bad support for notebooks?). 

Could the magic line of the notebook be what breaks it? https://i.imgur.com/zNqQP60.png
How can I make Pylance ignore it?

Video: https://streamable.com/uhb5h9
More examples of fictitious errors https://i.imgur.com/BIIOExd.png

Pylance: v2021.8.2
Pylance language server: 2021.8.2 (pyright f462f5bb)
Python:  3.8.5 
Win10 latest updates

![Code_NaWZaPeoFq](https://user-images.githubusercontent.com/4758917/130383832-ae1e0f76-9b55-491b-9c03-c9ef8badfd38.png)
![Code_L9Nb1GC4Yb](https://user-images.githubusercontent.com/4758917/130383835-f21319cc-dfe9-44e8-b38a-f360bc00f418.png)

**Comment by jakebailey** [comment] 2021-08-23 17:16
Does your notebook contain markdown cells? If it does, it may be a dupe of #1521.

**Comment by roboserg** [comment] 2021-08-23 22:35
> Does your notebook contain markdown cells or other non-Python cells? If it does, it may be a dupe of #1521.

Yes, several. The notebook starts with this - https://i.imgur.com/UQl7ZMe.png
And later markdown cells - https://i.imgur.com/55bbtyy.png

Is the issue with non python code? If so, is there a way to tell Pylance to ignore it?

**Comment by jakebailey** [comment] 2021-08-23 23:54
Thanks, that is more evidence that it's #1521 and that we know what's wrong (at least, where to start debugging).

We believe the issue is when you try and edit the non-python cells in a notebook, confusing the code that gives Pylance the cells as a single file. Pylance itself has no knowledge of notebooks, only the faked file that is generated in the Python extension.

**Closed by jakebailey** 2021-08-23 23:54 UTC
Labels: waiting for user response

**Comment by roboserg** [comment] 2021-08-24 01:23
Thanks, will await your fixes :) I must say VS Code is truly awesome for notebooks, the best of the IDEs I know of.
