### ISSUE TITLE
PEP 695 Type parameter syntax of functions causes red return arrow

### ISSUE THREAD

**Issue by Kuba314** [microsoft/pylance-release#4974] opened 2023-10-17 20:21 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.10.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from typing import TypeVar


TValue = TypeVar("TValue")

def old_unity(value: TValue) -> TValue:  # this arrow is white
    return value

def new_unity[T](value: T) -> T:  # this arrow is red, not underlined
    return value
```

<h3> Repro Steps </h3>

Load the provided snippet and look at the color of the return-type arrow in both functions. This happens only when the square brackets after the function name are there.

![image](https://github.com/microsoft/pylance-release/assets/35199722/31e09151-0934-4543-88ec-5fefbc98ca54)

**Comment by erictraut** [comment] 2023-10-17 20:26
This is a duplicate of https://github.com/microsoft/pylance-release/issues/4645. It needs to be fixed in VS Code, which ships the TextMate grammar for Python.

**Closed** 2023-10-17 20:27 UTC
Labels: duplicate
