### ISSUE TITLE
Pylance causes a huge CPU load

### ISSUE THREAD

**Issue by barthemius** [microsoft/pylance-release#1388] opened 2021-06-03 08:52 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.6.0
-   OS and version: macOS Big Sur 11.4 (20F71)
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.8.8 x64 Anaconda

<h3> Expected behaviour </h3>

Pylance swiftly analyses the code and highlights the variables (just like week ago).

<h3> Actual behaviour </h3>

A process called 'Code Helper (Renderer)' uses >100% of CPU for approx 30-50 seconds. I tracked it by PID and unfortunately Pylance is the culprit, switching to a different language server is a remedy.
About the problem - every little change in the code triggers the whole process again. Variable name colouring update takes like a minute.
This issue might be related to #1368 reported by xmatthias. However there, he described the problem occurring in the big project. Here the file I am working on is a short, merely 50 line python script. Additionally I run on a different OS.

What surprises me the most, using older versions of Pylance didn't work at all. I somehow relate this bug to the recent macOS update, but I don't know if it is relevant.

I guess the description I've given might be a bit vague, as I am not familiar with bug reporting like this. However I will happily answer any questions you might have.

<h3> Logs </h3>

For convenience, I put the log in the attachment.
[pylance_problem.log](https://github.com/microsoft/pylance-release/files/6590161/pylance_problem.log)

**Comment by jakebailey** [comment] 2021-06-03 18:06
It appears as though this is sympy, which has some known performance holes and will need some stubs.

**Comment by barthemius** [comment] 2021-06-03 18:20
> It appears as though this is sympy, which has some known performance holes and will need some stubs.

Yup, you're absolutely right! I uninstalled sympy and it works fine right now. Too bad I need sympy for my research... :(

**Comment by erictraut** [comment] 2021-06-03 19:06
As a potential workaround, you could create a dummy type stub for sympy. This approach should eliminate the large CPU usage, but the tradeoff is that you won't get any completion suggestions for sympy. 

To do this, create a file in your project called `typings/sympy/__init__.pyi`. Within that file, include the following:

```python
from typing import Any

def __getattr__(name: str) -> Any: ...
```

This will tell pylance that it shouldn't attempt to infer any type information from the sympy library.

**Comment by barthemius** [comment] 2021-06-04 07:30
That should do the trick, at least for now. Thank you Eric!

**Comment by jakebailey** [comment] 2021-07-14 18:31
Dupe of #1388.

**Closed by jakebailey** 2021-07-14 18:31 UTC
Labels: in backlog, needs investigation, needs stub

**Comment by mjpieters** [comment] 2021-07-15 07:42
@jakebailey you closed this as a duplicate of itself, did you mean to do that? Looking at the history, I think you meant to reference #946 instead?

**Comment by jakebailey** [comment] 2021-07-15 07:43
Yes, my mistake! Copy paste always gets me.
