### ISSUE TITLE
Crash on start: TypeError: [....] is not a function

### ISSUE THREAD

**Issue by dsforetellix** [microsoft/pylance-release#5042] opened 2023-10-29 06:59 UTC
Pylance stopped working after installing version 2023.10.50. No more code highlight, completion ..... nothing works

Went back to version 10.40 and everything went back to normal

## Environment data

-   Language Server version: 2023.10.50
-   OS and version: vs code on Windows 11,  Using ssh on an Ubuntu 20 .04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Repro Steps

Crash on vs code startup

## Logs

Log attached

**Comment by SwaggyZhang** [comment] 2023-10-29 11:57
> Pylance stopped working after installing version 2023.10.50. No more code highlight, completion ..... nothing works
> 
> Went back to version 10.40 and everything went back to normal
> 
> ## Environment data
> * Language Server version: 2023.10.50
> * OS and version: vs code on Windows 11,  Using ssh on an Ubuntu 20 .04
> * Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
> 
> ## Repro Steps
> Crash on vs code startup
> 
> ## Logs
> Log attached

I have the same problem on my windows 11. Therefore, I have to use version 10.40

**Comment by debonte** [comment] 2023-10-29 15:34
Duplicate of #5009. Please switch to pre-release build 2023.10.53.

**Closed by debonte** 2023-10-29 15:34 UTC
Labels: needs repro

**Comment by JuhaKalevi** [comment] 2023-11-02 02:41
Same problem here but will try the suggested fix.
