### ISSUE TITLE
Feature Request: Option to Hide Internal Members and Methods in Autocomplete

### ISSUE THREAD

**Issue by sfaroy** [microsoft/pylance-release#6581] opened 2024-10-20 10:13 UTC
When typing an object name followed by a period, the autocomplete currently lists all available members and methods. It would be really helpful to have an option to hide internal members and methods (those prefixed with an underscore) from this list during autocomplete, as the full list can sometimes be overwhelming for the user.

For cases where the "self" object is being accessed within a class, it would be ideal for all members to still be displayed by default.

**Comment by debonte** [comment] 2024-10-21 19:11
Thanks for the issue. This is a duplicate of https://github.com/microsoft/pylance-release/discussions/3797. Please up-vote that enhancement discussion.

**Closed by debonte** 2024-10-21 19:11 UTC
Labels: needs repro
