### ISSUE TITLE
Unpacking multiple iterables yields false negatives

### ISSUE THREAD

**Issue by derhintze** [microsoft/pylance-release#2371] opened 2022-02-11 08:14 UTC
## Environment data

-   Language Server version: 2022.2.1 (pyright 618f54ed)
-   OS and version: Red Hat 4.8.5-44
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1

## Expected behaviour

To not flag anything as wrong.

## Actual behaviour

Multiple errors errors found:

- Expected expression
- Expected ":"
- Only one unpack operation allowed in list

## Logs

```
(25626) Background analysis message: setFileOpened
(25626) Background analysis message: getDiagnosticsForRange
(25626) Background analysis message: getDiagnosticsForRange
(25626) Background analysis message: getSemanticTokens full
(25626) [BG(1)] getSemanticTokens full at /radarugs/hintze/s4-cnc-tools/test.py (5ms)
(25626) Background analysis message: analyze
```

## Code Snippet / Additional information

The following executes w/o problems in Python:

```python
a = [1, 2]
b = ["3", "4"]

for x in *a, *b:
    print(x)

c = *a, *b
print(c)

```

Yields the following output:

```
1
2
3
4
(1, 2, '3', '4')
```

But pylance marks the first `*` in line 4 (the `for`-loop) with `Expected expression`, the colon in the same line as `Expected ":"`, and the second unpacking in line 7 (where `c` is assigned) as `Only one unpack operation allowed in list`.

This is probably (partly?) related to #700.

**Comment by derhintze** [comment] 2022-02-11 08:39
also note that this syntax is only valid for Python >= 3.9

**Comment by erictraut** [comment] 2022-02-11 08:41
Thanks for the bug report. I wasn't aware of this change to the grammar in Python 3.9. Since this is a core type checker issue, I've created a tracking bug in the pyright repo. https://github.com/microsoft/pyright/issues/3029

**Comment by erictraut** [comment] 2022-02-11 09:09
This will be fixed in the next release.

**Comment by debonte** [comment] 2022-02-17 01:42
This issue has been fixed in version 2022.2.3, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202223-16-February-2022)

**Closed by debonte** 2022-02-17 01:42 UTC
Labels: bug, fixed in next version

**Comment by realworldhacker** [comment] 2023-09-15 19:45
expected expression error in visual studio code from an elif statement I tried to run. parenthesis only fixed if statement error, I', finding a hard time finding a solution for my current problem. following a PyCharm tutorial btw; but I'm having a hard time downloading it.

**Comment by debonte** [comment] 2023-09-19 19:14
@realworldhacker, I copied the code from that spot in the video (see below) and Pylance doesn't show any errors for me, so I'm assuming you have a typo somewhere in the code. One wild guess is that you typed `elif` instead of `else` on the second to last line.

If you believe that there is a problem with Pylance here, please open a new issue and include a minimal code snippet that reproduces the problem.

```python
fnum = input("What is the first number ")
snum = input("What is the second number")

if fnum > snum:
    print("The first number is larger!")
elif snum > fnum:
    print("The second number is larger. ")
else:
    print("The numbers are the same")
```
