### ISSUE TITLE
Vscode is slow at renaming folders

### ISSUE THREAD

**Issue by pablo-s-dev** [microsoft/pylance-release#6059] opened 2024-06-25 19:55 UTC
Type: <b>Bug</b>

It seems like if you keep pylance enabled and try to rename a folder, then it will take a decade. At least that was the conclusion of troubleshooting bisect feature of VS Code.

Extension version: 2024.6.1
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.9.3-76060903-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 8, 7|
|Memory (System)|11.50GB (0.74GB free)|
|Process Argv|--ms-enable-electron-run-as-node --extensions-dir=/home/ps/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --crash-reporter-id e4665169-1ac6-4103-b7df-9cb70c0a8970|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31082723

```

</details>

**Comment by rchiodo** [comment] 2024-06-25 20:03
Thanks for the issue. This should be a dupe of https://github.com/microsoft/pylance-release/issues/5475

**Closed by rchiodo** 2024-06-25 20:03 UTC
Labels: needs repro
