### ISSUE TITLE
Autocomplete unavailable on some module

### ISSUE THREAD

**Issue by build960o** [microsoft/pylance-release#2520] opened 2022-03-31 15:30 UTC
## Environment data

-   Language Server version: v2022.3.4
-   OS and version: macOS 10.12.6
-   Python version: 3.7.9 
-   Distribution: Miniconda

## Expected behaviour

I use `from gurobipy import *` to import a module named **Gurobi**(a math programming solver), but Pylance doesn't identify its functions and hence **Autocomplete doesn't work**. 

When I switch python language server to Jedi, the problem disappeared. If it occurs because of lack of support for some modules?

## Actual behaviour

Several warnings at the module's functions, such as:
"Model" is not defined
"GRB" is not defined

**Comment by judej** [comment] 2022-03-31 17:42
Thanks for the report, unfortunately, this is not enough data for us to debug. 

Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by build960o** [comment] 2022-04-01 01:35
### My "settings.json" about python

```    "python.analysis.completeFunctionParens": true,
    "python.analysis.extraPaths": [
        "/Users/x/miniconda3/lib/python3.7/site-packages",
        "/Users/x/miniconda3/pkgs"
    ],
    "python.analysis.logLevel": "Trace"
```
### Code example
```
from gurobipy import *

try:
    m = Model()

    x = m.addVar(vtype=GRB.BINARY, name='x')
    y = m.addVar(vtype=GRB.BINARY, name='y')
    z = m.addVar(vtype=GRB.BINARY, name='z')

    m.setObjective(x+y+2*z, GRB.MAXIMIZE)

    m.addConstr(x+y >= 1, 'c1')

    m.optimize()

    for v in m.getVars():
        print(v.varName, v.x)
    
    print(m.objVal)

except GurobiError as e:
    print('Error code' + str(e.errno) + ':' + str(e))

except AttributeError:
    print('Encountered an attribute error')
```

### Environment 
Python version: 3.7.9
Virtual environment: Miniconda
Files attached: [environment_requirements.zip](https://github.com/microsoft/pylance-release/files/8393961/environment_requirements.zip)

### Log
[log.txt](https://github.com/microsoft/pylance-release/files/8393976/log.txt)

**Comment by heejaechang** [comment] 2022-04-08 23:09
@build960o that is because the package has compiled module that we currently don't support due to various reasons. Jedi can handle it since it loads that compiled module and inspects it which we currently avoid since we don't want to run random modules on users machine.

but we do ship with a script that let you generate stubs from compiled module if you want to. if you look at your pylance extension folder, there should be scrape_module.py (ex, ms-python.vscode-pylance-2022.4.1\dist\scripts\scrape_module.py),

you can manually run that script to generate stub file, that you can put inside of typing folder so we can pick it up.

thank you

**Comment by heejaechang** [comment] 2022-04-08 23:10
I am closing it as "by design"

**Closed** 2022-04-08 23:13 UTC
Labels: needs investigation

**Comment by build960o** [comment] 2022-05-06 09:38
Thanks a lot for your reply!
I probably understand what I should do to generate stub, but I have been confused about some details.

The comment in "scrape_module.py" says I should use a command like
`python -W ignore -B -E scrape_module.py cv2.cv2 C:\Python3\Lib\site-packages > cv2.pyi`

The problem is, I don't know the exact compiled module name of _gurobi_ to replace "cv2.cv2" within this command. I only know that I use the module by `from gurobipy import *`. **How can I determine this part?** 

Does this module need explicit search path?

By the way, I'm unable to locate anything like *****.pyd** under "_/Users/x/miniconda3/lib/python3.7/site-packages_". The file structures are listed below(I use macOS instead of Windows):

- **/Users/x/miniconda3/lib/python3.7/site-packages**
  - gurobi.so
  - **gurobi**
    - \_\_init__.py
    - **\_\_pycache__**
      - \_\_init__.cpython-37.pyc
