### ISSUE TITLE
VS code freezes in notebook editor on latest version of pylance

### ISSUE THREAD

**Issue by amunger** [microsoft/pylance-release#2806] opened 2022-05-12 17:53 UTC
Issue Type: <b>Bug</b>

1. create a new notebook
2. add a second cell
3. type 'print' in the second cell

result: VS code is frozen

Extension version: 2022.5.1
VS Code version: Code - Insiders 1.68.0-insider (624bbc4fb966bfa34e9486e320a64a138ac337fd, 2022-05-12T05:20:55.891Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (19.51GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30475216
vsclangdc:30480125

```

</details>

**Comment by amunger** [comment] 2022-05-12 17:54
same as https://github.com/microsoft/vscode-jupyter/issues/9936. only occurs on latest version of Pylance

**Comment by bogurd** [comment] 2022-05-12 19:54
I believe this is a duplicate of #2783, perhaps you can comment your logs there?

**Closed** 2022-05-12 20:04 UTC
Labels: triage
