### ISSUE TITLE
'module' is not Accessed Pylance(Pylance is greyed out)

### ISSUE THREAD

**Issue by pybash1** [microsoft/pylance-release#757] opened 2020-12-21 10:53 UTC
When I am importing the python module 'requests'. PyLance or VSCode underlines it with yellow meaning warning. It is also shown in the problems panel in the integrated terminal of vscode. Hope it gets fixed soon. I did not use the Bug Report Template because I am not sure if it is a bug.
![Refference Image or Screenshot](https://user-images.githubusercontent.com/67195650/102769507-bc70ae00-43a8-11eb-9121-0f272ce69c1e.png)

**Comment by play4Tutorials** [comment] 2020-12-22 12:52
I guess I should not ask this... But why did you transfer this issue?

**Comment by judej** [comment] 2020-12-22 18:43
Pylance is greyed out because Pylance is the reporter of the error. With regard to the unresolved import warning, please take a look at the trouble shooting guide: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by play4Tutorials** [comment] 2020-12-23 03:59
Ok..that explains it.

**Comment by play4Tutorials** [comment] 2020-12-23 09:37
By the could you tell me what more info you need? I would be happy to help you... Because you added the `waiting for info` label...

**Comment by jakebailey** [comment] 2021-01-04 19:58
Our issue template typically asks for logs; you may have selected the "question" which is more discussion based. I'd be interested in seeing some trace logs to see what paths are being used and what files are analyzed.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue mirrors the template instructions.

**Comment by play4Tutorials** [comment] 2021-01-17 10:56
Update - 
After changing my interpreter from Python 3.7 to Anaconda Python 3.8.3 in VSCode

The issue was that I had python 3.7 selected in VSCode as my default interpreter but my os's default interpreter was conda 3.8.3 so all of my packages were installed there. But since Py 3.7 was selected in VSCode, Pylance thought it was not installed since it was installed for conda 3.8.3 and were not for py 3.7.

But due to some odd reason running it with 3.7 didn't give any error and  was able to use the modules.

But I dont know why Pylance does this when I am importing a local file.

**Comment by play4Tutorials** [comment] 2021-01-17 10:57
@erictraut was actually correct in his 2nd comment

**Comment by jakebailey** [comment] 2021-01-19 20:50
Your original issue was about requests, which isn't a local module (it'd be an installed package). You're now mentioning a local import, can you describe this setup at all? Are you assuming some `sys.path` modification that needs to be configured so we can find the import? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by play4Tutorials** [comment] 2021-01-29 09:56
Ok, let me explain.
----------------------------------------------------------------------------------------------------------------------------------------------
Terms used:
pip - pip3
Py, py - Python3
Conda, conda - Anaconda3
----------------------------------------------------------------------------------------------------------------------------------------------
First I was trying to import requests, wget and some more modules. But it showed this error. Now few days back I just found out that inside VSCode my python interpreter was selected as Py3.7. But conda3.8.3 was my windows default interpreter. And thus all modules installed using pip were installed there. But PyLance tried to find in Py3.7 and they were not present. But the scripts never showed an error because when I was executing them through the terminal, they actually getting executed in Conda3.8.3. So when i changed my interpreter from py3.7 to conda3.8.3 in vscode all those errors were gone. And that fixed it.
---------------------------------------------------------------------------------------------------------------------------------------------
But now if I try to import a local file. Executing it doesn't give any error. And workd fine. But Pylance Shows the error.
---------------------------------------------------------------------------------------------------------------------------------------------
Hope this helps you. So could you fix so that importing local modules doesn't give an error. And also, PyLance says, this is a warning not an error. If you want I can attach a screenshot.
---------------------------------------------------------------------------------------------------------------------------------------------
A suggestion - could you make the warning underlines yellow instead of green, that would be better. Since, green kind of means there are no issue.

**Comment by play4Tutorials** [comment] 2021-01-29 09:56
Don't know why everything became a "h1"?

**Comment by jakebailey** [comment] 2021-01-29 17:14
Pylance respects the interpreter chosen by the Python extension; if you have the wrong interpreter selected then we can't really do anything about that.

We want to show import resolution messages as they significantly impact the analysis. If you really don't care about import warnings, you can use diagnosticSeverityOverrides and silence them. This to me is a bad idea, as it means all of the info you're working with is silently wrong.

For local modules, your project layout may mean you need to set extraPaths: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#common-questions-and-issues

RE: h1, github issues are markdown, and putting `----` on the line after text makes it a header. I've edited your comment to make it readable again.

**Comment by play4Tutorials** [comment] 2021-01-31 12:28
Thanks for the edit... yeah i know the interpreter was my bad, sorry. But I don't know about the local modules. I can set extraPaths, but previously I never had to that. So I said. And the warnings are yellow, they are green because of my theme. And I used diagnosticSeverityOverrirdes and set it to information. that way it doesn't show a warning and I still get the info. Thanks. But could you make it so that I don't need to set extraPath for local modules.

**Comment by jakebailey** [comment] 2021-02-01 20:13
The thing I'm curious about is "previously I never had to that"; previously meaning what? With a previous version of Pylance? With another language server setting? In another editor?

**Comment by play4Tutorials** [comment] 2021-02-02 12:18
> The thing I'm curious about is "previously I never had to that"; previously meaning what? With a previous version of Pylance? With another language server setting? In another editor?

"previously I never had to do that" means with another language server. That is with the default Python extension from Microsoft.

**Comment by jakebailey** [comment] 2021-02-02 19:37
I see. The previous default is Jedi, which has a pretty loose/forgiving import resolution system that favors resolving modules rather than erroring when they may not actually work at runtime. For local stuff, Pylance's behavior matches MPLS and other analyses that are more strict and try to inform of these issues. I don't know that we're likely to try and change that behavior, as we try to be as spec-compliant as possible (even if some projects require some extra configuration; most do not). The troubleshooting docs do describe this "import not resolved" message as much as possible for this reason.

What'd be most helpful is a description of your repo layout, in case it's something we can attempt to detect or handle through other means.

**Comment by play4Tutorials** [comment] 2021-02-06 11:38
What do you mean by repo layout? the file structure or hierarchy?

**Comment by jakebailey** [comment] 2021-02-06 20:15
The folder layout, and how the files import each other.

I'm talking the languageServer setting; Pylance is an option you had to configure to enable. If unset, that means jedi.

**Comment by play4Tutorials** [comment] 2021-02-09 11:58
Re: I didn't configure Pylance manually I just installed it from the extension store.

**Comment by play4Tutorials** [comment] 2021-02-09 12:43
The Folder Layout:
A lot to type, so attaching images.

Folder Layout:
![image](https://user-images.githubusercontent.com/67195650/107364904-1157b780-6b02-11eb-8de7-05a9bafe4aca.png)

Files and their Imports(the programs_start directory is not included because they do not import anything and are not part of the project):
main.py:
![image](https://user-images.githubusercontent.com/67195650/107364998-36e4c100-6b02-11eb-9ddd-32aaec8b8e89.png)
files.py:
![image](https://user-images.githubusercontent.com/67195650/107365045-449a4680-6b02-11eb-808f-b6ea301e53f1.png)
windows.py:
![image](https://user-images.githubusercontent.com/67195650/107365090-52e86280-6b02-11eb-9ca7-5644377e6791.png)
web_search.py:
![image](https://user-images.githubusercontent.com/67195650/107365114-5c71ca80-6b02-11eb-9ee3-cc9884095db1.png)
query_finder.py:
![image](https://user-images.githubusercontent.com/67195650/107365134-65fb3280-6b02-11eb-9d8e-fc0cf6e03742.png)
programs.py:
![image](https://user-images.githubusercontent.com/67195650/107365159-6dbad700-6b02-11eb-9b70-0188adac41f5.png)

**Comment by limdauto** [comment] 2021-02-10 03:35
FWIW I can confirm that I'm seeing the same thing. I have a function that is definitely being used. As you could see in the screenshot, Pylance does know that there are 10 references to this function but it's greyed out nonetheless.
![Screenshot 2021-02-10 at 03 34 27](https://user-images.githubusercontent.com/2032984/107460930-eea0bf80-6b50-11eb-824d-b059d2008d97.png)

**Comment by erictraut** [comment] 2021-02-10 03:51
@limdauto, you're seeing a different issue unrelated to modules. A function whose name starts with an underscore is assumed to be private, and therefore intended only for use by callers within that module. You mentioned that there are 10 references to the function. Are they within the same module? If not, that explains why it is shown "grayed out". If your intent is to export it to other modules, you should change its name so it is not considered private.

**Comment by limdauto** [comment] 2021-02-10 05:09
@erictraut Ah sorry! My bad! You are right: in my case this particular function needs to be changed to public because it's being used elsewhere. Thank you.

**Comment by play4Tutorials** [comment] 2021-03-03 13:12
any updates??

**Comment by jakebailey** [comment] 2021-03-03 18:10
We are currently exploring ways in which we can improve our import resolution, or at least provide more guidance to fixing it. In your case, I did suggest extraPaths to mark extra import roots (which is our current suggestion) and we don't have any other guidance for when a project like this imports with unclear semantics (see also #253).

If there are updates, we'll put them here, but I'm fairly certain what you're seeing is a part of our current design and requires you to set extraPaths as is hinted in our troubleshooting docs.

**Comment by play4Tutorials** [comment] 2021-03-04 08:43
ok... and will this issue be closed, since it is kind of resolved??

**Comment by jakebailey** [comment] 2021-03-04 21:56
If you mean that it's resolved now with extraPaths, then sure, we can close this issue.

**Comment by play4Tutorials** [comment] 2021-03-10 11:33
ok then, close it... thanks

**Comment by pybash1** [comment] 2021-04-16 06:37
I just saw this today


`from . import module` doesn't give the error!

**Comment by jakebailey** [comment] 2021-04-16 17:51
Yes, relative imports don't need paths to be able to resolve, as they know where they're relative to (the current module's folder). Using relative imports bypasses the problem.

I'm not sure why I didn't close this issue after you asked for it, oops. #68 and #253 largely supersede this issue, in any case.

**Closed by jakebailey** 2021-04-16 17:51 UTC
Labels: needs investigation

**Comment by pybash1** [comment] 2021-04-17 11:36
Alright, thanks!

**Comment by Macanthony7** [comment] 2021-07-05 22:10
please i can't seem to solve this part. >

State the environment where your code is running; i.e. Python version, the virtual environment type, etc.
If using a virtual environment, please include the requirements.txt file.
If working with a conda environment, attach the environment.yml file.
A code example (or any other additional information) we can use to reproduce the issue.

**Comment by pybash1** [comment] 2021-07-06 10:28
> 
> 
> please i can't seem to solve this part. >
> 
> State the environment where your code is running; i.e. Python version, the virtual environment type, etc.
> If using a virtual environment, please include the requirements.txt file.
> If working with a conda environment, attach the environment.yml file.
> A code example (or any other additional information) we can use to reproduce the issue.

I can't understnad what you cant resolve?

**Comment by Macanthony7** [comment] 2021-07-08 20:44
I can seem to understand how and where to include the requirements.txt file
after selecting "Python Language Server" I'm confused sir.

**Comment by pybash1** [comment] 2021-07-10 11:17
@jakebailey Could you please help @Macanthony7 ?

**Comment by jakebailey** [comment] 2021-07-12 21:25
@Macanthony7 I don't think your issue is related to this one; can you please file a new issue and fill out the bug report template?

(The template you appear to be quoting isn't ours.)

**Comment by Ksp-3086** [comment] 2021-09-07 15:55
![python](https://user-images.githubusercontent.com/84498303/132374819-fb86b637-f5a2-4b9f-a320-66891d85b46c.png)
I have been facing the same import issue with any library module.

1. There is only 1 version of python installed 3.8.10 and pylance is also installed.
2. It was working before, as I am new to python and I have been practicing different codes, so before import worked fine but now even import numpy as np, OR from numpy import linspace, pi, ... don't work.
Anyone got a fix for this because none of the above discussion helped out

**Comment by jakebailey** [comment] 2021-09-07 16:14
"Not accessed" is a visual indicator that says you haven't used the import, not that it didn't resolve or that your code won't run. The "fix" is either to remove the import or to use it, but this is only a visual indicator.

**Comment by Ksp-3086** [comment] 2021-09-08 04:05
![asarray error](https://user-images.githubusercontent.com/84498303/132444732-e9c8fe06-ee1c-452c-ae91-b106bd7d752c.png)
ok, but if I use asfarray which is imported from numpy, it  says not defined.

**Comment by jakebailey** [comment] 2021-09-08 05:11
You need to write `numpy.asfarray`; that code will not execute.

**Comment by Ksp-3086** [comment] 2021-09-08 05:15
ok, thanks

**Comment by hyphaestion** [comment] 2022-02-05 20:51
Hey, I had this same problem. For others that are more visual learners, I followed the steps in this video https://www.youtube.com/watch?v=GqTsFOtZiQI 

I was able to resolve the issue.  Thank you for posting this thread, because you were able to help me identify the problem which was the interpreter that was being used. 

> Ok, let me explain.
> 
> Terms used: pip - pip3 Py, py - Python3 Conda, conda - Anaconda3
> 
> First I was trying to import requests, wget and some more modules. But it showed this error. Now few days back I just found out that inside VSCode my python interpreter was selected as Py3.7. But conda3.8.3 was my windows default interpreter. And thus all modules installed using pip were installed there. But PyLance tried to find in Py3.7 and they were not present. But the scripts never showed an error because when I was executing them through the terminal, they actually getting executed in Conda3.8.3. So when i changed my interpreter from py3.7 to conda3.8.3 in vscode all those errors were gone. And that fixed it.
> 
> But now if I try to import a local file, pylance shows the error. Executing it doesn't give any error. And workd fine. But Pylance Shows the error.
> 
> Hope this helps you. So could you fix so that importing local modules doesn't give an error. And also, PyLance says, this is a warning not an error. If you want I can attach a screenshot. Not using an virtual envirionment
> 
> A suggestion - could you make the warning underlines yellow instead of green, that would be better. Since, green kind of means there are no issue.

**Comment by erictraut** [comment] 2022-06-01 21:52
The import is grayed out as a subtle way of indicating that there is no _local_ reference to that imported symbol within the file. This is not flagged as an error (i.e. there's no red squiggle beneath it) because there are legitimate reasons why one might not reference an import locally — for example, if the intent is for the imported symbol to be re-exported to other modules. So don't think of a grayed-out statement as a "bug that needs to be fixed". Think of it instead just as a subtle hint that there is no local reference to that symbol. Sometimes that's intended and sometimes it's not. If it is intended, then ignore it. If it's not intended (e.g. it's an outdated import statement that you forgot to remove), then delete it.

**Comment by Aswini327** [comment] 2023-09-13 08:57
icon_id not accessed pylance
API_key not accessed pylance 
What happens in above lines please tell me

**Comment by debonte** [comment] 2023-09-13 14:25
@Aswini327, please file a new issue and include a code sample that reproduces the problem that you are seeing.

**Comment by abhinay181** [comment] 2023-10-19 05:28
@jakebailey 

I am unable to access methods from sqlalchemy package. I have installed the package successfully you can see it in the below screenshot I have run the pip list command to show that sqlalchemy is installed

![new 2](https://github.com/microsoft/pylance-release/assets/85485413/7627e2c2-4ecb-41c7-9684-aee317519127)
![new 3](https://github.com/microsoft/pylance-release/assets/85485413/a49905aa-4db5-4275-aa01-483b59dd58e5)
![new 4](https://github.com/microsoft/pylance-release/assets/85485413/1dd4b159-fd65-42bd-87db-45adacf33064)

**Comment by debonte** [comment] 2023-10-19 05:31
@abhinay181, since this is a runtime issue, it would be better to ask the library maintainers over at the sqlalchemy repo -- https://github.com/sqlalchemy/sqlalchemy/discussions
