### ISSUE TITLE
Type Parameter Syntax is not analyzed properly

### ISSUE THREAD

**Issue by yotaro-shimose** [microsoft/pylance-release#5318] opened 2023-12-23 15:16 UTC
Type: <b>Bug</b>

Hi maintainers. I love vscode and vscode-python extension so much. Thank you for your dedicated efforts.
This issue is moved from https://github.com/microsoft/pylance-release/issues/4645 since it seems better to treat here.

## Environment data

-   Language Server version: v2023.7.31
-   OS and version: Public python docker image python:3.12.0b4-bulluseye
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0b4

## Code Snippet

```python
from dataclasses import dataclass
from typing import Self


@dataclass
class MyInt:
    value: int
    def __add__(self, other: Self) -> Self:
        return MyInt(self.value + other.value)


def add[T: MyInt](a: T, b: T) -> T:
    return a + b


if __name__ == "__main__":
    print(add(MyInt(value=3), MyInt(value=4)))

```

## Repro Steps
1. Start the container pulled from the official python repository with the above mentioned tag.
2. Attach to it using vscode remote-development extension.
3. Install the python extension.
4. Paste the code above and let the pylance analyze it.

## Expected behavior

I expected the color of the return arrow of add function to be white, 

## Actual behavior
it becomes red, which is very confusing.
![image](https://github.com/microsoft/pylance-release/assets/65691831/ab67ce75-9138-4152-beaf-f44252584d0d)

By the way, when I stop using custom MyInt class and typehint without type parameter syntax, this behaviour goes away.
![image](https://github.com/microsoft/pylance-release/assets/65691831/aca5ec84-beb6-4600-b30d-1d873cb71e73)

As there is a growing focus on type-safe Python, generic programming, and hence, this type parameter syntax feature is crucial for many users. I respectfully request prioritizing this issue.

Extension version: 2023.22.1
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T22:27:05.695Z)
OS version: Linux x64 5.19.0-50-generic
Modes:
Remote OS version: Linux x64 5.19.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4599)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|15.53GB (10.19GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9322d294-702f-42bf-8bdc-0c1b2ccc7155|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|コンテナー python:3.12 (py312)|
|OS|Linux x64 5.19.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|Memory (System)|15.53GB (10.19GB free)|
|VM|0%|
</details>

**Comment by debonte** [comment] 2024-01-03 18:04
Duplicate of https://github.com/microsoft/pylance-release/issues/4645. This is a bug in TextMate grammar that VS Code uses for Python. We have a [work item](https://github.com/microsoft/pylance-release/issues/4645#issuecomment-1703160527) tracking the idea of us (Pylance or Python extension) shipping and maintaining a TextMate grammar ourselves, but no decision has been made there yet.

cc: @luabud

**Closed by debonte** 2024-01-03 18:04 UTC
Labels: needs repro
