### ISSUE TITLE
Failing to launch Pylance language server when opening workspace after upgrading VS Code

### ISSUE THREAD

**Issue by kevincon** [microsoft/pylance-release#1429] opened 2021-06-10 20:39 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.5 64-bit
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

I should also note I'm using the Remote Containers extension to open a multi-root workspace in a Docker container on a remote host via SSH from a Windows machine, so the "OS and version" above is for that Docker container on the remote host.

I'm also using Poetry to create a virtual environment for my project, but I'm only using that Poetry-managed Python 3.8.5 64-bit virtual environment for one of the roots of the multi-root workspace while a different root is using the system Python installation (2.7.18 64-bit).

<h3> Expected behaviour </h3>

Pylance language server launches successfully and provides intellisense, improved syntax highlighting, etc. of Python code for files in the workspace root which uses it.

<h3> Actual behaviour </h3>

Pylance language server fails to launch, so Jedi is used instead which doesn't provide as much intellisense, syntax highlighting, etc. of Python code.

<h3> Logs </h3>

Python Language Server Log

```
```
(was blank/empty)

<h3> Code Snippet / Additional information </h3>

Python output panel:
```
Starting Pylance language server.
Error 2021-06-10 20:22:03: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
	at new a (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
	at new y (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
	at r.startLanguageServer (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)]
Error 2021-06-10 20:22:03: Failed to start language server, Class name = r, completed in 564ms, has a falsy return value, Arg 1: <Uri:elided>, Arg 2: {"architecture":3,"path":"/usr/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"2.7.18-candidate1","major":2,"minor":7,"patch":18,"prerelease":["candidate1"],"build":[],"version":"2.7.18-candidate1"},"sysVersion":"2.7.18rc1 (default, Apr  7 2020, 12:05:55) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"010b6727b1315a29f43c0cd627674b95ae54f59264f6af9d5ed47fdf6d0fca8c2ec949f1d8071cc144a8fc340e1bf5b5070215c8ce0eea9f9a62520e5d1843ad","envType":"Unknown","displayName":"Python 2.7.18 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
	at new a (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
	at new y (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
	at r.startLanguageServer (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)]
Error 2021-06-10 20:22:03: [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
	at new a (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
	at new y (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
	at r.startLanguageServer (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-10 20:22:03: Failed to activate language server, Class name = a, completed in 569ms, has a falsy return value, Arg 1: <Uri:elided>, Arg 2: {"architecture":3,"path":"/usr/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"2.7.18-candidate1","major":2,"minor":7,"patch":18,"prerelease":["candidate1"],"build":[],"version":"2.7.18-candidate1"},"sysVersion":"2.7.18rc1 (default, Apr  7 2020, 12:05:55) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"010b6727b1315a29f43c0cd627674b95ae54f59264f6af9d5ed47fdf6d0fca8c2ec949f1d8071cc144a8fc340e1bf5b5070215c8ce0eea9f9a62520e5d1843ad","envType":"Unknown","displayName":"Python 2.7.18 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
	at new a (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
	at new y (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
	at r.startLanguageServer (/home/kdconley/.vscode-server/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)]
```

This just started happening after I upgraded VS Code to 1.57.0 today.

**Comment by jakebailey** [comment] 2021-06-10 20:40
Duplicate of #1428. See a workaround here: https://github.com/microsoft/pylance-release/issues/1428#issuecomment-858916868

**Closed by jakebailey** 2021-06-10 20:40 UTC
Labels: triage
