### ISSUE TITLE
Contextlib.suppress confuses pylance "Code is unreachable"

### ISSUE THREAD

**Issue by fried** [microsoft/pylance-release#559] opened 2020-11-03 18:49 UTC
## Environment data

Language Server version: 2020.10.3
OS and version:  macOS Catalina 10.15.7
Python version: 3.9.0 (installed via homebrew)

## Expected behaviour

https://docs.python.org/3/library/contextlib.html#contextlib.suppress

## Actual behaviour

Pylance says the code is unreachable

## Code Snippet / Additional information
This example is contrived, but its a simplification I was testing some nested transaction context handlers.
And was supprised that pylance told me the code was unreachable on line 14. 

<img width="382" alt="Screen Shot 2020-11-03 at 10 37 22 AM" src="https://user-images.githubusercontent.com/200457/98027864-26fe6800-1dc2-11eb-916f-8b7ca078e3d7.png">

```python
import unittest
from contextlib import suppress

class TransactionError(Exception):
    pass

class TestSomething(unittest.TestCase):
    def test_something(self):
        with suppress(TransactionError):
            raise TransactionError
        self.assertTrue(True)   ### HERE this is grey for being unreachable
```

**Comment by judej** [comment] 2020-11-03 18:55
Dupe of #494

**Closed by judej** 2020-11-03 18:55 UTC
Labels: triage
