### ISSUE TITLE
LSP Extension problems with Pylance

### ISSUE THREAD

**Issue by Allkams** [microsoft/pylance-release#5722] opened 2024-04-03 08:10 UTC
## Environment data

-   Language Server version: v2024.4.1
-   OS and version: Windows 11, version: 22631.3296
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.2

## Code Snippet

```python
# None... Just opening an empty .py file will trigger this from my experience this morning.
```

## Repro Steps

1. Create a VS Code LSP Extension from the [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample)
2. Run the extension with the newest Pylance version (v2024.4.1) and open a python project in the debugger VS Code  window.
3. Error should pop up in the extension IDE debug Console.

## Expected behavior

Well, not to much here but to work I would say... As this error is not present in the v2024.3.2 version and neither versions have the requested file "package.nls.en-us.json" in the given location, something feels odd with the Pylance v2024.4.1 version..

## Actual behavior

The received behavior is the error and not fully sure if it hinders the development per say, but it's annoying that it is there.

## Logs

As the error comes to the extension, and not from the python debugger, I could not get any other information. But as the bug is only present when running the pylance version 2024.4.1 I report it here. So the log below is the Debug Console output from the starting the extension and then opening a python file from the new window, where the error is displayed in the extension development environment and not the debugger window. 
```

EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\Allka\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\package.nls.en-us.json'
	at k.e (c:\Users\Allka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:6084)
	at Object.readFile (c:\Users\Allka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:4463)
	at async _0x9c8500 (c:\Users\Allka\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:204314)
	at async _0x4bfbb1 (c:\Users\Allka\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:203891)
	at async _0x1785d4 (c:\Users\Allka\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:313136)
	at async _0x15825a (c:\Users\Allka\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:242985)
	at async u.n (c:\Users\Allka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6255)
	at async u.m (c:\Users\Allka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6218)
	at async u.l (c:\Users\Allka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:5675) {code: 'FileNotFound', name: 'EntryNotFound (FileSystemError)', stack: 'EntryNotFound (FileSystemError): Error: ENOEN…ch\api\node\extensionHostProcess.js:140:5675)', message: 'Error: ENOENT: no such file or directory, op…ode-pylance-2024.4.1\package.nls.en-us.json''}
```

**Comment by debonte** [comment] 2024-04-03 14:36
This is a duplicate of https://github.com/microsoft/pylance-release/issues/5686. It will be fixed in our next prerelease build.

**Closed by debonte** 2024-04-03 14:36 UTC
Labels: needs repro
