### ISSUE TITLE
Signature Help Expected Behavior?

### ISSUE THREAD

**Issue by rlaabs** [microsoft/pylance-release#672] opened 2020-12-03 02:36 UTC
Is there documentation somewhere that covers when/under what conditions plyance is able to provide signature help?

For example, should help be expected for something like (the RandomForestClassifier instance)?

`
from sklearn.ensemble import RandomForestClassifier
rc = RandomForestClassifier()
`

On different machines, using the same version of pylance and vscode, for some reason I only get signature help on one. I'm trying to figure out if I'm missing something before filing an issue.

**Comment by judej** [comment] 2020-12-03 21:53
@rlaabs, It is unclear why you would be seeing this discrepancy. The signature help should show if pylance can find the docstrings in the .py files for the module or if there are docstrings in the type stubs. In your case, there is  docstrings for the `class RandomForestClassifier():` in the `sklearn\ensemble\_forest.py`. So Pylance should be able to find it. 

On the machine where it is not showing, would you hit F12 or "Go to definition" with the cursor on the class name in `rc = RandomForestClassifier()`. That may help narrow down the issue. 

Please let me know what you find.

thanks

**Comment by rlaabs** [comment] 2020-12-04 19:06
@judej The docstrings are the same, but I just noticed that scikitlearn (0.23.2) added a '@_deprecate_positional_args' decorator to the class definitions. The machine that it works on has an older version (0.22.1) without that decorator. 

Is it correct to assume that this issue is likely because of the behavior of that decorator and functools.wraps?




[IDX(2)]     parsing: /opt/miniconda3/envs/scikitlearn/lib/python3.8/site-packages/sklearn/ensemble/__init__.py [fs read 0ms] (1ms)
[IDX(2)]     binding: /opt/miniconda3/envs/scikitlearn/lib/python3.8/site-packages/sklearn/ensemble/__init__.py (1ms)
[IDX(2)]     indexing: /opt/miniconda3/envs/scikitlearn/lib/python3.8/site-packages/sklearn/ensemble/__init__.py ...

**Comment by jakebailey** [comment] 2020-12-04 19:12
Likely. Types for decorators (especially wraps) are a bit notorious for causing issues like these.

**Comment by savannahostrowski** [comment] 2021-02-25 00:07
Duplicate of #442

**Closed by savannahostrowski** 2021-02-25 00:07 UTC
Labels: needs investigation
