### ISSUE TITLE
Go To Definition ... NOT to stub

### ISSUE THREAD

**Issue by ahopkins** [microsoft/pylance-release#647] opened 2020-11-25 10:33 UTC
Sorry if this is a duplicate. I tried looking for something about this.

When clicking "Go to definition" where there is a `.pyi`, I do not want to see the stub file. I want to be brought to the actual source code.

**Comment by huguesv** [comment] 2020-11-25 17:37
Duplicate of https://github.com/microsoft/pylance-release/issues/65

**Closed by huguesv** 2020-11-25 17:37 UTC
Labels: triage

**Comment by ahopkins** [comment] 2020-11-25 18:34
TY. 🙏
