### ISSUE TITLE
"No code actions available" if Ctrl+. is hit quickly after moving the cursor

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/pylance-release#1247] opened 2021-05-07 08:32 UTC
## Environment data

-   Language Server version: Pylance language server 2021.4.3 (pyright 320a0a2f)
-   OS and version: Linux
-   Python version: CPython 3.9.4

## Expected behaviour

Imports suggested from all stdlib and application packages

## Actual behaviour

Imports only suggested for imports coming from files I previously opened in the editor

## Remarks

This is a rather large project. Does pylance/pyright switch to lazy analysis at some point? If yes, can this be tuned? Not getting imports generated without me opening (and thus knowing) the file containing them first kind of defeats its purpose...

**Comment by jakebailey** [comment] 2021-05-07 17:52
At the moment, this is intended behavior. You can opt-in to workspace/library indexing by enabling the hidden option:

```
"python.analysis.indexing": true
```

Can you try it and see if this behaves as you expect?

**Comment by ThiefMaster** [comment] 2021-05-07 18:01
That tip was super useful - it made "Go to symbol in workspace" much faster as well  (and I was always annoyed by the rather poor performance of that command in a larger project).

The `CTRL+Space` autocompletion does not suggest it (I'm curious.. why? At least I usually use that first!), but `CTRL+.` seems to work fine for it now.

However I noticed something strange - probably an unrelated issue though: If I press the shortcut very quickly after moving the cursor to name I want to import, I usually get "No code actions available". If I wait a moment longer, it works fine though.

**Comment by heejaechang** [comment] 2021-05-20 06:00
I need to check but I don't think vscode currently has a forced code action like VS. (VS forces code action to run when ctrl+. is issued), you need to wait until vscode gets code action (light bulb to show up) before you can issue ctrl+.

**Comment by jakebailey** [comment] 2021-05-20 16:51
It does, Ctrl+. does that in VS Code.

**Comment by heejaechang** [comment] 2021-06-15 17:05
if ctrl+. does force code action, then we probably are not waiting for BG to finish processing everything in the queue before return.

**Comment by heejaechang** [comment] 2022-04-12 00:13
we need to add an ability to wait until every request posted to BG are done when ctrl+. is asked. currently we don't have a way.

**Comment by heejaechang** [comment] 2023-10-20 17:40
This issue has been fixed in prerelease version 2023.10.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231041-19-October-2023-PreRelease)

**Closed by heejaechang** 2023-10-20 17:40 UTC
Labels: bug, fixed in next version
