### ISSUE TITLE
values() of a TypedDict are always of type 'object'

### ISSUE THREAD

**Issue by Shapedsundew9** [microsoft/pylance-release#3887] opened 2023-01-30 18:57 UTC
## Issue
pylance unable to introspect TypedDict value types.
In the screenshot below you can see the values() of DICT are considered of type 'object' which makes them almost certain to cause a an incompatible type error. 'Any' would be better if it was not possible to introspect class TD.

![image](https://user-images.githubusercontent.com/16618209/215567603-691e4d82-be84-46c1-8fca-22deb38a5766.png)
If I do not set the type of DICT to TD introspection of the value types works OK. i.e.
![image](https://user-images.githubusercontent.com/16618209/215568516-d457786c-cda3-4f86-ba38-56cf3283b3d9.png)

May be this is an issue with how TypedDict is defined?

## Environment data
Pylance language server 2023.1.40 (pyright e96b3ece)

Ubuntu 22.04.1 LTS

VS Code
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-57-generic
Sandboxed: No

Python 3.11.1 (main, Jan 28 2023, 18:47:50) [GCC 11.3.0] on linux

## Code Snippet
```python
from typing import TypedDict


class TD(TypedDict):
    a: str
    b: str


DICT: TD = {
    'a': 'b',
    'b': 'c'
}


def do_something(v: str) -> str:
    return '_' + v


e: set[str] = {do_something(v) for v in DICT.values()}
```

## Expected behavior
v is not identified as an incompatible type. Ideally it is the union of TD values() types but 'Any' would do.

## Actual behavior
v is considered of type 'object'

## Logs
```
[Info  - 1:29:43 p.m.] (609755) Pylance language server 2023.1.40 (pyright e96b3ece) starting
[Info  - 1:29:43 p.m.] (609755) Server root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.1.40/dist
[Info  - 1:29:43 p.m.] (609755) Starting service instance "scratch"
[Info  - 1:29:43 p.m.] (609755) No configuration file found.
[Info  - 1:29:43 p.m.] (609755) No pyproject.toml file found.
[Info  - 1:29:43 p.m.] (609755) Setting pythonPath for service "scratch": "/home/shapedsundew9/Projects/venv/bin/python3"
[Warn  - 1:29:43 p.m.] (609755) stubPath /home/shapedsundew9/Projects/scratch/typings is not a valid directory.
[Info  - 1:29:43 p.m.] (609755) Assuming Python version 3.11
[Info  - 1:29:43 p.m.] (609755) Assuming Python platform Linux
[Info  - 1:29:43 p.m.] (609755) Searching for source files
[Info  - 1:29:43 p.m.] (609755) Found 1 source file
[Info  - 1:29:44 p.m.] (609755) Background analysis(1) root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.1.40/dist
[Info  - 1:29:44 p.m.] (609755) Background analysis(1) started
[Info  - 1:29:44 p.m.] (609755) Indexer background runner(2) root directory: /home/shapedsundew9/.vscode/extensions/ms-python.vscode-pylance-2023.1.40/dist (index)
[Info  - 1:29:44 p.m.] (609755) Indexing(2) started
[Info  - 1:29:45 p.m.] (609755) scanned(2) 174 files over 1 exec env
[Info  - 1:29:48 p.m.] (609755) [IDX(2)] Long operation: index execution environment /home/shapedsundew9/Projects/scratch (3403ms)
[Info  - 1:29:48 p.m.] (609755) [IDX(2)] Long operation: index packages /home/shapedsundew9/Projects/scratch (3416ms)
[Info  - 1:29:48 p.m.] (609755) indexed(2) 123 files over 1 exec env
[Info  - 1:29:48 p.m.] (609755) Indexing finished(2).
```

**Comment by heejaechang** [comment] 2023-01-30 19:06
it is because `values` is defined as below in the typeshed.

```python
def values(self) -> dict_values[str, object]: ...
```

this issue probably should go to `typeshed` repo to change it to [str, Any]?

**Comment by erictraut** [comment] 2023-01-30 19:33
This is by design. The type of the `values` attribute comes from the `_TypedDict` class defined in `typing.pyi`. The type `object` is appropriate here, as all values are guaranteed to be subtypes of `object`. There's not much more that a static type checker can say about the values because it's possible for a `TypedDict` to be subclassed and additional values added to it in the subclass.

Mypy and other type checkers also evaluate the type as `object` in this case.

**Comment by judej** [comment] 2023-01-30 19:33
This is working as designed in Pylance. As Heejae mentions, if the type is changed to `Any` then the issues no longer exists. Closing as external.

**Closed** 2023-01-30 19:33 UTC
Labels: triage-needed, external bug

**Comment by Shapedsundew9** [comment] 2023-02-01 12:45
Thanks I have reported it to typeshed: https://github.com/python/typeshed/issues/9649

**Comment by sylann** [comment] 2023-08-21 11:18
I understand that it is possible to have various types in the values of a TypedDict.
And I am not aware of the technical difficulties behind this issue.

I would just like to share some examples I have encountered

---

`TypedDict`s are also useful for keys exhaustiveness.

If I have a dict with a set of known keys (e.g. "a", "b", "c") that all must have the same value type (e.g. bool).
I can't use `dict[t.Literal["a", "b", "c"], bool]` because this does not guarantee that all keys are present.

```py
import typing

SomeType = dict[typing.Literal["a", "b", "c"], bool]

should_work1__OK: SomeType = {
    "a": True,
    "b": True,
    "c": True,
}

should_not_work1__OOPS: SomeType = {
    "a": True,
    "b": True,
}

class SomeDict(typing.TypedDict):
    a: bool
    b: bool
    c: bool

should_work2__OK: SomeDict = {
    "a": True,
    "b": True,
    "c": True,
}

should_not_work2__OK: SomeDict = {
    "a": True,
    "b": True,
}
# Expression of type "dict[str, bool]" cannot be assigned to declared type "SomeDict"
#   "c" is required in "SomeDict"
```


You can't use the TypedDict in places where a less strict (but compatible) type is expected:

```py
import typing

class SomeDict(typing.TypedDict):
    a: bool
    b: bool
    c: bool

def some_other_func(input: dict[str, bool]):
    pass

data: SomeDict = {"a": True, "b": True, "c": False}

some_other_func(data)
# Argument of type "SomeDict" cannot be assigned to parameter "data" of type "dict[str, bool]" in function "some_other_func"
#    "SomeDict" is incompatible with "dict[str, bool]"
```

You can't map similar `TypedDict`s with dict comprehension.
Comprehensions are one of the most typical and useful features in Python.

Anytime you know you have several dicts with common exhaustive keys and want to go from one to the other, you have to systematically repeat all the keys.

I'll take a simple example for illustration, but you can imagine how this becomes tedious really quickly when your use cases are not ad hoc examples.

```py
import typing

T = typing.TypeVar("T")

class GenericBase(typing.TypedDict, typing.Generic[T]):
    a: T
    b: T
    c: T

SomeInputDict = GenericBase[str]
SomeOutputDict = GenericBase[bool]

def some_work(value: str) -> bool:
    return value == "it does not matter"

def some_func(input: SomeInputDict) -> SomeOutputDict:
    return {k: some_work(v) for k, v in input.items()}
    # Expression of type "dict[str, bool]" cannot be assigned to return type "SomeOutputDict"

def some_func_2(input: SomeInputDict) -> SomeOutputDict:
    return {
        "a": some_work(input["a"]),
        "b": some_work(input["b"]),
        "c": some_work(input["c"]),
    }
```

I'm happy to read your feedback on this.

**Comment by erictraut** [comment] 2023-08-21 14:36
@sylann, `TypedDict` is a structural type, like a protocol class. It's possible for a dictionary to have keys other than what is defined in a `TypedDict` and still be type compatible with that `TypedDict`. However, the authors of [PEP 589](PEP 589) (which introduced TypedDict) decided that when you construct a new TypedDict, type checkers should enforce that no additional keys are present at construction time. You can read about the justification for this decision in the PEP. I'm not sure I entirely agree with the reasoning, but this is how the spec is defined, and pyright (the type checker upon which pylance is built) complies with the spec. So do other type checkers like mypy.

```python
class A(TypedDict):
    a: int

class B(TypedDict):
    a: int
    b: str

a1: A = {"a": 0}
b1: B = {"a": 0, "b": ""}

a2: A = {"a": 0, "b": ""}  # Not allowed
a3: A = b1  # OK
```

With this knowledge in mind, it should become more clear why your code above will not type check. It's possible for a `TypedDict` value to contain keys that are not part of the `TypedDict` definition.

**Comment by ColinStroud** [comment] 2023-09-01 03:02
@sylan Just a heads up, you can specify literals as the keys to dict's. (FYI here on an unrelated issue so not likely to respond, do my best). See my screen shot below:
![image](https://github.com/microsoft/pylance-release/assets/41063766/0aae62ad-a4dc-49f4-b056-73a5e3e1eb15)
