### ISSUE TITLE
search over paths mentioned in .pth

### ISSUE THREAD

**Issue by DylanModesitt** [microsoft/pylance-release#808] opened 2021-01-06 03:29 UTC
I often use a `.pth` file in my `venv`s in order to add internal modules or packages. Usually, this is in order to have an efficient way to work on `pip`-package **A**'s interactions with package **B**.

Would it be possible to search for source in any paths mentioned in a venv's `*.pth` file(s) giving behavior analogous to manually adding those same paths to `"python.analysis.extraPaths"`?

**Comment by jakebailey** [comment] 2021-01-06 18:49
pth files should work normally (as we ask python for its `sys.path`), but don't; I'm going to call this a dupe of #78 as editable installs are also based on pth files, and what whole thing will be investigated together.

**Closed by jakebailey** 2021-01-06 18:49 UTC
Labels: triage
