### ISSUE TITLE
Pylace high CPU usage

### ISSUE THREAD

**Issue by sebastian-von-camen** [microsoft/pylance-release#4225] opened 2023-04-11 11:33 UTC
Type: <b>Bug</b>

- Open a Python folder with some code in it and open a file.
- CPU usage on my i9-11950H goes up to 12% and stays constantly at this level. 
- Once Pylance is disabled CPU usage drops down to normal.

Extension version: 2023.4.10
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.72GB (48.29GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/XXXXXXXXX/Projekte/reports|
|Screen Reader|no|
|VM|0%|
</details>

<details>
<summary>Python Language Server Log</summary>
```
[Info  - 1:34:28 PM] (5480) Pylance language server 2023.4.10 (pyright d7616109) starting
[Info  - 1:34:28 PM] (5480) Server root directory: c:\Users\XXXXXXXXX\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist
[Info  - 1:34:28 PM] (5480) Starting service instance "reports"
[Info  - 1:34:28 PM] (5480) Setting pythonPath for service "reports": "c:\Program Files\National Instruments\Shared\Skyline\Python\3.8\python.exe"
[Warn  - 1:34:28 PM] (5480) stubPath c:\Users\XXXXXXXXX\Projekte\reports\typings is not a valid directory.
[Info  - 1:34:28 PM] (5480) Assuming Python version 3.8
[Info  - 1:34:29 PM] (5480) Found 19 source files
[Info  - 1:34:29 PM] (5480) Background analysis(1) root directory: c:\Users\XXXXXXXXX\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist
[Info  - 1:34:29 PM] (5480) Background analysis(1) started
[Info  - 1:34:29 PM] (5480) Indexer background runner(2) root directory: c:\Users\XXXXXXXXX\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist (index)
[Info  - 1:34:29 PM] (5480) Indexing(2) started
[Info  - 1:34:29 PM] (5480) scanned(2) 46 files over 1 exec env
[Info  - 1:34:30 PM] (5480) indexed(2) 23 files over 1 exec env
[Info  - 1:34:30 PM] (5480) Indexing finished(2).
```
</details>

<details>
<summary>Python Output Log</summary>
```
Python interpreter path: c:\Program Files\National Instruments\Shared\Skyline\Python\3.8\python.exe
Starting Pylance language server.
[ERROR 2023-3-11 13:34:28.875]: Active interpreter type is detected as Unknown {"id":"C:\\PROGRAM FILES\\NATIONAL INSTRUMENTS\\SHARED\\SKYLINE\\PYTHON\\3.8\\PYTHON.EXE","sysPrefix":"c:\\Program Files\\National Instruments\\Shared\\Skyline\\Python\\3.8","envType":"Unknown","envName":"","envPath":"","path":"c:\\Program Files\\National Instruments\\Shared\\Skyline\\Python\\3.8\\python.exe","architecture":3,"sysVersion":"3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]","version":{"raw":"3.8.5","major":3,"minor":8,"patch":5,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.5 64-bit","detailedDisplayName":"Python 3.8.5 64-bit"}
```
</details>

**Comment by rchiodo** [comment] 2023-04-17 16:32
Closing as a dupe of 4218. This should be fixed in our latest prerelease bits.

**Closed as completed by rchiodo** 2023-04-17 16:32 UTC
Labels: waiting for user response
