### ISSUE TITLE
100% CPU and 100% Memory Usage when using Pylance 2020.9.0

### ISSUE THREAD

**Issue by kswydock** [microsoft/pylance-release#354] opened 2020-09-10 06:17 UTC
-   Language Server version: 2020.9.0
-   OS and version: Windows 10 Version 19041
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Build Python 3.8.3
## Expected behaviour
I recently updated to Pylance 2020.9.0 and whenever I have it enabled, my CPU and Memory usage for VSCode spikes to 100%.
Disabling the Pylance extension fixes this issue.

Additional Information:
VSCode Python Extension: 2020.8.108011
Visual Studio Intellicode: 1.2.10

**Comment by huguesv** [comment] 2020-09-10 18:00
duplicate of https://github.com/microsoft/pylance-release/issues/321

**Closed by huguesv** 2020-09-10 18:00 UTC
Labels: triage
