### ISSUE TITLE
python interactive windows, pylance crashes. Issue persists in v2024.9.1

### ISSUE THREAD

**Issue by philippweinmann** [microsoft/pylance-release#6414] opened 2024-09-19 17:38 UTC
## Environment data

-   Pylance version: v2024.9.1
-   OS and version: macos 14.5
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.9

## Code Snippet

```python
# %%
import numpy as np
# %%
```

## Repro Steps

It doesn't matter how exactly the interactive window is used, the error seems to be triggered often. However to reproduce it:

1. Create a python file, use the interactive window: # %%
2. execute it, have an "interactive" window open.
3. Close and reopen VScode (which opens both the python file and the interactive window)

On step 3, pylance crashes repeatedly.

Feel free to contact me for further information.

## Logs

I've added the logs as an attachment.

[pylance_logs.txt](https://github.com/user-attachments/files/17063660/pylance_logs.txt)

**Comment by debonte** [comment] 2024-09-19 18:24
This is a duplicate of https://github.com/microsoft/pylance-release/issues/6357, which is fixed in [2024.9.100](https://github.com/microsoft/pyrx/blob/main/packages/vscode-pylance/CHANGELOG.md#20249100-12-september-2024-prerelease). Please [switch to prerelease](https://github.com/microsoft/pylance-release/wiki/FAQ#switch-from-release-to-prerelease).

**Closed by debonte** 2024-09-19 18:24 UTC
Labels: needs repro
