### ISSUE TITLE
Unexpected pylance "reportMissingImports" in notebook for local package

### ISSUE THREAD

**Issue by AwePhD** [microsoft/pylance-release#3208] opened 2022-08-17 12:04 UTC
Hello,

I think there is a problem with the Python Analysis feature and Notebooks. I searched on SO and in the issues and I did not found anything similar.

## Description of the problem 

I have the following minimal set-up : 

```
├── lib
│   ├── data.py
│   ├── __init__.py
├── notebook_root.ipynb
└── notebooks
    └── notebook.ipynb
```

`data.py` contains `class A: pass`

In `notebook.ipynb` and `notebook_root.ipynb` have a single cell containing: `from lib.data import A`

Then I have the following :

- I can successfully execute BOTH cells. 
- In `notebook_root.ipynb`, there is no yellow warning.
- In `notebook.ipynb`, there is a pylance warning "reportMissingImports"

## Additional information 

[Intellicode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) properly detects the `A` class while I am typing the import line

I add the following extra settings : 

```JSON
  {
    "jupyter.notebookFileRoot": "${workspaceFolder}",
    "python.languageServer": "Default",
    "python.analysis.extraPaths": [
        "${workspaceFolder}"
    ],
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}",
    ],
}
```

## What did I try

I tried to change my option to see if the `${workspaceFolder}` is set. If I change the `jupyter.notebookFileRoot` to `${foo}`, then the `notebook.ipynb`'s cell cannot be run anymore because it cannot find the local package.
Although, the other settings do not seem to have any effect. If I change `${workspaceFolder}` to `${foo}` then there is no difference for both notebooks.

Ask me if you need any additional information. 

Have a nice day,
Mathias.

**Comment by bschnurr** [comment] 2022-08-17 20:35
does this happen on the pre-release pylance build?

**Comment by AwePhD** [comment] 2022-08-18 11:39
No, I do not use the Pre-Release version of the plugin. The current version is `v2022.8.30`

**Comment by OllieKampo** [comment] 2022-08-18 21:00
I am having the same issue, I wonder if it is related to this issue #3017. [This comment](https://github.com/microsoft/pylance-release/issues/3017#issuecomment-1214861849) seems to be something similar. I wonder if that fix has broken absolute imports with "jupyter.notebookFileRoot": "${workspaceFolder}" in settings.json.

In my case, I have a folder structure like this:
- a/
    - file_in_different_dir.py
- b/
    - file_in_same_dir.py
    - notebook.ipynb

If I do:
```
import a.file_in_different_dir
import b.file_in_same_dir
```
The jupyter notebook file runs correctly, but pylance reports "reportMissingImports" for both the imports. In the past (about a week ago) this worked just fine, no errors being reported.

If I do:
```
import file_in_same_dir
```
Pylance does not report the error and the file runs.

**Comment by YDX-2147483647** [comment] 2022-08-19 16:08
I met this issue on August 7. (It was the last version of Pylance)

I followed [the trouble-shooting guide](https://github.com/microsoft/pylance-release/blob/fbafb756c024e2b14ae9460002821dc7600fa467/TROUBLESHOOTING.md#filing-an-issue), and found a **direct evidence** of the working space (aka. the root path, cwd, or whatever.).

![IMG_1085](https://user-images.githubusercontent.com/73375426/185658902-8959d5db-3d9d-4e4d-a969-b49ddf8a4b5d.JPG)

- The sidebar on the left shows the file structure.

  To clarify: `outer.py`'s absolute path: `D:/DevelopProjects/temp/temp/outer.py`.

- Content of `that.py`: `print('This is that.py.')`.
 
  Remarks: I `import this` (which is beyond the screenshot) to make sure that standard libraries work fine. Therefore I call it `that.py`.

![](https://user-images.githubusercontent.com/73375426/185658915-1755f6f7-6ba3-4bd4-a52c-a76b1dcf0fba.JPG)

The selected row: the root path is VS Code's workspace (`…/temp/`) not notebook's (`…/temp/inner/`).

**Comment by AwePhD** [comment] 2022-08-22 06:54
For additional information, I did the same procedure as @YDX-2147483647. I put the log file on a [pastebin](https://pastebin.com/jWKgBzck). 

At the beginning of the log file there are these lines: 
```
[Info  - 8:43:44 AM] (12624) Search paths for /home/reusm-admin/code/issues_min/notebook_import
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/.vscode/extensions/ms-python.vscode-pylance-2022.8.30/dist/typeshed-fallback/stdlib
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/code/issues_min/notebook_import
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/code/issues_min/notebook_import/${toto}
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/code/issues_min/notebook_import/typings
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/.vscode/extensions/ms-python.vscode-pylance-2022.8.30/dist/typeshed-fallback/stubs/...
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/.vscode/extensions/ms-python.vscode-pylance-2022.8.30/dist/bundled/stubs
[Info  - 8:43:44 AM] (12624)   /usr/lib/python3.8
[Info  - 8:43:44 AM] (12624)   /usr/lib/python3.8/lib-dynload
[Info  - 8:43:44 AM] (12624)   /home/reusm-admin/.local/lib/python3.8/site-packages
[Info  - 8:43:44 AM] (12624)   /usr/local/lib/python3.8/dist-packages
[Info  - 8:43:44 AM] (12624)   /usr/lib/python3/dist-packages
```

It seems that the workspace folder, `/home/reusm-admin/code/issues_min/` here, is not included in the patch search.

**Comment by AwePhD** [comment] 2022-08-29 08:49
The pre-release `v2022.8.41` [did not fixed the bug](https://github.com/microsoft/pylance-release/issues/3017#issuecomment-1227512456). Which makes this issue different from #3017.

**Comment by OllieKampo** [comment] 2022-08-29 10:04
@AwePhD I was asking whether it is possible that the fix, or attempted fix, to #3017 may have somehow caused this bug. It seemed more than a coincidence that this bug was not present prior to v2022.8.12.

**Comment by torext** [comment] 2022-09-09 12:52
I confirm I also still see the same issue with Pylance `2022.9.10`, see https://github.com/microsoft/pylance-release/issues/3017#issuecomment-1241935685

**Comment by debonte** [comment] 2022-09-15 04:17
This issue has been fixed in prerelease version 2022.9.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022921-14-September-2022-PreRelease)

**Closed by debonte** 2022-09-15 04:17 UTC
Labels: bug, fixed in next version

**Comment by torext** [comment] 2022-09-15 13:29
FYI this doesn't seem fixed when creating and working in a new Jupyter notebook via `Create: New Jupyter Notebook`, see https://github.com/microsoft/pylance-release/issues/3017#issuecomment-1248097940.

**Comment by memeplex** [comment] 2024-07-18 01:48
I'm experiencing this in a project. pylance keeps saying that a python module in the same folder than my notebook could not be resolved. I tried to reproduce it in a minimal project of similar structure, to no avail. Then I duplicated the entire project into a new folder, opened it and suddenly it works, but if I now open the original project again it keeps failing to resolve the import as before. It seems like there is some state persisting for the workspace, but I couldn't find any way of cleaning it up. Clear Cache and Reload Window improves nothing.

**Comment by debonte** [comment] 2024-07-18 01:53
@memeplex this issue has been closed for almost two years. It's likely you're seeing something unrelated. Could you please open a new issue?

**Comment by memeplex** [comment] 2024-07-18 02:12
Not so sure it's unrelated since I see the issue popping up from time to time and it's always difficult to reproduce, as in my case. FWIW I went for the nuclear option and removed the entire workspaceStorage (I wish there was a more reasonable way but I'm afraid there isn't), opened my workspace again and pylance started behaving ok. So I don't have any hope to reproduce the issue in a way that's worth reporting other than a vague heads up about inconsistent state that is not purged without nuking the workspace.

**Comment by rchiodo** [comment] 2025-01-27 20:53
@balthild can you open a new issue? The root of the problem would be whether or not we find the import in this .venv:

![Image](https://github.com/user-attachments/assets/b9fbccca-a1bb-417e-9270-d81efc78187c)

That's we we're looking. If open a new issue we can investigate.
