### ISSUE TITLE
Not recognizing some functions in external libraries as a function

### ISSUE THREAD

**Issue by mahan-coder** [microsoft/pylance-release#535] opened 2020-10-28 14:01 UTC
## Environment data

-   Language Server version: v2020.10.2
-   OS and version: Windows 10 version 2004
-   Python version: 3.8.6

## Problem

I am writing this code:
```python
import numpy as np

array = np.arange(100)
print(array)
```
When I am typing `np.arange` It shows me arange with a variable icon instead of a function icon. also, it doesn't show anything when typing parentheses. when I hover over it, it shows `(import) arange: Any` to me. But when I run the code it gives me the correct output and when I try `print(np.arange)` it shows me `<built-in function arange>`. This problem happens with some other functions in external libraries. For example, it also happens with np.array. It seems that pylance isn't recognizing these as a function.

![image](https://user-images.githubusercontent.com/65105139/97446123-4705d580-1943-11eb-99c6-798279a62276.png)

**Comment by jakebailey** [comment] 2020-10-28 16:34
Duplicate of #150.

**Closed by jakebailey** 2020-10-28 16:34 UTC
Labels: triage
