### ISSUE TITLE
Issue with type narrowing for Optional type in Lists

### ISSUE THREAD

**Issue by Ashesh3** [microsoft/pylance-release#815] opened 2021-01-07 06:52 UTC
## Environment data

-   Language Server version: v2021.1.1-pre.1
-   OS and version: Windows 10 20H2
-   Python version : 3.9.1

## Expected behaviour

Consider the following snippet:

```
from typing import List, Optional

a: List[Optional[int]] = [None, None]

a[0] = 5
a[1] = 10

b: int = 0

if a[0] is not None:
    b = a[0]
```
Which throws the following error:

```
Expression of type "int | None" cannot be assigned to declared type "int"
  Type "int | None" cannot be assigned to type "int"
    Type "None" cannot be assigned to type "int"
```

I do check if `a[0] is not None` but I don't know why it still fails to narrow down the type of `a[0]` from `int | None` to `int` as the condition for `None` is already checked for.

`mypy` recognizes this as a valid snippet of code.

```
mypy test.py
Success: no issues found in 1 source file
```

## Actual behaviour

Pylance complains that `a[0]` could be possibly `None` even after the `if` condition filtering out that possibility.
This is under `PylancereportGeneralTypeIssues`

![image](https://user-images.githubusercontent.com/3626859/103861123-e59c7880-50e2-11eb-8e17-247f67585b53.png)

## Logs

```
Success: no issues found in 1 source file
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\fakepath\.vscode\extensions\ms-python.python-2021.1.467321600-dev\pythonFiles\pyvsc-run-isolated.py black --diff --quiet "c:\fakepath\test.py.84fd2df3c8ee8209df3448e9e9e7a849.tmp"
cwd: c:\Users\fakepath\
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\fakepath\.vscode\extensions\ms-python.python-2021.1.467321600-dev\pythonFiles\pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers "c:\fakepath\test.py"
cwd: c:\fakepath\
##########Linting Output - mypy##########
Success: no issues found in 1 source file
```

**Comment by erictraut** [comment] 2021-01-07 07:09
This is a duplicate of https://github.com/microsoft/pylance-release/issues/799.

**Closed** 2021-01-27 19:09 UTC
Labels: duplicate
