### ISSUE TITLE
Add `extraPath` doesn't work correctly with `network folder`

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5398] opened 2024-01-25 19:07 UTC
1. clone https://github.com/microsoft/pylance-release/tree/main/testing/single
2. create a network folder `NetworkFolder` to the `single` folder
3. open `//NetworkFolder/single` in `vscode`
4. run `add extraPath` code action on https://github.com/microsoft/pylance-release/blob/main/testing/single/src/codeaction.py#L39

expected:
`./outsideLib` is added like all other cases

actual:
`.///NetworkFolder//single/outsideLib` is added.

...

it works with `2023.12.1`

**Comment by rchiodo** [comment] 2024-01-25 20:47
@heejaechang do you know if this is a regression or did 2023.12.1 have the same problem?

**Comment by debonte** [comment] 2024-01-26 03:53
This has the same underlying cause as #5399. Resolving as a dupe.

**Closed by debonte** 2024-01-26 03:53 UTC
Labels: needs repro
