### ISSUE TITLE
Python Refactoring Move to file/to new file

### ISSUE THREAD

**Issue by nicolalandro** [microsoft/pylance-release#2903] opened 2022-06-09 08:14 UTC
I do not find any extension to move a function, a class or a selected text to a file/a new file, it should be a common instruction that I made every day in other ides. Did I miss a plugin or this function in python is not implemented?

The common use is for move into a specific file (for example extract this into function and after move function into existing file utils.py) or move to a new file (for example you create a class and you want to extract to a new file).

**Comment by judej** [comment] 2022-06-13 17:51
dupe of https://github.com/microsoft/pylance-release/discussions/2659

**Closed by judej** 2022-06-13 17:51 UTC
Labels: enhancement
