### ISSUE TITLE
Pylance becomes increasingly slow and unresponsive over time

### ISSUE THREAD

**Issue by paaksing** [microsoft/pylance-release#3514] opened 2022-10-21 21:13 UTC
<h3> Environment data </h3>

-   Language Server version: 2022.10.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

Apparently not code related.

<h3> Repro Steps </h3>

I don't know what is the cause

<h3> Expected behavior </h3>

Pylance is responsive and performs as normal throught the usage period

<h3> Actual behavior </h3>

Since October 19th (or earlier), language highlights and type hints will become increasingly slow over time and completely unresponsive after some time.
![image](https://user-images.githubusercontent.com/58193352/197290127-723bd913-6276-4109-9b68-bc9ce8ab8487.png)
Image shows already highlighted code, and the code that is not able to highlight or respond to hovers after a period of time.

I have to keep reloading vscode window to "fix temporarily".

<h3> Logs </h3>

```
[Info  - 4:33:27 PM] (26188) Found 230 source files
[Info  - 4:33:27 PM] (26188) Background analysis(1) root directory: c:\Users\***\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist
[Info  - 4:33:27 PM] (26188) Background analysis(1) started
[Info  - 4:33:27 PM] (26188) Indexer background runner(2) root directory: c:\Users\***\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist (index)
[Info  - 4:33:27 PM] (26188) Indexing(2) started
[Info  - 4:33:32 PM] (26188) [IDX(2)] Long operation: index execution environment c:\Users\***\Desktop\*** (2955ms)
[Info  - 4:33:32 PM] (26188) [IDX(2)] Long operation: index libraries c:\Users\***\Desktop\*** (4320ms)
[Info  - 4:33:32 PM] (26188) Indexer done(2). indexed 610 files
```

**Comment by bschnurr** [comment] 2022-10-21 22:43
is it just the first time hovering? 

if you have an obfuscated source examle that would help.

is it an example with large dictionaries or maps?

**Comment by paaksing** [comment] 2022-10-21 23:29
@bschnurr Apparently the bigger the file size, the faster it goes nuts, I downgraded pylance to `v2022.10.20` and it's working without issues now.

**Comment by paaksing** [comment] 2022-10-21 23:35
Also seems related to #3510, apparently the latest release seems to have some sort of "leakage".

**Comment by bschnurr** [comment] 2022-10-21 23:57
you could try turning on extra logging in your settings.json, to help identify where the extra time being spent is.

```
"python.analysis.logLevel":"Trace",
"python.analysis.logTypeEvaluationTime": true,
"python.analysis.typeEvaluationTimeThreshold": 1000,
```

**Comment by ooliver1** [comment] 2022-10-22 22:54
I seem to be getting a similar issue, a random process appears that uses `100%` of one thread, thus blocking pylance from doing anything.
![btop screenshot of bad pylance process](https://user-images.githubusercontent.com/34910574/197365174-1a8b6334-bf14-408d-ad0c-774c3978076b.png)

**Comment by bschnurr** [comment] 2022-10-24 16:41
diagnostic mode "openFilesOnly"
![image](https://user-images.githubusercontent.com/1946977/197579804-a39bce46-f56a-4553-a38a-fd3d8b2f0c1a.png)

**Comment by judej** [comment] 2022-10-24 17:48
Thanks for the report, unfortunately, this is not enough data for us to debug the issue. 

Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by txzpro** [comment] 2022-10-25 05:37
> v2022.10.20



> Reference

Thank you! Same issue here, and v2022.10.20 saved my life

**Comment by pietrolesci** [comment] 2022-10-25 15:09
Experiencing the same issue after the last update some days ago. In order to make it work again, I need to reopen VS code or Disable/Enable Pylance.

**Comment by judej** [comment] 2022-10-25 17:47
Dupe of #3513

**Closed by judej** 2022-10-25 17:47 UTC
Labels: bug
