### ISSUE TITLE
Import could not be resolved for symlinked python file

### ISSUE THREAD

**Issue by JavaScriptDude** [microsoft/pylance-release#4852] opened 2023-09-20 03:21 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When using PYTHONPATH to reconcile python libraries, it should allow for symbolic links to python files as well which is how its worked for years. However, now VSCode has issues showing `Import "<lib>" could not be resolved` message and all IDE helpers do not work.

## Steps to reproduce:

1. Set up a library with a lib folder
2. Within lib folder put a symbolic link to a python file in another location
3. Add a .env and settings.json files that properly sets the `PYTHONENV` to load `<workspace_folder>/lib`
4. Create a python file for the project that loads the symlink file in the lib folder

A full example with instructions is sitting in my test repo: https://github.com/JavaScriptDude/vscode-python_bug_230919

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Pyenv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
# None. Just problem outlined above
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

envFile: "<placeholder>"

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.16.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 5.15.0-1040-oracle
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (24 x 2485)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|94.29GB (28.66GB free)|
|Process Argv|--unity-launch /dpool/vcmain/dev/py/net/playwright/playwright_utils/test/playwright_utils_test --crash-reporter-id e151fb07-4234-4fa8-b983-d7f6da3bc129|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by sevenrats** [comment] 2023-09-21 06:16
Also having this issue. To my knowledge I did not change anything, it just started doing it this afternoon and won't stop. I've been using this project on vscode for months without issues, but today, randomly this happens. I have reinstalled, rebooted, can't make it go away.

**Comment by sevenrats** [comment] 2023-09-21 06:21
umm. I uninstalled the microsoft python extension and the issue went away. im not sure where my python syntax highlighting and autocompletion is coming from now, because ive removed all python plugins, but, its backing to working how it was? witchcraft.

**Comment by avoidik** [comment] 2023-09-21 10:02
after last update pylance ignores symlinked libraries from virtualenv

**Comment by avoidik** [comment] 2023-09-21 12:14
reproduce steps:

```terminal
$ mkdir -p blah/ahaha
$ cat <<'EOF' > blah/ahaha/__init__.py
__all__ = ['ahaha']
EOF
$ cat <<'EOF' > blah/ahaha/ahaha.py
def ahaha():
    print("ahaha!")
EOF
$ virtualenv --download --system-site-packages --activators bash .envahaha
$ source .envahaha/bin/activate
$ PYTHON_SEG="python$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')" # python3.11
$ ln -f -s "$(pwd)/blah/ahaha" "$(pwd)/.envahaha/lib/${PYTHON_SEG}/site-packages/ahaha"
$ mkdir project
$ cat <<'EOF' > project/abc.py
from ahaha import ahaha
if __name__ == "__main__":
    ahaha.ahaha()
EOF
$ python project/abc.py
ahaha!
```

now try to open it in vscode

```terminal
$ code .
```

using v2023.9.10 I was able to follow import definition, and using v2023.9.20 it didn't work

**Comment by debonte** [comment] 2023-09-21 14:06
Please upgrade to Pylance 2023.9.21 (our latest prerelease build) which includes Pyright 1.1.328 (and the fix for https://github.com/microsoft/pyright/issues/5943), and see if the issue is fixed for you.

**Comment by pikalaw** [comment] 2023-09-21 16:22
Just chiming in to say I have the same issue, which can be resolved by @debonte's suggestion.

**Comment by JavaScriptDude** [comment] 2023-09-21 21:51
I tested and can confirm that Pylance 2023.9.21 fixes the issue.

**Closed** 2023-09-21 21:59 UTC
Labels: needs repro
