### ISSUE TITLE
Call signature narrowing for overloaded methods/functions

### ISSUE THREAD

**Issue by BenjaminMidtvedt** [microsoft/pylance-release#5735] opened 2024-04-07 18:22 UTC
Pylance reports all available overloads for overloaded methods. However, as arguments are provided, some of them can be discarded. Example:

```py
@overload
def f(x: Literal["foo"], foo: int = 2) -> None: ...

@overload
def f(x: Literal["bar"], bar: int = 3) -> None: ...

def f(x: str, *args: int, **kwargs: int) -> None: ...
```

My expectation is that when entering the first literal string:

```py
f("bar", 
```
that pylance would suggest the call signature of the second overload directly. However, currently, the impossible first overload is still displayed:

![image](https://github.com/microsoft/pylance-release/assets/41636530/f004a301-7f69-4964-8880-5f0c4f6745da)

## Use case

It's a pretty common python pattern to dispatch to different implementations based on the value of some "mode" or "task" parameter. It is also commonly used in `__new__` to create one of several classes. This would greatly improve the user experience working with these patterns.

**Comment by Viicos** [comment] 2024-04-09 11:52
This is the same as https://github.com/microsoft/pylance-release/discussions/4148, and similar to https://github.com/microsoft/pylance-release/issues/4428

**Comment by StellaHuang95** [comment] 2024-07-16 19:18
Thanks for reporting the issue, this is indeed a dupe of https://github.com/microsoft/pylance-release/discussions/4148. Please upvote the idea if you'd like to see it being supported, thanks!

**Closed by StellaHuang95** 2024-07-16 19:18 UTC
Labels: duplicate, enhancement
