### ISSUE TITLE
Cant resolve long paths

### ISSUE THREAD

**Issue by sartyukhov** [microsoft/pylance-release#1410] opened 2021-06-08 10:25 UTC
## Environment data

-   Language Server version: Pylance v2021.6.0
-   OS and version: Manjaro Linux (Remote Containers inside Docker Ubuntu 20.04)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Expected behaviour

Hello! I can import module Retry with 2 ways, but with the long one it prints this message below.
Code works the same with any of them.

## Actual behaviour

![urllib3](https://user-images.githubusercontent.com/23495999/121168963-319f4500-c85c-11eb-829b-4a664c4c72fe.png)

```python
from urllib3.util.retry import Retry

from requests.packages.urllib3.util.retry import Retry
```

**Comment by jakebailey** [comment] 2021-06-08 16:27
The issue is not the length, but the dynamic behavior requests uses to create these modules.

Duplicate of #597.

**Closed by jakebailey** 2021-06-08 16:27 UTC
Labels: triage
