### ISSUE TITLE
Syntax highlighting wrong for function aliases

### ISSUE THREAD

**Issue by Kalilamodow** [microsoft/pylance-release#5785] opened 2024-04-21 19:33 UTC
## Environment data
-   Language Server version: 2024.4.1
-   OS and version: Windows 11 23H2
-   Python version: CPython 3.12.0

## Code Snippet

```python
def some_function(argument: str):    # "some_function" is yellow (function color, correct)
    print("some_function says", argument)

some_function("i am the function")   # "some_function" is yellow (function color, correct)

function_alias = some_function       # "function_alias" is blue (variable color, incorrect)
function_alias("i am the alias")     # "function_alias" is blue (variable color, incorrect)
```
![python issue](https://github.com/microsoft/pylance-release/assets/86890138/01375afb-c5b0-4e26-8daf-493ba7315a48)

## Logs

```
Pylance language server 2024.4.1 (pyright version 1.1.356, commit 6652c4a8) starting
2024-04-21 14:19:49.977 [info] [Info  - 2:19:49 PM] (60720) Server root directory: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist
2024-04-21 14:19:50.060 [info] [Info  - 2:19:50 PM] (60720) Starting service instance "pylance issue"
2024-04-21 14:19:50.086 [info] [Info  - 2:19:50 PM] (60720) Auto format for strings enabled
2024-04-21 14:19:50.175 [info] (60720) No configuration file found.
2024-04-21 14:19:50.178 [info] (60720) No pyproject.toml file found.
2024-04-21 14:19:50.180 [info] [Info  - 2:19:50 PM] (60720) Setting pythonPath for service "pylance issue": "C:\Users\{python install}\python.exe"
2024-04-21 14:19:50.182 [info] [Info  - 2:19:50 PM] (60720) Setting environmentName for service "pylance issue": "3.12.0 (global)"
2024-04-21 14:19:50.336 [info] [Info  - 2:19:50 PM] (60720) Assuming Python version 3.12.0.final.0
2024-04-21 14:19:50.338 [info] (60720) Assuming Python platform Windows
2024-04-21 14:19:50.606 [info] [Info  - 2:19:50 PM] (60720) Search paths for file:///c%3A/Users/{home}/python/pylance%20issue
2024-04-21 14:19:50.607 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{home}\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\typeshed-fallback\stdlib
2024-04-21 14:19:50.608 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{home}\python\pylance issue
2024-04-21 14:19:50.608 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{home}\python\pylance issue\typings
2024-04-21 14:19:50.609 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{home}\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\typeshed-fallback\stubs\...
2024-04-21 14:19:50.609 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{home}\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\bundled\stubs
2024-04-21 14:19:50.610 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{python install}\DLLs
2024-04-21 14:19:50.610 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{python install}\Lib
2024-04-21 14:19:50.611 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{python install}
2024-04-21 14:19:50.612 [info] [Info  - 2:19:50 PM] (60720)   c:\Users\{python install}\Lib\site-packages
2024-04-21 14:19:50.613 [info] [Info  - 2:19:50 PM] (60720) Adding fs watcher for library directories:
 file:///c%3A/{python install}/DLLs
file:///c%3A/{python install}/Lib
file:///c%3A/{python install}
file:///c%3A/{python install}/Lib/site-packages
2024-04-21 14:19:50.614 [info] [Info  - 2:19:50 PM] (60720) Adding fs watcher for directories:
 file:///c%3A/Users/{home}/python/pylance%20issue
2024-04-21 14:19:50.614 [info] (60720) Searching for source files
2024-04-21 14:19:50.619 [info] [Info  - 2:19:50 PM] (60720) Found 1 source file
2024-04-21 14:19:50.624 [info] (60720) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-04-21 14:19:50.624 [info] (60720) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-04-21 14:19:50.717 [info] (60720) [FG] parsing: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (78ms)
2024-04-21 14:19:50.839 [info] (60720) [FG] parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 3ms] (120ms)
2024-04-21 14:19:50.911 [info] (60720) [FG] binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi (69ms)
2024-04-21 14:19:50.912 [info] (60720) [FG] binding: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (1ms)
2024-04-21 14:19:50.926 [info] [Info  - 2:19:50 PM] (60720) Background analysis(1) root directory: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist
2024-04-21 14:19:50.932 [info] [Info  - 2:19:50 PM] (60720) Background analysis(1) started
2024-04-21 14:19:51.098 [info] (60720) pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-04-21 14:19:51.236 [info] (60720) [BG(1)] analyzing: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py ...
2024-04-21 14:19:51.237 [info] (60720) [BG(1)]   parsing: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (134ms)
2024-04-21 14:19:51.329 [info] (60720) [BG(1)]   parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 2ms] (91ms)
2024-04-21 14:19:51.377 [info] (60720) [BG(1)]   binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/builtins.pyi (46ms)
2024-04-21 14:19:51.378 [info] (60720) [BG(1)]   binding: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (1ms)
2024-04-21 14:19:51.418 [info] (60720) [BG(1)]   checking: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py ...
2024-04-21 14:19:51.418 [info] (60720) [BG(1)]     parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (21ms)
2024-04-21 14:19:51.437 [info] [Info  - 2:19:51 PM] (60720) Indexer background runner(2) root directory: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist (index)
2024-04-21 14:19:51.438 [info] [Info  - 2:19:51 PM] (60720) Indexing(2) started
2024-04-21 14:19:51.439 [info] (60720) [BG(1)]     binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/typing.pyi (18ms)
2024-04-21 14:19:51.460 [info] (60720) [BG(1)]     parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (8ms)
2024-04-21 14:19:51.466 [info] (60720) [BG(1)]     binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/types.pyi (5ms)
2024-04-21 14:19:51.480 [info] (60720) [BG(1)]     parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (6ms)
2024-04-21 14:19:51.483 [info] (60720) [BG(1)]     binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
2024-04-21 14:19:51.492 [info] (60720) [IDX(2)] scan packages file:///c%3A/Users/{home}/python/pylance%20issue ...
2024-04-21 14:19:51.493 [info] (60720) [IDX(2)]   read stdlib indices (46ms)
2024-04-21 14:19:51.495 [info] (60720) [BG(1)]     parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (2ms)
2024-04-21 14:19:51.497 [info] (60720) [BG(1)]     binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
2024-04-21 14:19:51.524 [info] (60720) [BG(1)]     parsing: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (8ms)
2024-04-21 14:19:51.528 [info] (60720) [BG(1)]     binding: file:///c%3A/Users/{home}/.vscode/extensions/ms-python.vscode-pylance-2024.4.1/dist/typeshed-fallback/stdlib/typing_extensions.pyi (4ms)
2024-04-21 14:19:51.542 [info] (60720) [BG(1)]   checking: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (164ms)
2024-04-21 14:19:51.543 [info] (60720) [BG(1)] analyzing: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (441ms)
2024-04-21 14:19:51.554 [info] (60720) [BG(1)] SemanticTokens range 0:0 - 8:0 at file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (6ms)
2024-04-21 14:19:51.557 [info] (60720) [BG(1)] SemanticTokens full at file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (1ms)
2024-04-21 14:19:51.561 [info] (60720) [BG(1)] indexing: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py [found 2] (2ms)
2024-04-21 14:19:51.562 [info] (60720) Indexing Done: file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py
2024-04-21 14:19:51.573 [info] (60720) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2024-04-21 14:19:52.029 [info] (60720) [BG(1)] SemanticTokens delta previousResultId:1713727191554 at file:///c%3A/Users/{home}/python/pylance%20issue/pylance%20issue.py (0ms)
2024-04-21 14:19:52.796 [info] (60720) [IDX(2)] scan packages file:///c%3A/Users/{home}/python/pylance%20issue (1351ms)
2024-04-21 14:19:52.797 [info] [Info  - 2:19:52 PM] (60720) scanned(2) 213 files over 1 exec env
2024-04-21 14:19:54.391 [info] (60720) [IDX(2)] index packages file:///c%3A/Users/{home}/python/pylance%20issue ...
2024-04-21 14:19:54.392 [info] (60720) [IDX(2)]   index execution environment file:///c%3A/Users/{home}/python/pylance%20issue ...
2024-04-21 14:19:54.392 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/concurrent/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.392 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/idlelib/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.393 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/lib2to3/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.393 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/pydoc_data/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.393 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/turtledemo/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.394 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/urllib/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.394 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/wsgiref/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.394 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/xmlrpc/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.394 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/__phello__/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.395 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/absl/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.395 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/astunparse/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.395 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/barcode/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.396 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/browser_cookie3/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.396 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/cchardet/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.396 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/cfscrape/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.397 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/cloudscraper/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.397 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/colorzero/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.397 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/Cython/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.397 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/eventlet/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.398 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/fastapi/_compat.py [skipped: private or protected file] (0ms)
2024-04-21 14:19:54.398 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/flask_sock/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.398 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/flatbuffers/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.399 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/g4f/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.399 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/gast/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.399 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/gpiozero/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.400 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/gpiozerocli/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.400 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/grpc_status/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.401 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/gvsbuild/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.401 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/gym_notices/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.401 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/h5py/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.401 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/keras/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.402 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/lxml/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.402 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/lz4/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.403 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/moby_dict/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.403 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/mouseinfo/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.404 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/msgpack/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.404 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/Naked/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.404 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/namex/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.405 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/opt_einsum/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.405 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pasta/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.406 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pdfkit/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.406 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/proxy_tools/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.406 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pyasn1_modules/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.407 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pydub/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.408 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pygetwindow/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.409 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pymsgbox/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.409 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pypub/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.410 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pyrect/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.410 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pytweening/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.411 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pyximport/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.411 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/pyzbar/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.411 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/py_arkose_generator/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.412 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/shapely/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.412 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/shellescape/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.412 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/shellingham/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.413 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/simple_websocket/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.413 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/tensorboard_data_server/__init__.py [skipped: no '__all__' defined] (1ms)
2024-04-21 14:19:54.413 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/trio_websocket/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.413 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/wheel/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.414 [info] (60720) [IDX(2)]     indexing: file:///c%3A/{python install}/Lib/site-packages/wrapt/__init__.py [skipped: no '__all__' defined] (0ms)
2024-04-21 14:19:54.431 [info] (60720) [IDX(2)]   index execution environment file:///c%3A/Users/{home}/python/pylance%20issue [found 5969 in 153 files] (60ms)
2024-04-21 14:19:54.431 [info] (60720) [IDX(2)] index packages file:///c%3A/Users/{home}/python/pylance%20issue [found 5969 in 1 exec envs] (653ms)
2024-04-21 14:19:54.432 [info] [Info  - 2:19:54 PM] (60720) indexed(2) 153 files over 1 exec env
2024-04-21 14:19:54.647 [info] [Info  - 2:19:54 PM] (60720) Indexing finished(2).
```

**Comment by erictraut** [comment] 2024-04-21 21:16
Pylance is working as intended here. In your example, the symbol `some_function` is declared as a function (using a `def` statement), and the symbol `function_alias` is declared as a variable (using an assignment statement). The fact that the `function_alias` variable is assigned a value that is callable doesn't change the fact that it's a variable. It could be assigned a different value (say `None`) on the next line.

**Comment by Kalilamodow** [comment] 2024-04-21 21:24
But couldn't it just change the color again if it's set to something else? So, when it's set as a function, it is highlighted as a function, but when it's set to a different value, it can become the color of a variable again. For example
```python
def some_function(argument: str) -> None: ...
variable = some_function  # currently highlighted as func
variable = 4  # now highlighted as a variable
```

**Comment by erictraut** [comment] 2024-04-21 21:44
The color indicates the semantic category of the symbol (whether it's a function, class, parameter, variable, constant, type alias, etc.). It doesn't reflect the type of the _value_ assigned to the symbol at that point in the program. The value assigned to a variable can (and often does) change from one line to the next whereas the semantic category doesn't change. I think most developers would find it confusing if the color of a symbol were to change from one line to the next. 

Also, consider that the type of a variable at a particular point in a program can be the combination of several types (a so-called "union"). For example, `foo = some_function if some_condition else None` assigns either a callable type or `None` to the variable `foo`. What color would you expect `foo` to be displayed as here — the color of a "function", a "variable", or perhaps some shade between those two colors?

**Closed** 2024-04-21 22:37 UTC
Labels: by design

**Comment by Kalilamodow** [comment] 2024-04-22 01:03
The value probably would change, but the type wouldn't. A variable that's set to a function would _probably_ stay a function, and if it doesn't, that's why there's a type checker. In the case of a  union, it could probably change depending on the usage. If it is of the type `Union[Callable, None]`, calling it as a function would make the type checker angry, and using an `is not None` could would colorize it as the variable color.

**Comment by ferdnyc** [comment] 2024-04-29 22:01
I think Pylance is doing exactly the correct thing here. It's _useful information_ to know when you're using a variable as a callable, vs. calling a function directly. That information would be lost if all callables were blindly highlighted as functions.

If you turn on inlay hints for argument names, they're even inserted into the aliased call, so clearly Pylance is correctly interpreting the code — and providing _ALL_ of the information available:

![image](https://github.com/microsoft/pylance-release/assets/538020/72e9a39b-6ae9-4d52-a6bd-95fdb3d2102a)

**Comment by heejaechang** [comment] 2024-04-29 22:38
we could add modifiers like `callable` or `type alias` to semantic token information so user could override the color if they want?

**Comment by jnooree** [comment] 2024-05-02 01:41
I strongly support @heejaechang's suggestion here. The fact that the symbol is a variable is of no interest. Most users don't care it's a variable or not; it's just a function from a user perspective.

**Comment by heejaechang** [comment] 2024-05-02 17:07
opened an issue, let's see how many upvote we gets.
