### ISSUE TITLE
Pydantic BasicModel with ConfigDict(frozen=True) is not hashable

### ISSUE THREAD

**Issue by andret13pinto** [microsoft/pylance-release#5774] opened 2024-04-18 13:42 UTC
## Environment data

-   Language Server version: v2024.4.1 
-   Python version: 3.11.4
-   Pydantic version: 2.6.0

## Code Snippet

```python
from pydantic import BaseModel
from pydantic import ConfigDict


class Foo(BaseModel):
    a: str

    model_config = ConfigDict(frozen=True)

bar = {Foo(a='a'), Foo(a='a1')}
```

![image](https://github.com/microsoft/pylance-release/assets/45769540/2460e167-1561-43ba-85ec-5a5834a8ff2e)

## Expected behavior

Pylance should understand that instances of Pydantic BaseModel classes with ConfigDict(frozen=True) are actually hashable.

## Actual behavior

Pylance reports that set entry is not Hashable.

**Comment by debonte** [comment] 2024-04-18 15:03
This is a duplicate of https://github.com/microsoft/pyright/issues/6481. See https://github.com/microsoft/pyright/issues/6481#issuecomment-1817154170 for an explanation of why Pylance doesn't work as you expect here.

**Closed by debonte** 2024-04-18 15:03 UTC
Labels: needs repro
