### ISSUE TITLE
Expected class type but received "Literal[...]"

### ISSUE THREAD

**Issue by timrid** [microsoft/pylance-release#365] opened 2020-09-14 06:23 UTC
## Environment data

-   Language Server version: 2020.9.4 (pyright 9983747f)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2 64-bit

## Expected behaviour
I have the following class of an array with a length:

```
class _ArrayMeta(type):
    def __getitem__(self, array_size: int):
        class ArrayWithSize(self):
            size = array_size
        return ArrayWithSize

class Array(bytearray, metaclass=_ArrayMeta):
    size: int

    def __init__(self, *args, **kwargs):
        if len(args) == 0:
            super().__init__(self.size)
        else:
            super().__init__(*args, **kwargs)
        if self.size != len(self):
            raise ValueError("Wrong Array Size (Got: {}, Expected: {})".format(len(self), self.size))
```

and want to use it in the following way:
```
@dataclass
class Struct1():
    entry1: Array[64]
    entry2: Array[64]
    entry3: Array[64]


s = Struct1()
s.entry1 = Array[64]()
```

## Actual behaviour
The code works as expected, but pylance gives me the following error:

![image](https://user-images.githubusercontent.com/6593626/93050390-1a338280-f663-11ea-8588-6011dd17191d.png)

**Comment by erictraut** [comment] 2020-09-14 08:00
You're using subscripting in a non-standard way that conflicts with assumptions that Pylance and other static type checkers need to make. The standard behavior in Python is for subscripting of a class to be used to provide type arguments for a generic type. I confirmed that mypy also emits errors in the same place as Pylance. 

If you want this to work in a manner that is compatible with static type checkers, you'll need to find a different approach — one that doesn't use subscripted expressions.

**Comment by timrid** [comment] 2020-09-20 14:04
I also thought about other ways of writing without subscripted expressions, for example a very simple factory method:

```
class Array2(bytearray):
    size: int

    def __init__(self, *args, **kwargs):
        if len(args) == 0:
            super().__init__(self.size)
        else:
            super().__init__(*args, **kwargs)
        if self.size != len(self):
            raise ValueError("Wrong Array Size (Got: {}, Expected: {})".format(len(self), self.size))
    
    @staticmethod
    def create(array_size: int):
        class ArrayWithSize(Array2):
            size = array_size
        return ArrayWithSize


@dataclass
class Struct1():
    entry1: Array2.create(64) = Array2.create(64)()
    entry2: Array2.create(64) = Array2.create(64)()
    entry3: Array2.create(64) = Array2.create(64)()


s = Struct1()
print(len(s.entry1))
```

This works as expected. The autocompletion works and pylance does not produce any error. 
But this is a very complicated notation. Are there other more readable approaches?

**Comment by erictraut** [comment] 2020-09-20 14:20
Is your intent to have the static type checker flag array size mismatches as errors? If so, the technique above won't work because the array length is not part of the type as you've defined it, and type checkers reason only about types, not about values.

Here's a potential solution that leverages generic types with literal type arguments.

```
_T = TypeVar("_T", bound=int)

class ArrayWithSize(Generic[_T]):
    def __init__(self, size: _T):
        self._size = size

    def __len__(self):
        return self._size


@dataclass
class Struct1(Generic[_T]):
    def __init__(self, size: _T):
        self.entry1 = ArrayWithSize(size)
        self.entry2 = ArrayWithSize(size)
        self.entry3 = ArrayWithSize(size)

    entry1: ArrayWithSize[_T]
    entry2: ArrayWithSize[_T]
    entry3: ArrayWithSize[_T]

s = Struct1(64)
print(len(s.entry1))

c64 = ArrayWithSize(64)
c100 = ArrayWithSize(100)
d1: ArrayWithSize[Literal[64]] = c64
d2: ArrayWithSize[Literal[64]] = c100  # Flagged as error
```

**Comment by jakebailey** [comment] 2020-10-21 18:16
It's been over a month since this issue was opened and we asked for feedback. I'm going to close this; if this is still an issue and you can provide the requested info, we can reopen it.

**Closed by jakebailey** 2020-10-21 18:16 UTC
Labels: waiting for info
