### ISSUE TITLE
python.analysis.completeFunctionParens add paraens when importing

### ISSUE THREAD

**Issue by Trim21** [microsoft/pylance-release#363] opened 2020-09-12 11:14 UTC
## Environment data

-   Language Server version: 2020.9.4
-   OS and version: win10 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

## Expected behaviour

`from pprint import pprint`

## Actual behaviour

![pylance_bug](https://user-images.githubusercontent.com/13553903/92994320-d8ec8700-f52b-11ea-8d91-4ab1ac4dc606.gif)

maybe relatived to https://github.com/microsoft/vscode-python/issues/4234

**Comment by jakebailey** [comment] 2020-09-14 17:58
Duplicate of #320

**Closed by jakebailey** 2020-09-14 17:58 UTC
Labels: triage
