### ISSUE TITLE
Right click functionality

### ISSUE THREAD

**Issue by holyoaks** [microsoft/pylance-release#2750] opened 2022-04-26 12:36 UTC
Issue Type: <b>Bug</b>

Starting yesterday, as soon as I open my Docker container app in VS Code, the right-click functionality on variables, class names, etc. disappears, and I'm left with just the standard `Change all Occurrences` menu option. I'm seeing warnings and errors in several logs. For example, the Log (Remote Server) shows a warning `[remoteagent] [warning] No ptyHost heartbeat after 6 seconds`. I'm also seeing multiple errors as shown below in the Log (Window):

```
[2022-04-26 07:28:49.742] [renderer1] [error] [Extension Host] Error: Unexpected SIGPIPE
	at process.<anonymous> (/root/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap.js:1:370)
	at process.emit (node:events:390:28)
```
This is making VS Code nearly unusable. Please help!

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id fb4199e6-8396-4083-9fce-d910eccdbdc3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container tv8_trivie (tv8_trivie_1)|
|OS|Linux x64 5.10.104-linuxkit|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (4 x 1996)|
|Memory (System)|3.84GB (0.32GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
jquerysnippets|don|0.0.1
terraform|has|2.22.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
mako|tom|0.2.0
JavaScriptSnippets|xab|1.8.0
gitlens|eam|12.0.6
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
sqltools|mtx|0.23.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by debonte** [comment] 2022-05-03 22:42
@holyoaks, the exception you provided above is the Python client telling us that Pylance crashed, but it doesn't explain **why** Pylance crashed, so it's not sufficient to diagnose the issue.

Can you please repro the issue and then send us the contents of your Python Language Server log in the Output pane? Our [troubleshooting guide] (https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) provides details on how to do that if you're not sure.

Also, can you possibly provide a code sample (or a link to a public repo) that reproduces this issue? I tried a simple `.py` file in a docker container and didn't see the issues you described.

**Comment by holyoaks** [comment] 2022-05-10 16:43
I cannot get the problem to occur with a simple python file, nor can I get it to occur with my application running locally (~40k lines of code). Running in the docker app, though, using the remote extension, it crashes. It's occurring occasionally with the `Jedi` language server as well, so it may simply be a problem with the docker app or resources available? Hard to tell at this point.

**Comment by holyoaks** [comment] 2022-05-10 20:42
To test my theory that it's specific to my Docker app, I bumped up the amount of swap space and memory dedicated to Docker itself. I've now been running Pylance v2022.4.3 for 4 hours and it has yet to crash. I will continue to monitor, but at this point, I think this was not a bug in VS Code or the extensions, but a lack of resources in Docker which caused the crash. Maybe something to add to the logging or docs to assist others in understanding what's going on?

**Comment by holyoaks** [comment] 2022-05-19 20:18
Yet I had a crash today. All the python right click functionality is gone. It's better with Docker having more resources, but it is still a problem. Please do not close

**Comment by erictraut** [comment] 2022-05-19 20:51
My best theory is that this is caused by memory exhaustion. Pyright, the static type checker that underlies pylance, uses an in-memory cache for types that it has already evaluated. It manages the size of this cache and empties it when it detects that memory usage is reaching the available limits. This technique relies on accurate information coming from the node.js runtime about the maximum heap size and the amount of memory already consumed. 

Here's how we could validate my theory. Create a "pyrightconfig.json" file if you haven't already done so. It should be located within the root of your project. Within the config file, add the following:
```python
{
    "verboseOutput": true
}
```

With that in place, try to repro the crash. The logs should now contain lines that begin with the string "Heap stats:" followed by a bunch of stats that come from the node.js runtime. I'm interested in those values, especially right before a crash occurs.

**Comment by holyoaks** [comment] 2022-05-19 20:56
Very good, thanks. I've created the `pyrightconfig.json` file with the specified config. I've yet to be able to predict the crash, but will monitor and see what I can do. Thanks again

**Comment by judej** [comment] 2022-06-06 15:45
Closing issue. Please reopen if/when you see the crash again. Also, if/when you do, would you please add the logs? thanks

**Closed by judej** 2022-06-06 15:45 UTC
Labels: waiting for user response
