### ISSUE TITLE
Code is unreachable message for reachable and running code

### ISSUE THREAD

**Issue by ChamanAgrawal** [microsoft/pylance-release#2476] opened 2022-03-15 12:23 UTC
## Environment data
-   Language Server version: 2022.3.1
-   OS and version: Windows 10 Home Single Language, 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.8

## Expected behaviour
Using influxdb==5.3.1 (https://github.com/influxdata/influxdb-python)
When I declare an instance of class `influxdb.DataFrameClient` , Pylance declares the code below declaration as unreachable, but on running the file; the code actually works. Similar thing also happens when using jupyter Notebook in vscode.

![image](https://user-images.githubusercontent.com/24999057/158376677-740821c7-3581-4bc2-8400-ea05c7deecd8.png)

![image](https://user-images.githubusercontent.com/24999057/158376589-1d7af288-b045-48f5-aa91-f7d81a6b354d.png)

## Actual behaviour

Since the code runs, it should be visible as reachable section.

**Comment by erictraut** [comment] 2022-03-15 14:35
Please provide a minimal self-contained sample in code form that exhibits the problem. It's not really possible to diagnose problems like this from screen shots of partial code.

**Comment by ChamanAgrawal** [comment] 2022-03-15 16:34
Hi @erictraut,
Here is a small piece of running code. I am also attaching the screenshot again because that is the only way I can think of to show the problem I have `Code in unreachable [Pylance]`.
```
from influxdb import DataFrameClient

influx_client = DataFrameClient()
print('Last line running')
```
![image](https://user-images.githubusercontent.com/24999057/158426085-d9406a23-302b-446b-a54c-fcb64255344c.png)

You can check the code by just running it, it prints the last print statement.
Do let me know I can do anything else, to clarify things. Thanks!

**Comment by erictraut** [comment] 2022-03-15 17:06
The issue here is that the influxdb code contains some unusual exception handling code to handle the case where `pandas` is not installed. Inside of an exception handler, it declares a proxy class called `DataFrameClient` that always raises an exception when its constructor is called. In the non-exception path (where `pandas` is successfully imported), `DataFrameClient` is imported from another sub-module. Pyright (the type checker that underlies pylance) uses some heuristics to determine which type definition to use in ambiguous (dynamic) cases like this. The current heuristic is preferring the proxy class in the exception path. I've updated the heuristic to prefer the non-exception path. This addresses the issue you're seeing. This change will be included in the next release.

**Comment by ChamanAgrawal** [comment] 2022-03-15 17:16
Great, thanks a lot

**Comment by bschnurr** [comment] 2022-03-17 16:37
This issue has been fixed in version 2022.3.2, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202232-16-March-2022)

**Closed by bschnurr** 2022-03-17 16:37 UTC
Labels: bug, fixed in next version

**Comment by AdityaGupta7782** [comment] 2022-04-07 13:54
Hi sir,
I want to fix the problem of code unreachable pylance please help me


import smtplib
import pyttsx3
import speech_recognition as sr
import datetime
import wikipedia
import webbrowser
import smtplib
import os

engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
# engine.setproperty(voices, voices[0].id)


def speak(audio):
    engine.say(audio)
    engine.runAndWait()
    
# def wishme(hour):
#     if hour>= 0 and hour<12:
#         print('Good Morinng! ')
#     elif hour>= 12 and hour<18:
#         print('Good Afternoon!')
#     else:
#         print('Good Evening!')
    
#     speak('I am jarvis Sir, How May I help you')
    
    
def takecommand():
    # it takes microphone input from users and returns string outputs
    
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print('Listening....')
        r.energy_threshold = 200
        r.pause_threshold = 1
        audio = r.listen(source)
        
    try:
        print('Recongnizing...')
        query = r.recognize_google(audio, language='en-in')
        print(f"user said: {query}\n")

    except Exception as e:

        print('Plaese Repeat that again...')
        return "None"
    return query

def sendemail(to, content):
    server = smtplib.SMTP('smntp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.login('adityagupta07018gmail.com', 'Nisha@2007')
    server.sendemail('yourgmaiol.com, to, content')
    server.close()
    
    
if __name__ == "__main__":
    # wishme()
    while True:
        query = takecommand().lower()

    # logic for executing tasks based on query
    if 'wikipedia' in query:
        speak("seasrching Wikiedia")
        query = query.replace('wikipedia', "")
        results = wikipedia.summary(query, sentences = 2)
        speak("According to Wikipedia")
        print(results)
        speak(results)
        
    elif 'open youtube' in query:
        webbrowser.open(youtube.com)
        
    elif 'open google' in query:
        webbrowser.open(google.com)

    elif 'open stackoverflow' in query:
        webbrowser.open(stackoverflow.com)
    
    elif 'the time' in query:
        strtime = datetime.datetime.now(),strtime("%H:%M:%S")
        speak(strtime)
        
    elif 'the vscode' in query:
        codepath ="C:\\Users\\Aditya 007\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"
        os.openfile()
        
    elif 'send email' in query:
        try:
            speak("What should I say")
            content = takecommand()
            to = "adityahacker07018@gmail.com"
            sendEmail(to, content)
            speak('Email has been sent!')
        except Exception as e:
            print(e)
            speak('sorry adibhau I am not able to sent this email')

            
![Screenshot (31)](https://user-images.githubusercontent.com/103197836/162215590-a198f7ea-64f1-4183-b3d2-b9f975ac09fd.png)

**Comment by enryH** [comment] 2023-02-28 16:06
I have the same issue using the `CollabDataLoaders` from `fastai`. Example:

```python
from dataclasses import dataclass, field
from fastai.collab import *
import pandas as pd


@dataclass
class DataSplits():
    is_wide_format: bool = field(init=True, repr=False)
    train_X: pd.DataFrame = None
    val_y: pd.DataFrame = None
    test_y: pd.DataFrame = None
    

def combine_data(train_df: pd.DataFrame, val_df: pd.DataFrame) -> Tuple[pd.DataFrame, float]:
    """Helper function to combine training and validation data in long-format. The 
    training and validation data will be mixed up in CF training as the sample
    embeddings have to be trained for all samples. The returned frac can be used to have
    the same number of (non-missing) validation samples as before.

    Parameters
    ----------
    train_df : pd.DataFrame
        Consecutive training data in long-format, each row having (unit, feature, value)
    val_df : pd.DataFrame
        Consecutive training data in long-format, each row having (unit, feature, value)

    Returns
    -------
    Tuple[pd.DataFrame, List[list, list]]
        Pandas DataFrame of concatenated samples of training and validation data.
        Fraction of samples originally in validation data.
    """
    X = train_df.append(val_df).reset_index()
    frac = len(val_df) / (len(train_df)+len(val_df))
    return X, frac

class CollabAnalysis():

    def __init__(self,
                 datasplits: DataSplits,
                 sample_column='Sample ID',
                 item_column='peptide',
                 target_column='intensity',
                 model_kwargs=dict(),
                 batch_size=64):
        self.X, self.frac = combine_data(datasplits.train_X,
                                         datasplits.val_y)
        self.batch_size = batch_size
        # if I comment out the next block ("self.dls") the lines after are reached.
        self.dls = CollabDataLoaders.from_df(self.X, valid_pct=self.frac,
                                             seed=42,
                                             user_name=sample_column,
                                             item_name=item_column,
                                             rating_name=target_column,
                                             bs=self.batch_size)
        # not reachable
        user_name=sample_column
        item_name=item_column
        rating_name=target_column
        # here it continues, but maybe not so interesting...
```

At runtime everything works as expected.

**Comment by debonte** [comment] 2023-02-28 20:30
@enryH, I'm unable to repro this. Can you please file a new issue?

**Comment by enryH** [comment] 2023-03-01 09:00
@debonte I cannot reproduce it either when I load the environment in a codespace. So might be due to Windows and an old python/fastai version... I'll see if I re-create the environment if the issue pertains and in that case open a new issue.

![image](https://user-images.githubusercontent.com/2833836/222091911-81355846-70d7-4650-8591-0e2ff2af7970.png)
