### ISSUE TITLE
Symlinks not resolved in extraPaths

### ISSUE THREAD

**Issue by brianm78** [microsoft/pylance-release#4883] opened 2023-09-26 12:36 UTC
When specifying a directory as an extra path for pylance (python.analysis.extraPaths setting), files and directories that are symlinks are not being recognised as valid imports, and are flagged as:

    Import "modulename" could not be resolved  Pylance(reportMissingImports)

This still works fine at runtime, just the linting / autocomplete etc fails.

Regular files / directories do work, so the additional path does seem to be working - just symlinks aren't being handled.

I believe this worked in the past (at least I remember this working with the same setup at one point, and don't think I've changed anything relevant since then)

## Environment data

-   Language Server version: Pylance v2023.9.20
-   OS and version: Arch linux
-   Python version (& distribution if applicable, e.g. Anaconda): python3.11.3

## Repro Steps

Create a module somewhere.  Eg:

    touch ~/testmodule.py

Create a directory somewhere:

    mkdir ~/lib

Add it to the extraPaths setting for pylance:

    "python.analysis.extraPaths": [
        "/home/brian/lib"
    ],

Symlink it to a directory listed in the extraPaths setting

    ln -s ~/testmodule.py  ~/lib

Import this in a python file:

    import testmodule

## Expected behavior

The module will be recognised as a valid import, with autocomplete etc applied as normal.

## Actual behavior

The module is flagged as nonexisting, with "Import "testmodule" could not be resolved"

**Comment by rchiodo** [comment] 2023-09-26 15:49
Thanks for the issue. This is a dupe of https://github.com/microsoft/pylance-release/issues/4852 which was fixed in 2023.9.21.

**Closed by rchiodo** 2023-09-26 15:49 UTC
Labels: needs repro
