### ISSUE TITLE
"Find All Implementations" produces no results

### ISSUE THREAD

**Issue by mforkel** [microsoft/pylance-release#1590] opened 2021-07-22 14:43 UTC
## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): 2021.7.1053846006
-   OS and version: WSL2 Debian in Windows 10 2004
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance 2021.7.4
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

With a method name selected, **References: Find All Implementations** shows all implementations of that method in all superclasses and subclasses defined in the workspace.

## Actual behaviour

**References: Find All Implementations** is available in the **Command Pallete**, but its result in References is "No results."

## Steps to reproduce:

Sample file:
```python
class Base:

    def method1(self):
        pass


class Sub1(Base):

    def method1(self):
        pass


class Sub2(Base):

    def method1(self):
        super().method1()
```

If I select `method1` in `Base`, **Find All Implementations** should find `Base.method1`, `Sub1.method1` and `Sub2.method1`. If I select `method1` in `Sub1`, **Find All Implementations** should find `Base.method1` and `Sub1.method1`. Currently, **Find All Implementations** does not find any of those implementations.

Of course, things get more interesting with more modules, packages and multiple inheritance.

Please note that **Find All Implementations** is different from **Find All References**, which will find the call to `method1` in `Sub2.method1` and `Base.method1` if the latter is selected.

I think this issue is related to microsoft/vscode-python#2694 and https://github.com/microsoft/vscode/issues/126666.

**Comment by judej** [comment] 2021-07-22 17:50
Thanks for the report. This is not a feature that Pylance supports as yet. Will add this to our list of proposed enhancements. Thanks!

**Comment by jakebailey** [comment] 2021-09-23 22:26
This is actually a dupe of #1200.

**Closed by jakebailey** 2021-09-23 22:26 UTC
Labels: enhancement
