### ISSUE TITLE
Feature request: copy reference 

### ISSUE THREAD

**Issue by xen** [microsoft/pylance-release#3069] opened 2022-07-17 13:39 UTC
I did search and didn't find any mention of this feature. 

Working with PyCharm I often use one of its features that allow to copy reference to the object from context menu. Here is an example of this feature:

<img width="727" alt="Screenshot 2022-07-17 at 15 30 51" src="https://user-images.githubusercontent.com/31260/179400854-cc3487c5-af82-4922-abd6-1c4a39e27503.png">

What it do. When you right/command click to the object or line IDE allow you to copy "pythonic" path to the object. For example, if you have function 'func' inside the file 'project/name/models.py' you will get 'project.name.models.func' in clipboard. 

This feature simplifies code management and let you send to colleague link to specific place in the code much easier. 

I guess this feature already partially implemented internally for breakpoints in debugger.

**Comment by judej** [comment] 2022-07-19 17:44
Dupe of https://github.com/microsoft/pylance-release/discussions/2669. Please feel free to upvote

**Closed by judej** 2022-07-19 17:44 UTC
Labels: triage-needed, feature-request

**Comment by xen** [comment] 2022-07-20 14:16
I searched by "copy reference", but this is the same. Thank you @judej
