### ISSUE TITLE
No auto complete options show for Openpyxl  

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#947] opened 2020-06-18 00:18 UTC
From https://github.com/MicrosoftDocs/intellicode/issues/199 by @Blotuxs 

> Hi
> 
> About a month ago Intellicode showed me recommendations for the Openpyxl library in Python. And since a few days ago it does not show all the recommendations (As seen in the image it does not show the Cell recommendation or others).
> 
> Try reinstalling Visual Studio Code, Openpyxl, Python and Intellicode but it doesn't work.
> 
> Try to delete the Extensions folder and download it again.
> 
> Settings:
> "python.jediEnabled": false
> "python.languageServer": "Microsoft"
> 
> I would appreciate any recommendation. Thank, in advance.
> ![Screenshot (3)](https://user-images.githubusercontent.com/66394989/83702938-845c7600-a5e4-11ea-9130-b3eb7c81f05d.png)

> Update:
> 
> If I dont click on "Enable it and Reload Windows", appear all the suggestions
> 
> ![Captura de pantalla (9)](https://user-images.githubusercontent.com/66394989/84925734-bb309280-b0a0-11ea-9885-d0eeb65e797d.png)

**Comment by jakebailey** [comment] 2021-02-12 23:48
I'm not sure this is related to Pylance, if the old "Microsoft" language server setting was being used. Try with pylance enabled, perhaps?

**Comment by luabud** [comment] 2021-02-12 23:51
@MoonBrain1 and @84tom, we have recently released a new and more performant language server called Pylance which likely solves these issues you are reporting.  You can download [Pylance](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/) from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and install it alongside the core Python extension.  Would you be able to try it out and let us know if it's working?

**Comment by jakebailey** [comment] 2021-03-16 18:53
It's been over a month since we asked for info and added the "waiting for info label"; I'm going to close this. If this is still a problem and you can provide more info, we can reopen this issue.

**Comment by ptrobot555** [comment] 2021-05-12 08:15
Any update regarding this issue? I'm using Pylance 2021.5.1 but the issue is still there.

_Not working with wb["Sheet1"]_

![image](https://user-images.githubusercontent.com/78074165/117941217-295df380-b30a-11eb-9fd9-3f83ef98296a.png)

_But works with wb.worksheets[0]_

![image](https://user-images.githubusercontent.com/78074165/117941424-5ad6bf00-b30a-11eb-97a4-89117cdbf095.png)

**Comment by jakebailey** [comment] 2021-05-12 16:35
Thanks. This appears to be a case where we can't infer the type of the result of the index expression; it's likely this library needs to be better stubbed (or have stubs written) to capture what that operator does.

**Comment by ptrobot555** [comment] 2021-05-14 09:58
Thanks for the input, @jakebailey. I have installed the openpyxl-stubs and it seems to be working fine now (tested both in Windows 10 and Linux).

$ pip install openpyxl-stubs
https://github.com/MartinThoma/openpyxl-stubs

![image](https://user-images.githubusercontent.com/78074165/118254559-847b1c00-b4ab-11eb-84be-ffeb38614abe.png)

**Comment by jakebailey** [comment] 2021-05-14 16:22
Thanks for that link; we may be able to bundle those stubs like we do a few other stub packages.

**Comment by jakebailey** [comment] 2021-05-19 23:42
This issue has been fixed in version 2021.5.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202153-19-may-2021

**Closed by jakebailey** 2021-05-19 23:42 UTC
Labels: fixed in next version, needs stub
