### ISSUE TITLE
Add import code action inserting import after usage instead of before

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pylance-release#6356] opened 2024-09-06 02:16 UTC
![image](https://github.com/user-attachments/assets/dc6dabbe-63cd-46a1-aa39-9b2d382c1c02)

## Environment data

-   Pylance version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet
https://github.com/microsoft/pylance-release/blob/main/testing/single/src/codeaction.py

```python
# you can trigger quick fix explicitly using `QuickFix` command
# use `command palette` to find the command and its short cut
# since code action usually modify code, make sure `undo` work as expected.

# place cursor on `os` and confirm lightbulb shows up
# and trigger quick fix and confirm `Add 'import os'` is listed
os

# place cursor on `Path` and confirm lightbulb shows up
# and trigger quick fix and confirm `Add 'from pathlib import Path'` is listed
Path

# place cursor on `userModule` and confirm lightbulb shows up
# and trigger quick fix and confirm `Add 'from lib import userModule'` is listed
userModule

# place cursor on `MyType` and confirm lightbulb shows up
# and trigger quick fix and confirm `Add 'from lib.userModule import MyType'` is listed
MyType()


# place cursor on `sys` and confirm lightbulb shows up
# and trigger quick fix and confirm `remove unused import` is listed
# execute the code action and confirm it works as expected
import sys
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by StellaHuang95** [comment] 2024-09-06 16:54
dupe of https://github.com/microsoft/pylance-release/issues/5425

**Closed by StellaHuang95** 2024-09-06 16:54 UTC
Labels: needs repro
