### ISSUE TITLE
Any comment that contains the word "region" triggers an error "#region is missing corresponding #endregion"

### ISSUE THREAD

**Issue by kurtschelfthout** [microsoft/pylance-release#3765] opened 2022-12-16 10:21 UTC
Any comment that contains the word "region" triggers an error "#region is missing corresponding #endregion"

Also I can't find a way to turn region checking off entirely ( e.g. using `"python.analysis.diagnosticSeverityOverrides"`). Nothing relevant is listed in the settings.

## Environment data
-   Language Server version: Pylance language server 2022.12.20 (pyright 621d886b) starting
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Code Snippet

```python
def foo() -> None:
    # region_name
    pass
```

## Repro Steps

Just paste that code in a py file, see the spurious error show up.

## Logs

Not relevant here I reckon

**Comment by return42** [comment] 2022-12-16 17:33
IDK if it is related to pylance, but I have this issue when using pyright.

**Comment by rchiodo** [comment] 2022-12-16 22:59
Thanks for the bug. I believe I've found the root cause, so we should be able to fix this soon.

**Comment by heejaechang** [comment] 2023-01-04 23:42
This issue has been fixed in prerelease version 2023.1.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023111-4-January-2023-PreRelease)

**Closed by heejaechang** 2023-01-04 23:42 UTC
Labels: bug, fixed in next version

**Comment by taldcroft** [comment] 2023-04-18 12:29
I'm seeing this again with the latest releases of VS code 1.77.1 and Pylance v2023.4.20 on Mac OSX.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/348089/232777060-5769a9b2-03b2-4069-88ac-3b6f717e10b2.png">
