### ISSUE TITLE
Split "Overload" hover into multiple lines, like completion

### ISSUE THREAD

**Issue by wuyudi** [microsoft/pylance-release#789] opened 2020-12-29 16:54 UTC
This is the typing hint of `map`

![image](https://user-images.githubusercontent.com/30024051/103299951-b62da200-4a38-11eb-8317-aa5dfb6b2cb7.png)

Maybe it's better to `\n` for each case?

```py
(function) map: Overload[
(__func: (p0: _T1) -> _S, __iter1: Iterable[_T1]) -> Iterator[_S], 
(__func: (p0: _T1, p1: _T2) -> _S, __iter1: Iterable[_T1], __iter2: Iterable[_T2]) -> Iterator[_S],
(__func: (p0: _T1, p1: _T2, p2: _T3) -> _S, __iter1: Iterable[_T1], __iter2: Iterable[_T2], __iter3: Iterable[_T3]) -> Iterator[_S],
(__func: (p0: _T1, p1: _T2, p2: _T3, p3: _T4) -> _S, __iter1: Iterable[_T1], __iter2: Iterable[_T2], __iter3: Iterable[_T3], __iter4: Iterable[_T4]) -> Iterator[_S],
(__func: (p0: _T1, p1: _T2, p2: _T3, p3: _T4, p4: _T5) -> _S, __iter1: Iterable[_T1], __iter2: Iterable[_T2], __iter3: Iterable[_T3], __iter4: Iterable[_T4], __iter5: Iterable[_T5]) -> Iterator[_S],
(__func: (*args: Any, **kwargs: Any) -> _S, __iter1: Iterable[Any], __iter2: Iterable[Any], __iter3: Iterable[Any], __iter4: Iterable[Any], __iter5: Iterable[Any], __iter6: Iterable[Any], *iterables: Iterable[Any]) -> Iterator[_S]
]
```

Or it seems better to be:

```py
(__func: (*args: Any, **kwargs: Any) -> _S,
__iter1: Iterable[Any],
__iter2: Iterable[Any],
__iter3: Iterable[Any],
__iter4: Iterable[Any],
__iter5: Iterable[Any],
__iter6: Iterable[Any],
*iterables: Iterable[Any]
) -> Iterator[_S]
```

**Comment by ain-soph** [comment] 2021-01-11 21:01
Highly agree with it. It's painful to read a method with many kinds of overload.

**Comment by bschnurr** [comment] 2021-01-11 21:08
I think we can solve this by adding double space or double backslash to the end of each line to signify a line break in markdown.

**Comment by jakebailey** [comment] 2021-01-11 21:09
These blocks are code blocks, and I don't think you can do that in them. If an overload is at the top level of a printed type for a tooltip, then it'd be nice to split it up into multiple lines each their own signature (rather than the nesting).

**Comment by jakebailey** [comment] 2021-02-05 01:53
This is actually a dupe of #612.

**Closed by jakebailey** 2021-02-05 01:53 UTC
Labels: enhancement
