### ISSUE TITLE
Code action to add `f` to a string literal

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#2960] opened 2022-06-22 20:36 UTC
https://twitter.com/mariatta/status/1539394706466951170

Basically detect when a string literal becomes an f-string and automatically add the `f` prefix or at least offer it as a notice to the user that they may have forgotten the `f` prefix.

**Comment by judej** [comment] 2022-06-23 17:41
Dupe of https://github.com/microsoft/pylance-release/discussions/2639. It is on the roadmap.

**Closed by judej** 2022-06-23 17:41 UTC
Labels: triage
