### ISSUE TITLE
Highlighting for type aliases in python

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3754] opened 2022-12-12 02:29 UTC
For example,

```python
from typing import NewType

AliasRawType = str
AliasNewType = NewType("AliasNewType", str)
test="helloworld"
```

We can see that AliasRawType and test have the same highlight.

![image](https://user-images.githubusercontent.com/100815370/206947958-76e41b0d-c1eb-4fcd-aace-8f80a1178442.png)

I hope that python can recognize that` AliasNewType` is an aliases instead of variable.

Can I set another color for all type aliases?
Thank you for your reply.

**Comment by debonte** [comment] 2024-03-01 23:58
Duplicate of #3100

**Closed by debonte** 2024-03-01 23:58 UTC
Labels: enhancement
