### ISSUE TITLE
"Go to definition" does not work when the method is in the parent class

### ISSUE THREAD

**Issue by ibobak** [microsoft/pylance-release#5903] opened 2024-05-20 22:59 UTC
Type: <b>Bug</b>

# Behaviour

when I try to do "go to definition",  it will NOT work for the function which is in the parent class.

## Steps to reproduce:

1. Get this code: https://pypi.org/project/pytorch-lifestream/ 
2. remove all directories except "demo" from this code
3. create a new environment, inside it do "pip install pytorch-lifestream", so that this library itself will be in your env, while the notebooks will be in the project.
4. use the notebook supervised-sequence-to-target.ipynb - there is the code which is on screenshot.

As you may see, there is a class PandasDataPreprocessor which is derived from DataPreprocessor, the latter has a method fit_transform().

Now I want to navigate this from code, and it just doesn't work:
![image](https://github.com/microsoft/vscode-python/assets/8807043/d9b6b3a6-a604-42f6-9d2a-02d7b3480595)
![image](https://github.com/microsoft/vscode-python/assets/8807043/5f668ce3-e504-44ad-9e05-b3782c63e2a7)

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.6.0
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|.NET Install Tool|ms-dotnettools.vscode-dotnet-runtime|2.0.5|
|autoDocstring - Python Docstring Generator|njpwerner.autodocstring|0.6.1|
|Ayu Monokai|lakshits11.ayu-monokai|0.0.3|
|Black Formatter|ms-python.black-formatter|2024.2.0|
|C#|ms-dotnettools.csharp|2.28.11|
|C# Dev Kit|ms-dotnettools.csdevkit|1.5.20|
|Checkpoints|micnil.vscode-checkpoints|1.3.3|
|Conventional Commits|vivaxy.vscode-conventional-commits|1.25.0|
|Data Wrangler|ms-toolsai.datawrangler|1.0.2|
|Dev Containers|ms-vscode-remote.remote-containers|0.362.0|
|Django|batisteo.vscode-django|1.15.0|
|Docker|ms-azuretools.vscode-docker|1.29.1|
|Docs View|bierner.docs-view|0.1.0|
|Edit csv|janisdd.vscode-edit-csv|0.9.1|
|Git Extension Pack|donjayamanne.git-extension-pack|0.1.3|
|Git Extension Pack (GPack)|SeyyedKhandon.gpack|2.0.0|
|Git File History|pomber.git-file-history|1.0.1|
|Git History|donjayamanne.githistory|0.6.20|
|Github Light Theme|Hyzeta.vscode-theme-github-light|7.14.2|
|GitHub Plus Theme|thenikso.github-plus-theme|1.4.3|
|GitHub Theme|GitHub.github-vscode-theme|6.3.4|
|gitignore|codezombiech.gitignore|0.9.0|
|GitLens — Git supercharged|eamodio.gitlens|15.0.3|
|Grey Light+ Pro|elanzalaco.grey-light-plus-pro|0.0.1|
|IntelliCode for C# Dev Kit|ms-dotnettools.vscodeintellicode-csharp|2.1.11|
|JavaScript Debugger|ms-vscode.js-debug|1.89.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|Jinja|wholroyd.jinja|0.0.8|
|julia light|JuliaLight.julia-light|0.4.0|
|Jupyter|ms-toolsai.jupyter|2024.4.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Jupyter Theme|sam-the-programmer.jupyter-theme|0.1.3|
|JupyterLab Light Theme|MiguelCorralJr.jupyterlab-light-theme|0.1.1|
|Light Pink Theme|mgwg.light-pink-theme|0.6.0|
|Markdown All in One|yzhang.markdown-all-in-one|3.6.2|
|Markdown Preview Enhanced|shd101wyy.markdown-preview-enhanced|0.8.13|
|MZ Light Grey Theme|Malaz-YI.mz-light-grey|2.1.1|
|Night Owl|sdras.night-owl|2.0.1|
|Notepad++ color themes|ShayanAhmedKhan.notepadpp-color-theme|0.2.0|
|Numbered Bookmarks|alefragnani.numbered-bookmarks|8.4.0|
|One Dark Pro|zhuangtongfa.material-theme|3.17.2|
|One Dark Theme|mskelton.one-dark-theme|1.14.2|
|Open in GitHub, Bitbucket, Gitlab, VisualStudio.com !|ziyasal.vscode-open-in-github|1.3.6|
|Path Intellisense|christian-kohler.path-intellisense|2.8.5|
|Project Manager|alefragnani.project-manager|12.8.0|
|Pylint|ms-python.pylint|2023.10.1|
|Python|ms-python.python|2024.6.0|
|Python Debugger|ms-python.debugpy|2024.6.0|
|Python Environment Manager|donjayamanne.python-environment-manager|1.2.4|
|Python Extension Pack|donjayamanne.python-extension-pack|1.7.0|
|Python Indent|KevinRose.vsc-python-indent|1.18.0|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.110.1|
|Remote - SSH: Editing Configuration Files|ms-vscode-remote.remote-ssh-edit|0.86.0|
|Remote - Tunnels|ms-vscode.remote-server|1.5.1|
|Remote Development|ms-vscode-remote.vscode-remote-extensionpack|0.25.0|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Studio Icons|jtlowe.vscode-icon-theme|1.6.6|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
|Visual Studio Keymap|ms-vscode.vs-keybindings|0.2.1|
|WSL|ms-vscode-remote.remote-wsl|0.88.2|
|Zoomer|anthonyattard.zoomer|0.3.1|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 2156)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|251.76GB (231.03GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
fchga941:31046352
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by debonte** [comment] 2024-05-21 05:24
This is a duplicate of https://github.com/microsoft/pylance-release/issues/5902. The code after `%%time` is not treated as Python code and therefore none of the Python language server features will work as you expect there.

**Closed by debonte** 2024-05-21 05:24 UTC
Labels: needs repro
