### ISSUE TITLE
Sphinx Style Docstring Rendering Feature

### ISSUE THREAD

**Issue by OmerFI** [microsoft/pylance-release#2251] opened 2022-01-15 07:03 UTC
## Environment data

-   Language Server version: 2022.1.1
-   OS and version: Windows 11
-   Python version: 3.10.0

## Expected behaviour

Sphinx style docstrings should be shown correctly.

## Actual behaviour

Sphinx style docstrings are not shown correctly, like:

![docstring image](https://user-images.githubusercontent.com/54645034/149612678-25b7f63d-8fad-4a73-a599-4c277be2bd08.png)

**Comment by judej** [comment] 2022-03-08 22:46
Thanks for the report. Will investigate this.

**Comment by avm19** [comment] 2022-04-04 19:38
I can confirm that the issue is still present. Here is another example, which illustrates that of two methods defined _in the same file and for the same class_, only one has its docstring shown correctly.

The docstring is displayed correctly:
![image](https://user-images.githubusercontent.com/52547519/161618174-4f2313a5-9242-48a9-b663-99c9a8ab2545.png)

The docstring is not shown (despite being present in the source code):
![image](https://user-images.githubusercontent.com/52547519/161618408-30ce7646-b986-48ad-8c4c-0ea4852455aa.png)

<details><summary>VS Code version info:</summary>

> Version: 1.66.0 (user setup)
> Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
> Date: 2022-03-30T05:50:14.623Z
> Electron: 17.2.0
> Chromium: 98.0.4758.109
> Node.js: 16.13.0
> V8: 9.8.177.11-electron.0
> OS: Windows_NT x64 10.0.19042
</details>

**Comment by bschnurr** [comment] 2022-04-11 21:18
@OmerFI what are you expecting?

currently it shows the `__init__` text

![image](https://user-images.githubusercontent.com/1946977/162835128-2acb72a4-9d27-454b-9f66-7e363654c6d2.png)

**Comment by bschnurr** [comment] 2022-04-11 21:19
> I can confirm that the issue is still present. Here is another example, which illustrates that of two methods defined _in the same file and for the same class_, only one has its docstring shown correctly.
> 
> The docstring is displayed correctly: ![image](https://user-images.githubusercontent.com/52547519/161618174-4f2313a5-9242-48a9-b663-99c9a8ab2545.png)
> 
> The docstring is not shown (despite being present in the source code): ![image](https://user-images.githubusercontent.com/52547519/161618408-30ce7646-b986-48ad-8c4c-0ea4852455aa.png)
> 
> VS Code version info:

this issue should be solved in the latest 2022.4.0 version.. issue with panda type stubs

**Comment by OmerFI** [comment] 2022-04-11 21:30
@bschnurr

When I use Numpy style docstring, it is shown beautifully, like:

![docstring-numpy](https://user-images.githubusercontent.com/54645034/162836569-ef3325b7-5843-4aea-a305-60c6e87cd3d3.png)

But, this is not the case with Sphinx style docstring:

![docstring-sphinx](https://user-images.githubusercontent.com/54645034/162836640-dcf7c821-82c3-4128-b426-6f6c10ba6e0f.png)

**Comment by avm19** [comment] 2022-04-11 21:38
@bschnurr I've checked the latest versions of both regular VS Code and VS Code Insiders. In either case, the docstring is not displayed correctly (or rather at all, only the function's signature).
Regular version:
```
Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042
```
![image](https://user-images.githubusercontent.com/52547519/162836859-02e5a002-dfb8-40eb-a005-6baf36db3a71.png)

Insider's build:
```
Version: 1.67.0-insider (system setup)
Commit: b84feecf9231d404a766e251f8a37c730089511b
Date: 2022-04-11T05:15:52.676Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042
```
![image](https://user-images.githubusercontent.com/52547519/162836927-47883d7c-1ae0-46be-ab0b-f414d9739d18.png)

And if you stretch it:
![image](https://user-images.githubusercontent.com/52547519/162837759-9884c773-4b0b-4e46-87a8-ef4d0347478d.png)

**Comment by bschnurr** [comment] 2022-04-11 21:46
if you `go to def` on convert_dtypes does it take you NDFrame class's convert_dtypes with docstring?

**Comment by bschnurr** [comment] 2022-04-11 21:50
> @bschnurr
> 
> When I use Numpy style docstring, it is shown beautifully, like:
> 
> ![docstring-numpy](https://user-images.githubusercontent.com/54645034/162836569-ef3325b7-5843-4aea-a305-60c6e87cd3d3.png)
> 
> But, this is not the case with Sphinx style docstring:
> 
> ![docstring-sphinx](https://user-images.githubusercontent.com/54645034/162836640-dcf7c821-82c3-4128-b426-6f6c10ba6e0f.png)

We currently try to detect the docstring format and do minimal changes to them so that they sort of appear like they do in raw text. VSCode treats the doctring text as markdown. see  https://medium.com/@michael.isprihanto/how-to-guide-markdown-in-visual-studio-code-e8a68cc01f64

so for this example with no fixups it would be shown like this
![image](https://user-images.githubusercontent.com/1946977/162839177-48cb31a9-9256-4026-b3ba-7bb3fc8f8c67.png)

**Comment by bschnurr** [comment] 2022-04-11 21:51
parser code here https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/docStringConversion.ts

**Comment by bschnurr** [comment] 2022-04-11 21:53
R you requesting something like this?
```
This is a Sphinx Stype Docstring

:param a: variable 1
:type a: int
:return: a
:rtype: int
```
to 

```
This is a Sphinx Stype Docstring
(a: int) -> int 
```

**Comment by OmerFI** [comment] 2022-04-11 22:08
> R you requesting something like this?
> 
> ```
> This is a Sphinx Stype Docstring
> 
> :param a: variable 1
> :type a: int
> :return: a
> :rtype: int
> ```
> 
> to
> 
> ```
> This is a Sphinx Stype Docstring
> a: int
> returns a: int
> ```

Yes, that's what I want.

**Comment by avm19** [comment] 2022-04-11 22:52
> if you `go to def` on convert_dtypes does it take you NDFrame class's convert_dtypes with docstring?

@bschnurr Go to Definition takes me to here:
![image](https://user-images.githubusercontent.com/52547519/162843576-cb43724f-3043-4315-9bce-559d801d445c.png)

Interestingly, mouse hover over a different method shows a docstring:
![image](https://user-images.githubusercontent.com/52547519/162843764-0c982062-ca50-4ddb-85bd-a083f6600b72.png)

A docstring is displayed for some methods but not for others. I tried to find a correlation with what class the method resolves to, but could not. For example, `pd.DataFrame.cummin` and `pd.DataFrame.abs` are both defined in `pandas.core.generic`, both have a docstrings displayed by built-in `help()`, but only `abs` shows a docstring on mouse over and "Trigger Suggest".

`Pylance v2022.4.0`

To be honest, I am not sure how the things with Pylance and stubs. Maybe the problem I complain about is not the same issue.

**Comment by matt-schwartz** [comment] 2022-06-12 17:11
VS Code is natively just rendering the docstring content as markdown in the hover box.  Ideally Python hover would be rendered via Sphinx so it's nicely styled regardless of the docstring format.  This might be an expensive operation, so a "light" parser that handles each of the common docstring formats and renders HTML in the hover box would be great to have.

**Comment by MiguelGuthridge** [comment] 2022-08-25 04:48
I write a lot of my docstrings as markdown (so that I can use `pdoc` to generate my documentation), and have noticed that there's quite a few things that behave extremely poorly. These issues seem to be very difficult to condense down into a minimal reproducible example, and have lots of very finicky edge cases surrounding them. If I can get some easier things to reproduce

* Nested indentation is super unreliable. The parser can't seem to match levels of indentation, and half the time it needs me to indent by >6 spaces to increase the indentation level.
* I can't use markdown tables within the documentation. Perhaps this is a limitation of VS Code though.

**Comment by MiguelGuthridge** [comment] 2022-08-25 05:12
Here's an example of the indentation issue:
```py
def myFunction():
    """
    * This is my first dot point. Its indentation level
      is correctly assigned to be zero.

    * Now this is another dot point. Once again, its
      indentation level is zero, which is correct.

      * But now I want to have an indented dot point. VS Code kept the
        indentation for this at zero even though it is indented.

    * This dot point just resets the indentation level.

        * Let's indent it even more. Notice how it still doesn't work, even
          though this is now very clearly on a deeper level of indentation.

    * This dot point just resets the indentation level.

          * And now finally, after six spaces, it does a deeper level of
            indentation. But notice how this line has all the indentation
            removed and is no-longer part of the dot point?

          * Now, even though the indentation level is still six spaces, VS Code
            treats it as level zero indentation.

    * When I go back to the first level of indentation, there is no difference.
      This absolutely butchers a lot of my complex documentation, and makes it
      borderline unreadable in VS Code.
    """
```

This will render as follows (split into multiple screenshots as I can't increase the size of the popup):

![image](https://user-images.githubusercontent.com/31365175/186580104-50f0b672-6c4c-40c6-8205-1f2278398b60.png)
![image](https://user-images.githubusercontent.com/31365175/186580139-d4a3c506-b785-419c-941b-93faa1e16e59.png)

I would massively appreciate a fix on this at some point soon, since it really breaks a lot of the documentation I write, especially for highly technical code that requires detailed descriptions.

**Comment by OmerFI** [comment] 2022-09-29 17:17
> VS Code is natively just rendering the docstring content as markdown in the hover box. Ideally Python hover would be rendered via Sphinx so it's nicely styled regardless of the docstring format. This might be an expensive operation, so a "light" parser that handles each of the common docstring formats and renders HTML in the hover box would be great to have.

I will be happy if this feature will be coming in the next releases

**Comment by MiguelGuthridge** [comment] 2022-09-30 04:54
> VS Code is natively just rendering the docstring content as markdown in the hover box does this mean that my issue described above is actually an issue with VS Code itself? I might want to copy my comment there too.

**Comment by Diogo-Rossi** [comment] 2022-10-20 23:55
> We currently try to detect the docstring format and do minimal changes to them so that they sort of appear like they do in raw text. VSCode treats the doctring text as markdown. see

If that is the proposal, it would be good if the changes remain more minimal.
There are some docstring formatting using indentation that disappear with the markdown parser, which is not predictable.

@MiguelGuthridge showed an example, here is another simpler one:
```python
def foo(a: str, b: float, c: int, d: list[float], e: tuple[str]):
    """Test

    My function

    Parameters
    ----------
    a : str
        Et quam quidem sit distinctio aliquam deserunt occaecati voluptates. Laudantium nulla
        ea officia. Voluptatum rerum expedita ipsam dolor quia.
    b : float
        Molestiae aliquid libero. Dolores voluptate eveniet. Voluptas expedita rem doloribus
        possimus perferendis non molestiae.
    c : int
        Voluptas officia autem maiores temporibus nihil ea. Molestiae est doloribus ducimus
        modi quisquam. Velit quasi aspernatur aut dolor. Voluptas rerum aut vel debitis. Omnis
        magnam nobis consequatur mollitia. Nemo ea debitis animi et saepe dicta ut. Hic fugiat
        aut facere. Itaque ea eos deleniti asperiores neque quia. Molestiae architecto sed
        rerum sequi suscipit. Omnis sunt ut voluptatum esse. Consequuntur eaque consequuntur.
        Velit et aut ea sit. Quos mollitia omnis incidunt doloribus beatae aspernatur
        exercitationem consequatur est. Voluptates asperiores itaque. Excepturi nam omnis.
        Doloribus reiciendis voluptatem. Blanditiis eos earum cupiditate autem qui nihil ex
        omnis. Enim alias exercitationem et fugit tempora voluptates dolores vel.
    d : list[float]
        Dolores quia mollitia blanditiis incidunt ab sunt non rerum. Aperiam sed neque ut quis
        excepturi voluptas quibusdam odio voluptates. Harum ea necessitatibus quibusdam omnis
        explicabo placeat. Eum qui deserunt. Quis nihil iure dicta id vero doloribus.
    e : tuple[str]
        Quo fugit rerum et ipsum et repellat aut. Voluptas provident autem praesentium et
        molestiae. Nulla et atque voluptatem ut.
    """
```


![image](https://user-images.githubusercontent.com/57204023/197080547-fb6f629b-e2ab-4516-9709-595da231b2a8.png)

**Comment by Diogo-Rossi** [comment] 2022-10-21 00:14
Another example is the use of sphinx directives.

They just are not show at all.

```python
def foo(a: str, b: float):
    """Test

    My function
    
    .. note:: 
        This is my note
    

    Parameters
    ----------
    a : str
        Et quam quidem sit distinctio aliquam deserunt occaecati voluptates. Laudantium nulla
        ea officia. Voluptatum rerum expedita ipsam dolor quia.
    b : float
        Molestiae aliquid libero. Dolores voluptate eveniet. Voluptas expedita rem doloribus
        possimus perferendis non molestiae.
    """
```

![image](https://user-images.githubusercontent.com/57204023/197082521-5049104a-6fd6-4a2c-b016-4d32d569d4ea.png)

**Comment by Keyacom** [comment] 2023-06-25 09:44
I am annoyed by the fact this never actually supported the basic syntax for \*\***bold text**\*\* or \**italic text*\*. Both `*` and `_` should be supported.

![image](https://github.com/microsoft/pylance-release/assets/70766223/1a6e25dd-6451-4e3d-ba6d-6e1ed4a7c59f)

Raw docstring content:

```md
Default YAWNS configuration. All security constants (like keys) are undefined.

All keys must be prefixed with `YAWNS_` because this is added to the Sanic
object's configuration, and it can conflict with some configuration of the
Sanic object.

**DO NOT EDIT THIS FILE**, because it *will* be overwritten on upgrade.
```

**Comment by heejaechang** [comment] 2024-02-20 19:26
make sure doc string builder can handle case listed here - https://github.com/microsoft/pylance-release/issues/5431 - as well.

https://github.com/apache/airflow/blame/07fe1d2a69cbe4f684a1989c047737c0686c4417/airflow/models/dag.py#L302

**Comment by rchiodo** [comment] 2024-05-29 17:52
This should be handled when we finish https://github.com/microsoft/pylance-release/issues/5363. Sphinx docstrings should at least be supported.

**Comment by rchiodo** [comment] 2024-06-05 23:24
Here's some examples of the coming changes.

PySimpleGui (which I believe the first screenshot was based on):


![Image](https://github.com/microsoft/pylance-release/assets/19672699/62867722-aafe-474f-88c0-d71976a543b2)

Tables



![Image](https://github.com/microsoft/pylance-release/assets/19672699/d19eaf7d-5946-4a99-bb9d-fd107d4b125a)

Emphasis problems:



![Image](https://github.com/microsoft/pylance-release/assets/19672699/81bcc813-70e2-4a93-904e-53a5a134af02)

Airflow (the example @heejaechang linked to)



![Image](https://github.com/microsoft/pylance-release/assets/19672699/b804fa70-3f38-42fd-aff9-9e5468c45d4b)

I wish we could output html in the markdown but VS code is very limited there, so mostly we're just using indents/italics/bolding to highligh different sections.

For example that same function in the actual generated Airflow documentation looks like so:



![Image](https://github.com/microsoft/pylance-release/assets/19672699/e848d113-3fae-44db-9ee4-91a56a4f7caa)

**Comment by rchiodo** [comment] 2024-06-14 00:27
This issue has been fixed in prerelease version 2024.6.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246100-13-June-2024-PreRelease)

**Closed by rchiodo** 2024-06-14 00:27 UTC
Labels: bug, enhancement, fixed in next version (main), docstrings

**Comment by rchiodo** [comment] 2024-06-14 00:38
The fix for this issue is behind an experimental feature flag:

```json
"python.analysis.supportRestructuredText": true
```

If you want to try out our new restructuredText support, enable this flag. It's behind a flag at the moment until we can make sure it handles all the possible Sphinx/GoogleDoc/Epytext scenarios that customers need. Please log additional issues if this setting isn't working out for you.

Thanks :)

**Comment by Diogo-Rossi** [comment] 2024-06-14 11:57
> The fix for this issue is behind an experimental feature flag:
> 
> ```json
> "python.analysis.supportRestructuredText": true
> ```
> 
> If you want to try out our new restructuredText support, enable this flag. It's behind a flag at the moment until we can make sure it handles all the possible Sphinx/GoogleDoc/Epytext scenarios that customers need. Please log additional issues if this setting isn't working out for you.
> 
> Thanks :)

Is not working for me.

Trying the same lib (PySimpleGUI):

![image](https://github.com/microsoft/pylance-release/assets/57204023/a3c326df-8ff9-4944-9f94-c6a32ff2c039)

**Comment by OmerFI** [comment] 2024-06-14 12:39
@Diogo-Rossi You should switch to the pre-release version of Pylance, it's working for me.

![resim](https://github.com/microsoft/pylance-release/assets/54645034/e55a388a-8257-4dbb-a169-cc9afada4b45)

Thanks @rchiodo for all your effort :)

**Comment by Diogo-Rossi** [comment] 2024-06-16 23:33
> @Diogo-Rossi You should switch to the pre-release version of Pylance, it's working for me.
> 
> ![resim](https://private-user-images.githubusercontent.com/54645034/339767310-e55a388a-8257-4dbb-a169-cc9afada4b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODA5NjQsIm5iZiI6MTcxODU4MDY2NCwicGF0aCI6Ii81NDY0NTAzNC8zMzk3NjczMTAtZTU1YTM4OGEtODI1Ny00ZGJiLWExNjktY2M5YWZhZGE0YjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDIzMzEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmY4ZjIxYzcxMjJmZmIxYmNkYzdiOTMwMDZlODAwNmY1ZTQzOTZlODdmMTUxY2Q0N2VkMDU5NzczZTU3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSk5xc7kQqVOhhJTCvDg5dYHam1qyH_98jVEZ_p4YxA)
> 
> Thanks @rchiodo for all your effort :)

Right! I missed the prerelease detail. I  thought that 2024.6.1 was the version mentioned.

It's working! Thank you @rchiodo for the feature!
