### ISSUE TITLE
Pylance reports problems in closed unavailable file.

### ISSUE THREAD

**Issue by agarrubio** [microsoft/pylance-release#4118] opened 2023-03-21 15:58 UTC
<h3> Environment data </h3>

-   Language Server version: 2023.3.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. Edit jupyter in vscode

<h3> Expected behavior </h3>

Error should not be reported if file is closed.

<h3> Actual behavior </h3>

Pylance reports problems in the 'Interactive-1.interactive' file, which is closed. Messages disapear with disable/enable Pylance. Is there another way?

<h3> Logs </h3>

```
XXX
```

**Comment by debonte** [comment] 2023-03-21 17:57
Duplicate of https://github.com/microsoft/pylance-release/issues/4113

**Closed by debonte** 2023-03-21 17:57 UTC
Labels: triage-needed
