### ISSUE TITLE
Pylance server crash: FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Boon-in-Oz** [microsoft/pylance-release#3498] opened 2022-10-18 22:11 UTC
<h3> Environment data </h3>

-   Language Server version: 2022.10.21
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

No code is executed. This happens on startup of VS Code.

<h3> Repro Steps </h3>

1. I'm not sure this is reproducible outside my own PC. I develop tools for 3D Studio Max and Maya, so I use Python from source control rather than installing it. I have a multi-root workspace with a few thousand files in it. 
2. I start VS Code using this workspace:
[main.code-workspace.txt](https://github.com/microsoft/pylance-release/files/9815395/main.code-workspace.txt)

<h3> Expected behavior </h3>

pylance continues to work normally

<h3> Actual behavior </h3>

A few minutes after startup, I get the message

> The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

<h3> Logs </h3>

The log is enormous so I saved to a file. Even so, with "python.analysis.logLevel": "Trace", it has been truncated:
[VSCode Pylance crash log (trace).txt](https://github.com/microsoft/pylance-release/files/9815399/VSCode.Pylance.crash.log.trace.txt)

With "python.analysis.logLevel": "Information", the log is not truncated and also includes a stacktrace:
[VSCode Pylance crash log (includes stack).txt](https://github.com/microsoft/pylance-release/files/9815407/VSCode.Pylance.crash.log.includes.stack.txt)

```
<--- Last few GCs --->

[115236:00005F3601820000]    26255 ms: Scavenge 549.6 (579.0) -> 543.8 (580.2) MB, 1.4 / 0.0 ms  (average mu = 0.981, current mu = 0.974) allocation failure; 
[115236:00005F3601820000]    26283 ms: Scavenge 550.8 (580.2) -> 544.8 (581.7) MB, 1.7 / 0.0 ms  (average mu = 0.981, current mu = 0.974) allocation failure; 
[115236:00005F3601820000]    26308 ms: Scavenge 552.9 (582.5) -> 546.8 (583.2) MB, 2.9 / 0.0 ms  (average mu = 0.981, current mu = 0.974) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 00007FF7EB66F5A6 node::Buffer::New+50054
 2: 00007FF7EB66F7AF node::OnFatalError+463
 3: 00007FF7EDF87AEA v8::Data::IsFixedArray+1002
 4: 00007FF7EDF87A06 v8::Data::IsFixedArray+774
 5: 00007FF7EE035B73 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+55299
 6: 00007FF7EA5E163D v8::CppHeap::GetAllocationHandle+176397
 7: 00007FF7EA5DD534 v8::CppHeap::GetAllocationHandle+159748
 8: 00007FF7EA5CD683 v8::CppHeap::GetAllocationHandle+94547
 9: 00007FF7EA5CB38C v8::CppHeap::GetAllocationHandle+85596
10: 00007FF7EA5C8686 v8::CppHeap::GetAllocationHandle+74070
11: 00007FF7ECC8D4AC v8::CppHeap::GetHeapHandle+69292
12: 00007FF7ECC7F11C v8::CppHeap::GetHeapHandle+11036
13: 00007FF7EA6B64CB v8::internal::OSROptimizedCodeCache::TryGet+187675
14: 00007FF76FECC93C 
[Error - 8:58:02 am] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

**Comment by luabud** [comment] 2022-10-19 17:58
Thanks for the report, is there a code sample with repro steps you can share with us so we can investigate?
You can also try setting `python.analysis.indexing: false` and `python.analysis.diagnosticMode: openFilesOnly` in your settings.json (View > Command Palette... and run "Preferences: Open User Settings (JSON)").

**Comment by Boon-in-Oz** [comment] 2022-10-21 06:21
I've tried a bunch of stuff and so far I can't repro this without using my actual workspace.

The crash seems to be caused by a combination of things. At one point (after removing a lot of folders from the workspace) I could make it happen simply by renaming that first (empty) directory from "hack_get_extraPaths_to_work" to "_hack_empty". I can't make that happen again now though.

Removing any one of the largest folders ("maya", "techart" or "dcc", with 17k, 33k and 7k files respectively) from the workspace prevents the crash. 

The "maya" folder contains some enormous Python files: four are 1MB-5MB and contain just numbers in a few huge lists; others are almost 20k lines of Python. Deleting the four files containing the huge lists from my drive also prevents the crash.

Unfortunately none of the above solutions are actually viable for me.

Regarding your suggestions: setting `"python.analysis.indexing": false` in my workspace settings prevents the crash and will probably be my workaround. Leaving indexing on, and setting `"python.analysis.diagnosticMode": "openFilesOnly"` in my workspace does not help.

Sorry I can't give you anything better to go on. I know that probably makes this impractical to fix.

**Comment by luabud** [comment] 2022-10-24 22:57
Thanks for the info! I'll leave this issue open in case more people bump into it and can provide more info to help with diagnosing this. Glad to know the workaround of setting `"python.analysis.indexing": false` at least works for now, but hopefully we'll be able to figure out what's going on and provide a proper fix at some point :) 

cc @heejaechang

**Comment by erictraut** [comment] 2022-10-24 23:06
I added a fix a couple of weeks ago for out-of-memory conditions that can occur with large projects that use multi-root workspaces. Here's the [issue](https://github.com/microsoft/pylance-release/issues/3408). That fix should prevent this from happening. The fix will be in this week's release of pylance. It's already in the insiders release today, so if you want to try it now you could switch to that build.

If you're still able to repro the problem with the new release, we could use some verbose logging information. To do so, please create a `pyrightconfig.json` file in your project's root directory and add the following to this file:

```json
{
    "verboseOutput": true
}
```

Then reload your project and reproduce the out-of-memory condition. The output should now include more details. Look for lines in the output logs that start with "Heap stats: ". Please provide the last few of these heap stat outputs prior to the crash.

**Comment by Boon-in-Oz** [comment] 2022-10-25 21:51
That issue says it was fixed in 2022.10.11. I am on the prerelease channel for Pylance so I have 2022.10.31 already. The issue is still occurring.

I've created `pyrightconfig.json` in the same directory as my .code-workspace with the three lines you specified, and opened the workspace again. I didn't see any "Heap stats" in my log, so I set "python.analysis.logLevel": "Trace" and tried again. Now there are thousands and the last few are in a group several thousand lines above the last crash. Here they are:
> (151696) [BG(10)] binding: c:\project\game\bin\lang\techart\packages-py37\cv.py (0ms)
> (151696) [BG(10)] indexing: c:\project\game\bin\lang\techart\packages-py37\cv.py [found 0] (0ms)
> (151696) Indexing Done: c:\project\game\bin\lang\techart\packages-py37\cv.py
> [Info  - 8:39:13 am] (151696) Heap stats: total_heap_size=749MB, used_heap_size=708MB, total_physical_size=749MB, total_available_size=3363MB, heap_size_limit=4096MB
> (151696) [BG(10)] parsing: c:\project\game\bin\lang\techart\packages-py37\cycler.py [fs read 0ms] (2ms)
> (151696) [BG(10)] binding: c:\project\game\bin\lang\techart\packages-py37\cycler.py (0ms)
> (151696) [BG(10)] indexing: c:\project\game\bin\lang\techart\packages-py37\cycler.py [found 6] (1ms)
> (151696) Indexing Done: c:\project\game\bin\lang\techart\packages-py37\cycler.py
> [Info  - 8:39:13 am] (151696) Heap stats: total_heap_size=749MB, used_heap_size=710MB, total_physical_size=749MB, total_available_size=3362MB, heap_size_limit=4096MB
> (151696) [BG(10)] parsing: c:\project\game\bin\lang\techart\packages-py37\decorator.py [fs read 0ms] (7ms)
> (151696) [BG(10)] binding: c:\project\game\bin\lang\techart\packages-py37\decorator.py (1ms)
> (151696) [BG(10)] indexing: c:\project\game\bin\lang\techart\packages-py37\decorator.py [found 14] (0ms)
> (151696) Indexing Done: c:\project\game\bin\lang\techart\packages-py37\decorator.py
> [Info  - 8:39:13 am] (151696) Heap stats: total_heap_size=751MB, used_heap_size=705MB, total_physical_size=751MB, total_available_size=3366MB, heap_size_limit=4096MB
> (151696) [BG(10)] parsing: c:\project\game\bin\lang\techart\packages-py37\dot_parser.py [fs read 0ms] (5ms)
> (151696) [BG(10)] binding: c:\project\game\bin\lang\techart\packages-py37\dot_parser.py (1ms)
> (151696) [BG(10)] indexing: c:\project\game\bin\lang\techart\packages-py37\dot_parser.py [found 22] (0ms)
> (151696) Indexing Done: c:\project\game\bin\lang\techart\packages-py37\dot_parser.py
> [Info  - 8:39:13 am] (151696) Heap stats: total_heap_size=751MB, used_heap_size=707MB, total_physical_size=751MB, total_available_size=3364MB, heap_size_limit=4096MB
> (151696) [BG(10)] parsing: c:\project\game\bin\lang\techart\packages-py37\entrypoints.py [fs read 1ms] (2ms)
> (151696) [BG(10)] binding: c:\project\game\bin\lang\techart\packages-py37\entrypoints.py (0ms)
> (151696) [BG(10)] indexing: c:\project\game\bin\lang\techart\packages-py37\entrypoints.py [found 12] (0ms)
> (151696) Indexing Done: c:\project\game\bin\lang\techart\packages-py37\entrypoints.py
> [Info  - 8:39:13 am] (151696) Heap stats: total_heap_size=751MB, used_heap_size=708MB, total_physical_size=751MB, total_available_size=3363MB, heap_size_limit=4096MB

**Comment by rchiodo** [comment] 2022-11-11 00:37
Without a repro this one is going to be hard to diagnose.

**Comment by judej** [comment] 2022-11-14 18:50
Closing since we can't repro.

**Closed by judej** 2022-11-14 18:50 UTC
Labels: triage-needed
