### ISSUE TITLE
pylance not shown in python language server

### ISSUE THREAD

**Issue by carica** [microsoft/pylance-release#198] opened 2020-08-04 12:22 UTC
## Expected behaviour

use pylance as the language server

## Actual behaviour

![image](https://user-images.githubusercontent.com/4182063/89293062-e6426600-d68f-11ea-87c6-d09758c45db2.png)

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by jakebailey** [comment] 2020-08-04 16:40
Duplicate of #16, will be fixed in the next Python extension release.

**Closed by jakebailey** 2020-08-04 16:40 UTC
Labels: triage

**Comment by carica** [comment] 2020-08-05 11:54
> Duplicate of #16, will be fixed in the next Python extension release.

No it is not. The popup window didn't show up. Nothing happened after installation of pylance.

**Comment by jakebailey** [comment] 2020-08-05 17:32
The Python extension has not done this month's release (slated for a week or two from now). If you want to see the UI ahead of time, you can run their insiders build. #16 isn't closed yet either, but I mentioned the timeframe here for completeness.
