### ISSUE TITLE
pylance giving wrong type isssue

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [microsoft/pylance-release#501] opened 2020-10-19 05:38 UTC
Issue Type: <b>Bug</b>

import numpy as np
for i in np.random.rand(10):
    print(i)
pylance reporting:
"rand" is not a known member of modulePylance (reportGeneralTypeIssues)

Extension version: 2020.10.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.63GB free)|
|Process Argv|--crash-reporter-id e154b062-c64b-4aa8-8867-3638ddc17c20|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment] 2020-10-19 17:47
Duplicate of #150. Should be improved once numpy releases with their stubs.

**Closed by jakebailey** 2020-10-19 17:47 UTC
Labels: triage
