### ISSUE TITLE
Typechecking fails for some numpy functions

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#617] opened 2020-11-17 18:43 UTC
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9

## Expected behaviour

Correctly handle numpy typechecking

## Actual behaviour

Assuming the following code:
```
import numpy as np
res = np.full_like(arr1, np.nan)
res[i] = np.max(arr2)
```

Pylance complains:
```
"__setitem__" method not defined on type "Tuple[Unknown]"
```

This seems to be caused by a mis-interpretation of the numpy source code which contains the idiom `return (a, )` but in fact somehow returns a numpy ndarray object, not a tuple as understood by Pylance. The modified return type could be because of the operation of the decorator of the relevant function.

See numpy code [here](https://github.com/numpy/numpy/blob/5da4a8e1835a11d5a03b715e9c0afe3bb96c883b/numpy/core/numeric.py#L357) and [here](https://github.com/numpy/numpy/blob/5da4a8e1835a11d5a03b715e9c0afe3bb96c883b/numpy/core/multiarray.py#L140)

**Comment by jakebailey** [comment] 2020-11-17 18:46
Duplicate of #150. Numpy isn't typed, so it's a bit of a difficult time to try and work on.

**Closed by jakebailey** 2020-11-17 18:46 UTC
Labels: triage
