### ISSUE TITLE
Cannot assign to an attribute that has been bound to None

### ISSUE THREAD

**Issue by gmos** [microsoft/pylance-release#666] opened 2020-12-02 13:45 UTC
## Environment data
-   Language Server version: v2020.11.2
-   OS and version:  Linux 4.4.0-19041-Microsoft on wsl-1
-   Python version: 3.7.7

## Expected behaviour
Assingment to y.q and y.r in the snippet below  should not raise an error.
## Actual behaviour
Pylance v2020.11.2 raises: **Cannot assign to "None"** 
## Code Snippet / Additional information
```python
x = None
x = 33
# As expected no error. Can assign to x.


class TT:
    p = 1
    q = None

    def __init__(self):
        self.r = None


y = TT()
y.p = 1
y.q = 1
y.r = 1

# For the assignment to y.q and y.r  pylance v2020.11.2 raises:
#       Cannot assign to "None" Pylance(reportGeneralTypeIssues)
# Would expect no error.
```

**Comment by erictraut** [comment] 2020-12-02 16:30
This is the intended behavior. The type of the class variables `q` and `r` are not declared via a type annotation, so their types are inferred based on how they are assigned within the class. In your example, they are assigned only values of `None`, so that is its inferred type. You are then attempting to assign it a value outside of the class, and that type doesn't match its inferred type.

If you don't want type checking errors, you can set the typeCheckingMode to "off". If you want type checking, there are cases where the addition of type annotations will be required. This is one such case.

```python
class TT:
    q: Optional[int] = None
```

Or if you're using a version of Python older than 3.6:

```python
class TT:
   q = None # type: Optional[int]
```

**Comment by erictraut** [comment] 2020-12-02 16:31
For more information about type declarations and type inference, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md).

**Comment by gvanrossum** [comment] 2020-12-02 17:41
Hallo Gijs! Leuk nog eens van je te horen (ik ben je nog een email tegoed :-).

Seriously, this is indeed intended behavior; the types are inferred from the initializations. It's no different than writing
```py
class C:
    a: int

c = C()
c.a = "abc"  # Error
```

**Closed by gvanrossum** 2020-12-02 17:41 UTC
Labels: triage

**Comment by gmos** [comment] 2020-12-02 19:05
Dus nu mailen we via Github Guido 😉.

Understood, but then the behavior is perhaps inconsistent.  In a module I can do:
```python
X = None
X = 1
```
without complaints.

Since I’m mainly working in MicroPython couldn’t use variable type hints and had to rely on inference. Fortunately they have fixed that last month’s release.

**Comment by gvanrossum** [comment] 2020-12-02 19:11
The example with `x = None; x = 42` is different because this is treated as overwriting a variable in the same scope. When the definition is inside a class, the type is finalized when the class body is finished.

**Comment by JeffHanna** [comment] 2021-02-08 17:04
If you declare a @property and a @setter for your class attribute you can define the class attribute as None and not generate the PyLance "Cannot assign to None" error you are encountering.
