### ISSUE TITLE
Allow custom definition of auto-import completions? 

### ISSUE THREAD

**Issue by bzm3r** [microsoft/pylance-release#6242] opened 2024-08-07 20:20 UTC
See this StackOverflow question: https://stackoverflow.com/questions/78845297/how-do-define-custom-auto-imports-for-pylance-visual-studio-code

Where the answer determined that currently Pylance has the following auto-import completions hardcoded:

* `np` for `numpy`
* `pd` for `pandas`
* `tf` for `tensorflow`
* `plt` for `pyplot`/`matplotlib`
* `mpl` for `matplotlib`
* `m` for `math`
* `spio` for `io`/`scipy`
* `sp` for `scipy`
* `pn` for `panel`
* `hv` for `holoviews`

Can we allow definition of custom auto-import triggers? For example, `pl` for `polars`?

**Comment by debonte** [comment] 2024-08-07 20:34
I know we've discussed this before, but I don't recall the decision and can't find an existing issue on this.

Reassigning to HeeJae who may know.

**Comment by heejaechang** [comment] 2024-08-07 21:00
@luabud should expose it as option?

**Comment by luabud** [comment] 2024-08-07 21:37
I believe this is a dupe of https://github.com/microsoft/pylance-release/discussions/2589? We currently only have 4 upvotes there

**Comment by debonte** [comment] 2024-08-08 00:46
Resolving as a duplicate. @bzm3r, please upvote https://github.com/microsoft/pylance-release/discussions/2589 if you haven't already.

**Closed by debonte** 2024-08-08 00:46 UTC
Labels: enhancement
