### ISSUE TITLE
PyLance not recognizing importing file with .pyw extension

### ISSUE THREAD

**Issue by Tosh0kan** [microsoft/pylance-release#4000] opened 2023-02-23 22:53 UTC
## Environment data

-   Language Server version: v2023.1.10
-   OS and version: Win 10 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0, regular distribution
-  Virtual environment used is the venv that comes with Python.
-  Requirements are:
>altgraph==0.17.3
anyio==3.6.2
auto-py-to-exe==2.28.0
beautifulsoup4==4.11.2
bottle==0.12.23
bottle-websocket==0.2.9
bs4==0.0.1
certifi==2022.12.7
cffi==1.15.1
Eel==0.14.0
future==0.18.3
gevent==22.10.2
gevent-websocket==0.10.1
greenlet==2.0.2
h11==0.14.0
httpcore==0.16.3
httpx==0.23.3
idna==3.4
Jinja2==3.1.2
lxml==4.9.2
MarkupSafe==2.1.2
packaging==23.0
pefile==2022.5.30
pycodestyle==2.10.0
pycparser==2.21
pyinstaller==5.7.0
pyinstaller-hooks-contrib==2022.15
pyinstaller-versionfile==2.1.1
pyparsing==3.0.9
pytz==2022.7.1
pywin32-ctypes==0.2.0
PyYAML==6.0
rfc3986==1.5.0
sniffio==1.3.0
soupsieve==2.3.2.post1
whichcraft==0.6.1
winotify==1.1.0
zope.event==4.6
zope.interface==5.5.2

## Code Snippet

```python
import sonar 

sonar.Guncs.toaster('test', 'test', 'test', 'test')
```

## Repro Steps

1. Have a file named `sonar.pyw` in the same folder as file `__init__.py`. File `__init__.py` contains the snippet detailed above
2. Inside `sonar.pyw`, have the following code in it:
```py
from winotify import Notification
from time import sleep

class Guncs:
    @staticmethod
        def toaster(series_title: str, ch_no: str, ch_title: str, ch_id: str) -> None:

            toast = Notification(
                app_id="MangaDex Feed",
                title=series_title,
                msg=f"Ch. {ch_no}: {ch_title}",
                launch=f"https://www.mangadex.org/chapter/{ch_id}"
            )
            toast.show()
            sleep(0.5)
```

## Expected behavior

PyLance recognizes the imported `sonar.pyw` file.

## Actual behavior

It doesn't recognize it, and it throw the following error:

> Import "sonar" could not be resolved Pylance(reportMissingImport) [Ln 1 Col 8]

## Fix Attempts

I already tried using the measure included in known issues. In my case, I added the following option in `settings.json`:
```json
"python.analysis.extraPaths": ["."],
```
 but it didn't work.

## Logs

```
Telemetry level is off
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
[ERROR 2023-1-23 19:34:57.310]: readdir() failed for "C:\Program Files (x86)\geckodriver.exe" (Error: ENOTDIR: not a directory, scandir 'C:\Program Files (x86)\geckodriver.exe')
[ERROR 2023-1-23 19:34:57.315]: readdir() failed for "C:\Program Files (x86)\geckodriver.exe" (Error: ENOTDIR: not a directory, scandir 'C:\Program Files (x86)\geckodriver.exe')
> conda info --json
Caminho do interpretador Python: .\venv\Scripts\python.exe
> "d:/01 Libraries/Documents/Coding/MangaDex Feed Notifier/venv/Scripts/activate.bat" && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/printEnvVariables.py
> ~\AppData\Local\Programs\Python\Python311\python.exe ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
> C:\msys64\mingw64\bin\python.exe ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
> "d:\01 Libraries\Documents\Coding\MangaDex Feed Notifier\venv\Scripts\python.exe" ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
> C:\Python310\python.exe ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
[ERROR 2023-1-23 19:35:3.98]: [Error: Command failed: C:\Python310\python.exe c:\Users\igor\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py c:\Users\igor\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
O sistema nao pode encontrar o caminho especificado.

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Python310\\python.exe c:\\Users\\igor\\.vscode\\extensions\\ms-python.python-2022.16.1\\pythonFiles\\get_output_via_markers.py c:\\Users\\igor\\.vscode\\extensions\\ms-python.python-2022.16.1\\pythonFiles\\interpreterInfo.py'
}
> ~\AppData\Local\Programs\Python\Python39\python.exe ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
[ERROR 2023-1-23 19:35:3.241]: [Error: Command failed: C:\Users\igor\AppData\Local\Programs\Python\Python39\python.exe c:\Users\igor\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\get_output_via_markers.py c:\Users\igor\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\interpreterInfo.py
'C:\Users\igor\AppData\Local\Programs\Python\Python39\python.exe' nao � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\igor\\AppData\\Local\\Programs\\Python\\Python39\\python.exe c:\\Users\\igor\\.vscode\\extensions\\ms-python.python-2022.16.1\\pythonFiles\\get_output_via_markers.py c:\\Users\\igor\\.vscode\\extensions\\ms-python.python-2022.16.1\\pythonFiles\\interpreterInfo.py'
}
Iniciando servidor de idiomas Pylance.
> "d:\01 Libraries\Documents\Coding\MangaDex Feed Notifier\venv\Scripts\python.exe" ~\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\linter.py -m pycodestyle "--ignore=E501, E115" "d:\01 Libraries\Documents\Coding\MangaDex Feed Notifier\__init__.py"
cwd: d:\01 Libraries\Documents\Coding\MangaDex Feed Notifier
##########Linting Output - pycodestyle##########
```

**Comment by erictraut** [comment] 2023-02-23 22:56
This is a duplicate of https://github.com/microsoft/pylance-release/issues/639.

**Comment by Tosh0kan** [comment] 2023-02-23 23:01
So this issue still haven't been resolved?

**Closed** 2023-02-23 23:05 UTC
Labels: triage-needed

**Comment by Tosh0kan** [comment] 2023-02-23 23:06
I guess this answer my question that no, it still hasn't been solved lol

**Comment by erictraut** [comment] 2023-02-23 23:07
If you want this to be prioritized, please upvote the original issue.
