### ISSUE TITLE
Syntax highlighting not working after VSCode update

### ISSUE THREAD

**Issue by HighwayChile** [microsoft/pylance-release#4490] opened 2023-06-10 00:41 UTC
Type: <b>Bug</b>

Python extension for VSCode, v2023.10.0, after update today most of the syntax highlighting does not work. Docstrings are the same color as comments, and functions, classes, and variables do not highlight. This is making writing code very difficult. Please help. email: slickdick101@gmail.com
My OS is Windows 10 Pro, VSCode 1.79.0. 

Extension version: 2023.10.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.81GB free)|
|Process Argv|--crash-reporter-id 4b8cf8a6-8f3e-47e5-ab7d-bf0946860ba0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosmt12:30757131

```

</details>

**Comment by rchiodo** [comment] 2023-06-12 17:18
Thanks for the issue.

This is a dupe of https://github.com/microsoft/pylance-release/issues/4429. Please upvote/respond in that issue.

**Closed by rchiodo** 2023-06-12 17:18 UTC
Labels: triage-needed

**Comment by rchiodo** [comment] 2023-06-12 17:41
The docstrings as comments was a change made by VS code here:
https://github.com/microsoft/vscode/commit/b4368691e928191228076c0c329d815972e07fe1

I don't know the reasons behind it, but it was on purpose.

**Comment by rchiodo** [comment] 2023-06-12 17:42
The PR was here: https://github.com/microsoft/vscode/pull/182162.

**Comment by lkct** [comment] 2023-06-12 18:17
I opened an issue summarizing where we are: microsoft/vscode#184836
Now I'm proposing to revert this change: microsoft/vscode#184938
